Implement XMLHttpRequest.send(Document)
servo/servo pull request #10604
Opened 2016-04-14 12:19 UTC by jaysonsantos

If you guys need a rebase just tell me and I do it.
When serializing document I am using unwrap, should I change `extracted` return to be a result?
Fixes #9490

2016-04-14 12:19 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @wafflespeanut (or someone else) soon.

2016-04-14 12:19 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/document.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/webidls/XMLHttpRequest.webidl

2016-04-14 12:37 UTC, KiChjang commented
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/dom/document.rs, line 1823 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJjeZX8yuTl-bGxB0u:-KFJjeZX8yuTl-bGxB0v:-4709022) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/document.rs#L1823)):*
Since this method already returns a `Fallible`, we don't need a match statement and panic in the Err arm. Instead, an `if let` would do the job just fine.

---

*[components/script/dom/xmlhttprequest.rs, line 533 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkRhawzgGy22tUIlb:-KFJkRhawzgGy22tUIlc:-694749777) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/xmlhttprequest.rs#L533)):*
Were you not able to use `DocumentOrBodyInit`?

---

*[components/script/dom/xmlhttprequest.rs, line 1442 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJl-PlrnHNpSiilHSL:-KFJl-PlrnHNpSiilHSM:1275654086) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/xmlhttprequest.rs#L1442)):*
Use the `mime!` macro to generate Content-Type headers.

---

*[components/script/dom/webidls/XMLHttpRequest.webidl, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkXlSd1ue4bV0N4th:-KFJkXlSd1ue4bV0N4ti:-2065304861) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/webidls/XMLHttpRequest.webidl#L58)):*
This is a pretty bad sign if we have to deviate from the WebIDL spec def in order to support XHR.send.

---

*[tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkn874TqZdjed_Yxx:-KFJkn88dDRQ3DDky1nq:621374487) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm#L21)):*
Does the test still pass without your changes here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604#-:-KFJl6AQYWc-UFdH6VUa:1458266033)*
<!-- Sent from Reviewable.io -->

2016-04-14 12:47 UTC, jaysonsantos commented
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/dom/xmlhttprequest.rs, line 533 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkRhawzgGy22tUIlb:-KFJm_ZLl9izkD-3sOC_:339330022) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/xmlhttprequest.rs#L533)):*
When I generate the data it will always generate DocumentOrBlobOrStringOrURLSearchParams even doing `(Document or BodyInit)` and it will not generate the BodyInit on the beginning of the file.

---

*[components/script/dom/webidls/XMLHttpRequest.webidl, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkXlSd1ue4bV0N4th:-KFJnQD48ExRBqxZl_KX:-1315196273) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/webidls/XMLHttpRequest.webidl#L58)):*
As I said before if I try to use `(Document or BodyInit)?` it will generate a `DocumentOrBlobOrStringOUrlSearchParam` and will not generate the `BodyInit`, I can paste the error here if you want.

---

*[tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkn874TqZdjed_Yxx:-KFJnHUwa5Q_qpm_esI8:-1748913210) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm#L21)):*
No, the serializer always put a `\n` after `<!DOCTYPE html>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 13:05 UTC, KiChjang commented
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webidls/XMLHttpRequest.webidl, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkXlSd1ue4bV0N4th:-KFJrf-1UKaYIQ9cj7nO:-1606098663) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/webidls/XMLHttpRequest.webidl#L58)):*
This is a bug. Filed #10605. For now, we should revert these (i.e. use `Document or BodyInit`) and uncomment the typedef up in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 13:25 UTC, jaysonsantos commented
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/dom/document.rs, line 1823 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJjeZX8yuTl-bGxB0u:-KFJpOgHll-cCJWparD7:-474389316) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/document.rs#L1823)):*
Do you mean something like this?
```rust
if let Ok(()) = serialize(&mut writer, &self.upcast::<Node>(),
    SerializeOpts {traversal_scope: ChildrenOnly,..Default::default()}) {
    Ok(DOMString::from(String::from_utf8(writer).unwrap()))
} else {
    Err(Error::InvalidState)
}
```

---

*[components/script/dom/xmlhttprequest.rs, line 1442 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJl-PlrnHNpSiilHSL:-KFJwTXd2LaxZNru2yoS:-1955630011) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/xmlhttprequest.rs#L1442)):*
To use that macro I will have to add mime on lib.rs and cargo.toml, is that ok?

---

*[components/script/dom/webidls/XMLHttpRequest.webidl, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkXlSd1ue4bV0N4th:-KFJwLR-81uQnJDXu4P0:-2103050201) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/webidls/XMLHttpRequest.webidl#L58)):*
So, this PR wait it then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 13:32 UTC, KiChjang commented
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/document.rs, line 1823 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJjeZX8yuTl-bGxB0u:-KFJxXO7wYtwmONth4lQ:677251276) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/document.rs#L1823)):*
Yes.

---

*[components/script/dom/xmlhttprequest.rs, line 1442 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJl-PlrnHNpSiilHSL:-KFJxZJnuGyxeojUfURU:677251276) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/xmlhttprequest.rs#L1442)):*
Yes.

---

*[components/script/dom/webidls/XMLHttpRequest.webidl, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkXlSd1ue4bV0N4th:-KFJx_Vn9ugUV285r2aH:1801121505) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/webidls/XMLHttpRequest.webidl#L58)):*
Not necessarily. We can still use `BodyInit`, and in the Rust code where `BodyInit` is referenced, use `BlobOrDOMStringOrURLSearchParams` instead.

---

*[tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkn874TqZdjed_Yxx:-KFJxriTxAhslp44nbzw:-220026248) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm#L21)):*
That also looks undesirable. FWIW there's a discussion about this in a WPT PR [here](https://github.com/w3c/web-platform-tests/pull/2667#issuecomment-196728740). If possible, I'd like to make changes to the serializer instead (it is located at servo/html5ever).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 13:52 UTC, jaysonsantos commented
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/webidls/XMLHttpRequest.webidl, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkXlSd1ue4bV0N4th:-KFK1ISuJYLJU2-GXfxg:-1760480609) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/webidls/XMLHttpRequest.webidl#L58)):*
If I try to do it, this will happen:
```
   Compiling script v0.0.1 (file:///home/jayson/src/servo/components/script)
/home/jayson/src/servo/target/debug/build/script-2a4d8b76db936b97/out/Bindings/XMLHttpRequestBinding.rs:133:9: 133:86 error: unresolved import `dom::bindings::codegen::UnionTypes::BlobOrStringOrURLSearchParams`. There is no `BlobOrStringOrURLSearchParams` in `dom::bindings::codegen::UnionTypes`. Did you mean to use `USVStringOrURLSearchParams`? [E0432]
/home/jayson/src/servo/target/debug/build/script-2a4d8b76db936b97/out/Bindings/XMLHttpRequestBinding.rs:133 pub use dom::bindings::codegen::UnionTypes::BlobOrStringOrURLSearchParams as BodyInit;
                                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jayson/src/servo/components/script/dom/bindings/mod.rs:160:9: 160:64 note: in this expansion of include!
/home/jayson/src/servo/target/debug/build/script-2a4d8b76db936b97/out/Bindings/XMLHttpRequestBinding.rs:133:9: 133:86 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to previous error
error: Could not compile `script`.

To learn more, run the command again with --verbose.
Build completed in 90.63s
```

---

*[tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkn874TqZdjed_Yxx:-KFK1Nc7IqcwXgRRdlky:1692211433) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm#L21)):*
Should I try to change it on this PR or open an issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 14:44 UTC, KiChjang commented
-S-awaiting-review +S-needs-code-changes +S-blocked-on-external 

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/xmlhttprequest.rs, line 1447 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFKB8Iy79W4z4cBLXph:-KFKB8Iz8ojOp5W7sEJI:1515046907) ([raw file](https://github.com/servo/servo/blob/152807b957e3ac0ecbe662e5229bcaec45a438ff/components/script/dom/xmlhttprequest.rs#L1447)):*
Does `content_type.to_string()` not work?

---

*[components/script/dom/webidls/XMLHttpRequest.webidl, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkXlSd1ue4bV0N4th:-KFKC6Qq6nBjoy2NBi3F:2108130972) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/webidls/XMLHttpRequest.webidl#L58)):*
Ugh, it looks like the `BlobOrDOMStringOrURLSearchParams` union type is completely forgotten and `DocumentOrDOMStringOrURLSearchParams` supersedes it. Looks like this PR will be blocked until this is fixed.

---

*[tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJkn874TqZdjed_Yxx:-KFKCdfeFuGozrsk274j:-1942466902) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm#L21)):*
You'll need to change it in servo/html5ever either way. This PR is not capable of making changes under that repo. For now, remove this extra \n and mark the test as a failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604#-:-KFKDbz-zHn927SKlESn:155397596)*
<!-- Sent from Reviewable.io -->

2016-04-14 14:50 UTC, jaysonsantos commented
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/xmlhttprequest.rs, line 1447 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFKB8Iy79W4z4cBLXph:-KFKElmYCvzVqHMFkxfu:-908405862) ([raw file](https://github.com/servo/servo/blob/152807b957e3ac0ecbe662e5229bcaec45a438ff/components/script/dom/xmlhttprequest.rs#L1447)):*
I didn't find any `to_string` on https://doc.servo.org/mime/struct.Mime.html did I miss something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 14:55 UTC, jaysonsantos commented
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/xmlhttprequest.rs, line 1447 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFKB8Iy79W4z4cBLXph:-KFKG6coVKM2zHB8S4zP:1027377400) ([raw file](https://github.com/servo/servo/blob/152807b957e3ac0ecbe662e5229bcaec45a438ff/components/script/dom/xmlhttprequest.rs#L1447)):*
Ah sorry, I didn't pay attention it uses AsRef

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 15:09 UTC, jaysonsantos commented
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/xmlhttprequest.rs, line 1447 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFKB8Iy79W4z4cBLXph:-KFKJS4jDN0ntV2CVagw:-1751022136) ([raw file](https://github.com/servo/servo/blob/152807b957e3ac0ecbe662e5229bcaec45a438ff/components/script/dom/xmlhttprequest.rs#L1447)):*
implements s/AsRef/Display/*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 20:26 UTC, KiChjang commented
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm, line 21 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFLRXrxgJWYtxuI1RjV:-KFLRXrxgJWYtxuI1RjW:2140161409) ([raw file](https://github.com/servo/servo/blob/1d06bfbd01d1ff2e04ff854f98f90200c430439c/tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm#L21)):*
I'm not very comfortable with changing the testfiles just to make our test cases pass; these tests are also used by other browsers, so if there's a problem with parsing in Rust, contact the mime crate author (@seanmonstar) instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 20:32 UTC, jaysonsantos commented
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm, line 21 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFLRXrxgJWYtxuI1RjV:-KFLT9cSPM6-markGTZ_:482144171) ([raw file](https://github.com/servo/servo/blob/1d06bfbd01d1ff2e04ff854f98f90200c430439c/tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm#L21)):*
Got it, I didn't know about this. I just opened this issue to talk about it https://github.com/hyperium/mime.rs/issues/41
I will revert it. If the pr get's accepted I will rebase to make the merge cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604)*
<!-- Sent from Reviewable.io -->

2016-04-14 21:13 UTC, seanmonstar commented
@KiChjang the tests are incorrect. The spec shows OWS as well as the charset value being case-insensitive. Examples are also included: https://tools.ietf.org/html/rfc7231#section-3.1.1.1

2016-04-14 21:24 UTC, KiChjang commented
@seanmonstar There's a previous discussion about this in w3c [here](https://github.com/w3c/web-platform-tests/pull/2667#issuecomment-196728740). They are saying that if the client did not specify OWS character, then the UAs should not normalize it by adding any OWS at all. (I also have a PR [here](https://github.com/w3c/web-platform-tests/pull/2807#issuecomment-208938912) that has the same reply)

2016-04-15 01:58 UTC, KiChjang commented
-S-blocked-on-external +S-needs-code-changes 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[components/script/dom/xmlhttprequest.rs, line 1442 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10604#-KFJl-PlrnHNpSiilHSL:-KFMchbDkeVWBoAYmriK:-744134164) ([raw file](https://github.com/servo/servo/blob/349081b2fb3754d027d9681063f580c97cb4c482/components/script/dom/xmlhttprequest.rs#L1442)):*
So we have a conclusion here - instead of using the mime crate, we'll have to actually generate the strings here, i.e. revert back to the previous revision where it is correct and passes the WPT test. Sorry about the back-and-forth changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10604#-:-KFMcPlc-PMhwVlnHDzF:1423438770)*
<!-- Sent from Reviewable.io -->

2016-04-15 13:45 UTC, KiChjang commented
Squash!

2016-04-15 15:21 UTC, jaysonsantos commented
Windows build is failing because of a lib named `tinyfiledialogs`, is that happening on master also?

2016-04-15 15:43 UTC, KiChjang commented
Don't worry too much about that; AppVeyor is occasionally freaking out at times.

Oh, and since your changes on html5ever has landed, I'll have to ask you to update html5ever and remove that test failure about the extra newline character. You can update it by running `./mach cargo-update -p html5ever`.

2016-04-15 16:06 UTC, jaysonsantos commented
@KiChjang I think that html5ever is not released on cargo yet.

2016-04-15 17:00 UTC, KiChjang commented
Now it is :). Released as version 0.5.4.

2016-04-15 17:03 UTC, KiChjang commented
This is still blocked on the issue of typedefs not appearing on union types, which should be addressed by #10615.

2016-04-15 18:35 UTC, jaysonsantos commented
```./mach cargo-update -p html5ever

components/servo
    Updating registry `https://github.com/rust-lang/crates.io-index`
ports/cef
    Updating registry `https://github.com/rust-lang/crates.io-index`
ports/geckolib
error: package id specification `html5ever` matched no packages
ports/gonk```
I found it inside some .toml, do I update it manually?

2016-04-15 20:26 UTC, jdm commented
No, that's perfectly fine. geckolib doesn't use html5ever.

2016-04-16 13:00 UTC, jaysonsantos commented
But after running the update code, a `git diff` does not show anything.

2016-04-16 13:25 UTC, jdm commented
I guess we need to run `./mach cargo-update -p html5ever --precise 0.5.4`.

2016-04-16 14:46 UTC, jaysonsantos commented
I also had to update tendril.

2016-04-20 18:25 UTC, jaysonsantos commented
@KiChjang Is there something missing on it yet?

2016-04-20 18:54 UTC, KiChjang commented
This is still dependent on #10615.

2016-04-20 19:07 UTC, jaysonsantos commented
Ah, right, I forgot about the tag blocked on external.

2016-04-23 19:42 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #9840) made this pull request unmergeable. Please resolve the merge conflicts.

2016-07-17 19:14 UTC, frewsxcv commented
This is now dependent on https://github.com/servo/servo/pull/12397 ?

2016-07-17 19:28 UTC, KiChjang commented
Correct.

2016-09-10 00:12 UTC, KiChjang commented
Once #13201 lands, I believe this is unblocked. @jaysonsantos are you going to work on this PR any more? If not, I can help you rebase and merge this. Thanks for the all the work!

2016-09-10 07:00 UTC, jaysonsantos commented
Hey, I will try to do it again.

On Sat, 10 Sep 2016, 02:13 Keith Yeung, <notifications@github.com> wrote:

> Once #13201 <https://github.com/servo/servo/pull/13201> lands, I believe
> this is unblocked. @jaysonsantos <https://github.com/jaysonsantos> are
> you going to work on this PR any more? If not, I can help you rebase and
> merge this. Thanks for the all the work!
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/servo/servo/pull/10604#issuecomment-246073035>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AADJNk4NNh4KEFNi-oOYH9s3RGjNyKUeks5qofYSgaJpZM4IHT3c>
> .
>

2016-09-15 20:14 UTC, jaysonsantos commented
Hey @KiChjang I've just rebased this because there were a lot of conflicts and I was trying to remember what I did.
From now on I will try to check the tests for xhr.send(DOcument)

2016-09-15 21:30 UTC, KiChjang commented on components/script/dom/webidls/XMLHttpRequest.webidl
> +  void send(optional (Document or Blob or DOMString or URLSearchParams)? data = null);
This is not necessary anymore. Using `Document or BodyInit` should work now.

2016-09-15 21:34 UTC, KiChjang commented on components/script/dom/xmlhttprequest.rs
> +                (data.get_bytes().to_vec(), content_type)
Looks like a rebasing error.

2016-09-15 21:34 UTC, KiChjang commented on components/script/dom/xmlhttprequest.rs
> +            BodyInit::Document(ref d) => {
I'm surprised if this code even compiled at all.

2016-09-15 21:45 UTC, KiChjang commented on components/script/dom/document.rs
> +            SerializeOpts { traversal_scope: ChildrenOnly, ..Default::default() }) {
Why `ChildrenOnly`?

2016-09-15 21:46 UTC, KiChjang commented on components/script/dom/document.rs
> +    pub fn serialize(&self) -> Fallible<DOMString> {
I don't think this method belongs here, since it's only used in XHR.send().

2016-09-15 21:46 UTC, KiChjang requested changes
Reminder of what you were trying to do - you were trying to implement [this step of the send() method](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send-document) before.

2016-09-15 21:55 UTC, jaysonsantos commented
There are a lot of code changes I will have to check the whole rebase or reimplement all the stuff from zero.

2016-09-16 17:35 UTC, jaysonsantos commented on components/script/dom/document.rs
> +    pub fn serialize(&self) -> Fallible<DOMString> {
What would you suggest? I put here because it was meant to serialize a Document.

2016-09-16 17:38 UTC, KiChjang commented on components/script/dom/document.rs
> +    pub fn serialize(&self) -> Fallible<DOMString> {
Putting it inline in `xmlhttprequest.rs`? There's no need for a function altogether.

2016-09-16 17:42 UTC, jaysonsantos commented on components/script/dom/xmlhttprequest.rs
> +            BodyInit::Document(ref d) => {
I've managed to make it compilable, if you want I can push the wip.

2016-09-18 11:56 UTC, jaysonsantos commented
I am having trouble running tests on linux, it is a out of box lubuntu 16.04 with just the installed binaries from the docs and it is running from a VM, running the tests with `./mach test-wpt --debugger --pause-after-test tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm` 
and this screen will stay there no matter how long i leave it running.
I've also tried to run it on the master branch and the same happend. I've managed to see that some tests were failing because I've changed testharness.js to print the error. 

![captura de tela 2016-09-18 13 51 22](https://cloud.githubusercontent.com/assets/51510/18615452/b4248e54-7da7-11e6-8215-e5b55e375a3b.png)

If I download the nightly version of rust for linux and point to `localhost:8000/path/of/wpt/test` it works perfectly reporting all the erros.
I read through the log of scripts components using `RUST_LOG=scripts=debug` and it didn't show anything useful.
Do you know of the top of your head what that could be?

2016-09-18 13:16 UTC, jdm commented
What happens if you remove the --debugger argument? Does the test harness eventually time out?

2016-09-18 13:19 UTC, jaysonsantos commented
It does not matter, it will always ways be like that. The last time I used the debugger to check if my change was breaking it. But if you want, I can post it without debugger

2016-09-18 13:22 UTC, jaysonsantos commented
Actually, in the screenshot I was running it without the debugger

2016-09-19 12:01 UTC, jaysonsantos commented
@jdm I left it there a few hours and it will never timout and quit
```
Mo 19. Sep 11:07:00 CEST 2016
Running 1 tests in web-platform-tests

Unsupported test type wdspec for product servo
  ▶ TIMEOUT [expected OK] /XMLHttpRequest/send-entity-body-document.htm

Ran 1 tests finished in 10407.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 1 tests timed out unexpectedly

Mo 19. Sep 14:00:32 CEST 2016
```
Afther almost 3 hours I just closed the browser window.

2016-09-19 13:30 UTC, jdm commented
I mean, the browser window won't close on its own if you specify `--pause-after-test`, but at what point was the timeout reported?

2016-09-19 13:30 UTC, jdm commented
(anything over three minutes is wasted time; no need to wait for several hours :))

2016-09-19 13:33 UTC, jaysonsantos commented
@jdm that was to test with gdb, the three hours one was `date; ./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm; date` and the funny thing is that If i put a message on testharness.js when the test fails it print it normally when I use gdb, meaning that the js wasn't broken or locked and If i try to run all the wpt it will timeout on a lot of tests.

2016-09-19 14:11 UTC, jdm commented
Could you paste the output of `./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm --log-mach -`?

2016-09-19 14:14 UTC, jaysonsantos commented
Here it is
```
 0:00.99 LOG: MainThread INFO Using 8 client processes
 0:01.02 LOG: MainThread INFO Generating new CA in /tmp/tmp_N1sbg
 0:01.18 PROCESS_OUTPUT: MainThread (pid:18554) Full command: /usr/bin/openssl req -config /tmp/tmp_N1sbg/openssl.cfg -batch -new -newkey rsa:2048 -keyout /tmp/tmp_N1sbg/cakey.pem -out /tmp/tmp_N1sbg/careq.pem -subj /CN=web-platform-tests -passout pass:web-platform-tests
(pid:18554) "Generating a 2048 bit RSA private key
..........................+++
...............................+++
writing new private key to '/tmp/tmp_N1sbg/cakey.pem'
-----
"
 0:01.21 PROCESS_OUTPUT: MainThread (pid:18556) Full command: /usr/bin/openssl ca -config /tmp/tmp_N1sbg/openssl.cfg -batch -create_serial -keyfile /tmp/tmp_N1sbg/cakey.pem -passin pass:web-platform-tests -selfsign -extensions v3_ca -in /tmp/tmp_N1sbg/careq.pem -out /tmp/tmp_N1sbg/cacert.pem
(pid:18556) "Using configuration from /tmp/tmp_N1sbg/openssl.cfg
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 870307 (0xd47a3)
        Validity
            Not Before: Sep 19 14:12:41 2016 GMT
            Not After : Oct 19 14:12:41 2016 GMT
        Subject:
            commonName                = web-platform-tests
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Subject Key Identifier: 
                6A:E5:8F:30:D8:9E:1A:FA:D5:77:36:92:ED:FE:D1:74:1B:54:BD:2A
            X509v3 Authority Key Identifier: 
                keyid:6A:E5:8F:30:D8:9E:1A:FA:D5:77:36:92:ED:FE:D1:74:1B:54:BD:2A
                DirName:/CN=web-platform-tests
                serial:0D:47:A3

            X509v3 Key Usage: 
                Certificate Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
Certificate is to be certified until Oct 19 14:12:41 2016 GMT (30 days)

Write out database with 1 new entries
Data Base Updated
"
 0:01.21 LOG: MainThread INFO Generating new host cert
 0:01.47 PROCESS_OUTPUT: MainThread (pid:18557) Full command: /usr/bin/openssl req -config /tmp/tmp_N1sbg/openssl.cfg -batch -newkey rsa:2048 -keyout /tmp/tmp_N1sbg/127.0.0.1.key -in /tmp/tmp_N1sbg/cakey.pem -nodes -out /tmp/tmp_N1sbg/wpt.req
(pid:18557) "Generating a 2048 bit RSA private key
..............................................................................................+++
..........................................................+++
writing new private key to '/tmp/tmp_N1sbg/127.0.0.1.key'
-----
"
 0:01.52 PROCESS_OUTPUT: MainThread (pid:18558) Full command: /usr/bin/openssl ca -config /tmp/tmp_N1sbg/openssl.cfg -batch -in /tmp/tmp_N1sbg/wpt.req -passin pass:web-platform-tests -subj /CN=127.0.0.1 -out /tmp/tmp_N1sbg/127.0.0.1.pem
(pid:18558) "Using configuration from /tmp/tmp_N1sbg/openssl.cfg
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 870308 (0xd47a4)
        Validity
            Not Before: Sep 19 14:12:42 2016 GMT
            Not After : Oct 19 14:12:42 2016 GMT
        Subject:
            commonName                = 127.0.0.1
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                59:86:26:67:F7:A1:3D:71:B0:3E:3F:12:DF:6B:F9:A4:6E:26:EA:1F
            X509v3 Authority Key Identifier: 
                keyid:6A:E5:8F:30:D8:9E:1A:FA:D5:77:36:92:ED:FE:D1:74:1B:54:BD:2A

            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:127.0.0.1, DNS:xn--n8j6ds53lwwkrqhv28a.127.0.0.1, DNS:www.127.0.0.1, DNS:xn--lve-6lad.127.0.0.1, DNS:www2.127.0.0.1, DNS:www1.127.0.0.1
Certificate is to be certified until Oct 19 14:12:42 2016 GMT (30 days)

Write out database with 1 new entries
Data Base Updated
"
 0:01.52 LOG: MainThread INFO Generating new host cert
 0:01.70 PROCESS_OUTPUT: MainThread (pid:18559) Full command: /usr/bin/openssl req -config /tmp/tmp_N1sbg/openssl.cfg -batch -newkey rsa:2048 -keyout /tmp/tmp_N1sbg/web-platform.test.key -in /tmp/tmp_N1sbg/cakey.pem -nodes -out /tmp/tmp_N1sbg/wpt.req
(pid:18559) "Generating a 2048 bit RSA private key
................................................+++
.................................+++
writing new private key to '/tmp/tmp_N1sbg/web-platform.test.key'
-----
"
 0:01.74 PROCESS_OUTPUT: MainThread (pid:18560) Full command: /usr/bin/openssl ca -config /tmp/tmp_N1sbg/openssl.cfg -batch -in /tmp/tmp_N1sbg/wpt.req -passin pass:web-platform-tests -subj /CN=web-platform.test -out /tmp/tmp_N1sbg/web-platform.test.pem
(pid:18560) "Using configuration from /tmp/tmp_N1sbg/openssl.cfg
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 870309 (0xd47a5)
        Validity
            Not Before: Sep 19 14:12:42 2016 GMT
            Not After : Oct 19 14:12:42 2016 GMT
        Subject:
            commonName                = web-platform.test
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                40:78:95:59:27:38:90:66:25:99:AF:D2:6D:32:57:51:D3:1D:49:C3
            X509v3 Authority Key Identifier: 
                keyid:6A:E5:8F:30:D8:9E:1A:FA:D5:77:36:92:ED:FE:D1:74:1B:54:BD:2A

            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:web-platform.test, DNS:www.web-platform.test, DNS:xn--n8j6ds53lwwkrqhv28a.web-platform.test, DNS:xn--lve-6lad.web-platform.test, DNS:www2.web-platform.test, DNS:www1.web-platform.test
Certificate is to be certified until Oct 19 14:12:42 2016 GMT (30 days)

Write out database with 1 new entries
Data Base Updated
"
 0:01.77 LOG: MainThread wptserve INFO Starting http server on 127.0.0.1:8000
 0:01.77 LOG: MainThread wptserve INFO Starting http server on 127.0.0.1:8001
 0:01.78 LOG: MainThread wptserve INFO Starting http server on 127.0.0.1:8443
 0:03.76 SUITE_START: MainThread 1
 0:03.76 LOG: MainThread INFO Running reftest tests
 0:03.77 LOG: MainThread INFO No reftest tests to run
 0:03.77 LOG: MainThread INFO Running wdspec tests
 0:03.77 LOG: MainThread ERROR Unsupported test type wdspec for product servo
 0:03.77 LOG: MainThread INFO Running testharness tests
 0:03.78 LOG: Thread-TestrunnerManager-1 INFO Starting runner
 0:03.79 LOG: Thread-TestrunnerManager-2 INFO Starting runner
 0:03.80 LOG: Thread-TestrunnerManager-3 INFO No more tests
 0:03.81 TEST_START: Thread-TestrunnerManager-1 /XMLHttpRequest/send-entity-body-document.htm
 0:03.81 LOG: Thread-TestrunnerManager-4 INFO No more tests
 0:03.81 LOG: Thread-TestrunnerManager-5 INFO No more tests
 0:03.81 LOG: Thread-TestrunnerManager-6 INFO No more tests
 0:03.81 LOG: Thread-TestrunnerManager-7 INFO No more tests
 0:03.81 LOG: Thread-TestrunnerManager-8 INFO No more tests
 0:04.82 LOG: Thread-TestrunnerManager-2 WARNING u'runner_teardown' ()
 0:04.82 LOG: Thread-TestrunnerManager-2 INFO No more tests
 1:06.12 LOG: Thread-TestrunnerManager-1 INFO Pausing until the browser exits
 1:06.12 TEST_END: Thread-TestrunnerManager-1 TIMEOUT, expected OK

 1:06.12 LOG: Thread-TestrunnerManager-1 INFO Pausing until the browser exits
 1:06.13 LOG: Thread-TestrunnerManager-1 WARNING u'runner_teardown' ()
 1:06.13 LOG: Thread-TestrunnerManager-1 INFO No more tests
 1:06.13 LOG: MainThread INFO Got 1 unexpected results
 1:06.13 SUITE_END: MainThread 
Summary
=======

Ran 1 tests
Expected results: 0
Unexpected results: 1 (TIMEOUT: 1)

Unexpected Results
==================

TIMEOUT /XMLHttpRequest/send-entity-body-document.htm
 1:06.17 LOG: MainThread INFO Closing logging queue
 1:06.17 LOG: M [...]

2016-09-19 15:06 UTC, jdm commented
Is that with these changes applied or against an unmodified master?

2016-09-19 15:34 UTC, jdm commented
Huh, I can't reproduce on master :/

2016-09-19 15:35 UTC, jaysonsantos commented
do you want a copy of my vm? it is running on lubuntu. Last time I updated  master was yesterday, let me update it again.

2016-09-19 15:37 UTC, jaysonsantos commented
Yes, with the head being a82d5106bd15d243c8552bf58472e3e9889d1ce2 the same problem happens. I was wondering if it can be because there is no proper 2d/3d acceleration.

2016-09-19 15:39 UTC, jdm commented
Is there any difference if you use `./mach build -r && ./mach test-wpt --release /XMLHttpRequest/send-entity-body-document.htm`?

2016-09-19 18:44 UTC, jaysonsantos commented
Hey @jdm the [here](https://gist.github.com/jaysonsantos/f58edf077ba4b9c5f3a840b774d8e121) is the log. This is the first time i compile release in this machine and looks like that there is a linker problem.

2016-09-20 11:23 UTC, jaysonsantos commented
@jdm Yesterday I did a ./mach clean, removed the .cargo dir and rebuild it as release and the tests worked. Do you know why would dev build not work?
I still have about 3 tests to fix.
Thanks!

2016-09-20 12:41 UTC, jdm commented
I'm not sure why it worked, but I'm glad it did :)

2016-09-20 18:09 UTC, jaysonsantos commented on components/script/dom/document.rs
> +            SerializeOpts { traversal_scope: ChildrenOnly, ..Default::default() }) {
Just answering this. If I don't use it, the serializer will break with this message.
```
  ▶ CRASH [expected OK] /XMLHttpRequest/send-entity-body-document.htm
  │ 
  │ Can't serialize Document node itself (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /home/jayson/p/servo/components/script/parse/html.rs:244)
  │ stack backtrace:
  │    0:     0x559b20a9ed9d - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:     0x559b20a9f422 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:     0x559b1f1dc19d - servo::main::_{{closure}}::hd8627710ce441e59
  │    3:     0x559b20cf21e5 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
  │    4:     0x559b1f5d54bf - std::panicking::begin_panic::h0914615a412ba184
  │    5:     0x559b1fb71014 - script::parse::html::_<impl html5ever..serialize..Serializable for &'a script..dom..node..Node>::serialize::hb19cf3d1a8128106
  │    6:     0x559b1f827c4e - html5ever::serialize::serialize::h5ca983e95371f52f
  │    7:     0x559b1f9e2530 - script::dom::document::Document::serialize::h29b3a36f0c434859
  │    8:     0x559b1fb63be0 - _<script..dom..bindings..codegen..UnionTypes..DocumentOrBodyInit as script..dom..xmlhttprequest..Extractable>::extract::h6808393b4e7b8052
  │    9:     0x559b1fb5bcd3 - _<script..dom..xmlhttprequest..XMLHttpRequest as script..dom..bindings..codegen..Bindings..XMLHttpRequestBinding..XMLHttpRequestBinding..XMLHttpRequestMethods>::Send::h337db624ae2e3ae8
  │   10:     0x559b1f5db6f3 - std::panicking::try::do_call::h0608cafe54224437
  │   11:     0x559b20cfa456 - __rust_maybe_catch_panic
  │   12:     0x559b1f999600 - script::dom::bindings::codegen::Bindings::XMLHttpRequestBinding::XMLHttpRequestBinding::send::hf8d32e9e3f3c3781
  │   13:     0x559b1fd1d184 - CallJitMethodOp
  │   14:     0x559b1f862854 - script::dom::bindings::utils::generic_call::hc239be2aefa6c7d4
  │   15:     0x559b200e2942 - 2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgs
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscntxtinlines.h:232
  │                          - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:453
  │   16:     0x559b200de0f1 - 2js13CallFromStackEP9JSContextRKN2JS8CallArgs
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:504
  │                          - Interpret
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:2873
  │   17:     0x559b200e265f - 2js9RunScriptEP9JSContextRNS_8RunState
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:399
  │   18:     0x559b200e2880 - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:471
  │   19:     0x559b200e2b47 - 2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_E
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:517
  │   20:     0x559b1ffd0edc - 2js9fun_applyEP9JSContextjPN2JS5Value
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsfun.cpp:1325
  │   21:     0x559b200e2942 - 2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgs
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscntxtinlines.h:232
  │                          - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:453
  │   22:     0x559b200de0f1 - 2js13CallFromStackEP9JSContextRKN2JS8CallArgs
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:504
  │                          - Interpret
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:2873
  │   23:     0x559b200e265f - 2js9RunScriptEP9JSContextRNS_8RunState
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:399
  │   24:     0x559b200e2880 - 2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstruct
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:471
  │   25:     0x559b200e2b47 - 2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_E
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Interpreter.cpp:517
  │   26:     0x559b1ff6650a - _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
  │                         at /home/jayson/p/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsapi.cpp:2781
  │   27:     0x559b1f8b8c1e - script::dom::bindings::codegen::Bindings::EventHandlerBinding::EventHandlerNonNull::Call::hfff992aab4ab8b4e
  │   28:     0x559b1f8b88c5 - script::dom::bindings::codegen::Bindings::EventHandlerBinding::EventHandlerNonNull::Call_::h86d2e00a2172acc3
  │   29:     0x559b1fa1790a - script::dom::eventdispatcher::handle_event::h16053516d9ef050b
  │   30:     0x559b1fa19c95 - script::dom::eventdispatcher::invoke::h1eae724394b1a36d
  │   31:     0x559b1fa18fef - script::dom::eventdispatcher::dispatch_event::h44cedf88bf8e65be
  │   32:     0x559b1fa1c9f2 - script::dom::eventtarget::EventTarget::fire_event::hc088fba0976b8daa
  │   33:     0x559b1fa622dc - script::dom::htmliframeelement::HTMLIFrameElement::iframe_load_event_steps::hb6a68ea29c7054a6
  │   34:     0x559b1fb8d5d2 - script::script_thread::ScriptThread::handle_msg_from_constellation::h4e39a1d4f2af6997
  │   35:     0x559b1fbd8b01 - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::had1422a31c223a9c
  │   36:     0x559b1fb86de4 - script::script_thread::ScriptThread::handle_msgs::he0c72778ea94b501
  │   37:     0x559b1f631517 - std::panicking::try::do_call::h4c43a18df829bea5
  │   38:     0x559b20cfa456 - __rust_maybe_catch_panic
  │   39:     0x559b1f7943e4 - _<F as alloc..boxed..FnBox<A>>::call_box::h9939d2c8ad214242
  │   40:     0x559b20cf0820 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  │   41:     0x7f9b8a9b36f9 - start_thread
  │   42:     0x7f9b8a4d3b5c - clone
  │   43:                0x0 - <unknown>
  │ ERROR:servo: Can't serialize Document node itself
  └ Pipeline failed in hard-fail mode.  Crashing!
```

2016-09-20 19:03 UTC, jaysonsantos commented
Hey guys, I've pushed just the code moving because I want to check 2 tests with you. When the shift-js runs it returns some mojibake and fail. I did [this](https://github.com/servo/servo/pull/10604/files#diff-016eef304e69674de212b7fbcd9330fdR1400), was it right?

2016-09-20 20:09 UTC, KiChjang commented on components/script/dom/xmlhttprequest.rs
> +        SerializeOpts { traversal_scope: ChildrenOnly, ..Default::default() }) {
IIRC `traversal_scope` is `ChildrenOnly` by default, so the second argument can just be `Default::default()` instead.

2016-09-20 20:10 UTC, KiChjang commented on components/script/dom/xmlhttprequest.rs
> +    if let Ok(()) = serialize(&mut writer, &document.upcast::<Node>(),
`if serialize(&mut writer, &document.upcast::<Node>(), Default::default()).is_ok() {`

2016-09-20 20:45 UTC, KiChjang commented on components/script/dom/xmlhttprequest.rs
> +            DocumentOrBodyInit::Document(ref d) => {
A document is not `Extractable`. This should be done in `fn Send()`, under step 4 (first half).

2016-09-20 20:46 UTC, KiChjang requested changes

2016-09-28 06:36 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13382) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-01 07:29 UTC, KiChjang commented
@jaysonsantos Is this still being worked on?

2016-10-01 07:55 UTC, jaysonsantos commented
@KiChjang Hi, I did a small pause because my newborn is here, my local branch is already rebased but I didn't push to avoid you guys doing unnecessary code review. If you think this is critical you can assign to a new person, otherwise, I will get back to it probably in a few days.

2016-10-12 00:36 UTC, KiChjang commented
Let us know when you want to work on this again, in the meantime, I'm closing this.Thanks for your work so far!

2016-10-12 00:36 UTC, closed without merging

2016-10-25 19:07 UTC, jaysonsantos commented
@KiChjang just a check even though this pr is not open anymore. I moved the serialize_document outside of the `Extractable` implementation here https://github.com/servo/servo/compare/master...jaysonsantos:xhr-send and I don't know if this is related but it started to break with this error.
```
   Compiling script v0.0.1 (file:///D:/p/personal/servo/components/script)
error: no method named `extract` found for type `&dom::bindings::codegen::UnionTypes::BlobOrFormDataOrStringOrURLSearchParams` in the current scope
   --> D:\p\personal\servo\components\script\dom\request.rs:374:48
    |
374 |             let extracted_body_tmp = init_body.extract();
    |                                                ^^^^^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `extract`, perhaps you need to implement it:
    = help: candidate #1: `dom::xmlhttprequest::Extractable`

error: no method named `extract` found for type `&dom::bindings::codegen::UnionTypes::BlobOrFormDataOrStringOrURLSearchParams` in the current scope
   --> D:\p\personal\servo\components\script\dom\response.rs:115:55
    |
115 |             let (extracted_body, content_type) = body.extract();
    |                                                       ^^^^^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `extract`, perhaps you need to implement it:
    = help: candidate #1: `dom::xmlhttprequest::Extractable`

error: aborting due to 2 previous errors

error: Could not compile `script`.

To learn more, run the command again with --verbose.
```
Which shouldn't happen because on the webidl it has an alias `typedef (Blob or /*BufferSource or */ FormData or DOMString or URLSearchParams) BodyInit;`
Do you see why this would be happening?
Plus, can racer complete code that comes from the codegen?
Thank you very much!

2016-10-25 19:27 UTC, KiChjang commented
`Extractable` should only be implemented on `BodyInit`, not `DocumentOrBodyInit`.

2016-10-25 20:21 UTC, jaysonsantos commented
@KiChjang I think I got it. But if I implement `Extractable for BodyInit` and send gets `Option<DocumentOrBodyInit>` how would I cast it back to BodyInit in case it the value is not `DocumentOrBodyInit::Document` and I cannot match `DocumentOrBodyInit::BodyInit` because `BodyInit` expands to (Blob, FormData, String and something else)?

2016-10-25 20:51 UTC, KiChjang commented
So, 4 possible solutions:
1) Implement `Extractable` for `DocumentOrBodyInit` anyway, and serialize the document in the `Document` variant (what you have in this PR).
2) Implement `Extractable` for the inner field types of the `BodyInit` struct variants, and instead of just calling `data.extract()` in step 4 of `Send`, have a match expression that handles the variants appropriately.
3) Patch CodegenRust.py so that `DocumentOrBodyInit` would produce 2 variants: `Document` and `BodyInit`.
4) Convert `DocumentOrBodyInit` variants (except for the `Document` variant) into `BodyInit`, and call `.extract()` on it.

4 sounds like the easiest, since you can just use a match expression and wrap `BodyInit` around it, e.g. 
```rust
let body_init = match data {
    // ...
    DocumentOrBodyInit::String(s => BodyInit::String(s),
    // ...
};
```
... though it may sound a bit silly, since you're creating another wrapper struct just to call a method on that struct. It may just be better to go with 2, since you'd be able to do the following:
```rust
let body_init = match data {
    // ...
    DocumentOrBodyInit::String(s => s.extract(),
    // ...
};
```

2016-10-27 20:19 UTC, jaysonsantos commented
Hi @KiChjang I came up with this
```diff
diff --git a/components/script/dom/xmlhttprequest.rs b/components/script/dom/xmlhttprequest.rs
index 462ba85..3c215fd 100644
--- a/components/script/dom/xmlhttprequest.rs
+++ b/components/script/dom/xmlhttprequest.rs
@@ -8,7 +8,7 @@ use dom::bindings::codegen::Bindings::BlobBinding::BlobMethods;
 use dom::bindings::codegen::Bindings::DocumentBinding::DocumentMethods;
 use dom::bindings::codegen::Bindings::EventHandlerBinding::EventHandlerNonNull;
 use dom::bindings::codegen::Bindings::WindowBinding::WindowMethods;
-use dom::bindings::codegen::Bindings::XMLHttpRequestBinding;
+use dom::bindings::codegen::Bindings::XMLHttpRequestBinding::{BodyInit, self};
 use dom::bindings::codegen::Bindings::XMLHttpRequestBinding::XMLHttpRequestMethods;
 use dom::bindings::codegen::Bindings::XMLHttpRequestBinding::XMLHttpRequestResponseType;
 use dom::bindings::codegen::UnionTypes::DocumentOrBodyInit;
@@ -25,6 +25,7 @@ use dom::document::{Document, IsHTMLDocument};
 use dom::document::DocumentSource;
 use dom::event::{Event, EventBubbles, EventCancelable};
 use dom::eventtarget::EventTarget;
+use dom::formdata::FormData;
 use dom::globalscope::GlobalScope;
 use dom::headers::is_forbidden_header_name;
 use dom::htmlformelement::{encode_multipart_form_data, generate_boundary};
@@ -32,6 +33,7 @@ use dom::node::Node;
 use dom::progressevent::ProgressEvent;
 use dom::servoparser::html::{ParseContext, parse_html};
 use dom::servoparser::xml::{self, parse_xml};
+use dom::urlsearchparams::URLSearchParams;
 use dom::window::Window;
 use dom::workerglobalscope::WorkerGlobalScope;
 use dom::xmlhttprequesteventtarget::XMLHttpRequestEventTarget;
@@ -519,20 +521,45 @@ impl XMLHttpRequestMethods for XMLHttpRequest {
             _ => data
         };
         // Step 4 (first half)
-        let extracted = data.as_ref().map(|d| d.extract());
+        let extracted = match data {
+            Some(DocumentOrBodyInit::Document(ref d)) => {
+                let data: Vec<u8> = serialize_document(d).unwrap().into();
+                let decoded_data: Vec<u8> = match &*d.CharacterSet() {
+                    "UTF-8" => {
+                        debug!("Document is already utf-8, skipping conversion {:?}", d.url());
+                        data
+                    },
+                    document_charset => {
+                        debug!("Document is {:?} we have to decode", document_charset);
+                        let charset = encoding_from_whatwg_label(&*d.CharacterSet()).unwrap_or(UTF_8);
+                        charset.decode(&*data, DecoderTrap::Replace).unwrap().into_bytes()
+                    }
+                };
+                let mut content_type = String::new();
+                if d.is_html_document() {
+                    content_type.push_str("text/html");
+                } else {
+                    content_type.push_str("application/xml");
+                };
+                content_type.push_str(";charset=UTF-8");
+                (decoded_data, Some(DOMString::from(content_type)))
+            },
+            Some(DocumentOrBodyInit::Blob(ref blob)) => blob.extract(),
+            Some(DocumentOrBodyInit::FormData(ref form_data)) => form_data.extract(),
+            Some(DocumentOrBodyInit::String(ref s)) => s.extract(),
+            Some(DocumentOrBodyInit::Blob(ref usp)) => usp.extract()
+        };
 
-        self.request_body_len.set(extracted.as_ref().map_or(0, |e| e.0.len()));
+        self.request_body_len.set(extracted.0.len());
 
         // todo preserved headers?
 
         // Step 6
         self.upload_complete.set(false);
         // Step 7
-        self.upload_complete.set(match extracted {
-            None => true,
-            Some (ref e) if e.0.is_empty() => true,
-            _ => false
-        });
+        if extracted.0.is_empty() {
+            self.upload_complete.set(true);
+        }
         // Step 8
         self.send_flag.set(true);
 
@@ -590,7 +617,7 @@ impl XMLHttpRequestMethods for XMLHttpRequest {
             headers: (*self.request_headers.borrow()).clone(),
             unsafe_request: true,
             // XXXManishearth figure out how to avoid this clone
-            body: extracted.as_ref().map(|e| e.0.clone()),
+            body: Some(extracted.0.clone()),
             // XXXManishearth actually "subresource", but it doesn't exist
             // https://github.com/whatwg/xhr/issues/71
             destination: Destination::None,
@@ -612,7 +639,7 @@ impl XMLHttpRequestMethods for XMLHttpRequest {
 
         // step 4 (second half)
         match extracted {
-            Some((_, ref content_type)) => {
+            (_, ref content_type) => {
                 // this should handle Document bodies too, not just BodyInit
                 let encoding = if let Some(DocumentOrBodyInit::String(_)) = data {
                     // XHR spec differs from http, and says UTF-8 should be in capitals,
@@ -1370,61 +1397,47 @@ pub trait Extractable {
     fn extract(&self) -> (Vec<u8>, Option<DOMString>);
 }
 
-impl Extractable for DocumentOrBodyInit {
+impl Extractable for Root<Blob> {
     // https://fetch.spec.whatwg.org/#concept-bodyinit-extract
     fn extract(&self) -> (Vec<u8>, Option<DOMString>) {
-        match *self {
-            DocumentOrBodyInit::String(ref s) => {
-                let encoding = UTF_8 as EncodingRef;
-                (encoding.encode(s, EncoderTrap::Replace).unwrap(),
-                    Some(DOMString::from("text/plain;charset=UTF-8")))
-            }
-            DocumentOrBodyInit::URLSearchParams(ref usp) => {
-                // Default encoding is UTF-8.
-                (usp.serialize(None).into_bytes(),
-                    Some(DOMString::from("application/x-www-form-urlencoded;charset=UTF-8")))
-            }
-            DocumentOrBodyInit::Blob(ref b) => {
-                let content_type = if b.Type().as_ref().is_empty() {
-                    None
-                } else {
-                    Some(b.Type())
-                };
-                let bytes = b.get_bytes().unwrap_or(vec![]);
-                (bytes, content_type)
-            }
-            DocumentOrBodyInit::FormData(ref formdata) => {
-                let boundary = generate_boundary();
-                let bytes = encode_multipart_form_data(&mut formdata.datums(), boundary.clone(),
-                                                       UTF_8 as EncodingRef);
-                (bytes, Some(DOMString::from(format!("multipart/form-data;boundary={}", boundary))))
-            },
-            DocumentOrBodyInit::Document(ref d) => {
-                let data: Vec<u8> = serialize_document(d).unwrap().into();
-                let decoded_data: Vec<u8> = match &*d.CharacterSet() {
-                    "UTF-8" => {
-                        debug!("Document is already utf-8, skipping conversion {:?}", d.url());
-                        data
-                    },
-                    document_charset => {
-                        debug!("Document is {:?} we have to decode", document_charset);
-                        let charset = encoding_from_whatwg_label(&*d.CharacterSet()).unwrap_or(UTF_8);
-                        charset.decode(&*data, DecoderTrap::Replace).unwrap().into_bytes()
-                    }
-                };
-                let mut content_type = String::new();
-                if d.is_html_document() {
-                    content_type.push_str("text/html");
-                } else {
-                    content_type.push_str("application/xml");
-                };
-                content_type.push_str(";charset=UTF-8");
-                (decoded_data, Some(DOMString::from(content_type)))
-            }
-        }
+        let content_type = if self.Type().as_ref().is_empty() {
+            None
+        } else {
+            Some(self.Type())
+        };
+        let bytes = self.get_bytes().unwrap_or(vec![]);
+        (bytes, content_type)
     }
 }
 
 [...]

2016-10-27 20:42 UTC, KiChjang commented
The easiest way here is to simply implement `Extractable` on `BodyInit`, and have it call `.extract()` on its enum variants.

2016-10-27 20:43 UTC, KiChjang commented
Also, instead of implementing traits on `Root<T>`, you should implement traits on `T` instead.

2016-10-28 06:56 UTC, jaysonsantos commented
> The easiest way here is to simply implement Extractable on BodyInit, and have it call .extract() on its enum variants.

To do it I would have to make a match on DocumentOrBodyInit and create a BodyInit, right? That `let extracted_body_tmp = init_body.extract();` would only use BodyInit or would it still run with DocumentOrBodyInit?

2016-11-07 21:00 UTC, jaysonsantos commented
Hey @KiChjang  I was trying to implement what you said and I got a really dumb error with the ownership but all the ways I tried to look real ugly and I thought that it might be because the way I tried to do the last changes. When I match data to extract the values, it's ownership is being transferred and it is being used down in the same function, I thought of using match as reference but when I started putting `&` to all returns of it started to feel strange.
this is the compared version https://github.com/servo/servo/compare/master...jaysonsantos:xhr-send
this was the error:

```
   Compiling script v0.0.1 (file:///D:/p/personal/servo/components/script)
error[E0382]: use of partially moved value: `data`
   --> D:\p\personal\servo\components\script\dom\xmlhttprequest.rs:658:77
    |
546 |             Some(DocumentOrBodyInit::Blob(blob)) => {
    |                                           ---- value moved here
...
658 |                 let encoding = if let Some(DocumentOrBodyInit::String(_)) = data {
    |                                                                             ^^^^ value used here after move
    |
    = note: move occurs because `((data:core::prelude::v1::Some).0:dom::bindings::codegen::UnionTypes::DocumentOrBodyInit::Blob).0` has type `dom::bindings::js::Root<dom::blob::Blob>`, which does not implement t
he `Copy` trait

error: aborting due to previous error

error: Could not compile `script`.

To learn more, run the command again with --verbose.
```

2016-11-07 21:29 UTC, jdm commented
Yeah, that's a tricky one. You probably need to do something like this:
```rust
           Some(DocumentOrBodyInit::Blob(ref blob)) => {
                let blob = BodyInit::Blob(Root::from_ref(&**blob));
```

2016-11-08 13:35 UTC, jaysonsantos commented
is it too ugly / is it possible to do something like this?
```rust
let (extracted, data) = match data {
    Some(...) => (Some(extracted_data), data),
    _ => (None, data)
}
```
?

2016-11-08 13:55 UTC, jdm commented
Seems reasonable.

2016-11-09 13:10 UTC, jaysonsantos commented
I tried both ways and in the end this happened:
```
PS D:\p\personal\servo> .\mach build -d
   Compiling script v0.0.1 (file:///D:/p/personal/servo/components/script)
error[E0507]: cannot move out of borrowed content
   --> D:\p\personal\servo\components\script\dom\xmlhttprequest.rs:555:47
    |
555 |                 let string = BodyInit::String(*string);
    |                                               ^^^^^^^ cannot move out of borrowed content

error[E0505]: cannot move out of `data` because it is borrowed
   --> D:\p\personal\servo\components\script\dom\xmlhttprequest.rs:544:77
    |
524 |             Some(DocumentOrBodyInit::Document(ref d)) => {
    |                                               ----- borrow of `data.0.0` occurs here
...
544 |                 (Some((decoded_data, Some(DOMString::from(content_type)))), data)
    |                                                                             ^^^^ move out of `data` occurs here

error[E0505]: cannot move out of `data` because it is borrowed
   --> D:\p\personal\servo\components\script\dom\xmlhttprequest.rs:548:40
    |
546 |             Some(DocumentOrBodyInit::Blob(ref blob)) => {
    |                                           -------- borrow of `data.0.0` occurs here
547 |                 let blob = BodyInit::Blob(Root::from_ref(blob));
548 |                 (Some(blob.extract()), data)
    |                                        ^^^^ move out of `data` occurs here

error[E0505]: cannot move out of `data` because it is borrowed
   --> D:\p\personal\servo\components\script\dom\xmlhttprequest.rs:552:45
    |
550 |             Some(DocumentOrBodyInit::FormData(ref form_data)) => {
    |                                               ------------- borrow of `data.0.0` occurs here
551 |                 let form_data = BodyInit::FormData(Root::from_ref(form_data));
552 |                 (Some(form_data.extract()), data)
    |                                             ^^^^ move out of `data` occurs here

error[E0505]: cannot move out of `data` because it is borrowed
   --> D:\p\personal\servo\components\script\dom\xmlhttprequest.rs:556:42
    |
554 |             Some(DocumentOrBodyInit::String(ref string)) => {
    |                                             ---------- borrow of `data.0.0` occurs here
555 |                 let string = BodyInit::String(*string);
556 |                 (Some(string.extract()), data)
    |                                          ^^^^ move out of `data` occurs here

error[E0505]: cannot move out of `data` because it is borrowed
   --> D:\p\personal\servo\components\script\dom\xmlhttprequest.rs:560:39
    |
558 |             Some(DocumentOrBodyInit::URLSearchParams(ref usp)) => {
    |                                                      ------- borrow of `data.0.0` occurs here
559 |                 let usp = BodyInit::URLSearchParams(Root::from_ref(usp));
560 |                 (Some(usp.extract()), data)
    |                                       ^^^^ move out of `data` occurs here

error: aborting due to 6 previous errors

error: Could not compile `script`.
```
When using Root:from_ref i tried both with two derefs and without and the result looks like the same.
I was wondering if it is not better to create a match on the top just to check if it is a string type to avoid the down match breaking.

2016-11-09 15:06 UTC, jdm commented
Two things - when moving data back out, you want to get rid of the `ref` from the match arms. This also means that Root::from_ref will need to be `Root::from_ref(&*usp)` (for example).