Add option to record frames for playback
servo/servo pull request #12630
Opened 2016-07-28 04:09 UTC by alanamramjit

Adds a debug option, -Z record, to record webrender's display lists for debugging.
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-07-28 04:09 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2016-07-28 04:27 UTC, paulrouget commented
I'm not sure to understand what this is supposed to do. Where is `enable_recording` used?

2016-07-28 11:36 UTC, jdm commented
@paulrouget https://github.com/servo/webrender/pull/316

2016-07-28 17:30 UTC, alanamramjit commented
This is for an issue in webrender :)
https://github.com/servo/webrender/issues/6

2016-08-03 14:25 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #12711) made this pull request unmergeable. Please resolve the merge conflicts.

2016-08-21 02:13 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #12941) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-15 09:17 UTC, shinglyu requested changes
Sorry for the wait, LGTM with some naming nits.

2016-12-15 09:17 UTC, shinglyu commented on components/util/opts.rs
> +        enable_recording: debug_options.enable_recording,
There is a similar feature for dumping layout frame tree called `trace_layout`, maybe we should follow the convention and call this `trace_webrender` or `record_webrender`, or even `record_display_list`.

2016-12-15 09:17 UTC, shinglyu commented on components/util/opts.rs
> +    print_option("record", "Serializes all frame data sent to webrender and writes to record folder.");
Is "frame data" == display list? Just say "Serialize the display list ..." sounds clearer to me.

2016-12-15 09:17 UTC, shinglyu commented on components/util/opts.rs
> +    ///Record and write to disk each frame sent to webrender.
Does this one do the similar thing as the one in `DebugOptions`? Then we should probably use the same comment.

2016-12-15 10:07 UTC, shinglyu commented
Travis build was failing, is the webrender side ready?

2016-12-19 14:45 UTC, jdm commented
This was subsumed by #14249.

2016-12-19 14:45 UTC, closed without merging