Implement indexed access on select elements
servo/servo pull request #13066
Opened 2016-08-26 23:19 UTC by mskrzypkows

Added methods for indexed access on select: SetLength, Length, Item, IndexedGetter

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11763 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-08-26 23:20 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/htmlselectelement.rs, components/script/dom/webidls/HTMLSelectElement.webidl

2016-08-26 23:41 UTC, jdm commented
r? @KiChjang

2016-08-26 23:44 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +            let document = node.GetOwnerDocument();
`document_from_node(self)`

2016-08-26 23:47 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +                        Err(e) => println!("error appending child of HTML Select: {:?}", e),
```rust
if let Err(e) = node.AppendChild(element.upcast()) {
    println!("error appending child of HTMLSelectElement: {:?}", e);
}
```

2016-08-26 23:50 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +        if item.is_some() {
` if let Some(item) = item {`

2016-08-26 23:55 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +        if item.is_some() {
Actually, we can even do this:
```rust
item.map(|i| Root::from_ref(i.upcast()))
```

2016-08-27 00:08 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +        if item.is_some() {
Or, if you don't mind chaining up functions:
```rust
node.traverse_preorder()
    .filter_map(Root::downcast::<HTMLOptionElement>)
    .nth(index as usize)
    .map(|item| Root::from_ref(item.upcast()))
```

2016-08-27 00:33 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +                let lastChild = node.GetLastChild();
I think we can just use `node.descending_last_children().take(length - value)` here.

2016-09-10 21:09 UTC, mskrzypkows commented on components/script/dom/htmlselectelement.rs
> +                let lastChild = node.GetLastChild();
For some reason
```
for child in node.descending_last_children().take((length - value) as usize) {
    if let Err(e) = node.RemoveChild(&child) {
        println!("error removing child of HTML Select: {:?}", e);
    }
}
```
doesn't work. I'll check it and upload next commit.

2016-09-10 22:51 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +                let lastChild = node.GetLastChild();
```rust
let iter = node.descending_last_children().take((length - value) as usize);
while let Some(child) = iter.next() {
    if let Err(e) = node.RemoveChild(&child) {
        println!("Error removing child of HTMLSelectElement: {:?}", e);
    }
}
```

2016-09-16 10:06 UTC, Manishearth commented
Any updates? If you need help, just ask! 😄

2016-09-16 10:10 UTC, mskrzypkows commented
I'll update today, sorry for the delay, I was busy recently.

2016-09-16 10:14 UTC, Manishearth commented
No problem :)

2016-09-16 11:08 UTC, mskrzypkows commented on components/script/dom/htmlselectelement.rs
> +                let lastChild = node.GetLastChild();
Still doesn't work, removing children test fails.

2016-09-16 17:31 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +                if let Some(lastChild) = node.GetLastChild() {
Looks like you ignored my review comments for this part.

2016-09-16 17:32 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +        let node = self.upcast::<Node>();
This can be melded into the following line without a let-binding to node.

2016-09-16 17:33 UTC, KiChjang requested changes

2016-09-17 08:12 UTC, mskrzypkows commented on components/script/dom/htmlselectelement.rs
> +                if let Some(lastChild) = node.GetLastChild() {
I didn't ignore your comment, check my reply to your previous comment. It doesn't work as you mentioned children nodes aren't deleted.

2016-09-17 21:18 UTC, KiChjang commented on components/script/dom/htmlselectelement.rs
> +                if let Some(lastChild) = node.GetLastChild() {
Sorry, `descending_last_children` is incorrect. Use `rev_children` instead.

2016-09-17 21:18 UTC, KiChjang commented on tests/wpt/metadata/html/semantics/forms/the-select-element/common-HTMLOptionsCollection.html.ini
>    type: testharness
This file can be deleted.

2016-09-17 21:18 UTC, KiChjang requested changes

2016-09-19 06:49 UTC, mskrzypkows commented on components/script/dom/htmlselectelement.rs
> +                if let Some(lastChild) = node.GetLastChild() {
OK, thanks for hints.

2016-09-21 07:54 UTC, KiChjang commented
Squash!

2016-09-21 12:14 UTC, jdm commented
@bors-servo: r=KiChjang

2016-09-21 12:14 UTC, bors-servo commented
:pushpin: Commit 920f42b has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 920f42b1e5812079ab5084f50bd96703027fd611 -->

2016-09-21 12:25 UTC, bors-servo commented
:hourglass: Testing commit 920f42b with merge 43c0bfe...

2016-09-21 13:49 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3210)

2016-09-21 14:14 UTC, jdm commented
```
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLSelectElement interface: attribute length

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLSelectElement interface: operation item(unsigned long)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLSelectElement interface: document.createElement("select") must inherit property "length" with the proper type (10)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLSelectElement interface: document.createElement("select") must inherit property "item" with the proper type (11)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLSelectElement interface: calling item(unsigned long) on document.createElement("select") with too few arguments must throw TypeError
```

2016-09-22 12:07 UTC, mskrzypkows commented
Strange build error, it seems not related to my changes.

2016-09-22 12:19 UTC, KiChjang approved these changes

2016-09-22 12:19 UTC, KiChjang commented
@bors-servo r+

2016-09-22 12:19 UTC, bors-servo commented
:pushpin: Commit 670693b has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 670693ba7ed62081db5dc7accec1020cf5d71a1a -->

2016-09-22 13:51 UTC, bors-servo commented
:hourglass: Testing commit 670693b with merge 96f6c1d...

2016-09-22 15:01 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3239)

2016-09-22 17:30 UTC, KiChjang commented
@bors-servo retry
* #12654, #13359

2016-09-22 18:14 UTC, bors-servo commented
:hourglass: Testing commit 670693b with merge d74f6ad...

2016-09-22 19:18 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3049), [arm64](http://build.servo.org/builders/arm64/builds/3065), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3118), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3292), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3120), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3116), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3243), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1011)

2016-09-22 19:18 UTC, merged