Create ./mach test-perf command
servo/servo pull request #13091
Opened 2016-08-28 08:50 UTC by zack1030

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes fix #12792 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it is low-risk

in **testing_commands.py**, I linked the new command to **test_perf.sh**
in **test_perf.sh**, it prepares tp5n.zip and virtual environment
then runs **test_all.sh**

2016-08-28 08:50 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/testing_commands.py
 * @aneeshusa: etc/ci/performance/test_all.sh, etc/ci/performance/runner.py, etc/ci/performance/test_perf.sh

2016-08-28 08:54 UTC, zack1030 commented
r? @shinglyu

2016-08-28 10:25 UTC, KiChjang commented
@bors-servo delegate=shinglyu

2016-08-28 10:25 UTC, bors-servo commented
:v: @shinglyu can now approve this pull request

2016-08-31 06:55 UTC, shinglyu commented on etc/ci/performance/test_all.sh
> +if ${upload_perfherder}; then
Please quote the variable like so: `if "${upload_perfherder}";`

2016-08-31 06:58 UTC, shinglyu commented on etc/ci/performance/test_perf.sh
> +#!/usr/bin/env bash
Please set the `set -o *` lines as described in the [style guide](https://github.com/servo/servo/blob/master/docs/STYLE_GUIDE.md#shell-scripts)

2016-08-31 06:59 UTC, shinglyu commented on etc/ci/performance/test_perf.sh
> +virtualenv venv --python=/usr/bin/python3
I wonder if `/usr/bin/env python3` works?

2016-08-31 07:04 UTC, shinglyu commented on etc/ci/performance/test_perf.sh
> +cp ../../../target/release/servo servo && \
Could we avoid the copying by using `../../../target/release/servo` in `runner.py`?

2016-08-31 07:04 UTC, shinglyu commented on etc/ci/performance/test_all.sh
> +  --upload)
Could you document this flag in the `README.md` file in this folder?

2016-08-31 07:05 UTC, shinglyu commented on python/servo/testing_commands.py
> +             description='Run the performance tests',
"Run the page load performance test" will be more accurate.

2016-08-31 07:08 UTC, shinglyu commented on etc/ci/performance/test_perf.sh
> +#!/usr/bin/env bash
You may also need to add the license here, run `./mach test-tidy` to check

2016-08-31 14:40 UTC, zack1030 commented on etc/ci/performance/test_perf.sh
> +virtualenv venv --python=/usr/bin/python3
Do you mean ```virtualenv venv --python=/usr/bin/env python3```?
It does not work the same way.
I guess ```/usr/bin/env virtualenv venv --python=python3``` is what you want.
But, I have not seen anyone use this.

2016-08-31 22:57 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
> +virtualenv venv --python=/usr/bin/python3
Please use
```
virtualenv venv --python="$(which python3)"
```
as not all systems have `python3` in the same place.

2016-08-31 22:58 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
> +set +u
Please add a comment about why this is necessary.

2016-08-31 23:00 UTC, aneeshusa commented
I'd like to see some caching for the `tp5n.zip` download and extraction, similarly to how we cache our downloaded `rustc`s and `cargo`s, to avoid downloading it every time. This would be especially useful for our CI machines.
@shinglyu, that zip is not meant to change, correct? Should we rehost it on the servo-rust S3 bucket? cc @larsbergstrom @edunham

2016-08-31 23:03 UTC, aneeshusa commented
Follow-up to last comment: I'm hoping there is some caching infrastructure in Mach/python that we can re-use for this from the rustc/cargo downloads.

2016-09-01 07:22 UTC, shinglyu commented on etc/ci/performance/test_perf.sh
> +virtualenv venv --python=/usr/bin/python3
Let's keep it as-is.

2016-09-01 07:25 UTC, shinglyu commented
Let's keep it simple by checking if `tp5n.zip` exist, then we skip the downloading. 

@aneeshusa : I don't think the zip URL will be removed in the near future, but we could host it in our S3 bucket in a followup bug

2016-09-01 07:26 UTC, shinglyu commented on etc/ci/performance/test_perf.sh
> +virtualenv venv --python=/usr/bin/python3
@aneeshusa 's suggestion below is what I wanted to say.

2016-09-06 08:20 UTC, shinglyu commented
Sorry, #12946 was submitted before this one, so I'm merging that first. I believe there will be some merge conflicts.

2016-09-06 09:58 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #12946) made this pull request unmergeable. Please resolve the merge conflicts.

2016-09-19 12:21 UTC, zack1030 commented
r? @bors-servo

2016-09-19 12:22 UTC, zack1030 commented
r? @shinglyu

2016-09-22 08:21 UTC, shinglyu commented on etc/ci/performance/test_perf.sh
> +cp -r ../../../resources servo && \
If we are running `../../../target/release/servo` in `runner.py`, we probably don't need to copy this folder.

2016-09-22 08:23 UTC, shinglyu commented on etc/ci/performance/test_perf.sh
> +TP5N_SOURCE="http://people.mozilla.org/~jmaher/taloszips/zips/tp5n.zip"
Let's use `https` for extra security.

2016-09-22 08:25 UTC, shinglyu requested changes
This looks good, just address the two small nits then we are ready to merge. Thank you for pushing this through.

2016-09-25 06:57 UTC, zack1030 commented
r? @shinglyu

2016-09-26 08:41 UTC, shinglyu commented
@bors-servo r+

2016-09-26 08:41 UTC, bors-servo commented
:pushpin: Commit fd204e0 has been approved by `shinglyu`

<!-- @bors-servo r=shinglyu fd204e03651b2642bb78ae0796c348561fc47e1c -->

2016-09-26 09:36 UTC, bors-servo commented
:hourglass: Testing commit fd204e0 with merge 9943566...

2016-09-26 11:03 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3122), [arm64](http://build.servo.org/builders/arm64/builds/3138), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3205), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3382), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3191), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3183), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3318), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1086)

2016-09-26 11:03 UTC, merged