Improve windows compile
servo/servo pull request #13277
Opened 2016-09-15 14:27 UTC by jaysonsantos

When you have python in any dir that is not the default one in C: it will break with this message:
```
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#87c47526)`
process didn't exit successfully: `D:/p/personal/servo/target\debug\build\mozjs_sys-661d4efe7c7ca939\build-script-build` (exit code: 101)
--- stderr
makefile.cargo:102: *** recipe commences before first target.  Stop.
thread 'main' panicked at 'assertion failed: result.success()', D:/p/personal/servo/.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\master\build.rs:43
stack backtrace:
   0:           0x44940e - <unknown>
   1:           0x4475c3 - <unknown>
   2:           0x447daa - <unknown>
   3:           0x404ef2 - <unknown>
   4:           0x40ef42 - <unknown>
   5:           0x447a28 - <unknown>
   6:           0x451d08 - <unknown>
   7:           0x446cc3 - <unknown>
   8:           0x40f81a - <unknown>
   9:           0x4013b4 - <unknown>
  10:           0x4014c7 - <unknown>
  11:     0x7ffc6b728643 - <unknown>

Build FAILED in 0:00:33
```

Creating a symbolic link to the python directory worked.

2016-09-15 14:27 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @kichjang (or someone else) soon.

2016-09-15 21:25 UTC, KiChjang commented
r? @larsbergstrom or someone else who knows about the windows build

2016-09-15 21:30 UTC, larsbergstrom commented on README.md
> +```
I think that the right fix here is actually to do as specified in:
https://github.com/servo/servo/issues/13206#issuecomment-247177576

Which is instead to set `NATIVE_WIN32_PYTHON` to be the full path to the `python.exe` that you want to run. Thanks for looking into correcting these instructions!

2016-09-15 21:30 UTC, larsbergstrom requested changes

2016-09-15 21:38 UTC, jaysonsantos commented on README.md
> +```
Hi, It does not state that there is this variable. Do you want me to add it there?

2016-09-16 12:56 UTC, UK992 commented
I think it would be simpler if you just add environment variable in ``command_base.py`` in ``build_env``, 
something like:
```python
env["NATIVE_WIN32_PYTHON"] = os.path.dirname(sys.executable)
```

2016-09-16 17:44 UTC, larsbergstrom commented
Good idea @UK992!

2016-09-16 18:12 UTC, jaysonsantos commented
@UK992 I think that will break, the mach is using msys' python and mozjs is using win32 one. I tried to run both with win32 and It broke because it tried to download a win32 rustc with unknown platform and it does not exist on nigthly builds of rust.
Anyway, I am closing this because it does not make sense as there is that variable.

2016-09-16 18:12 UTC, closed without merging

2016-09-16 18:23 UTC, UK992 commented
@jaysonsantos i meant only for msvc, which use the same python.