Implement ExtendableEvent as base type for ServiceWorker events
servo/servo pull request #13292
Opened 2016-09-16 15:12 UTC by creativcoder

Requires https://github.com/servo/string-cache/pull/170

---

- [ ] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] These changes do not require tests because refactor

2016-09-16 15:12 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/webidls/ExtendableEvent.webidl, components/script/dom/mod.rs, components/script/dom/webidls/ExtendableMessageEvent.webidl, components/script/dom/extendablemessageevent.rs, components/script/dom/extendableevent.rs, components/script/dom/serviceworkerglobalscope.rs

2016-09-16 15:12 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-09-16 15:43 UTC, jdm commented on components/script/dom/serviceworkerglobalscope.rs
> +                                             atom!("activate"),
nit: indentation

2016-09-16 15:44 UTC, jdm commented on components/script/dom/webidls/ExtendableEvent.webidl
> + Pref="dom.serviceworker.enabled" ]
nit: remove the extra space before ]

2016-09-16 15:44 UTC, jdm commented on components/script/dom/webidls/ExtendableMessageEvent.webidl
> +  Pref="dom.serviceworker.enabled" ]
nit: remove the extra space after [ and before ]

2016-09-16 15:45 UTC, jdm commented on components/script/dom/extendablemessageevent.rs
> +                                      HandleValue::undefined(),
nit: indentation

2016-09-16 15:47 UTC, jdm commented on components/script/dom/extendableevent.rs
> +    pub fn new_uninitialized(global: GlobalRef) -> Root<ExtendableEvent> {
I don't see any need to have the split between initialized/uninitialized. That's only for older event types that can be created in an uninitialized states.

2016-09-16 15:47 UTC, jdm commented on components/script/dom/extendableevent.rs
> +    fn init_extendable_event(&self,
Let's move the initialization into `new` directly.

2016-09-16 15:47 UTC, jdm commented on components/script/dom/extendablemessageevent.rs
> +    pub fn new_initialized(global: GlobalRef,
No need for the initialized/uninitialized split.

2016-09-16 15:48 UTC, jdm commented on components/script/dom/extendableevent.rs
> +            // TODO throw invalid state error, but this does not return a `Fallible` ?
Add `[Throws]` to the webidl method.

2016-09-16 15:49 UTC, jdm commented on components/script/dom/extendableevent.rs
> +                            Atom::from(type_),
nit: indentation.

2016-09-16 15:49 UTC, jdm requested changes

2016-09-16 16:35 UTC, jdm commented on components/script/dom/extendableevent.rs
> +            if !ev.dispatching() {
No need for this; we can't be dispatching in the constructor.

2016-09-16 16:36 UTC, jdm commented on components/script/dom/extendablemessageevent.rs
>      pub fn new_initialized(global: GlobalRef,
This can be called `new`.

2016-09-16 16:38 UTC, jdm requested changes
The indentation in dispatch_activate is still incorrect.

2016-09-16 23:04 UTC, jdm commented on components/script/dom/extendableevent.rs
>                 cancelable: bool)
These aren't used now, are they?

2016-09-16 23:05 UTC, jdm commented on components/script/dom/extendableevent.rs
>                     init: &ExtendableEventBinding::ExtendableEventInit) -> Fallible<Root<ExtendableEvent>> {
nit: indentation.

2016-09-16 23:05 UTC, jdm commented on components/script/dom/extendableevent.rs
> +    pub fn WaitUntil(&self, _cx: *mut JSContext, val: HandleValue) -> Fallible<()> {
We can use `ErrorResult` instead of `Fallible<()>`.

2016-09-16 23:07 UTC, jdm commented on components/script/dom/extendablemessageevent.rs
> +        reflect_dom_object(ev, global, ExtendableMessageEventBinding::Wrap)
We should reflect the object as soon as possible after creating it, otherwise we risk GC-unsafety.

2016-09-16 23:09 UTC, jdm requested changes
We can include the update to string_cache now, since it's been published.

2016-09-17 14:19 UTC, creativcoder commented on components/script/dom/extendableevent.rs
>                 cancelable: bool)
Yes, in `event.init_event()`. Made changes.

2016-09-17 14:26 UTC, creativcoder commented on components/script/dom/extendablemessageevent.rs
>          {
@jdm Will this be safe place of invocation for `reflect_dom_object` ?

2016-09-17 14:58 UTC, jdm commented on components/script/dom/extendablemessageevent.rs
>          {
Yes.

2016-09-17 15:00 UTC, jdm approved these changes

2016-09-17 15:01 UTC, jdm commented
@bors-servo: delegate+
Please squash them all into one commit, then you can merge with r=jdm.

2016-09-17 15:01 UTC, bors-servo commented
:v: @creativcoder can now approve this pull request

2016-09-17 15:33 UTC, creativcoder commented
@bors-servo r=jdm

2016-09-17 15:33 UTC, bors-servo commented
:pushpin: Commit 8b10cca has been approved by `jdm`

<!-- @bors-servo r=jdm 8b10cca91fb8163d648838706525b25935e8374b -->

2016-09-17 15:33 UTC, bors-servo commented
:hourglass: Testing commit 8b10cca with merge 83f687a...

2016-09-17 16:36 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/2961), [arm64](http://build.servo.org/builders/arm64/builds/2977), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3030), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3204), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3036), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3030), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3151), [windows-dev](http://build.servo.org/builders/windows-dev/builds/924)

2016-09-17 16:36 UTC, merged