Code refactoring
servo/servo pull request #13307
Opened 2016-09-18 09:20 UTC by bubbles231

The code was refactored to follow Rust naming conventions better.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes help fix #12379.

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because logic was not changed.

2016-09-18 09:20 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @manishearth (or someone else) soon.

2016-09-18 09:20 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/workerlocation.rs, components/script/dom/dompoint.rs, components/script/dom/htmlbrelement.rs, components/script/dom/htmlulistelement.rs, components/script/dom/blob.rs, components/script/dom/location.rs, components/script/dom/htmlfieldsetelement.rs, components/script/dom/htmllielement.rs, components/script/dom/htmlpreelement.rs, components/script/dom/htmlobjectelement.rs, components/script/dom/htmltextareaelement.rs, components/script/dom/htmlmapelement.rs, components/script/dom/htmldetailselement.rs, components/script/dom/file.rs, components/script/dom/htmlimageelement.rs, components/script/dom/console.rs, components/script/dom/htmlbuttonelement.rs, components/script/dom/node.rs, components/script/dom/htmldataelement.rs, components/script/dom/htmlanchorelement.rs, components/script/dom/url.rs, components/script/dom/htmldatalistelement.rs, components/script/dom/bluetoothcharacteristicproperties.rs, components/script/dom/activation.rs, components/script/dom/htmlcanvaselement.rs, components/script/dom/htmlselectelement.rs, components/script/dom/htmldlistelement.rs, components/script/dom/bluetoothdevice.rs, components/script/dom/htmlparamelement.rs, components/script/dom/htmlvideoelement.rs, components/script/dom/htmllinkelement.rs, components/script/dom/performance.rs, components/script/dom/browsingcontext.rs, components/script/dom/htmlmeterelement.rs, components/script/dom/htmldialogelement.rs, components/script/dom/htmlinputelement.rs, components/script/dom/bluetoothadvertisingdata.rs, components/script/dom/htmlareaelement.rs, components/script/dom/htmlframesetelement.rs, components/script/dom/htmltrackelement.rs, components/script/dom/htmlframeelement.rs, components/script/dom/htmlheadingelement.rs, components/script/dom/htmlolistelement.rs, components/script/dom/closeevent.rs, components/script/dom/htmlhrelement.rs, components/script/dom/htmltabledatacellelement.rs, components/script/dom/htmltablecolelement.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/htmlmetaelement.rs, components/script/dom/mouseevent.rs, components/script/dom/window.rs, components/script/dom/htmltitleelement.rs, components/script/dom/document.rs, components/script/dom/htmllegendelement.rs, components/script/dom/htmltableheadercellelement.rs, components/script/dom/htmlparagraphelement.rs, components/script/dom/htmlspanelement.rs, components/script/dom/htmltemplateelement.rs, components/script/dom/htmllabelelement.rs, components/script/dom/htmlbaseelement.rs, components/script/dom/htmlstyleelement.rs, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/htmltimeelement.rs, components/script/dom/htmldirectoryelement.rs, components/script/dom/dompointreadonly.rs, components/script/dom/performancetiming.rs, components/script/dom/storage.rs, components/script/dom/canvasrenderingcontext2d.rs, components/script/dom/keyboardevent.rs, components/script/dom/htmlfontelement.rs, components/script/dom/htmlmodelement.rs, components/script/dom/htmlsourceelement.rs, components/script/dom/storageevent.rs, components/script/dom/htmlappletelement.rs, components/script/dom/htmlheadelement.rs, components/script/dom/navigator.rs, components/script/dom/htmlquoteelement.rs, components/script/dom/htmlscriptelement.rs, components/script/dom/htmlaudioelement.rs, components/script/dom/htmltablesectionelement.rs, components/script/dom/htmlunknownelement.rs, components/script/dom/htmltablerowelement.rs, components/script/dom/htmloptionelement.rs, components/script/dom/htmlembedelement.rs, components/script/dom/htmloutputelement.rs, components/script/dom/urlhelper.rs, components/script/dom/touchevent.rs, components/script/dom/htmltableelement.rs, components/script/dom/htmldivelement.rs, components/script/dom/bluetoothremotegattcharacteristic.rs, components/script/script_runtime.rs, components/script/dom/htmlbodyelement.rs, components/script/dom/htmliframeelement.rs, components/script/dom/htmlelement.rs, components/script/dom/htmloptgroupelement.rs, components/script/dom/htmlformelement.rs, components/script/dom/websocket.rs, components/script/dom/htmlprogresselement.rs, components/script/dom/htmltablecaptionelement.rs

2016-09-18 09:20 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-09-18 10:10 UTC, Manishearth commented on components/script/dom/htmliframeelement.rs
> -pub fn Navigate(iframe: &HTMLIFrameElement, direction: TraversalDirection) -> ErrorResult {
This shouldn't be renamed

2016-09-18 10:10 UTC, Manishearth commented on components/script/dom/htmliframeelement.rs
> -            if UrlHelper::SameOrigin(&self_url, &win_url) {
Ditto

2016-09-18 10:12 UTC, Manishearth commented on components/script/dom/location.rs
> +        UrlHelper::hash(&self.get_url())
I think these should keep the capitalization

2016-09-18 10:12 UTC, Manishearth commented on components/script/dom/urlhelper.rs
>  impl UrlHelper {
These should keep the names

2016-09-18 10:13 UTC, Manishearth commented on components/script/dom/window.rs
> -    pub fn IndexedGetter(&self, _index: u32, _found: &mut bool) -> Option<Root<Window>> {
This shouldn't be changed

2016-09-18 10:14 UTC, Manishearth requested changes
We shouldn't be renaming `CamelCase` (not `camelCase`) methods on DOM types.

The `URLHelper` methods are a bit of an edge case here -- they're not directly called from Javascript, but I think they're supposed to mirror the URL interface.

2016-09-18 13:25 UTC, Manishearth approved these changes
Looks good to me!

2016-09-18 13:25 UTC, Manishearth commented
@bors-servo r+

2016-09-18 13:25 UTC, bors-servo commented
:pushpin: Commit 5f961f9 has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth 5f961f9fd9aeb13ff6c5746a8d143a30a90b06c2 -->

2016-09-18 13:25 UTC, bors-servo commented
:hourglass: Testing commit 5f961f9 with merge 25c2d0a...

2016-09-18 14:14 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3210)

2016-09-19 00:12 UTC, bubbles231 commented
I am excited to make my first PR to servo. It is really close -- There is only one out of 9977 tests that are failing. 
````
Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /css21_dev/html4/height-072.htm
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  │ failed to receive response to font request: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread LayoutWorker worker 1/12, at ../src/libcore/result.rs:799)
  │ stack backtrace:

````

Can you help me understand how to re-run this one failing test?

It seems like the error might be related to font selection in CSS. Do you have an idea of where in the
code that issue might be coming from?

2016-09-19 03:23 UTC, Manishearth commented
@bors-servo retry

Looks like an intermittent (let's see if it really is)

2016-09-19 03:58 UTC, bors-servo commented
:hourglass: Testing commit 5f961f9 with merge 5457b80...

2016-09-19 05:44 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/2976), [arm64](http://build.servo.org/builders/arm64/builds/2992), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3045), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3219), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3049), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3044), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3166), [windows-dev](http://build.servo.org/builders/windows-dev/builds/939)

2016-09-19 05:44 UTC, merged