Decode UTF-8 with from_utf8_lossy in DedicatedWorkerGlobalScope
servo/servo pull request #13306
Opened 2016-09-18 08:50 UTC by Jenselme

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13247

- [X] There are tests for these changes: `./mach test-wpt /workers/semantics/encodings/004.worker` passes

2016-09-18 08:50 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @larsbergstrom (or someone else) soon.

2016-09-18 08:50 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/dedicatedworkerglobalscope.rs

2016-09-19 07:24 UTC, Ms2ger commented on components/script/dom/dedicatedworkerglobalscope.rs
> +            let (metadata, bytes) = match load_whole_resource(LoadContext::Script,
Nit: realign the other arguments to `load_whole_resource` so they line up again.

2016-09-19 07:24 UTC, Ms2ger commented on tests/wpt/metadata/workers/semantics/encodings/004.worker.js.ini
> +  expected: PASS
This file can be removed entirely now.

2016-09-19 07:25 UTC, Ms2ger requested changes
Thanks! Just two small comments.

2016-09-19 08:29 UTC, Jenselme commented
@Ms2ger Just updated the PR to fix you comments.

2016-09-19 09:07 UTC, Ms2ger commented
Thanks so much!

@bors-servo r+

2016-09-19 09:07 UTC, bors-servo commented
:pushpin: Commit 9adda6e has been approved by `Ms2ger`

<!-- @bors-servo r=Ms2ger 9adda6e38da0988c8898a690fed46066608ab08d -->

2016-09-19 09:07 UTC, bors-servo commented
:hourglass: Testing commit 9adda6e with merge fe426f6...

2016-09-19 10:11 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/2981), [arm64](http://build.servo.org/builders/arm64/builds/2997), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3050), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3224), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3055), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3049), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3171), [windows-dev](http://build.servo.org/builders/windows-dev/builds/944)

2016-09-19 10:11 UTC, merged