Implement the Fetch method
servo/servo pull request #13323
Opened 2016-09-19 17:37 UTC by jeenalee

This PR implements the fetch method, which is described in [the Fetch Spec](https://fetch.spec.whatwg.org/#fetch-method). The expected wpt results are updated as well.

A few comments about the current fetch implementation:
- The fetch method manually calls `JSAutoCompartment` in order to prevent SpiderMonkey from crashing. This may have to change in the future.
- Not all `FetchResponseListener` methods are implemented.
- `net_traits::CoreResourceMsg::Fetch` message takes a `net_traits::request::RequestInit`. However, when the fetch method is called, a `RequestBinding::RequestInit` is given. The fetch method constructs a `dom::request::Request` with the given `RequestInit`, then creates `net_traits::request::RequestInit` from the dom Request object for the fetch message.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11898 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-09-19 17:37 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/devtools/Cargo.toml, components/devtools/lib.rs, components/devtools/actors/network_event.rs, components/devtools_traits/lib.rs, components/devtools_traits/lib.rs
 * @kichjang: components/script/dom/request.rs, components/net_traits/response.rs, components/net_traits/response.rs, components/script/timers.rs, components/net/http_loader.rs, components/script/dom/workerglobalscope.rs, components/script/dom/bindings/error.rs, components/script/fetch.rs, components/script/Cargo.toml, components/net/blob_loader.rs, components/script/script_thread.rs, components/script/dom/promise.rs, components/script/dom/webidls/Fetch.webidl, components/script/dom/mod.rs, components/script/dom/htmllinkelement.rs, components/script/dom/bindings/refcounted.rs, components/script/dom/testbinding.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/htmlmediaelement.rs, components/script/dom/webidls/PromiseNativeHandler.webidl, components/script/dom/response.rs, components/script/dom/bindings/codegen/Bindings.conf, components/script/dom/bindings/trace.rs, components/script/dom/window.rs, components/net_traits/lib.rs, components/net_traits/lib.rs, components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/webidls/TestBinding.webidl, components/net/fetch/methods.rs, components/script/dom/webidls/Promise.webidl, components/script/dom/bindings/global.rs, components/script/dom/webidls/Response.webidl, components/script/dom/htmlscriptelement.rs, components/script/lib.rs, components/script/dom/bindings/codegen/Configuration.py, components/net/about_loader.rs, components/script/dom/promisenativehandler.rs, components/script/dom/headers.rs, components/script/dom/bindings/js.rs, components/script/script_runtime.rs, components/script/dom/webidls/WindowOrWorkerGlobalScope.webidl

2016-09-19 17:37 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.
* These commits modify **unsafe code**. Please review it carefully!

2016-09-19 17:41 UTC, jeenalee commented
r? @jdm

2016-09-21 09:32 UTC, emilio commented
@bors-servo: try

2016-09-21 09:32 UTC, bors-servo commented
:hourglass: Trying commit c135549 with merge 864ba39...

2016-09-21 10:24 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3260)

2016-09-21 13:22 UTC, jdm commented on components/script/dom/headers.rs
> +    pub fn set_guard_immutable(&self) {
We can use `set_guard` instead.

2016-09-21 13:24 UTC, jdm commented on components/script/dom/response.rs
> +        self.Headers().set_headers( match option_hyper_headers {
nit: extra space after (

2016-09-21 13:33 UTC, jdm commented on components/script/fetch.rs
> +#[allow(unrooted_must_root)]
Do you remember why this was required?

2016-09-21 13:34 UTC, jdm commented on components/script/fetch.rs
> +    let referer = request.referrer.borrow();
`referrer`

2016-09-21 13:34 UTC, jdm commented on components/script/fetch.rs
> +fn from_referer_to_referer_url(request: &NetTraitsRequest) -> Option<Url> {
`from_referrer_to_referrer_url`

2016-09-21 13:35 UTC, jdm commented on components/script/fetch.rs
> +    match referer.to_url() {
`referrer.to_url().map(|url| url.clone())`

2016-09-21 13:40 UTC, jdm commented on components/script/fetch.rs
> +                                       e);
nit: this can join the previous line.

2016-09-21 13:41 UTC, jdm commented on components/script/dom/webidls/Fetch.webidl
> +  [NewObject, Throws] Promise<Response> fetch(RequestInfo input, optional RequestInit init);
No need for `Throws` anymore.

2016-09-21 13:41 UTC, jdm commented on components/script/fetch.rs
> +        response_object: Trusted::new(response.r()),
We can use `&*` instead of `.r()` here.

2016-09-21 13:42 UTC, jdm commented on components/script/fetch.rs
> +        // TODO: double check how to get script_chan
This comment is meaningless here; let's remove it.

2016-09-21 13:43 UTC, jdm commented on components/script/fetch.rs
> +        context: fetch_context.clone(),
I don't think this clone is necessary.

2016-09-21 13:44 UTC, jdm commented on components/script/fetch.rs
> +        let promise = match self.fetch_promise.take() {
Let's use `let promise = self.fetch_promise.take().expect("fetch promise is missing").root();`

2016-09-21 13:48 UTC, jdm requested changes
Nice work!

2016-09-21 16:37 UTC, jeenalee commented on components/script/fetch.rs
> +#[allow(unrooted_must_root)]
It was indeed not required. Thank you for pointing it out!

2016-09-21 17:38 UTC, jeenalee commented
@jdm Review comments addressed!

2016-09-21 18:42 UTC, jdm approved these changes

2016-09-21 18:42 UTC, jdm commented
Great! You can squash your commits together, and then we'll merge this once #12830 is merged.

2016-09-21 19:39 UTC, jeenalee commented
@jdm: Should I squash all of the three commits into one?

2016-09-21 20:39 UTC, jdm commented
Yep.

2016-09-22 21:59 UTC, jdm commented
@bors-servo: delegate+
This can merge whenever it's rebased.

2016-09-22 21:59 UTC, bors-servo commented
:v: @jeenalee can now approve this pull request

2016-09-22 23:41 UTC, jeenalee commented
@jdm: I updated the code to reflect the changes in net_traits/lib.rs. Can you take a look at the changes when you have a moment? Thank you!

2016-09-23 00:01 UTC, KiChjang commented on components/script/fetch.rs
> +                    } => self.response_object.root().set_type(DOMResponseType::Opaque),
I prefer this style more:
```rust
FetchMetadata::Filtered { filtered, .. } => match filtered {
    FilteredMetadata::Transparent(metadata) => {
        self.response_object.root().set_headers(metadata.headers);
        // ... and others, could probably extract the 3 lines into a helper method
    }
    FilteredMetadata::Opaque => self.response_object.root().set_type(DOMResponseType::Opaque)
}
```

2016-09-23 00:01 UTC, KiChjang commented on components/script/fetch.rs
> +    fn process_response(&mut self, fetchmetadata: Result<FetchMetadata, NetworkError>) {
nit: Snake case instead (`fetch_metadata`).

2016-09-23 00:02 UTC, KiChjang commented on components/script/fetch.rs
> +            Ok(fetchmetadata_) => {
Perhaps call this `metadata`?

2016-09-23 00:02 UTC, KiChjang commented on components/script/fetch.rs
> +                        filtered: FilteredMetadata::Transparent(metadata),
And this just `meta`, `data`, or maybe even `m`?

2016-09-23 00:03 UTC, KiChjang requested changes
Minor changes required, but looks good otherwise!

2016-09-23 00:11 UTC, jeenalee commented on components/script/fetch.rs
> +                    } => self.response_object.root().set_type(DOMResponseType::Opaque),
That is a lot more elegant. Thanks!

2016-09-23 17:11 UTC, jeenalee commented
@KiChjang Addressed your comments. Thank you!

2016-09-23 17:30 UTC, jdm commented
@bors-servo: r+

2016-09-23 17:30 UTC, bors-servo commented
:pushpin: Commit 8cd83e4 has been approved by `jdm`

<!-- @bors-servo r=jdm 8cd83e41b581fd7d2b7cf9873faf76f717c62699 -->

2016-09-23 18:33 UTC, KiChjang approved these changes

2016-09-24 00:57 UTC, bors-servo commented
:hourglass: Testing commit 8cd83e4 with merge cf866ea...

2016-09-24 02:08 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3328)

2016-09-26 02:14 UTC, jdm commented
Lots of test expectation updates required :)

2016-09-26 03:18 UTC, jeenalee commented
@jdm Test expectations updated!

2016-09-26 03:27 UTC, jdm commented
@bors-servo: r+

2016-09-26 03:27 UTC, bors-servo commented
:pushpin: Commit e332265 has been approved by `jdm`

<!-- @bors-servo r=jdm e332265d4e041b6640e05dd1b9daa3d0e52c5eff -->

2016-09-26 03:27 UTC, bors-servo commented
:hourglass: Testing commit e332265 with merge 9670d14...

2016-09-26 03:27 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3358)

2016-09-26 03:38 UTC, jdm commented
@bors-servo: retry
* weird cargo failure

2016-09-26 03:38 UTC, bors-servo commented
:hourglass: Testing commit e332265 with merge cf88b33...

2016-09-26 03:38 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3363)

2016-09-26 04:23 UTC, jdm commented
@bors-servo: retry
* weird cargo git failure

2016-09-26 04:23 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/3110), [arm64](http://build.servo.org/builders/arm64/builds/3127), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3182), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1074) are reusable. Rebuilding only [linux-dev](http://build.servo.org/builders/linux-dev/builds/3187), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3363), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3176), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3309)...

2016-09-26 04:24 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3191)

2016-09-26 04:49 UTC, KiChjang commented
@bors-servo retry
* Cargo is a git

2016-09-26 04:49 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/3110), [arm64](http://build.servo.org/builders/arm64/builds/3127), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3182), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1074) are reusable. Rebuilding only [linux-dev](http://build.servo.org/builders/linux-dev/builds/3191), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3367), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3176), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3309)...

2016-09-26 04:49 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3194)

2016-09-26 10:15 UTC, KiChjang commented
@bors-servo retry

2016-09-26 14:02 UTC, bors-servo commented
:hourglass: Testing commit e332265 with merge 4187cb3...

2016-09-26 14:39 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3388)

2016-09-26 14:39 UTC, highfive commented
▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-credentials-worker.html:
      │ TIMEOUT [expected PASS] Redirect 307 from remote to another remote with user and password
      └   → Test timed out
    
      ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-credentials-worker.html:
      └ NOTRUN [expected PASS] Redirect 307 from remote to another remote with user
    
      ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-credentials-worker.html:
      └ NOTRUN [expected PASS] Redirect 307 from remote to another remote with password
    
      ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-credentials-worker.html:
      └ NOTRUN [expected TIMEOUT] Redirect 308 from same origin to remote with user and password
    
      ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-preflight-worker.html:
      │ TIMEOUT [expected FAIL] Redirect 303: cors to same origin (preflight after redirection failure case)
      └   → Test timed out
    
      ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-preflight-worker.html:
      └ NOTRUN [expected TIMEOUT] Redirect 303: cors to another cors (preflight after redirection success case)

2016-09-26 14:47 UTC, jdm commented
Looks like a few final test result changes.

2016-09-26 17:37 UTC, jeenalee commented
@jdm tests updated!

2016-09-26 17:46 UTC, KiChjang commented
@bors-servo r=jdm

2016-09-26 19:46 UTC, bors-servo commented
:hourglass: Testing commit 275ff78 with merge de1fa4b...

2016-09-26 20:39 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3396)

2016-09-26 20:54 UTC, KiChjang commented
```
Ran 7578 tests finished in 1040.0 seconds.
  • 7575 ran as expected. 1677 tests skipped.
  • 3 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-preflight.html:
  │ TIMEOUT [expected FAIL] Redirect 303: cors to same origin (preflight after redirection success case)
  └   → Test timed out

  ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-preflight.html:
  └ NOTRUN [expected TIMEOUT] Redirect 303: cors to same origin (preflight after redirection failure case)

  ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-credentials.html:
  │ TIMEOUT [expected PASS] Redirect 307 from remote to another remote with password
  └   → Test timed out

  ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-credentials.html:
  └ NOTRUN [expected PASS] Redirect 308 from same origin to remote with user and password

  ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect-credentials.html:
  └ NOTRUN [expected TIMEOUT] Redirect 308 from same origin to remote with user

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-location-worker.html:
  │ TIMEOUT [expected PASS] Redirect 302 in "follow" mode with invalid location
  └   → Test timed out

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-location-worker.html:
  └ NOTRUN [expected TIMEOUT] Redirect 302 in "manual" mode with invalid location
```

2016-09-26 21:10 UTC, jdm commented
@bors-servo: r=jdm

2016-09-26 21:10 UTC, bors-servo commented
:pushpin: Commit e0a1017 has been approved by `jdm`

<!-- @bors-servo r=jdm e0a1017b7637fec4f43aaece351e5033521c896a -->

2016-09-26 21:10 UTC, jeenalee commented
@jdm: I disabled the `/redirect` and `/cors` tests.

2016-09-26 21:56 UTC, bors-servo commented
:hourglass: Testing commit e0a1017 with merge 3c05432...

2016-09-26 22:30 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3400)

2016-09-27 00:35 UTC, KiChjang commented
@bors-servo retry
* wpt wat

2016-09-27 01:22 UTC, bors-servo commented
:hourglass: Testing commit e0a1017 with merge 835ec54...

2016-09-27 01:57 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3407)

2016-09-27 05:15 UTC, jdm commented on tests/wpt/include.ini
> +      [cors]
I think this line (and the subsequent ones) are over-indented, which is throwing off the manifest parser.
```
[api]
  skip: false
  [cors]
    skip: true
  [redirect]
    skip: true
```

2016-09-27 05:41 UTC, jeenalee commented on tests/wpt/include.ini
> +      [cors]
Fixed!

2016-09-27 07:41 UTC, KiChjang commented
@bors-servo r=jdm

2016-09-27 07:41 UTC, bors-servo commented
:pushpin: Commit f06188e has been approved by `jdm`

<!-- @bors-servo r=jdm f06188e3c112fe8e945a52769f4d6bbc95bed549 -->

2016-09-27 09:44 UTC, bors-servo commented
:hourglass: Testing commit f06188e with merge 9b4ed9f...

2016-09-27 11:04 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3350)

2016-09-27 12:45 UTC, jdm commented
@bors-servo: retry
* #13458

2016-09-27 13:32 UTC, bors-servo commented
:hourglass: Testing commit f06188e with merge 0115406...

2016-09-27 14:58 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3216)

2016-09-27 15:24 UTC, jdm commented
@bors-servo: retry
* #13463

2016-09-27 16:38 UTC, bors-servo commented
:hourglass: Testing commit f06188e with merge ddc04bc...

2016-09-27 17:49 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3359)

2016-09-27 18:21 UTC, jdm commented
@bors-servo: retry
* #13458

2016-09-28 03:33 UTC, jdm commented
@bors-servo: r+

2016-09-28 03:33 UTC, bors-servo commented
:pushpin: Commit 8a15e78 has been approved by `jdm`

<!-- @bors-servo r=jdm 8a15e784fc11266479691750c6465488fefddfa5 -->

2016-09-28 03:38 UTC, bors-servo commented
:hourglass: Testing commit 8a15e78 with merge c8a9713...

2016-09-28 03:39 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3370)

2016-09-28 04:00 UTC, KiChjang commented
@bors-servo retry

2016-09-28 06:35 UTC, bors-servo commented
:hourglass: Testing commit 8a15e78 with merge 780f45e...

2016-09-28 07:43 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3380)

2016-09-28 07:43 UTC, highfive commented
▶ TIMEOUT [expected OK] /html/the-xhtml-syntax/parsing-xhtml-documents/xhtml-mathml-dtd-entity-support.htm
      │ 
      │ VMware, Inc.
      │ Gallium 0.4 on softpipe
      └ 3.3 (Core Profile) Mesa 12.0.1
    
      ▶ TIMEOUT [expected OK] /webgl/conformance-1.0.3/conformance/textures/origin-clean-conformance.html
      │ 
      │ VMware, Inc.
      │ Gallium 0.4 on softpipe
      └ 3.3 (Core Profile) Mesa 12.0.1

2016-09-28 15:04 UTC, jdm commented
@bors-servo: retry
* #13341, #13482

2016-09-28 21:40 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13475) made this pull request unmergeable. Please resolve the merge conflicts.

2016-09-28 21:54 UTC, jdm commented
@bors-servo: r+

2016-09-28 21:54 UTC, bors-servo commented
:pushpin: Commit f1b198e has been approved by `jdm`

<!-- @bors-servo r=jdm f1b198ef36e4aeb6ddf7420d5c8a0d21b2c82bb2 -->

2016-09-28 22:46 UTC, bors-servo commented
:hourglass: Testing commit f1b198e with merge 8f6861b...

2016-09-28 23:39 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3463)

2016-09-29 00:26 UTC, jdm commented
@bors-servo: retry
* #13492

2016-09-29 00:31 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/3199), [arm64](http://build.servo.org/builders/arm64/builds/3212), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3284), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3276), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3257), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1162) are reusable. Rebuilding only [linux-rel](http://build.servo.org/builders/linux-rel/builds/3463), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3400)...

2016-09-29 01:40 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3402)

2016-09-29 04:13 UTC, jeenalee commented
I re-introduced the change ([disable request-cache.html](https://github.com/servo/servo/commit/8a15e78)) that was lost during rebase.

2016-09-29 05:12 UTC, KiChjang commented
@bors-servo r=jdm

2016-09-29 05:12 UTC, bors-servo commented
:pushpin: Commit 0c25840 has been approved by `jdm`

<!-- @bors-servo r=jdm 0c258405fdc673b6c0816abd25cfccec97ee71ae -->

2016-09-29 06:18 UTC, bors-servo commented
:hourglass: Testing commit 0c25840 with merge c7e2a5a...

2016-09-29 07:22 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3405)

2016-09-29 11:25 UTC, jdm commented
@bors-servo: retry
#13359

2016-09-29 12:19 UTC, bors-servo commented
:lock: Merge conflict

2016-09-29 12:19 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13345) made this pull request unmergeable. Please resolve the merge conflicts.

2016-09-29 15:21 UTC, jeenalee commented
Rebased as #13345 was merged (hooray!)!

2016-09-29 15:42 UTC, jdm commented
@jeenalee: Does this include new test results for all the tests? Working body methods will have changed the results from previous runs significantly.

2016-09-29 16:30 UTC, jeenalee commented
@jdm I built and ran `fetch/api/` tests, and updated the test results. Will that suffice?

2016-09-29 16:47 UTC, jdm commented
@bors-servo: r+

2016-09-29 16:47 UTC, bors-servo commented
:pushpin: Commit 3216009 has been approved by `jdm`

<!-- @bors-servo r=jdm 3216009731664d5099049267bca7a79e6af22196 -->

2016-09-29 17:26 UTC, bors-servo commented
:hourglass: Testing commit 3216009 with merge f6d5cac...

2016-09-29 18:16 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3481)

2016-09-29 18:21 UTC, jdm commented
@bors-servo: retry
#12654

2016-09-29 19:28 UTC, bors-servo commented
:hourglass: Testing commit 3216009 with merge 5996e00...

2016-09-29 20:29 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3218), [arm64](http://build.servo.org/builders/arm64/builds/3231), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3303), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3483), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3295), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3276), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3420), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1181)

2016-09-29 20:29 UTC, merged