Implement the MozMap type.
servo/servo pull request #13332
Opened 2016-09-20 10:09 UTC by Ms2ger

2016-09-20 10:09 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/testbinding.rs, components/script/dom/bindings/mod.rs, components/script/dom/bindings/mozmap.rs, components/script/dom/bindings/conversions.rs, components/script/dom/webidls/TestBinding.webidl

2016-09-20 10:09 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2016-09-20 12:11 UTC, nox commented on components/script/dom/bindings/conversions.rs
> +pub fn string_jsid_to_string(cx: *mut JSContext, id: HandleId) -> DOMString {
Could you make it unsafe while at it?

2016-09-20 14:27 UTC, jdm commented on components/script/dom/bindings/codegen/CodegenRust.py
> +    return type.inner.inner if type.nullable() else type.inner
We might as well merge this with the innerSequenceType function (innerMapOrSequenceType?), since they're identical except for the asserts.

2016-09-20 14:29 UTC, jdm commented on components/script/dom/bindings/codegen/CodegenRust.py
> +    if type.isMozMap():
Merge this with the previous.

2016-09-20 14:37 UTC, jdm commented on components/script/dom/bindings/conversions.rs
> +/// Handling of invalid UTF-16 in strings depends on the relevant option.
Relevant option?

2016-09-20 14:41 UTC, jdm commented on components/script/dom/bindings/mozmap.rs
> +                ConversionResult::Failure(message) => return Ok(ConversionResult::Failure(message)),
`failure => return Ok(failure),`

2016-09-20 14:43 UTC, jdm commented on components/script/dom/bindings/mozmap.rs
> +            let key = jsid_to_string(cx, id.handle()).unwrap();
Couldn't this panic on an unpaired surrogate?

2016-09-20 14:45 UTC, jdm requested changes
Only a couple small changes and clarifications. Great work!

2016-09-21 11:38 UTC, Ms2ger commented on components/script/dom/bindings/conversions.rs
> +/// Handling of invalid UTF-16 in strings depends on the relevant option.
Refers to `opts::get().replace_surrogates`; not sure if it would be better to mention `-Z replace-surrogates` explicitly.

2016-09-21 11:40 UTC, Ms2ger commented on components/script/dom/bindings/mozmap.rs
> +                ConversionResult::Failure(message) => return Ok(ConversionResult::Failure(message)),
```
   |
73 |                 failure => return Ok(failure),
   |                                      ^^^^^^^ expected struct `dom::bindings::mozmap::MozMap`, found type parameter
   |
   = note: expected type `js::conversions::ConversionResult<dom::bindings::mozmap::MozMap<T>>`
   = note:    found type `js::conversions::ConversionResult<T>`
```

2016-09-21 12:10 UTC, jdm commented
@bors-servo: r+

2016-09-21 12:10 UTC, bors-servo commented
:pushpin: Commit 2d83e5a has been approved by `jdm`

<!-- @bors-servo r=jdm 2d83e5a78880724713366a38f599a1dac65403dc -->

2016-09-21 15:09 UTC, bors-servo commented
:hourglass: Testing commit 2d83e5a with merge 7b98c8a...

2016-09-21 16:13 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3023), [arm64](http://build.servo.org/builders/arm64/builds/3039), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3092), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3266), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3096), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3091), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3213), [windows-dev](http://build.servo.org/builders/windows-dev/builds/986)

2016-09-21 16:13 UTC, merged