Support OpenEndedDictionary (Mozmap) in the Headers
servo/servo pull request #13356
Opened 2016-09-21 18:24 UTC by jeenalee

This PR will support OpenEndedDictionary (based on MozMap implementation from #13332) in the Headers API.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11897  (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-09-21 18:24 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/request.rs, components/script/dom/bindings/mozmap.rs, components/script/dom/webidls/Headers.webidl, components/script/dom/headers.rs

2016-09-21 18:24 UTC, jeenalee commented
r? @jdm

2016-09-21 18:36 UTC, jdm commented on components/script/dom/request.rs
> +use dom::bindings::codegen::UnionTypes::HeadersOrByteStringSequenceSequenceOrByteStringMozMap  as HeadersInitType;
nit: extra space before as.

2016-09-21 18:37 UTC, jdm commented on components/script/dom/request.rs
> +        {
```rust
&HeadersInitType::ByteStringMozMap(ref m) =>
    HeadersInitType::ByteStringMozMap(m.clone())
```

2016-09-21 18:39 UTC, jdm requested changes
I'm operating under the assumption that all of the tests now timing out require Promises. These changes look good!

2016-09-22 18:49 UTC, KiChjang commented on components/script/dom/request.rs
> +use dom::bindings::codegen::UnionTypes::HeadersOrByteStringSequenceSequenceOrByteStringMozMap as HeadersInitType;
Hmm... `dom::bindings::codegen::Bindings::RequestBinding` should re-export this union type as `HeadersInit`. Have you tried importing that instead?

2016-09-22 19:13 UTC, jdm commented
I'm going to hold off merging this until after Promises, since there's a lot of overlap between the test result changes.

2016-09-22 21:38 UTC, jeenalee commented on components/script/dom/request.rs
> +use dom::bindings::codegen::UnionTypes::HeadersOrByteStringSequenceSequenceOrByteStringMozMap as HeadersInitType;
You're right! Fixing it right now. Thanks!

2016-09-22 21:39 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #12830) made this pull request unmergeable. Please resolve the merge conflicts.

2016-09-22 21:58 UTC, jdm commented
If you rebase, I will merge :)

2016-09-22 21:58 UTC, jdm commented
Oh, and go ahead and squash the commits into one.

2016-09-22 21:59 UTC, jdm commented
@bors-servo: delegate+

2016-09-22 21:59 UTC, bors-servo commented
:v: @jeenalee can now approve this pull request

2016-09-22 22:05 UTC, jeenalee commented
@bors-servo: r=jdm

2016-09-22 22:05 UTC, bors-servo commented
:pushpin: Commit 3b75d22 has been approved by `jdm`

<!-- @bors-servo r=jdm 3b75d223f111995ffc9bffe7c8516a931b8112f5 -->

2016-09-22 23:15 UTC, bors-servo commented
:hourglass: Testing commit 3b75d22 with merge 68e7ff3...

2016-09-23 00:15 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3298)

2016-09-23 00:15 UTC, highfive commented
▶ Unexpected subtest result in /_mozilla/mozilla/promise.html:
      │ FAIL [expected PASS] Native promise from async callback can be resolved
      │   → assert_true: expected true got false
      │ 
      └ @http://web-platform.test:8000/_mozilla/mozilla/promise.html:58:11

2016-09-23 09:09 UTC, Ms2ger commented
@bors-servo retry

2016-09-23 09:25 UTC, bors-servo commented
:hourglass: Testing commit 3b75d22 with merge 0ecaa77...

2016-09-23 09:40 UTC, bors-servo commented
:hourglass: Testing commit 3b75d22 with merge 06f7a64...

2016-09-23 11:08 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3067), [arm64](http://build.servo.org/builders/arm64/builds/3083), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3137), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3310), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3137), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3134), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3261), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1029)

2016-09-23 11:09 UTC, merged