Return an enum instead of a boolean from dispatch_event
servo/servo pull request #13397
Opened 2016-09-23 15:55 UTC by aochagavia

Fixes #13196

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13196.
- [X] These changes do not require tests because the functionality hasn't changed

2016-09-23 15:55 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2016-09-23 15:55 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/worker.rs, components/script/dom/document.rs, components/script/dom/eventtarget.rs, components/script/dom/eventdispatcher.rs, components/script/dom/event.rs, components/script/dom/dedicatedworkerglobalscope.rs, components/script/dom/htmlscriptelement.rs

2016-09-23 15:55 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-09-23 15:56 UTC, aochagavia commented
An unresolved question is whether `handle_touch_event` should use `EventStatus` as the return value instead of `bool`. The function has some early returns that seem unrelated to Event::fire, so I am unsure if they all mean the same. The current implementation converts the `EventStatus` back into a bool.

2016-09-23 17:36 UTC, aochagavia commented
There is something wrong with the (Windows, GNU) build, but it seems unrelated to this PR

2016-09-23 17:36 UTC, aochagavia commented
r? @Ms2ger

2016-09-23 18:35 UTC, KiChjang commented on components/script/dom/eventdispatcher.rs
> +pub enum EventStatus {
You can derive `PartialEq` here so that you don't need `if let` to match for it.

2016-09-24 09:37 UTC, aochagavia commented on components/script/dom/eventdispatcher.rs
> +pub enum EventStatus {
I actually like `if let`, but if you think it is necessary I could change the code to use `==`

2016-09-26 11:29 UTC, Ms2ger commented on components/script/dom/eventdispatcher.rs
> +pub enum EventStatus {
I agree with @KiChjang here; please do use `==` rather than `if let`.

2016-09-26 11:31 UTC, Ms2ger commented on components/script/dom/eventdispatcher.rs
> +    match event.DefaultPrevented() {
I would suggest adding a method on `Event` that returned this.

2016-09-26 11:31 UTC, Ms2ger commented on components/script/dom/eventtarget.rs
> +        match self.dispatch_event(event) {
Nit: you can use `Ok(match ...)`.

2016-09-26 11:32 UTC, Ms2ger requested changes
Looking good, just needs a few small changes.

2016-09-26 13:43 UTC, aochagavia commented
@Ms2ger Thanks for your feedback! I have pushed the changes.

2016-09-26 14:19 UTC, Ms2ger commented on components/script/dom/event.rs
> +    {
`{` should go on the previous line

2016-09-26 14:21 UTC, Ms2ger commented on components/script/dom/dedicatedworkerglobalscope.rs
> +        if EventStatus::NotCanceled == event_status {
If you want to swap around the left-hand and right-hand sides of these comparisons, I think that would read better. r+ either way, if you fix the other comment below.

2016-09-26 14:21 UTC, Ms2ger requested changes

2016-09-26 15:48 UTC, aochagavia commented on components/script/dom/event.rs
> +    {
Nice catch... Too much C# programming these days...

2016-09-26 15:59 UTC, aochagavia commented
@Ms2ger I pushed new changes, including swapping the comparisons.

2016-09-26 16:01 UTC, Ms2ger commented
Thanks a lot!

@bors-servo r+

2016-09-26 16:01 UTC, bors-servo commented
:pushpin: Commit 6c8bfdb has been approved by `Ms2ger`

<!-- @bors-servo r=Ms2ger 6c8bfdb77467314d9b9cc77e16c7d938794a445f -->

2016-09-26 17:09 UTC, bors-servo commented
:hourglass: Testing commit 6c8bfdb with merge 9b77080...

2016-09-26 18:37 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3133), [arm64](http://build.servo.org/builders/arm64/builds/3148), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3216), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3393), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3202), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3192), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3329), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1097)

2016-09-26 18:37 UTC, merged