Don't crash when #[dom_struct] is applied on an empty struct
servo/servo pull request #13425
Opened 2016-09-26 09:00 UTC by Manishearth

2016-09-26 09:02 UTC, Manishearth commented
r? @emilio

2016-09-26 09:08 UTC, Ms2ger commented on components/plugins/reflector.rs
> +            if def.fields().len()== 0 {
Space before `==`

2016-09-26 09:10 UTC, Ms2ger commented on components/plugins/reflector.rs
> +                cx.span_err(span, "#[dom_struct] should have a reflector or parent dom struct as its first field");
Do we need to return here?

2016-09-26 09:10 UTC, Ms2ger requested changes

2016-09-26 09:13 UTC, Manishearth commented
Fixed both

-Manish Goregaokar

On Mon, Sep 26, 2016 at 11:10 AM, Ms2ger <notifications@github.com> wrote:

> *@Ms2ger* requested changes on this pull request.
> ------------------------------
>
> In components/plugins/reflector.rs
> <https://github.com/servo/servo/pull/13425#pullrequestreview-1498114>:
>
> > @@ -12,6 +12,9 @@ pub fn expand_reflector(cx: &mut ExtCtxt, span: Span, _: &MetaItem, annotatable:
>                          push: &mut FnMut(Annotatable)) {
>      if let &Annotatable::Item(ref item) = annotatable {
>          if let ItemKind::Struct(ref def, _) = item.node {
> +            if def.fields().len()== 0 {
> +                cx.span_err(span, "#[dom_struct] should have a reflector or parent dom struct as its first field");
>
> Do we need to return here?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/servo/servo/pull/13425#pullrequestreview-1498114>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABivSCmnnhfznC-mHvDp9cTiqBMjD5d2ks5qt4wcgaJpZM4KGSXA>
> .
>

2016-09-26 10:07 UTC, emilio commented on components/plugins/reflector.rs
> +            if def.fields().len()== 0 {
Or even better, `def.fields.is_empty()`.

2016-09-26 10:08 UTC, emilio commented
r=me,Ms2ger with or without the `is_empty` thing.

2016-09-26 10:10 UTC, Manishearth commented
@bors-servo r=emilio,Ms2ger

2016-09-26 10:10 UTC, bors-servo commented
:pushpin: Commit 85b65fc has been approved by `emilio,Ms2ger`

<!-- @bors-servo r=emilio,Ms2ger 85b65fc0d3c5e6ceca3f79b24f6e8f3c83a3f136 -->

2016-09-26 11:26 UTC, Ms2ger approved these changes

2016-09-27 11:04 UTC, bors-servo commented
:hourglass: Testing commit 85b65fc with merge 1ed3521...

2016-09-27 12:31 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3159), [arm64](http://build.servo.org/builders/arm64/builds/3173), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3243), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3420), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3227), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3213), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/3352), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1124)

2016-09-27 12:31 UTC, merged