Update WebBluetooth to use Promises
servo/servo pull request #13428
Opened 2016-09-26 09:20 UTC by dati91

Initial patch to support promises in WebBluetooth.
This will allow us to use the expected syntax in webpages.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-09-26 09:20 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/webidls/Bluetooth.webidl, components/script/dom/bluetoothremotegattserver.rs, components/script/dom/webidls/BluetoothRemoteGATTServer.webidl, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/bluetooth.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs, components/script/dom/webidls/BluetoothRemoteGATTCharacteristic.webidl, components/script/dom/webidls/BluetoothRemoteGATTService.webidl, components/script/dom/webidls/BluetoothRemoteGATTDescriptor.webidl

2016-09-26 09:20 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-09-26 09:20 UTC, dati91 commented
r? @jdm

2016-09-26 14:36 UTC, jdm commented on components/script/dom/bluetooth.rs
> +    match bluetooth_result {
```rust
let p = Promise::new(global_ref);
match bluetooth_result {
    Ok(v) => p.resolve_native(v),
    Err(e) => p.reject_error(e),
}
```

2016-09-26 14:38 UTC, jdm commented on components/script/dom/bluetoothremotegattcharacteristic.rs
> +    #[allow(unsafe_code)]
Don't need this and similar ones in this file and other files.

2016-09-26 14:38 UTC, jdm commented on components/script/dom/bluetooth.rs
> +                                                 -> Fallible<Rc<Promise>> {
nit: indentation

2016-09-26 14:41 UTC, jdm commented on components/script/dom/webidls/Bluetooth.webidl
>    [Throws]
This doesn't need to be here anymore, or most (all?) of the other ones in other bluetooth webidl files.

2016-09-26 14:43 UTC, jdm requested changes
Great improvement!

2016-09-26 16:16 UTC, dati91 commented on components/script/dom/webidls/Bluetooth.webidl
>    [Throws]
Do you mean we should remove the Throws/Fallible from the return types?

2016-09-26 16:27 UTC, jdm commented on components/script/dom/webidls/Bluetooth.webidl
>    [Throws]
Specifically, the [Throws] annotation, since none of the methods throw an exception any more.

2016-09-26 18:00 UTC, jdm commented
@bors-servo: delegate+
Just say `@bors-servo: r=jdm` after squashing the commits into one. Thanks!

2016-09-26 18:00 UTC, bors-servo commented
:pushpin: Commit da1d9f9 has been approved by `jdm``

<!-- @bors-servo r=jdm` da1d9f90ad1fffd8c1b22aa4526edfebd2cff6ef -->

2016-09-26 18:00 UTC, bors-servo commented
:v: @dati91 can now approve this pull request

2016-09-26 18:00 UTC, jdm commented
@bors-servo: r-

2016-09-26 18:23 UTC, dati91 commented
@bors-servo: r=jdm

2016-09-26 18:23 UTC, bors-servo commented
:pushpin: Commit e05a839 has been approved by `jdm`

<!-- @bors-servo r=jdm e05a839d25377c9bb0f209f154f0ea998ddc2151 -->

2016-09-27 12:40 UTC, bors-servo commented
:hourglass: Testing commit e05a839 with merge 1ea0924...

2016-09-27 13:32 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3422)

2016-09-27 13:34 UTC, jdm commented
@bors-servo: retry
* #12654

2016-09-28 03:43 UTC, bors-servo commented
:hourglass: Testing commit e05a839 with merge 04f5155...

2016-09-28 03:45 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3231)

2016-09-28 04:01 UTC, KiChjang commented
@bors-servo retry

2016-10-01 10:25 UTC, KiChjang commented
@bors-servo retry

2016-10-01 11:19 UTC, bors-servo commented
:hourglass: Testing commit e05a839 with merge 0c80ac9...

2016-10-01 12:18 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3266), [arm64](http://build.servo.org/builders/arm64/builds/3279), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3354), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3534), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3343), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3323), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/22), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/22), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1229)

2016-10-01 12:19 UTC, merged