Restore the layout trace viewer
servo/servo pull request #13432
Opened 2016-09-26 12:28 UTC by shinglyu

This patch restores the layout trace viewer removed in https://github.com/servo/servo/commit/e7510ab90c3482233ca8b188d748216901041970 , with some changes that makes it work with https://github.com/servo/servo/pull/13214

Sorry for the minified 3rd party CSS frameworks, it was from the original version and I haven't got time to replace them with hand-crafted CSS. 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because is a stand-alone debugging tool

2016-09-26 12:29 UTC, shinglyu commented
I'll also try to update the wiki to document this after the patch merged.

2016-09-26 12:49 UTC, Manishearth commented
r? @mbrubeck

2016-09-26 16:41 UTC, mbrubeck commented on etc/layout_viewer/README
> +./servo --trace-layout <url>
This doesn't seem to work. Should it be removed? Or changed to use `-Z trace-layout`?

2016-09-26 16:42 UTC, mbrubeck commented on etc/layout_viewer/viewer.html
> +                });*/
Should this be removed?

2016-09-26 16:45 UTC, mbrubeck commented on etc/layout_viewer/css/bootstrap-treeview.min.css
> +.list-group-item{cursor:pointer}span.indent{margin-left:10px;margin-right:10px}span.icon{margin-right:5px}
Could you please add `*.min.css` as an excluded filename for the `mach grep` command in `python/servo/devenv_commands.py`? (`*.min.js` is already excluded.)

2016-09-26 16:46 UTC, mbrubeck requested changes
Works great! r=mbrubeck with some minor fixes.

2016-10-17 02:57 UTC, shinglyu commented on etc/layout_viewer/css/bootstrap-treeview.min.css
> +.list-group-item{cursor:pointer}span.indent{margin-left:10px;margin-right:10px}span.icon{margin-right:5px}
Fixed!

2016-10-17 02:59 UTC, shinglyu commented
Rebased to latest master to get rid of the CI failures.

2016-10-17 15:06 UTC, mbrubeck commented
@bors-servo r+

2016-10-17 15:06 UTC, bors-servo commented
:pushpin: Commit 0cab050 has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck 0cab0501f46a17adefbfb704b571244f013b3221 -->

2016-10-17 15:06 UTC, bors-servo commented
:hourglass: Testing commit 0cab050 with merge 0af9be9...

2016-10-17 16:01 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3566), [arm64](http://build.servo.org/builders/arm64/builds/3577), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3643), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/276), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/276), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3644), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3622), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/324), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/326), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1533)

2016-10-17 16:01 UTC, merged