Remove same-origin-data-url flag from fetch implementation
servo/servo pull request #13467
Opened 2016-09-27 20:56 UTC by JanZerebecki

The spec removed it. Check the scheme instead, data is always same origin now,
except for workers.
Closes #13362

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13362 .

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they only remove code.

2016-09-27 20:56 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @pcwalton (or someone else) soon.

2016-09-27 20:56 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/request.rs, components/net/fetch/methods.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/htmlscriptelement.rs, components/net_traits/request.rs, components/net_traits/request.rs

2016-09-27 21:19 UTC, KiChjang commented on components/net/fetch/methods.rs
>      // Step 9
Step annotations for this fetch function needs to be updated to match the spec, I'm afraid.

2016-09-27 22:06 UTC, JanZerebecki commented on components/net/fetch/methods.rs
>      // Step 9
Done.

2016-09-27 22:12 UTC, KiChjang requested changes
Almost done! If you can squash your commits after stylistic nits, I can land this :).

2016-09-27 22:12 UTC, KiChjang commented on components/net/fetch/methods.rs
> +    // Step 7
nit: add a newline before step 7.

2016-09-27 22:12 UTC, KiChjang commented on components/net/fetch/methods.rs
> +    //TODO implement return network_error if not HTTP(S)
nit: space after `//`.

2016-09-27 22:12 UTC, KiChjang commented on components/net/fetch/methods.rs
> +    //TODO implement referrer policy
nit: space after `//`.

2016-09-27 22:20 UTC, JanZerebecki commented on components/net/fetch/methods.rs
> +    // Step 7
The newline is missing intentionally because the previous lines are preparation for Step 7 and not used in Step 6.

2016-09-27 22:24 UTC, JanZerebecki commented on components/net/fetch/methods.rs
> +    //TODO implement return network_error if not HTTP(S)
Done.

2016-09-27 22:25 UTC, JanZerebecki commented on components/net/fetch/methods.rs
> +    //TODO implement referrer policy
Done.

2016-09-27 22:32 UTC, KiChjang commented on components/net/fetch/methods.rs
> +    // Step 7
Then the step annotation should be above the previous line.

2016-09-28 22:23 UTC, JanZerebecki commented on components/net/fetch/methods.rs
> +    // Step 7
Done.

2016-09-28 23:03 UTC, KiChjang commented
@bors-servo r+

Thanks!

2016-09-28 23:03 UTC, bors-servo commented
:pushpin: Commit beaf91d has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang beaf91d70450fa52dd05114e916103ae6510889c -->

2016-09-28 23:03 UTC, KiChjang approved these changes

2016-09-30 11:18 UTC, bors-servo commented
:hourglass: Testing commit beaf91d with merge a014e4b...

2016-09-30 11:22 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3323)

2016-09-30 14:41 UTC, jdm commented
```
error[E0560]: struct `net_traits::request::RequestInit` has no field named `same_origin_data`
  --> /home/servo/buildbot/slave/linux-dev/build/components/script/fetch.rs:47:9
   |
47 |         same_origin_data: request.same_origin_data.get(),
   |         ^^^^^^^^^^^^^^^^

error: attempted access of field `same_origin_data` on type `net_traits::request::Request`, but no field with that name was found
  --> /home/servo/buildbot/slave/linux-dev/build/components/script/fetch.rs:47:27
   |
47 |         same_origin_data: request.same_origin_data.get(),
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: did you mean `omit_origin_header`?
  --> /home/servo/buildbot/slave/linux-dev/build/components/script/fetch.rs:47:35
   |
47 |         same_origin_data: request.same_origin_data.get(),
   |                                   ^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

2016-09-30 14:41 UTC, jdm commented
That code was added in #13323 which only merged yesterday.

2016-10-01 07:27 UTC, KiChjang commented
@bors-servo r+

2016-10-01 07:27 UTC, bors-servo commented
:pushpin: Commit 95a7482 has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 95a7482d26d354e7e02a4309e72d9cd6722e490f -->

2016-10-01 07:52 UTC, bors-servo commented
:hourglass: Testing commit 95a7482 with merge 389a798...

2016-10-01 08:35 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/18)

2016-10-01 10:16 UTC, KiChjang commented
@bors-servo retry
* #13133

2016-10-01 10:19 UTC, bors-servo commented
:hourglass: Testing commit 95a7482 with merge e494ded...

2016-10-01 11:18 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3265), [arm64](http://build.servo.org/builders/arm64/builds/3278), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3353), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3533), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3342), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3322), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/21), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/21), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1228)

2016-10-01 11:19 UTC, merged