Support sequential focus navigation
servo/servo pull request #13460
Opened 2016-09-27 14:19 UTC by nerith

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-09-27 14:19 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/document.rs, components/script/dom/htmlanchorelement.rs, components/script/dom/element.rs

2016-09-27 14:19 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-09-27 14:19 UTC, nerith commented
r? @jdm

2016-10-14 17:15 UTC, jdm commented
I'm really sorry I haven't reviewed this yet. In the interests of allowing it to make progress while I unearth myself from lots of review requests, I'm handing it off.
r? @nox

2016-10-17 08:09 UTC, nox requested changes

2016-10-17 08:09 UTC, nox commented on components/script/dom/document.rs
> +    fn sequential_search(&self, direction: NavigationDirection) -> usize {
This is supposed to return a candidate; shouldn't the return type be `Root<Element>`?

2016-10-17 08:09 UTC, nox commented on components/script/dom/document.rs
> +    fn sequential_search(&self, direction: NavigationDirection) -> usize {
To which behaviour this method correspond in the spec for that algorithm?

2016-10-17 08:09 UTC, nox commented on components/script/dom/document.rs
> +            let key_event = event.downcast::<KeyboardEvent>().unwrap();
Try to downcast to `KeyboardEvent`, and only then check that its type is `keydown`.

2016-10-17 08:09 UTC, nox commented on components/script/dom/element.rs
> +        }
When do you remove focusable elements from the document? Shouldn't that be done in `unbind_from_tree`?

2016-10-17 08:09 UTC, nox commented on components/script/dom/htmlanchorelement.rs
> +    }
Could that change come with a spec link?

2016-10-17 08:09 UTC, nox commented on components/script/dom/htmlanchorelement.rs
> +    fn handle_event(&self, event: &Event) {
You didn't call the super type `handle_event` method.

2016-11-03 18:06 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14043) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-03 20:12 UTC, nerith commented
@KiChjang I'm still working on this. Sorry for the delay. I had hardware issues the past week and was blocked on my machine by issue #13823.

2016-11-16 19:26 UTC, nerith commented
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[components/script/dom/document.rs, line 244 at r3](https://reviewable.io:443/reviews/servo/servo/13460#-KSg00VQMEXjXTVsWI5Q-r3-244:-KUZc0d_nXq0qgm1Hszi:but0nel) ([raw file](https://github.com/servo/servo/blob/acdbb2ee334f7999be71f7c624cb71309a9889fa/components/script/dom/document.rs#L244)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Why `u64` and not `usize`?
</details>
`usize` will work. I don't remember why I made this `u64`.

---

*[components/script/dom/document.rs, line 1703 at r3](https://reviewable.io:443/reviews/servo/servo/13460#-KSg00VQMEXjXTVsWI5Q-r3-1703:-KUZcaychXqLM7jFIFmn:b-8jea7r) ([raw file](https://github.com/servo/servo/blob/acdbb2ee334f7999be71f7c624cb71309a9889fa/components/script/dom/document.rs#L1703)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> To which behaviour this method correspond in the spec for that algorithm?
</details>
This is fixed now. I wasn't sure how to return a `Root<Element>` without getting a compiler error in the original changes. That's why I just returned the index.

Currently, the method is only trying to handle the "sequential" behavior specified in the sequential navigation search algorithm spec. I still need to specify `starting point` and `selection mechanism`.

---

*[components/script/dom/element.rs, line 2217 at r3](https://reviewable.io:443/reviews/servo/servo/13460#-KSg00VRfvdMxWwdx2Ui-r3-2217:-KWi8uxWRbkwCq1HwKYX:b-rzgiw8) ([raw file](https://github.com/servo/servo/blob/acdbb2ee334f7999be71f7c624cb71309a9889fa/components/script/dom/element.rs#L2217)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> When do you remove focusable elements from the document? Shouldn't that be done in `unbind_from_tree`?
</details>
I did not handle removing elements from the ordering list.  I added a function called `remove_focusable_element` in document.rs and call it in `unbind_from_tree` now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13460)*
<!-- Sent from Reviewable.io -->

2016-12-15 19:24 UTC, jdm commented
@nox Review ping.

2017-01-04 00:31 UTC, jdm commented
@nox Post holiday review ping.

2017-01-20 12:01 UTC, nox commented on components/script/dom/htmlanchorelement.rs
> +pub fn follow_hyperlink(subject: &Element, hyperlink_suffix: Option<String>, referrer_policy: Option<ReferrerPolicy>) {
AFAIK this doesn't need to be public.

2017-03-03 11:47 UTC, nox commented
I'll carry this in the next few days.

2017-03-14 09:14 UTC, nox commented
Superseded by #15936, thanks for your contribution!

2017-03-14 09:14 UTC, closed without merging