Don't log in the middle of mutating a reentrant lock
servo/servo pull request #13472
Opened 2016-09-28 03:32 UTC by asajeffrey

Moved assertion that we are the lock owner to after the lock release. The problem is that Servo uses a reentrant lock for logging, so logging in the middle of mutating the lock is A Bad Idea.

While I was at it, I tidied up the reentrant lock code.

cc @jdm 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13463.
- [X] These changes do not require tests because they fix an existing intermittent.

2016-09-28 03:32 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2016-10-01 07:23 UTC, KiChjang commented
r? @jdm

2016-10-01 18:35 UTC, notriddle commented
Could you add this to the [former intermittent file](https://github.com/servo/servo/blob/master/etc/ci/former_intermittents_css.txt)?

2016-10-04 18:54 UTC, jdm requested changes

2016-10-04 18:54 UTC, jdm commented on components/util/remutex.rs
> +        // to do any logging while we hold a re-entrant lock.
```rust
// Make sure we release the lock before checking the assertions.
// We protect logging by a re-entrant lock, so we don't want to
// do any incidental logging while we while the lock is held.
```

2016-10-04 19:07 UTC, jdm commented
Squash commits 1 & 3 and this can merge.

2016-10-04 20:51 UTC, asajeffrey commented
@bors-servo r=jdm

2016-10-04 20:51 UTC, bors-servo commented
:pushpin: Commit 432580b has been approved by `jdm`

<!-- @bors-servo r=jdm 432580bd043c402fad1a1dd428c2921b27456b05 -->

2016-10-04 21:01 UTC, bors-servo commented
:hourglass: Testing commit 432580b with merge 318b23e...

2016-10-04 22:19 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3319), [arm64](http://build.servo.org/builders/arm64/builds/3332), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3408), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/26), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/26), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3396), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3376), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/77), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/76), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1284)

2016-10-04 22:19 UTC, merged