Make readystatechange fire more often (fixes#13481)
servo/servo pull request #13485
Opened 2016-09-28 17:21 UTC by mathieuh

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-09-28 17:21 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @asajeffrey (or someone else) soon.

2016-09-28 17:21 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/xmlhttprequest.rs

2016-09-28 17:21 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-09-28 19:48 UTC, jdm commented
@bors-servo: try

2016-09-28 19:48 UTC, bors-servo commented
:hourglass: Trying commit f3e8cd6 with merge bd0fbd6...

2016-09-28 20:43 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel](http://build.servo.org/builders/linux-rel/builds/3459)

2016-09-28 22:53 UTC, jdm commented
The failing test is the one mentioned in https://github.com/w3c/web-platform-tests/issues/3834.

2016-09-29 23:18 UTC, mathieuh commented
Hi @jdm,

What exactly do you want to do with this test, can't we just disable it?

2016-09-30 14:39 UTC, jdm commented
As part of modifying our implementation, we should update the test to reflect the new specification. We should presumably pass it after modifying it, too.

2016-09-30 22:47 UTC, mathieuh commented
I managed to update the test thanks to @nox

2016-10-03 10:38 UTC, nox commented
@bors-servo try

2016-10-03 10:38 UTC, bors-servo commented
:hourglass: Trying commit 82b51a3 with merge c0a8d2d...

2016-10-03 11:38 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3293), [arm64](http://build.servo.org/builders/arm64/builds/3306), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3381), [linux-rel](http://build.servo.org/builders/linux-rel/builds/3561), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3370), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3350), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/49), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/49), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1256)

2016-10-03 13:31 UTC, jdm commented
We should change the title of the test as well, so as not to confuse matters.

2016-10-03 13:34 UTC, mathieuh commented
@jdm Sure, my bad, it's done.

2016-10-03 14:22 UTC, jdm requested changes
With the one indentation change, this looks fine to merge.

2016-10-03 14:22 UTC, jdm commented on components/script/dom/xmlhttprequest.rs
> +                           EventCancelable::Cancelable);
nit: please indent these lines to line up with `global.r()`.

2016-10-03 14:34 UTC, mathieuh commented on components/script/dom/xmlhttprequest.rs
> +                           EventCancelable::Cancelable);
Updated, tell me if it's ok like that.

2016-10-03 14:46 UTC, jdm commented on components/script/dom/xmlhttprequest.rs
> +                           EventCancelable::Cancelable);
I actually meant indenting 981, 982, and 983 to match the position of `global.r()` on line 980 ;)

2016-10-03 14:47 UTC, nox commented on components/script/dom/xmlhttprequest.rs
> +                           EventCancelable::Cancelable);
We also use that style of indentation in other places, and I think we should prefer it given it reduces the rightwards drift with longer expressions. Are you still blocking on this or are you ok with the current code @jdm?

2016-10-03 14:54 UTC, jdm commented
@bors-servo: r+
Thanks!

2016-10-03 14:54 UTC, bors-servo commented
:pushpin: Commit fe8749e has been approved by `jdm`

<!-- @bors-servo r=jdm fe8749eae68fbcde9bc953a4c1c0b626f5f186cb -->

2016-10-03 16:16 UTC, bors-servo commented
:hourglass: Testing commit fe8749e with merge 2908bfa...

2016-10-03 16:32 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3384)

2016-10-03 17:00 UTC, jdm commented
@bors-servo: retry
* #13563

2016-10-03 17:39 UTC, bors-servo commented
:hourglass: Testing commit fe8749e with merge c7857f0...

2016-10-03 17:54 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3388)

2016-10-04 13:59 UTC, nox commented
@bors-servo retry #13563

2016-10-04 14:46 UTC, bors-servo commented
:hourglass: Testing commit fe8749e with merge d42235e...

2016-10-04 16:11 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3311), [arm64](http://build.servo.org/builders/arm64/builds/3324), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3401), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/18), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/18), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3388), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3368), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/69), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/68), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1276)

2016-10-04 16:11 UTC, merged