A test case change is added to #13442: Fix  #12193 Servo displays upper level Thai character in wrong place.
servo/servo pull request #13506
Opened 2016-09-29 10:59 UTC by veer66

A test case change is added to #13442
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-09-29 10:59 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @larsbergstrom (or someone else) soon.

2016-09-29 10:59 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* This pull request modifies the contents of
`tests/wpt/css-tests/`, which are overwriten occasionally whenever the
directory is synced from upstream.

2016-09-29 11:16 UTC, jdm commented
Rather than modifying the test, it would be better to duplicate it in tests/wpt/mozilla/tests/mozilla.

2016-09-29 11:35 UTC, veer66 commented
@jdm 

- Should I keep file name the same i.e. word-break-break-all-007.htm? 
- If I don't modify tests/wpt/css-tests/css-text-3_dev/html/word-break-break-all-007.htm, can this patch pass this test case?

2016-09-29 11:39 UTC, jdm commented
* Yes
* No

2016-09-29 11:43 UTC, veer66 commented
@jdm So adding a new test case does not solve the issue in #13442?

2016-09-29 11:55 UTC, jdm commented
The issue I'm interested in solving is a lack of tests that fail before the change and pass after it. It doesn't matter to me if the original test still fails, because we know why it fails. Does that make sense?

2016-09-30 05:56 UTC, veer66 commented
That sounds good.

2016-10-29 21:10 UTC, jdm commented
Any progress, @veer66?

2016-12-14 18:50 UTC, KiChjang commented
Looks like this is abandoned, needs a new owner.

2016-12-15 05:13 UTC, veer66 commented
There is no progress. I hope I can resume working on this in 2017.

2017-01-19 21:55 UTC, jdm commented
@bors-servo: try

2017-01-19 21:55 UTC, bors-servo commented
:hourglass: Trying commit 02ee820 with merge e58a522...

2017-01-19 22:38 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1959)

2017-01-19 22:47 UTC, jdm commented
```
  ▶ PASS [expected FAIL] /css-text-3_dev/html/word-break-break-all-007.htm
```
Woooooooo
This is totally ready to merge if word-break-break-all-007.htm.ini is removed.

2017-02-01 19:30 UTC, jdm commented
r? @mbrubeck

2017-02-01 19:42 UTC, mbrubeck requested changes

2017-02-01 19:42 UTC, mbrubeck commented on tests/wpt/mozilla/tests/css/complex_glyphs_ref.html
> +ยิน&#X200Bดี
There's a missing semicolon after `&#X200B;`

2017-02-01 19:43 UTC, mbrubeck commented
r=mbrubeck with that minor bug in the test fixed.

2017-02-01 20:08 UTC, jdm commented
@bors-servo: r=mbrubeck

2017-02-01 20:08 UTC, bors-servo commented
:pushpin: Commit a83fd07 has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck a83fd079df1c824956dc2a692226ef6c8a6be3dc -->

2017-02-01 20:08 UTC, bors-servo commented
:hourglass: Testing commit a83fd07 with merge d161f6e...

2017-02-01 21:03 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5163), [arm32](http://build.servo.org/builders/arm32/builds/5349), [arm64](http://build.servo.org/builders/arm64/builds/5389), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5493), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2175), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2190), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5471), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5507), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2164), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2220), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/631), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/635)

2017-02-01 21:03 UTC, merged