Minimal Win32 font platform implementation.
servo/servo pull request #13567
Opened 2016-10-04 07:04 UTC by glennw

This uses a (very simple) Win32 API call to enumerate font
families available, and load them as byte buffers.

The font rasterization itself is done by freetype.

This gets Servo + WR + Windows working, but should be improved
by adding a proper implementation that matches fonts correctly
and also uses DirectWrite (or GDI) to handle font rasterization.

2016-10-04 07:04 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify gfx code, but no tests are modified. Please consider adding a test!

2016-10-04 07:04 UTC, glennw commented
<img width="782" alt="servo" src="https://cloud.githubusercontent.com/assets/2350882/19065052/91fdb954-8a54-11e6-94bf-f50b81b6554b.png">

2016-10-04 07:04 UTC, glennw commented
r? @vvuk  or @larsbergstrom

2016-10-04 14:09 UTC, jdm commented
cc @aochagavia

2016-10-04 14:12 UTC, aochagavia commented
Awesome!

2016-10-04 16:18 UTC, larsbergstrom requested changes
Just the one issue here - thanks for doing this. It's totally awesome and unblocks MSVC for the nightly!

2016-10-04 16:18 UTC, larsbergstrom commented on components/gfx/platform/windows/font_template.rs
> +                    gdi32::GetFontData(hdc, 0, 0, buffer.as_mut_ptr() as *mut _, size);
Do we need to check the return code here and `panic!` after the `DeleteDC` and `DeleteObject` instead of returning a possibly uninitialized buffer?

2016-10-04 21:47 UTC, glennw commented on components/gfx/platform/windows/font_template.rs
> +                    gdi32::GetFontData(hdc, 0, 0, buffer.as_mut_ptr() as *mut _, size);
Added a (release mode) assert that the returned size matches the required size from the initial call.

2016-10-05 00:56 UTC, larsbergstrom commented
@bors-servo r+

2016-10-05 00:56 UTC, bors-servo commented
:pushpin: Commit 0849607 has been approved by `larsbergstrom`

<!-- @bors-servo r=larsbergstrom 08496072396b2b049ff9b676084ec34a9ba94124 -->

2016-10-05 01:06 UTC, bors-servo commented
:hourglass: Testing commit 0849607 with merge eb3333e...

2016-10-05 02:03 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3324), [arm64](http://build.servo.org/builders/arm64/builds/3337), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3414), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/31), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/31), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3401), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3381), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/82), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/81), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1289)

2016-10-05 02:04 UTC, merged