Use the fetch stack for stylesheets.
servo/servo pull request #13575
Opened 2016-10-04 14:14 UTC by Ms2ger

Fixes #13462.

2016-10-04 14:14 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/htmllinkelement.rs

2016-10-04 14:14 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-10-04 15:03 UTC, jdm requested changes

2016-10-04 15:03 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +            .. RequestInit::default()
This should set `use_url_credentials` to true per https://html.spec.whatwg.org/multipage/infrastructure.html#create-a-potential-cors-request , as well as set mode to Cors.

2016-10-04 15:03 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +            destination: Destination::Style,
The spec says destination should be the empty string, but the table at https://fetch.spec.whatwg.org/#concept-request-type disagrees. I've filed https://github.com/whatwg/html/issues/1856.

2016-10-04 15:03 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +            type_: RequestType::Script,
The spec doesn't specify a type; the table at https://fetch.spec.whatwg.org/#concept-request-type says it should be style.

2016-10-04 15:28 UTC, Ms2ger commented
Done

2016-10-04 18:23 UTC, jdm commented
@bors-servo: r+

2016-10-04 18:23 UTC, bors-servo commented
:pushpin: Commit 2980903 has been approved by `jdm`

<!-- @bors-servo r=jdm 2980903bfb7a0fd1ed92ca5e1bf5aaf29ccb92c6 -->

2016-10-04 23:12 UTC, bors-servo commented
:hourglass: Testing commit 2980903 with merge 710bd7e...

2016-10-05 00:04 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3321), [arm64](http://build.servo.org/builders/arm64/builds/3334), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3411), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/28), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/28), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3398), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3378), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/79), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/78), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1286)

2016-10-05 00:04 UTC, merged