Support SVG element (WIP, DO NOT MERGE)
servo/servo pull request #13589
Opened 2016-10-04 22:42 UTC by splav

minimal SVG element implementation
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12974 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-10-04 22:42 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/tidy/servo_tidy/tidy.py
 * @kichjang: components/script/dom/svggraphicselement.rs, components/script/dom/svgelement.rs, components/script/dom/node.rs, components/script/layout_wrapper.rs, components/script/dom/webidls/SVGGraphicsElement.webidl, components/script/dom/create.rs, components/script_layout_interface/wrapper_traits.rs, components/script/dom/mod.rs, components/script/dom/svgsvgelement.rs, components/script/dom/webidls/SVGSVGElement.webidl, components/script/dom/virtualmethods.rs, components/script_layout_interface/lib.rs, components/script/dom/webidls/SVGElement.webidl

2016-10-04 22:42 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify layout and script code, but no tests are modified. Please consider adding a test!

2016-10-04 22:44 UTC, pcwalton commented on components/layout/fragment.rs
> +    SVG(Box<SVGFragmentInfo>),
nit: name this `Svg`; we follow Rust conventions in layout, not DOM ones

2016-10-04 22:44 UTC, pcwalton commented on components/layout/fragment.rs
> +    /// Returns the original inline-size of the canvas.
Presumably you mean "SVG element" instead of "canvas"?

2016-10-04 22:46 UTC, splav commented
Note: this is WIP. As it required a lot of small modifications in different places I definitely missed something.

2016-10-05 02:13 UTC, Wafflespeanut commented
r? @Ms2ger, @jdm, etc.

2016-10-05 04:26 UTC, splav commented
Yep... I should stop changing code before 1.30am :)

5 окт. 2016 г. 5:17 AM пользователь "Ravi Shankar" <notifications@github.com>
написал:

> *@Wafflespeanut* commented on this pull request.
> ------------------------------
>
> In components/script/dom/create.rs
> <https://github.com/servo/servo/pull/13589#pullrequestreview-2837608>:
>
> >
> -    let prefix = prefix.map(|p| DOMString::from(&*p));
> +    macro_rules! make(
> +        ($ctor:ident) => ({
> +            let obj = $ctor::new(name.local, prefix, document);
> +            Root::upcast(obj)
> +        });
> +        ($ctor:ident, $($arg:expr),+) => ({
> +            let obj = $ctor::new(name.local, prefix, document, $($arg),+);
> +            Root::upcast(obj)
> +        })
> +    );
>
> Instead of duplicating the macro, it could be moved outside the function :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/servo/servo/pull/13589#pullrequestreview-2837608>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AALHIt45mCf8XdtpPbh66vpeabcDlQUpks5qwwjUgaJpZM4KOPVw>
> .
>

2016-10-05 20:28 UTC, splav commented on components/script/dom/create.rs
> +    );
Actually it's not so obvious. If I move macro out of scope I'll lose name.local, prefix, document local vars and should make them arguments. That makes macro mostly useless.

2016-10-05 22:10 UTC, frewsxcv commented
@bors-servo try

2016-10-05 22:10 UTC, bors-servo commented
:hourglass: Trying commit cdbd858 with merge c169252...

2016-10-05 22:47 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/51)

2016-10-05 23:25 UTC, jdm commented
That's just #13593. This shouldn't have any effect on other tests because all the code is preffed off by default.

2016-10-06 12:37 UTC, Ms2ger requested changes
DOM parts seem generally OK to me.

2016-10-06 12:37 UTC, Ms2ger commented on components/script/dom/svggraphicselement.rs
> +        if let Some(ref s) = self.super_type() {
Neither of those methods need to be overridden, I think.

2016-10-06 12:37 UTC, Ms2ger commented on components/script/dom/svgelement.rs
> +    fn bind_to_tree(&self, tree_in_doc: bool) {
Drop those two overrides.

2016-10-06 12:37 UTC, Ms2ger commented on components/script/dom/svgelement.rs
> +use style::element_state::*;
Please avoid glob imports

2016-10-06 12:37 UTC, Ms2ger commented on components/script/dom/create.rs
> +    );
Alright, let's keep it duplicated for now.

2016-10-07 14:59 UTC, Ms2ger approved these changes

2016-10-07 15:00 UTC, Ms2ger commented
r+ on the DOM parts; it's not clear to me if everything else has been reviewed.

2016-10-07 18:23 UTC, pcwalton approved these changes
r=me with nits

2016-10-07 18:23 UTC, pcwalton commented on components/layout/fragment.rs
> +pub struct SVGFragmentInfo {
nit: name this `SvgFragmentInfo`

2016-10-07 18:55 UTC, jdm commented
@bors-servo: r=pcwalton,Ms2ger

2016-10-07 18:55 UTC, bors-servo commented
:pushpin: Commit 1f0b9ab has been approved by `pcwalton,Ms2ger`

<!-- @bors-servo r=pcwalton,Ms2ger 1f0b9ab3b7a6f0c8949fa9a78138a72e66393014 -->

2016-10-07 19:10 UTC, bors-servo commented
:hourglass: Testing commit 1f0b9ab with merge eb47b99...

2016-10-07 19:54 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/86)

2016-10-07 19:54 UTC, highfive commented
▶ FAIL [expected PASS] /_mozilla/css/inline_block_opacity_change.html
      └   → /_mozilla/css/inline_block_opacity_change.html aed6845267bba6c52d3aa69c4889449b454d8117
    /_mozilla/css/inline_block_opacity_change_ref.html febec1b4730afab195f280694dad47200b09ea3c
    Testing aed6845267bba6c52d3aa69c4889449b454d8117 == febec1b4730afab195f280694dad47200b09ea3c

2016-10-07 19:59 UTC, jdm commented
@bors-servo: retry
* #13360

2016-10-07 20:57 UTC, bors-servo commented
:hourglass: Testing commit 1f0b9ab with merge 3f2e857...

2016-10-07 21:30 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/139)

2016-10-07 21:44 UTC, jdm commented
@bors-servo: retry
* #13645

2016-10-07 22:40 UTC, bors-servo commented
:hourglass: Testing commit 1f0b9ab with merge dad3b47...

2016-10-07 23:33 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3383), [arm64](http://build.servo.org/builders/arm64/builds/3396), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3470), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/90), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/90), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3460), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3442), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/141), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/141), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1348)

2016-10-07 23:33 UTC, merged