Provide the fetched data to fetch() consumers.
servo/servo pull request #13597
Opened 2016-10-05 13:28 UTC by Ms2ger

2016-10-05 13:28 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/request.rs, components/script/fetch.rs, components/script/dom/response.rs, components/script/body.rs

2016-10-05 13:28 UTC, Ms2ger commented
@bors-servo try

2016-10-05 13:28 UTC, bors-servo commented
:hourglass: Trying commit 7ac1910 with merge e447d56...

2016-10-05 13:44 UTC, jdm requested changes

2016-10-05 13:44 UTC, jdm commented on components/script/dom/request.rs
> +        assert!(mem::replace(&mut *self.body_promise.borrow_mut(), Some((p.clone(), body_type))).is_none());
Same as later comment.

2016-10-05 13:44 UTC, jdm commented on components/script/dom/response.rs
> +        assert!(mem::replace(&mut *self.body_promise.borrow_mut(), Some((p.clone(), body_type))).is_none());
This is a complicated way of writing
```rust
assert!(self.body_promise.borrow().is_none());
*self.body_promise.borrow_mut() = Some(p.clone(), body_type);
```
which I would prefer.

2016-10-05 13:44 UTC, jdm commented on components/script/body.rs
> +#[allow(unrooted_must_root)]
Is this necessary?

2016-10-05 13:44 UTC, jdm commented on components/script/body.rs
> +    if let Some(body) = object.take_body() {
```rust
let body = match object.take_body() {
    Some(body) => body,
    None => return,
};
```

2016-10-05 14:00 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/92)

2016-10-05 14:37 UTC, Ms2ger commented
@bors-servo try

2016-10-05 14:37 UTC, bors-servo commented
:hourglass: Trying commit c805e3b with merge 1a28907...

2016-10-05 15:09 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/43)

2016-10-05 15:14 UTC, jdm commented
We probably need a compartment for the JSON case.

2016-10-06 10:00 UTC, Ms2ger commented
@bors-servo try

2016-10-06 10:00 UTC, bors-servo commented
:hourglass: Trying commit 8f6a0b7 with merge 3ca06c1...

2016-10-06 10:32 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/107)

2016-10-06 12:36 UTC, jdm commented
@bors-servo: r+

2016-10-06 12:36 UTC, bors-servo commented
:pushpin: Commit cd47e21 has been approved by `jdm`

<!-- @bors-servo r=jdm cd47e214f0fef017cf6d571235676f6e8f17eba3 -->

2016-10-06 13:20 UTC, Ms2ger commented
@bors-servo p=1

2016-10-06 13:57 UTC, bors-servo commented
:hourglass: Testing commit cd47e21 with merge 113ef4c...

2016-10-06 14:46 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3411)

2016-10-06 15:00 UTC, Ms2ger commented
@bors-servo retry

2016-10-06 15:25 UTC, bors-servo commented
:hourglass: Testing commit cd47e21 with merge 0d25bc9...

2016-10-06 15:50 UTC, larsbergstrom commented
@bors-servo clean force retry 
 - infra buildbot restart

2016-10-06 15:56 UTC, bors-servo commented
:hourglass: Testing commit cd47e21 with merge f1c3288...

2016-10-06 16:13 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3443)

2016-10-06 16:17 UTC, Ms2ger commented
Oh what the hell:
```
LLVM ERROR: IO failure on output stream.
```
twice on servo-linux2

@larsbergstrom ?

2016-10-06 16:24 UTC, larsbergstrom commented
@Ms2ger disk full, please retry.

2016-10-06 16:30 UTC, larsbergstrom commented
@bors-servo retry
- infra

2016-10-06 17:34 UTC, bors-servo commented
:hourglass: Testing commit cd47e21 with merge bd05aa2...

2016-10-06 18:27 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3355), [arm64](http://build.servo.org/builders/arm64/builds/3368), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3445), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/62), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/62), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3432), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3414), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/113), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/113), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1320)

2016-10-06 18:27 UTC, merged