Support multiprocess constellation on Windows
servo/servo pull request #13609
Opened 2016-10-06 00:45 UTC by vvuk

Allow `-M` on windows to use multiprocess mode.  Sandboxing is still disallowed, as `gaol` is not implemented on Windows.  This depends on https://github.com/servo/ipc-channel/pull/108 to provide windows support in ipc-channel.  At the moment this causes a panic in ipc-channel when run with multiprocess (works fine single process), but I wanted to put this up so that others can test.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-10-06 00:45 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/pipeline.rs

2016-10-13 12:26 UTC, jdm requested changes

2016-10-13 12:26 UTC, jdm commented on components/constellation/pipeline.rs
> +    // without sandboxing
My preference would be to add a cfg block to the existing non-Windows code rather than duplicating the non-sandbox pieces here.

2016-10-20 17:24 UTC, vvuk commented on components/constellation/pipeline.rs
> +    // without sandboxing
The reason I didn't do that is that we don't have the `gaol` crate available on Windows at all.  `cfg!(...)` evaluates to a boolean, so the types would still need to be available for both paths through the function.  Is there a way to do this that I'm not seeing?  The only other way I could think of was to create separate spawn_sandboxed() and spawn_unsandboxed() methods that spawn_multiprocess calls, and then have a windows-only spawn_sandboxed that panics.

With my latest changes at https://github.com/servo/ipc-channel/pull/108, multiprocess Servo works on Windows.

2016-12-14 20:13 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14536) made this pull request unmergeable. Please resolve the merge conflicts.

2017-03-03 11:47 UTC, nox commented
@jdm Are you ok with repeating these few lines of code for now? Should we land this?

2017-03-03 18:20 UTC, jdm commented
We need https://github.com/servo/ipc-channel/pull/108 to merge before this can. I'm ok with the code duplication.

2017-11-15 22:18 UTC, jdm commented
No need to keep this open indefinitely.

2017-11-15 22:18 UTC, closed without merging