layout: Implement `vertical-align: middle` per CSS 2.1 § 10.8.1.
servo/servo pull request #13602
Opened 2016-10-05 18:31 UTC by pcwalton

This also includes a test for the popular inline-block centering
technique described here:
https://s.codepen.io/shshaw/fullpage/gEiDt?#Inline-Block

r? @notriddle

2016-10-05 18:32 UTC, pcwalton commented
r? @mbrubeck

2016-10-05 19:03 UTC, emilio commented
@bors-servo: try

I'm surprised not to see the `x_height` of the font involved here, since it's explicitly mentioned in the spec, but maybe you're doing something smart with the font metrics?

2016-10-05 19:03 UTC, bors-servo commented
:hourglass: Trying commit faef393 with merge 336f014...

2016-10-05 19:38 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/48)

2016-10-05 19:39 UTC, highfive commented
▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox-flex-direction-default.htm
    
      ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox-flex-direction-row.htm
    
      ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox-flex-direction-row-reverse.htm
    
      ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox-flex-wrap-wrap-reverse.htm
    
      ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox-flex-wrap-wrap.htm

2016-10-05 20:38 UTC, pcwalton commented
Updated to mark tests as newly passing. r? @mbrubeck

2016-10-05 20:58 UTC, mbrubeck requested changes

2016-10-05 20:58 UTC, mbrubeck commented on components/layout/inline.rs
> +                            line_block_metrics.size.scale_by(0.5) +
As @emilio said, I think this should use the x-height.

2016-10-05 20:58 UTC, mbrubeck commented on components/layout/inline.rs
> +                            fragment_inline_metrics.depth_below_baseline.scale_by(0.5)
Should this be `fragment.border_box.size.block.scale_by(0.5)` to find the middle of the fragment?  Currently if the fragment is an `<img>` whose height is different from the line height, it doesn't align correctly.

2016-10-08 02:02 UTC, pcwalton commented
Here's the rewrite! See commits for details.

r? @mbrubeck

2016-10-08 03:26 UTC, frewsxcv commented
```
The command "bash etc/ci/manifest_changed.sh" exited with 1.
```

2016-10-08 19:04 UTC, jdm commented
Looks like a bunch of missing reftest `<link>` attributes.

2016-10-11 17:49 UTC, mbrubeck commented
Looks good! r=mbrubeck with one minor improvement suggestion (below).

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 13 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 35 of 35 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/fragment.rs, line 2244 at r5](https://reviewable.io:443/reviews/servo/servo/13602#-KToplC6EG1AecPt_eyO:-KToplC7DtyDrxYRh8OV:b-n556dh) ([raw file](https://github.com/servo/servo/blob/15ed039856bb7c7df97f8217ddece64b8e046ba2/components/layout/fragment.rs#L2244)):*
> ```Rust
>                                  actual_line_metrics: Option<&LineMetrics>)
>                                  -> Au {
>         // FIXME(pcwalton): Cache `self.content_inline_metrics()` if we need it multiple times?
> ```

You could just pass in the `content_inline_metrics` from the caller (`aligned_inline_metrics`, below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13602#-:-KToqpPc5ZtlxYQ_nN9B:btbk07k)*
<!-- Sent from Reviewable.io -->

2016-10-11 20:00 UTC, pcwalton commented
@bors-servo: r=mbrubeck

2016-10-11 20:00 UTC, bors-servo commented
:pushpin: Commit 773614f has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck 773614f84c679aac2a7fd455f706e59d8222a967 -->

2016-10-11 20:33 UTC, bors-servo commented
:hourglass: Testing commit 773614f with merge 768a699...

2016-10-11 21:26 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3462), [arm64](http://build.servo.org/builders/arm64/builds/3474), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3547), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/168), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/169), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3539), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3518), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/220), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/220), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1427)

2016-10-11 21:26 UTC, merged