Replacing Node.rootNode for Node.getRootNode.
servo/servo pull request #13703
Opened 2016-10-11 20:24 UTC by Rafagd

- Changed the specification for the Node element to reflect the new standard.
- Changed the implementation of the NodeMethod.

I'm still waiting for some answers for the questions I've posted on #13699, but I'm already doing the pull request so I can get some feedback as well.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13699 (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-10-11 20:24 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @mbrubeck (or someone else) soon.

2016-10-11 20:24 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/node.rs, components/script/dom/webidls/Node.webidl

2016-10-11 20:24 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-10-13 10:36 UTC, Ms2ger requested changes

2016-10-13 10:36 UTC, Ms2ger commented on components/script/dom/webidls/Node.webidl
> +  Node getRootNode(optional GetRootNodeOptions options);
I would prefer if you declared this as `Node getRootNode();`, without the argument. That makes it more obvious that the argument is not implemented yet.

2016-10-13 14:13 UTC, Rafagd commented on components/script/dom/webidls/Node.webidl
> +  Node getRootNode(optional GetRootNodeOptions options);
ok

2016-10-13 15:21 UTC, Ms2ger commented
Code looks good, but I expect we'll need to update some test expectations.

@bors-servo try

2016-10-13 15:21 UTC, bors-servo commented
:hourglass: Trying commit 7b68746 with merge 3da821c...

2016-10-13 16:00 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/273)

2016-10-13 16:38 UTC, Rafagd commented
@Ms2ger Is there a way for me to only run the failed tests?

2016-10-13 17:04 UTC, KiChjang commented
@Rafagd You need to update the test expectations located in `tests/wpt/metadata/dom/interfaces.html.ini` and `tests/wpt/metadata/dom/nodes/rootNode.html`.

2016-10-13 17:17 UTC, Rafagd commented
Oh, now I get it. Working on it.

2016-10-13 18:28 UTC, KiChjang requested changes
By default, all tests are expected to PASS. You can simply remove the lines of code where it's expected to FAIL instead of changing them to PASS.

2016-10-13 18:48 UTC, KiChjang commented
@bors-servo try

2016-10-13 18:48 UTC, bors-servo commented
:hourglass: Trying commit 00dca6c with merge 9d408f4...

2016-10-13 19:00 UTC, Rafagd commented
@KiChjang I'm removing the PASS tests now

2016-10-13 19:08 UTC, KiChjang commented
Yes.

2016-10-13 19:22 UTC, KiChjang commented
@bors-servo try

2016-10-13 19:22 UTC, bors-servo commented
:hourglass: Trying commit 53a6182 with merge 1ba7e59...

2016-10-13 21:01 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3523), [arm64](http://build.servo.org/builders/arm64/builds/3533), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3601), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/229), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/229), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3600), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3578), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/281), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/280), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1488)

2016-10-13 21:16 UTC, KiChjang commented
@Rafagd You'll now need to squash all your commits into one, and we're ready to land this!

2016-10-14 09:49 UTC, Rafagd commented
Everything is squashed into a single commit now.

2016-10-14 15:59 UTC, Ms2ger commented
Thanks!

@bors-servo r+

2016-10-14 15:59 UTC, bors-servo commented
:pushpin: Commit 0074d2a has been approved by `Ms2ger`

<!-- @bors-servo r=Ms2ger 0074d2a7a8b3bc40f96238347e021670528165a8 -->

2016-10-14 16:35 UTC, bors-servo commented
:hourglass: Testing commit 0074d2a with merge fbe96d1...

2016-10-14 17:10 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/246)

2016-10-14 17:10 UTC, highfive commented
▶ FAIL [expected PASS] /_mozilla/css/inline_block_opacity_change.html
      └   → /_mozilla/css/inline_block_opacity_change.html aed6845267bba6c52d3aa69c4889449b454d8117
    /_mozilla/css/inline_block_opacity_change_ref.html febec1b4730afab195f280694dad47200b09ea3c
    Testing aed6845267bba6c52d3aa69c4889449b454d8117 == febec1b4730afab195f280694dad47200b09ea3c

2016-10-14 17:11 UTC, KiChjang commented
@bors-servo retry
* #13360

2016-10-14 19:07 UTC, bors-servo commented
:hourglass: Testing commit 0074d2a with merge 697e197...

2016-10-14 19:46 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/248)

2016-10-14 19:48 UTC, KiChjang commented
@bors-servo retry
* #13775

2016-10-14 19:48 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/3541), [arm64](http://build.servo.org/builders/arm64/builds/3552), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3619), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/250), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3619), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/299), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1508) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/248), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3597), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/301)...

2016-10-14 20:46 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3541), [arm64](http://build.servo.org/builders/arm64/builds/3552), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3619), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/250), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/250), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3619), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3597), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/299), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/301), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1508)

2016-10-14 20:46 UTC, merged