[WIP] Fiix referrer policy tests for a-tag
servo/servo pull request #13713
Opened 2016-10-12 08:24 UTC by TheKK

This RP tries to fix referrer policy test for <a> which was introduced in #12493 (sorry for my silly mistake). But the fact that Servo lakes of some functionalities make these tests a little tricky to do.

The desired solution for tests for <a> is to:

1. create a document which is running test harness
2. append an `<iframe>` to its parent document and give it a name
3. append and `<a>` to its parent document and set its `target` as `<iframe>`'s name
4. each referrer policy attribute (eg. HTTP header, <meta>) would contribute to `<a>` directly
5. we call `click()` on `<a>` and when the test was done, we call `postMessage()` inside `<iframe>` to notify its parent document

And target feature for `<a>` and cross origin `postMessage()` is still on its way. My solution is:

1. create a document which is running test harness
2. append an `<iframe>` to its parent document
3. append and `<a>` into `<iframe>`
4. we call `click()` on `<a>` and `<iframe>` navigate to `<a>`'s href

Current solution does not work for some cases:

- HTTP header, it only apply to test harness html document but `<a>` inside `<iframe>`
- cross origin detection, we navigate `<iframe>` rather than its parent document, which make test expectation wrong

One workaround in my mind is to load our test harness html document **inside** `<iframe>` under sandbox, so the test won't run again and we get `<meta>` and HTTP header as we expect. But this would break some consistency in `common.js` and make thing more complex.

----
Sorry for the long description. But I'd like to hear more thought before I actually make things dirty, and find the most proper solution for this.

2016-10-13 09:46 UTC, Ms2ger commented
r? @jdm

2016-10-14 17:22 UTC, jdm commented
What if instead of loading a-tag.html directly in the iframe, we load a python script which reads a-tag.html and optionally provides the Referrer-Policy header as well?

2016-10-14 17:36 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/subresource/a-tag.html
> +        // TODO crashed when you assigned value to rel attribute
I think this isn't necessary any more after #12799 was fixed.

2016-10-14 17:36 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/subresource/a-tag.html
> +      if (meta_referrer !== "undefined") {
We could move all of the dynamic page changes into the python script if we used it (just do string replacement on stuff like `<!-- a tag -->`. Not sure if that's better or not.

2016-10-14 17:36 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/common.js
>          // TODO crashed when you assigned value to rel attribute
I don't think this is true after #12799 was fixed.

2016-10-14 17:37 UTC, jdm commented
I'm not clear on why the cross-origin situation isn't working - I thought that was why we were using the python stash to communicate, since cross-origin postMessage doesn't exist yet.

2016-10-15 15:53 UTC, TheKK commented on tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/subresource/a-tag.html
> +      if (meta_referrer !== "undefined") {
This sounds like a reasonable solution. I'll give it a try!

2016-10-15 16:37 UTC, TheKK commented
> I'm not clear on why the cross-origin situation isn't working

Say that we have:
  - resource A: insecure-protocol.no-redirect.http.html
  - resource B: a-tag.html
  - resource C: document.py

Normally, we read `resource A` in and some element like `<link>` load `resource C`. For `resource C` its referrer would be `resource A`.

But for tests of `<a>` this isn't true, since we load `resource B` into iframe then navigate to `resource C`. Its referrer becomes `resource B` instead of `resource A`.

2016-10-15 16:57 UTC, jdm commented
Oh, I see. Which part of the test harness gets confused by that?

2016-10-15 18:01 UTC, TheKK commented
As I know, some tests for `<a>` with **origin-when-cross-origin** would be confuse

2016-10-15 18:30 UTC, jdm commented
Right, but which part of the test harness code receives the wrong URL as the reference? Is there some way we could modify the tests to pass a different URL for the `<a>` tests?

2016-10-15 20:06 UTC, TheKK commented
Maybe we can modify 

```javascript
      /* referrer-policy-test-case.js */

      /* eg. http://www1.web-platform.test:8000/_mozilla/mozilla/referrer-policy/generic/subresource/a-tag.html?redirection=no-redirect&cache_destroyer=1476561407449 */
      t._subresourceUrl = t._scenario.target_protocol + "://" +
                          domainForOrigin[t._scenario.origin] +
                          normalizePort(targetPort) +
                          t._scenario["subresource_path"] +
                          "?redirection=" + t._scenario["redirection"] +
                          "&cache_destroyer=" + (new Date()).getTime();
```

and

```javascript
      /* a-tag-html */
      var a = document.createElement("a");
      a.href = "/_mozilla/mozilla/referrer-policy/generic/subresource/document.py" +
        "?id=" + id +
        "&redirection=" + redirection +
        "&cache_destroyer=" + cache_destroyer;
```

to delay the origin changing for `<a>` test. I'll try this and see how it going tomorrow.

2016-10-28 17:37 UTC, TheKK commented
Is there any way I can inspect the referrer policy when it was delivered by HTTP header to test harness document? I successfully delivered referrer policy via HTTP header to loading `document.py` but I can't infer the policy the test like to apply.

2016-10-31 17:00 UTC, jdm commented
I do not believe so. Maybe we could add a meta element to every test that contains the test's referrer policy?

2017-03-03 11:46 UTC, nox commented
@jdm @TheKK So what do we do here?

2017-03-03 19:20 UTC, jdm commented
I'll take a look at addressing the previous question sometime in the next few days.

2017-03-06 03:28 UTC, jdm commented
I have a commit that makes the HTTP header tests pass at https://github.com/jdm/servo/commit/0819c96ff8825a3a62c44d176f46e2bd40d63c74. @TheKK Are you still interested in finishing up this work?

2017-03-06 03:55 UTC, TheKK commented
Sure! Give me some time to recap my work :)

2017-03-24 10:51 UTC, nox commented
@TheKK Ping? :)

2017-03-24 13:31 UTC, TheKK commented
@nox sorry that I only had a little spare time working on this issue in the last busy weeks. Since the storm has passed I can finally resume my work next day :)

2017-03-24 13:31 UTC, nox commented
No problem, just a friendly ping.

2017-03-25 19:23 UTC, TheKK commented
@jdm Do you mind me apply your change directly?

Since I left this PR for 5 months, I'd like to double check I'm on the correct path:

- all test with referrer policy deliver by `content attribute` should fail for now. (that's why I'm working on #11861)
- all test with referrer policy deliver by `meta-csp` should fail.
- all test with referrer policy deliver by `http header`, `meta-referrer` and `relation` should pass.

Technically this issue has been fixed thanks to jdm's help. I'll clean up mess, add some comments if necessary and make sure that I won't introducing any defects this time. And hopefully, this PR should be able to be merged after that. :)

2017-03-26 12:07 UTC, jdm commented
That summary looks correct to me. Please go ahead and merge my changes with your existing ones!

2017-03-27 14:15 UTC, TheKK commented
I've clean my previous changes and squashed them into single commit. It should be ready to be reviewed.

One thing that confuses me is the naming style to use in `common.js ` because there exists both snake_case and camelStyle. Please let me know If camel style is proper choice so that I can fix that.

2017-03-27 14:34 UTC, jdm requested changes
Three small changes; otherwise this looks good to go!

2017-03-27 14:34 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/subresource/a-tag.html
> +        if (attr === "rel") {
We should not need this special-case any longer.

2017-03-27 14:34 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/common.js
>          // TODO crashed when you assigned value to rel attribute
Let's get rid of this special-case.

2017-03-27 14:34 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/referrer-policy/generic/subresource/mozresource.py
> +        response.writer.write_header("Referrer-Policy",
Let's make this `referrer-policy` to match the style of the other headers in this file.

2017-03-28 06:08 UTC, TheKK commented
Opps, seem like that `rel` attribute on `<a>` has not yet been implemented. I'll summit another PR to fix that.

2017-03-30 00:40 UTC, jdm commented
@bors-servo: delegate=TheKK
This can merge after #16170 merges and the test expectations are updated appropriately.

2017-03-30 00:40 UTC, bors-servo commented
:v: @TheKK can now approve this pull request

2017-03-31 04:03 UTC, TheKK commented
@bors-servo: r+

2017-03-31 04:03 UTC, bors-servo commented
:pushpin: Commit 53cc3d3 has been approved by `TheKK`

<!-- @bors-servo r=TheKK 53cc3d3b19fd6872bb98abf57e88048cc1425b02 -->

2017-03-31 04:26 UTC, bors-servo commented
:hourglass: Testing commit 53cc3d3b19fd6872bb98abf57e88048cc1425b02 with merge 32a42d860e6f1eea9d21c747e839616fe9d94c4c...

2017-03-31 04:39 UTC, bors-servo commented
:broken_heart: Test failed - [arm64](http://build.servo.org/builders/arm64/builds/6318)

2017-03-31 05:09 UTC, jdm commented
Ah, this needs `./mach update-manifest`.

2017-03-31 05:55 UTC, TheKK commented
totally forgot that...

2017-03-31 12:15 UTC, jdm commented
@bors-servo: r+

2017-03-31 12:15 UTC, bors-servo commented
:pushpin: Commit 4b39ffe has been approved by `jdm`

<!-- @bors-servo r=jdm 4b39ffe82959fe9dabe5f2bdc40bdc4cab9a9078 -->

2017-03-31 12:16 UTC, bors-servo commented
:hourglass: Testing commit 4b39ffe82959fe9dabe5f2bdc40bdc4cab9a9078 with merge b09aab76834c83bcdfbe1eb2533cebd0a2116769...

2017-03-31 13:36 UTC, TheKK commented
> {"status": "CRASH", "stack": null, "subtest": null, "action": "test_result", "test": "/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-2.html", "line": 199059, "message": null, "expected": "ERROR"}

hmm, I rebased to latest commit, recompiled, tried this test on my machine and got "ERROR" which is expected result. And idea?

2017-03-31 14:41 UTC, jdm commented
That's just #14323 and can be ignored.

2017-03-31 14:41 UTC, jdm commented
@bors-servo: r+

2017-03-31 14:41 UTC, bors-servo commented
:pushpin: Commit 0edab51 has been approved by `jdm`

<!-- @bors-servo r=jdm 0edab51f05fe4749075d35393e87d24ddbd23842 -->

2017-03-31 14:46 UTC, bors-servo commented
:hourglass: Testing commit 0edab51f05fe4749075d35393e87d24ddbd23842 with merge 3f83628fa9362624968a7efccd8fa6f8c6a9aa7d...

2017-03-31 15:22 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6071), [arm32](http://build.servo.org/builders/arm32/builds/6291), [arm64](http://build.servo.org/builders/arm64/builds/6324), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6426), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3157), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3179), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6430), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6460), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3116), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3181), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1599)
Approved by: jdm
Pushing 3f83628fa9362624968a7efccd8fa6f8c6a9aa7d to master...

2017-03-31 15:22 UTC, merged