layout: Use the margin box for vertical positioning of `inline-block` fragments if `overflow` is not `visible` per CSS 2.1 § 10.8.1.
servo/servo pull request #13732
Opened 2016-10-12 19:23 UTC by pcwalton

Additionally, this patch reverts the change introduced in #12642 in
favor of the spec-compliant behavior described above. This patch also
removes the `inline_block_overflow.html` reftest introduced in #3725, as
the behavior it expected contradicted CSS 2.1 (and in fact the test
fails in Gecko).

The changes that this patch makes to `input_selection_a.html` and
`input_selection_incremental_a.html` are necessary workarounds to make
the tests pass in light of the fact that Servo's UA stylesheet applies
`overflow: hidden` to `<input>` elements. I believe that the changes are
not necessary in other rendering engines because they hard-code
`overflow: hidden`-like behavior for `<input>` elements, while Servo
uses the actual CSS `overflow: hidden` behavior. As far as I can tell,
Servo's behavior is arguably more spec-compliant, but it remains to be
seen how Web compatible it is.

Improves the Google results pages.

Closes #13707.

r? @notriddle

2016-10-12 19:38 UTC, notriddle requested changes

2016-10-12 19:38 UTC, notriddle commented on tests/wpt/mozilla/tests/css/input_selection_ref.html
> +        color: white;
Remove the `color:black` declaration.

2016-10-12 20:38 UTC, pcwalton commented
@notriddle Done. r?

2016-10-12 20:43 UTC, notriddle approved these changes

2016-10-12 20:43 UTC, notriddle commented
@bors-servo r+

2016-10-12 20:43 UTC, bors-servo commented
:pushpin: Commit 79de34b has been approved by `notriddle`

<!-- @bors-servo r=notriddle 79de34b272ba7689ab99d7827c2c064f96fab6ad -->

2016-10-13 09:28 UTC, bors-servo commented
:hourglass: Testing commit 79de34b with merge 576aa97...

2016-10-13 10:33 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/215)

2016-10-13 10:33 UTC, highfive commented
▶ Unexpected subtest result in /html/webappapis/scripting/event-loops/microtask_after_raf.html:
      └ PASS [expected FAIL] Microtask execute immediately after script

2016-10-13 10:56 UTC, jdm commented
@bors-servo: retry
* #13501

2016-10-13 12:08 UTC, bors-servo commented
:hourglass: Testing commit 79de34b with merge d465940...

2016-10-13 12:46 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/218)

2016-10-13 12:46 UTC, highfive commented
▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_box-clear.htm

2016-10-13 16:10 UTC, notriddle commented
```
13.0909 < notriddle> crowbot: is flexbox_box-clear.htm intermittent?
13.0909 < crowbot> No intermittent issues filed with 'flexbox_box-clear.htm' in 
                   the title
```

2016-10-13 16:36 UTC, pcwalton commented
@bors-servo: r=notriddle

2016-10-13 16:36 UTC, bors-servo commented
:pushpin: Commit c25dd2a has been approved by `notriddle`

<!-- @bors-servo r=notriddle c25dd2adf6f849f074af959a6ef81d6868d22e91 -->

2016-10-13 17:06 UTC, bors-servo commented
:hourglass: Testing commit c25dd2a with merge bbcc743...

2016-10-13 17:51 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3517), [arm64](http://build.servo.org/builders/arm64/builds/3529), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3597), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/225), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/224), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3595), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3574), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/275), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/276), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1483)

2016-10-13 17:51 UTC, merged