[WIP] Use the fetch stack for documents.
servo/servo pull request #13742
Opened 2016-10-13 09:24 UTC by Ms2ger

2016-10-13 09:24 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/script_thread.rs, components/script/dom/document.rs, components/script/dom/servoparser/mod.rs, components/script/document_loader.rs

2016-10-13 09:24 UTC, Ms2ger commented
@bors-servo try

2016-10-13 09:24 UTC, bors-servo commented
:hourglass: Trying commit d97ae85 with merge 45ab9d5...

2016-10-13 09:55 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/265)

2016-10-14 09:35 UTC, Ms2ger commented
@bors-servo try

2016-10-14 09:35 UTC, bors-servo commented
:hourglass: Trying commit 19bd43f with merge c8cdccb...

2016-10-14 10:09 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/242)

2016-10-14 13:10 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13750) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-14 14:14 UTC, Ms2ger commented
Status update: investigating the timeout in `/_mozilla/mozilla/referrer-policy/unset-referrer-policy/meta-referrer/same-origin/http-https/iframe-tag/upgrade-protocol.keep-origin-redirect.http.html`. Apparently the load event is not dispatched at the iframe created in `queryIframe`.

2016-10-18 10:20 UTC, Ms2ger commented
The issue lies within this lovely piece of code:
```rust
        let mut ssl_error = None;
        let metadata = match meta_result {
            Ok(meta) => Some(meta),
            Err(NetworkError::SslValidation(url, reason)) => {
                ssl_error = Some(reason);
                let mut meta = Metadata::default(url);
                let mime: Option<Mime> = "text/html".parse().ok();
                meta.set_content_type(mime.as_ref());
                Some(meta)
            },
            Err(_) => None,
        };
```

With the old stack, we get `Err(NetworkError::SslValidation(..))`, create a new `Metadata` and go on our merry way. With the fetch stack, we get some other `Err(..)` value, `ScriptThread::page_headers_available` notices `metadata` is `None` and returns `None` itself, so we bail out without a parser object, and the load event is never fired.

@jdm, thoughts?

2016-10-18 14:30 UTC, jdm commented
I propose that we modify the `ResponseType::Error` variant to store a `NetworkError` value, and modify the block in `http_network_fetch` that gets an Err value from `obtain_response` to turn the response into an error response that contains the actual error that was returned from the network stack. This will allow the `metadata` method to return an error that was extracted from the error response, rather than just returning an internal error.

2016-10-18 16:13 UTC, Ms2ger commented
Rebased; planning to look into your suggestion tomorrow. Thanks!

2016-10-19 13:11 UTC, Ms2ger commented
@bors-servo try

2016-10-19 13:11 UTC, bors-servo commented
:hourglass: Trying commit addec42 with merge 6a83c01...

2016-10-19 13:26 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3669)

2016-10-19 14:32 UTC, Ms2ger commented
@bors-servo try

2016-10-19 14:32 UTC, bors-servo commented
:hourglass: Trying commit ac3dec9 with merge 1286a2b...

2016-10-19 14:51 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3671)

2016-10-20 06:14 UTC, Ms2ger commented
@bors-servo try

2016-10-20 06:14 UTC, bors-servo commented
:hourglass: Trying commit 53046d2 with merge 5d14791...

2016-10-20 06:48 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/322)

2016-10-20 08:49 UTC, Ms2ger commented
@bors-servo try

2016-10-20 08:49 UTC, bors-servo commented
:hourglass: Trying commit 23b2f6f with merge 0d98603...

2016-10-20 09:20 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/324)

2016-10-20 11:32 UTC, Ms2ger commented
r? @jdm

2016-10-20 13:34 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13854) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-21 07:36 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13848) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-22 13:06 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13891) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-31 17:12 UTC, jdm requested changes
Nice work; this was a straightforward series of commits to read through.

2016-10-31 17:12 UTC, jdm commented on components/net_traits/response.rs
> +    pub fn get_network_error(&self) -> Option<&NetworkError> {
Every caller clones the error, so I'm not sure it's worth returning a borrow.

2016-10-31 17:12 UTC, jdm commented on components/net/fetch/methods.rs
> +        // TODO: should block cookies?
I don't think this is a meaningful TODO given https://tools.ietf.org/html/rfc6265#section-7.

2016-10-31 17:12 UTC, jdm commented on components/script/script_thread.rs
> +            .. RequestInit::default()
Let's file a followup issue to support non-follow redirect modes for RequestInit.

2016-11-02 08:25 UTC, Ms2ger commented on components/net_traits/response.rs
> +    pub fn get_network_error(&self) -> Option<&NetworkError> {
I think it's better to at least make it possible for new callers to not have to clone, if they don't need to.

2016-11-02 08:26 UTC, Ms2ger commented
@bors-servo r=jdm

2016-11-02 08:26 UTC, bors-servo commented
:pushpin: Commit c7636a2 has been approved by `jdm`

<!-- @bors-servo r=jdm c7636a215ebb63bc87ee0176949291f96659598b -->

2016-11-02 08:26 UTC, bors-servo commented
:hourglass: Testing commit c7636a2 with merge ba2fb4e...

2016-11-02 09:28 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3825), [arm64](http://build.servo.org/builders/arm64/builds/3835), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3913), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/553), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/555), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3903), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3895), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/584), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/591), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1817)

2016-11-02 09:28 UTC, merged