Migrated -Z trace-layout to serde_json
servo/servo pull request #13740
Opened 2016-10-13 06:53 UTC by shinglyu

Migrated the trace-layout code from old `rustc-serialize` to `serde_json`. This will help us iterate faster on the layout viewer (#13432), #13436, #12675 and fix #12936.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12936 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's a relatively low risk debug tool

2016-10-13 06:54 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/logical_geometry.rs

2016-10-13 06:54 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style and layout code, but no tests are modified. Please consider adding a test!

2016-10-14 10:55 UTC, nox commented on components/layout/Cargo.toml
> +serde_json = "0.8"
serde_derive should come before serde_json.

2016-10-15 22:14 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13756) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-20 02:37 UTC, shinglyu commented
Just rebased to the latest master, @nox r?

2016-10-27 02:51 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13870) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-28 02:50 UTC, shinglyu commented
@nox @asajeffrey r?

2016-10-28 03:38 UTC, jdm requested changes

2016-10-28 03:38 UTC, jdm commented on components/layout/flow_list.rs
> +                    _ => { Value::Null }     // TODO: Support captions
We should probably use explicit variants here, to avoid incorrect defaults.

2016-10-28 03:38 UTC, jdm commented on components/layout/fragment.rs
> +        let mut state = try!(serializer.serialize_struct("fragment", 3)); //change the length!
I'm not sure what these comments mean.

2016-10-28 03:38 UTC, jdm commented on components/layout/lib.rs
> +#![feature(proc_macro)]
Move these in alphabetical order.

2016-10-28 03:38 UTC, jdm commented on components/layout/table_rowgroup.rs
> +    fn serialize<S: Serializer>(&self, serializer: &mut S) -> Result<(), S::Error>{
nit: space before {

2016-10-28 03:38 UTC, jdm commented on components/layout/block.rs
> +    fn serialize<S: Serializer>(&self, serializer: &mut S) -> Result<(), S::Error>{
nit: space before {

2016-10-28 15:20 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13960) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-31 14:32 UTC, jdm requested changes

2016-10-31 14:32 UTC, jdm commented on components/layout/lib.rs
> +#![feature(rustc_attrs)]
What's this feature for?

2016-10-31 14:32 UTC, jdm commented on components/layout/table_row.rs
> +    fn serialize<S: Serializer>(&self, serializer: &mut S) -> Result<(), S::Error>{
nit: space before { (there are a bunch of other instances in this PR; search for `>{`)

2016-11-01 06:20 UTC, shinglyu commented on components/layout/lib.rs
> +#![feature(rustc_attrs)]
These are some features required by `serde_json`, but looks like they are no longer needed in `rustc-1.14.0`, I'll try removing them and see if it works.

2016-11-01 06:20 UTC, shinglyu commented on components/layout/lib.rs
> +#![feature(rustc_attrs)]
ref: https://github.com/serde-rs/serde/issues/567

2016-11-01 06:35 UTC, shinglyu commented on components/layout/lib.rs
> +#![feature(rustc_attrs)]
Oh we don't need that anymore, I can compile with `rustc-1.14.0` with them removed.

2016-11-01 12:52 UTC, jdm commented
This is good to merge after a rebase.

2016-11-02 02:04 UTC, shinglyu commented
@bors-servo try - r=jdm

2016-11-02 02:04 UTC, bors-servo commented
:pushpin: Commit fe9e126 has been approved by `jdm`

<!-- @bors-servo r=jdm fe9e126db4f0154c583142bb75d1d5a5c9be7ead -->

2016-11-02 02:04 UTC, bors-servo commented
:hourglass: Testing commit fe9e126 with merge 4bf89b3...

2016-11-02 02:21 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3911)

2016-11-02 03:05 UTC, jdm commented
Uh oh, `./mach build-geckolib` doesn't like unstable features like custom derive.

2016-11-02 07:05 UTC, shinglyu commented
I'll try to disable the serialization in stylo because stylo doesn't need that for now.

2016-11-02 08:16 UTC, shinglyu commented
I moved the derives in the style crate into `#[cfg_attr(feature = "servo", derive(Serialize))]`. r? @jdm

2016-11-02 12:31 UTC, jdm commented
@bors-servo: r+

2016-11-02 12:31 UTC, bors-servo commented
:pushpin: Commit d1619a6 has been approved by `jdm`

<!-- @bors-servo r=jdm d1619a65139313b125bd6802d96e8d809d7ebd0e -->

2016-11-02 13:21 UTC, bors-servo commented
:hourglass: Testing commit d1619a6 with merge f78dea2...

2016-11-02 13:58 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3918)

2016-11-02 14:15 UTC, shinglyu commented
Oh I shouldn't check in the Cargo.lock file?

bors-servo <notifications@github.com> 於 2016年11月2日 週三 21:58 寫道：

> 💔 Test failed - linux-dev
> <http://build.servo.org/builders/linux-dev/builds/3918>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/servo/servo/pull/13740#issuecomment-257871877>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ADGbJ7MmIl_h0Gb9abvL4Une7Cn7KeXPks5q6JcggaJpZM4KVi47>
> .
>

2016-11-02 14:24 UTC, jdm commented
No, it means that you need to run `./mach cargo-update -p style` to make sure that ports/cef/Cargo.lock is updated.

2016-11-03 02:32 UTC, shinglyu commented
Just ran the `update-cargo` command, sorry for wasting everyone's time :'(

2016-11-03 02:33 UTC, shinglyu commented
@bors-servo retry

2016-11-03 02:33 UTC, shinglyu commented
@bors-servo: retry

2016-11-03 03:06 UTC, jdm commented
@bors-servo: r+

2016-11-03 03:06 UTC, bors-servo commented
:pushpin: Commit e585d33 has been approved by `jdm`

<!-- @bors-servo r=jdm e585d33c473d91fd52a82b785f0ff029a4502715 -->

2016-11-03 04:03 UTC, bors-servo commented
:lock: Merge conflict

2016-11-03 04:05 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14028) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-04 09:23 UTC, shinglyu commented
Rebased again, hopefully it will pass this time.

2016-11-04 12:05 UTC, jdm commented
@bors-servo: r+

2016-11-04 12:05 UTC, bors-servo commented
:pushpin: Commit 10754ed has been approved by `jdm`

<!-- @bors-servo r=jdm 10754ed8bde9a9ad4298443f2cfe2ae4d3e8df51 -->

2016-11-04 14:26 UTC, bors-servo commented
:hourglass: Testing commit 10754ed with merge 5c26f25...

2016-11-04 15:08 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/649)

2016-11-04 15:08 UTC, highfive commented
▶ TIMEOUT [expected CRASH] /_mozilla/mozilla/sigsegv.html
      │ 
      │ VMware, Inc.
      │ Gallium 0.4 on softpipe
      └ 3.3 (Core Profile) Mesa 12.0.1

2016-11-04 15:21 UTC, jdm commented
@bors-servo: retry
* #14067

2016-11-04 16:36 UTC, bors-servo commented
:hourglass: Testing commit 10754ed with merge ea70993...

2016-11-04 17:41 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/653)

2016-11-04 17:41 UTC, highfive commented
▶ TIMEOUT [expected CRASH] /_mozilla/mozilla/sigsegv.html
      │ 
      │ VMware, Inc.
      │ Gallium 0.4 on softpipe
      └ 3.3 (Core Profile) Mesa 12.0.1

2016-11-04 18:31 UTC, jdm commented
@bors-servo: retry
* #14067

2016-11-04 19:21 UTC, bors-servo commented
:hourglass: Testing commit 10754ed with merge a93e81c...

2016-11-04 20:01 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/622)

2016-11-04 20:18 UTC, jdm commented
@bors-servo: retry
* #13776

2016-11-04 20:54 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/3885), [arm64](http://build.servo.org/builders/arm64/builds/3895), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3979), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/619), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3967), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3962), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/648), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1889) are reusable. Rebuilding only [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/622), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/657)...

2016-11-04 21:53 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/660)

2016-11-04 21:53 UTC, highfive commented
▶ TIMEOUT [expected CRASH] /_mozilla/mozilla/sigsegv.html
      │ 
      │ VMware, Inc.
      │ Gallium 0.4 on softpipe
      └ 3.3 (Core Profile) Mesa 12.0.1

2016-11-04 23:04 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14053) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-07 07:55 UTC, shinglyu commented
@bors-servo: retry, r=jdm

2016-11-07 07:55 UTC, bors-servo commented
:pushpin: Commit 8bea421 has been approved by `jdm`

<!-- @bors-servo r=jdm 8bea421329f584f8394bd9ffe874249d293b8249 -->

2016-11-07 08:15 UTC, bors-servo commented
:hourglass: Testing commit 8bea421 with merge 1c26f44...

2016-11-07 09:07 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3936), [arm64](http://build.servo.org/builders/arm64/builds/3942), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4034), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/676), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/676), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4019), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4015), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/699), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/711), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1945)

2016-11-07 09:07 UTC, merged