Implement EventSource constructor, parse metadata in EventSource response
servo/servo pull request #13774
Opened 2016-10-14 19:20 UTC by KiChjang

It still doesn't parse the event stream correctly, but it does announce and fail the connection correctly. Re-establishing the connection is not supported yet.

Partial #8925.

2016-10-14 19:20 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmllinkelement.rs, components/script/dom/bindings/trace.rs, components/script/fetch.rs, components/script/dom/globalscope.rs, components/script/dom/xmlhttprequest.rs, components/script/network_listener.rs, components/script/dom/workerglobalscope.rs, components/script/task_source/networking.rs, components/script/dom/websocket.rs, components/script/dom/htmlscriptelement.rs, components/script/dom/htmlmediaelement.rs, components/script/dom/htmlimageelement.rs, components/script/dom/webidls/EventSource.webidl, components/script/dom/eventsource.rs, components/script/dom/window.rs, components/script/script_thread.rs
 * @kichjang: components/script/dom/htmllinkelement.rs, components/script/dom/bindings/trace.rs, components/script/fetch.rs, components/script/dom/globalscope.rs, components/script/dom/xmlhttprequest.rs, components/script/network_listener.rs, components/script/dom/workerglobalscope.rs, components/script/task_source/networking.rs, components/script/dom/websocket.rs, components/script/dom/htmlscriptelement.rs, components/script/dom/htmlmediaelement.rs, components/script/dom/htmlimageelement.rs, components/script/dom/webidls/EventSource.webidl, components/script/dom/eventsource.rs, components/script/dom/window.rs, components/script/script_thread.rs, components/net_traits/request.rs, components/net_traits/request.rs

2016-10-14 19:20 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-10-14 19:21 UTC, KiChjang commented
@bors-servo try

2016-10-14 19:21 UTC, bors-servo commented
:hourglass: Trying commit 650383d with merge b3f92ec...

2016-10-14 20:09 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/251)

2016-10-14 20:16 UTC, KiChjang commented
I believe there's still too many timeouts in EventSource and it's not worthwhile to enable it just yet.

2016-10-17 12:40 UTC, SimonSapin commented
r? @frewsxcv

2016-10-17 12:58 UTC, frewsxcv commented
```
./components/script/task_source/networking.rs:19: tab on line
```

2016-10-17 13:00 UTC, frewsxcv commented on components/script/dom/eventsource.rs
> +enum ReadyState {
Can you add a comment here?

```
https://html.spec.whatwg.org/multipage/#dom-eventsource-readystate
```

2016-10-17 13:14 UTC, frewsxcv commented
I can look through this, though I don't have much time over the next few days to do an in-depth review of this. Might be better to find someone else for the r+.

Is it true that there are not test expectation differences or have they not been updated?

2016-10-17 17:51 UTC, KiChjang commented
@frewsxcv They haven't been updated yet, since I'm not entirely sure that it's worth enabling the tests again due to the amount of expected timeouts in the tests.

2016-10-17 20:11 UTC, frewsxcv commented
Considering websockets will be partially supported after this PR, would it make sense to enable them?

2016-10-18 04:54 UTC, jdm commented
How are websockets related to EventSource? We already support websockets in Servo.

2016-10-18 13:02 UTC, frewsxcv commented
Blah, my bad, I was thinking "SSE" but said "websockets".

2016-10-27 09:14 UTC, KiChjang commented
@bors-servo try

2016-10-27 09:15 UTC, bors-servo commented
:hourglass: Trying commit 555d576 with merge c6338be...

2016-10-27 09:31 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/456)

2016-10-27 09:51 UTC, KiChjang commented
With the latest commit, testing locally yields 11 expected failures, 11 unexpected timeouts, and 43 passes. Ideally, there should be no timeouts, but maybe this amount of timeouts is acceptable?

2016-10-27 10:46 UTC, KiChjang commented
r? @jdm

2016-10-28 08:16 UTC, KiChjang commented
@bors-servo try

2016-10-28 08:17 UTC, bors-servo commented
:hourglass: Trying commit f2cf410 with merge 2a0fdba...

2016-10-28 08:51 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/471)

2016-10-28 10:09 UTC, KiChjang commented
With the latest commit, we have 11 expected failures, 10 timeouts and 47 unexpected passes. Progress!

2016-10-29 00:44 UTC, KiChjang commented
@bors-servo retry

2016-10-29 00:45 UTC, KiChjang commented
@bors-servo try

2016-10-29 00:45 UTC, bors-servo commented
:hourglass: Trying commit 3ed564c with merge a6766c8...

2016-10-29 00:45 UTC, bors-servo commented
:hourglass: Trying commit 3ed564c with merge 85a9227...

2016-10-29 01:27 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/538)

2016-10-29 02:58 UTC, KiChjang commented
```
Ran 3221 tests finished in 848.0 seconds.
  • 3173 ran as expected. 465 tests skipped.
  • 10 tests timed out unexpectedly
  • 48 tests had unexpected subtest results
```
<details>
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-close.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: close()

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-constructor-url-bogus.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: constructor (invalid URL)

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-eventtarget.worker:
  └ PASS [expected FAIL] dedicated worker - EventSource: addEventListener()

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-onmesage.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: onmessage

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-onopen.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: onopen (announcing the connection)

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-prototype.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: prototype et al

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-url.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: url

  ▶ Unexpected subtest result in /eventsource/event-data.html:
  └ PASS [expected FAIL] EventSource: lines and data parsing

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-document-domain.htm:
  └ PASS [expected FAIL] EventSource: document.domain

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, object

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, 1

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, null

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, undefined

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-url-bogus.htm:
  └ PASS [expected FAIL] EventSource: constructor (invalid URL)

  ▶ Unexpected subtest result in /eventsource/eventsource-eventtarget.htm:
  └ PASS [expected FAIL] EventSource: addEventListener()

  ▶ Unexpected subtest result in /eventsource/eventsource-onmessage.htm:
  └ PASS [expected FAIL] EventSource: onmessage

  ▶ Unexpected subtest result in /eventsource/eventsource-onopen.htm:
  └ PASS [expected FAIL] EventSource: onopen (announcing the connection)

  ▶ Unexpected subtest result in /eventsource/eventsource-prototype.htm:
  └ PASS [expected FAIL] EventSource: prototype et al

  ▶ Unexpected subtest result in /eventsource/eventsource-url.htm:
  └ PASS [expected FAIL] EventSource: url

  ▶ Unexpected subtest result in /eventsource/format-bom-2.htm:
  └ PASS [expected FAIL] EventSource: Double BOM

  ▶ Unexpected subtest result in /eventsource/format-comments.htm:
  └ PASS [expected FAIL] EventSource: comment fest

  ▶ Unexpected subtest result in /eventsource/format-field-data.htm:
  └ PASS [expected FAIL] EventSource: data field parsing

  ▶ Unexpected subtest result in /eventsource/format-field-event-empty.htm:
  └ PASS [expected FAIL] EventSource: empty "event" field

  ▶ Unexpected subtest result in /eventsource/format-field-event.htm:
  └ PASS [expected FAIL] EventSource: custom event name

  ▶ Unexpected subtest result in /eventsource/eventsource-close.htm:
  └ PASS [expected FAIL] EventSource: close()

  ▶ Unexpected subtest result in /eventsource/eventsource-close.htm:
  │ TIMEOUT [expected FAIL] EventSource: close(), test events
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/format-field-parsing.htm:
  └ PASS [expected FAIL] EventSource: field parsing

  ▶ TIMEOUT [expected OK] /eventsource/eventsource-cross-origin.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ Unexpected subtest result in /eventsource/eventsource-cross-origin.htm:
  │ TIMEOUT [expected FAIL] EventSource: cross-origin basic use
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/eventsource-cross-origin.htm:
  │ TIMEOUT [expected FAIL] EventSource: cross-origin redirect use
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/eventsource-cross-origin.htm:
  │ TIMEOUT [expected FAIL] EventSource: cross-origin redirect use recon
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/eventsource-cross-origin.htm:
  │ TIMEOUT [expected FAIL] EventSource: cross-origin allow-origin: http://example.org should fail
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/eventsource-cross-origin.htm:
  │ TIMEOUT [expected FAIL] EventSource: cross-origin allow-origin:'' should fail
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/format-field-retry-empty.htm:
  └ PASS [expected FAIL] EventSource: empty retry field

  ▶ TIMEOUT [expected OK] /eventsource/eventsource-reconnect.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ Unexpected subtest result in /eventsource/eventsource-reconnect.htm:
  │ TIMEOUT [expected FAIL] EventSource: reconnection 200
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/eventsource-reconnect.htm:
  │ TIMEOUT [expected FAIL] EventSource: reconnection, test reconnection events
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/format-field-unknown.htm:
  └ PASS [expected FAIL] EventSource: unknown fields and parsing fun

  ▶ Unexpected subtest result in /eventsource/format-leading-space.htm:
  └ PASS [expected FAIL] EventSource: leading space

  ▶ TIMEOUT [expected OK] /eventsource/format-data-before-final-empty-line.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ Unexpected subtest result in /eventsource/format-data-before-final-empty-line.htm:
  │ TIMEOUT [expected FAIL] EventSource: a data before final empty line
  └   → Test timed out

  ▶ Unexpected subtest result in /eventsource/format-mime-bogus.htm:
  └ PASS [expected FAIL] EventSource: bogus MIME type

  ▶ Unexpected subtest result in /eventsource/format-mime-trailing-semicolon.htm:
  └ PASS [expected FAIL] EventSource: MIME type with trailing ;

  ▶ Unexpected subtest result in /eventsource/format-mime-valid-bogus.htm:
  └ PASS [expected FAIL] EventSource: incorrect valid MIME type

  ▶ Unexpected subtest result in /eventsource/format-newlines.htm:
  └ PASS [expected FAIL] EventSource: newline fest

  ▶ Unexpected subtest result in /eventsource/format-null-character.html:
  └ PASS [expected FAIL] EventSource: null character in response

  ▶ Unexpected subtest result in /eventsource/format-utf-8.htm:
  └ PASS [expected FAIL] EventSource: always UTF-8

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface object length

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface object name

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: existence and properties of interface prototype object's "constructor" property

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: attribute url

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: attribute withCredentials

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant CONNECTING on interface object

  ▶ Unexpected subtest result in /e [...]

2016-10-29 17:40 UTC, KiChjang commented
@bors-servo try

2016-10-29 17:40 UTC, bors-servo commented
:hourglass: Trying commit d52474b with merge 6ddf7dd...

2016-10-29 18:11 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/502)

2016-10-29 19:45 UTC, KiChjang commented
```
Ran 7564 tests finished in 913.0 seconds.
  • 7514 ran as expected. 1764 tests skipped.
  • 4 tests timed out unexpectedly
  • 50 tests had unexpected subtest results
```
<details>
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-constructor-non-same-origin.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: constructor (act as if there is a network error) (about:blank)

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-close.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: close()

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-constructor-url-bogus.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: constructor (invalid URL)

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-eventtarget.worker:
  └ PASS [expected FAIL] dedicated worker - EventSource: addEventListener()

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-onopen.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: onopen (announcing the connection)

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-prototype.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: prototype et al

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-onmesage.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: onmessage

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-url.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: url

  ▶ Unexpected subtest result in /eventsource/event-data.html:
  └ PASS [expected FAIL] EventSource: lines and data parsing

  ▶ Unexpected subtest result in /eventsource/eventsource-close.htm:
  └ PASS [expected FAIL] EventSource: close()

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-document-domain.htm:
  └ PASS [expected FAIL] EventSource: document.domain

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-url-bogus.htm:
  └ PASS [expected FAIL] EventSource: constructor (invalid URL)

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, object

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, 1

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, null

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, undefined

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-non-same-origin.htm:
  └ PASS [expected FAIL] EventSource: constructor (act as if there is a network error) (about:blank)

  ▶ Unexpected subtest result in /eventsource/eventsource-onmessage.htm:
  └ PASS [expected FAIL] EventSource: onmessage

  ▶ Unexpected subtest result in /eventsource/eventsource-prototype.htm:
  └ PASS [expected FAIL] EventSource: prototype et al

  ▶ Unexpected subtest result in /eventsource/eventsource-eventtarget.htm:
  └ PASS [expected FAIL] EventSource: addEventListener()

  ▶ Unexpected subtest result in /eventsource/eventsource-onopen.htm:
  └ PASS [expected FAIL] EventSource: onopen (announcing the connection)

  ▶ Unexpected subtest result in /eventsource/eventsource-url.htm:
  └ PASS [expected FAIL] EventSource: url

  ▶ Unexpected subtest result in /eventsource/format-bom-2.htm:
  └ PASS [expected FAIL] EventSource: Double BOM

  ▶ Unexpected subtest result in /eventsource/format-field-data.htm:
  └ PASS [expected FAIL] EventSource: data field parsing

  ▶ Unexpected subtest result in /eventsource/format-comments.htm:
  └ PASS [expected FAIL] EventSource: comment fest

  ▶ Unexpected subtest result in /eventsource/format-field-event-empty.htm:
  └ PASS [expected FAIL] EventSource: empty "event" field

  ▶ Unexpected subtest result in /eventsource/format-field-event.htm:
  └ PASS [expected FAIL] EventSource: custom event name

  ▶ Unexpected subtest result in /eventsource/format-field-retry-empty.htm:
  └ PASS [expected FAIL] EventSource: empty retry field

  ▶ Unexpected subtest result in /eventsource/format-field-id.htm:
  └ PASS [expected FAIL] EventSource: Last-Event-ID

  ▶ Unexpected subtest result in /eventsource/format-field-parsing.htm:
  └ PASS [expected FAIL] EventSource: field parsing

  ▶ Unexpected subtest result in /eventsource/format-field-unknown.htm:
  └ PASS [expected FAIL] EventSource: unknown fields and parsing fun

  ▶ Unexpected subtest result in /eventsource/format-leading-space.htm:
  └ PASS [expected FAIL] EventSource: leading space

  ▶ Unexpected subtest result in /eventsource/format-field-id-2.htm:
  └ PASS [expected FAIL] EventSource: Last-Event-ID (2)

  ▶ Unexpected subtest result in /eventsource/format-mime-bogus.htm:
  └ PASS [expected FAIL] EventSource: bogus MIME type

  ▶ Unexpected subtest result in /eventsource/format-mime-valid-bogus.htm:
  └ PASS [expected FAIL] EventSource: incorrect valid MIME type

  ▶ Unexpected subtest result in /eventsource/format-mime-trailing-semicolon.htm:
  └ PASS [expected FAIL] EventSource: MIME type with trailing ;

  ▶ Unexpected subtest result in /eventsource/format-newlines.htm:
  └ PASS [expected FAIL] EventSource: newline fest

  ▶ Unexpected subtest result in /eventsource/format-utf-8.htm:
  └ PASS [expected FAIL] EventSource: always UTF-8

  ▶ Unexpected subtest result in /eventsource/request-accept.htm:
  └ PASS [expected FAIL] EventSource: Accept header

  ▶ Unexpected subtest result in /eventsource/format-null-character.html:
  └ PASS [expected FAIL] EventSource: null character in response

  ▶ Unexpected subtest result in /eventsource/request-redirect.htm:
  └ PASS [expected FAIL] EventSource: redirect (301)

  ▶ Unexpected subtest result in /eventsource/request-redirect.htm:
  └ PASS [expected FAIL] EventSource: redirect (302)

  ▶ Unexpected subtest result in /eventsource/request-redirect.htm:
  └ PASS [expected FAIL] EventSource: redirect (303)

  ▶ Unexpected subtest result in /eventsource/request-redirect.htm:
  └ PASS [expected FAIL] EventSource: redirect (307)

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface object length

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface object name

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: existence and properties of interface prototype object's "constructor" property

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: attribute url

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: attribute withCredentials

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant CONNECTING on interface object

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant CONNECTING on interface prototype object

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant OPEN on interface object

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant OPEN on interface prototype object

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant CLOSED on interface object

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant CLOSED on interface prototype object

  ▶ Unexpected  [...]

2016-11-01 19:17 UTC, jdm requested changes
Nice work! This all came out pretty readable, in my opinion. We'll need the test result changes added, too.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +        if self.gen_id != self.event_source.root().generation_id.get() {
Same as previous.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/event.rs
> +    pub fn set_type(&self, type_: Atom) {
This isn't used.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +        thread::sleep(Duration::from_millis(event_source.reconnection_time.get()));
Use the timer support in script/timer.rs instead, like the built-in XHR timer.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +        if !self.unparsed_bytes.is_empty() {
```rust
if self.unparsed_bytes.is_empty() {
    return;
}
```

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +            let stream = String::from_utf8(bytes).unwrap();
Unwrapping here looks dangerous.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +        let event = MessageEvent::new(&*global, self.type_.clone(), false, false, data.handle(),
This is supposed to be created before this runnable is queued.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +        event.upcast::<Event>().fire(&event_source.upcast());
We missed the readyState check.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +        if event_source.ready_state.get() != ReadyState::Closed {
This is supposed to happen inside of the queued runnable instead.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +        // Step 7
Might as well have this in the correct order.

2016-11-01 19:17 UTC, jdm commented on components/script/dom/eventsource.rs
> +        spawn_named("Reestablish EventSource Connection Thread".to_owned(), move || {
I still think a timer would be more appropriate here.

2016-11-01 19:40 UTC, KiChjang commented on components/script/dom/eventsource.rs
> +        let event = MessageEvent::new(&*global, self.type_.clone(), false, false, data.handle(),
So the problem of creating this before the runnable is queued is that `MessageEvent` is not `Send`, perhaps I should wrap it inside a `Trusted` or an `Arc`?

2016-11-01 20:23 UTC, jdm commented on components/script/dom/eventsource.rs
> +        let event = MessageEvent::new(&*global, self.type_.clone(), false, false, data.handle(),
`Trusted<MessageEvent>`, yes.

2016-11-02 09:29 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13742) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-05 22:45 UTC, KiChjang commented
Rebased, but still need to work on the timeout callback code.

@jdm Do you mean that we should remove the new thread code altogether and just use the timer code?

2016-11-06 03:11 UTC, jdm commented
Yes, the thread should be unnecessary with a proper timer.

2016-11-06 04:37 UTC, KiChjang commented
@bors-servo try

2016-11-06 04:37 UTC, bors-servo commented
:hourglass: Trying commit 5ac45c5 with merge a5cab52...

2016-11-06 04:59 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/4011)

2016-11-06 05:20 UTC, KiChjang commented
```
Ran 3255 tests finished in 855.0 seconds.
  • 3207 ran as expected. 498 tests skipped.
  • 3 tests timed out unexpectedly
  • 48 tests had unexpected subtest results
```
<details>
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /XMLHttpRequest/responsexml-document-properties.htm:
  │ FAIL [expected PASS] lastModified set to time of response if no HTTP header provided
  │   → assert_less_than_equal: expected a number less than or equal to 1478409219 but got 1478412819
  │ 
  │ @http://web-platform.test:8000/XMLHttpRequest/responsexml-document-properties.htm:39:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  └ @http://web-platform.test:8000/XMLHttpRequest/responsexml-document-properties.htm:35:7

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-close.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: close()

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-constructor-non-same-origin.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: constructor (act as if there is a network error) (about:blank)

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-constructor-url-bogus.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: constructor (invalid URL)

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-eventtarget.worker:
  └ PASS [expected FAIL] dedicated worker - EventSource: addEventListener()

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-onmesage.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: onmessage

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-onopen.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: onopen (announcing the connection)

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-prototype.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: prototype et al

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-url.htm:
  └ PASS [expected FAIL] dedicated worker - EventSource: url

  ▶ Unexpected subtest result in /eventsource/event-data.html:
  └ PASS [expected FAIL] EventSource: lines and data parsing

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-document-domain.htm:
  └ PASS [expected FAIL] EventSource: document.domain

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-non-same-origin.htm:
  └ PASS [expected FAIL] EventSource: constructor (act as if there is a network error) (about:blank)

  ▶ Unexpected subtest result in /eventsource/eventsource-close.htm:
  └ PASS [expected FAIL] EventSource: close()

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, object

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, 1

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, null

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-stringify.htm:
  └ PASS [expected FAIL] EventSource: stringify argument, undefined

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-url-bogus.htm:
  └ PASS [expected FAIL] EventSource: constructor (invalid URL)

  ▶ Unexpected subtest result in /eventsource/eventsource-eventtarget.htm:
  └ PASS [expected FAIL] EventSource: addEventListener()

  ▶ Unexpected subtest result in /eventsource/eventsource-onmessage.htm:
  └ PASS [expected FAIL] EventSource: onmessage

  ▶ Unexpected subtest result in /eventsource/eventsource-onopen.htm:
  └ PASS [expected FAIL] EventSource: onopen (announcing the connection)

  ▶ Unexpected subtest result in /eventsource/eventsource-prototype.htm:
  └ PASS [expected FAIL] EventSource: prototype et al

  ▶ Unexpected subtest result in /eventsource/eventsource-reconnect.htm:
  └ PASS [expected FAIL] EventSource: reconnection 200

  ▶ Unexpected subtest result in /eventsource/eventsource-reconnect.htm:
  └ PASS [expected FAIL] EventSource: reconnection, test reconnection events

  ▶ Unexpected subtest result in /eventsource/format-bom-2.htm:
  └ PASS [expected FAIL] EventSource: Double BOM

  ▶ Unexpected subtest result in /eventsource/eventsource-url.htm:
  └ PASS [expected FAIL] EventSource: url

  ▶ Unexpected subtest result in /eventsource/format-comments.htm:
  └ PASS [expected FAIL] EventSource: comment fest

  ▶ Unexpected subtest result in /eventsource/format-field-data.htm:
  └ PASS [expected FAIL] EventSource: data field parsing

  ▶ Unexpected subtest result in /eventsource/format-field-event.htm:
  └ PASS [expected FAIL] EventSource: custom event name

  ▶ Unexpected subtest result in /eventsource/format-field-event-empty.htm:
  └ PASS [expected FAIL] EventSource: empty "event" field

  ▶ Unexpected subtest result in /eventsource/format-field-parsing.htm:
  └ PASS [expected FAIL] EventSource: field parsing

  ▶ Unexpected subtest result in /eventsource/format-field-retry-empty.htm:
  └ PASS [expected FAIL] EventSource: empty retry field

  ▶ Unexpected subtest result in /eventsource/format-field-id.htm:
  └ PASS [expected FAIL] EventSource: Last-Event-ID

  ▶ Unexpected subtest result in /eventsource/format-field-id-2.htm:
  └ PASS [expected FAIL] EventSource: Last-Event-ID (2)

  ▶ Unexpected subtest result in /eventsource/format-field-unknown.htm:
  └ PASS [expected FAIL] EventSource: unknown fields and parsing fun

  ▶ Unexpected subtest result in /eventsource/format-leading-space.htm:
  └ PASS [expected FAIL] EventSource: leading space

  ▶ Unexpected subtest result in /eventsource/format-mime-bogus.htm:
  └ PASS [expected FAIL] EventSource: bogus MIME type

  ▶ Unexpected subtest result in /eventsource/format-mime-trailing-semicolon.htm:
  └ PASS [expected FAIL] EventSource: MIME type with trailing ;

  ▶ Unexpected subtest result in /eventsource/format-mime-valid-bogus.htm:
  └ PASS [expected FAIL] EventSource: incorrect valid MIME type

  ▶ Unexpected subtest result in /eventsource/format-newlines.htm:
  └ PASS [expected FAIL] EventSource: newline fest

  ▶ Unexpected subtest result in /eventsource/format-null-character.html:
  └ PASS [expected FAIL] EventSource: null character in response

  ▶ Unexpected subtest result in /eventsource/format-utf-8.htm:
  └ PASS [expected FAIL] EventSource: always UTF-8

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface object length

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface object name

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: existence and properties of interface prototype object's "constructor" property

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: attribute url

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: attribute withCredentials

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant CONNECTING on interface object

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant CONNECTING on interface prototype object

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant OPEN on interface object

  ▶ Unexpected subtest result in /eventsource/interfaces.html:
  └ PASS [expected FAIL] EventSource interface: constant OPEN on interface prototype object

  ▶ Unexpected subtest resu [...]

2016-11-06 06:42 UTC, KiChjang commented
Also, I plan to rewrite the timer callbacks in a later PR to become a full-fledged trait accepting an associated type item.

2016-11-06 18:59 UTC, KiChjang commented
@bors-servo try

2016-11-06 18:59 UTC, bors-servo commented
:hourglass: Trying commit 83d1f3c with merge de50cd5...

2016-11-06 19:04 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/664)

2016-11-06 19:05 UTC, KiChjang commented
@bors-servo retry
* ICE?!?!

2016-11-06 19:05 UTC, bors-servo commented
:hourglass: Trying commit 83d1f3c with merge 2e37e64...

2016-11-06 19:42 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/667)

2016-11-06 20:36 UTC, KiChjang commented
@bors-servo try

2016-11-06 20:36 UTC, bors-servo commented
:hourglass: Trying commit 62532cb with merge 6a0a308...

2016-11-06 21:28 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/669)

2016-11-08 04:42 UTC, KiChjang commented
@jdm I believe this is ready to be re-reviewed.

2016-11-09 22:26 UTC, jdm requested changes

2016-11-09 22:26 UTC, jdm commented on components/script/dom/eventsource.rs
> +        let _ = self.done_receiver.recv();
If this timer ends up being invoked before the done_sender message is sent, we will deadlock.

2016-11-09 22:27 UTC, jdm commented
Not sure why github thinks my last comment is outdated.

2016-11-09 22:28 UTC, KiChjang commented on components/script/dom/eventsource.rs
> +        let _ = self.done_receiver.recv();
Hmm... so perhaps the timer should be started in the ReestablishConnectionRunnable instead?

2016-11-09 23:24 UTC, KiChjang commented
Okay, so I put the timer code in ReestablishConnectionRunnable instead.

2016-11-10 01:10 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14083) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-10 21:45 UTC, KiChjang commented
Crap, something went wrong during rebase, will fix soon.

2016-11-10 22:56 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14156) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-12 14:08 UTC, jdm commented
@bors-servo: r+

2016-11-12 14:08 UTC, bors-servo commented
:pushpin: Commit a39d1fa has been approved by `jdm`

<!-- @bors-servo r=jdm a39d1fa7d1b6119f4d86c11cc42728ce22bf1060 -->

2016-11-12 14:08 UTC, bors-servo commented
:hourglass: Testing commit a39d1fa with merge 579ab2d...

2016-11-12 15:08 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4051), [arm64](http://build.servo.org/builders/arm64/builds/4058), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4152), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/797), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/794), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4135), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4132), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/819), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/830), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2067)

2016-11-12 15:08 UTC, merged