Implement `select` property on `<option>`.
servo/servo pull request #13783
Opened 2016-10-16 02:13 UTC by frewsxcv

2016-10-16 02:13 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmloptionelement.rs, components/script/dom/htmlselectelement.rs, components/script/dom/webidls/HTMLSelectElement.webidl
 * @kichjang: components/script/dom/htmloptionelement.rs, components/script/dom/htmlselectelement.rs, components/script/dom/webidls/HTMLSelectElement.webidl

2016-10-16 02:14 UTC, frewsxcv commented
@bors-servo try

2016-10-16 02:14 UTC, bors-servo commented
:hourglass: Trying commit 622265b with merge bcf116e...

2016-10-16 02:40 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/3628)

2016-10-16 02:42 UTC, frewsxcv commented
@bors-servo try

2016-10-16 02:42 UTC, bors-servo commented
:hourglass: Trying commit 857dcbe with merge 7e8a1fd...

2016-10-16 03:52 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3552), [arm64](http://build.servo.org/builders/arm64/builds/3563), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3629), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/260), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/261), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3630), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3608), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/310), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/312), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1519)

2016-10-16 10:54 UTC, nox requested changes
Some changes are required. We should also add a test to check that we correctly skip options that are not children of `select` or `optgroup`.

2016-10-16 10:54 UTC, nox commented on components/script/dom/htmlselectelement.rs
> +            .traverse_preorder()
This doesn't seem correct to me. What about this tree?

```html
<select>
  <div>
    <option value="I should be ignored" selected="selected">
  </div>
</select>
```

2016-10-16 10:54 UTC, nox commented on components/script/dom/htmlselectelement.rs
> +        while let Some(opt) = opt_iter.next() {
Why a `while` loop?

2016-10-16 10:54 UTC, nox commented on components/script/dom/htmlselectelement.rs
> +                               .traverse_preorder()
Same as above.

2016-10-16 10:54 UTC, nox commented on components/script/dom/htmlselectelement.rs
> +        for ref opt in opt_iter {
Why is the `ref` necessary here?

2016-10-16 12:48 UTC, frewsxcv commented on components/script/dom/htmlselectelement.rs
> +            .traverse_preorder()
Same algorithm is done elsewhere in the file and was going to take care of it with https://github.com/servo/servo/issues/13763

2016-10-16 12:49 UTC, frewsxcv commented on components/script/dom/htmlselectelement.rs
> +        while let Some(opt) = opt_iter.next() {
`opt_iter` gets moved when I tried a `for opt in opt_iter`

2016-10-16 12:52 UTC, frewsxcv commented on components/script/dom/htmlselectelement.rs
> +        for ref opt in opt_iter {
`ref` removed in the latest force push.

2016-10-16 15:20 UTC, frewsxcv commented on components/script/dom/htmlselectelement.rs
> +                               .traverse_preorder()
https://github.com/servo/servo/pull/13783#discussion_r83550821

2016-10-16 17:14 UTC, frewsxcv commented on components/script/dom/htmlselectelement.rs
> +        while let Some(opt) = opt_iter.next() {
Just kidding, forgot `Iterator::by_ref` exists.

2016-10-16 17:26 UTC, frewsxcv commented
@nox Comments have been addressed. Also did a rewriting of the `SetValue` flow.

2016-10-17 07:47 UTC, nox commented
@bors-servo r+

2016-10-17 07:47 UTC, bors-servo commented
:pushpin: Commit a3d4d33 has been approved by `nox`

<!-- @bors-servo r=nox a3d4d336b753ee66d574286e3595cafdfcfc8eb9 -->

2016-10-17 07:47 UTC, bors-servo commented
:hourglass: Testing commit a3d4d33 with merge a71b1e6...

2016-10-17 08:41 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3564), [arm64](http://build.servo.org/builders/arm64/builds/3575), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3641), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/273), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/274), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3642), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3620), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/322), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/324), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1531)

2016-10-17 08:41 UTC, merged