Implement CSS filter for Stylo
servo/servo pull request #13795
Opened 2016-10-17 04:07 UTC by shinglyu

This patch is part of https://bugzilla.mozilla.org/show_bug.cgi?id=1310117

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-10-17 04:07 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/gecko_bindings/bindings.rs, components/style/properties/gecko.mako.rs, components/style/properties/longhand/effects.mako.rs

2016-10-17 04:07 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify style code, but no tests are modified. Please consider adding a test!

2016-10-17 04:08 UTC, shinglyu commented
r? @Manishearth

2016-10-17 04:08 UTC, Manishearth commented
@bors-servo r+

2016-10-17 04:08 UTC, bors-servo commented
:pushpin: Commit cabc25b has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth cabc25bb050000a033e53475cb3efa2486e34e20 -->

2016-10-17 04:20 UTC, bors-servo commented
:hourglass: Testing commit cabc25b with merge e1f8b97...

2016-10-17 04:35 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3641)

2016-10-17 04:41 UTC, Manishearth commented
```
   Compiling env_logger v0.3.4
   Compiling app_units v0.3.0
   Compiling euclid v0.10.2
   Compiling selectors v0.13.1
   Compiling style_traits v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/components/style_traits)
   Compiling util v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/components/util)
error[E0425]: unresolved name `Gecko_ResetFilters`
    --> /Users/servo/buildbot/slave/mac-dev-unit/build/target/geckolib/debug/build/style-e4892124584d9ae5/out/gecko_properties.rs:4154:13
     |
4154 |             Gecko_ResetFilters(&mut self.gecko, v.filters.len());
     |             ^^^^^^^^^^^^^^^^^^
/Users/servo/buildbot/slave/mac-dev-unit/build/components/style/lib.rs:151:5: 151:64 note: in this expansion of include!

error[E0425]: unresolved name `Gecko_CopyFiltersFrom`
    --> /Users/servo/buildbot/slave/mac-dev-unit/build/target/geckolib/debug/build/style-e4892124584d9ae5/out/gecko_properties.rs:4196:13
     |
4196 |             Gecko_CopyFiltersFrom(&other.gecko, &mut self.gecko);
     |             ^^^^^^^^^^^^^^^^^^^^^
/Users/servo/buildbot/slave/mac-dev-unit/build/components/style/lib.rs:151:5: 151:64 note: in this expansion of include!

error[E0308]: mismatched types
    --> /Users/servo/buildbot/slave/mac-dev-unit/build/target/geckolib/debug/build/style-e4892124584d9ae5/out/gecko_properties.rs:4149:34
     |
4149 |             gecko_filter.mType = m_type;
     |                                  ^^^^^^ expected i32, found u32
/Users/servo/buildbot/slave/mac-dev-unit/build/components/style/lib.rs:151:5: 151:64 note: in this expansion of include!

error: aborting due to previous error

```

2016-10-17 11:28 UTC, emilio requested changes
Mostly format nits, looks good otherwise :)

2016-10-17 11:28 UTC, emilio commented on components/style/properties/gecko.mako.rs
> +                                      NS_STYLE_FILTER_BRIGHTNESS,
nit: Please use multiple `use` statements instead of this.

2016-10-17 11:28 UTC, emilio commented on components/style/properties/gecko.mako.rs
> +        assert!(v.filters.len() == self.gecko.mFilters.len());
nit: `debug_assert!`

2016-10-17 11:28 UTC, emilio commented on components/style/properties/gecko.mako.rs
> +                Blur(len) =>          fill_filter(NS_STYLE_FILTER_BLUR,
nit: Maybe align the fat arrow too?

2016-10-17 11:28 UTC, emilio commented on components/style/properties/gecko.mako.rs
> +
nit: Leave only one blank line here.

2016-10-17 11:30 UTC, emilio commented on components/style/gecko_bindings/bindings.rs
> +    pub fn Gecko_CopyFiltersFrom(aSrc: &nsStyleEffects, aDest: *mut nsStyleEffects);
hmm... This seems to be written manually, given bindgen doesn't generate references? I think you should actually regenerate the bindings, you can do that easily without regenating the structs running:

```
./regen.py --target bindings /path/to/objdir
```

2016-10-19 05:16 UTC, shinglyu commented on components/style/gecko_bindings/bindings.rs
> +    pub fn Gecko_CopyFiltersFrom(aSrc: &nsStyleEffects, aDest: *mut nsStyleEffects);
I ran the above command, but I got this:

```
./mach test-stylo                                                                                                                                                 101 ↵ ✹ ✭
   Compiling style v0.0.1 (file:///home/shinglyu/workspace/stylo/servo/components/style)
error: expected one of `!`, `(`, `+`, `::`, `;`, or `<`, found `mozilla`
    --> /home/shinglyu/workspace/stylo/servo/components/style/gecko_bindings/bindings.rs:1115:14
     |
1115 |     typename mozilla::Conditional<MapTypeToRootKind<T>::kind == JS::RootKind::Traceable, js::DispatchWrapper<T>, T>::Type;
     |              ^^^^^^^

error: aborting due to previous error

error: Could not compile `style`.

To learn more, run the command again with --verbose.
```

2016-10-19 05:17 UTC, shinglyu commented
I just pushed the nit fixes, but didn't push the new bindgen generated file, because I got the compile failures posted above.

2016-10-19 05:29 UTC, shinglyu commented on components/style/gecko_bindings/bindings.rs
> +    pub fn Gecko_CopyFiltersFrom(aSrc: &nsStyleEffects, aDest: *mut nsStyleEffects);
I'm pointing the `/path/to/objdir` to my `stylo-incubator` one, should I use the latest mozilla-central instead?

2016-10-19 06:31 UTC, Manishearth commented
Post regen:
<details>
```patch
diff --git a/components/style/gecko_bindings/bindings.rs b/components/style/gecko_bindings/bindings.rs
index 23dfd71..8416724 100644
--- a/components/style/gecko_bindings/bindings.rs
+++ b/components/style/gecko_bindings/bindings.rs
@@ -522,6 +522,13 @@ extern "C" {
      -> *mut StyleBasicShape;
 }
 extern "C" {
+    pub fn Gecko_ResetFilters(effects: *mut nsStyleEffects, new_len: usize);
+}
+extern "C" {
+    pub fn Gecko_CopyFiltersFrom(aSrc: *mut nsStyleEffects,
+                                 aDest: *mut nsStyleEffects);
+}
+extern "C" {
     pub fn Gecko_FillAllBackgroundLists(layers: *mut nsStyleImageLayers,
                                         max_len: u32);
 }
diff --git a/components/style/gecko_bindings/structs_debug.rs b/components/style/gecko_bindings/structs_debug.rs
index 0a3fad9..c5318ad 100644
--- a/components/style/gecko_bindings/structs_debug.rs
+++ b/components/style/gecko_bindings/structs_debug.rs
@@ -10930,7 +10930,7 @@ fn bindgen_test_layout_nsStyleSVG() {
 #[repr(C)]
 #[derive(Debug)]
 pub struct nsStyleFilter {
-    pub mType: i32,
+    pub mType: u32,
     pub mFilterParameter: nsStyleCoord,
     pub __bindgen_anon_1: nsStyleFilter__bindgen_ty_bindgen_id_217312,
 }
diff --git a/components/style/gecko_bindings/structs_release.rs b/components/style/gecko_bindings/structs_release.rs
index c13e876..8b8e12a 100644
--- a/components/style/gecko_bindings/structs_release.rs
+++ b/components/style/gecko_bindings/structs_release.rs
@@ -10874,7 +10874,7 @@ fn bindgen_test_layout_nsStyleSVG() {
 #[repr(C)]
 #[derive(Debug)]
 pub struct nsStyleFilter {
-    pub mType: i32,
+    pub mType: u32,
     pub mFilterParameter: nsStyleCoord,
     pub __bindgen_anon_1: nsStyleFilter__bindgen_ty_bindgen_id_211452,
 }
```
</details>

I'll try to apply this patch and see what happens

2016-10-19 06:35 UTC, Manishearth commented
@bors-servo r+

2016-10-19 06:35 UTC, bors-servo commented
:pushpin: Commit 0cdd96e has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth 0cdd96e0573994f8f81b1e2847223ad9aee4524a -->

2016-10-20 02:56 UTC, Manishearth commented
@bors-servo r+

shoot, forgot

2016-10-20 02:56 UTC, bors-servo commented
:pushpin: Commit ff7bb69 has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth ff7bb691d70ea94a9bb271a4ac11592d41dadbff -->

2016-10-20 02:56 UTC, bors-servo commented
:hourglass: Testing commit ff7bb69 with merge 6071252...

2016-10-20 03:56 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/320)

2016-10-20 03:58 UTC, Manishearth commented
```

---- gecko_bindings::structs::bindgen_test_layout_nsIDocument stdout ----
	thread 'gecko_bindings::structs::bindgen_test_layout_nsIDocument' panicked at 'assertion failed: `(left == right)` (left: `952`, right: `944`)', /home/servo/buildbot/slave/linux-rel-css/build/components/style/gecko_bindings/structs_release.rs:3165
stack backtrace:
   1:     0x7ff2ccd8ef39 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x7ff2ccd92eac - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x7ff2ccd92084 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x7ff2ccd927e8 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x7ff2ccd92642 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x7ff2ccd925b0 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x7ff2ccd4e797 - style::gecko_bindings::structs::bindgen_test_layout_nsIDocument::ha6b566dd1eada7ac
   8:     0x7ff2ccd5998b - _<F as alloc..boxed..FnBox<A>>::call_box::hd5b7ed3c754c2638
   9:     0x7ff2ccd52c4f - std::panicking::try::do_call::h63a911edf59441a1
  10:     0x7ff2ccd9a996 - __rust_maybe_catch_panic
  11:     0x7ff2ccd5934a - _<F as alloc..boxed..FnBox<A>>::call_box::h3db4d78fb37007ad
  12:     0x7ff2ccd90d92 - std::sys::thread::Thread::new::thread_start::h4c0ad33b336bc6ea
  13:     0x7ff2cc6fc183 - start_thread
  14:     0x7ff2cc21337c - clone
  15:                0x0 - <unknown>
```

2016-10-20 03:58 UTC, Manishearth commented
@heycam hmm, looks like something went wrong in the sync here?

2016-10-20 05:35 UTC, heycam commented
I just run `./mach test-stylo` on servo tip and didn't come up with any errors from the bindings.  Maybe just rebasing these changes on top of current tip will work?

2016-10-20 05:37 UTC, Manishearth commented
well, that's what homu does

2016-10-20 13:47 UTC, Manishearth commented
@bors-servo retry

2016-10-20 14:40 UTC, bors-servo commented
:hourglass: Testing commit ff7bb69 with merge ee713bc...

2016-10-20 16:29 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3623), [arm64](http://build.servo.org/builders/arm64/builds/3633), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3698), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/339), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/336), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3701), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3679), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/382), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/382), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1596)

2016-10-20 16:29 UTC, merged