Implement `selectedIndex` property on `<select>`.
servo/servo pull request #13818
Opened 2016-10-18 16:52 UTC by frewsxcv

2016-10-18 16:52 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmlselectelement.rs, components/script/dom/webidls/HTMLSelectElement.webidl
 * @kichjang: components/script/dom/htmlselectelement.rs, components/script/dom/webidls/HTMLSelectElement.webidl

2016-10-19 00:19 UTC, frewsxcv commented
@bors-servo try

2016-10-19 00:19 UTC, bors-servo commented
:hourglass: Trying commit fdc4963 with merge 46cdf3a...

2016-10-19 00:55 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/295)

2016-10-19 00:55 UTC, highfive commented
▶ TIMEOUT [expected FAIL] /css21_dev/html4/abspos-replaced-width-margin-000.htm
      │ 
      │ VMware, Inc.
      │ Gallium 0.4 on softpipe
      │ 3.3 (Core Profile) Mesa 12.0.1
      └ Shutting down the Constellation after generating an output file or exit flag specified

2016-10-19 00:56 UTC, frewsxcv commented
@bors-servo retry

2016-10-19 00:56 UTC, bors-servo commented
:hourglass: Trying commit fdc4963 with merge 52c4196...

2016-10-19 01:26 UTC, bors-servo commented
:hourglass: Trying commit fdc4963 with merge 3f0b99d...

2016-10-19 02:07 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/296)

2016-10-19 02:07 UTC, highfive commented
▶ FAIL [expected PASS] /_mozilla/css/incremental_trailing_whitespace_a.html
      └   → /_mozilla/css/incremental_trailing_whitespace_a.html da54041086f2975f8e3c776d2283ad6609e6862a
    /_mozilla/css/incremental_trailing_whitespace_ref.html f5d0147c8bddbdc772a7e5e86c7c9e433fcd486b
    Testing da54041086f2975f8e3c776d2283ad6609e6862a == f5d0147c8bddbdc772a7e5e86c7c9e433fcd486b

2016-10-19 14:06 UTC, frewsxcv commented
r? @KiChjang or @nox ?

2016-10-19 16:47 UTC, KiChjang requested changes
My general comment here is that both the getter and setter methods can use the `HTMLSelectElement#options` WebIDL method to get the "list of options" instead of manually iterating through the tree and performing lookups for HTMLOptionElements.

2016-10-19 17:15 UTC, frewsxcv commented
@KiChjang That would allocate a new collection, which we don't need to do. The "list of options" is a separate issue: https://github.com/servo/servo/issues/13763 which can just be represented as an `Iterator`

2016-10-19 19:10 UTC, KiChjang commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
This is quite surprising, isn't it supposed to be -1, since none of the child options have a `selected` attribute?

2016-10-19 19:10 UTC, KiChjang commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 1);
Same here, none of the child options have a `selected` attribute.

2016-10-19 19:17 UTC, frewsxcv commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
https://html.spec.whatwg.org/multipage/forms.html#the-select-element:nodes-are-inserted

https://jsfiddle.net/vjupL02r/

2016-10-19 19:18 UTC, frewsxcv commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
From what I understand, as long as there are undisabled `<option>`s in the "list of options", there will always be a selected item.

2016-10-19 20:06 UTC, KiChjang commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
Looks like we should also have a test case when one of the child options [asks for a reset](https://html.spec.whatwg.org/multipage/forms.html#ask-for-a-reset).

2016-10-19 20:07 UTC, frewsxcv commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
How is that related to `selectedIndex`?

2016-10-19 22:18 UTC, KiChjang commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
The algorithm for selecting an option also runs when any of the child options asks for a reset.

2016-10-20 04:01 UTC, frewsxcv commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
That's being taken care of in https://github.com/servo/servo/pull/13762/.

2016-10-20 17:21 UTC, KiChjang commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
Your current tests doesn't have a case where it attempts to reset an options element, and then testing whether the selectedIndex of the parent select element is correct.

2016-10-20 19:19 UTC, frewsxcv commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
To rephrase my previous comment: I added such a test to this branch (not yet pushed), though it depends on #13762 merging first.

2016-10-21 15:48 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13784) made this pull request unmergeable. Please resolve the merge conflicts.

2016-10-24 18:22 UTC, frewsxcv commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
Let me know what you think of my latest force push.

2016-10-24 18:22 UTC, frewsxcv commented on tests/wpt/web-platform-tests/html/semantics/forms/the-select-element/selected-index.html
> +  assert_equals(select.selectedIndex, 0);
For what it's worth, this pull request is not modifying the behavior of resetting selections, this is just a pull request for the `selectedIndex` property.

2016-10-24 18:39 UTC, KiChjang approved these changes

2016-10-24 18:40 UTC, KiChjang commented
LGTM

@bors-servo r+

2016-10-24 18:40 UTC, bors-servo commented
:pushpin: Commit bec5bf4 has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang bec5bf49bd921ce2370b105db2a34407507cce08 -->

2016-10-24 18:40 UTC, bors-servo commented
:hourglass: Testing commit bec5bf4 with merge 94ab590...

2016-10-24 19:24 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3739)

2016-10-24 19:30 UTC, KiChjang commented
@bors-servo retry
* #13887

2016-10-24 19:31 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/3679), [arm64](http://build.servo.org/builders/arm64/builds/3688), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3751), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/397), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/393), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3756), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/436), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/437), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1654) are reusable. Rebuilding only [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3739)...

2016-10-24 20:22 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3679), [arm64](http://build.servo.org/builders/arm64/builds/3688), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3751), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/397), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/393), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3756), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3740), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/436), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/437), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1654)

2016-10-24 20:23 UTC, merged