Implement Step 1 of Response API Clone Method
servo/servo pull request #13895
Opened 2016-10-22 21:23 UTC by lautat

Implements first step of response API Clone method. Response Clone test expectations have been updated. Fixes issue #13888.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13888.

- [X] There are tests for these changes

2016-10-22 21:23 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @kichjang (or someone else) soon.

2016-10-22 21:23 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/response.rs
 * @kichjang: components/script/dom/response.rs

2016-10-22 23:11 UTC, KiChjang requested changes
Looks good! Just 2 minor nits and r=me.

2016-10-22 23:11 UTC, KiChjang commented on components/script/dom/response.rs
> +        if self.is_locked() || self.BodyUsed() {
nit: This can just be `self.body_used.get()` instead of `self.BodyUsed()`.

2016-10-22 23:11 UTC, KiChjang commented on components/script/dom/response.rs
> +            return Err(Error::Type("cannot clone a disturbed response".to_string()))
nit: Add a semi-colon at the end of this line.

2016-10-23 12:30 UTC, jdm commented
@bors-servo: r=KiChjang

2016-10-23 12:30 UTC, bors-servo commented
:pushpin: Commit 65a7747 has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 65a774786444065eaa59a727e9c8851ef2bb40d5 -->

2016-10-23 12:55 UTC, bors-servo commented
:hourglass: Testing commit 65a7747 with merge 2772626...

2016-10-23 13:47 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3721)

2016-10-23 15:57 UTC, jdm commented
@bors-servo: retry
* #13887

2016-10-23 16:29 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/3663), [arm64](http://build.servo.org/builders/arm64/builds/3672), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3735), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/378), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/376), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3740), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/420), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/421), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1638) are reusable. Rebuilding only [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3721)...

2016-10-23 17:21 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3663), [arm64](http://build.servo.org/builders/arm64/builds/3672), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3735), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/378), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/376), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3740), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3722), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/420), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/421), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1638)

2016-10-23 17:21 UTC, merged