[WIP] WebBluetooth fixes for the wpt tests
servo/servo pull request #13918
Opened 2016-10-25 14:28 UTC by zakorgy

Note: depends on #13612
WebBluetooth fixes for the failing wpt tests, excluding the `disconnect-during` tests cases, due to the lack of the event handling in the current implementation.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes OR

2016-10-25 14:28 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/bluetoothdevice.rs, components/script/dom/webidls/TestRunner.webidl, components/script/dom/webidls/Window.webidl, components/script/dom/window.rs, components/script/dom/testrunner.rs, components/script/dom/bluetooth.rs, components/script/dom/webidls/BluetoothDevice.webidl, components/script/dom/mod.rs, components/script/dom/bluetoothremotegattserver.rs, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs
 * @kichjang: components/script/dom/bluetoothdevice.rs, components/net_traits/bluetooth_scanfilter.rs, components/net_traits/bluetooth_scanfilter.rs, components/script/dom/webidls/TestRunner.webidl, components/script/dom/webidls/Window.webidl, components/net/lib.rs, components/net/bluetooth_thread.rs, components/script/dom/window.rs, components/script/dom/testrunner.rs, components/script/dom/bluetooth.rs, components/net/Cargo.toml, components/script/dom/webidls/BluetoothDevice.webidl, components/script/dom/mod.rs, components/script/dom/bluetoothremotegattserver.rs, components/net/bluetooth_test.rs, components/script/dom/bluetoothremotegattservice.rs, components/net_traits/bluetooth_thread.rs, components/net_traits/bluetooth_thread.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs

2016-10-25 14:28 UTC, zakorgy commented
r? @jdm

2016-10-31 19:23 UTC, jdm requested changes
These changes are largely fine.

2016-10-31 19:23 UTC, jdm commented on components/net_traits/bluetooth_scanfilter.rs
> +        match &self.name {
`self.name.as_ref().map(|s| s.as_str())`

2016-10-31 19:23 UTC, jdm commented on components/net_traits/bluetooth_scanfilter.rs
> +         self.get_name().unwrap_or("").len() > MAX_NAME_LENGTH ||
These lines should be unindented by one, since they are not part of the subexpression.

2016-10-31 19:23 UTC, jdm commented on components/net/bluetooth_thread.rs
> +use script::bluetooth_blacklist::{uuid_is_blacklisted, Blacklist};
These helpers need to move into net_traits instead.

2016-10-31 19:23 UTC, jdm commented on components/net/Cargo.toml
> +script = {path = "../script"}
We need to find a way not to do this; it's useful for net to be able to build without depending on script.

2016-11-02 14:25 UTC, jdm requested changes

2016-11-02 14:25 UTC, jdm commented on components/servo/Cargo.lock
> + "regex 0.1.76 (registry+https://github.com/rust-lang/crates.io-index)",
We'll need to run `./mach cargo-update -p net_traits` to ensure that ports/cef/Cargo.lock is updated too.

2016-11-02 14:25 UTC, jdm commented
Other than that, this is good to merge after #13612.

2016-11-07 14:43 UTC, zakorgy commented
The last commit solves #14112.

2016-11-07 15:02 UTC, jdm commented
@bors-servo: r+

2016-11-07 15:02 UTC, bors-servo commented
:pushpin: Commit 91a0c4d has been approved by `jdm`

<!-- @bors-servo r=jdm 91a0c4d50da7df38e2902e29fbec699e34ee892b -->

2016-11-07 15:50 UTC, bors-servo commented
:hourglass: Testing commit 91a0c4d with merge eb2484f...

2016-11-07 16:53 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3946), [arm64](http://build.servo.org/builders/arm64/builds/3952), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4045), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/688), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/687), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4030), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4026), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/710), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/723), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1958)

2016-11-07 16:53 UTC, merged