Use headless rendering for performance test
servo/servo pull request #13930
Opened 2016-10-26 09:47 UTC by shinglyu

Properly set the software rendering environment variables and use `-z` to run the performance test in headless mode. Also changed some logging format to improve the readability and reduce log size.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13903 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because need manual test

2016-10-26 09:47 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/testing_commands.py
 * @aneeshusa: etc/ci/performance/README.md, etc/ci/performance/runner.py, etc/ci/performance/test_perf.sh

2016-10-26 09:48 UTC, shinglyu commented
r? @aneeshusa

2016-10-26 16:03 UTC, jdm commented
```
41.81s$ ./mach test-tidy --no-progress --all
Checking the config file...
Checking directories for correct file extensions...
Checking files for tidiness...
./python/servo/testing_commands.py:656: F821 undefined name 'kwargs'
./python/servo/testing_commands.py:656: F821 undefined name 'kwargs'
./python/servo/testing_commands.py:670: E303 too many blank lines (3)
```

2016-10-27 16:37 UTC, aneeshusa commented on etc/ci/performance/runner.py
> +            "-z",
nit: use long form (`--headless`) for readability

2016-10-27 16:38 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
> +    echo "Found existing test cases, skip download."
grammar: `skip` -> `skipping`

2016-10-27 16:38 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
> +    echo "Found existing test cases, skip unzip."
grammar: `skip` -> `skipping`

2016-10-27 16:40 UTC, aneeshusa commented on python/servo/testing_commands.py
> +        if sys.platform.startswith('darwin'):
nit: `if` -> `elif`

2016-10-27 16:42 UTC, aneeshusa commented
Looks good overall, though I'd like to try this out by hand.
In particular, I like that the caching is now smart about not re-downloading, but I want to confirm it works properly.
Not required but it may be nicer to split into multiple commits:
- Update caching/downloading script
- Use headless rendering for performance testing
- Update logging messages

2016-10-28 07:01 UTC, shinglyu commented
I'm splitting the patches, hold on.

2016-10-28 07:05 UTC, shinglyu commented
Done!

2016-10-30 06:31 UTC, aneeshusa requested changes
Looks good overall, just a few nits about the caching behavior.

2016-10-30 06:31 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
> +    unzip -o "${TP5N_PATH}" -d "$(dirname "${TP5N_PATH}")"
Please add the `-q` (quiet) option to suppress printing the list of files extracted.

2016-10-30 06:31 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
> +    unzip -o "${TP5N_PATH}" -d "$(dirname "${TP5N_PATH}")"
And possibly some print statements around the `unzip` call so the user knows extraction is happening, e.g. `Extracting...done`.

2016-10-30 06:31 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
> +    echo "Found existing test cases, skipping download."
Check for the extracted test cases first, since we can skip downloading the zip file if we already have the extracted copies of the files.

2016-11-07 02:13 UTC, shinglyu commented
review ping @aneeshusa

2016-11-07 05:57 UTC, aneeshusa commented
Thanks for the ping.
Code looks good, move all the `etc/ci/performance/test_perf.sh` changes into the first commit (i.e. from the last commit) and r=me.

2016-11-07 07:23 UTC, shinglyu commented
Done, I'll start merging by myself. Thanks!

2016-11-07 07:24 UTC, shinglyu commented
@bors-servo: try, r=aneeshusa

2016-11-07 07:24 UTC, bors-servo commented
:pushpin: Commit 2407fe6 has been approved by `aneeshusa`

<!-- @bors-servo r=aneeshusa 2407fe614be6eb7ca8fddb2c666d3bb3b672dcf8 -->

2016-11-07 07:24 UTC, bors-servo commented
:hourglass: Testing commit 2407fe6 with merge f5a3d68...

2016-11-07 08:15 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3935), [arm64](http://build.servo.org/builders/arm64/builds/3941), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4033), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/675), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/675), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4018), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4014), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/698), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/710), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1944)

2016-11-07 08:15 UTC, merged