Check that an iframe is in a document with a browsing context before processing src
servo/servo pull request #13965
Opened 2016-10-28 18:11 UTC by asajeffrey

Check that an iframe is in a document with a browsing context before processing src.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13964.
- [X] These changes do not require tests because this is already tested by https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/old-tests/submission/Opera/script_scheduling/034.html

2016-10-28 18:11 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmliframeelement.rs, components/script/dom/node.rs
 * @kichjang: components/script/dom/htmliframeelement.rs, components/script/dom/node.rs

2016-10-28 18:11 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-10-28 18:11 UTC, asajeffrey commented
cc @Ms2ger

2016-10-31 16:34 UTC, Ms2ger requested changes
r? @Ms2ger

2016-10-31 16:34 UTC, Ms2ger commented on components/script/dom/node.rs
> +    pub fn is_in_a_document_tree(&self) -> bool {
This duplicates `is_in_doc()` very slowly; please remove.

2016-10-31 16:34 UTC, Ms2ger commented on components/script/dom/node.rs
> +        self.inclusive_ancestors().last()
This can be `self.is_in_doc() && self.owner_doc().browsing_context().is_some()`

2016-10-31 17:47 UTC, asajeffrey commented on components/script/dom/node.rs
> +    pub fn is_in_a_document_tree(&self) -> bool {
The problem is that `is_in_doc` returns true if the node is in a document fragment.

2016-10-31 17:47 UTC, asajeffrey commented on components/script/dom/node.rs
> +        self.inclusive_ancestors().last()
Same problem.

2016-11-01 19:57 UTC, asajeffrey commented
@Ms2ger should I fix `is_in_doc` so that it returns `false` when it's in a `DocumentFragment`?

2016-11-02 10:06 UTC, Ms2ger commented
> The problem is that `is_in_doc` returns true if the node is in a document fragment.

That sounds like a pretty serious bug. Are you sure?

CC @nox.

2016-11-02 13:34 UTC, nox commented
> The problem is that is_in_doc returns true if the node is in a document fragment.

That doesn't sound true to me. Where did you find that?

2016-11-02 14:21 UTC, asajeffrey commented
OK, I'll go and check.

2016-11-02 15:16 UTC, asajeffrey commented
Unsurprisingly, you are both right. Hmm. I could have sworn I was getting an error because of this. Oh well, I'll fix this.

2016-11-02 19:14 UTC, asajeffrey commented
I remember what the issue was! It's that `owner_doc` is `Some(document)` even when the node is in a document fragment. `is_in_doc` is fine.

2016-11-03 14:11 UTC, Ms2ger requested changes

2016-11-03 14:11 UTC, Ms2ger commented on components/script/dom/node.rs
> +        self.is_in_doc() && self.owner_doc().is_html_document()
Unfortunately this needs to return true if `is_in_doc()` is false. Maybe you should just inline it into its only caller, to avoid confusion.

2016-11-03 14:26 UTC, asajeffrey commented on components/script/dom/node.rs
> +        self.is_in_doc() && self.owner_doc().is_html_document()
Fixed.

2016-11-03 15:05 UTC, Ms2ger commented
r=me if you squash all commits

2016-11-03 15:06 UTC, Ms2ger approved these changes

2016-11-03 15:07 UTC, asajeffrey commented
@Ms2ger thanks! @bors-servo r=Ms2ger

2016-11-03 15:07 UTC, bors-servo commented
:pushpin: Commit 330953a has been approved by `Ms2ger`

<!-- @bors-servo r=Ms2ger 330953aedd09d8b8c6cca9b78f150ec1c7fa644a -->

2016-11-03 15:12 UTC, bors-servo commented
:hourglass: Testing commit 330953a with merge 06e3ed9...

2016-11-03 16:19 UTC, larsbergstrom commented
@bors-servo clean force retry

2016-11-03 17:52 UTC, asajeffrey commented
Rebased to unstick homu.

2016-11-03 17:52 UTC, KiChjang commented
@bors-servo r=Ms2ger

2016-11-03 17:52 UTC, bors-servo commented
:pushpin: Commit 1803a58 has been approved by `Ms2ger`

<!-- @bors-servo r=Ms2ger 1803a585e5eb388830efac7e80d582f2fa4eb652 -->

2016-11-03 19:03 UTC, bors-servo commented
:hourglass: Testing commit 1803a58 with merge 4984a83...

2016-11-03 20:04 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3858), [arm64](http://build.servo.org/builders/arm64/builds/3871), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3950), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/591), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/593), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3938), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3932), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/620), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/627), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1855)

2016-11-03 20:04 UTC, merged