Script thread with no root document
servo/servo pull request #14013
Opened 2016-11-01 20:19 UTC by asajeffrey

This PR removes the single root document from the script thread, and replaces it by a lookup table from `PipelineId`s to `Document`s. This is needed if we're going to share script threads, as per #633.

The last commit is the one that matters, the ones before are #13646.

cc @jdm @Ms2ger @ConnorGBrewster 
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because refactoring

2016-11-01 20:19 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/webdriver_handlers.rs, components/script/dom/node.rs, components/script/dom/browsingcontext.rs, components/script/dom/storage.rs, components/script_traits/script_msg.rs, components/script_traits/script_msg.rs, components/script/document_loader.rs, components/script/dom/nodelist.rs, components/script/script_thread.rs, components/script_traits/lib.rs, components/script_traits/lib.rs, components/script/devtools.rs
 * @kichjang: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/webdriver_handlers.rs, components/net/http_loader.rs, components/script/dom/node.rs, components/script/dom/browsingcontext.rs, components/script/dom/storage.rs, components/script_traits/script_msg.rs, components/script_traits/script_msg.rs, components/script/document_loader.rs, components/script/dom/nodelist.rs, components/script/script_thread.rs, components/script_traits/lib.rs, components/script_traits/lib.rs, components/script/devtools.rs

2016-11-01 20:19 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2016-11-01 20:36 UTC, frewsxcv commented on components/script/script_thread.rs
> +            let current_url = document.url().to_string();
You might be able to get by with `let current_url = document.url().as_str();` here?

2016-11-01 20:47 UTC, emilio commented
@bors-servo try

2016-11-01 20:47 UTC, bors-servo commented
:hourglass: Trying commit d8de7de with merge 2d7d730...

2016-11-01 21:46 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3820), [arm64](http://build.servo.org/builders/arm64/builds/3830), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3908), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/548), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/550), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3898), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3890), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/579), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/586), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1812)

2016-11-02 20:18 UTC, asajeffrey commented on components/script/script_thread.rs
> +            let current_url = document.url().to_string();
It was a bit trickier than that, but I did manage to avoid double-copying the urls here.

2016-11-02 20:43 UTC, asajeffrey commented
Rebased. @bors-servo try

2016-11-02 20:43 UTC, bors-servo commented
:hourglass: Trying commit 18b7b5d with merge 2a6c3bb...

2016-11-03 07:19 UTC, bors-servo commented
:boom: Test timed out

2016-11-03 12:47 UTC, jdm commented
@bors-servo: try

2016-11-03 12:47 UTC, jdm commented
@bors-servo: retry

2016-11-03 12:47 UTC, bors-servo commented
:hourglass: Trying commit 18b7b5d with merge 4fe3e6f...

2016-11-03 13:31 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/582)

2016-11-03 13:51 UTC, asajeffrey commented
```
  ▶ CRASH [expected FAIL] /css-text-3_dev/html/line-break-strict-017.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread main, at ../src/libcore/result.rs:837)
  │ stack backtrace:
  │    0:     0x7ffc0078f3ad - backtrace::backtrace::trace::h16372ee7bf1517e5
  │    1:     0x7ffc0078fa42 - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
  │    2:     0x7ffbff126e7d - servo::main::_{{closure}}::h993bd385ff269be0
  │    3:     0x7ffc00d52b74 - std::panicking::rust_panic_with_hook
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:452
  │    4:     0x7ffc00d52a34 - std::panicking::begin_panic<collections::string::String>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
  │    5:     0x7ffc00d52959 - std::panicking::begin_panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
  │    6:     0x7ffc00d528e7 - std::panicking::rust_begin_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
  │    7:     0x7ffc00d8f34d - core::panicking::panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
  │    8:     0x7ffc008202df - core::result::unwrap_failed::h97cf4d1c2597280e
  │    9:     0x7ffc008213d2 - webrender_traits::api::_<impl webrender_traits..RenderApiSender>::create_api::h8aae9b868a4fcac9
  │   10:     0x7ffbff1248fd - servo::main::hf0cef208a66e3646
  │   11:     0x7ffc00d5b1da - panic_unwind::__rust_maybe_catch_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  │   12:     0x7ffc00d51b9a - std::panicking::try<(),fn()>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
  │                          - std::panic::catch_unwind<fn(),()>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
  │                          - std::rt::lang_start
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  │   13:     0x7ffbfca39f44 - __libc_start_main
  │   14:     0x7ffbff0f9909 - <unknown>
  │   15:                0x0 - <unknown>
  │ thread panicked while processing panic. aborting.
  └ thread panicked while processing panic. aborting.
```

2016-11-03 13:56 UTC, asajeffrey commented
Looks like #13480.

2016-11-03 20:06 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13965) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-03 20:57 UTC, asajeffrey commented
Rebased and squashed. @bors-servo try

2016-11-03 20:57 UTC, bors-servo commented
:hourglass: Trying commit 1080827 with merge 4aa4b02...

2016-11-03 22:39 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3860), [arm64](http://build.servo.org/builders/arm64/builds/3874), [linux-dev](http://build.servo.org/builders/linux-dev/builds/3953), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/595), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/597), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/3942), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3935), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/624), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/631), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1860)

2016-11-04 14:29 UTC, asajeffrey commented
Rebased. #13646 has landed, so now this one can too.

2016-11-07 16:37 UTC, jdm requested changes
Well done! There are a lot of straightforward changes here, and I like that some parts of the code actually became more straightforward with this change.

2016-11-07 16:37 UTC, jdm commented on components/script/script_thread.rs
> +        for document in self.documents.borrow().iter() {
If we can iterate over the keys and values simultaneously, we don't need to get the pipeline id from the window below.

2016-11-07 16:37 UTC, jdm commented on components/script/script_thread.rs
> +            let pending_reflows = document.window().get_pending_reflow_count();
Add a `let window = document.window()` here.

2016-11-07 16:37 UTC, jdm commented on components/script/script_thread.rs
> +            if reports.len() > 0 { path_seg.push_str(", "); }
nit: three lines for this, please.

2016-11-07 16:37 UTC, jdm commented on components/script/script_thread.rs
>          struct AutoContextRemover<'a> {
We can remove this entirely; there are no early returns from this method any more.

2016-11-07 16:37 UTC, jdm commented on components/script/script_thread.rs
> +    // sever the connection between the global and the DOM tree
The function is odd - `document.window()` can return a Window for a document that has no browsing context, but that doesn't mean that we want to shut down layout for that window. Perhaps this function should accept a `&Window` argument instead, and obtain the context from that.

2016-11-07 16:37 UTC, jdm commented on components/script/webdriver_handlers.rs
> +                  .find(|candidate| candidate.unique_id() == node_id))
nit: weird indentation.

2016-11-07 16:37 UTC, jdm commented on components/script/webdriver_handlers.rs
> +                .unwrap_or(Err(()))
`documents.find_window(pipeline).map(|window| window.parent()).ok_or(())`

2016-11-07 16:37 UTC, jdm commented on components/script/webdriver_handlers.rs
> +    let node_id = documents.find_document(pipeline)
```rust
let node_id = documents.find_document(pipeline)
    .ok_or(())
    .and_then(|doc| doc.QuerySelector(DOMString::from(selector)).map_err(|_| ()))
    .map(|node| node.map(|x| x.upcast::<Node>().unique_id()));
```

2016-11-07 16:37 UTC, jdm commented on components/script/webdriver_handlers.rs
> +        .map(|nodes| nodes.iter().map(|x| x.upcast::<Node>().unique_id()).collect());
Same as previous.

2016-11-07 16:37 UTC, jdm commented on components/script/webdriver_handlers.rs
>                           reply: IpcSender<Vec<Serde<Cookie>>>) {
nit: indentation.

2016-11-07 16:37 UTC, jdm commented on components/script_traits/script_msg.rs
> +    /// or to the window if no subpage id is provided.
How would no subpage id be provided?

2016-11-07 20:34 UTC, asajeffrey commented
@jdm thanks! I am trying to make the code easier to follow.

2016-11-07 20:56 UTC, asajeffrey commented on components/script/script_thread.rs
> +            let pending_reflows = document.window().get_pending_reflow_count();
Done.

2016-11-07 20:57 UTC, asajeffrey commented on components/script/script_thread.rs
> +            if reports.len() > 0 { path_seg.push_str(", "); }
Done.

2016-11-07 21:12 UTC, asajeffrey commented on components/script/webdriver_handlers.rs
> +                .unwrap_or(Err(()))
Done.

2016-11-07 21:16 UTC, asajeffrey commented on components/script/webdriver_handlers.rs
> +                  .find(|candidate| candidate.unique_id() == node_id))
Hey, this is what emacs rust mode did! Reindented.

2016-11-07 21:18 UTC, asajeffrey commented on components/script/webdriver_handlers.rs
> +        .map(|nodes| nodes.iter().map(|x| x.upcast::<Node>().unique_id()).collect());
Done.

2016-11-07 21:21 UTC, asajeffrey commented on components/script_traits/script_msg.rs
> +    /// or to the window if no subpage id is provided.
It happens, e.g., when we generate an error caused by a panic but we don't have a pipeline to blame it on, e.g. a panic from a resource thread.

2016-11-07 21:31 UTC, jdm commented on components/script_traits/script_msg.rs
> +    /// or to the window if no subpage id is provided.
Ok, but the types involved are PipelineId and PipelineId, so I still don't understand what this means.

2016-11-07 21:58 UTC, asajeffrey commented on components/script_traits/script_msg.rs
> +    /// or to the window if no subpage id is provided.
Oh oops, argh I reverted a code change but didn't revert the accompanying comment!

2016-11-07 22:41 UTC, jdm commented
Squash and merge!

2016-11-08 03:01 UTC, asajeffrey commented
Squashed. @bors-servo r=jdm

2016-11-08 03:01 UTC, bors-servo commented
:pushpin: Commit ae9268d has been approved by `jdm`

<!-- @bors-servo r=jdm ae9268de2c32eddf295a0f38e7b2016178bfe9f1 -->

2016-11-08 03:30 UTC, bors-servo commented
:hourglass: Testing commit ae9268d with merge 8236d19...

2016-11-08 04:04 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/703)

2016-11-08 14:45 UTC, asajeffrey commented
Hmm, failing tests. Puts on debugging hat...

2016-11-08 16:50 UTC, asajeffrey commented
@bors-servo r=jdm

2016-11-08 16:50 UTC, bors-servo commented
:pushpin: Commit 90e9c91 has been approved by `jdm`

<!-- @bors-servo r=jdm 90e9c910f4338adb01c322034a2cd3230e7e9b8c -->

2016-11-08 17:31 UTC, bors-servo commented
:hourglass: Testing commit 90e9c91 with merge d1b7f19...

2016-11-08 18:23 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3979), [arm64](http://build.servo.org/builders/arm64/builds/3985), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4078), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/721), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/720), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4063), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4059), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/743), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/756), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1991)

2016-11-08 18:24 UTC, merged