Storage notifications routed via the constellation.
servo/servo pull request #14023
Opened 2016-11-02 14:18 UTC by asajeffrey

At the moment, storage notifications are only sent within a script thread, not to same-origin pipelines in different script threads. This PR fixes that.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #5196
- [X] These changes do not require tests because existing tests now pass

2016-11-02 14:18 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/storage.rs, components/script_traits/script_msg.rs, components/script_traits/script_msg.rs, components/script/script_thread.rs, components/script_traits/lib.rs, components/script_traits/lib.rs
 * @kichjang: components/script/dom/storage.rs, components/script_traits/script_msg.rs, components/script_traits/script_msg.rs, components/script/script_thread.rs, components/script_traits/lib.rs, components/script_traits/lib.rs

2016-11-04 00:11 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13646) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-07 10:06 UTC, nox requested changes

2016-11-07 10:06 UTC, nox commented on components/constellation/constellation.rs
> +                let _ = pipeline.script_chan.send(msg);
Why ignore failure here?

2016-11-07 10:06 UTC, nox commented on components/constellation/constellation.rs
> +            if (pipeline.id != pipeline_id) && (pipeline.url.origin() == origin) {
Nit: remove parens.

2016-11-07 10:06 UTC, nox commented on components/constellation/constellation.rs
> +        };
<strike>Why ignore failure here? Why isn't that method taking an `Url` directly? I see below that the `String` comes directly from an `Url`, so please just unwrap the result of `Url::parse` or pass an actual `Url` around.</strike>

Oh I see you did that in second commit. Could you squash them?

2016-11-07 10:06 UTC, nox commented on components/script/dom/storage.rs
> +            Some(&*storage)
Why the sudden `*`?

2016-11-07 10:06 UTC, nox commented on components/script_traits/script_msg.rs
> +    BroadcastStorageEvent(PipelineId, StorageType, String, Option<String>, Option<String>, Option<String>),
Maybe use a struct variant instead of documenting each field in prose?

2016-11-07 10:07 UTC, nox commented
GitHub somehow decided that some of my comments are outdated when they are not, please expand them when you read this @asajeffrey.

2016-11-08 17:07 UTC, asajeffrey commented on components/constellation/constellation.rs
> +        };
I'll squash them before merging.

2016-11-08 17:07 UTC, asajeffrey commented on components/constellation/constellation.rs
> +            if (pipeline.id != pipeline_id) && (pipeline.url.origin() == origin) {
Hmm, I prefer explicit parens rather than relying on operator pecedence to resolve ambiguity.

2016-11-08 17:07 UTC, asajeffrey commented on components/constellation/constellation.rs
> +                let _ = pipeline.script_chan.send(msg);
Fixed.

2016-11-08 17:10 UTC, asajeffrey commented
We should probably hold off on merging this until #14013 has landed, c.f. https://github.com/servo/servo/pull/14013/files#diff-ab86862fdf6e275f1f412558ce78bc2aR195.

2016-11-08 18:25 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14013) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-15 15:41 UTC, asajeffrey commented on components/script_traits/script_msg.rs
> +    BroadcastStorageEvent(PipelineId, StorageType, String, Option<String>, Option<String>, Option<String>),
I agree with you, but we should be consistent about it, not just adopt struct variants piecemeal.

2016-11-15 15:50 UTC, asajeffrey commented on components/script/dom/storage.rs
> +            Some(&*storage)
Apparently no good reason, not sure how this snuck in. Fixed.

2016-11-15 15:54 UTC, nox commented
Squash and r=me.

2016-11-15 15:58 UTC, asajeffrey commented
Squashed. @bors-servo r=nox

2016-11-15 15:58 UTC, bors-servo commented
:pushpin: Commit c91ef86 has been approved by `nox`

<!-- @bors-servo r=nox c91ef86a20813d433fb7fb595c37d611d27967d0 -->

2016-11-15 16:50 UTC, bors-servo commented
:hourglass: Testing commit c91ef86 with merge 07b9dbe...

2016-11-15 18:47 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4103), [arm64](http://build.servo.org/builders/arm64/builds/4110), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4204), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/853), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/850), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4186), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4184), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/872), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/882), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2121)

2016-11-15 18:47 UTC, merged