Network Security : Implement StrictOrigin and StrictOriginWhenCrossOr…
servo/servo pull request #14059
Opened 2016-11-04 08:08 UTC by mrnayak

This pull request contains commit implementing initial steps for Improving Network Security project. As part of initial steps referer policy enums for strict-origin and strict-origin-when-cross-origin have been added to hyper([https://github.com/hyperium/hyper/pull/943]). Unit tests and additional logic has been added to handle these policies. Since enum changes are available on hyper version 0.9.11. We had to update hyper version to 0.9.11.

Hyper 0.9.11 depends on num_cpus 1.1.0. To avoid different version of num_cpus. We have updated rayon version from 0.4.0 to 0.4.3. Cargo.toml of util, style, geckolib, stylo component has been updated to use num_cpus version 1.1.0 instead of 0.2.2.  

---

- [ X] `./mach build -d` does not report any errors
- [ X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

…igin

Referer policy strict-origin and strict-origin-when-cross-origin changes have been implemented. Relevant unit test cases have been added. Enum for RefererPolicy has been added to hyper codebase and v 0.9.11 of hyper contains these changes.

This commit also contains changes related to upgrade of hyper from v0.9.10 to v0.9.11. Other dependencies changed are rayon, utils, num_cpus.

2016-11-04 11:45 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #13816) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-04 11:54 UTC, nox requested changes
Some nits.

2016-11-04 11:54 UTC, nox commented on components/net/http_loader.rs
> +    return strip_url(referrer_url, true);
Nit: `return` is useless here.

2016-11-04 11:54 UTC, nox commented on components/net/http_loader.rs
> +        return strip_url(referrer_url, false);
Nit: `return` is useless here and doing `strip_url(referrer_url, cross_origin)` is shorter.

2016-11-04 11:54 UTC, nox commented on components/net/http_loader.rs
> +    let cross_origin = referrer_url.origin() != url.origin();
Nit: you can do that after the `return None` shortcut.

2016-11-04 11:54 UTC, nox commented on components/net/http_loader.rs
> +    } else {
Nit: no need for a `else` here, removing it reduces indentation which is nice.

2016-11-04 11:54 UTC, nox commented
@bors-servo try

2016-11-04 11:54 UTC, bors-servo commented
:lock: Merge conflict

2016-11-04 15:25 UTC, mrnayak commented on components/net/http_loader.rs
> +    return strip_url(referrer_url, true);
Can you please elaborate why return is not required?

Thanks,
Raghav

2016-11-04 15:44 UTC, nox commented on components/net/http_loader.rs
> +    return strip_url(referrer_url, true);
It's the last expression of the function, and the last expression in a function is the function's return value.

2016-11-04 16:16 UTC, mrnayak commented on components/net/http_loader.rs
> +    return strip_url(referrer_url, true);
Thank you,

I will change and commit the changes

2016-11-04 16:38 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14054) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-04 17:29 UTC, jdm commented
@bors-servo: try

2016-11-04 17:30 UTC, bors-servo commented
:hourglass: Trying commit e0e734f with merge 7586dd8...

2016-11-04 18:22 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/654)

2016-11-04 18:22 UTC, highfive commented
▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/http-rp/cross-origin/http-http/script-tag/cross-insecure.keep-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via script-tag using the http-rp\n                                 delivery method with keep-origin-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/http-rp/cross-origin/http-http/script-tag/cross-insecure.no-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via script-tag using the http-rp\n                                 delivery method with no-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/http-rp/cross-origin/http-http/script-tag/cross-insecure.swap-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via script-tag using the http-rp\n                                 delivery method with swap-origin-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/http-rp/cross-origin/http-http/xhr-request/cross-insecure.keep-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via xhr-request using the http-rp\n                                 delivery method with keep-origin-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/http-rp/cross-origin/http-http/xhr-request/cross-insecure.no-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via xhr-request using the http-rp\n                                 delivery method with no-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/http-rp/cross-origin/http-http/xhr-request/cross-insecure.swap-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via xhr-request using the http-rp\n                                 delivery method with swap-origin-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/http-rp/same-origin/http-http/script-tag/same-insecure.swap-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via script-tag using the http-rp\n                                 delivery method with swap-origin-redirect and when\n                                 the target request is same-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/http-rp/same-origin/http-http/xhr-request/same-insecure.swap-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via xhr-request using the http-rp\n                                 delivery method with swap-origin-redirect and when\n                                 the target request is same-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/meta-referrer/cross-origin/http-http/script-tag/cross-insecure.no-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via script-tag using the meta-referrer\n                                 delivery method with no-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/meta-referrer/cross-origin/http-http/script-tag/cross-insecure.keep-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via script-tag using the meta-referrer\n                                 delivery method with keep-origin-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/meta-referrer/cross-origin/http-http/script-tag/cross-insecure.swap-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via script-tag using the meta-referrer\n                                 delivery method with swap-origin-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/meta-referrer/cross-origin/http-http/xhr-request/cross-insecure.keep-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via xhr-request using the meta-referrer\n                                 delivery method with keep-origin-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/meta-referrer/cross-origin/http-http/xhr-request/cross-insecure.no-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via xhr-request using the meta-referrer\n                                 delivery method with no-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/meta-referrer/cross-origin/http-http/xhr-request/cross-insecure.swap-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is origin when a\n                                 document served over http requires an http\n                                 sub-resource via xhr-request using the meta-referrer\n                                 delivery method with swap-origin-redirect and when\n                                 the target request is cross-origin.
    
      ▶ Unexpected subtest result in /referrer-policy/strict-origin-when-cross-origin/meta-referrer/same-origin/http-http/script-tag/same-insecure.swap-origin-redirect.http.html:
      └ PASS [expected FAIL] The referrer URL is  [...]

2016-11-04 18:28 UTC, jdm commented
Look at all those newly-passing tests! The timeout is #14067 and can be ignored, but the rest need to have their [expected results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) updated.

2016-11-04 18:36 UTC, jdm commented
Also, it looks like there was a rebase error in cef/Cargo.lock: https://github.com/servo/servo/pull/14059/files#diff-f58e90618d14a4b6a043be78f4a4af21R2882

2016-11-05 04:10 UTC, gurudarshan266 commented
@jdm All the .ini files corresponding to PASSing testcases have been removed for strict-origin and strict-origin-when-cross-origin referrer policies

2016-11-07 08:56 UTC, nox commented
@bors-servo r+

2016-11-07 08:56 UTC, bors-servo commented
:pushpin: Commit e0132b9 has been approved by `nox`

<!-- @bors-servo r=nox e0132b98cc223a666778ab8280b675307929c3b9 -->

2016-11-07 10:37 UTC, bors-servo commented
:hourglass: Testing commit e0132b9 with merge dd34b2a...

2016-11-07 12:34 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3939), [arm64](http://build.servo.org/builders/arm64/builds/3945), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4038), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/681), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/680), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4023), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4019), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/703), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/716), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1951)

2016-11-07 12:35 UTC, merged