[WIP] Add redirect_mode to RequestInit
servo/servo pull request #14083
Opened 2016-11-05 17:12 UTC by rnestler

This adds support for non-follow redirect modes for `RequestInit`.
---
- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #14018 (github issue number if applicable).
- [ ] There are tests for these changes

2016-11-05 17:12 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/fetch.rs
 * @kichjang: components/script/fetch.rs, components/net_traits/request.rs, components/net_traits/request.rs

2016-11-05 17:12 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-11-05 17:17 UTC, emilio commented
Looks great! I think this still needs to update `Request::from_init`, right?

r? @jdm

2016-11-05 17:21 UTC, rnestler commented
> Looks great! I think this still needs to update Request::from_init, right?

Yes exactly, but I wanted to get feedback early on.

2016-11-05 18:12 UTC, jdm requested changes

2016-11-05 18:12 UTC, jdm commented on components/net_traits/request.rs
> +            redirect_mode: RedirectMode::Manual,
According to https://fetch.spec.whatwg.org/#concept-request-redirect-mode the default should be Follow.

2016-11-05 18:45 UTC, rnestler commented on components/net_traits/request.rs
> +            redirect_mode: RedirectMode::Manual,
Done. Thanks for the link! I'm not really familiar with those specs.

2016-11-05 18:58 UTC, jdm commented
Looks great? Have you run the tests locally?

2016-11-05 19:06 UTC, rnestler commented
> Looks great? Have you run the tests locally?

Yes and I have 2 "unexpected success" so I need to adapt the ini file.
```
./mach test-wpt tests/wpt/web-platform-tests/fetch/api/
....
Ran 118 tests finished in 45.0 seconds.
  • 109 ran as expected. 1 tests skipped.
  • 2 tests unexpectedly okay
  • 9 tests had unexpected subtest results
```

2016-11-05 20:07 UTC, rnestler commented on tests/wpt/metadata/fetch/api/cors/cors-cookies-worker.html.ini
> +    expected: PASS
Should I delete the ini file if it only contains PASS?

2016-11-05 20:55 UTC, jdm commented on tests/wpt/metadata/fetch/api/cors/cors-cookies-worker.html.ini
> +    expected: PASS
Yes please.

2016-11-05 22:03 UTC, rnestler commented
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/net_traits/request.rs, line 162 at r1](https://reviewable.io:443/reviews/servo/servo/14083#-KVpT_TT98N1II6LMyT7-r1-162:-KVqVagf6crThld0dgxv:b-896fix) ([raw file](https://github.com/servo/servo/blob/a520e434f7d30f1adc82393357dda69aee54c4d6/components/net_traits/request.rs#L162)):*
<details><summary><i>Previously, rnestler (Raphael Nestler) wrote…</i></summary>
> Done. Thanks for the link! I'm not really familiar with those specs.
</details>
Done.

---

*[tests/wpt/metadata/fetch/api/cors/cors-cookies-worker.html.ini, line 4 at r4](https://reviewable.io:443/reviews/servo/servo/14083#-KVq4VHRwhYE1BReO9bM-r4-4:-KVqVksWcYVJqDxwxm5-:b-896fix) ([raw file](https://github.com/servo/servo/blob/e9a416c383f2fcacd3d8f06616bc11702d500c7e/tests/wpt/metadata/fetch/api/cors/cors-cookies-worker.html.ini#L4)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Yes please.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/14083)*
<!-- Sent from Reviewable.io -->

2016-11-06 14:26 UTC, rnestler commented
I did try to update the expected test results according to the [Readme](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations). But I seem to hit a bug in the mach script:
```
./mach test-wpt --release --log-raw /tmp/servo.log                                                                             :(
Running 7727 tests in web-platform-tests

  ▶ FAIL [expected PASS] /_mozilla/css/pixel_snapping_glyphs.html
  └   → /_mozilla/css/pixel_snapping_glyphs.html f17ab077bf2fca2feab86dd80382d7a209cad99c
/_mozilla/css/pixel_snapping_glyphs_ref.html 8fd4ceac07c55bfc1afc22bbfa816c2d492670d6
Testing f17ab077bf2fca2feab86dd80382d7a209cad99c == 8fd4ceac07c55bfc1afc22bbfa816c2d492670d6

  ▶ PASS [expected FAIL] /_mozilla/css/text_decoration_underline_subpx_a.html

  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: Intl should be defined on the global scope expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:83:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:7:1

  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.worker:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: Intl should be defined on the global scope expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:83:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.worker.js:9:1

  ▶ Unexpected subtest result in /_mozilla/mozilla/localeCompare.html:
  │ FAIL [expected PASS] localeCompare should return the same as other browsers, even though it's implementation-dependent
  │   → assert_equals: expected -1 but got 8
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/localeCompare.html:3:3
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/localeCompare.html:2:1

Ran 7727 tests finished in 2161.0 seconds.
  • 7722 ran as expected. 1763 tests skipped.
  • 1 tests failed unexpectedly
  • 1 tests passed unexpectedly
  • 3 tests had unexpected subtest results

./mach test-wpt --release --log-raw /tmp/servo.log  16306.42s user 498.59s system 771% cpu 36:18.40 total
```

```
./mach update-wpt /tmp/servo.log                                                                                               :(


Warning: Duplicate heading /html/semantics/text-level-semantics/the-wbr-element/wbr-element.html
Error running mach:

    ['update-wpt', '/tmp/servo.log']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

KeyError

  File "/home/roughl/proggen/projects/servo/python/servo/testing_commands.py", line 495, in update_wpt
    return run_globals["update_tests"](**kwargs)
  File "/home/roughl/proggen/projects/servo/tests/wpt/update.py", line 25, in update_tests
    rv = update.run_update(logger, **kwargs)
  File "/home/roughl/proggen/projects/servo/tests/wpt/update/__init__.py", line 25, in run_update
    return updater.run()
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/update/update.py", line 151, in run
    rv = update_runner.run()
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/update/base.py", line 65, in run
    rv = step(self.logger).run(step_index, self.state)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/update/base.py", line 36, in run
    self.create(state)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/update/update.py", line 97, in create
    runner.run()
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/update/base.py", line 65, in run
    rv = step(self.logger).run(step_index, self.state)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/update/base.py", line 36, in run
    self.create(state)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/update/metadata.py", line 40, in create
    boolean_properties=state.boolean_properties)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/metadata.py", line 56, in update_expected
    boolean_properties=boolean_properties)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/metadata.py", line 152, in update_from_logs
    updater.update_from_log(f)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/metadata.py", line 232, in update_from_log
    reader.each_log(log_reader, self.action_map)
  File "/home/roughl/proggen/projects/servo/python/_virtualenv/lib/python2.7/site-packages/mozlog/reader.py", line 48, in each_log
    action_map[item["action"]](item)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/metadata.py", line 281, in test_end
    test_cls = wpttest.manifest_test_cls[test.test_type]
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/manifestupdate.py", line 146, in test_type
    return self.get("type", None)
  File "/home/roughl/proggen/projects/servo/tests/wpt/harness/wptrunner/wptmanifest/backends/conditional.py", line 234, in get
    raise KeyError
./mach update-wpt /tmp/servo.log  16.23s user 0.20s system 99% cpu 16.478 total
```

2016-11-06 16:27 UTC, jdm commented
Fun! I recommend generating the log by running test-wpt on the /fetch subdirectory of the tests, rather than running all of the tests. That should both work around the problem and reduce the number of tests that need to be run by a _huge_ amount.

2016-11-07 06:52 UTC, rnestler commented
I did run

    ./mach test-wpt --release --log-raw /tmp/servo.log tests/wpt/web-platform-tests/fetch
    ./mach update-wpt /tmp/servo.log

And it worked :smiley: But I can't really tell if the changes are correct.

2016-11-07 15:03 UTC, jdm commented
I'm going to wait on #14070 so we have a better sense of what this changes.

2016-11-08 14:10 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14116) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-08 16:41 UTC, jdm commented
@rnestler Can you update against the latest changes in master and run the tests again?

2016-11-09 13:04 UTC, rnestler commented
@jdm Done. The new test results seem much more plausible.

2016-11-09 15:02 UTC, jdm commented
@bors-servo: r+
I agree!

2016-11-09 15:02 UTC, bors-servo commented
:pushpin: Commit 26524e9 has been approved by `jdm`

<!-- @bors-servo r=jdm 26524e96f7949dec958249749b640cd6210d5245 -->

2016-11-09 15:19 UTC, bors-servo commented
:hourglass: Testing commit 26524e9 with merge 1ff364f...

2016-11-09 16:03 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/739)

2016-11-09 16:03 UTC, highfive commented
▶ FAIL [expected PASS] /_mozilla/css/incremental_trailing_whitespace_a.html
      └   → /_mozilla/css/incremental_trailing_whitespace_a.html da54041086f2975f8e3c776d2283ad6609e6862a
    /_mozilla/css/incremental_trailing_whitespace_ref.html f5d0147c8bddbdc772a7e5e86c7c9e433fcd486b
    Testing da54041086f2975f8e3c776d2283ad6609e6862a == f5d0147c8bddbdc772a7e5e86c7c9e433fcd486b

2016-11-09 17:19 UTC, jdm commented
@bors-servo: retry
* #10473

2016-11-09 18:42 UTC, bors-servo commented
:hourglass: Testing commit 26524e9 with merge 22874ff...

2016-11-09 19:24 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/767)

2016-11-09 19:30 UTC, jdm commented
@bors-servo: retry
#14152

2016-11-10 00:13 UTC, bors-servo commented
:hourglass: Testing commit 26524e9 with merge 58baf3e...

2016-11-10 01:08 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4010), [arm64](http://build.servo.org/builders/arm64/builds/4016), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4109), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/752), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/751), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4093), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4090), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/775), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/787), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2022)

2016-11-10 01:08 UTC, merged