Remove CollectMemoryReports from compositor (fixes #13735)
servo/servo pull request #14087
Opened 2016-11-05 19:59 UTC by MichaelKohler

Remove all of the code in compositor.rs related to:

* sending the RegisterReporter message
* sending the UnregisterReporter message
* the mem_profiler_chan member of IOCompositor
* move the code that sends the ProfilerMsg::Exit message into Constellation::handle_exit instead

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13735 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _____

2016-11-05 19:59 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2016-11-05 19:59 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/constellation.rs

2016-11-05 20:57 UTC, jdm requested changes

2016-11-05 20:57 UTC, jdm commented on components/compositing/compositor.rs
> -                    let msg = Msg::CollectMemoryReports(reporter_request.reports_channel);
I suspect the code that receives and processes this message can be removed as well. Probably the message variant from the enum, too.

2016-11-06 00:46 UTC, MichaelKohler commented
@jdm thanks for the review, I've updated this PR

2016-11-06 03:08 UTC, jdm commented
@bors-servo: r+
Thanks!

2016-11-06 03:08 UTC, bors-servo commented
:pushpin: Commit 1985ad6 has been approved by `jdm`

<!-- @bors-servo r=jdm 1985ad6d85faadab149a8b679c7b22c3ff0cb3c3 -->

2016-11-06 04:50 UTC, bors-servo commented
:hourglass: Testing commit 1985ad6 with merge 41e0b6a...

2016-11-06 06:00 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/679)

2016-11-06 06:00 UTC, highfive commented
▶ Unexpected subtest result in /XMLHttpRequest/responsexml-document-properties.htm:
      │ FAIL [expected PASS] lastModified set to time of response if no HTTP header provided
      │   → assert_less_than_equal: expected a number less than or equal to 1478411709 but got 1478415309
      │ 
      │ @http://web-platform.test:8000/XMLHttpRequest/responsexml-document-properties.htm:39:9
      │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
      │ test@http://web-platform.test:8000/resources/testharness.js:501:9
      └ @http://web-platform.test:8000/XMLHttpRequest/responsexml-document-properties.htm:35:7
    
      ▶ Unexpected subtest result in /html/dom/documents/resource-metadata-management/document-lastModified-01.html:
      │ FAIL [expected PASS] Date returned by lastModified is current at page load
      │   → assert_approx_equals: expected 1478411913 +/- 2.5 but got 1478415513
      │ 
      │ @http://web-platform.test:8000/html/dom/documents/resource-metadata-management/document-lastModified-01.html:8:5
      │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
      │ test@http://web-platform.test:8000/resources/testharness.js:501:9
      └ @http://web-platform.test:8000/html/dom/documents/resource-metadata-management/document-lastModified-01.html:7:3
    
      ▶ Unexpected subtest result in /html/dom/documents/resource-metadata-management/document-lastModified-01.html:
      │ FAIL [expected PASS] Date returned by lastModified is current after timeout.
      │   → assert_approx_equals: (initial value was 1478415513) expected 1478411917 +/- 2.5 but got 1478415517
      │ 
      │ @http://web-platform.test:8000/html/dom/documents/resource-metadata-management/document-lastModified-01.html:41:7
      │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
      └ @http://web-platform.test:8000/html/dom/documents/resource-metadata-management/document-lastModified-01.html:38:5

2016-11-06 16:25 UTC, jdm commented
@bors-servo: retry
* #14098

2016-11-06 16:30 UTC, bors-servo commented
:hourglass: Testing commit 1985ad6 with merge 72981db...

2016-11-06 17:36 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/663)

2016-11-06 18:54 UTC, jdm commented
@bors-servo: retry
* #12580

2016-11-06 20:01 UTC, bors-servo commented
:hourglass: Testing commit 1985ad6 with merge b5cf4db...

2016-11-06 21:04 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/3927), [arm64](http://build.servo.org/builders/arm64/builds/3934), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4025), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/666), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/668), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4011), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4006), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/691), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/702), [windows-dev](http://build.servo.org/builders/windows-dev/builds/1935)

2016-11-06 21:04 UTC, merged