Flexbox trace
servo/servo pull request #14124
Opened 2016-11-08 05:52 UTC by shinglyu

This is a follow up for #13740, so r? @jdm 

The first patch enables JSON serialization for flexbox flows, the second one fixed format incompatibilities for the layout viewer. 

The 3rd and 4th patches are just layout viewer UI enhancements, we could split that to a spearate PR if you prefer.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13846  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's a trivial debug tool

2016-11-08 05:52 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @emilio: components/layout/flow_list.rs, components/layout/flex.rs, components/layout/model.rs, components/layout/flow.rs

2016-11-08 05:52 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify layout code, but no tests are modified. Please consider adding a test!

2016-11-08 13:32 UTC, jdm requested changes

2016-11-08 13:32 UTC, jdm commented on components/layout/flex.rs
> +impl Serialize for FlexItem {
What's the deal with all this commented-out code?

2016-11-08 13:32 UTC, jdm commented
r? @glennw for the layout viewer changes.

2016-11-09 03:06 UTC, shinglyu commented on components/layout/flex.rs
> +impl Serialize for FlexItem {
I should have deleted them, must be my mistake while squashing.

2016-11-09 03:06 UTC, shinglyu commented
FYI: The new layout viewer screenshot ![selection_069](https://cloud.githubusercontent.com/assets/3250983/20125974/6e6ab256-a66c-11e6-8b50-5d3a0ede7508.png)

2016-11-09 10:51 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14130) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-17 09:19 UTC, shinglyu commented
@glennw: Do you have some time to review this patch? If not, do you mind I delegate it to someone else?

2016-12-01 05:52 UTC, glennw commented on components/layout/flow_list.rs
> +                    FlowClass::Block         => to_value(f.as_block()),
I'm not sure what the preferred formatting here is - but probably best to leave it as it was.

2016-12-01 05:53 UTC, glennw commented
@shinglyu Looks good to me, apart from that small formatting nit.

2016-12-13 06:22 UTC, shinglyu commented
@glennw Fixed and rebased! Is this ready for a r+?

2016-12-28 07:33 UTC, shinglyu commented on components/style/logical_geometry.rs
> +#[cfg_attr(feature = "servo", derive(Serialize))]
I fixed this line so Stylo won't derive `Serialize` anymore. Is this safe for Stylo? @Manishearth ?

2016-12-28 07:34 UTC, Manishearth commented on components/style/logical_geometry.rs
> +#[cfg_attr(feature = "servo", derive(Serialize))]
you'd need to use a build script with serde_codegen to make this work. I don't think we need this for stylo now, so we can just leave it out I guess.

2016-12-28 08:33 UTC, shinglyu commented
Thanks @Manishearth, looks like all the review comments are addressed and the tests are green. I'm going to merge this.

2016-12-28 08:33 UTC, shinglyu commented
@bors-servo r=glennw

2016-12-28 08:33 UTC, bors-servo commented
:pushpin: Commit 344ad61 has been approved by `glennw`

<!-- @bors-servo r=glennw 344ad61f2cbb0e18ca4fe80bf8b24ab3b05c42de -->

2016-12-28 08:33 UTC, bors-servo commented
:hourglass: Testing commit 344ad61 with merge 58fec2f...

2016-12-28 09:27 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4631), [arm32](http://build.servo.org/builders/arm32/builds/4805), [arm64](http://build.servo.org/builders/arm64/builds/4830), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4920), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1596), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1604), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4897), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4937), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1604), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1638), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/59), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/60)

2016-12-28 09:27 UTC, merged