Added an option to allow submitting test-perf result to perfherder
servo/servo pull request #14147
Opened 2016-11-09 07:02 UTC by shinglyu

This patch enables us  to run `./mach test-perf --submit` in CI to submit the result to perfherder. r? @aneeshusa 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because too many manual setup required to test it

2016-11-09 07:02 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/testing_commands.py
 * @aneeshusa: etc/ci/performance/README.md, etc/ci/performance/test_all.sh, etc/ci/performance/test_perf.sh

2016-11-14 09:11 UTC, Wafflespeanut commented on etc/ci/performance/README.md
> +If you want to run a performance test for your servo build. Simply go to the top-level servo directory and run `./mach test-perf`. The test result JOSN will be saved to `etc/ci/performance/output/`.
Nit: Fixing style,

"`./mach test-perf` can be used to run a performance test on your servo build. The test result JSON will be saved to `etc/ci/performance/output/`. You can then run `python test_differ.py` to compare these two test results. Run `python test_differ.py -h` for instructions."

2016-11-14 09:11 UTC, Wafflespeanut commented on etc/ci/performance/README.md
> +
What should be done here?

2016-11-15 06:12 UTC, aneeshusa requested changes
Just a few nits, looks like this will be useful!

2016-11-15 06:12 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
> +if [[ "${1}" = "--submit" ]]; then
You need to guard this by checking the number of arguments before looking at any of their values.

2016-11-15 06:12 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
>  ./git_log_to_json.sh > servo/revision.json && \
No need for the `&& \` at the end.

2016-11-15 06:12 UTC, aneeshusa commented on etc/ci/performance/test_perf.sh
>  mkdir -p output
Why do we need to make this `output` dir? Add a comment or remove it.

2016-11-15 06:12 UTC, aneeshusa commented on python/servo/testing_commands.py
> +            cmd += ["--submit"]
We should check that the Treeherder environment variables are set if `submit` is True before we actually run the command, to improve the user experience (e.g. if you don't read carefully).

2016-11-16 06:05 UTC, shinglyu commented on etc/ci/performance/README.md
> +
This H1 is for the subsections "For Servo" and "For Gecko", I'll change them to "CI for Servo" to make it clear.

2016-11-16 06:08 UTC, Wafflespeanut commented on etc/ci/performance/README.md
> +
Oh, never mind :smile:

2016-11-16 06:09 UTC, Wafflespeanut commented on etc/ci/performance/README.md
> +
But yeah, it could just be "CI for Servo"

2016-11-17 15:00 UTC, Wafflespeanut commented
./etc/ci/performance/test_perf.sh:38: variable substitutions should use the full "${VAR}" form

2016-11-26 15:34 UTC, Wafflespeanut commented
@aneeshusa This is waiting on your review.

2016-11-28 09:06 UTC, shinglyu commented
@aneeshusa Since there is no major issue, and I need to land this ASAP, I'll ask @larsbergstrom for the final sign-off. Hope you don't mind!

2016-11-29 03:00 UTC, larsbergstrom commented
@bors-servo r=larsbergstrom,aneeshusa

We can chat more in Hawaii if there are any follow-ups needed here :-)

2016-11-29 03:00 UTC, bors-servo commented
:pushpin: Commit 4f377ac has been approved by `larsbergstrom,aneeshusa`

<!-- @bors-servo r=larsbergstrom,aneeshusa 4f377ac448009bc0f53e99427b6d5dbd0c7b06c2 -->

2016-11-29 03:29 UTC, bors-servo commented
:hourglass: Testing commit 4f377ac with merge 90e77f9...

2016-11-29 04:22 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1198)

2016-11-29 05:22 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14194) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-01 02:30 UTC, shinglyu commented
The conflict is in the README file, so no big deal. The test seems to be some network error while running `filter-intermittents`

2016-12-01 02:33 UTC, shinglyu commented
@bors-servo r=larsbergstrom,aneeshusa

2016-12-01 02:33 UTC, bors-servo commented
:pushpin: Commit ddd0322 has been approved by `larsbergstrom,aneeshusa`

<!-- @bors-servo r=larsbergstrom,aneeshusa ddd03229e0f0247a7ffe1337025c4827a7851666 -->

2016-12-01 04:12 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4471), [arm64](http://build.servo.org/builders/arm64/builds/4479), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4561), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1237), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1257), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4537), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4558), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1249), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1262), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2503)

2016-12-01 04:12 UTC, merged