Home end key scroll2
servo/servo pull request #14141
Opened 2016-11-08 19:09 UTC by samuknet

* Refactor all scroll related code to use a new `ScrollLocation` struct which can either be a `delta` (as before) or a `Start` or `End` request, to represent the desire to scroll to the start and end of the page.
Effectively, everywhere a delta was used, there is now a `ScrollLocation` struct instead.

* Add key press listeners for HOME and END keys so as to cause a scroll to be queued with `ScrollLocation::Start` (in HOME case) or `ScrollLocation::End` (in END case).

* These changes depend on added support for the new `ScrollLocation` in webrender and webrender_traits.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ x] These changes fix #13082 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because scrolling I/O

2016-11-08 19:09 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @nox (or someone else) soon.

2016-11-09 11:42 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14145) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-17 14:54 UTC, gterzian commented
@samuknet Have you considered rebasing off the latest Servo? I think it might make the build pass, since this PR is using `webrender_traits 0.8.0`, and the `ScrollLocation` you added to webrender was not part of it at version `0.8.0`, since Servo itself has been upgraded to use `0.11.0`, rebasing might be just enough. 

I'm waiting for this one to land to be able to further test https://github.com/servo/webrender/pull/599 😄

2016-12-19 14:10 UTC, samuknet commented
@gterzian Working on it, should be up soon.  servo/webrender#599  looks cool :)

2016-12-20 05:19 UTC, samuknet commented
@gterzian 
I've done the rebase although when testing the home/end key scrolling doesn't actually happen on the webrender side.  The `webrender_traits` repos has not yet been updated to use the new `ScrollLocation` instead of deltas  - https://github.com/servo/webrender_traits/blob/master/src/api.rs#L184.  Should I go ahead and PR the changes separately on `webrender_traits`?

So what's happening is the [render_backend](https://github.com/servo/webrender/blob/master/webrender/src/render_backend.rs#L228-L230) is just sending through the deltas with:
`if self.frame.scroll(delta, cursor, move_phase)`
 which is the old way without `ScrollLocation`.

Although what's unusual is that `fn scroll(...)` in [`frame.rs`](https://github.com/servo/webrender/blob/master/webrender/src/frame.rs#L330-L331) is taking a `ScrollLocation` which seems different from the way `render_backend` is calling it?  I see that `webrender` is using the types from the un-updated `webrender_traits` separate repos although I don't see how `fn scroll` can be used with a delta signature in `render_backend.rs` but defined with a `ScrollLocation` in `frame.rs`.

2016-12-20 11:52 UTC, gterzian commented
@samuknet thanks for doing all this research! I think the `webrender_traits` repo you are looking at is not used anymore(last update seems to have been 5 months ago), and the code has been moved into the `webrender` repo. 

You can see [in the new repo](https://github.com/servo/webrender/blob/master/webrender_traits/src/api.rs#L184) that the `ScrollLocation` is indeed used in `ApiMsg::Scroll`

Also you could take a look at [this PR](https://github.com/servo/servo/pull/14412/files) because it looks like @glennw has done some work on the Servo side to integrate `webrender_traits::ScrollLocation`. 

I'm not sure why "when testing the home/end key scrolling doesn't actually happen", but maybe with the info above you can get an idea why?

2016-12-20 13:23 UTC, samuknet commented
@gterzian - thanks for this info.  Found the issue - changes to coordinates in WR meant the home/end safety checks were stopping the scroll in the wrong when they should have been allowing it.

Waiting now on https://github.com/servo/webrender/pull/656.

2016-12-21 13:12 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14652) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-21 14:02 UTC, jdm commented
That PR merged, so this is ready for review.

2016-12-21 14:03 UTC, jdm commented
It looks like this PR updates a bunch of other dependencies, though, which we probably want to avoid!

2016-12-21 18:29 UTC, KiChjang commented
The branch doesn't look like it's rebased; it looks more like there are 2 merges with the master branch.

2017-01-15 11:19 UTC, samuknet commented
@jdm any idea why the travis CI build failed? I suspect something is wrong with the `Cargo.lock` on this branch.

Thanks! :)

2017-01-15 16:06 UTC, jdm reviewed
The travis error is because our script that verifies that no accidental Cargo.lock changes were committed triggered.

2017-01-15 16:06 UTC, jdm commented on components/compositing/Cargo.toml
> +layers = {git = "https://github.com/servo/rust-layers", features = ["plugins"]}
This line was added and is not necessary. Probably a mistake while rebasing?

2017-01-15 17:19 UTC, jdm commented
r? @glennw

2017-01-15 17:33 UTC, glennw commented on ports/glutin/lib.rs
> +
nit: extra line here

2017-01-15 17:33 UTC, glennw commented on components/compositing/compositor.rs
> +                    if combined_event.phase != scroll_event.phase {
This if {} looks to be checking the exact condition that if if {} above it is checking - rebase error perhaps?

2017-01-15 17:33 UTC, glennw commented on components/compositing/compositor.rs
> +                        let combined_delta = match combined_event.scroll_location {
Is this code necessary? Won't the for loop have been broken out of by the condition above?

2017-01-15 17:33 UTC, glennw commented on components/compositing/compositor.rs
> +                                last_combined_event.scroll_location = ScrollLocation::Delta(delta + this_delta);
nit: extra spacing

2017-01-15 17:33 UTC, glennw commented on components/compositing/compositor.rs
> +                        ScrollLocation::Delta(delta) => {
nit: indentation

2017-01-15 17:42 UTC, samuknet commented on components/compositing/compositor.rs
> +                        let combined_delta = match combined_event.scroll_location {
For the `combined_event`, we know that it is a `Delta` at this point although I found myself having to do the match anyway in order to extract the actual delta. This leaves the awkward `_` match arm which should never be hit-  I wasn't sure what to write in the this arm.  Is there a more idiomatic way of doing this?

2017-01-19 22:25 UTC, glennw requested changes
Just a couple of minor changes. After those are fixed, r=me when squashed.

2017-01-19 22:25 UTC, glennw commented on components/compositing/compositor.rs
> +                _ => {
I'd prefer we remove the _ here and explicitly specify the Home/End enum values. That way, if/when new values are added to the enum, this becomes a compile error until they are accounted for here.

2017-01-19 22:25 UTC, glennw commented on components/compositing/compositor.rs
> +                        _ => {
Same as above.

2017-01-23 11:00 UTC, samuknet commented
@glennw All done and squashed - ready to go hopefully

2017-01-23 12:09 UTC, jdm commented
@bors-servo: r=glennw

2017-01-23 12:09 UTC, bors-servo commented
:pushpin: Commit 0c9c343 has been approved by `glennw`

<!-- @bors-servo r=glennw 0c9c3433e3479403d3fdd886c0ed0d45e24ab33a -->

2017-01-23 12:10 UTC, bors-servo commented
:hourglass: Testing commit 0c9c343 with merge 3535d5b...

2017-01-23 12:24 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5294)

2017-01-23 12:32 UTC, samuknet commented
@jdm Looks like this could be fixed by changing the macro in `browser_hosts.rs` on line 474 to be:

```rust
this.downcast().send_window_event(WindowEvent::Scroll(ScrollLocation::Delta(delta),
                                                                  origin,
                                                                  TouchEventType::Move))
```
This compilation error doesn't occur on my machine, I'm guessing because it depends on the platform?

2017-01-23 13:22 UTC, Ms2ger commented
Have you tried running `./mach build-cef`?

2017-01-23 13:40 UTC, samuknet commented
@Ms2ger Thanks for this - I've just pushed the nescessary changes in `browser_hosts.rs`.

2017-01-23 15:25 UTC, jdm commented
@bors-servo: r=glennw

2017-01-23 15:25 UTC, bors-servo commented
:pushpin: Commit 7e4255e has been approved by `glennw`

<!-- @bors-servo r=glennw 7e4255eb95ba5c95f1e86090109063c2f8694e14 -->

2017-01-23 15:26 UTC, bors-servo commented
:hourglass: Testing commit 7e4255e with merge 1706ffd...

2017-01-23 16:55 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5010), [arm32](http://build.servo.org/builders/arm32/builds/5182), [arm64](http://build.servo.org/builders/arm64/builds/5226), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5327), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2001), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2011), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5297), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5337), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1999), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2045), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/465), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/468)

2017-01-23 16:56 UTC, merged