specialized constructors for singly-exposed DOM types
servo/servo pull request #14160
Opened 2016-11-10 07:31 UTC by ajnirp

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14071 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because these are codegen changes and the generated code builds successfully

2016-11-10 07:31 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/comment.rs, components/script/dom/webglcontextevent.rs, components/script/dom/dommatrixreadonly.rs, components/script/dom/dommatrix.rs, components/script/dom/document.rs, components/script/dom/documentfragment.rs, components/script/dom/text.rs, components/script/dom/keyboardevent.rs, components/script/dom/range.rs, components/script/dom/focusevent.rs, components/script/dom/extendablemessageevent.rs, components/script/dom/domparser.rs, components/script/dom/htmlimageelement.rs, components/script/dom/mouseevent.rs, components/script/dom/transitionevent.rs, components/script/dom/extendableevent.rs, components/script/dom/uievent.rs
 * @fitzgen: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/comment.rs, components/script/dom/webglcontextevent.rs, components/script/dom/dommatrixreadonly.rs, components/script/dom/dommatrix.rs, components/script/dom/document.rs, components/script/dom/documentfragment.rs, components/script/dom/text.rs, components/script/dom/keyboardevent.rs, components/script/dom/range.rs, components/script/dom/focusevent.rs, components/script/dom/extendablemessageevent.rs, components/script/dom/domparser.rs, components/script/dom/htmlimageelement.rs, components/script/dom/mouseevent.rs, components/script/dom/transitionevent.rs, components/script/dom/extendableevent.rs, components/script/dom/uievent.rs
 * @emilio: components/script/dom/webglcontextevent.rs

2016-11-10 07:31 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-11-10 10:45 UTC, nox requested changes
Thanks for your contribution!

2016-11-10 10:45 UTC, nox commented on components/script/dom/bindings/codegen/CodegenRust.py
> +                                       globalName[0].upper() + globalName[1:])
Could you explain what these two lines are supposed to do? Also you may want to look at `MakeNativeName` in Configuration.py.

2016-11-10 10:45 UTC, nox commented on components/script/dom/bindings/codegen/CodegenRust.py
> +                glob = "global.upcast::<GlobalScope>()"
Why is this needed?

2016-11-10 10:45 UTC, nox commented on components/script/dom/webglcontextevent.rs
> +        let global = window.upcast::<GlobalScope>();
`WebGLContextEvent::new` should probably be made to take a `&Window` too.

2016-11-10 10:45 UTC, nox commented on components/script/dom/extendableevent.rs
> +        let global = worker.upcast::<GlobalScope>();
`ExtendableEvent::new` should take a `&Window`.

2016-11-10 10:45 UTC, nox commented on components/script/dom/extendablemessageevent.rs
> +        let global = worker.upcast::<GlobalScope>();
`ExtendableMessageEvent::new` should take a `&Window`.

2016-11-10 10:45 UTC, nox commented on components/script/dom/dommatrixreadonly.rs
> +    pub fn Constructor(window: &Window) -> Fallible<Root<Self>> {
`DOMMatrix` and friends are supposed to be `Exposed=(Window,Worker)`.

2016-11-11 01:26 UTC, ajnirp commented on components/script/dom/bindings/codegen/CodegenRust.py
> +                                       globalName[0].upper() + globalName[1:])
This is for the case when a DOM type is exposed to exactly one global. In that case, we downcast `global` from `GlobalScope` to that particular struct.

Thank you for pointing out `MakeNativeName`! I have fixed it.

2016-11-11 01:26 UTC, ajnirp commented on components/script/dom/webglcontextevent.rs
> +        let global = window.upcast::<GlobalScope>();
Done!

2016-11-11 01:26 UTC, ajnirp commented on components/script/dom/extendableevent.rs
> +        let global = worker.upcast::<GlobalScope>();
I think this should be `&ServiceWorkerGlobalScope`, based on `ExtendableEvent.webidl` Updated!

2016-11-11 01:26 UTC, ajnirp commented on components/script/dom/extendablemessageevent.rs
> +        let global = worker.upcast::<GlobalScope>();
Likewise, I think this should be `&ServiceWorkerGlobalScope` as well. Updated!

2016-11-11 13:23 UTC, nox requested changes

2016-11-11 13:23 UTC, nox commented on components/script/dom/bindings/codegen/CodegenRust.py
> +            downcast = """let global = global.downcast::<dom::{}::{}>().unwrap();\n"""
I think you can just do:

```python
let downcast = "global.downcast::<%s>().unwrap();" % descriptor.path
```

2016-11-11 13:23 UTC, nox commented on components/script/dom/extendablemessageevent.rs
> +        let global = worker.upcast::<GlobalScope>();
Oh right! :)

2016-11-11 13:23 UTC, nox commented on components/script/dom/webidls/DOMMatrix.webidl
> +Exposed=(Window,Worker)
Could you do that in a first separate commit?

2016-11-14 17:18 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14201) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-27 13:39 UTC, nox commented
Carried in #14376, thanks for your contribution!

2016-11-27 13:39 UTC, closed without merging