Add a few minimal debugging docs.
servo/servo pull request #14187
Opened 2016-11-12 20:41 UTC by emilio

r? @jdm (or anyone else)

2016-11-12 20:41 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/Cargo.toml
 * @wafflespeanut: python/servo/post_build_commands.py

2016-11-12 20:41 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style and layout code, but no tests are modified. Please consider adding a test!

2016-11-13 14:47 UTC, jdm requested changes
This is a nice improvement over the status quo of no docs :)

2016-11-13 14:47 UTC, jdm commented on docs/debugging.md
> +`--debug-mozjs` flag to `mach`.
`./mach build`

2016-11-13 14:47 UTC, jdm commented on docs/debugging.md
> +you might have to delete the `mozjs` build directory, or running `./mach clean`.
```
or run `./mach clean` before performing the first `--debug-mozjs` build.
```

2016-11-13 15:47 UTC, emilio commented
Amended, let me know if you think it's good to go :)

2016-11-13 20:16 UTC, jdm commented
@bors-servo: r+

2016-11-13 20:16 UTC, bors-servo commented
:pushpin: Commit 6c5cb9c has been approved by `jdm`

<!-- @bors-servo r=jdm 6c5cb9c369254f154e367e419a431995d286326c -->

2016-11-13 20:16 UTC, bors-servo commented
:hourglass: Testing commit 6c5cb9c with merge bfd4a0e...

2016-11-13 21:12 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4061), [arm64](http://build.servo.org/builders/arm64/builds/4068), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4162), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/807), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/805), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4145), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4142), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/829), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/840), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2077)

2016-11-13 21:12 UTC, merged