Use Selenium for Gecko performance test
servo/servo pull request #14194
Opened 2016-11-14 03:43 UTC by shinglyu

We run the `etc/ci/performance` test on Gecko for comparison, but the old add-on approach doesn't work anymore. I'm using selenium to drive Gecko instead. Also did some refactoring and fixed some nits I saw along the way.

r? @aneeshusa 
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #14148  (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-11-14 03:43 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @aneeshusa: etc/ci/performance/test_runner.py, etc/ci/performance/gecko_driver.py, etc/ci/performance/README.md, etc/ci/performance/test_all.sh, etc/ci/performance/runner.py

2016-11-14 08:41 UTC, Wafflespeanut commented on etc/ci/performance/README.md
> +* Run `python gecko_driver.py` to test
I'm curious. Do we really need geckodriver for selenium to work with firefox? I'm sure we need chromedriver for chrome, but I thought selenium supported firefox without the driver.

2016-11-14 14:06 UTC, jgraham commented
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[etc/ci/performance/gecko_driver.py, line 55 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWXd06JLl9600-PjQ-m:-KWXd06K8fRd2Tu4SiB6:b85q91n) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/gecko_driver.py#L55)):*
> ```Python
>     #     timings = driver.execute_script("return performance.timing")
>     # But for some test case the webdriver will fail with "too much recursion"
>     # So we need to get the timing fields one by one
> ```

I wonder what happens if you JSON serialise `performance.timing` and return that?

But even if you don't you could easily pass in the list of properties to the script and do the loop in js, returning a single object with everything you need.d

---

*[etc/ci/performance/gecko_driver.py, line 68 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWXdTRyQqYadpZq2gbq:-KWXdTRyQqYadpZq2gbr:b-ab8ytt) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/gecko_driver.py#L68)):*
> ```Python
> 
>     timings['testcase'] = testcase
>     # driver.quit() gives an "'NoneType' object has no attribute 'path'" error.
> ```

I'm not really clear if this comment is still relevant or not?

---

*[etc/ci/performance/README.md, line 67 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWXcNkj6_TrIipNl8aL:-KWXcNkj6_TrIipNl8aM:b-rmynlh) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/README.md#L67)):*
> ```Markdown
> 
> * Install Firefox Nightly in your PATH
> * Download [geckodrive](https://github.com/mozilla/geckodriver/releases) and add it to the `PATH`
> ```

s/geckodrive/geckodriver/

---

*[etc/ci/performance/runner.py, line 108 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWY83eG-2huhQWTjnee:-KWY83eHC6cSKFHhf9oi:bh92j5d) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/runner.py#L108)):*
> ```Python
>     def valid_timing(timing, testcase=None):
>         if (timing is None or
>                 testcase is None or
> ```

Weird indentation

---

*[etc/ci/performance/runner.py, line 147 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWY8L0FYaiq0pcYmQFQ:-KWY8L0FYaiq0pcYmQFR:b-ca6c06) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/runner.py#L147)):*
> ```Python
> 
>     valid_timing_for_case = partial(valid_timing, testcase=testcase)
>     timings = list(filter(valid_timing_for_case, map(parse_block, blocks)))
> ```

FWIW I would totally just have written

    timings = [item for item in [parse_block(block) for block in blocks]
               if valid_timing(item, testcase=testcase)]

But your way works too.

---

*[etc/ci/performance/test_all.sh, line 20 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWY9AI7Nd85992_ByaO:-KWY9AI8cz2UBfgUNYT5:bi04b2h) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/test_all.sh#L20)):*
> ```Shell
>   --gecko)
>     engine="--engine=gecko"
>     timeout=15
> ```

Why different timeouts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/14194)*
<!-- Sent from Reviewable.io -->

2016-11-15 06:31 UTC, aneeshusa requested changes
This seems much nicer to me (since it's automatable unlike Firefox add-on installation).
Maybe we ought to have a performance-related-things virtualenv (for treeherder, selenium, etc.)?

I believe the entire `etc/ci/performance/firefox` directory is unneeded now.

Also, a question since I haven't kept up with this area: it looks like we're testing Firefox with WebDriver (via Selenium) - in the future, would it be feasible/a good idea to do the same for Servo?

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/test_all.sh
> +python3 runner.py ${engine} --runs 3 --timeout "${timeout}"\
nit: space before the `\` at the end of the line

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/gecko_driver.py
> +    firefox_binary = "./firefox/firefox/firefox"
Shouldn't this look in the `$PATH`?

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/gecko_driver.py
> +            if name == "navigationStart":
This if/else can probably be boiled down to a one line ternary; a comment about the 0  / -1 distinction might also be nice (although I feel like I saw an explanation somewhere else...).

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/gecko_driver.py
> +    timings['testcase'] = testcase
Looks to be superfluous.

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/gecko_driver.py
> +    return [timings]
Any reason to wrap the return value in a list?

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/gecko_driver.py
> +    driver.quit()
An explicit `driver.quit()` worries me. Please wrap this into a context manager.

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/runner.py
> +                                       timeout=timeout)
Prefer block indent:
```
    return subprocess.check_output(
        command, stderr=subprocess.STDOUT, timeout=timeout
    )
````

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/runner.py
> -    # able to identify failed tests (successful tests have time >=0).
Here's that explanatory comment I was thinking of above, please migrate it :)

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/runner.py
> +                # results will be a mixure of timeings dict and testcase strings
spelling: timeings -> timings

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/runner.py
> +            run_test = command_factory(testcase)
Since we pass `testcase` down below to `run_test`, no need to pass it here. (Can probably also get rid of a layer of indirection/function calls.)

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/runner.py
> +    return gecko_driver.execute_gecko_test
Call it `run_gecko_test` for consistency with `run_servo_test`.

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/runner.py
> +        command = ["../../../target/release/servo", url,
style nit: have opening and closing brace alone:
```
command = [
    "../../../target/release/servo", url,
    ...
    "-o", "output.png"
]
```

2016-11-15 06:31 UTC, aneeshusa commented on etc/ci/performance/runner.py
> +            log = subprocess.check_output(command,
Same comment about block indent.

2016-11-16 08:56 UTC, shinglyu commented
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[etc/ci/performance/gecko_driver.py, line 68 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWXdTRyQqYadpZq2gbq:-KWgJAe750B6NL4C4xVo:br2s9f5) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/gecko_driver.py#L68)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I'm not really clear if this comment is still relevant or not?
</details>
It's still valid for Selenium 3.0.1 (install by pip 9.0.1/python3.4.3), so I'm keeping it here

---

*[etc/ci/performance/gecko_driver.py, line 72 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWVvp0KJZCLPs-0fBNV-r1-72:-KWgJZAlciNNcGK9jeeg:b-1wgihx) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/gecko_driver.py#L72)):*
<details><summary><i>Previously, aneeshusa (Aneesh Agrawal) wrote…</i></summary>
> Any reason to wrap the return value in a list?
</details>
Because servo's test may return a list of timings, (e.g. for nested iframe, there will be a timing for each iframe). The caller is responsible for filtering the results. I'm returning a list to maintain a consistent API for servo's and gecko's test method 

---

*[etc/ci/performance/runner.py, line 108 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWY83eG-2huhQWTjnee:-KWgKEQkxxvFkL5nOCaI:bm3ypsa) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/runner.py#L108)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Weird indentation
</details>
I'm trying to avoid PEP8 errors. ([reference](http://stackoverflow.com/questions/181530/python-style-multiple-line-conditions-in-ifs)) What do you suggest?

---

*[etc/ci/performance/test_all.sh, line 20 at r1](https://reviewable.io:443/reviews/servo/servo/14194#-KWY9AI7Nd85992_ByaO:-KWgKYq6XigW75Yo_Rkq:b-czboja) ([raw file](https://github.com/servo/servo/blob/611001756956124d9fdd7fbd312a1c4adc7d0f19/etc/ci/performance/test_all.sh#L20)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Why different timeouts?
</details>
Gecko is much more stable than Servo right now, so if it doesn't load in 15 seconds, it probably hangs, so we kill it to speed up the test. Servo might need longer so we give it more time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/14194)*
<!-- Sent from Reviewable.io -->

2016-11-16 09:54 UTC, shinglyu commented on etc/ci/performance/gecko_driver.py
> +    return [timings]
(see the comment in Reviewable)

2016-11-16 09:55 UTC, shinglyu commented
@aneeshusa @jgraham I refactor the `gecko_driver.py` to use resource manager and make the workflow more clear. Also left some comments in Reviewable. Thanks.

2016-11-28 09:06 UTC, shinglyu commented
@aneeshusa @jgraham  Since there is no major issue, and I need to land this ASAP, I'll ask @larsbergstrom for the final sign-off. Hope you don't mind!

2016-11-29 03:00 UTC, larsbergstrom commented
So far as I can tell, all issues have been addressed here.

@bors-servo r=larsbergstrom,aneeshusa,jgraham

2016-11-29 03:00 UTC, bors-servo commented
:pushpin: Commit ecfabb6 has been approved by `larsbergstrom,aneeshusa,jgraham`

<!-- @bors-servo r=larsbergstrom,aneeshusa,jgraham ecfabb6e9f6f0c128a911021ee039bfdd4d9ebbf -->

2016-11-29 04:22 UTC, bors-servo commented
:hourglass: Testing commit ecfabb6 with merge 69f914b...

2016-11-29 05:21 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4427), [arm64](http://build.servo.org/builders/arm64/builds/4435), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4518), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1189), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1199), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4494), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4512), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1205), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1213), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2459)

2016-11-29 05:21 UTC, merged