BluetoothUUID wpt tests
servo/servo pull request #14207
Opened 2016-11-14 14:55 UTC by zakorgy

Wpt tests for the `BluetoothUUID` functions.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/servo/14207)

2016-11-14 14:55 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.

2016-11-14 14:55 UTC, zakorgy commented
r? @jdm

2016-11-14 17:15 UTC, jdm requested changes
Looks good apart from one comment!

2016-11-14 17:15 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/bluetooth/idl-BluetoothUUID.html
> +}, '0x0 should produce valid UUID.');
This description doesn't match what's being tested.

2016-11-15 09:23 UTC, zakorgy commented
I changed the description in the first test function, also moved the used variables in the test file, because these are only used in this test.

2016-11-15 12:52 UTC, jdm commented
Even better!
@bors-servo: r+

2016-11-15 12:52 UTC, bors-servo commented
:pushpin: Commit c333aef has been approved by `jdm`

<!-- @bors-servo r=jdm c333aef6037751b1f54c569d5beb7abca4cfa8a0 -->

2016-11-16 15:21 UTC, Ms2ger commented
@bors-servo p=-2

2016-11-17 12:52 UTC, bors-servo commented
:hourglass: Testing commit c333aef with merge 8708410...

2016-11-17 13:54 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4160), [arm64](http://build.servo.org/builders/arm64/builds/4167), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4255), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/912), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/904), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4238), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4239), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/926), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/939), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2186)

2016-11-17 13:54 UTC, merged