Remove the dependency of fetch on filemanager_thread::UIProvider.
servo/servo pull request #14275
Opened 2016-11-18 12:10 UTC by Ms2ger

2016-11-18 12:10 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net/filemanager_thread.rs, components/net/fetch/methods.rs, components/net/resource_thread.rs, components/net/blob_loader.rs

2016-11-18 12:10 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2016-11-18 12:26 UTC, Ms2ger commented
Fails unit tests, hold on.

2016-11-18 12:33 UTC, Ms2ger commented
Fixed.

2016-11-21 14:24 UTC, jdm requested changes

2016-11-21 14:24 UTC, jdm commented on components/net/filemanager_thread.rs
> +#[derive(Clone)]
Is this necessary?

2016-11-21 14:26 UTC, jdm commented
@bors-servo: r+

2016-11-21 14:26 UTC, bors-servo commented
:pushpin: Commit ae1340b has been approved by `jdm`

<!-- @bors-servo r=jdm ae1340bf506eeef71c026e3da10b010eca59d379 -->

2016-11-21 14:26 UTC, jdm approved these changes

2016-11-22 00:28 UTC, bors-servo commented
:hourglass: Testing commit ae1340b with merge d287f58...

2016-11-22 01:33 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4274), [arm64](http://build.servo.org/builders/arm64/builds/4282), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4366), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1033), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1033), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4349), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4357), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1051), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1055), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2303)

2016-11-22 01:34 UTC, merged