serviceData and manufacturerData support
servo/servo pull request #14277
Opened 2016-11-18 16:26 UTC by zakorgy

Allow requesting for BluetoothDevices with service and manufacturer specific data.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes

2016-11-18 16:26 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/bluetooth.rs, components/script/dom/webidls/Bluetooth.webidl
 * @kichjang: components/script/dom/bluetooth.rs, components/script/dom/webidls/Bluetooth.webidl

2016-11-18 16:26 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.

2016-11-18 16:27 UTC, zakorgy commented
r? @jdm

2016-11-22 13:00 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14206) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-22 15:40 UTC, jdm requested changes

2016-11-22 15:40 UTC, jdm commented on components/script/dom/bluetooth.rs
> +    let data_prefix = match bdfi.dataPrefix {
`let data_prefix = bdfi.dataPrefix.cloned().unwrap_or(vec![]);`

2016-11-22 15:40 UTC, jdm commented on components/script/dom/bluetooth.rs
> +            for (key, bdfi) in manufacturer_data_map.deref() {
Can't this be `for (key, bdfi) in &manufacturer_data_map {`?

2016-11-22 15:40 UTC, jdm commented on components/script/dom/bluetooth.rs
> +            if service_data_map.deref().is_empty() {
No need for deref.

2016-11-22 15:40 UTC, jdm commented on components/script/dom/bluetooth.rs
> +            for (key, bdfi) in service_data_map.deref() {
`for (key, bdfi) in &service_data_map {`

2016-11-22 15:40 UTC, jdm commented on components/bluetooth_traits/scanfilter.rs
> +    pub fn get_manufacturer_data(&self) -> &Option<ManufacturerData> {
`-> Option<&ManufacturerData>`

2016-11-22 15:40 UTC, jdm commented on components/bluetooth_traits/scanfilter.rs
> +        &self.manufacturer_data
`self.manufacturer_data.as_ref()`

2016-11-22 15:40 UTC, jdm commented on components/bluetooth_traits/scanfilter.rs
> +        &self.service_data
`self.service_data.as_ref()`, and change the return type.

2016-11-22 15:40 UTC, jdm commented on components/bluetooth/lib.rs
> +    for i in 0..mask.len() {
```rust
for ((data, mask), prefix) in data.iter().zip(mask.iter()).zip(prefix.iter()) {
    if data & mask != prefix & mask {
        return false;
    }
}
```

2016-11-22 15:40 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/bluetooth/requestDevice/canonicalizeFilter/wrong-service-data-key.html
> +}, 'Rejects with SyntaxError, if a serviceData key not converts to a valid uuid.');
`if a serviceData key does not convert to a valid uuid`.

2016-11-22 15:40 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/bluetooth/requestDevice/device-not-found-with-service-and-manufacturer-data.html
> +}, 'Requesting with manufacturerData and serviceData in the same filter, will not find a device which does not advertises both.');
`does not advertise`

2016-11-22 23:09 UTC, dati91 commented on components/script/dom/bluetooth.rs
> +    let data_prefix = match bdfi.dataPrefix {
Note: I changed this to `clone` not `cloned`. I'm not sure why was the `ref` used here.

2016-11-23 00:06 UTC, jdm commented
Looks good! Go ahead and squash the commits, then this can be merged.
@bors-servo: delegate+

2016-11-23 00:06 UTC, bors-servo commented
:v: @zakorgy can now approve this pull request

2016-11-23 06:34 UTC, zakorgy commented
@bors-servo r+

2016-11-23 06:34 UTC, bors-servo commented
:pushpin: Commit 3547530 has been approved by `zakorgy`

<!-- @bors-servo r=zakorgy 354753063821a33246720397f1afec3f580c66d1 -->

2016-11-23 06:34 UTC, bors-servo commented
:hourglass: Testing commit 3547530 with merge d11703b...

2016-11-23 07:12 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1068)

2016-11-23 07:17 UTC, zakorgy commented
@bors-servo retry #14317

2016-11-23 07:24 UTC, bors-servo commented
:hourglass: Trying commit 3547530 with merge 21a1e1c...

2016-11-23 08:06 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1089)

2016-11-23 08:17 UTC, KiChjang commented
@bors-servo retry
* #14338

2016-11-23 08:17 UTC, bors-servo commented
:hourglass: Trying commit 3547530 with merge 4770de2...

2016-11-23 08:18 UTC, KiChjang commented
@bors-servo try- clean

2016-11-23 08:18 UTC, KiChjang commented
@bors-servo r=jdm

2016-11-23 08:18 UTC, bors-servo commented
:bulb: This pull request was already approved, no need to approve it again.

- This pull request is currently being tested. If there's no response from the continuous integration service, you may use `retry` to trigger a build again.

2016-11-23 08:18 UTC, bors-servo commented
:pushpin: Commit 3547530 has been approved by `jdm`

<!-- @bors-servo r=jdm 354753063821a33246720397f1afec3f580c66d1 -->

2016-11-23 09:25 UTC, KiChjang commented
@bors-servo r=jdm

2016-11-23 09:25 UTC, bors-servo commented
:pushpin: Commit 1b1b07e has been approved by `jdm`

<!-- @bors-servo r=jdm 1b1b07ef420f440f8d3390dc5a8d74a2ab680648 -->

2016-11-23 09:25 UTC, bors-servo commented
:hourglass: Testing commit 1b1b07e with merge 5946f75...

2016-11-23 11:22 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4312), [arm64](http://build.servo.org/builders/arm64/builds/4320), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4403), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1072), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1073), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4386), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4394), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1090), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1093), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2341)

2016-11-23 11:22 UTC, merged