Update to webrender 0.10.0
servo/servo pull request #14286
Opened 2016-11-19 15:12 UTC by gterzian

Changes necessary to build servor with webrender 0.10.0

WIP as of now...
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-11-19 15:12 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/Cargo.toml
 * @fitzgen: components/script/Cargo.toml, components/script_traits/Cargo.toml, components/script_traits/Cargo.toml
 * @kichjang: components/script/Cargo.toml, components/script_traits/Cargo.toml, components/script_traits/Cargo.toml, components/net/image_cache_thread.rs

2016-11-19 15:12 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net and script code, but no tests are modified. Please consider adding a test!

2016-11-19 15:14 UTC, gterzian commented
This is a WIP, I didn't see another PR doing the same work, please do let me know if there is one or if anyone is aleady working on this. I am doing this because I wanted to be able to build with `webrender:0.10.0` in order to do some last checks for https://github.com/servo/webrender/pull/533

2016-11-19 15:16 UTC, emilio requested changes

2016-11-19 15:16 UTC, emilio commented on ports/servo/Cargo.toml
> +[replace]
huh, remove this?

2016-11-19 15:16 UTC, emilio commented
I don't know if shaders need to be updated, if not and tests pass, looks good.

2016-11-19 15:17 UTC, gterzian commented
@emilio thanks for looking at this, it's still not building locally, I'm in the process of updating `script/dom/webgltexture` to use the latest `webrender_traits::channel::MsgSender`...

2016-11-19 15:18 UTC, gterzian commented on ports/servo/Cargo.toml
> +"webrender_traits:0.10.0" = { path = '/Users/gregory/Projects/webrender/webrender_traits' }
sorry this one slipped in, I'll make sure to remove it...

2016-11-19 15:23 UTC, gterzian commented on ports/servo/Cargo.toml
> +[replace]
yep :+1:

2016-11-20 02:24 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14284) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-20 03:59 UTC, gterzian commented
@emilio in the squash, should I separate the 'update dependencies' and 'update code' stuff, or just put it all in one 'update to webrender 0.10.0' commit?

2016-11-20 04:06 UTC, gterzian commented on ports/servo/Cargo.toml
> +[replace]
this has been done

2016-11-20 07:10 UTC, gterzian commented
Any ideas on the windows build failure?

```

error[E0308]: mismatched types
  --> C:\projects\servo\components\gfx\platform\windows\font_template.rs:48:14
   |
48 |         Some(descriptor)
   |              ^^^^^^^^^^ expected struct `dwrote::FontDescriptor`, found a different struct `dwrote::FontDescriptor`
   |
   = note: expected type `dwrote::FontDescriptor` (struct `dwrote::FontDescriptor`)
   = note:    found type `dwrote::FontDescriptor` (struct `dwrote::FontDescriptor`)
note: Perhaps two different versions of crate `dwrote` are being used?
  --> C:\projects\servo\components\gfx\platform\windows\font_template.rs:48:14
   |

```

2016-11-20 13:20 UTC, emilio commented
Yep, that's a duplicated dependency version, you need to update both of 
them.

On Sat, Nov 19, 2016 at 11:10:24PM -0800, Gregory Terzian wrote:
> Any ideas on the windows build failure?
> 
> ```
> 
> error[E0308]: mismatched types
>   --> C:\projects\servo\components\gfx\platform\windows\font_template.rs:48:14
>    |
> 48 |         Some(descriptor)
>    |              ^^^^^^^^^^ expected struct `dwrote::FontDescriptor`, found a different struct `dwrote::FontDescriptor`
>    |
>    = note: expected type `dwrote::FontDescriptor` (struct `dwrote::FontDescriptor`)
>    = note:    found type `dwrote::FontDescriptor` (struct `dwrote::FontDescriptor`)
> note: Perhaps two different versions of crate `dwrote` are being used?
>   --> C:\projects\servo\components\gfx\platform\windows\font_template.rs:48:14
>    |
> 
> ```
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/servo/servo/pull/14286#issuecomment-261762983

2016-11-20 14:26 UTC, gterzian commented
@emilio thanks! Could you please elaborate on how to update them? FYI thy are both at the up to date version, but one is pointing to Github, while the other points to cargo...

2016-11-20 14:30 UTC, jdm commented
Sounds like we should change the one that's pointing at git to use cargo instead.

2016-11-20 15:27 UTC, gterzian commented
Also, from manual testing I was getting just a flickering black screen previously, will test again tomorrow, wondering if perhaps more changes are required then the minimum needed to successfully compile...

2016-11-20 23:54 UTC, glennw commented
@gterzian Thanks for working on this! I've pushed 3 new commits to your PR branch. The first one updates the display list generation for scroll API changes. The 2nd one enables the IPC feature of WR, and switches dwrote to the crates.io version. The 3rd commit removes all the old shaders that are now embedded by default.

With these changes, it's running locally on my machine fine (in both the WPT tests and some manual website tests).

2016-11-20 23:55 UTC, glennw commented
@bors-servo try

2016-11-20 23:55 UTC, bors-servo commented
:hourglass: Trying commit 702655f with merge 5657962...

2016-11-21 01:01 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/4340)

2016-11-21 01:16 UTC, glennw commented
@bors-servo try

2016-11-21 01:16 UTC, bors-servo commented
:hourglass: Trying commit a98fee0 with merge e4be389...

2016-11-21 02:40 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1028)

2016-11-21 02:54 UTC, glennw commented
@bors-servo retry
 * Seeing which are repeatable, as none of these timeouts are reproducible locally.

2016-11-21 02:54 UTC, bors-servo commented
:hourglass: Trying commit a98fee0 with merge bfb8372...

2016-11-21 03:50 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1030)

2016-11-21 03:53 UTC, glennw commented
These new timeouts seem permanent, but I can't reproduce them locally (I'm fairly confident they are unrelated to the WR update, but I'll see if I can repro on the build machines).

2016-11-21 04:34 UTC, glennw commented
@bors-servo try

2016-11-21 04:34 UTC, bors-servo commented
:hourglass: Trying commit deefe18 with merge 7584253...

2016-11-21 05:53 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1033)

2016-11-21 05:57 UTC, glennw commented
@bors-servo try

2016-11-21 05:57 UTC, bors-servo commented
:hourglass: Trying commit 850ce08 with merge d91f482...

2016-11-21 07:38 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1012)

2016-11-21 07:50 UTC, glennw commented
@bors-servo retry
 * #14215
 * #14217

2016-11-21 07:50 UTC, bors-servo commented
:hourglass: Trying commit 850ce08 with merge 41260ee...

2016-11-21 10:29 UTC, gterzian commented
@glennw thanks for your help!

2016-11-21 18:25 UTC, bors-servo commented
:boom: Test timed out

2016-11-21 18:37 UTC, glennw commented
@bors-servo retry
* Infra?

2016-11-21 18:37 UTC, bors-servo commented
:hourglass: Trying commit 850ce08 with merge c174068...

2016-11-21 19:55 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1027)

2016-11-21 20:15 UTC, glennw commented
The commits by @gterzian look fine to me. r? anyone else on my commits added to this PR?

I expect this will still have some new intermittent failures (which are not locally reproducible for me). I'm fairly confident they aren't related to this PR at all, but I'll do some investigating today on the build machines. It should still be fine to review now though.

2016-11-21 21:12 UTC, emilio commented
@bors-servo r=emilio,glennw

2016-11-21 21:12 UTC, bors-servo commented
:pushpin: Commit 850ce08 has been approved by `emilio,glennw`

<!-- @bors-servo r=emilio,glennw 850ce085c5dbf558dc623d5503b0419b76b5670d -->

2016-11-21 22:02 UTC, glennw commented
@bors-servo r=emilio,glennw

2016-11-21 22:02 UTC, bors-servo commented
:pushpin: Commit 341977e has been approved by `emilio,glennw`

<!-- @bors-servo r=emilio,glennw 341977e14ebd73587286d68801ff3ec61f7e2f37 -->

2016-11-22 02:34 UTC, bors-servo commented
:hourglass: Testing commit 341977e with merge a49490b...

2016-11-22 03:27 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1053)

2016-11-22 04:11 UTC, glennw commented
@bors-servo retry
 * https://github.com/servo/servo/issues/12797

2016-11-22 04:19 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/4276), [arm64](http://build.servo.org/builders/arm64/builds/4284), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4368), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4351), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4359), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1057), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2305) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1035), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1035), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1053)...

2016-11-22 05:00 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1037)

2016-11-22 05:07 UTC, glennw commented
@bors-servo retry
 * #12797
 * #14267

2016-11-22 06:02 UTC, bors-servo commented
:hourglass: Testing commit 341977e with merge b216292...

2016-11-22 06:48 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1057)

2016-11-22 06:48 UTC, highfive commented
▶ TIMEOUT [expected OK] /html/browsers/browsing-the-web/navigating-across-documents/javascript-url-return-value-handling.html
      │ 
      │ VMware, Inc.
      │ Gallium 0.4 on softpipe
      └ 3.3 (Core Profile) Mesa 12.0.1
    
      ▶ Unexpected subtest result in /html/browsers/browsing-the-web/navigating-across-documents/javascript-url-return-value-handling.html:
      └ NOTRUN [expected FAIL] Test that javascript: evaluation only performs a navigation to the\n  result when the result is a string value.
    
      ▶ TIMEOUT [expected OK] /html/dom/documents/dom-tree-accessors/nameditem-02.html
      │ 
      │ VMware, Inc.
      │ Gallium 0.4 on softpipe
      └ 3.3 (Core Profile) Mesa 12.0.1

2016-11-22 06:56 UTC, glennw commented
@bors-servo retry
 * #12797 
 * #13555

2016-11-22 07:46 UTC, bors-servo commented
:zap: Previous build results for [arm32](http://build.servo.org/builders/arm32/builds/4279), [arm64](http://build.servo.org/builders/arm64/builds/4287), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4371), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4354), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4362), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1060), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2308) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1039), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1039), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1057)...

2016-11-22 08:23 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1041)

2016-11-22 13:52 UTC, jdm commented
@bors-servo: retry
* #12797 #14319

2016-11-22 14:37 UTC, bors-servo commented
:hourglass: Testing commit 341977e with merge 39ed083...

2016-11-22 15:57 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1050)

2016-11-22 16:09 UTC, jdm commented
I'm really not sure what to do here. This WR update is clearly stressing the build machines in ways that other PRs do not currently, which is causing havoc in a bunch of tests that appear to be timing-dependent.

2016-11-22 18:49 UTC, glennw commented
@jdm Yea, I'm similarly unsure what to do here. This PR will definitely change timing dependent things (e.g. shaders are now embedded in binary and not loaded from disk), but I'm fairly confident all the intermittents that it triggers are not an issue with this PR itself, but exposing other bugs :( I'm going to just spend all of today trying to track down the root cause of some of these intermittents. Perhaps there's only 1-2 things causing most of these to trigger.

2016-11-23 01:57 UTC, glennw commented
@bors-servo try

2016-11-23 01:57 UTC, bors-servo commented
:hourglass: Trying commit dbd6c18 with merge e180754...

2016-11-23 03:25 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1082)

2016-11-23 03:28 UTC, glennw commented
@bors-servo retry
 * #13776

2016-11-23 03:28 UTC, bors-servo commented
:hourglass: Trying commit dbd6c18 with merge d369246...

2016-11-23 04:14 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1065)

2016-11-23 05:19 UTC, glennw commented
@bors-servo try

2016-11-23 05:19 UTC, bors-servo commented
:hourglass: Trying commit be17989 with merge f5713ea...

2016-11-23 06:20 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1067)

2016-11-24 18:59 UTC, kvark commented
@gterzian heads up! https://github.com/servo/webrender/pull/591 has supposedly fixed the intermittent issues with the bots. So if you update the PR to the latest WR, it has a chance of passing through.

2016-11-24 19:20 UTC, glennw commented
@bors-servo try

2016-11-24 19:20 UTC, bors-servo commented
:hourglass: Trying commit 3e7f093 with merge 1b9e6d2...

2016-11-24 20:21 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4353), [arm64](http://build.servo.org/builders/arm64/builds/4361), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4444), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1112), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1118), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4422), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4435), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1129), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1135), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2385)

2016-11-24 20:29 UTC, jdm commented
@bors-servo: r+

2016-11-24 20:29 UTC, bors-servo commented
:pushpin: Commit 3d67c1c has been approved by `jdm`

<!-- @bors-servo r=jdm 3d67c1cf4cb5c7a3188fbd19f872c2d06fecacc4 -->

2016-11-24 20:29 UTC, bors-servo commented
:hourglass: Testing commit 3d67c1c with merge e1eff69...

2016-11-24 21:35 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4354), [arm64](http://build.servo.org/builders/arm64/builds/4362), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4445), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1113), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1119), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4423), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4436), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1130), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1136), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2386)

2016-11-24 21:35 UTC, merged