Use unguessable PipelineIds and FrameIds
servo/servo pull request #14283
Opened 2016-11-18 22:20 UTC by ConnorGBrewster

Blocked on webrender update and servo/webrender#578

r? @asajeffrey 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #10542 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because refactoring

2016-11-18 22:20 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/pipeline.rs, components/constellation/constellation.rs
 * @kichjang: components/script_traits/lib.rs, components/script_traits/lib.rs, components/script/script_thread.rs, components/net/image_cache_thread.rs
 * @fitzgen: components/script_traits/lib.rs, components/script_traits/lib.rs, components/script/script_thread.rs
 * @emilio: components/layout/webrender_helpers.rs

2016-11-18 22:20 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net, layout, and script code, but no tests are modified. Please consider adding a test!

2016-11-20 14:06 UTC, nox commented on components/msg/constellation_msg.rs
> +            id: Uuid::new_v4(),
This means we will yet again require the RNG and open `/dev/random`. Will it be a problem here? Can we do otherwise? Cc @larsbergstrom.

2016-11-21 23:22 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14173) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-22 15:50 UTC, asajeffrey commented on components/msg/constellation_msg.rs
> +            id: Uuid::new_v4(),
Ouch. Can we have a `lazy_static` RNG that we use just to create RNGs? That way we'd only be opening `dev/random` once per process.

2016-12-13 15:56 UTC, asajeffrey commented
Once #14351 lands, we can use an RNG without using an fd.

2017-01-10 12:54 UTC, asajeffrey commented
#14351 has landed, so we can now use uuids.

2017-01-10 20:10 UTC, cbrewster commented
rebased. once this is reviewed we can merge servo/webrender#578

2017-01-10 20:30 UTC, asajeffrey requested changes
A big improvement! There are still a couple of places that the Rust default RNG is being used though.

2017-01-10 20:30 UTC, asajeffrey commented on components/msg/constellation_msg.rs
> +    #[ignore_heap_size_of = "no heapsize for uuid"]
It would be nice if we could get a heap size for uuid.

2017-01-10 20:30 UTC, asajeffrey commented on components/msg/constellation_msg.rs
> +            id: Uuid::new_v4(),
Doesn't this use the Rust default RNG rather than Servo's RNG?

2017-01-10 20:30 UTC, asajeffrey commented on components/msg/constellation_msg.rs
> +            id: Uuid::new_v4(),
Rust RNG?

2017-01-11 00:50 UTC, cbrewster commented on components/msg/constellation_msg.rs
> +            id: Uuid::new_v4(),
woops! fixed.

2017-01-20 16:39 UTC, asajeffrey commented on components/msg/Cargo.toml
> +uuid = { version = "0.3.1", features = ["v4", "serde"] }
Can we use `uuid = { version = "0.3.1", default-features = false, features = ["serde"] }` to make sure we're not using `rand`?

2017-01-20 16:41 UTC, asajeffrey commented on components/msg/constellation_msg.rs
> +            id: Uuid::rand(&mut rng),
Nit: might be easier to read as `servo_rand::thread_rng()::gen()`?

2017-01-20 16:42 UTC, asajeffrey commented on components/msg/constellation_msg.rs
> +            id: Uuid::rand(&mut rng),
Ditto.

2017-01-23 12:11 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15136) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-26 07:38 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15216) made this pull request unmergeable. Please resolve the merge conflicts.

2017-02-20 03:17 UTC, closed without merging