Annotations for WebBluetooth functions
servo/servo pull request #14407
Opened 2016-11-29 13:27 UTC by zakorgy

1. Moved the `convert_request_device_options` function steps into `request_bluetooth_devices` function., to stay consistent with the current specification.
2. Updated the existing step annotations for the requestDevice and related methods.
3. Added step annotations for the implemented WebBluetooth methods.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix  #14324, #12614

2016-11-29 13:27 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/bluetoothremotegattserver.rs, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/bluetooth.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs, components/script/dom/bluetoothdevice.rs
 * @kichjang: components/script/dom/bluetoothremotegattserver.rs, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/bluetooth.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs, components/script/dom/bluetoothdevice.rs

2016-11-29 13:27 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-11-29 13:27 UTC, zakorgy commented
r? @jdm

2016-11-29 14:32 UTC, jdm requested changes
This is a great improvement! Thanks!

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +                // TODO: Step 5.1.4: Use the excahnge MTU procedure.
exchange

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +    // https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattserver-getprimaryservice
Shouldn't this be https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren or at least reference it?

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +        // Step 2.5.
These numbers don't correspond to step numbers in the spec, given the split between https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren and https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattserver-getprimaryservice .

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
>          }
We should be able to remove this special case entirely, since we return the same value if we finish looping through services.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
>          }
Same as before - we should be able to remove this.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +        // TODO: Step 7: If its argument is empty, throws a NotFoundError.
This can be removed in favour of the return statement that already exists.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +        // TODO: Step 7: If its argument is empty, throws a NotFoundError.
No need for this.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +    // https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattservice-getcharacteristic
We really need to link to https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren somewhere too.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +    // https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattservice-getincludedservices
We really need to link to https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren somewhere as well.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +    // https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattservice-getincludedservice
We really need to link to https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren somewhere too.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
>          }
This block is unnecessary.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
>          }
Unnecessary.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +    // https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattservice-getcharacteristics
Add a link to https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
>          }
Remove this.

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +    // https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattcharacteristic-getdescriptor
Add a link to https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren .

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
> +    // https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattcharacteristic-getdescriptors
Add a link to https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren .

2016-11-29 14:32 UTC, jdm commented on components/bluetooth/lib.rs
>          }
Remove this.

2016-11-29 15:06 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14393) made this pull request unmergeable. Please resolve the merge conflicts.

2016-11-29 16:48 UTC, dati91 commented
@jdm How should I number the steps? e.g. `Step 2.7` which is the 7. step in gattchildren, or `Step 7.` but then i need to resolve the numbering in the dom side somehow, because there will be 2 `Step 1`

I realize this thing is a bit unfortunate, but i could move up the gattchildren implementation in my todo list if you prefer :)

2016-11-29 16:51 UTC, jdm commented
@dati91 I would add a comment like `// Subsequent steps are relative to https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren`

2016-11-29 17:58 UTC, jdm commented
@bors-servo: delegate+
Squash the latest commits into a9237d6 and this can merge.

2016-11-29 17:58 UTC, bors-servo commented
:v: @zakorgy can now approve this pull request

2016-11-30 07:11 UTC, zakorgy commented
@bors-servo r=jdm

2016-11-30 07:11 UTC, bors-servo commented
:pushpin: Commit 8dd100f has been approved by `jdm`

<!-- @bors-servo r=jdm 8dd100f74fdabd55d5f3c179b3d5e52d2e0aa0e5 -->

2016-11-30 07:11 UTC, bors-servo commented
:hourglass: Testing commit 8dd100f with merge 1820bb5...

2016-11-30 07:49 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/4276)

2016-11-30 13:38 UTC, zakorgy commented
@bors-servo retry

2016-11-30 13:39 UTC, bors-servo commented
:hourglass: Trying commit 8dd100f with merge f2ca433...

2016-11-30 14:19 UTC, jdm commented
@zakorgy That's just https://github.com/servo/saltfs/issues/545. You should be able to retry like usual.

2016-11-30 15:09 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4458), [arm64](http://build.servo.org/builders/arm64/builds/4466), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4549), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1222), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1240), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4525), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4544), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1236), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1247), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2490)

2016-11-30 15:09 UTC, bors-servo commented
:hourglass: Testing commit 8dd100f with merge 9a902a7...

2016-11-30 15:59 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1225)

2016-11-30 18:32 UTC, KiChjang commented
@bors-servo retry
* #14425

2016-11-30 22:50 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1231)

2016-11-30 22:54 UTC, KiChjang commented
@bors-servo retry
* #14237

2016-12-01 00:37 UTC, bors-servo commented
:hourglass: Testing commit 8dd100f with merge 16199b4...

2016-12-01 01:31 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4468), [arm64](http://build.servo.org/builders/arm64/builds/4476), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4558), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1234), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1254), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4534), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4555), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1246), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1259), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2500)

2016-12-01 01:31 UTC, merged