Made http_redirect_fetch error for non-HTTPS. #14069
servo/servo pull request #14420
Opened 2016-11-30 05:47 UTC by 46bit

Hi! I'm a newbie looking to resolve #14069.

The [existing tests](https://dxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/fetch/api/redirect/redirect-schemes.html) now pass. 

* Should I add "http" and "https" tests that check for 200 status code? 
  * Are there convenient URLs for which I could assume 200?
* I found `NetworkError::SslValidation(ServoUrl, String)`. This isn't about Certificate Validation and I think the `NetworkError::Internal` variant is correct?

Cheers!

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14069 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-11-30 05:48 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @kichjang (or someone else) soon.

2016-11-30 05:48 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net/http_loader.rs

2016-11-30 06:07 UTC, KiChjang requested changes
Thanks for your PR! There are a couple of minor changes, r=me after they're fixed.

For the questions you posed, I don't think it's necessary to resolve them in this PR since they're out of scope. I'd also encourage you to comment on the relevant issue first before working on it next time.

2016-11-30 06:07 UTC, KiChjang commented on components/net/http_loader.rs
> +        "https" => { },
This can just be `"http" | "https" => { }`.

2016-11-30 06:07 UTC, KiChjang commented on components/net/http_loader.rs
> +        _ => return Response::network_error(NetworkError::Internal("Not an HTTPS Scheme".into()))
`"Not an HTTP(S) scheme"`.

2016-11-30 06:23 UTC, 46bit commented
r=KiChjang

2016-11-30 07:41 UTC, KiChjang commented
@46bit That message was intended for other reviewers indicating that this patch can be landed if I happen to be away for a while. Thanks for your contribution nonetheless!

@bors-servo r+

2016-11-30 07:41 UTC, bors-servo commented
:pushpin: Commit 3d43b97 has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 3d43b97ad534692a3abdae4d6368d0013c8aee2c -->

2016-11-30 07:55 UTC, bors-servo commented
:hourglass: Testing commit 3d43b97 with merge 06bd113...

2016-11-30 08:31 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/4278)

2016-11-30 12:39 UTC, Ms2ger commented
@bors-servo retry https://github.com/servo/saltfs/issues/545

2016-11-30 17:48 UTC, bors-servo commented
:hourglass: Testing commit 3d43b97 with merge acdbdfa...

2016-11-30 18:24 UTC, KiChjang approved these changes

2016-11-30 18:33 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1241)

2016-11-30 18:38 UTC, KiChjang commented
Looks like more tests are passing after your changes:
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl.html:
  └ PASS [expected FAIL] Testing data URL loading after same-origin redirection (cors mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl.html:
  └ PASS [expected FAIL] Testing data URL loading after same-origin redirection (no-cors mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl.html:
  └ PASS [expected FAIL] Testing data URL loading after same-origin redirection (same-origin mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl.html:
  └ PASS [expected FAIL] Testing data URL loading after cross-origin redirection (cors mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl.html:
  └ PASS [expected FAIL] Testing data URL loading after cross-origin redirection (no-cors mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl-worker.html:
  └ PASS [expected FAIL] Testing data URL loading after same-origin redirection (cors mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl-worker.html:
  └ PASS [expected FAIL] Testing data URL loading after same-origin redirection (no-cors mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl-worker.html:
  └ PASS [expected FAIL] Testing data URL loading after same-origin redirection (same-origin mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl-worker.html:
  └ PASS [expected FAIL] Testing data URL loading after cross-origin redirection (cors mode)

  ▶ Unexpected subtest result in /fetch/api/redirect/redirect-to-dataurl-worker.html:
  └ PASS [expected FAIL] Testing data URL loading after cross-origin redirection (no-cors mode)
```
You'll need to update the test expectations accordingly.

2016-11-30 20:50 UTC, 46bit commented
Aha. I've removed the outdated expectations and checked the full `./mach test-wpt tests/wpt/web-platform-tests/fetch`.

2016-11-30 20:54 UTC, KiChjang commented
Thanks!

@bors-servo r+

2016-11-30 20:54 UTC, bors-servo commented
:pushpin: Commit 52194c0 has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 52194c01d5fc77012bfe06a2c6383da65882196f -->

2016-12-01 06:45 UTC, bors-servo commented
:hourglass: Testing commit 52194c0 with merge b3745d6...

2016-12-01 07:36 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4475), [arm64](http://build.servo.org/builders/arm64/builds/4483), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4565), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1241), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1261), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4541), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4562), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1253), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1266), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2507)

2016-12-01 07:36 UTC, merged