Properly mark application/xhtml+xml documents as XML
servo/servo pull request #14423
Opened 2016-11-30 15:21 UTC by nox

2016-11-30 15:21 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/document.rs, components/script/dom/attr.rs, components/script/dom/htmlcollection.rs, components/script/dom/node.rs, components/script/dom/element.rs, components/script/Cargo.toml, components/script/dom/range.rs, components/script/dom/servoparser/mod.rs, components/script/dom/servoparser/xml.rs, components/script/dom/csskeyframesrule.rs, components/script/lib.rs, components/script/script_thread.rs
 * @kichjang: components/script/dom/document.rs, components/script/dom/attr.rs, components/script/dom/htmlcollection.rs, components/script/dom/node.rs, components/script/dom/element.rs, components/script/Cargo.toml, components/script/dom/range.rs, components/script/dom/servoparser/mod.rs, components/script/dom/servoparser/xml.rs, components/script/dom/csskeyframesrule.rs, components/script/lib.rs, components/script/script_thread.rs

2016-11-30 15:21 UTC, nox commented
@bors-servo try

2016-11-30 15:21 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-11-30 15:21 UTC, bors-servo commented
:hourglass: Trying commit 2add2de with merge 2d5858b...

2016-11-30 15:21 UTC, nox commented
r? @Ms2ger

2016-11-30 17:08 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1244)

2016-11-30 17:09 UTC, nox commented
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /dom/nodes/Document-getElementsByTagName-xhtml.xhtml:
  └ PASS [expected FAIL] HTML element with uppercase tag name matches in XHTML documents

  ▶ Unexpected subtest result in /dom/nodes/Document-getElementsByTagName-xhtml.xhtml:
  └ PASS [expected FAIL] Element in HTML namespace, no prefix, non-ascii characters in name

  ▶ Unexpected subtest result in /dom/nodes/Document-getElementsByTagName-xhtml.xhtml:
  └ PASS [expected FAIL] Element in HTML namespace, prefix, non-ascii characters in name

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement(undefined) in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement(null) in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f1oo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo1") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f\u0bc6") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo\u0bc6") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement(":foo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f:oo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo:") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f:o:o") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f::oo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f::oo:") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo:0") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo:_") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo:\u0bc6") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo:foo\u0bc6") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo\u0bc6:foo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("xml") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("xmlns") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("xmlfoo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("xml:foo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("xmlns:foo") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("xmlfoo:bar") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("svg") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("math") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("FOO") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("mar\u212a") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("\u0130nput") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("\u0131nput") in XHTML document

  ▶ Unexpected subtest result in /dom/nodes/Node-nodeName-xhtml.xhtml:
  └ PASS [expected FAIL] For Element nodes, nodeName should return the same as tagName.

  ▶ Unexpected subtest result in /html/dom/dynamic-markup-insertion/document-write/document.write-01.xhtml:
  └ PASS [expected FAIL] document.write in XHTML

  ▶ Unexpected subtest result in /html/dom/dynamic-markup-insertion/document-writeln/document.writeln-01.xhtml:
  └ PASS [expected FAIL] document.writeln in XHTML
```

2016-12-01 00:38 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14376) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-01 10:31 UTC, Ms2ger requested changes

2016-12-01 10:31 UTC, Ms2ger commented on components/script/dom/element.rs
> +            _ => Root::downcast::<Element>(context_node.GetParentNode().unwrap()).unwrap()
`GetParentElement().unwrap()`

2016-12-01 10:31 UTC, Ms2ger commented on components/script/dom/element.rs
> +                Root::upcast(HTMLBodyElement::new(local_name!("body"), None, &owner_doc))
No need for the `&`.

2016-12-01 10:31 UTC, Ms2ger commented on components/script/dom/node.rs
> +                    .unwrap_or(ns!())
`map_or()`?

2016-12-01 10:31 UTC, Ms2ger commented on components/script/dom/element.rs
> +            let attr = ref_filter_map(self.attrs(), |attrs| attrs.iter().find(|attr| {
Wrap the closure body in a block.

2016-12-01 10:31 UTC, Ms2ger commented on components/script/dom/node.rs
> +                    .map(|elem| elem.locate_namespace(prefix))
`map_or()`?

2016-12-01 10:31 UTC, Ms2ger commented on components/script/dom/element.rs
> +        // TODO: XML case.
Check if there is an issue; if not, file one. In either case, make this `FIXME(#NNNN): XML case.`

2016-12-01 10:31 UTC, Ms2ger commented on components/script/dom/document.rs
> +#[derive(Clone, Copy, HeapSizeOf, JSTraceable, PartialEq)]
Make it `Debug` while you're here.

2016-12-01 11:10 UTC, Ms2ger commented
@bors-servo r+

2016-12-01 11:10 UTC, bors-servo commented
:pushpin: Commit c1bdd3d has been approved by `Ms2ger`

<!-- @bors-servo r=Ms2ger c1bdd3d5ce0e971c7b3eec0dadcfaf7dd448e9a3 -->

2016-12-01 11:10 UTC, Ms2ger approved these changes

2016-12-01 11:57 UTC, bors-servo commented
:hourglass: Testing commit c1bdd3d with merge 5abbc9f...

2016-12-01 12:48 UTC, bors-servo commented
:sunny: Test successful - [arm32](http://build.servo.org/builders/arm32/builds/4481), [arm64](http://build.servo.org/builders/arm64/builds/4489), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4571), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1247), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1267), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4547), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4568), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1259), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1272), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2513)

2016-12-01 12:49 UTC, merged