layout: Dramatically improve performance of layout queries and `requestAnimationFrame()`.
servo/servo pull request #14442
Opened 2016-12-02 20:57 UTC by pcwalton

See individual commits for details. This improves nytimes.com CPU usage and gets it within the ballpark of Firefox.

r? @emilio

2016-12-02 20:57 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/document.rs, components/script/timers.rs, components/script_layout_interface/wrapper_traits.rs
 * @fitzgen: components/script/dom/document.rs, components/script/timers.rs, components/script_layout_interface/wrapper_traits.rs
 * @emilio: components/layout/construct.rs, components/layout/sequential.rs, components/layout/query.rs, components/layout/flow.rs

2016-12-02 20:57 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify layout and script code, but no tests are modified. Please consider adding a test!

2016-12-02 21:18 UTC, fitzgen commented
Regarding ba274c9: Is an RAF that performs canvas draws but no dom mutations considered "spurious"? Is that desirable?

2016-12-02 21:54 UTC, pcwalton commented
@fitzgen No, it shouldn't be considered spurious. Does it dirty the canvas? If not, I'm not sure what the best way to detect this is.

2016-12-02 21:59 UTC, pcwalton commented
The canvas element is dirtied when you draw to it, so there should be no problems here.

2016-12-03 01:08 UTC, emilio reviewed
r=me on the layout changes, they're great :)

I'm not sure we can fake animation frame callbacks using a timer per spec. IIRC we should run them at a very specific timing per [the processing model](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model), and we're already awful at it unfortunately.

I'd love to see this, and it may be the case that results are black-box identical in this case (though I think not because at least the last fake callback that modifies something and makes us go back to real animation frames runs out of sync).

I'd probably defer to @jdm or @Ms2ger to approve that bit, or request more proof of that being the case.

2016-12-03 01:09 UTC, emilio commented
@bors-servo try

2016-12-03 01:09 UTC, bors-servo commented
:hourglass: Trying commit 89895e3 with merge 6d97221...

2016-12-03 01:52 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1288)

2016-12-03 07:39 UTC, pcwalton commented
@emilio I don't see anything in that list that mandates *when* animation frame callbacks run, only that they run at specific times relative to other events. We already don't try to do that, I don't think. Indeed it'd be impossible for the spec to mandate a specific time other than describing what a VBLANK is (and if it did, then every other browser on non-Windows platforms would fail it because they don't sync to VBLANK properly).

(On a side note, it's irritating that the spec technically forbids off main thread CSS animations, but I'm going to just break the spec because that's dumb.)

2016-12-03 11:05 UTC, emilio commented
On Fri, Dec 02, 2016 at 11:39:39PM -0800, Patrick Walton wrote:
> We already don't try to do that, I don't think. Indeed it'd be
> impossible for the spec to mandate a specific time other than
> describing what a VBLANK is (and if it did, then every other browser
> on non-Windows platforms would fail it because they don't sync to
> VBLANK properly).

That's fair, that's why I lean towards merging this. But I think we
eventually should try to conform to it, given there are pages that rely
on it, and this will be more complexity to rewrite/remove when we want
to do it.

2016-12-07 03:28 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14473) made this pull request unmergeable. Please resolve the merge conflicts.

2017-02-02 15:27 UTC, jdm requested changes
This looks fine to me. Sorry that it was overlooked for so long!

2017-02-02 15:27 UTC, jdm commented on components/script/dom/document.rs
> +    #[allow(unrooted_must_root)]
This shouldn't be necessary.

2017-03-03 11:42 UTC, nox commented
@jdm Want me to carry this? @pcwalton is busy with his Pathfinder adventures AFAIK.

2017-03-03 18:19 UTC, jdm commented
That would be great!

2017-03-05 13:17 UTC, nox commented
I carried the first 2 commits in #15816. 👶👣

2017-03-12 11:02 UTC, nox commented
@pcwalton Are you sure the commit "query: Stop searching the entire flow tree to resolve script-to-layout" works as intended?

2017-03-15 10:41 UTC, nox commented
Lack of response, I'm closing this.

2017-03-15 10:41 UTC, closed without merging