Remove dependency of canvas_traits on azure
servo/servo pull request #14547
Opened 2016-12-10 18:17 UTC by Naruto8

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Signed-off-by: Rohith Mukku <rohithmukku@gmail.com>

2016-12-10 18:17 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @connorgbrewster (or someone else) soon.

2016-12-10 18:18 UTC, Naruto8 commented
This is my first time, if there are any mistakes or errors... help me rectify it! Thanks!

2016-12-10 18:33 UTC, KiChjang commented
What issue number is this trying to solve?

2016-12-10 18:36 UTC, KiChjang requested changes

2016-12-10 18:36 UTC, KiChjang commented on components/canvas/canvas_paint_thread.rs
> +    fn to_azure_pattern(&self, drawtarget: &DrawTarget) -> Self::Target {
Have you tried compiling your changes? This does not(look like it should compile.

2016-12-10 18:36 UTC, KiChjang commented on components/canvas/canvas_paint_thread.rs
> +	fn to_str(&self) -> &str {
This also does not look like it should compile.

2016-12-10 18:36 UTC, KiChjang commented on components/canvas/canvas_paint_thread.rs
> +	fn to_str(&self) -> &str {
Same here.

2016-12-19 09:14 UTC, KiChjang commented
@Naruto8 Are you still planning on working on this?

2016-12-21 21:18 UTC, KiChjang commented
Closing due to inactivity.

2016-12-21 21:18 UTC, closed without merging