Implement browsing context discarding
servo/servo pull request #14559
Opened 2016-12-12 22:16 UTC by asajeffrey

Implement browsing context discarding (https://html.spec.whatwg.org/multipage/browsers.html#discard-a-document).

* When a pipeline is closed, inform the script thread whether the browsing context is to be discarded.
* In script threads, synchronously discard any similar-origin documents and browsing contexts.
* When a browsing context is discarded, it loses the reference to the active document, but the window keeps it, so we need to move the `Document` pointer from `BrowsingContext` to `Window`.
* Fix the webIDL for Window to make parent and top optional (the spec says they can return null when the browsing context is discarded).

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14411 
- [X] There are tests for these changes

2016-12-12 22:16 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/dom/browsingcontext.rs, components/script_traits/script_msg.rs, components/script_traits/script_msg.rs, components/script/script_thread.rs, components/script/dom/window.rs, components/script/dom/webidls/Window.webidl, components/script_traits/lib.rs, components/script_traits/lib.rs
 * @kichjang: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/dom/browsingcontext.rs, components/script_traits/script_msg.rs, components/script_traits/script_msg.rs, components/script/script_thread.rs, components/script/dom/window.rs, components/script/dom/webidls/Window.webidl, components/script_traits/lib.rs, components/script_traits/lib.rs

2016-12-12 22:17 UTC, asajeffrey commented
This should help with the crash we were seeing in https://github.com/servo/servo/pull/13996#issuecomment-263386164 (though that crash has mysteriously disappeared). cc @Ms2ger @jdm

2016-12-12 22:19 UTC, asajeffrey commented
Also see #14434

2016-12-13 06:09 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14557) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-15 03:42 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14412) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-15 23:56 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14260) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-23 15:10 UTC, asajeffrey commented
Rebased. r? @ConnorGBrewster

2016-12-23 17:31 UTC, cbrewster requested changes
Looks good! Although it looks like removing the reference to the active document in the browsing context caused a couple of regressions. I think we should find a way to fix those before merging. 

Also since the BS doesn't store the active document, we will need to find a way to determine if the document is `active` vs `fully_active`.

2016-12-23 17:31 UTC, ConnorGBrewster commented on components/constellation/constellation.rs
> +            self.close_pipeline(entry.pipeline_id, DiscardBrowsingContext::No, ExitPipelineMode::Normal);
Why do we not discard the Browsing Context here?

2016-12-23 17:31 UTC, ConnorGBrewster commented on components/script/dom/browsingcontext.rs
> -    pub fn active_document(&self) -> Root<Document> {
What are the reasons behind not storing a reference to the Document in the BC?

2016-12-23 17:31 UTC, ConnorGBrewster commented on components/script/dom/document.rs
> +        // TODO Step 3.
I think we should find a way to do this, and other cases that may have regressed with this PR before merging.

2016-12-23 17:31 UTC, ConnorGBrewster commented on components/script/dom/window.rs
> +    #[allow(unsafe_code)]
Is this needed?

2016-12-23 17:31 UTC, ConnorGBrewster commented on components/script_traits/lib.rs
> +/// When a pipeline is closed, should its browsing context be discarded too?
Maybe add a spec link here that discussing when to discard browsing contexts?

2016-12-23 18:30 UTC, asajeffrey commented on components/script/dom/document.rs
> +        // FIXME: this should check for being active rather than fully active
The problem is that we're currently not sending enough information from the constellation to the script thread to determine if a document is active. We're sending freeze/thaw messages to determine if a document is fully active, but not any messages about being active. I think this is a spec issue, the spec should really say "fully active" here.

2016-12-23 18:32 UTC, asajeffrey commented on components/constellation/constellation.rs
> +            self.close_pipeline(entry.pipeline_id, DiscardBrowsingContext::No, ExitPipelineMode::Normal);
This code is used when a browsing context navigates, we don't want to close the BC in this case. Nested BCs will get closed, when the recursive call is made it's with `DiscardBrowsingContext::Yes`.

2016-12-23 18:35 UTC, asajeffrey commented on components/script/dom/browsingcontext.rs
> -    pub fn active_document(&self) -> Root<Document> {
We never needed it, so I removed it! SpiderMonkey does the dance to resolve `WindowProxy` to `Window`, which tracks the current document.

2016-12-23 18:39 UTC, asajeffrey commented on components/script/dom/document.rs
> +        // TODO Step 3.
I think it's broken in the same way as it was before. Did this cause a regression?

2016-12-23 18:41 UTC, asajeffrey commented on components/script/dom/window.rs
> +    #[allow(unsafe_code)]
Good catch.

2016-12-24 12:38 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14623) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-05 21:13 UTC, asajeffrey commented
Rebased.

2017-01-05 21:14 UTC, asajeffrey commented
@bors-servo try

2017-01-05 21:14 UTC, bors-servo commented
:hourglass: Trying commit 7c2de62 with merge c0706a2...

2017-01-05 22:06 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1718)

2017-01-06 00:03 UTC, jdm commented
@bors-servo: retry
* #14323

2017-01-06 00:03 UTC, bors-servo commented
:hourglass: Trying commit 7c2de62 with merge 1d5503b...

2017-01-06 02:05 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4743), [arm32](http://build.servo.org/builders/arm32/builds/4914), [arm64](http://build.servo.org/builders/arm64/builds/4948), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5039), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1716), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1723), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5016), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5055), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1722), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1758), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/179), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/180)

2017-01-06 02:19 UTC, cbrewster approved these changes

2017-01-06 02:20 UTC, cbrewster commented
@bors-servo r+ retry

2017-01-06 02:20 UTC, bors-servo commented
:pushpin: Commit 7c2de62 has been approved by `cbrewster`

<!-- @bors-servo r=cbrewster 7c2de62124995c8c353756abdb1ec7c08973ae3a -->

2017-01-06 02:20 UTC, bors-servo commented
:hourglass: Testing commit 7c2de62 with merge 8b274f2...

2017-01-06 03:59 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4744), [arm32](http://build.servo.org/builders/arm32/builds/4915), [arm64](http://build.servo.org/builders/arm64/builds/4950), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5042), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1719), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1726), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5019), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5058), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1724), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1761), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/182), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/183)

2017-01-06 03:59 UTC, merged