Remove-ResponseAction
servo/servo pull request #14586
Opened 2016-12-14 15:33 UTC by deror1869107

Remove the old Enum ResponseAction and use net_traits::FetchResponseMsg instead.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13717 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because @KiChjang said so.

2016-12-14 15:33 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @simonsapin (or someone else) soon.

2016-12-14 15:33 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net/image_cache_thread.rs

2016-12-14 15:33 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2016-12-14 15:52 UTC, jdm requested changes
God start!

2016-12-14 15:52 UTC, jdm commented on components/net/image_cache_thread.rs
> +                                    FetchResponseMsg::ProcessResponse(meta_result)
This change means that the image cache no longer sees the unfiltered metadata.

2016-12-14 15:52 UTC, jdm commented on components/net/image_cache_thread.rs
> +                                    FetchResponseMsg::ProcessResponseEOF(response)
This feels a bit redundant :) We can do this instead:
```rust
let action = match action {
    FetchResponseMsg::ProcessRequestBody |
    FetchResponseMsg::ProcessRequestEOF => return,
    FetchResponseMsg::ProcessResponse(meta_result) => ...,
    a => a,
};
```

2016-12-14 16:35 UTC, jdm commented on components/net/image_cache_thread.rs
> +                                    FetchResponseMsg::ProcessResponse(meta_result)
Oh, right. You're absolutely correct.

2016-12-14 16:53 UTC, deror1869107 commented on components/net/image_cache_thread.rs
> +                                    FetchResponseMsg::ProcessResponseEOF(response)
I have already fixed the redundant code.
Do I have to pull-request again for fixing the redundant code?

2016-12-14 17:10 UTC, jdm commented on components/net/image_cache_thread.rs
> +                                    FetchResponseMsg::ProcessResponseEOF(response)
No - if you commit the changes and push to the same branch, this pull request will be updated. Go ahead and use `git commit --amend` to merge the changes into the same commit, or [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) if there are already multiple commits.

2016-12-14 18:36 UTC, jdm commented
@bors-servo: r+

2016-12-14 18:36 UTC, bors-servo commented
:pushpin: Commit 55dddc8 has been approved by `jdm`

<!-- @bors-servo r=jdm 55dddc8c41f74d628ddf409f4c0e782ec7ddc543 -->

2016-12-15 04:34 UTC, bors-servo commented
:hourglass: Testing commit 55dddc8 with merge fde9ac1...

2016-12-15 05:29 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4484), [arm32](http://build.servo.org/builders/arm32/builds/4658), [arm64](http://build.servo.org/builders/arm64/builds/4680), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4767), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1446), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1450), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4743), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4781), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1451), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1485), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2732)

2016-12-15 05:29 UTC, merged