[WIP] Implement GetGATTChildren
servo/servo pull request #14593
Opened 2016-12-14 20:54 UTC by dati91

Implement the [GetGATTChildren](https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren) function for webbluetooth.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

2016-12-14 20:54 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/bluetoothremotegattserver.rs, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/bluetooth.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs
 * @kichjang: components/script/dom/bluetoothremotegattserver.rs, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/bluetooth.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs

2016-12-14 20:55 UTC, dati91 commented
Note: it depends on https://github.com/servo/servo/pull/14567 and also needs a rebase.

2016-12-14 20:56 UTC, dati91 commented
r? @jdm

2016-12-14 21:02 UTC, jdm commented
What does WIP in the title mean?

2016-12-14 21:05 UTC, dati91 commented
work in progress, maybe i should have used [do not merge yet] or something
I just wanted to indicate somehow that the first patch doesn't belong here, just a placeholder before the other pr lands.

2016-12-15 00:53 UTC, jdm commented
We can use the S-blocked-on-external label for that. WIP usually means that it's not necessarily ready for review yet.

2016-12-15 16:19 UTC, jdm requested changes
This is a nice improvement that reduces code complexity.

2016-12-15 16:19 UTC, jdm commented on components/bluetooth/lib.rs
> +    fn get_gatt_children(&mut self,
Let's add the https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren link back.

2016-12-15 16:19 UTC, jdm commented on components/script/dom/bluetooth.rs
> +    if let Some(u) = uuid {
```rust
let result_uuid = if let Some(u) = uuid {
    let canonicalized = match uuid_canonicalizer(u) {
        Ok(canonicalized_uuid) => canonicalized_uuid.to_string(),
        Err(e) => {
            ...
        }
    };
    if uuid_is_blocklisted(canonicalized.as_ref(), Blocklist::All) {
        ...
    }
    Some(canonicalized)
} else {
    None
};

2016-12-15 18:56 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14604) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-16 19:12 UTC, jdm commented
@bors-servo: delegate+
Squash and r=jdm.

2016-12-16 19:12 UTC, bors-servo commented
:v: @dati91 can now approve this pull request

2016-12-16 20:04 UTC, dati91 commented
@bors-servo r=jdm

2016-12-16 20:04 UTC, bors-servo commented
:pushpin: Commit b010368 has been approved by `jdm`

<!-- @bors-servo r=jdm b0103682fa2cd5147778e70b065ad4ee051684fd -->

2016-12-16 20:30 UTC, bors-servo commented
:hourglass: Testing commit b010368 with merge 6efea39...

2016-12-16 22:23 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4518), [arm32](http://build.servo.org/builders/arm32/builds/4691), [arm64](http://build.servo.org/builders/arm64/builds/4714), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4802), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1481), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1484), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4777), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4815), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1485), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1519), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2767)

2016-12-16 22:23 UTC, merged