Remove the util crate
servo/servo pull request #14592
Opened 2016-12-14 20:52 UTC by asajeffrey

This PR removes the `util` crate.

* Replaced the `spawn_named` and `clamp` functions by appropriate uses of `std::thread::Builder::spawn`, `std::cmp::min` and `std::cmp::max`.
* Moved `opts`, `prefs` and `resource_files` into a new `config` crate.
* Moved `remutex` and `geometry` into their own crates.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because they are refactorings

2016-12-14 20:53 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/stylesheets.rs, components/style/properties/properties.mako.rs, components/style/parallel.rs, components/style/Cargo.toml, components/style/lib.rs, components/style/traversal.rs, components/style/matching.rs
 * @jgraham: components/webdriver_server/Cargo.toml, components/webdriver_server/lib.rs
 * @kichjang: components/script/dom/navigatorinfo.rs, components/script/timers.rs, components/net/http_loader.rs, components/net/storage_thread.rs, components/script/dom/create.rs, components/script/Cargo.toml, components/script/script_thread.rs, components/net/resource_thread.rs, components/script/serviceworker_manager.rs, components/script/dom/htmlanchorelement.rs, components/net/lib.rs, components/net/hsts.rs, components/script/dom/servoparser/mod.rs, components/script/dom/testbinding.rs, components/script/dom/xmlhttprequest.rs, components/net/image_cache_thread.rs, components/script/dom/bindings/conversions.rs, components/net/filemanager_thread.rs, components/script/dom/bindings/guard.rs, components/script/dom/userscripts.rs, components/script/dom/htmlmetaelement.rs, components/script/dom/filereader.rs, components/script/dom/mouseevent.rs, components/script/dom/window.rs, components/script/dom/document.rs, components/net_traits/lib.rs, components/net_traits/lib.rs, components/script/dom/bindings/codegen/CodegenRust.py, components/net/Cargo.toml, components/net/chrome_loader.rs, components/net/content_blocker.rs, components/net_traits/pub_domains.rs, components/net_traits/pub_domains.rs, components/script/dom/characterdata.rs, components/net_traits/Cargo.toml, components/net_traits/Cargo.toml, components/script/lib.rs, components/net/connector.rs, components/script/dom/dedicatedworkerglobalscope.rs, components/net/websocket_loader.rs, components/script/script_runtime.rs, components/script/dom/htmliframeelement.rs, components/script/dom/serviceworkerglobalscope.rs
 * @fitzgen: components/script/dom/navigatorinfo.rs, components/profile_traits/Cargo.toml, components/profile_traits/Cargo.toml, components/script/timers.rs, components/debugger/Cargo.toml, components/script/dom/create.rs, components/devtools/actors/timeline.rs, components/script/Cargo.toml, components/profile_traits/lib.rs, components/profile_traits/lib.rs, components/script/script_thread.rs, components/script/serviceworker_manager.rs, components/script/dom/htmlanchorelement.rs, components/debugger/lib.rs, components/script/dom/servoparser/mod.rs, components/profile/Cargo.toml, components/devtools/Cargo.toml, components/script/dom/testbinding.rs, components/script/dom/xmlhttprequest.rs, components/devtools/lib.rs, components/profile/heartbeats.rs, components/profile/mem.rs, components/script/dom/bindings/conversions.rs, components/script/dom/bindings/guard.rs, components/script/dom/userscripts.rs, components/script/dom/htmlmetaelement.rs, components/script/dom/filereader.rs, components/script/dom/mouseevent.rs, components/script/dom/window.rs, components/script/dom/document.rs, components/script/dom/bindings/codegen/CodegenRust.py, components/profile/time.rs, components/profile_traits/time.rs, components/profile_traits/time.rs, components/profile/lib.rs, components/script/dom/characterdata.rs, components/script/lib.rs, components/script/dom/dedicatedworkerglobalscope.rs, components/script/script_runtime.rs, components/script/dom/htmliframeelement.rs, components/script/dom/serviceworkerglobalscope.rs
 * @emilio: components/style/stylesheets.rs, components/style/properties/properties.mako.rs, components/canvas/webgl_paint_thread.rs, components/layout/traversal.rs, components/layout/sequential.rs, components/style/parallel.rs, components/style/Cargo.toml, components/style/lib.rs, components/layout/parallel.rs, components/layout/context.rs, components/layout/construct.rs, components/layout/display_list_builder.rs, components/layout/block.rs, components/style/traversal.rs, components/style/matching.rs, components/layout/Cargo.toml, components/layout/lib.rs

2016-12-14 20:53 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2016-12-14 21:08 UTC, mbrubeck requested changes
r=mbrubeck with some nits. (Could be fixed by just squashing into a single commit.)

2016-12-14 21:08 UTC, mbrubeck commented on components/geometry/Cargo.toml
> +[package]
Nit: This addition is in the wrong commit.

2016-12-14 21:08 UTC, mbrubeck commented on components/remutex/Cargo.toml
> +[package]
Nit: This addition is in the wrong commit.

2016-12-14 21:08 UTC, mbrubeck commented on tests/unit/remutex/Cargo.toml
> +[package]
Nit: This addition is in the wrong commit.

2016-12-14 21:08 UTC, mbrubeck commented on tests/unit/util/thread.rs
> -/* This Source Code Form is subject to the terms of the Mozilla Public
This deletion is in the wrong commit.

2016-12-14 21:12 UTC, asajeffrey commented
Squashed. @bors-servo: r=mbrubeck

2016-12-14 21:12 UTC, bors-servo commented
:pushpin: Commit facca14 has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck facca1461c761af717f7841f1e3c211e506bf001 -->

2016-12-14 21:17 UTC, KiChjang commented
@bors-servo p=10

2016-12-14 21:28 UTC, bors-servo commented
:hourglass: Testing commit facca14 with merge 70219ae...

2016-12-14 21:53 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/4759)

2016-12-14 22:22 UTC, KiChjang commented
Unit tests imports need to be updated, I presume?

2016-12-14 22:28 UTC, asajeffrey commented
@KiChjang indeed, doing that right now. Ditto cef.

2016-12-14 22:41 UTC, asajeffrey commented
Updated unit tests and cef port. @bors-servo r=mbrubreck p=10

2016-12-14 22:41 UTC, bors-servo commented
:pushpin: Commit caacb9b has been approved by `mbrubreck`

<!-- @bors-servo r=mbrubreck caacb9b8df537fae5914dca5ea26bbc2a7a87569 -->

2016-12-14 23:13 UTC, bors-servo commented
:hourglass: Testing commit caacb9b with merge e9a1129...

2016-12-14 23:29 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/4761)

2016-12-14 23:40 UTC, KiChjang commented
```
error: unused import
  --> /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/style-584c140631e9c02b/out/properties.rs:31:5
   |
31 | use servo_config::prefs::PREFS;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/servo/buildbot/slave/linux-dev/build/components/style/lib.rs:155:5: 155:58 note: in this expansion of include!
   |
note: lint level defined here
  --> /home/servo/buildbot/slave/linux-dev/build/components/style/lib.rs:30:9
   |
30 | #![deny(warnings)]
   |         ^^^^^^^^
```

2016-12-14 23:43 UTC, asajeffrey commented
Oh bah humbug, geckolib.

2016-12-15 00:07 UTC, asajeffrey commented
Fixed geckolib @bors-servo r=mbrubeck

2016-12-15 00:07 UTC, bors-servo commented
:pushpin: Commit 9be4fd5 has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck 9be4fd56ce5467ce6d0e48c6efda9eb26f40eb7a -->

2016-12-15 00:48 UTC, bors-servo commented
:hourglass: Testing commit 9be4fd5 with merge 4eb6538...

2016-12-15 01:40 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4480), [arm32](http://build.servo.org/builders/arm32/builds/4654), [arm64](http://build.servo.org/builders/arm64/builds/4676), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4763), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1442), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1446), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4739), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4777), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1447), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1481), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2728)

2016-12-15 01:41 UTC, merged