Added some new tests for a few webBuetooth method.
servo/servo pull request #14614
Opened 2016-12-16 13:36 UTC by fokinv

We made some new tests for WebBluetooth.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

2016-12-16 20:24 UTC, KiChjang commented
Nit: The commit message has a typo on Bluetooth.

2016-12-21 21:50 UTC, jdm requested changes
Looks like a good set of tests!

2016-12-21 21:50 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/bluetooth/requestDevice/acceptAllDevices/device-with-no-name.html
> +    .then(device => assert_true(device.name === null));
assert_equals(device.name, null)

2016-12-21 21:50 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/bluetooth/requestDevice/acceptAllDevices/optional-services-missing.html
> +    .then(gattServer => promise_rejects(t, 'NotFoundError' ,gattServer.getPrimaryServices()));
nit: move the , next to the string and add a space after it.

2016-12-22 14:39 UTC, jdm commented
@bors-servo: delegate+
This can merge with r=jdm after squashing.

2016-12-22 14:39 UTC, bors-servo commented
:v: @fokinv can now approve this pull request

2016-12-22 14:53 UTC, dati91 commented
@jdm Valentin is already on Holiday, so if you could r+ it that would be great!

2016-12-22 14:56 UTC, jdm commented
@bors-servo: r+

2016-12-22 14:56 UTC, bors-servo commented
:pushpin: Commit 693d026 has been approved by `jdm`

<!-- @bors-servo r=jdm 693d026e9a3fcc9ed00ad6bdcc354123910e6f0d -->

2016-12-22 15:52 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14612) made this pull request unmergeable. Please resolve the merge conflicts.

2016-12-22 18:27 UTC, KiChjang commented
@bors-servo r=jdm

2016-12-22 18:27 UTC, bors-servo commented
:pushpin: Commit bc948f7 has been approved by `jdm`

<!-- @bors-servo r=jdm bc948f7975917db539acb3dce672deeb8454f344 -->

2016-12-22 19:04 UTC, bors-servo commented
:hourglass: Testing commit bc948f7 with merge 185eb56...

2016-12-22 20:02 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4569), [arm32](http://build.servo.org/builders/arm32/builds/4742), [arm64](http://build.servo.org/builders/arm64/builds/4766), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4853), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1534), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1539), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4829), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4868), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1537), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1571), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2818)

2016-12-22 20:02 UTC, merged