Use MediaQueryListEvent for media query list change events
servo/servo pull request #14630
Opened 2016-12-19 16:02 UTC by bd339

- Implements MediaQueryListEvent interface
- Makes MediaQueryList change events conform to the spec
- Updates matchMedia.html test to verify that the new event type is used

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14064

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-12-19 16:02 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @asajeffrey (or someone else) soon.

2016-12-19 16:02 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/mod.rs, components/script/dom/mediaquerylistevent.rs, components/script/dom/webidls/MediaQueryListEvent.webidl, components/script/dom/mediaquerylist.rs
 * @kichjang: components/script/dom/mod.rs, components/script/dom/mediaquerylistevent.rs, components/script/dom/webidls/MediaQueryListEvent.webidl, components/script/dom/mediaquerylist.rs

2016-12-19 18:52 UTC, KiChjang commented on components/script/dom/mediaquerylist.rs
> +                let ev = MediaQueryListEvent::new(&mql.root().unwrap().global(),
I believe having a `let mql = mql.root().unwrap();` above this line would save you a lot of the unnecessary rooting and unwrapping every time you want to make a reference to the `MediaQueryList`.

2016-12-19 18:53 UTC, KiChjang commented on tests/wpt/mozilla/tests/mozilla/interfaces.html
> +  "MediaQueryListEvent",
This needs review from @jdm or @Ms2ger in order to be added.

2016-12-19 19:14 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/interfaces.html
> +  "MediaQueryListEvent",
I approve this change.

2016-12-19 19:16 UTC, jdm commented on components/script/dom/mediaquerylist.rs
> +                mql.root().unwrap().upcast::<EventTarget>().dispatch_event(&event);
We should this instead:
```rust
let event = ev.upcast::<Event>();
event.fire(mql.root().unwrap().upcast::<EventTarget>());
```

2016-12-19 20:57 UTC, bd339 commented on components/script/dom/mediaquerylist.rs
> +                mql.root().unwrap().upcast::<EventTarget>().dispatch_event(&event);
Will do, but what is the difference?

2016-12-19 21:25 UTC, KiChjang commented on components/script/dom/mediaquerylist.rs
> +                mql.root().unwrap().upcast::<EventTarget>().dispatch_event(&event);
`Event::fire` implicitly sets the trusted field to true.

2016-12-19 21:28 UTC, bd339 commented on components/script/dom/mediaquerylist.rs
> +                mql.root().unwrap().upcast::<EventTarget>().dispatch_event(&event);
Oh, right. Completely missed that from his snippet.

2016-12-19 21:55 UTC, KiChjang commented on components/script/dom/mediaquerylistevent.rs
> +        self.event.IsTrusted()
`self.upcast::<Event>().IsTrusted()`

2016-12-20 13:00 UTC, bd339 commented
r?@KiChjang

2016-12-20 19:02 UTC, KiChjang requested changes
Great work! One minor nit and you can r=me.

2016-12-20 19:02 UTC, KiChjang commented on components/script/dom/mediaquerylistevent.rs
> +            media: media.clone(),
Is the clone necessary here?

2016-12-20 21:16 UTC, bd339 commented
r=KiChjang

2016-12-20 21:37 UTC, bors-servo commented
:pushpin: Commit eed68e1 has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang eed68e1c7b1949b65bca01e492c119b9eb594e42 -->

2016-12-20 21:37 UTC, KiChjang approved these changes

2016-12-20 21:37 UTC, bors-servo commented
:hourglass: Testing commit eed68e1 with merge bcf154d...

2016-12-20 22:44 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4548), [arm32](http://build.servo.org/builders/arm32/builds/4721), [arm64](http://build.servo.org/builders/arm64/builds/4745), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4832), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1513), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1517), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4808), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4847), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1516), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1550), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2797)

2016-12-20 22:44 UTC, merged