Support the 'current' global object.
servo/servo pull request #14647
Opened 2016-12-20 16:33 UTC by Ms2ger

2016-12-20 16:33 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/dom/servoparser/mod.rs, components/script/dom/globalscope.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/xmldocument.rs, components/script/dom/domparser.rs, components/script/script_thread.rs, components/script/dom/node.rs, components/script/dom/domimplementation.rs
 * @kichjang: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/dom/servoparser/mod.rs, components/script/dom/globalscope.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/xmldocument.rs, components/script/dom/domparser.rs, components/script/script_thread.rs, components/script/dom/node.rs, components/script/dom/domimplementation.rs

2016-12-20 16:33 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-12-20 16:49 UTC, jdm commented
On the surface this seems like a partial implementation of the script settings stack, but I don't see how we could build a stack that we could return non-current entries from. Since that's the case, it's not clear to me why it's worth implementing this by itself, rather than doing the script stack properly.

2016-12-20 17:06 UTC, Ms2ger commented
I don't see a reason to block this on a full implementation of incumbent/entry globals; there will be no need to change this code when we do that, and at least now we can properly implement the security checks for `contentDocument`.

2016-12-20 18:26 UTC, metajack commented
cc @Ms2ger

2016-12-20 18:32 UTC, jdm commented
That makes sense.

2016-12-20 18:33 UTC, metajack commented
cc @metajack

2016-12-20 19:33 UTC, Ms2ger commented
@bors-servo try

2016-12-20 19:33 UTC, bors-servo commented
:hourglass: Trying commit c2ff9d3 with merge 96076d4...

2016-12-20 20:25 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4545), [arm32](http://build.servo.org/builders/arm32/builds/4718), [arm64](http://build.servo.org/builders/arm64/builds/4742), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4829), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1510), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1514), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4805), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4844), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1513), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1547), [windows-dev](http://build.servo.org/builders/windows-dev/builds/2794)

2016-12-21 11:09 UTC, Ms2ger commented
Depends on https://github.com/servo/rust-mozjs/pull/322

2016-12-23 10:39 UTC, Ms2ger commented
r? @jdm

2016-12-28 16:02 UTC, jdm requested changes

2016-12-28 16:02 UTC, jdm commented on components/script/dom/xmlhttprequest.rs
> +                      doc.origin().alias(),
Given that the XHR specification doesn't specify any origin, I believe this should be an opaque origin instead.

2016-12-28 16:14 UTC, Ms2ger commented on components/script/dom/xmlhttprequest.rs
> +                      doc.origin().alias(),
> Set document's origin to context object's relevant settings object's origin. 

https://xhr.spec.whatwg.org/#document-response step 11

2016-12-28 16:15 UTC, jdm commented
@bors-servo: r+

2016-12-28 16:15 UTC, bors-servo commented
:pushpin: Commit d49e34c has been approved by `jdm`

<!-- @bors-servo r=jdm d49e34c1b1e6e3759633c9315a3e02dde091546c -->

2016-12-28 16:15 UTC, jdm approved these changes

2016-12-28 17:08 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1648)

2016-12-28 18:03 UTC, Ms2ger commented
```
Tests with unexpected results:
  ▶ ERROR [expected OK] /workers/baseurl/alpha/sharedworker.html
  └   → SharedWorker is not defined
```

I'm not sure how that could happen; I'll try to reproduce locally first.

2016-12-28 18:06 UTC, Ms2ger commented
@bors-servo try

2016-12-28 18:11 UTC, Ms2ger commented
@bors-servo r- try retry

Doesn't reproduce locally. Let's see if it's consistent on the builder.

2016-12-28 18:11 UTC, bors-servo commented
:hourglass: Trying commit d49e34c with merge d0aaedc...

2016-12-28 19:32 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4644), [arm32](http://build.servo.org/builders/arm32/builds/4819), [arm64](http://build.servo.org/builders/arm64/builds/4843), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4933), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1609), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1617), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4910), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4950), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1617), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1651), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/72), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/73)

2016-12-29 08:53 UTC, Ms2ger commented
I ran this 800 times locally and didn't fail once; filed https://github.com/servo/servo/issues/14772.

@bors-servo try- r=jdm retry

2016-12-29 08:54 UTC, bors-servo commented
:pushpin: Commit d49e34c has been approved by `jdm`

<!-- @bors-servo r=jdm d49e34c1b1e6e3759633c9315a3e02dde091546c -->

2016-12-29 09:38 UTC, bors-servo commented
:hourglass: Testing commit d49e34c with merge 885d152...

2016-12-29 10:34 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4653), [arm32](http://build.servo.org/builders/arm32/builds/4827), [arm64](http://build.servo.org/builders/arm64/builds/4852), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4942), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1618), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1626), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4919), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4959), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1626), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1660), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/81), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/82)

2016-12-29 10:34 UTC, merged