[WIP] Support origins in CSSOM stylesheets
servo/servo pull request #14646
Opened 2016-12-20 12:28 UTC by canaltinova

I still need to pass the origin clean flag to constructors. `style::stylesheets::Stylesheet` has an origin field but I don't think that's relevant.
I can get href in htmllinkelement.rs like this:
```rust
let element = self.upcast::<Element>();
let href = element.get_string_attribute(&local_name!("href"));
```
But I'm not sure how to proceed after here.
@Manishearth any opinions?

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14327 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-12-20 12:28 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmlmetaelement.rs, components/script/dom/htmllinkelement.rs, components/script/dom/webidls/CSSStyleSheet.webidl, components/script/dom/cssstylesheet.rs, components/script/dom/htmlstyleelement.rs
 * @kichjang: components/script/dom/htmlmetaelement.rs, components/script/dom/htmllinkelement.rs, components/script/dom/webidls/CSSStyleSheet.webidl, components/script/dom/cssstylesheet.rs, components/script/dom/htmlstyleelement.rs

2016-12-20 12:28 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2016-12-20 13:31 UTC, Ms2ger commented
The spec defines this here: <https://html.spec.whatwg.org/multipage/#link-type-stylesheet>.

In particular, you need to check if the response is [CORS-same-origin](https://html.spec.whatwg.org/multipage/infrastructure.html#cors-same-origin). This is a check on `Response::response_type`… which is not exposed yet to the DOM code. Two ways to pass that value along come to mind:

* Pass it in the `Metadata` struct that is passed to `FetchResponseListener::process_response`
* Pass it as the `Ok` value of the `Result` that is passed to `FetchResponseListener::process_response_eof`

CC @jdm

2016-12-20 14:56 UTC, jdm commented
Yeah, that information is supposed to be part of https://github.com/servo/servo/issues/14068.

2016-12-20 16:01 UTC, canaltinova commented
Okay, I'll wait this one. Thanks for the info!

2016-12-20 16:57 UTC, Manishearth commented on components/script/dom/cssstylesheet.rs
> +            origin_clean: AtomicBool::new(origin_clean),
`Cell<bool>` is fine here, the DOM is not multithreaded, thank goodness.

2016-12-20 19:38 UTC, canaltinova commented on components/script/dom/cssstylesheet.rs
> +            origin_clean: AtomicBool::new(origin_clean),
😄  Thanks, updated the code :)

2017-01-14 17:56 UTC, canaltinova commented
@jdm I'm not so sure about the code I wrote in `components/script/stylesheet_loader.rs`. It can be better I think but I couldn't come up with a better idea. I couldn't downcast to CSSStyleSheet from HTMLElement directly, so I had to try to downcast  3 different type of element and get stylesheet from them.
Also in my local copy, I got some unexpected failing tests with some passing ones.
@bors-servo try

2017-01-14 17:56 UTC, bors-servo commented
:hourglass: Trying commit 9deb817 with merge 962ec3d...

2017-01-14 18:42 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1882)

2017-01-19 19:57 UTC, jdm commented
I believe the failures you see come from CSSStyleSheet::origin_clean being initialized to false - for inline style elements, they will never be marked clean since the stylesheet loader won't interact with them.

2017-01-19 19:59 UTC, jdm requested changes

2017-01-19 19:59 UTC, jdm commented on components/script/stylesheet_loader.rs
> +            stylesheet = element.get_cssom_stylesheet();
I don't believe stylesheets originating from meta elements can ever cause a network load to start, so this shouldn't be necessary here.

2017-01-19 19:59 UTC, jdm commented on components/script/dom/cssstylesheet.rs
> +            origin_clean: Cell::new(false),
We should probably assume this is clean instead, or we'll break inline stylesheets and the ones from meta elements unless we add special handling for them.

2017-01-19 20:47 UTC, canaltinova commented on components/script/dom/cssstylesheet.rs
> +            origin_clean: Cell::new(false),
Oh, you are right. I thought it will always enter process_response. (I don't know why I thought like this :) )

2017-01-19 20:48 UTC, canaltinova commented
@bors-servo try

2017-01-19 20:49 UTC, bors-servo commented
:hourglass: Trying commit 32e4a94 with merge 0b0f039...

2017-01-19 21:50 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4971), [arm32](http://build.servo.org/builders/arm32/builds/5139), [arm64](http://build.servo.org/builders/arm64/builds/5183), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5284), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1957), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1967), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5253), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5294), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1956), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2002), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/421), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/423)

2017-01-19 21:52 UTC, jdm commented
It's unnerving that no tests changed results with the latest changes... please write a test that verifies these changes are doing the right thing?

2017-01-20 00:19 UTC, canaltinova commented
Hm, actually it wasn't working. I wrote a simple test case but I was still able to access stylesheet instead of an error. `get_cssom_stylesheet` was returning None in HTMLLinkElement. It was because `process_response_eof` is [creating](https://github.com/canaltinova/servo/blob/32e4a949965b113466be9e0b041bcd924cfae266/components/script/stylesheet_loader.rs#L162-L170) the StyleSheet and during `process_response` it was always none.

But we are unable to access FetchMetadata inside process_response_eof. I checked it in the process_response and stored in a cell, then assigned to the cssom stylesheet inside process_response_eof.

2017-01-20 00:26 UTC, canaltinova commented
Ah, I also deleted the HTMLStyleElement related code. I don't think it can ever be a cross origin, can it?

I want to write a test for it but I need to give a css link of a website that we are sure it won't change. Should we write a test like this?

2017-01-20 00:28 UTC, Manishearth commented
Nope. No src.

https://html.spec.whatwg.org/multipage/semantics.html#the-style-element

It may contain `@import` rules however, and we probably need to set the flags for those.

2017-01-20 00:53 UTC, canaltinova commented
Okay, updated the code to cover `@import` too. To be able to cast one of the both stylesheet owners easily, I had to add a new function to StylesheetOwner trait.

2017-01-20 04:01 UTC, jdm requested changes
Nice improvement using the StylesheetOwner trait.

2017-01-20 04:01 UTC, jdm commented on components/script/stylesheet_loader.rs
> +    origin_clean: Cell<bool>,
No need for a Cell, since the methods are &mut self.

2017-01-20 04:01 UTC, jdm commented on components/script/stylesheet_loader.rs
> +                self.origin_clean.set(true);
Since it starts as true, we only need to set it in the cases where it's not origin clean.

2017-01-20 04:03 UTC, jdm commented
@canaltinova The WPT harness has multiple hosts that resolve to localhost but get treated as cross-origin - https://dxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/common/get-host-info.sub.js is an example of how to set up those addresses.

2017-01-20 04:04 UTC, jdm commented
@bors-servo: try

2017-01-20 04:04 UTC, bors-servo commented
:hourglass: Trying commit dbaea1b with merge 512dd93...

2017-01-20 05:00 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4975), [arm32](http://build.servo.org/builders/arm32/builds/5144), [arm64](http://build.servo.org/builders/arm64/builds/5188), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5289), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1963), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1973), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5259), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5299), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1961), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2007), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/427), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/429)

2017-01-20 10:08 UTC, Manishearth commented
Hmm, so we don't actually support any attributes on `CSSImportRule` right now, so handling that case doesn't exactly matter yet.

We'll basically have to store an independent origin-clean flag on the `ImportRule`, and use that to manually set the origin flag of the lazily-created `CSSStyleSheet`. (We don't create that stylesheet at all right now)

2017-01-20 18:37 UTC, jdm requested changes
Nice test!

2017-01-20 18:37 UTC, jdm commented on tests/wpt/web-platform-tests/cssom/stylesheet-same-origin.sub.html
> +        }, "Origin-clean check in CSSOM Stylesheets");
Let's split these into separate tests for same-origin and cross-origin stylesheets.

2017-01-20 18:37 UTC, jdm commented on tests/wpt/web-platform-tests/cssom/stylesheet-same-origin.sub.html
> +            assert_equals(sameorigin.cssRules.length, 1, "Same origin stylesheet.insertRule should be accessible.");
The message should use deleteRule.

2017-01-20 18:43 UTC, canaltinova commented
Updated tests.

2017-01-20 18:59 UTC, jdm commented
If you squash the commits into one, this can land with r=jdm.
@bors-servo: delegate+

2017-01-20 18:59 UTC, bors-servo commented
:v: @canaltinova can now approve this pull request

2017-01-20 19:03 UTC, canaltinova commented
@bors-servo r=jdm
Thanks for all help!

2017-01-20 19:03 UTC, bors-servo commented
:pushpin: Commit fd950a7 has been approved by `jdm`

<!-- @bors-servo r=jdm fd950a730961dcf71eccd1e244776897c5f945c4 -->

2017-01-20 19:13 UTC, bors-servo commented
:hourglass: Testing commit fd950a7 with merge 15c542d...

2017-01-20 20:10 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4985), [arm32](http://build.servo.org/builders/arm32/builds/5154), [arm64](http://build.servo.org/builders/arm64/builds/5198), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5299), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1973), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1983), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5269), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5309), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1971), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2017), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/437), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/439)

2017-01-20 20:10 UTC, merged