Implement CSSKeyframeRule.style
servo/servo pull request #14712
Opened 2016-12-24 09:15 UTC by KiChjang

Fixes #14636.

r? @Manishearth

2016-12-24 09:15 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/cssstyledeclaration.rs, components/script/dom/cssstylerule.rs, components/script/dom/webidls/CSSKeyframeRule.webidl, components/script/dom/csskeyframerule.rs
 * @kichjang: components/script/dom/cssstyledeclaration.rs, components/script/dom/cssstylerule.rs, components/script/dom/webidls/CSSKeyframeRule.webidl, components/script/dom/csskeyframerule.rs

2016-12-24 09:15 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.

2016-12-24 09:19 UTC, Manishearth requested changes
test needs fixing

2016-12-24 09:19 UTC, Manishearth commented on tests/wpt/web-platform-tests/cssom/CSSKeyframeRule.html
> +  div { margin: 10px; padding: 0px; }
this isn't a keyframe rule

2016-12-25 23:19 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14640) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-08 02:42 UTC, KiChjang commented
Fixed tests. r? @Manishearth

2017-01-08 05:05 UTC, Manishearth commented
@bors-servo r+

2017-01-08 05:05 UTC, bors-servo commented
:pushpin: Commit dddc458 has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth dddc458fcc04d4a404834eacde8d1c0eb57489ba -->

2017-01-08 05:05 UTC, bors-servo commented
:hourglass: Testing commit dddc458 with merge fddc1a7...

2017-01-08 05:22 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/5092)

2017-01-08 06:18 UTC, KiChjang commented
@bors-servo r=Manishearth

2017-01-08 06:18 UTC, bors-servo commented
:pushpin: Commit 18567ce has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth 18567ce7a88aad4ce315f5c277d29d32c702d899 -->

2017-01-08 06:18 UTC, bors-servo commented
:hourglass: Testing commit 18567ce with merge cdf1473...

2017-01-08 07:14 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4793), [arm32](http://build.servo.org/builders/arm32/builds/4959), [arm64](http://build.servo.org/builders/arm64/builds/4999), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5093), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1770), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1777), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5068), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5109), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1774), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1813), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/232), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/233)

2017-01-08 07:14 UTC, merged