Default is top-to-bottom if unset, not bottom-to-top
servo/servo pull request #14746
Opened 2016-12-27 23:33 UTC by DominoTree

Reverse linear gradient direction if not explicitly specified to match expected default behavior

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #14745 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-12-27 23:33 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/values/computed/image.rs
 * @emilio: components/style/values/computed/image.rs

2016-12-27 23:33 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2016-12-27 23:33 UTC, cbrewster commented
Could we add a ref test for this?

2016-12-27 23:34 UTC, DominoTree commented
Yeah, I can add a test

2016-12-28 00:50 UTC, DominoTree commented
I added a test, it required a bit of boilerplate, not sure if we should put it into a macro or something.

2016-12-28 05:08 UTC, cbrewster commented
Here is how to add a new reftest: https://github.com/servo/servo/tree/master/tests/wpt#writing-new-tests

2016-12-28 05:42 UTC, jdm commented
r? @SimonSapin

2016-12-28 08:14 UTC, shinglyu requested changes

2016-12-28 08:14 UTC, shinglyu commented on tests/unit/style/parsing/image.rs
> +    // AngleOrCorner::None should become AngleOrCorner::Angle(Angle(PI)) when parsed
Maybe add a link to the spec in the comment. Or at least make clear that `PI` means "top-to-bottom". :)

2016-12-28 08:20 UTC, shinglyu commented
For the reftest, you can create two htmls, the test html could be a gradient box with the default, the reference html can be a gradient box that was explicitly set as `to bottom`. The two should render exactly the same.

To begin with, you can put the test in `tests/wpt/mozilla/tests/css`, these are servo-specific tests that are hard or impossible to upstream. But later you might want to upstream that to wpt and pull the new wpt test into servo.

2016-12-28 12:37 UTC, KiChjang commented
Pulling from upstream WPT should really only be done by @Ms2ger or @jgraham. Please wait for them to update WPT when you have submitted and merged tests upstream.

2016-12-28 15:18 UTC, DominoTree commented
Added reftests to existing linear-gradient parsing tests in `tests/wpt/mozilla/tests/css`

2016-12-28 16:39 UTC, emilio commented
Looks great to me, thanks.

@bors-servo r+

2016-12-28 16:39 UTC, bors-servo commented
:pushpin: Commit 23d4f04 has been approved by `emilio`

<!-- @bors-servo r=emilio 23d4f04ce5a726e824490f03587762e6b59d1ec2 -->

2016-12-28 17:08 UTC, bors-servo commented
:hourglass: Testing commit 23d4f04 with merge 3911fbe...

2016-12-28 17:43 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1615)

2016-12-28 18:09 UTC, jdm commented
@bors-servo: retry
* #14323

2016-12-28 18:46 UTC, bors-servo commented
:hourglass: Testing commit 23d4f04 with merge adb3e12...

2016-12-28 20:05 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4645), [arm32](http://build.servo.org/builders/arm32/builds/4818), [arm64](http://build.servo.org/builders/arm64/builds/4844), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4934), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1610), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1618), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4911), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/4951), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1618), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1652), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/73), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/74)

2016-12-28 20:05 UTC, merged