Updating http_network_or_cache_fetch to better match the fetch API spec
servo/servo pull request #14784
Opened 2016-12-30 01:41 UTC by mattnenterprise

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #14742

- [x] There are tests for these changes

2016-12-30 01:41 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net/http_loader.rs

2016-12-30 01:41 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2016-12-30 01:58 UTC, KiChjang commented
@bors-servo try

2016-12-30 01:58 UTC, bors-servo commented
:hourglass: Trying commit 563c9eb with merge 5944e85...

2016-12-30 02:35 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1635)

2016-12-30 02:42 UTC, KiChjang commented
```

  ▶ Unexpected subtest result in /XMLHttpRequest/send-entity-body-empty.htm:
  └ PASS [expected FAIL] XMLHttpRequest: send("") - empty entity body (HEAD)

  ▶ Unexpected subtest result in /XMLHttpRequest/send-entity-body-get-head.htm:
  └ PASS [expected FAIL] XMLHttpRequest: send() - non-empty data argument and GET/HEAD (HEAD)

  ▶ Unexpected subtest result in /XMLHttpRequest/send-entity-body-none.htm:
  └ PASS [expected FAIL] No content type (HEAD)

  ▶ Unexpected subtest result in /XMLHttpRequest/send-entity-body-none.htm:
  └ PASS [expected FAIL] Explicit content type (HEAD)

  ▶ Unexpected subtest result in /eventsource/request-cache-control.htm:
  └ PASS [expected TIMEOUT] EventSource: Cache-Control

  ▶ Unexpected subtest result in /html/webappapis/scripting/event-loops/microtask_after_script.html:
  └ PASS [expected FAIL] Microtask immediately after script
```
Looking good! You'll need to update the WPT test expectations.

2016-12-30 04:35 UTC, jdm commented on tests/wpt/metadata/html/webappapis/scripting/event-loops/microtask_after_script.html.ini
> -
Unfortunately this isn't actually a result caused by these changes (see #14221), so we should revert this.

2016-12-30 17:01 UTC, mattnenterprise commented
I have made the updates.

2016-12-30 18:46 UTC, jdm requested changes
This looks fine with some indentation adjustments.

2016-12-30 18:46 UTC, jdm commented on components/net/http_loader.rs
> +          return Response::network_error(NetworkError::Internal("Couldn't find response in cache".into()))
nit: four space indents, please.

2016-12-30 18:46 UTC, jdm commented on components/net/http_loader.rs
> +          // Step 21
nit: four space indents on this block and the previous line, please.

2016-12-30 18:46 UTC, jdm commented on components/net/http_loader.rs
>              // Substep 1
nit: this block should be indented four spaces past the previous line.

2016-12-30 18:46 UTC, jdm commented on components/net/http_loader.rs
> +          // Step 22
nit: indent this block by another two spaces.

2016-12-30 18:46 UTC, jdm commented on components/net/http_loader.rs
> +          // Step 23
nit: indentation.

2016-12-30 18:46 UTC, jdm commented on components/net/http_loader.rs
> +      // TODO Create the authentication entry for request and the given realm
nit: indentation.

2016-12-31 17:43 UTC, mattnenterprise commented
I have made the updates.

2017-01-01 06:03 UTC, KiChjang requested changes
Almost there! Still needs some indentation changes, and after that it can be r=me.

2017-01-01 06:03 UTC, KiChjang commented on components/net/http_loader.rs
> +          cors_flag, done_chan, context);
nit: Indentation.

2017-01-01 06:03 UTC, KiChjang commented on components/net/http_loader.rs
> +          http_request.cache_mode.get() == CacheMode::OnlyIfCached {
nit: Indentation, this should match the previous line's `http_request`.

2017-01-01 18:28 UTC, mattnenterprise commented
I have made the updates.

2017-01-01 23:33 UTC, jdm commented
@bors-servo r=KiChjang,jdm
Thanks!

2017-01-01 23:33 UTC, bors-servo commented
:pushpin: Commit 6caa5a2 has been approved by `KiChjang,jdm`

<!-- @bors-servo r=KiChjang,jdm 6caa5a27921741c8ca112b146c2649bed658f7b3 -->

2017-01-01 23:33 UTC, bors-servo commented
:hourglass: Testing commit 6caa5a2 with merge b337e92...

2017-01-01 23:52 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/4972)

2017-01-02 16:09 UTC, jdm commented
```
Checking files for tidiness...
./components/net/http_loader.rs:1058: Line is longer than 120 characters
```

2017-01-02 17:17 UTC, mattnenterprise commented
I have fixed that line.

2017-01-02 18:35 UTC, jdm commented
@bors-servo: r=jdm,KiChjang

2017-01-02 18:35 UTC, bors-servo commented
:pushpin: Commit 09194a1 has been approved by `jdm,KiChjang`

<!-- @bors-servo r=jdm,KiChjang 09194a15ac107473c47d8777a569cc4b0729ea5f -->

2017-01-02 19:30 UTC, bors-servo commented
:hourglass: Testing commit 09194a1 with merge 987b640...

2017-01-02 20:06 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1668)

2017-01-02 21:36 UTC, jdm commented
@bors-servo: retry
* #13400

2017-01-02 21:36 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/4695), [arm32](http://build.servo.org/builders/arm32/builds/4864), [arm64](http://build.servo.org/builders/arm64/builds/4895), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4986), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1663), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1669), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4963), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5002), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1705), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/125), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/126) are reusable. Rebuilding only [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1668)...

2017-01-02 22:17 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4695), [arm32](http://build.servo.org/builders/arm32/builds/4864), [arm64](http://build.servo.org/builders/arm64/builds/4895), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4986), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1663), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1669), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4963), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5002), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1670), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1705), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/125), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/126)

2017-01-02 22:17 UTC, merged