WIP add spec links to all CSS properties
servo/servo pull request #14827
Opened 2017-01-02 21:55 UTC by Manishearth

Currently the spec argument is optional, but I will make it mandatory later.

Still going through the properties adding links.

2017-01-02 21:55 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/properties/shorthand/background.mako.rs, components/style/properties/shorthand/border.mako.rs, components/style/properties/data.py, components/style/properties/longhand/background.mako.rs, components/style/properties/longhand/color.mako.rs, components/style/properties/helpers.mako.rs, components/style/properties/longhand/position.mako.rs, components/style/properties/longhand/border.mako.rs, components/style/properties/shorthand/position.mako.rs
 * @emilio: components/style/properties/shorthand/background.mako.rs, components/style/properties/shorthand/border.mako.rs, components/style/properties/data.py, components/style/properties/longhand/background.mako.rs, components/style/properties/longhand/color.mako.rs, components/style/properties/helpers.mako.rs, components/style/properties/longhand/position.mako.rs, components/style/properties/longhand/border.mako.rs, components/style/properties/shorthand/position.mako.rs

2017-01-02 21:55 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2017-01-02 22:58 UTC, Manishearth commented
r? @emilio 

(still WIP)

I also added support for some logical values we seem to have missed (MDN helpfully tells you when there are specs which supplement the existing one), which needs review.

2017-01-03 02:24 UTC, emilio commented
Does Gecko implement float/clear: inline-{start, end}?

The rest looks great! Thanks for doing this :)

2017-01-03 02:26 UTC, Manishearth commented
> Does Gecko implement float/clear: inline-{start, end}?

Yes. Behind a pref (enabled by default on nightly/aurora), but yes.

2017-01-03 02:40 UTC, Manishearth commented
At some point we'll need to figure out our story for experimental gecko props. It's especially complicated because gecko has support for both completely turning off some properties as well as just preffing off some values.

2017-01-03 03:43 UTC, Manishearth commented
Done. r? @emilio

2017-01-03 10:25 UTC, emilio requested changes

2017-01-03 10:25 UTC, emilio commented on components/style/properties/data.py
> +            raise TypeError("Spec should be specified for %s" %name)
nit: I think the common style is with spaces around both sides of `%`? Here and below.

2017-01-03 10:25 UTC, emilio commented on components/style/properties/data.py
>      def __init__(self, name, sub_properties, spec="NO SPEC", experimental=False, internal=False,
Also, this patch is useless until you change both `spec="NO SPEC"` to `spec=None`, right?

2017-01-03 10:25 UTC, emilio commented on components/style/properties/longhand/box.mako.rs
> +                   spec="Nonstandard (for user-agent stylesheets only)">
Instead of this, I'd probably write "Internal (not web-exposed)", what do you think?

2017-01-03 10:25 UTC, emilio commented on components/style/properties/longhand/box.mako.rs
> +    spec="Nonstandard, may be standardized (https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-box)")}
Similarly, this should probably say that this is not web-exposed? Or is it?

2017-01-03 10:25 UTC, emilio commented on components/style/properties/longhand/box.mako.rs
> +    products="gecko", animatable=False, internal=True,
Is this really an internal property in Gecko? (from the MDN docs it seems web exposed).

If it is exposed, please address this or file an issue for a followup.

If it isn't, please note it in the `spec=`.

2017-01-03 10:25 UTC, emilio commented on components/style/properties/longhand/margin.mako.rs
> +        spec = "https://drafts.csswg.org/css-box/#propdef-%s" % side[0]
is there a `margin-` missing here? This will generate links like `propdef-right`, right?

2017-01-03 10:25 UTC, emilio commented on components/style/properties/longhand/ui.mako.rs
> +// TODO spec says that UAs should not support this
File a bug and reference it here please.

2017-01-03 15:17 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14830) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-03 18:26 UTC, Manishearth commented on components/style/properties/longhand/box.mako.rs
> +    products="gecko", animatable=False, internal=True,
Internal but may be exposed later.

2017-01-03 18:33 UTC, Manishearth commented
Updated

2017-01-03 19:29 UTC, emilio approved these changes

2017-01-03 19:29 UTC, emilio commented on components/style/properties/helpers.mako.rs
> +    /// ${property.spec}
Maybe worth to be a bit more descriptive (using also `${property.name}`.

Ideally we could come up with pretty good messages, but that's not required to land this.

2017-01-03 19:29 UTC, emilio commented
@bors-servo r+

Thanks for doing this! :)

2017-01-03 19:29 UTC, bors-servo commented
:pushpin: Commit 645ebd3 has been approved by `emilio`

<!-- @bors-servo r=emilio 645ebd3703017b5c627623e73101af1df1be12b8 -->

2017-01-03 19:29 UTC, bors-servo commented
:hourglass: Testing commit 645ebd3 with merge b8ebf21...

2017-01-03 19:34 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/4994)

2017-01-03 19:40 UTC, emilio commented
Well, it works:

```
--- stderr


Traceback (most recent call last):
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/build.py", line 60, in render
    return template.render(**context).encode("utf8")
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/Mako-0.9.1.zip/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/Mako-0.9.1.zip/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/Mako-0.9.1.zip/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/Mako-0.9.1.zip/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/properties.mako.rs", line 71, in render_body
    <%include file="/longhand/effects.mako.rs" />
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/Mako-0.9.1.zip/mako/runtime.py", line 734, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/longhand/effects.mako.rs", line 10, in render_body
    ${helpers.predefined_type("opacity",
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/helpers.mako.rs", line 20, in render_predefined_type
    <%call expr="longhand(name, predefined_type=type, **kwargs)">
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/helpers.mako.rs", line 588, in longhand
    </%call>
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/helpers.mako.rs", line 8, in render_longhand
    <%call expr="raw_longhand(name, **kwargs)">
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/helpers.mako.rs", line 179, in raw_longhand
    </%call>
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/helpers.mako.rs", line 183, in render_raw_longhand
    <%
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/data.py", line 226, in declare_longhand
    longhand = Longhand(self.current_style_struct, name, **kwargs)
  File "/home/servo/buildbot/slave/linux-dev/build/components/style/properties/data.py", line 94, in __init__
    raise TypeError("Spec should be specified for %s" % name)
TypeError: Spec should be specified for opacity
```

2017-01-03 21:41 UTC, Manishearth commented
@bors-servo r=emilio

2017-01-03 21:41 UTC, bors-servo commented
:pushpin: Commit ac6fb96 has been approved by `emilio`

<!-- @bors-servo r=emilio ac6fb963e284eeefe84364b92fe584d692ad8398 -->

2017-01-03 21:41 UTC, bors-servo commented
:hourglass: Testing commit ac6fb96 with merge 9696403...

2017-01-03 21:52 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/4996)

2017-01-03 22:04 UTC, Manishearth commented
@bors-servo r=emilio

2017-01-03 22:04 UTC, bors-servo commented
:pushpin: Commit 1094c68 has been approved by `emilio`

<!-- @bors-servo r=emilio 1094c68a556b961ae6cb55ba5072b764a8bcbd48 -->

2017-01-03 22:04 UTC, bors-servo commented
:hourglass: Testing commit 1094c68 with merge bfb1de9...

2017-01-03 22:20 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/4997)

2017-01-03 22:28 UTC, Manishearth commented
@bors-servo r=emilio

2017-01-03 22:28 UTC, bors-servo commented
:pushpin: Commit 94412ab has been approved by `emilio`

<!-- @bors-servo r=emilio 94412ab6b03b6a89b937e0fe00fe69755a879d32 -->

2017-01-03 22:28 UTC, bors-servo commented
:hourglass: Testing commit 94412ab with merge 61f6454...

2017-01-03 23:52 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4706), [arm32](http://build.servo.org/builders/arm32/builds/4875), [arm64](http://build.servo.org/builders/arm64/builds/4907), [linux-dev](http://build.servo.org/builders/linux-dev/builds/4998), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1675), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1681), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/4975), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5014), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1681), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1717), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/137), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/138)

2017-01-03 23:52 UTC, merged

2017-01-04 00:47 UTC, emilio commented
On Tue, Jan 03, 2017 at 03:52:22PM -0800, bors-servo wrote:
> Merged #14827.
> 

Yay! Thanks for this Manish :)

> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/servo/servo/pull/14827#event-910558032