Implement Subresource Integrity
servo/servo pull request #14865
Opened 2017-01-05 16:51 UTC by mrnayak

Implemented response validation part of https://w3c.github.io/webappsec-subresource-integrity/.
Implemented step eighteen of the main fetch. If a request has integrity metadata, then following steps are performed
1) Wait for response body
2)If the response does not have a termination reason and response does not match request’s integrity metadata, set response and internalResponse to a network error.

Dependecy updated: html5ever-atoms from 0.1.2 to 0.1.3. This will not completely fix #14523, It will implement changes related to response validation. Request validation algorithm implementation need CSP.

I did not update any WPT-Test. In my local system I found some assertion issue dependent on order of execution of test-case. 

r? @jdm 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

2017-01-05 16:52 UTC, mrnayak commented
r? @jdm

2017-01-05 18:11 UTC, jdm commented
@bors-servo: try

2017-01-05 18:11 UTC, bors-servo commented
:hourglass: Trying commit a64b964 with merge 2457bcf...

2017-01-05 19:13 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1749)

2017-01-05 19:22 UTC, jdm commented
```
  ▶ TIMEOUT [expected OK] /subresource-integrity/subresource-integrity.sub.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ Unexpected subtest result in /subresource-integrity/subresource-integrity.sub.html:
  └ NOTRUN [expected PASS] Style: Same-origin with correct sha256 and sha512 hash, rel='alternate stylesheet' enabled

  ▶ Unexpected subtest result in /subresource-integrity/subresource-integrity.sub.html:
  └ NOTRUN [expected PASS] Style: Same-origin with incorrect sha256 and sha512 hash, rel='alternate stylesheet' enabled

  ▶ Unexpected subtest result in /subresource-integrity/subresource-integrity.sub.html:
  │ FAIL [expected PASS] Style: <crossorigin='anonymous'> with correct hash, ACAO: *
  │   → assert_unreached: Good load fired error handler. Reached unreachable code
  │ FAIL [expected PASS] Style: <crossorigin='use-credentials'> with correct hash, CORS-eligible
  │   → assert_unreached: Good load fired error handler. Reached unreachable code
  │ 
  │ SRIStyleTest.prototype.execute/</<@http://web-platform.test:8000/subresource-integrity/subresource-integrity.sub.html:132:39
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ SRIStyleTest.prototype.execute/<@http://web-platform.test:8000/subresource-integrity/subresource-integrity.sub.html:132:17

  ▶ Unexpected subtest result in /subresource-integrity/subresource-integrity.sub.html:
  │ FAIL [expected PASS] Script: <crossorigin='use-credentials'> with correct hash, CORS-eligible
  │   → assert_unreached: Good load fired error handler. Reached unreachable code
  │ 
  │ SRIScriptTest.prototype.execute/</<@http://web-platform.test:8000/subresource-integrity/subresource-integrity.sub.html:59:39
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ SRIScriptTest.prototype.execute/<@http://web-platform.test:8000/subresource-integrity/subresource-integrity.sub.html:59:17

  ▶ Unexpected subtest result in /subresource-integrity/subresource-integrity.sub.html:
  │ FAIL [expected PASS] Style: Same-origin with incorrect hash.
  │   → assert_not_equals: got disallowed value "rgb(255, 255, 0)"
  │ FAIL [expected PASS] Style: Same-origin with sha256 match, sha512 mismatch
  │   → assert_not_equals: got disallowed value "rgb(255, 255, 0)"
  │ FAIL [expected PASS] Style: <crossorigin='anonymous'> with incorrect hash, ACAO: *
  │   → assert_not_equals: got disallowed value "rgb(255, 255, 0)"
  │ FAIL [expected PASS] Style: <crossorigin='use-credentials'> with incorrect hash CORS-eligible
  │   → assert_not_equals: got disallowed value "rgb(255, 255, 0)"
  │ FAIL [expected PASS] Style: <crossorigin='anonymous'> with CORS-ineligible resource
  │   → assert_not_equals: got disallowed value "rgb(255, 255, 0)"
  │ FAIL [expected PASS] Style: Cross-origin, not CORS request, with correct hash
  │   → assert_not_equals: got disallowed value "rgb(255, 255, 0)"
  │ FAIL [expected PASS] Style: Cross-origin, not CORS request, with hash mismatch
  │   → assert_not_equals: got disallowed value "rgb(255, 255, 0)"
  │ 
  │ SRIStyleTest.prototype.execute/</<@http://web-platform.test:8000/subresource-integrity/subresource-integrity.sub.html:141:21
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ SRIStyleTest.prototype.execute/<@http://web-platform.test:8000/subresource-integrity/subresource-integrity.sub.html:139:17
```

2017-01-05 19:24 UTC, jdm commented
Let me know if you want me to start reviewing the changes or whether I should wait until you look into the test failure.

2017-01-06 03:10 UTC, mrnayak commented
Thanks Josh, I will work on these test cases today. Will notify you once these gets fixed.

2017-01-06 13:30 UTC, mrnayak commented
None of the test case failures seem to be related to changes.

1) assertion error in 7 test case is due to stylesheet already been loaded in other success test case. I moved all test case expecting assert_not_equals to execute before any success test case.
2) crossorigin has not been implemented in htmllinkelement. So i changed assertion of two test case (`Style: <crossorigin='anonymous'> with correct hash, ACAO: *` and `Style: <crossorigin='use-credentials'> with correct hash, CORS-eligible`) to false.
3) Two alternate stylesheet related tests got timed out since we ignore alternate stylesheet. I have filed an issue #14881. Currently, I have commented these tests.
4) `Script: <crossorigin='use-credentials'> with correct hash, CORS-eligible` failed due to bug in step six of cors_check of `http_loader` . This has been fixed.

@jdm If my above analysis is correct, can you please review the changes.

2017-01-06 15:04 UTC, jdm commented
Rather than modifying the test file, we should be modifying `tests/wpt/metadata/subresource-integrity/subresource-integrity.sub.html.ini` to include the expected failing test results.

2017-01-06 15:05 UTC, jdm commented
Can you explain point 1 in more detail? Why does the order make a difference in the test result?

2017-01-06 15:18 UTC, mrnayak commented
@jdm I am not sure if point 1 is a bug. Our assertion is to validate that div style background color is not yellow.  Moment first success test case executes stylesheet gets loaded and subsequent all assertion fail though we don't load stylesheet again. 

I update `tests/wpt/metadata/subresource-integrity/subresource-integrity.sub.html.ini`, Thanks

2017-01-06 15:32 UTC, jdm commented
I know what the problem is - the test relies on removing the stylesheet from any previous test before starting the new test. However, Servo doesn't support removing stylesheets from the document yet (see #976).

2017-01-06 15:34 UTC, mrnayak commented
So I will modify `subresource-integrity.sub.html.ini` to include these tests as well?

2017-01-06 15:34 UTC, jdm commented
Yes please!

2017-01-06 16:26 UTC, mrnayak commented
@jdm I have done the changes

2017-01-06 18:40 UTC, jdm requested changes
This is really great work! I have a number of small changes, but in general I like the way the code is organized and found the changes easy to read.

2017-01-06 18:40 UTC, jdm commented on tests/unit/net/fetch.rs
> +    assert!(response.internal_response.unwrap().is_network_error());
This assertion won't pass after previous changes I requested. We should be able to remove it.

2017-01-06 18:40 UTC, jdm commented on tests/unit/net/fetch.rs
> +             = "sha384-H8BRh8j48O9oYatfu5AZzq6A9RINhZO5H16dQZngK7T62em8MUt1FLm52t+eX6xO".to_owned();
Let's add a comment about how this was generated.

2017-01-06 18:40 UTC, jdm commented on tests/unit/net/fetch.rs
> +    let do_fetch = |url: ServoUrl| {
This code can be inline instead of using a closure.

2017-01-06 18:40 UTC, jdm commented on tests/unit/net/subresource_integrity.rs
> +fn test_parsed_metadata_without_options() {
Let's add a test for malformed integrity attributes, too. No `-`s, multiple `?`s, etc.

2017-01-06 18:40 UTC, jdm commented on components/net/subresource_integrity.rs
> +    static ref SUPPORTED_ALGORITHM: HashMap<&'static str, usize> = {
We can do this instead:
```rust
const SUPPORTED_ALGORITHM: &'static [&'static str] = [
    "sha256",
    "sha384",
    "sha512",
];
```
and use the position in the array as the priority instead.

2017-01-06 18:40 UTC, jdm commented on components/net/subresource_integrity.rs
> +    let right_priority = SUPPORTED_ALGORITHM.get(hash_func_right).unwrap();
These can use `SUPPORTED_ALGORITHM.position(|s| s == hash_func_left).unwrap()` instead.

2017-01-06 18:40 UTC, jdm commented on components/net/subresource_integrity.rs
> +pub fn get_prioritized_hash_function(hash_func_left: &str, hash_func_right: &str) -> String {
Let's return `Option<&str>` here instead, which will avoid the magic empty string behaviour.

2017-01-06 18:40 UTC, jdm commented on components/net/subresource_integrity.rs
> +    for i in 1..integrity_metadata_list.len() {
```rust
for integrity_metadata in &integrity_metadata_list[1..] {
```

2017-01-06 18:40 UTC, jdm commented on components/net/subresource_integrity.rs
> +                                                                 &*current_algorithm);
nit: indentation.

2017-01-06 18:40 UTC, jdm commented on components/net/subresource_integrity.rs
> +        "".to_owned()
We should probably make this `unreachable!("Tried to calculate digest of incomplete response body")` instead.

2017-01-06 18:40 UTC, jdm commented on components/net/subresource_integrity.rs
> +    if parsed_metadata_list.len() == 0 {
`if parse_metadata_list.is_empty() {`

2017-01-07 09:21 UTC, mrnayak commented
Thanks @jdm I have made changes. Please let me know if there are any other changes.

2017-01-07 14:52 UTC, jdm commented
@bors-servo: r+
Wonderful!

2017-01-07 14:52 UTC, bors-servo commented
:pushpin: Commit 49aff3e has been approved by `jdm`

<!-- @bors-servo r=jdm 49aff3e58efb9a386dbb8dadcc15b9b16701230c -->

2017-01-07 15:38 UTC, bors-servo commented
:hourglass: Testing commit 49aff3e with merge f3fe099...

2017-01-07 16:18 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1761)

2017-01-07 16:24 UTC, mrnayak commented
I had missed updating expectation of two test case :(. I have corrected this.

2017-01-07 18:21 UTC, jdm commented
You will also need to adjust the expectations for /html/dom/interfaces.html, /html/dom/reflection-misc.html, and /html/dom/reflection-metadata.html. I recommend running
`./mach test-wpt tests/wpt/web-platform-test/path/to/test.html --no-pause-after-test --log-raw /tmp/servo.log && ./mach update-wpt /tmp/servo.log` for each of those tests.

2017-01-07 20:01 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14867) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-08 03:24 UTC, mrnayak commented
@jdm Thanks, I have fixed expectations and merge conflicts

2017-01-08 06:18 UTC, jdm commented
@bors-servo: r+

2017-01-08 06:18 UTC, bors-servo commented
:pushpin: Commit a302649 has been approved by `jdm`

<!-- @bors-servo r=jdm a3026499f43860c0d02170534bee20f8f5cc7faa -->

2017-01-08 07:14 UTC, bors-servo commented
:hourglass: Testing commit a302649 with merge f958daf...

2017-01-08 07:28 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/5094)

2017-01-08 07:32 UTC, mrnayak commented
Infra issue?

2017-01-08 07:56 UTC, KiChjang commented
@bors-servo retry

2017-01-08 07:56 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/4794), [arm64](http://build.servo.org/builders/arm64/builds/5000), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1778), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5069), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1775), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/233), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/234) are reusable. Rebuilding only [arm32](http://build.servo.org/builders/arm32/builds/4960), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5094), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1771), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5110), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1814)...

2017-01-08 08:15 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4794), [arm32](http://build.servo.org/builders/arm32/builds/4960), [arm64](http://build.servo.org/builders/arm64/builds/5000), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5095), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1771), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1778), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5069), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5110), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1775), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1814), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/233), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/234)

2017-01-08 08:16 UTC, merged