Handle crossorigin in Link
servo/servo pull request #14940
Opened 2017-01-10 11:12 UTC by mrnayak

Implemented Step three and handled step four of obtain the resource part
of 4.2.4 The link element.
Link to spec : https://html.spec.whatwg.org/multipage/semantics.html#concept-link-obtain

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-01-10 11:12 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmllinkelement.rs, components/script/dom/webidls/HTMLLinkElement.webidl, components/script/stylesheet_loader.rs
 * @kichjang: components/script/dom/htmllinkelement.rs, components/script/dom/webidls/HTMLLinkElement.webidl, components/script/stylesheet_loader.rs

2017-01-10 16:51 UTC, jdm requested changes
I'm glad to see more tests passing. I've made a few suggestions for ways to avoid duplicating code.

2017-01-10 16:51 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +    // https://html.spec.whatwg.org/multipage/#dom-link-crossorigin
This should be using an enumerated getter instead: https://dxr.mozilla.org/servo/rev/124301cf484818a87ab0b3e0c4ef34645be66174/components/script/dom/htmlimageelement.rs#296

2017-01-10 16:51 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +    fn SetCrossOrigin(&self, value: Option<DOMString>) {
This can use `make_setter`: https://dxr.mozilla.org/servo/rev/124301cf484818a87ab0b3e0c4ef34645be66174/components/script/dom/htmlimageelement.rs#298

2017-01-10 16:51 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +        let cors_setting = match self.GetCrossOrigin() {
Let's make a helper function for this and share it with htmlscriptelement.rs.

2017-01-10 16:51 UTC, jdm commented on components/script/stylesheet_loader.rs
> +        self.load(StylesheetContextSource::Import(import.clone()), None, "".to_owned())
Let's add a TODO comment about whether we should use the original loader's CORS setting. I don't find any direction from the specification about it.

2017-01-11 03:57 UTC, mrnayak commented on components/script/dom/htmllinkelement.rs
> +    // https://html.spec.whatwg.org/multipage/#dom-link-crossorigin
Using `enumerated_getter` always returns default crossorigin value as `anonymous`. This value is returned even if request is not a valid crossorigin request. This breaks many test case.

2017-01-11 04:01 UTC, mrnayak commented on components/script/dom/htmllinkelement.rs
> +        let cors_setting = match self.GetCrossOrigin() {
I have added a method in `request.rs` which given a `&str` returns `CorsSettings`. I am not sure if this is good refactoring. Other option could be return `CorsSettings` given `DomString` but I dont know what is the right location for such utility.

2017-01-11 19:32 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14911) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-11 20:07 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +    // https://html.spec.whatwg.org/multipage/#dom-link-crossorigin
You're right. Could we share this code with htmlscriptelement.rs instead of duplicating it, in that case?

2017-01-11 20:15 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +        let cors_setting = match self.GetCrossOrigin() {
I propose the following in element.rs:
```rust
fn reflect_cross_origin_attribute(element: &Element) -> Option<DOMString> {
    // body of HTMLScriptElement::GetCrossOrigin
}

fn cors_setting_for_element(element: &Element) -> Option<CorsSetting> {
    reflect_cross_origin_attribute(element).map(|attr| {
        // body of CorsSetting::from_str_ref
    })
}
```
Then these can be called by both HTMLLinkElement and HTMLScriptElement as necessary.

2017-01-11 20:17 UTC, jdm commented on components/script/dom/htmllinkelement.rs
> +    fn SetCrossOrigin(&self, value: Option<DOMString>) {
My mistake; it can't. Let's add another `set_cross_origin_attribute` helper we can call from both HTMLLinkElement and HTMLScriptElement.

2017-01-13 18:07 UTC, mrnayak commented
@jdm Thanks, I have addressed review comments. Additionally I refactored `HTMLImageElement` to use this updated change.

2017-01-13 18:14 UTC, mrnayak commented on components/script/dom/htmllinkelement.rs
> +    // https://html.spec.whatwg.org/multipage/#dom-link-crossorigin
I have fixed this.

2017-01-13 18:22 UTC, jdm commented
@bors-servo: r+

2017-01-13 18:22 UTC, bors-servo commented
:pushpin: Commit 3d9e44a has been approved by `jdm`

<!-- @bors-servo r=jdm 3d9e44a8c497acd52b428dd02062a9c55a2efafc -->

2017-01-13 18:22 UTC, bors-servo commented
:hourglass: Testing commit 3d9e44a with merge 9afd960...

2017-01-13 19:13 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4888), [arm32](http://build.servo.org/builders/arm32/builds/5051), [arm64](http://build.servo.org/builders/arm64/builds/5096), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5196), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1868), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1878), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5164), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5206), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1870), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1913), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/332), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/334)

2017-01-13 19:13 UTC, merged