Implemented display: inline-flex
servo/servo pull request #14978
Opened 2017-01-12 06:41 UTC by shinglyu

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #14685 (github issue number if applicable).

- [x] There are tests for these changes

2017-01-12 06:44 UTC, shinglyu commented on components/layout/construct.rs
> +    fn build_fragment_for_inline_flex(&mut self, node: &ConcreteThreadSafeLayoutNode)
This function should probably reuse `build_fragment_for_inline_block`, but I'm not sure if we want to have a `build_fragment_for_inline_block_or_inline_flex` and pass a flag into it, or should we have two functions and extract the shared part into a helper function.

2017-01-12 06:45 UTC, shinglyu commented
cc @stshine

2017-01-12 07:39 UTC, shinglyu commented
r? anyone? 
@highfive where are you?

2017-01-12 08:28 UTC, stshine commented
r? @mbrubeck or @pcwalton or @notriddle 
I am busy with my job, will try to look later.

2017-01-12 22:21 UTC, mbrubeck requested changes

2017-01-12 22:21 UTC, mbrubeck commented on components/layout/inline.rs
> +                (display::T::inline_flex, vertical_align::T::top) |
`top` should be `bottom` here

2017-01-13 10:47 UTC, stshine reviewed
Disclaimer: I do not have access as a reviewer.

2017-01-13 10:47 UTC, stshine commented on components/layout/construct.rs
> +    fn build_fragment_for_inline_flex(&mut self, node: &ConcreteThreadSafeLayoutNode)
Yeah, I agree add a flag should be a better solution.

2017-01-13 10:47 UTC, stshine commented on components/layout/construct.rs
> +    fn build_fragment_for_inline_flex(&mut self, node: &ConcreteThreadSafeLayoutNode)
Yeah, I agree add a flag should be a better solution.

2017-01-13 10:47 UTC, stshine commented on components/style/properties/properties.mako.rs
>          computed_values::display::T::grid |
Why not also fix `inline-grid` for stylo?

2017-01-13 10:47 UTC, stshine commented on tests/wpt/metadata-css/css-flexbox-1_dev/html/flex-flexitem-percentage-prescation.htm.ini
> -[flex-flexitem-percentage-prescation.htm]
This test actually does not pass.

2017-01-13 18:36 UTC, KiChjang commented on components/layout/construct.rs
> +    fn build_fragment_for_inline_flex(&mut self, node: &ConcreteThreadSafeLayoutNode)
Also, small nit: the `Shared code` comment needs another slash in front of it to be a doc comment.

2017-01-18 03:31 UTC, shinglyu commented on components/style/properties/properties.mako.rs
>          computed_values::display::T::grid |
fixed!

2017-01-18 03:32 UTC, shinglyu commented
Let me know when it's ready for squashing.

2017-01-18 05:08 UTC, stshine commented
Looks good to me, nice work :-)
Your need an actual reviewer for the review process.

2017-01-19 18:07 UTC, notriddle commented
Squash this, then I'll r+ it.

2017-01-23 02:31 UTC, shinglyu commented
@notriddle Squahed. Thank you!

2017-01-23 03:46 UTC, notriddle commented
@bors-servo r+

2017-01-23 03:46 UTC, bors-servo commented
:pushpin: Commit e31ee04 has been approved by `notriddle`

<!-- @bors-servo r=notriddle e31ee04dad52d80af33762aad13d500aff087041 -->

2017-01-23 03:46 UTC, bors-servo commented
:hourglass: Testing commit e31ee04 with merge 9aa4848...

2017-01-23 03:52 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2003)

2017-01-23 03:57 UTC, stshine commented
@bors-servo retry

internal compiler error

2017-01-23 03:57 UTC, bors-servo commented
:hourglass: Testing commit e31ee04 with merge c75946c...

2017-01-23 05:16 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5004), [arm32](http://build.servo.org/builders/arm32/builds/5175), [arm64](http://build.servo.org/builders/arm64/builds/5219), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5320), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1994), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2004), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5290), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5330), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1992), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2038), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/458), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/461)

2017-01-23 05:16 UTC, merged