Pass typed array structs as arguments to binding methods.
servo/servo pull request #15007
Opened 2017-01-13 09:33 UTC by Ms2ger

WIP to check if anyone has thoughts on the design.

2017-01-13 09:33 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/testbinding.rs, components/script/dom/webidls/TestBinding.webidl
 * @kichjang: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/testbinding.rs, components/script/dom/webidls/TestBinding.webidl

2017-01-13 09:33 UTC, Ms2ger commented
CC @jdm @nox

2017-01-13 15:23 UTC, jdm commented
I spent a while looking through it, and it seems reasonable. I do not have any alternatives to propose.

2017-01-17 10:28 UTC, Ms2ger commented
Ready for review

2017-01-18 13:44 UTC, jdm commented
r? @jdm

2017-01-19 14:14 UTC, jdm requested changes
As written, these changes look fine. However, I am concerned that if we don't support unions in this PR as well we may need to redesign it later on.

2017-01-19 14:14 UTC, jdm commented on components/script/dom/bindings/codegen/CodegenRust.py
> +    assert not info.needsRooting
We should support unions containing typed arrays; various network and webgl specs require them.

2017-01-19 14:14 UTC, jdm commented on components/script/dom/bindings/codegen/CodegenRust.py
> +                    assert not info.needsRooting
Does this mean we don't support overloading that involves typed arrays? Will this restriction make https://dxr.mozilla.org/servo/rev/b8df502491b880cb942badee4ddbf7ec65b174fb/components/script/dom/webidls/WebGLRenderingContext.webidl#491-505 impossible?

2017-01-19 14:14 UTC, jdm commented on components/script/dom/bindings/codegen/CodegenRust.py
> +        assert not any(i.needsRooting for (_, i) in self.memberInfo)
If RsaHashedKeyAlgorithm is the only code that would use this right now, I'm not bothered by this restriction.

2017-01-19 14:28 UTC, jdm commented on components/script/dom/bindings/codegen/CodegenRust.py
> +                    assert not info.needsRooting
Actually, a more immediately applicable example is WebSocket::send with ArrayBuffer/ArrayBufferView overloads.

2017-02-16 11:00 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15544) made this pull request unmergeable. Please resolve the merge conflicts.

2017-03-03 11:30 UTC, Ms2ger commented
For the record, I'm trying to come up with a more general approach that supports unions.

2017-06-08 18:35 UTC, jdm commented
Closing until this work is taken up once more.

2017-06-08 18:35 UTC, closed without merging