Max session fix
servo/servo pull request #15026
Opened 2017-01-14 20:22 UTC by tydus101

Converted document discarding from an opt into a pref. Updated testing docs and changed all uses to pref api. 

---

- [ X] `./mach build -d` does not report any errors
- [ X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #14960 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ X] These changes do not require tests because current test suite is sufficient

2017-01-14 20:22 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @jdm (or someone else) soon.

2017-01-14 20:22 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/constellation.rs

2017-01-14 20:32 UTC, jdm requested changes
Let's squash all the commits into one, as well.

2017-01-14 20:32 UTC, jdm commented on resources/prefs.json
> +  "session_history.max_length":20,
Let's use `session-history.max-length` to be consistent with other preference names. Also, add a space after `:`.

2017-01-14 20:40 UTC, tydus101 commented on resources/prefs.json
> +  "session_history.max_length":20,
Oops, overlooked that. Thanks!

2017-01-14 20:56 UTC, jdm requested changes

2017-01-14 20:56 UTC, jdm commented on components/constellation/constellation.rs
> +                .checked_sub(PREFS.get("session_history.max_length").as_u64().unwrap_or(20) as usize)
This needs to be renamed to match now.

2017-01-14 20:56 UTC, jdm commented
@bors-servo: r+

2017-01-14 20:56 UTC, bors-servo commented
:pushpin: Commit 740e279 has been approved by `jdm`

<!-- @bors-servo r=jdm 740e279d34b45959a82b56d16dc3e642f3e5e266 -->

2017-01-14 20:56 UTC, bors-servo commented
:hourglass: Testing commit 740e279 with merge 9e2fba3...

2017-01-14 21:53 UTC, cbrewster commented on resources/prefs.json
> +  "session-history.max-length":20,
nit: space between `:` and `20`

2017-01-14 23:08 UTC, jdm commented
@bors-servo: r+

2017-01-14 23:08 UTC, bors-servo commented
:pushpin: Commit 0fae39f has been approved by `jdm`

<!-- @bors-servo r=jdm 0fae39f468e84678c9bca27cd739a8a26f8bb5ae -->

2017-01-14 23:08 UTC, bors-servo commented
:hourglass: Testing commit 0fae39f with merge d09bf70...

2017-01-15 00:24 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4905), [arm32](http://build.servo.org/builders/arm32/builds/5070), [arm64](http://build.servo.org/builders/arm64/builds/5115), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5215), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1887), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1897), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5183), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5225), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1888), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1932), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/351), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/353)

2017-01-15 00:24 UTC, merged