Return the intrinsic image dimension when the image is not rendered
servo/servo pull request #15053
Opened 2017-01-16 23:39 UTC by emilio

See individual commits for details.

r? @jdm

2017-01-16 23:39 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/document.rs, components/script/dom/node.rs, components/script/dom/element.rs, components/script/dom/htmlanchorelement.rs, components/script/dom/htmlimageelement.rs, components/script/dom/window.rs, components/script_layout_interface/rpc.rs
 * @kichjang: components/script/dom/document.rs, components/script/dom/node.rs, components/script/dom/element.rs, components/script/dom/htmlanchorelement.rs, components/script/dom/htmlimageelement.rs, components/script/dom/window.rs, components/script_layout_interface/rpc.rs

2017-01-16 23:41 UTC, emilio commented
@bors-servo try

2017-01-16 23:41 UTC, bors-servo commented
:hourglass: Trying commit 3b897af with merge 5ab4733...

2017-01-17 00:14 UTC, anholt commented
Combined with a series I'm working on, this fixes `tex-image-and-sub-image-2d-with-image.html`

2017-01-17 00:34 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4923), [arm32](http://build.servo.org/builders/arm32/builds/5086), [arm64](http://build.servo.org/builders/arm64/builds/5131), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5231), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1903), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1913), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5199), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5241), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1904), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1948), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/367), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/369)

2017-01-17 00:36 UTC, emilio commented
I'd hoped this would have been caught for at least one other test :(

This is a test that could be upstreamed to WPT, cc #15058

2017-01-18 14:06 UTC, jdm requested changes

2017-01-18 14:06 UTC, jdm commented on components/script/dom/htmlanchorelement.rs
> +                // (unwrap the content box)?
Pretty sure this could break in the present of `img.click()` when it's not rendered.

2017-01-18 14:06 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img_width_height_not_rendered.html
> +<title>Image intrinsic dimensions are returned if the image isn't rendered</title>
Assuming this passes in Firefox and Chrome, let's move it to web-platform-tests/html/semantics/embedded-content/the-img-element/ instead.

2017-01-18 14:07 UTC, jdm commented
I forgot to mention how nice it was to read the sequence of commits. This was a very enjoyable PR to review!

2017-01-18 15:55 UTC, emilio commented on tests/wpt/mozilla/tests/mozilla/img_width_height_not_rendered.html
> +<title>Image intrinsic dimensions are returned if the image isn't rendered</title>
Done

2017-01-18 15:56 UTC, emilio commented on components/script/dom/htmlanchorelement.rs
> +                // (unwrap the content box)?
You're right, of course, I thought the activation behavior didn't run in those cases.

2017-01-18 16:06 UTC, jdm commented
@bors-servo: r+

2017-01-18 16:06 UTC, bors-servo commented
:pushpin: Commit 127da41 has been approved by `jdm`

<!-- @bors-servo r=jdm 127da41a2a2eb393b8497e178a6c28bc6ee3129e -->

2017-01-18 16:43 UTC, bors-servo commented
:hourglass: Testing commit 127da41 with merge ba59ee6...

2017-01-18 18:03 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/4952), [arm32](http://build.servo.org/builders/arm32/builds/5121), [arm64](http://build.servo.org/builders/arm64/builds/5165), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5266), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/1938), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/1948), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5234), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5276), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/1938), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/1983), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/402), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/404)

2017-01-18 18:03 UTC, merged