Allow windows to share browsing contextw.
servo/servo pull request #15120
Opened 2017-01-19 22:18 UTC by asajeffrey

This PR allows different `Window` objects in the same browsing context to share a `BrowsingContext` object.

SpiderMonkey requires a `WindowProxy` object to be in the same compartment as its `Window`, so when a `WindowProxy` changes `Window`, we have to brain-transplant it. In turn this requires the reflector of a `BrowsingContext` to be mutable.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13608 and #14843 
- [X] These changes do not require tests because an existing test catches this (`/html/browsers/the-window-object/Window-document.html` is now `PASS`)

2017-01-19 22:18 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/document.rs, components/script/dom/node.rs, components/script/dom/browsingcontext.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/xmldocument.rs, components/script/dom/servoparser/mod.rs, components/script/script_thread.rs, components/script/dom/domparser.rs, components/script/dom/window.rs, components/script/dom/domimplementation.rs
 * @kichjang: components/script/dom/document.rs, components/script/dom/node.rs, components/script/dom/browsingcontext.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/xmldocument.rs, components/script/dom/servoparser/mod.rs, components/script/script_thread.rs, components/script/dom/domparser.rs, components/script/dom/window.rs, components/script/dom/domimplementation.rs

2017-01-19 22:18 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-01-19 22:19 UTC, asajeffrey commented
r? @jdm

2017-01-19 22:30 UTC, jdm commented
I think my changes in #15118 may make some of the mutable Reflector changes unnecessary (particularly if we modify rust-mozjs to make Heap::set not require &mut self).

2017-01-19 22:34 UTC, asajeffrey commented
You're right, we could use `reflector.rootable()` to set the reflector.

2017-01-20 15:54 UTC, asajeffrey commented
@jdm: I used `reflector.rootable()` to set the reflector, rather than having the reflector inside a `RefCell`.

2017-01-20 16:00 UTC, asajeffrey commented
@cbrewster does this PR fix the problems you were having with webstorage tests? http://logs.glob.uno/?c=mozilla%23servo&s=11+Jan+2017&e=11+Jan+2017#c591494

2017-01-20 16:01 UTC, asajeffrey commented
For the record, here's the IRC conversation I had with @bzbarsky about brain transplanting window proxy objects: http://logs.glob.uno/?c=mozilla%23jsapi&s=19+Jan+2017&e=19+Jan+2017#c819204

2017-01-23 12:11 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15136) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-24 16:59 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15176) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-26 23:49 UTC, jdm requested changes

2017-01-26 23:49 UTC, jdm commented on components/script/dom/browsingcontext.rs
> +            // Create a new reflector.
`Update the reflector.`

2017-01-26 23:49 UTC, jdm commented on components/script/dom/browsingcontext.rs
> +            // Set the window proxy.
This comment is redundant given the function name. How about `Notify the JS engine that the window proxy has changed.`?

2017-01-26 23:49 UTC, jdm commented on components/script/dom/document.rs
>      /// https://html.spec.whatwg.org/multipage/#concept-document-bc
This comment doesn't belong any more.

2017-01-26 23:49 UTC, jdm commented on components/script/dom/document.rs
> +               has_browsing_context: bool,
I lean towards a self-documenting enum here, given that every caller passes a boolean literal.

2017-01-26 23:49 UTC, jdm commented on components/script/script_thread.rs
> +    /// TODO: this map grows, but never shrinks.
We should file an issue about this and mention it here.

2017-01-27 03:54 UTC, asajeffrey commented on components/script/dom/browsingcontext.rs
> +            // Set the window proxy.
Done

2017-01-27 03:54 UTC, asajeffrey commented on components/script/dom/browsingcontext.rs
> +            // Create a new reflector.
Oops. Done.

2017-01-27 03:57 UTC, asajeffrey commented on components/script/dom/document.rs
>      /// https://html.spec.whatwg.org/multipage/#concept-document-bc
Oops. Done.

2017-01-27 03:59 UTC, asajeffrey commented on components/script/dom/document.rs
> +               has_browsing_context: bool,
Done.

2017-01-27 04:02 UTC, asajeffrey commented on components/script/script_thread.rs
> +    /// TODO: this map grows, but never shrinks.
Done. It's #15258.

2017-01-27 04:35 UTC, jdm approved these changes

2017-01-27 04:37 UTC, asajeffrey commented
Squashed. @bors-servo: r=jdm

2017-01-27 04:37 UTC, bors-servo commented
:pushpin: Commit c69a4d5 has been approved by `jdm`

<!-- @bors-servo r=jdm c69a4d5a31038c67b7f98b49807ed83512103e3b -->

2017-01-27 05:31 UTC, bors-servo commented
:hourglass: Testing commit c69a4d5 with merge e1bc7e0...

2017-01-27 05:40 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5372)

2017-01-27 05:42 UTC, cbrewster commented
```
error[E0308]: mismatched types
   --> /Users/servo/buildbot/slave/mac-dev-unit/build/components/script/dom/browsingcontext.rs:143:42
    |
143 |             *self.reflector.rootable() = new_window_proxy.get();
    |                                          ^^^^^^^^^^^^^^^^^^^^^^ expected struct `js::jsapi::Heap`, found *-ptr
    |
    = note: expected type `js::jsapi::Heap<*mut js::jsapi::JSObject>`
               found type `*mut js::jsapi::JSObject`
```

2017-01-27 13:15 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15220) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-27 15:23 UTC, asajeffrey commented
Oh rats, `reflector.rootable()` now returns a `&Heap<*mut JSObject>` rather than a `*mut *mut JSObject`.

@jdm should I go back to `Reflector` being a `RefCell`? Or is there a better way to update the reflector?

2017-01-27 15:42 UTC, jdm commented
It's not clear to me why Heap::set requires `&mut self`. Without that restriction you wouldn't have any problems.

2017-01-27 15:43 UTC, jdm commented
I propose making Heap::set take &self. It stores an UnsafeCell internally, and I think it was just following the pattern of the other mutable types in https://github.com/servo/rust-mozjs/blob/master/src/rust.rs.

2017-01-27 16:18 UTC, asajeffrey commented
OK,. Slightly annoyingly this means a PR to rust-mozjs, but it's probably the easiest solution.

2017-01-27 17:55 UTC, asajeffrey commented
Filed https://github.com/servo/rust-mozjs/pull/328.

2017-01-27 18:50 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15262) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-27 20:05 UTC, asajeffrey commented
@bors-servo r=jdm

2017-01-27 20:05 UTC, bors-servo commented
:pushpin: Commit 2e863a9 has been approved by `jdm`

<!-- @bors-servo r=jdm 2e863a9ab762f5a355973031c2645623735c7dc8 -->

2017-01-27 20:58 UTC, bors-servo commented
:hourglass: Testing commit 2e863a9 with merge 4f1d6ba...

2017-01-27 21:08 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5391)

2017-01-27 21:10 UTC, asajeffrey commented
That would be caused by it picking up the old version of rust-mozjs. Wait for https://github.com/servo/rust-mozjs/pull/329 to land...

2017-01-28 01:27 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #14971) made this pull request unmergeable. Please resolve the merge conflicts.

2017-01-29 03:58 UTC, asajeffrey commented
https://github.com/servo/rust-mozjs/pull/329 has landed. Rebased. @bors-servo: r=jdm

2017-01-29 03:58 UTC, bors-servo commented
:pushpin: Commit 403499a has been approved by `jdm`

<!-- @bors-servo r=jdm 403499a9d5aa3749571ef960f9ab909855570a6f -->

2017-01-29 04:35 UTC, bors-servo commented
:hourglass: Testing commit 403499a with merge 67c1826...

2017-01-29 05:24 UTC, merged