Implement microtask checkpoints
servo/servo pull request #15189
Opened 2017-01-25 00:03 UTC by jdm

This generalizes the work previously done for Promise job callbacks. There is now a microtask queue that correctly processes all queued microtasks after each turn of the event loop, as well as after a scripted callback finishes executing, and after a classic script executes.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #4283
- [X] There are tests for these changes

2017-01-25 00:03 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/lib.rs, components/script/microtask.rs, components/script/dom/globalscope.rs, components/script/dom/workerglobalscope.rs, components/script/dom/bindings/settings_stack.rs, components/script/dom/dedicatedworkerglobalscope.rs, components/script/dom/htmlscriptelement.rs, components/script/script_thread.rs, components/script/script_runtime.rs, components/script/dom/serviceworkerglobalscope.rs
 * @kichjang: components/script/lib.rs, components/script/microtask.rs, components/script/dom/globalscope.rs, components/script/dom/workerglobalscope.rs, components/script/dom/bindings/settings_stack.rs, components/script/dom/dedicatedworkerglobalscope.rs, components/script/dom/htmlscriptelement.rs, components/script/script_thread.rs, components/script/script_runtime.rs, components/script/dom/serviceworkerglobalscope.rs

2017-01-25 00:14 UTC, nox reviewed
Just some comments.

2017-01-25 00:14 UTC, nox commented on components/script/dom/bindings/settings_stack.rs
> +                       &*self.global as *const GlobalScope,
I think all DOM structs implement `PartialEq` with pointer equality.

2017-01-25 00:14 UTC, nox commented on components/script/microtask.rs
> +    pub fn new() -> MicrotaskQueue {
You could also use `Default`.

2017-01-25 00:14 UTC, nox commented on components/script/microtask.rs
> +            // `flushing_queue` is a static snapshot during this checkpoint.
Why not just replace by an empty vector, like we do in `Document::run_the_animation_frame_callbacks`?

2017-01-25 00:14 UTC, nox commented on components/script/script_thread.rs
> +            let script_thread = root.as_ref().unwrap();
I think this was reverted and you need to rebase. :(

2017-01-25 00:17 UTC, Manishearth commented
r? @nox

2017-01-25 14:11 UTC, nox requested changes
Very nice work.

2017-01-25 14:11 UTC, nox commented on components/script/dom/dedicatedworkerglobalscope.rs
> +                    global.upcast::<WorkerGlobalScope>().perform_a_microtask_checkpoint();
Could you put a spec link as to why we perform a checkpoint here?

2017-01-25 14:11 UTC, nox commented on components/script/dom/globalscope.rs
> +    pub fn perform_a_microtask_checkpoint(&self) {
Spec link.

2017-01-25 14:11 UTC, nox commented on components/script/dom/globalscope.rs
> +    pub fn enqueue_microtask(&self, job: Microtask) {
Spec link.

2017-01-25 14:11 UTC, nox commented on components/script/dom/serviceworkerglobalscope.rs
> +                    global.upcast::<WorkerGlobalScope>().perform_a_microtask_checkpoint();
Spec link?

2017-01-25 14:11 UTC, nox commented on components/script/dom/workerglobalscope.rs
> +    pub fn enqueue_microtask(&self, job: Microtask) {
Spec link.

2017-01-25 14:11 UTC, nox commented on components/script/dom/workerglobalscope.rs
> +    pub fn perform_a_microtask_checkpoint(&self) {
Spec link.

2017-01-25 14:11 UTC, nox commented on components/script/microtask.rs
> +pub struct MicrotaskQueue {
Could you put this first, then `Microtask`, then `EnqueuedPromiseCallback`?

2017-01-25 14:11 UTC, Ms2ger commented on components/script/dom/bindings/settings_stack.rs
> +        if !thread::panicking() && incumbent_global().is_none() {
I don't know that this check is correct, mostly because I don't know what the correct check is.

2017-01-25 14:11 UTC, Ms2ger commented on components/script/dom/htmlscriptelement.rs
> +        if !document.is_fully_active() || !document.is_scripting_enabled() {
Do these additional checks make any tests pass?

2017-01-25 14:11 UTC, Ms2ger commented on components/script/microtask.rs
> +use dom::bindings::callback::ExceptionHandling;
A line of top-level documentation here, please.

2017-01-25 14:11 UTC, Ms2ger commented on components/script/microtask.rs
> +    /// a microtask checkpoint.
Add a note that this would be a local variable if it wasn't for rooting concerns.

2017-01-25 14:16 UTC, jdm commented
@bors-servo: try

2017-01-25 14:16 UTC, bors-servo commented
:hourglass: Trying commit 1da28b5 with merge 534ca6d...

2017-01-25 14:23 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5344)

2017-01-25 14:28 UTC, jdm commented on components/script/dom/bindings/settings_stack.rs
> +                       &*self.global as *const GlobalScope,
The compiler complains that &GlobalScope doesn't implement the Debug trait if I get rid of the pointer casts.

2017-01-25 14:29 UTC, nox commented on components/script/dom/bindings/settings_stack.rs
> +                       &*self.global as *const GlobalScope,
Oh I see. I guess that's ok. Alternatively you can use `assert!(... == ...);` but that reports a less detailed panic.

2017-01-25 14:41 UTC, jdm commented
@bors-servo: try

2017-01-25 14:41 UTC, bors-servo commented
:hourglass: Trying commit fe15278 with merge 5cad7fa...

2017-01-25 14:45 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/5372)

2017-01-25 14:47 UTC, jdm commented
@bors-servo: try

2017-01-25 14:47 UTC, bors-servo commented
:hourglass: Trying commit dc0165a with merge af725e3...

2017-01-25 15:24 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2062)

2017-01-25 15:26 UTC, jdm commented
<details>

```
  ▶ TIMEOUT [expected OK] /XMLHttpRequest/send-entity-body-document.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ CRASH [expected OK] /fetch/api/basic/accept-header-worker.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ called `Option::unwrap()` on a `None` value (thread WebWorker for http://web-platform.test:8000/fetch/api/basic/accept-header.js, at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:323)
  │ stack backtrace:
  │    0:     0x7f29c97a73dd - backtrace::backtrace::trace::h3daaf829744ddab9
  │    1:     0x7f29c97a7ad2 - backtrace::capture::Backtrace::new::hd6fb6e83f9059b0d
  │    2:     0x7f29c7f8c707 - servo::main::{{closure}}::h2a03f49e668fc733
  │    3:     0x7f29c9e20e88 - std::panicking::rust_panic_with_hook
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:556
  │    4:     0x7f29c9e20d54 - std::panicking::begin_panic<collections::string::String>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
  │    5:     0x7f29c9e20c79 - std::panicking::begin_panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
  │    6:     0x7f29c9e20c07 - std::panicking::rust_begin_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
  │    7:     0x7f29c9e4e27d - core::panicking::panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
  │    8:     0x7f29c9e4e1b4 - core::panicking::panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  │    9:     0x7f29c86bb93a - <script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope as script::dom::bindings::codegen::Bindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeMethods>::PostMessage::hc505b6a095572763
  │   10:     0x7f29c847b630 - std::panicking::try::do_call::ha0f1a4b739b956b5
  │   11:     0x7f29c9e27dca - panic_unwind::__rust_maybe_catch_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  │   12:     0x7f29c898303b - script::dom::bindings::codegen::Bindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeBinding::postMessage::hc9cbbf1b15eaf0d3
  │   13:     0x7f29c8b87bb4 - CallJitMethodOp
  │   14:     0x7f29c865cd34 - script::dom::bindings::utils::generic_call::h3881052955259884
  │   15:     0x7f29ca7ce82c - <unknown>
  │ ERROR:servo: called `Option::unwrap()` on a `None` value
  │ Pipeline failed in hard-fail mode.  Crashing!
  │ thread panicked while processing panic. aborting.
  └ thread panicked while processing panic. aborting.

  ▶ CRASH [expected OK] /fetch/api/basic/mode-same-origin-worker.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ called `Option::unwrap()` on a `None` value (thread WebWorker for http://web-platform.test:8000/fetch/api/basic/mode-same-origin.js, at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:323)
  │ stack backtrace:
  │    0:     0x7fbb573023dd - backtrace::backtrace::trace::h3daaf829744ddab9
  │    1:     0x7fbb57302ad2 - backtrace::capture::Backtrace::new::hd6fb6e83f9059b0d
  │    2:     0x7fbb55ae7707 - servo::main::{{closure}}::h2a03f49e668fc733
  │    3:     0x7fbb5797be88 - std::panicking::rust_panic_with_hook
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:556
  │    4:     0x7fbb5797bd54 - std::panicking::begin_panic<collections::string::String>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
  │    5:     0x7fbb5797bc79 - std::panicking::begin_panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
  │    6:     0x7fbb5797bc07 - std::panicking::rust_begin_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
  │    7:     0x7fbb579a927d - core::panicking::panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
  │    8:     0x7fbb579a91b4 - core::panicking::panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  │    9:     0x7fbb5621693a - <script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope as script::dom::bindings::codegen::Bindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeMethods>::PostMessage::hc505b6a095572763
  │   10:     0x7fbb55fd6630 - std::panicking::try::do_call::ha0f1a4b739b956b5
  │   11:     0x7fbb57982dca - panic_unwind::__rust_maybe_catch_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  │   12:     0x7fbb564de03b - script::dom::bindings::codegen::Bindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeBinding::postMessage::hc9cbbf1b15eaf0d3
  │   13:     0x7fbb566e2bb4 - CallJitMethodOp
  │   14:     0x7fbb561b7d34 - script::dom::bindings::utils::generic_call::h3881052955259884
  │   15:     0x7fbb5842d82c - <unknown>
  │ ERROR:servo: called `Option::unwrap()` on a `None` value
  └ Pipeline failed in hard-fail mode.  Crashing!

  ▶ CRASH [expected OK] /fetch/api/basic/integrity-worker.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ called `Option::unwrap()` on a `None` value (thread WebWorker for http://web-platform.test:8000/fetch/api/basic/integrity.js?pipe=sub, at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:323)
  │ stack backtrace:
  │    0:     0x7f933222c3dd - backtrace::backtrace::trace::h3daaf829744ddab9
  │    1:     0x7f933222cad2 - backtrace::capture::Backtrace::new::hd6fb6e83f9059b0d
  │    2:     0x7f9330a11707 - servo::main::{{closure}}::h2a03f49e668fc733
  │    3:     0x7f93328a5e88 - std::panicking::rust_panic_with_hook
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:556
  │    4:     0x7f93328a5d54 - std::panicking::begin_panic<collections::string::String>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
  │    5:     0x7f93328a5c79 - std::panicking::begin_panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
  │    6:     0x7f93328a5c07 - std::panicking::rust_begin_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
  │    7:     0x7f93328d327d - core::panicking::panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
  │    8:     0x7f93328d31b4 - core::panicking::panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  │    9:     0x7f933114093a - <script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope as script::dom::bindings::codegen::Bindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeMethods>::PostMessage::hc505b6a095572763
  │   10:     0x7f9330f00630 - std::panicking::try::do_call::ha0f1a4b739b956b5
  │   11:    [...]

2017-01-27 11:24 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15242) made this pull request unmergeable. Please resolve the merge conflicts.

2017-02-01 17:56 UTC, jdm commented
@creativcoder You may be interested in the changes I made to the ServiceWorker job queue implementation.

2017-02-01 17:56 UTC, jdm commented
Review comments addressed. All tests pass now.

2017-02-02 07:13 UTC, creativcoder commented
@jdm Thanks for notifying. :) I went through it. I'm currently working on remaining part of the Update algorithm, to fetch a service worker script and update it and the rest. Guess, they will be needing changes accordingly.

2017-02-03 13:27 UTC, nox commented
@jdm You said you don't want to put links on `GlobalScope` methods, which I can understand, but in the end none of the `perform_a_microtask_checkpoint` methods have a spec link in your PR.

2017-02-03 14:13 UTC, jdm commented
Because they both delegate to a single method that has the link instead. Adding the link to places like that feels confusing to me.

2017-02-03 15:10 UTC, nox commented
Fair enough.

@bors-servo r+

2017-02-03 15:10 UTC, bors-servo commented
:pushpin: Commit 60d1717 has been approved by `nox`

<!-- @bors-servo r=nox 60d1717eca5469c8203861c17ad139160e8c1424 -->

2017-02-03 15:53 UTC, bors-servo commented
:hourglass: Testing commit 60d1717 with merge cbcafd1...

2017-02-03 16:48 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5193), [arm32](http://build.servo.org/builders/arm32/builds/5381), [arm64](http://build.servo.org/builders/arm64/builds/5421), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5524), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2206), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2222), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5503), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5538), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2195), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2252), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/663), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/667)
Approved by: nox
Pushing cbcafd18f4cb5973948b081b4c104d99735e2789 to master...

2017-02-03 16:48 UTC, merged