Permissions API and WebBluetooth integration
servo/servo pull request #15314
Opened 2017-01-31 15:17 UTC by dati91

This implements the [Permissions API](https://w3c.github.io/permissions/) spec.
Also includes the WebBluetooth related implementation for this.

There are some know issues:
[ ] If the descriptor name is invalid [this](https://gist.github.com/dati91/7a6a0a563d90f49ba5a351e48c5b626b#file-permissionstatusbindings-rs-L323) will throw an error, rather that return it and we could handle it.
[ ] The [environment settings object](https://html.spec.whatwg.org/multipage/webappapis.html#environment-settings-object) is not implemented in servo and the spec rely on it.
[ ] There is a popup in the implementation which prevent us to add wpt test, we should figure out a way to make it work
[ ] The allowedDevice's allowed_services attribute is not used in our implementation, because we store these in the lower level, not in the dom side.
[ ] We think the bluetooth revoke function will need some more work, but the problem is the spec needs clarifications on that part.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because

2017-01-31 15:17 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/navigator.rs, components/script/dom/permissionstatus.rs, components/script/dom/mod.rs, components/script/dom/webidls/PermissionStatus.webidl, components/script/dom/bluetoothdevice.rs, components/script/dom/bluetoothremotegattserver.rs, components/script/dom/webidls/Permissions.webidl, components/script/dom/bluetoothpermissionresult.rs, components/script/dom/webidls/Navigator.webidl, components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/webidls/BluetoothDevice.webidl, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/bluetooth.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs, components/script/dom/webidls/BluetoothPermissionResult.webidl, components/script/dom/permissions.rs, components/script/dom/webidls/WorkerNavigator.webidl, components/script/dom/workernavigator.rs
 * @kichjang: components/script/dom/navigator.rs, components/script/dom/permissionstatus.rs, components/script/dom/mod.rs, components/script/dom/webidls/PermissionStatus.webidl, components/script/dom/bluetoothdevice.rs, components/script/dom/bluetoothremotegattserver.rs, components/script/dom/webidls/Permissions.webidl, components/script/dom/bluetoothpermissionresult.rs, components/script/dom/webidls/Navigator.webidl, components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/webidls/BluetoothDevice.webidl, components/script/dom/bluetoothremotegattservice.rs, components/script/dom/bluetooth.rs, components/script/dom/bluetoothremotegattdescriptor.rs, components/script/dom/bluetoothremotegattcharacteristic.rs, components/script/dom/webidls/BluetoothPermissionResult.webidl, components/script/dom/permissions.rs, components/script/dom/webidls/WorkerNavigator.webidl, components/script/dom/workernavigator.rs

2017-01-31 15:17 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-01-31 15:17 UTC, dati91 commented
r? @jdm

2017-01-31 15:43 UTC, Ms2ger commented on components/script/dom/bluetooth.rs
> +        // TODO: `environment settings object` is not implemented in Servo yet.
The "relevant global object" for *status* is just `status.global()` in Servo.

2017-01-31 15:48 UTC, dati91 commented on components/script/dom/bluetooth.rs
> +        // TODO: `environment settings object` is not implemented in Servo yet.
Great! I based this comment on [this](https://github.com/servo/servo/blob/master/components/script/dom/request.rs#L139) line. Maybe next time i shouldn't give up on searching that early. :)

2017-02-03 13:10 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15366) made this pull request unmergeable. Please resolve the merge conflicts.

2017-02-04 09:44 UTC, zakorgy commented on components/script/dom/permissions.rs
> +    PermissionState::Denied;
Remove the `;` from the end of line. It causes the build error on windows: https://ci.appveyor.com/project/servo/servo/build/1.0.13207/job/f0pbavepdah2u611#L619

2017-02-09 22:20 UTC, jdm requested changes
Sorry for the delay! I've been really busy and there was a _lot_ of code to review.

2017-02-09 22:20 UTC, jdm commented on components/script/dom/permissions.rs
> +        // Without these the remaining steps can't be implemented properly.
We can use `GlobalScope::current()` to give us the equivalent of the `current environment settings object`.

2017-02-09 22:20 UTC, jdm commented on components/script/dom/permissions.rs
> +pub fn get_descriptor_permission_state(permission_name: PermissionName ,
No need for this to be public.

2017-02-09 22:20 UTC, jdm commented on components/script/dom/permissions.rs
> +                                       _env_settings_obj: Option<*mut JSObject>)
This should be `Option<&GlobalScope>` instead.

2017-02-09 22:20 UTC, jdm commented on components/script/dom/permissions.rs
> +    // TODO: `environment settings object` is not implemented in Servo yet.
`GlobalScope::current()`.

2017-02-09 22:20 UTC, jdm commented on components/script/dom/permissions.rs
> +    // TODO: `environment settings object` is not implemented in Servo yet.
We can store this in a field on Window.

2017-02-13 11:41 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15525) made this pull request unmergeable. Please resolve the merge conflicts.

2017-02-13 19:24 UTC, jdm requested changes

2017-02-13 19:24 UTC, jdm commented on components/script/dom/webidls/BluetoothPermissionResult.webidl
> +dictionary BluetoothPermissionData {
Given that BluetoothPermissionData and AllowedBluetoothDevice are never exposed to web content as far as I can see, we don't need to define them in WebIDL. They can be native Rust types instead, which will make it easier to derive implementations like HeapSizeOf and JSTraceable on them.

2017-02-13 19:24 UTC, jdm commented on components/script/dom/bluetooth.rs
> +    permission_data: DOMRefCell<BluetoothPermissionData>,
We should inline the members of BluetoothPermissionData inside BluetoothExtreaPermissionData; there's no need for the extra level of indirection.

2017-02-13 19:24 UTC, jdm commented on components/script/dom/bluetooth.rs
> +        self.permission_data.borrow().allowedDevices.clone()
If we return `Ref<Vec<...>>` instead (via Ref::map) then we don't need to clone the array every time.

2017-02-14 15:31 UTC, jdm approved these changes

2017-02-14 15:32 UTC, jdm commented
From my perspective these changes look good. Was there anything else you intended to change before merging?

2017-02-14 15:37 UTC, dati91 commented
No, that was all.

2017-02-14 15:42 UTC, jdm commented
@bors-servo: r+

2017-02-14 15:42 UTC, bors-servo commented
:pushpin: Commit 462a825 has been approved by `jdm`

<!-- @bors-servo r=jdm 462a825bd1797f881bc724006dbf2563775a341f -->

2017-02-14 16:09 UTC, bors-servo commented
:hourglass: Testing commit 462a825 with merge a537cf4...

2017-02-14 17:13 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5338), [arm32](http://build.servo.org/builders/arm32/builds/5541), [arm64](http://build.servo.org/builders/arm64/builds/5575), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5683), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2369), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2392), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5668), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5701), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2354), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2417), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/827), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/829)
Approved by: jdm
Pushing a537cf48b18d9bba3453b924a4453f5e19dea4ed to master...

2017-02-14 17:13 UTC, merged