Event handlers in generated by macros check for window presence
servo/servo pull request #15359
Opened 2017-02-03 00:24 UTC by freeatnet

This change adds a check for the presence of a window in the event handlers generated by the `define_window_owned_event_handler` macro.

Changes to event handlers that are [not generated by the macro](https://github.com/servo/servo/issues/15332#issuecomment-277083557) are not yet included — let me know if they are okay to go in the same PR.
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix the first part #15332

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

I'm new to both Servo and Rust — so any suggestions for improvement are very welcome.

2017-02-03 14:19 UTC, jdm commented
Great work on the tests! All the changes look correct; please go ahead and do the non-native handlers too!

2017-02-03 19:29 UTC, KiChjang requested changes

2017-02-03 19:29 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                None
Why is this returning `None` here? Shouldn't it default into returning `self.upcast::<EventTarget>().get_event_handler_common("load")`?

2017-02-03 19:29 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                None
Same question here.

2017-02-03 19:29 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                None
Same question here.

2017-02-03 19:29 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                None
Same question here.

2017-02-03 19:29 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                None
Same question here.

2017-02-03 19:29 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                None
Same question here.

2017-02-03 19:29 UTC, KiChjang commented on components/script/dom/macros.rs
> +                None
Same question here.

2017-02-03 19:29 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                window_from_node(self).GetOnload()
This pattern can be simplified to
```rust
let document = document_from_node(self);
if document.has_browsing_context() {
    document.window().GetOnload()
}
```

2017-02-03 19:39 UTC, freeatnet commented on components/script/dom/macros.rs
> +                window_from_node(self).$getter()
@KiChjang Any objections to applying the simplified pattern from above here too?

2017-02-03 19:48 UTC, freeatnet commented on components/script/dom/htmlelement.rs
> +                None
I believe this is consistent with the following specification definition (mentioned in #15332):
> If an event handler IDL attribute exposes an event handler of an object that doesn't exist, it must always return null on getting and must do nothing on setting.

2017-02-03 20:18 UTC, KiChjang commented on components/script/dom/macros.rs
> +                window_from_node(self).$getter()
No, go right ahead in fixing it!

2017-02-03 20:18 UTC, KiChjang commented
Also, my comments from my last review hasn't been addressed.

2017-02-03 20:26 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                None
> If an event handler IDL attribute exposes an event handler of an object that doesn't exist, it must always return null on getting and must do nothing on setting.

Here, you did not check whether an event handler exists when a browsing context doesn't exist.

2017-02-03 20:30 UTC, freeatnet commented on components/script/dom/htmlelement.rs
> +                None
Is there a case where a window would exist without a browsing context?

2017-02-03 20:31 UTC, KiChjang commented on components/script/dom/htmlelement.rs
> +                None
That's orthogonal to the problem I described. If there isn't a browsing context (i.e. there's not a window), then you should check whether the HTML element has an event handler registered for this particular event.

2017-02-03 20:35 UTC, jdm commented on components/script/dom/htmlelement.rs
> +                None
@KiChjang That countermands the spec, as @freeatnet pointed out.

2017-02-03 20:37 UTC, freeatnet commented on components/script/dom/htmlelement.rs
> +                None
The branch we are discussing deals with `body` and `frameset` elements that do not have a browsing context only, right?

My understanding is that `body` and `frameset` elements actually expose event handlers of their Window as their event handlers (first note in [the spec](https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-idl-attributes)).

Is there a case where the note above does not hold?

2017-02-03 20:49 UTC, KiChjang commented
Okay, nevermind, confusion has been solved via IRC chat with @jdm.

@bors-servo r+

2017-02-03 20:49 UTC, bors-servo commented
:pushpin: Commit 72ec00e has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 72ec00e0b56943ad64403eb1fefa216a925d98b0 -->

2017-02-03 20:49 UTC, bors-servo commented
:bulb: This pull request was already approved, no need to approve it again.

- There's another pull request that is currently being tested, blocking this pull request: #15363

2017-02-03 20:49 UTC, bors-servo commented
:pushpin: Commit 72ec00e has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 72ec00e0b56943ad64403eb1fefa216a925d98b0 -->

2017-02-03 20:54 UTC, freeatnet commented
@KiChjang Thank you and my apologies for the confusion. I should've linked the related specs in the PR.

2017-02-03 21:10 UTC, bors-servo commented
:hourglass: Testing commit 72ec00e with merge 8926db3...

2017-02-03 22:45 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5200), [arm32](http://build.servo.org/builders/arm32/builds/5388), [arm64](http://build.servo.org/builders/arm64/builds/5428), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5531), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2213), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2230), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5511), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5545), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2202), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2260), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/671), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/675)
Approved by: KiChjang
Pushing 8926db302a71079b8c116247abbcf059fde4e808 to master...

2017-02-03 22:45 UTC, merged

2017-02-16 13:03 UTC, jgraham commented
Please note that linking to external resources (in this case jQuery) in tests isn't allowed because it is commonly forbidden in tests environments and where it isn't may lead to test instability.

2017-02-16 13:09 UTC, freeatnet commented
@jgraham oh shoot. It was accidentally left in and isn't actually required for the test. Want me to PR the removal?

2017-02-16 13:11 UTC, jgraham commented
I'm going to land a commit in Gecko to remove it, which will be upstreamed in due course. But a separate PR here or in web-platfrom-tests wouldn't be harmful.