Remove slice_to_array_buffer_view and update_array_buffer_view
servo/servo pull request #15427
Opened 2017-02-07 19:08 UTC by deror1869107

Remove slice_to_array_buffer_view and update_array_buffer_view

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15350 
- [X] These changes do not require tests

2017-02-07 19:08 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/vreyeparameters.rs, components/script/dom/vrframedata.rs, components/script/dom/vrpose.rs, components/script/dom/bindings/conversions.rs, components/script/dom/vrstageparameters.rs
 * @kichjang: components/script/dom/vreyeparameters.rs, components/script/dom/vrframedata.rs, components/script/dom/vrpose.rs, components/script/dom/bindings/conversions.rs, components/script/dom/vrstageparameters.rs

2017-02-07 19:09 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-02-07 19:10 UTC, jdm commented on components/script/dom/vrframedata.rs
> +                MutableHandleObject::from_marked_location(framedata.right_view.get_unsafe()));
We should add a `handle_mut()` method to `Heap` instead of using from_marked_location everywhere.

2017-02-07 19:12 UTC, deror1869107 commented on components/script/dom/vrframedata.rs
> +                MutableHandleObject::from_marked_location(framedata.right_view.get_unsafe()));
Yes, the code is too long.
I can add ```handle_mut()``` and fix the code in this PR.

2017-02-08 18:38 UTC, deror1869107 commented
Change all ```MutableHandleObject::from_marked_location``` to ```handle_mut()```.

2017-02-09 19:17 UTC, jdm requested changes
Looks good! I just have some stylistic comments to make it easier to read.

2017-02-09 19:17 UTC, jdm commented on components/script/dom/vreyeparameters.rs
> +                Some(&result.parameters.borrow().offset), result.offset.handle_mut());
Let format this like:
```rust
let _ = Float32Array::create(global.get_cx(),
                             result.parameters.borrow().offset.len() as u32,
                             Some(&result.parameters.borrow().offset),
                             result.offset.handle_mut());
```

2017-02-09 19:17 UTC, jdm commented on components/script/dom/vrframedata.rs
> +                framedata.right_view.handle_mut());
nit: use `Float32Array::create` and indent the second line to match `global.get_cx()`.

2017-02-09 19:17 UTC, jdm commented on components/script/dom/vrpose.rs
> +                    dst.handle_mut());
nit: `Float32Array::create`, and move `dst.handle_mut()` into the previous line.

2017-02-09 19:17 UTC, jdm commented on components/script/dom/vrstageparameters.rs
> +                stage.transform.handle_mut());
nit: `Float32Array::create`, and indent each line to match `global.get_cx()`.

2017-02-10 17:12 UTC, deror1869107 commented
Fixed

2017-02-10 17:44 UTC, jdm requested changes
Sorry, one last issue that I noticed.

2017-02-10 17:44 UTC, jdm commented on components/script/dom/vrframedata.rs
> +                                         framedata.right_view.handle_mut());
This is a GC hazard right now - the GC does not know about `framedata` yet, so if any of the `Float32Array::create` calls trigger a GC, the existing typed arrays will be GCed and `framedata` will store invalid pointers. We should call `reflect_dom_object` first before creating the arrays.

2017-02-11 15:28 UTC, deror1869107 commented on components/script/dom/vrframedata.rs
> +                                         framedata.right_view.handle_mut());
The code that call ```reflect_dom_object``` has been moved before creating the arrays!

2017-02-11 16:04 UTC, jdm commented
@bors-servo: r+

2017-02-11 16:04 UTC, bors-servo commented
:pushpin: Commit 2d99f7f has been approved by `jdm`

<!-- @bors-servo r=jdm 2d99f7f995ad532e5f70526bca95dfcc1ae5c97e -->

2017-02-11 16:04 UTC, bors-servo commented
:hourglass: Testing commit 2d99f7f with merge 1ab3c34...

2017-02-11 16:57 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5296), [arm32](http://build.servo.org/builders/arm32/builds/5493), [arm64](http://build.servo.org/builders/arm64/builds/5529), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5634), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2320), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2343), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5618), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5652), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2307), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2368), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/778), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/780)
Approved by: jdm
Pushing 1ab3c34dd937ab36ce6bf56e70f09f823c240fe0 to master...

2017-02-11 16:57 UTC, merged