Calling matchMedia during a MQL change event will not panic
servo/servo pull request #15495
Opened 2017-02-10 14:35 UTC by prampey

Calling matchMedia now leads to a new copy of MQL objects to prevent errors when borrowing references from MQL during an MQL change event.  

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14967  (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-02-10 14:35 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/mediaquerylist.rs
 * @kichjang: components/script/dom/mediaquerylist.rs

2017-02-10 15:44 UTC, jdm requested changes
Great work! Just a couple stylistic comments, and the changes will need to be rebased against master.

2017-02-10 15:44 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/mql_borrow.html
> +    var test = async_test("No clashes found while trying to get a refernce to mql");
"Using matchMedia inside of a MediaQueryList callback does not panic"

2017-02-10 15:44 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/mql_borrow.html
> +            }));
Let's unindent this code to match `var test`.

2017-02-10 15:44 UTC, jdm commented on components/script/dom/mediaquerylist.rs
> +        {
nit: `for mql in &mql_list {`

2017-02-10 15:44 UTC, jdm commented on components/script/dom/mediaquerylist.rs
> +        for mql in self.cell.borrow_mut().iter() {
Why do we need borrow_mut here?

2017-02-10 18:21 UTC, prampey commented on components/script/dom/mediaquerylist.rs
> +        {
@jdm For the sake of theory, there is no performance difference between the two right?

2017-02-10 18:26 UTC, prampey commented on components/script/dom/mediaquerylist.rs
> +        for mql in self.cell.borrow_mut().iter() {
Yeah it works without.

2017-02-10 18:34 UTC, prampey commented on components/script/dom/mediaquerylist.rs
> +        {
Also, I get an error saying that `RootedVec` doesn't implement the `Iterator` trait.

2017-02-10 18:38 UTC, jdm commented on components/script/dom/mediaquerylist.rs
> +        {
Correct.

2017-02-10 19:15 UTC, prampey commented on components/script/dom/mediaquerylist.rs
> +        {
I get that error for `&mql_list`. Should I revert back?

2017-02-10 19:28 UTC, jdm commented on components/script/dom/mediaquerylist.rs
> +        {
Yes, my mistake. Please keep the { on the same line, though.

2017-02-13 20:13 UTC, prampey commented
@jdm Cool. I'm done with the stylistic changes but I seem to be a bit confused when resolving `MANIFEST.json`.

2017-02-13 21:03 UTC, jdm commented
@prampey You should be able to revert all changes to MANIFEST.json and run `./mach manifest-update` to get a version which is correct.

2017-02-15 17:42 UTC, prampey commented
@jdm  Yes, I already used `update-manifest`. However while rebasing, the latest commit and my commit seem to have huge differences in code. How do I go about this?

2017-02-15 18:11 UTC, jdm commented
@prampey Do you mean in MANIFEST.json? My point is that while rebasing you can just resolve merge conflicts in that file by reverting all changes and running update-manifest again, then adding the modified file.

2017-02-16 12:47 UTC, prampey commented
@jdm Oh okay, my bad. I pushed in the new changes.

2017-02-16 20:33 UTC, jdm commented
@bors-servo: r+
Thanks a lot for fixing this!

2017-02-16 20:33 UTC, bors-servo commented
:pushpin: Commit 2369de7 has been approved by `jdm`

<!-- @bors-servo r=jdm 2369de737f524248e3779a47b0dc88e780f05ef3 -->

2017-02-16 20:59 UTC, bors-servo commented
:hourglass: Testing commit 2369de7 with merge 89b2275...

2017-02-16 21:36 UTC, prampey commented
@jdm Thanks a lot for bearing with me :) Also, I think it'd be really convenient for developers if we added the documentation link (_http://testthewebforward.org/docs/testharness-library.html_) in the `wpt` Readme file. Should I send in a PR?

2017-02-16 21:44 UTC, jdm commented
Please do!

2017-02-16 21:51 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2478)

2017-02-16 23:17 UTC, jdm commented
```
  ▶ TIMEOUT [expected OK] /_mozilla/mozilla/mql_borrow.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  �� Unexpected subtest result in /_mozilla/mozilla/mql_borrow.html:
  └ NOTRUN [expected PASS] Using matchMedia inside of a MediaQueryList callback does not panic
```
That's not good. That means that the first matchMedia listener never fired.

2017-02-16 23:18 UTC, jdm commented
@prampey What happens if you run `./mach test-wpt tests/wpt/mozilla/tests/mozilla/mql_borrow.html --no-pause-after-test`? Do you see a timeout?

2017-02-16 23:37 UTC, prampey commented
@jdm Yes I do. Could it be because of the `update` method in `evaluate_and_report_changes`?

2017-02-17 05:06 UTC, jdm commented
I suspect the problem is that resizeTo does not trigger a resize event when running Servo in headless mode. If you resize an iframe instead then I expect it will work. Please file an issue with this test case so we can track the problem with headless mode!

2017-02-17 22:36 UTC, prampey commented
@jdm Yes, iframes seemed to work. Just pushed in the update.

2017-02-17 23:05 UTC, jdm commented
@bors-servo: r+

2017-02-17 23:05 UTC, bors-servo commented
:pushpin: Commit 60f5155 has been approved by `jdm`

<!-- @bors-servo r=jdm 60f5155ab125e354579eb0c2322bf2b90f91524a -->

2017-02-17 23:08 UTC, jdm commented
I filed #15621 about the headless resize issue.

2017-02-18 00:30 UTC, bors-servo commented
:hourglass: Testing commit 60f5155 with merge e91f316...

2017-02-18 01:02 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5751)

2017-02-18 01:50 UTC, jdm commented
Bah, another manifest-update is necessary :<

2017-02-19 11:31 UTC, nox commented
@bors-servo r=jdm

2017-02-19 11:31 UTC, bors-servo commented
:pushpin: Commit 0c21333 has been approved by `jdm`

<!-- @bors-servo r=jdm 0c213337774575605a8d171bc1a2d7cc05747aac -->

2017-02-19 12:10 UTC, bors-servo commented
:hourglass: Testing commit 0c21333 with merge debdebe...

2017-02-19 13:10 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5435), [arm32](http://build.servo.org/builders/arm32/builds/5646), [arm64](http://build.servo.org/builders/arm64/builds/5676), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5787), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2481), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2502), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5777), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5807), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2460), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2525), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/937), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/939)
Approved by: jdm
Pushing debdebe8dea69c41472002bb49dbb29cc30a85f2 to master...

2017-02-19 13:11 UTC, merged