fixed the wrong behavior of border-spacing
servo/servo pull request #15612
Opened 2017-02-17 06:45 UTC by UnICorN21

fixed the wrong behavior of border-spacing
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15489.

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-02-17 06:45 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2017-02-17 06:45 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/properties/longhand/inherited_table.mako.rs
 * @emilio: components/style/properties/longhand/inherited_table.mako.rs

2017-02-17 12:45 UTC, canova reviewed
Thanks for working on this! Additionally, we need some tests for this change. But since parser checks the exhaustion in another part of code, it can't be tested with `assert_roundtrip_with_context` macro. You can test it with creating a parser and checking if it's exhausted or not. This was explained more here: https://github.com/servo/servo/pull/15598#issuecomment-280497543

2017-02-17 12:45 UTC, canaltinova commented on python/servo/testing_commands.py
> +            packages = set(os.listdir(path.join(self.context.topdir, "tests", "unit"))) - set(['.DS_Store'])
What does this change do exactly? Was .DS_Store breaking the tests?

2017-02-17 12:45 UTC, canaltinova commented on tests/unit/style/parsing/border.rs
> -    assert_eq!(result.border_image_slice.unwrap(), parse_longhand!(border_image_slice, "30 30% 45 fill"));
Normally linter allows up to 120 characters per line. But this is better, I guess.

2017-02-17 14:38 UTC, jdm commented on python/servo/testing_commands.py
> +            packages = set(os.listdir(path.join(self.context.topdir, "tests", "unit"))) - set(['.DS_Store'])
I bet it's working around https://github.com/servo/servo/issues/15581.

2017-02-17 14:53 UTC, UnICorN21 commented on python/servo/testing_commands.py
> +            packages = set(os.listdir(path.join(self.context.topdir, "tests", "unit"))) - set(['.DS_Store'])
see #15581. I met the same problem too, and here's a quick fix.

2017-02-17 15:33 UTC, canaltinova commented on python/servo/testing_commands.py
> +            packages = set(os.listdir(path.join(self.context.topdir, "tests", "unit"))) - set(['.DS_Store'])
Ah, okay. Thanks for the clarification.

2017-02-18 16:25 UTC, canova requested changes
Thanks for the tests! A few comments :)

2017-02-18 16:25 UTC, canaltinova commented on tests/unit/style/properties/serialization.rs
> +fn test_border_spacing() {
I think this belongs to `tests/unit/style/parsing/border.rs`. This is a parsing test normally. We don't check if the values are correct here. Could you move it there please?

2017-02-18 16:25 UTC, canaltinova commented on tests/unit/style/properties/serialization.rs
> +    macro_rules! parse_assert {
We can use this macro in the future for other longhands too. Could you move it to `parsing/mod.rs` and rename it something like `assert_parser_exhausted`. You can look at the `parse_longhand` macro for an example of this.

2017-02-18 16:25 UTC, canaltinova commented on tests/unit/style/properties/serialization.rs
> +            let parsed = border_spacing::parse(&context, &mut parser);
After moving to `mod.rs`, we need to make this macro generic. To do this, we need to replace border_spacing::parse function with `$name::parse` and get the `$name` variable from macro parameters. You can call this macro like this after that: `assert_parser_exhausted!(border_spacing, "1px rubbish", false);`

2017-02-18 16:25 UTC, canaltinova commented on tests/unit/style/properties/serialization.rs
> -                Some(Image::Url(SpecifiedUrl::new_for_testing("http://servo/test.png"))));
I don't think these changes are necessary. For example this line was fine before and we don't like too much empty lines like previous lines. Please revert these.

2017-02-19 00:31 UTC, UnICorN21 commented on tests/unit/style/properties/serialization.rs
> -                Some(Image::Url(SpecifiedUrl::new_for_testing("http://servo/test.png"))));
Sorry, these style changes are caused by the automatic check of rustfmt

2017-02-19 11:55 UTC, canova approved these changes
This looks very good! Thank you for doing this!
Could you squash your commits into one(except .DS_Store commit), so we can merge this :)
Btw, I'm not a reviewer, we'll need a reviewer to approve this.

2017-02-19 14:48 UTC, UnICorN21 commented
@canaltinova ok, thanks

2017-02-19 15:33 UTC, canaltinova commented
I mean you can add .DS_Store commit but seperate commit is good for it instead of a squashed one.(Or you can create another PR for it if you like)

2017-02-20 22:38 UTC, canaltinova commented
It looks good to me, could you review this one please? @emilio,  @Manishearth 

Thanks again for all the work @UnICorN21!

2017-02-20 22:54 UTC, emilio reviewed
Looks good, thanks!

2017-02-20 22:54 UTC, emilio commented on python/servo/testing_commands.py
> +            packages = set(os.listdir(path.join(self.context.topdir, "tests", "compiletest"))) - set('.DS_Store')
Please revert these changes and submit them in another PR, since they're unrelated to the rest of the PR.

2017-02-20 22:55 UTC, emilio commented
And thanks for taking over the review @canaltinova :)

@bors-servo delegate=canaltinova

2017-02-20 22:55 UTC, bors-servo commented
:v: @canaltinova can now approve this pull request

2017-02-20 23:21 UTC, canaltinova commented on python/servo/testing_commands.py
> +            packages = set(os.listdir(path.join(self.context.topdir, "tests", "compiletest"))) - set('.DS_Store')
Oh, I thought we can do that, but you're right.
Sorry about that :)

2017-02-21 00:15 UTC, UnICorN21 commented on python/servo/testing_commands.py
> +            packages = set(os.listdir(path.join(self.context.topdir, "tests", "compiletest"))) - set('.DS_Store')
Ok, I moved this change to #15665

2017-02-21 09:09 UTC, canaltinova commented
@bors-servo r+
Thanks!

2017-02-21 09:09 UTC, bors-servo commented
:pushpin: Commit 06650f8 has been approved by `canaltinova`

<!-- @bors-servo r=canaltinova 06650f8428f4ef7ec8477b8ec234d85b8c84c189 -->

2017-02-21 09:09 UTC, bors-servo commented
:hourglass: Testing commit 06650f8 with merge d724bff...

2017-02-21 10:19 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5461), [arm32](http://build.servo.org/builders/arm32/builds/5674), [arm64](http://build.servo.org/builders/arm64/builds/5702), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5815), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2508), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2529), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5804), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5834), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2486), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2553), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/965), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/966)
Approved by: canaltinova
Pushing d724bffde80fec1698a485698d8743022a1e9d57 to master...

2017-02-21 10:20 UTC, merged