Eliminate a mem::transmute in CodeGen
servo/servo pull request #15659
Opened 2017-02-20 13:51 UTC by gregkatz

Eliminate a mem::transmute in CodeGen by changing the find_enum_string_index function to take a slice of pairs and return an enum value.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15587 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because _____

2017-02-20 13:51 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @mbrubeck (or someone else) soon.

2017-02-20 13:51 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/bindings/utils.rs
 * @kichjang: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/bindings/utils.rs

2017-02-20 13:51 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-02-20 15:29 UTC, Ms2ger commented on components/script/dom/bindings/codegen/CodegenRust.py
> +           ",\n    ".join(['("%s", super::%s::%s)' % (val, ident, getEnumValueName(val)) for val in enum.values()]),
Maybe define this in a local variable

2017-02-20 15:30 UTC, Ms2ger requested changes

2017-02-20 15:30 UTC, Ms2ger commented on components/script/dom/bindings/utils.rs
> +                                       -> Result<(Option<T>, DOMString), ()> {
I think we can avoid the `Copy` bound by doing
```rust
                                       pairs: &'a [(&'static str, T)])
                                       -> Result<(Option<&'a T>, DOMString), ()> {
```

and then in the generated code
```rust
Ok((Some(&value), _)) => value,
```

2017-02-20 15:34 UTC, gregkatz commented on components/script/dom/bindings/utils.rs
> +                                       -> Result<(Option<T>, DOMString), ()> {
Thanks for the comments! I'll work on them.

2017-02-21 11:32 UTC, nox commented on components/script/dom/bindings/utils.rs
> +pub unsafe fn find_enum_value<'a, T>(cx: *mut JSContext,
I don't think you need the explicit `'a` here, lifetime elision should do the job.

2017-02-21 12:05 UTC, Ms2ger commented
I think it's fine.

@bors-servo r+

2017-02-21 12:05 UTC, bors-servo commented
:pushpin: Commit 214db8d has been approved by `Ms2ger`

<!-- @bors-servo r=Ms2ger 214db8d9f0f6fda6ae20136442f3a28171e4b4c8 -->

2017-02-21 12:28 UTC, bors-servo commented
:hourglass: Testing commit 214db8d with merge af6353d...

2017-02-21 13:15 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5463), [arm32](http://build.servo.org/builders/arm32/builds/5676), [arm64](http://build.servo.org/builders/arm64/builds/5704), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5817), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2510), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2531), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5806), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/5836), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2488), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2555), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/967), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/968)
Approved by: Ms2ger
Pushing af6353df87770c6d616facdc07f9f929e99b9eda to master...

2017-02-21 13:15 UTC, merged