Pass the initial URL as an argument to Browser::new, not as a opts property
servo/servo pull request #15699
Opened 2017-02-23 03:56 UTC by deror1869107

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15636 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-02-23 04:32 UTC, fabricedesre commented on ports/servo/main.rs
> +        browser: Browser::new(window.clone(), opts::get().url.clone().unwrap()),
what if unwrap() panics?

2017-02-23 04:36 UTC, deror1869107 commented on ports/servo/main.rs
> +        browser: Browser::new(window.clone(), opts::get().url.clone().unwrap()),
So should I add some code like ```if let opts::get().url.clone() = url { }```?

2017-02-23 05:22 UTC, KiChjang commented on ports/servo/main.rs
> +        browser: Browser::new(window.clone(), opts::get().url.clone().unwrap()),
`.unwrap_or(ServoUrl::parse("about:blank").unwrap())` may make sense here. If that unwrap fails, then we're in deeply screwed territory anyway so it doesn't matter.

2017-02-23 07:42 UTC, paulrouget commented
I would not make the url an `Option<>`. Also, ideally, `Opts::url` would disappear. See https://github.com/servo/servo/issues/15636#issuecomment-281239922

ports/servo/main.rs should look at the pref (not opts) and call Browser::new with the right URL. The compositor should not accept an empty URL (create_constellation should not take an Option as an argument).

One of the issue we have here is that command line is handled in components/ (libservo) when I believe should be parsed in ports/ (embedder). Ideally the command line would be handled in ports/ (initialising `opts` and running `Browser::new(…, url)`). It might be beyond the scope of this PR though.

Maybe for now, we should do this:

1. down to create_constellation, the url should never be an option. It's up to main.rs to get the url from 1) command line 2) PREFS 3) about:blank
2. to get the url from the command line, main.rs can use opts, and the would be the only code access opts.url
3. file a follow up issue to make it so that command handling is done in ports/, where all options would be fed to opts, except the url, which would be used to initiate Browser.
4. remove the opts.url access from 2)

2017-02-23 07:46 UTC, paulrouget requested changes

2017-02-23 07:46 UTC, paulrouget commented on components/servo/lib.rs
> +                                                                    Some(url),
Can we not use an Option<> here? Is there any situation where we want to initialise a constellation without a url?

2017-02-23 07:46 UTC, paulrouget commented on ports/servo/main.rs
> +                              opts::get().url.clone()
opts.url checks for the PREFS shell.homepage. Shouldn't we remove that from the opts::from_cmdline_args and move it here instead?

2017-02-26 07:25 UTC, deror1869107 commented on components/servo/lib.rs
> +                                                                    Some(url),
No. We can change ```fn create_constellation``` to use ```url: ServoUrl``` as parameter

2017-02-28 17:55 UTC, paulrouget commented
To this I would add that when starting multiple instances of Servo, we might want to share the options, but not the url.

2017-03-03 07:19 UTC, KiChjang commented
r? @paulrouget 
@bors-servo delegate=paulrouget

2017-03-03 07:19 UTC, bors-servo commented
:v: @paulrouget can now approve this pull request

2017-03-06 02:31 UTC, paulrouget commented
@deror1869107, let me know if there's anything I can do to help or if there's anything I could clarify.

2017-04-12 03:45 UTC, jdm commented
Closing due to inactivity.

2017-04-12 03:45 UTC, closed without merging