first stab. added ServoUrl as a parameter to report_error(...) of Par…
servo/servo pull request #15751
Opened 2017-02-27 11:04 UTC by avinash-vijayaraghavan

1. Added ServoUrl as a parameter to report_error(...) of ParseErrorReporter trait. 
2. I am not sure how to handle the case of impl ParseErrorReporter for CSSErrorReporter and MemoryHoleReporter, so have not made any changes  (other than adding ServoUrl arg) to report_error implementations for these.
3. In StdoutErrorReporter i have added the ServoUrl arg to the info! function,
4. I would like to know if i am on the correct path and clarify what else needs to be done.

---

- [ X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because wanted to clarify before writing tests

2017-02-27 11:04 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @cbrewster (or someone else) soon.

2017-02-27 11:04 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/parser.rs, components/style/stylesheets.rs, components/style/error_reporting.rs
 * @kichjang: components/script_layout_interface/reporter.rs
 * @fitzgen: components/script_layout_interface/reporter.rs
 * @emilio: components/style/parser.rs, components/style/stylesheets.rs, components/style/error_reporting.rs

2017-02-27 11:04 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2017-02-27 12:46 UTC, ghost requested changes
Thanks for your PR! I have a few comments :)

2017-02-27 12:46 UTC, Wafflespeanut commented on components/style/error_reporting.rs
> +             match  servo_url {
Nit: double spaces

Also, we probably don't want `match` here. We could simply rewrite the existing log statement with `map` and `unwrap` methods of `Option<T>` like,

``` rust
info!("{}{}:{} {}", servo_url.map(|u| &format!("ServoUrl: {}\n", u.as_str())).unwrap_or(""), /* other things */);
```

2017-02-27 12:46 UTC, Wafflespeanut commented on components/style/parser.rs
> +    parsercontext.error_reporter.report_error(input, position, message,servo_url);
Nit: space after comma

2017-02-27 12:46 UTC, Wafflespeanut commented on patch.diff.txt
> +diff --git a/components/script_layout_interface/reporter.rs b/components/script_layout_interface/reporter.rs
Please remove this file from the commit.

2017-02-27 12:46 UTC, Wafflespeanut commented on components/script_layout_interface/reporter.rs
> +     fn report_error(&self, input: &mut Parser, position: SourcePosition, message: &str, servo_url : Option<&ServoUrl>) {
This doesn't seem to be used. We should use it in the log statement (just like we did below).

2017-02-27 12:48 UTC, Wafflespeanut commented
Also, please make sure that your changes pass `./mach test-tidy` and (as jdm suggested in the issue), this needs unit tests before landing.

2017-02-27 16:48 UTC, avinash-vijayaraghavan commented on components/script_layout_interface/reporter.rs
> +     fn report_error(&self, input: &mut Parser, position: SourcePosition, message: &str, servo_url : Option<&ServoUrl>) {
@Wafflespeanut @jdm @cbrewster 
Do we use the url in the same way here too ?

2017-02-27 16:48 UTC, avinash-vijayaraghavan commented on patch.diff.txt
> +diff --git a/components/script_layout_interface/reporter.rs b/components/script_layout_interface/reporter.rs
i will remove this patch file

2017-02-27 16:49 UTC, avinash-vijayaraghavan commented on components/style/error_reporting.rs
> +             match  servo_url {
@Wafflespeanut @jdm @cbrewster 
does **u.as_str()** not break  when u is None  ?
I avoided this problem Using **match** and **Some(url)** to provide a valid url for
**url.as_str()**

2017-02-27 17:29 UTC, Wafflespeanut commented on components/style/error_reporting.rs
> +             match  servo_url {
[`map`](https://doc.rust-lang.org/std/option/enum.Option.html#method.map) is called only when there's `Some(T)` in `Option<T>`, and `unwrap_or("")` makes sure that if there's `None`, then we'll get an empty string. So, we're good :)

2017-02-27 17:30 UTC, Wafflespeanut commented on components/script_layout_interface/reporter.rs
> +     fn report_error(&self, input: &mut Parser, position: SourcePosition, message: &str, servo_url : Option<&ServoUrl>) {
Yep!

2017-02-27 17:31 UTC, emilio commented on components/style/error_reporting.rs
> +             match  servo_url {
Though at that point you can also just call `map_or` :)

2017-02-28 06:29 UTC, avinash-vijayaraghavan commented
@Wafflespeanut @emilio 
made changes based on ur suggestions.
i need some help with the unit tests. not quite sure what i need to test. :)

2017-03-01 01:12 UTC, cbrewster commented
Hi! Thank you for these changes. These unit tests need to be updated:
[tests/unit/style/stylesheets.rs](https://dxr.mozilla.org/servo/rev/4b394312153c56812113c149df77a313939de30f/tests/unit/style/stylesheets.rs#295)
[tests/unit/style/rule_tree/bench.rs](https://dxr.mozilla.org/servo/rev/4b394312153c56812113c149df77a313939de30f/tests/unit/style/rule_tree/bench.rs#20)
[tests/unit/style/media_queries.rs](https://dxr.mozilla.org/servo/rev/4b394312153c56812113c149df77a313939de30f/tests/unit/style/media_queries.rs#21)

2017-03-02 17:44 UTC, avinash-vijayaraghavan reviewed
@cbrewster 
i have made the following changes based on your suggestions. :) let me know your opinion

2017-03-02 17:44 UTC, avinash-vijayaraghavan commented on tests/unit/style/stylesheets.rs
> +                url: url,
added the **url** into the **cserror** struct so that it can be picked up from the **errors**

2017-03-02 17:44 UTC, avinash-vijayaraghavan commented on tests/unit/style/stylesheets.rs
> +    assert_eq!(url, error.url);
checking whether the url has been passed correctly
error.url (**csserror field : url**)

2017-03-02 17:44 UTC, avinash-vijayaraghavan commented on tests/unit/style/stylesheets.rs
> +fn test_report_error_passing_correct_url() {
added a new test for checking urls
loop thru different urls and check if they are being passed correctly

2017-03-03 05:32 UTC, cbrewster reviewed
Looking Good!
Just a few nits and a couple changes I would like to see.

2017-03-03 05:32 UTC, cbrewster commented on components/script_layout_interface/reporter.rs
> +
nit: revert these newlines

2017-03-03 05:32 UTC, cbrewster commented on components/script_layout_interface/reporter.rs
> +            //  info!("{}:{} {}", location.line, location.column, message)
nit: remove comment

2017-03-03 05:32 UTC, cbrewster commented on components/script_layout_interface/reporter.rs
> +             location.line, location.column, message)
nit: indent this line one more tab

2017-03-03 05:32 UTC, cbrewster commented on tests/unit/style/stylesheets.rs
> +    let mut servo_urls = vec!();
I think it would be okay to just check with 1 URL.

2017-03-03 05:32 UTC, cbrewster commented on tests/unit/style/media_queries.rs
> +
nit: remove newline

2017-03-03 05:32 UTC, cbrewster commented on tests/unit/style/media_queries.rs
> +
nit: remove newline

2017-03-03 05:32 UTC, cbrewster commented on tests/unit/style/media_queries.rs
> +            let css_url = servo_url.unwrap().clone();
Lets keep the url as a param, but leave the body of this method empty.
You'll want to rename the parameter to `_url` or `_servo_url` as the `_` will get rid of the unused variable warning

2017-03-03 05:32 UTC, cbrewster commented on components/style/stylesheets.rs
> +        _: Option<&ServoUrl>) {
nit: Indent

2017-03-03 05:32 UTC, cbrewster commented on components/style/error_reporting.rs
> +        url: Option<&ServoUrl>) {
I could be wrong, but I believe `url` will never be `None` so we should change `Option<&ServoUrl>` to `&ServoUrl` and remove any unneeded unwraps.

2017-03-03 05:32 UTC, cbrewster commented on tests/unit/style/stylesheets.rs
> +    let wrong_url = ServoUrl::parse("about::test_wrong").unwrap();
remove this line

2017-03-03 05:32 UTC, cbrewster commented on tests/unit/style/stylesheets.rs
> +    // assert_eq!(wrong_url, error.url);
remove this line

2017-03-03 05:32 UTC, cbrewster commented on tests/unit/style/stylesheets.rs
> +    assert_eq!(url, error.url);
Looks good! could we add another `assert_eq!` with the previous error above?

2017-03-03 05:32 UTC, cbrewster commented on tests/unit/style/stylesheets.rs
> +fn test_report_error_passing_correct_url() {
I think that the added `assert_eq!`s in the test above may be enough for this actually. so you could probably just remove this test.

@jdm would you still prefer an added test module `error_reporting.rs` that has a custom error reporter?

2017-03-03 12:48 UTC, avinash-vijayaraghavan reviewed
i could remove the test test_report_error_passing_correct_url(...) since it does nothing more than the previous test. let me know

2017-03-03 12:48 UTC, avinash-vijayaraghavan commented on components/script_layout_interface/reporter.rs
> +         servo_url: &ServoUrl) {
removed the option for the servourl as per @cbrewster suggestions

2017-03-03 18:27 UTC, jdm commented
Yes, removing the duplicate test makes sense.

2017-03-04 06:25 UTC, avinash-vijayaraghavan reviewed
@cbrewster @jdm 
removed the duplicate test as per @jdm 's request.

2017-03-06 04:26 UTC, cbrewster requested changes
Just a few more nits lefts!

2017-03-06 04:26 UTC, cbrewster commented on components/script_layout_interface/reporter.rs
> +            }
nit: unindent here

2017-03-06 04:26 UTC, cbrewster commented on components/script_layout_interface/reporter.rs
> +         servo_url: &ServoUrl) {
nit: lets just call this `url` to be consistent

2017-03-06 04:26 UTC, cbrewster commented on tests/unit/style/media_queries.rs
> +        _servo_url: &ServoUrl) {
nit: `_url` for consistency

2017-03-06 04:26 UTC, cbrewster commented on tests/unit/style/rule_tree/bench.rs
> +        servo_url: &ServoUrl) {
same here

2017-03-06 04:26 UTC, cbrewster commented on tests/unit/style/stylesheets.rs
> +        servo_url: &ServoUrl) {
same here

2017-03-06 04:26 UTC, cbrewster commented on tests/unit/style/stylesheets.rs
> +        let url = servo_url.clone();
let's remove this line and add `.clone()` to `url` when creating the `CSSError` instance

2017-03-06 04:26 UTC, cbrewster commented on tests/unit/style/stylesheets.rs
> +
nit: remove blank newline

2017-03-06 04:58 UTC, avinash-vijayaraghavan reviewed
@cbrewster 
i have made the changes

2017-03-06 04:58 UTC, avinash-vijayaraghavan commented on components/script_layout_interface/reporter.rs
> +         _url: &ServoUrl) {
changed to _url

2017-03-06 05:21 UTC, cbrewster commented on components/script_layout_interface/reporter.rs
> +         _url: &ServoUrl) {
Thank you! Although in the cases where url is used in the function, it shouldn't be prefixed with an underscore. The underscore tells the compiler that the variable is not intended to be used in the function so the compiler knows not to emit an unused variable warning

2017-03-06 05:26 UTC, avinash-vijayaraghavan commented on components/script_layout_interface/reporter.rs
> +         _url: &ServoUrl) {
@cbrewster 
thanks for letting me know. :) should i revert this ?

2017-03-06 15:10 UTC, cbrewster approved these changes

2017-03-06 15:11 UTC, cbrewster commented
Thank you!
@bors-servo r+

2017-03-06 15:11 UTC, bors-servo commented
:pushpin: Commit f48f056 has been approved by `cbrewster`

<!-- @bors-servo r=cbrewster f48f0567cf44ac87fb34756b4167b644ad6049db -->

2017-03-06 15:11 UTC, bors-servo commented
:hourglass: Testing commit f48f056 with merge 0dbee36...

2017-03-06 15:58 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5614), [arm32](http://build.servo.org/builders/arm32/builds/5848), [arm64](http://build.servo.org/builders/arm64/builds/5870), [linux-dev](http://build.servo.org/builders/linux-dev/builds/5986), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2691), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2711), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/5981), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6007), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2655), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2731), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1143), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1143)
Approved by: cbrewster
Pushing 0dbee36915abd926e61ca8571e11abf1f97ec830 to master...

2017-03-06 15:58 UTC, merged