updated files for openssl bump, changed to hyper_openssl::opensslclient
servo/servo pull request #15775
Opened 2017-03-01 01:03 UTC by avadacatavra

fixed new wrapped hyper to handle strings per hyper 10

bumped to cookie 0.6

use serde_json to persist cookies in net crate

fixed tests to be compatible with new cookie version

fixed case mismatch with domain test

bumped to webdriver 0.22

Bumped hyper, cookie and webdriver. Added a dependency on hyper_openssl as part of the bump.

It's important to point out that I had to fork and update websocket. I spoke with @nox about websocket/ws. This branch points to my fork. Until we migrate to ws (#14517), we'll need to maintain a fork.

Also, I believe this may fix #10550, but that might require additional verification
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14203 and #15010 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-03-01 01:04 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/webdriver_server/lib.rs, components/webdriver_server/Cargo.toml
 * @jgraham: components/webdriver_server/lib.rs, components/webdriver_server/Cargo.toml
 * @fitzgen: components/devtools_traits/Cargo.toml, components/devtools_traits/Cargo.toml, components/devtools/Cargo.toml, components/script/dom/document.rs, components/script/webdriver_handlers.rs, components/script/Cargo.toml, components/script/dom/websocket.rs, components/script_traits/webdriver_msg.rs, components/script_traits/webdriver_msg.rs, components/script_traits/Cargo.toml, components/script_traits/Cargo.toml
 * @kichjang: components/net/lib.rs, components/script/dom/document.rs, components/net/http_loader.rs, components/net/connector.rs, components/net_traits/lib.rs, components/net_traits/lib.rs, components/script/webdriver_handlers.rs, components/script/Cargo.toml, components/net/cookie_storage.rs, components/net_traits/Cargo.toml, components/net_traits/Cargo.toml, components/net/resource_thread.rs, components/net/Cargo.toml, components/net/cookie.rs, components/net/subresource_integrity.rs, components/script/dom/websocket.rs, components/script_traits/webdriver_msg.rs, components/script_traits/webdriver_msg.rs, components/script_traits/Cargo.toml, components/script_traits/Cargo.toml

2017-03-01 01:15 UTC, KiChjang commented
This requires a rebase, unfortunately.

2017-03-01 08:44 UTC, nox commented on components/net/Cargo.toml
> +cookie = {version = "0.6", features = ["rustc-serialize"]}
No need for that feature anymore.

2017-03-01 09:12 UTC, nox requested changes
Did a first review pass, most comments are superficial, great work. 🍷

2017-03-01 09:12 UTC, nox commented on components/net/resource_thread.rs
> +}
Indentation is broken.

2017-03-01 09:12 UTC, nox commented on components/net_traits/Cargo.toml
> +cookie = {version = "0.6", features = ["rustc-serialize"]}
This feature is useless now.

2017-03-01 09:12 UTC, nox commented on components/net_traits/lib.rs
> +        CookieSource),
Indentation is broken. Please realign as it was before.

2017-03-01 09:12 UTC, nox commented on components/net_traits/lib.rs
> +    SetCookiesForUrl(ServoUrl, String, CookieSource),
Why did you rename `SetCookieForUrl` to `SetCookiesForUrl` and `SetCookiesForUrl` to `SetCookiesForUrlWithData`?

2017-03-01 09:12 UTC, nox commented on components/net_traits/lib.rs
> +    //  and exit
Comment is broken.

2017-03-01 09:12 UTC, nox commented on components/script/Cargo.toml
> +cookie = {version = "0.6", features = ["rustc-serialize"]}
This feature is useless now.

2017-03-01 09:12 UTC, nox commented on components/script/dom/document.rs
> +                    .send(SetCookiesForUrl(self.url(), String::from(cookie), NonHTTP));
Oh I see now why things have been renamed. What about renaming `SetCookieForUrl` to `SetCookieHeaderForUrl` and keep `SetCookiesForUrl` as is?

2017-03-01 09:12 UTC, nox commented on components/script/dom/websocket.rs
> +            }
This can be written in a shorter way:

```rust
cookies.iter().map(ToString::to_string).collect::<String>()
```

2017-03-01 09:12 UTC, nox commented on components/script/dom/websocket.rs
> +                SetCookiesForUrl(ws.url.clone(), v, HTTP));
Could you use `SetCookiesForUrlWithData` instead, parsing each `String` from the `SetCookie` header to a `Cookie` before sending it? I would rather not roundtrip through a longer string only to split it again afterwards.

2017-03-01 09:12 UTC, nox commented on components/script/webdriver_handlers.rs
> +    let cookies: Vec<Serde<Cookie<'static>>> = match documents.find_document(pipeline) {
Is this type annotation even necessary?

2017-03-01 09:12 UTC, nox commented on components/script/webdriver_handlers.rs
> +    let cookie = cookie.to_owned();
Why? `cookie` is already a `Cookie<'static>`.

2017-03-01 09:12 UTC, nox commented on components/script/webdriver_handlers.rs
> +    let cookie2 = cookie.clone().to_owned();
Why clone `cookie`?

2017-03-01 09:12 UTC, nox commented on components/script/webdriver_handlers.rs
> +    let domain = cookie2.domain().clone().to_owned();
Why clone `cookie`'s domain?

2017-03-01 09:12 UTC, nox commented on components/webdriver_server/Cargo.toml
> +cookie = {version = "0.6", features = ["rustc-serialize"]}
This feature is useless now.

2017-03-01 09:12 UTC, nox commented on components/webdriver_server/lib.rs
> +    load_timeout: Option<u64>,
Why an `Option` now?

2017-03-01 09:12 UTC, nox commented on components/webdriver_server/lib.rs
> +        };*/
Please remove the commented out code.

2017-03-01 11:17 UTC, avadacatavra commented on components/net/connector.rs
> +    let mut ssl_connector_builder = SslConnectorBuilder::new(SslMethod::tls()).unwrap();
yup!

2017-03-01 11:21 UTC, avadacatavra commented on components/net/cookie.rs
> +        let domain_string = &domain_string.to_lowercase();
tests/net/cookie_http_state.rs::test_domain0026 uses the domain eXaMpLe.org, which causes a failure in domain match--putting to_lowercase() in the relevant locations solved it

2017-03-01 11:23 UTC, avadacatavra commented on components/net/cookie_storage.rs
> +    reg_suffix(url).to_lowercase()
fix for tests/net/cookie_http_state.rs::test_domain0026

2017-03-01 11:24 UTC, nox commented on components/net/cookie.rs
> +        let domain_string = &domain_string.to_lowercase();
You should do a case-insensitive comparison with the `unicase`, and I am not sure the case-insensitivity should apply to all Unicode code points, just ASCII. Do you know where the spec states such things should be case-insensitive?

2017-03-01 17:04 UTC, avadacatavra commented on components/webdriver_server/lib.rs
> +    load_timeout: Option<u64>,
i changed it to an option to be consistent with the TimeoutParameters in webdriver

2017-03-01 17:24 UTC, avadacatavra commented
Review status: 0 of 27 files reviewed at latest revision, 32 unresolved discussions.

---

*[components/net/cookie.rs, line 37 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGL-r1-37:-Ke9tXhIzzUnDBwPrEKU:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/cookie.rs#L37)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Rename to `from_cookie_string`.
</blockquote></details>

Done.

---

*[components/net/cookie.rs, line 43 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGL-r1-43:-Ke9tZbfQDLnCgfPSrWd:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/cookie.rs#L43)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

I'm pretty sure you don't need the type annotation and whatnot here.

```rust
cookie_rs::Cookie::parse(cookie_str)
    .ok()
    .map(|cookie| Cookie::new_wrapped(cookie, request, source))
```
</blockquote></details>

Done.

---

*[components/net/cookie.rs, line 49 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGL-r1-49:-Ke9taKVwWOJyQbqLsQO:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/cookie.rs#L49)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This is unneeded given `cookie` is already a `Cookie<'static>`.
</blockquote></details>

Done.

---

*[components/net/cookie.rs, line 51 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGL-r1-51:-Ke9tcK9iezRYA3NiCJx:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/cookie.rs#L51)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

No need for the `&` anymore to appease the borrow checker, could you clean it up a bit?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:25 UTC, avadacatavra commented
Review status: 0 of 27 files reviewed at latest revision, 32 unresolved discussions.

---

*[components/net/Cargo.toml, line 15 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGJ-r1-15:-Ke9trvB9wGdPGsvtNKJ:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/Cargo.toml#L15)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

No need for that feature anymore.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:27 UTC, avadacatavra commented
Review status: 0 of 27 files reviewed at latest revision, 32 unresolved discussions.

---

*[components/net/http_loader.rs, line 169 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-169:-Ke9u6sB5ffF-aQFLcGf:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L169)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Seems like an error, what's up with all that commented-out code?
</blockquote></details>

Done.

---

*[components/net/http_loader.rs, line 202 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-202:-Ke9u8HwRDtquBnOgslN:b-ldncd5) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L202)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

I think it would be better if we stored the proper type of error that we get instead of `String`, but that can be filed as a follow-up.
</blockquote></details>

let's do that as a follow up so we can get this landed

---

*[components/net/http_loader.rs, line 1137 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-1137:-Ke9uHluyKox5REiaH54:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L1137)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Indentation is broken.
</blockquote></details>

Done.

---

*[components/net/http_loader.rs, line 1146 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-1146:-Ke9uIYxFSjyRfyRm0F3:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L1146)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Indentation is broken.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:27 UTC, avadacatavra commented
Review status: 0 of 27 files reviewed at latest revision, 32 unresolved discussions.

---

*[components/net/lib.rs, line 46 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGO-r1-46:-Ke9uNG9VHhECRxYHoaK:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/lib.rs#L46)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Nit: spurious newline.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:27 UTC, avadacatavra commented
Review status: 0 of 27 files reviewed at latest revision, 32 unresolved discussions.

---

*[components/net/resource_thread.rs, line 336 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGP-r1-336:-Ke9uPb83KgPn_cU-1-c:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/resource_thread.rs#L336)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Indentation is broken.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:28 UTC, avadacatavra commented
Review status: 0 of 27 files reviewed at latest revision, 32 unresolved discussions.

---

*[components/net/connector.rs, line 36 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGK-r1-36:-Ke9udJmwRjGJch07NM4:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/connector.rs#L36)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

yup!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:30 UTC, avadacatavra commented
Review status: 0 of 27 files reviewed at latest revision, 32 unresolved discussions.

---

*[components/net/http_loader.rs, line 205 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-205:-Ke9v43muR9SA4nzZUN-:b5emm72) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L205)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Shouldn't this be implemented on `LoadError`?
</blockquote></details>

can we make this a follow up

---

*[components/net/http_loader.rs, line 211 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-211:-Ke9v03MHuO3jIuQn6wt:b5eod2f) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L211)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Shouldn't this be implemented on `LoadError`?
</blockquote></details>

can we make this a followup?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:36 UTC, avadacatavra commented
Review status: 0 of 27 files reviewed at latest revision, 32 unresolved discussions.

---

*[components/net_traits/Cargo.toml, line 13 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGR-r1-13:-Ke9vUXHHjEkixQGMo-U:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net_traits/Cargo.toml#L13)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This feature is useless now.
</blockquote></details>

Done.

---

*[components/net_traits/lib.rs, line 383 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGS-r1-383:-Ke9vXiLaDww7gpyhV5V:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net_traits/lib.rs#L383)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Indentation is broken. Please realign as it was before.
</blockquote></details>

Done.

---

*[components/net_traits/lib.rs, line 398 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGS-r1-398:-Ke9viRh282urNz4RC_2:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net_traits/lib.rs#L398)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Comment is broken.
</blockquote></details>

Done.

---

*[components/script/Cargo.toml, line 36 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGT-r1-36:-Ke9vkMFFDG6PYK7WhO-:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/Cargo.toml#L36)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This feature is useless now.
</blockquote></details>

Done.

---

*[components/script/webdriver_handlers.rs, line 231 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGW-r1-231:-Ke9vsXQaSuc1edQs4Uq:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/webdriver_handlers.rs#L231)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Why? `cookie` is already a `Cookie<'static>`.
</blockquote></details>

Done.

---

*[components/script/dom/document.rs, line 3106 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGU-r1-3106:-Ke9vvYKM0nnnY9TYieB:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/dom/document.rs#L3106)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Oh I see now why things have been renamed. What about renaming `SetCookieForUrl` to `SetCookieHeaderForUrl` and keep `SetCookiesForUrl` as is?
</blockquote></details>

Done.

---

*[components/script/dom/websocket.rs, line 504 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGV-r1-504:-Ke9wCcfzFp2gNE05kdO:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/dom/websocket.rs#L504)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This can be written in a shorter way:

```rust
cookies.iter().map(ToString::to_string).collect::<String>()
```
</blockquote></details>

Done.

---

*[components/webdriver_server/Cargo.toml, line 13 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGZ-r1-13:-Ke9wFrSDLT_o5e9nzUe:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/webdriver_server/Cargo.toml#L13)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This feature is useless now.
</blockquote></details>

Done.

---

*[components/webdriver_server/lib.rs, line 702 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrG_-r1-702:-Ke9wIs1s8JC7tdrryjV:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/webdriver_server/lib.rs#L702)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Please remove the commented out code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:47 UTC, nox commented
Reviewed 10 of 27 files at r1, 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[components/net/http_loader.rs, line 202 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-202:-Ke9xi0BsY1UJcthpWOq:bj30i2e) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L202)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

let's do that as a follow up so we can get this landed
</blockquote></details>

Ok, don't forget to file it.

---

*[components/net/http_loader.rs, line 205 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-205:-Ke9xkPe9CxQDVlsEVvI:bj30i2e) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L205)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

can we make this a follow up
</blockquote></details>

Ok, don't forget to file it.

---

*[components/net/http_loader.rs, line 211 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGN-r1-211:-Ke9xlqtWkzcde2VFIob:bj30i2e) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/http_loader.rs#L211)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

can we make this a followup?
</blockquote></details>

Ok, don't forget to file it.

---

*[components/net_traits/lib.rs, line 398 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGS-r1-398:-Ke9xyRe5rex6iqOsqFS:b-eaaa64) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net_traits/lib.rs#L398)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You sure?

---

*[components/webdriver_server/lib.rs, line 112 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrG_-r1-112:-Ke9yRaNCODJvrdNYa4R:b-s5dk3g) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/webdriver_server/lib.rs#L112)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

i changed it to an option to be consistent with the TimeoutParameters in webdriver
</blockquote></details>

Oh, nice catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 17:58 UTC, avadacatavra commented
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/net/cookie.rs, line 153 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGL-r1-153:-KeA0VMElK3naC5bAblm:b-clgng2) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/cookie.rs#L153)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

You should do a case-insensitive comparison with the `unicase`, and I am not sure the case-insensitivity should apply to all Unicode code points, just ASCII. Do you know where the spec states such things should be case-insensitive?
</blockquote></details>

let's do this as a followup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 18:01 UTC, nox commented
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/net/cookie.rs, line 153 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGL-r1-153:-KeA0i3qnEq4VvaWzevg:b-72m7ss) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/cookie.rs#L153)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

let's do this as a followup
</blockquote></details>

@jdm Are you ok with this? As for myself, I am.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 18:16 UTC, avadacatavra commented
Review status: 25 of 27 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/net_traits/lib.rs, line 378 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGS-r1-378:-KeA2h0h9RM09cu_W3hO:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net_traits/lib.rs#L378)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Why did you rename `SetCookieForUrl` to `SetCookiesForUrl` and `SetCookiesForUrl` to `SetCookiesForUrlWithData`?
</blockquote></details>

Done.

---

*[components/net_traits/lib.rs, line 398 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGS-r1-398:-KeA2nlE17nOzSYnmL_4:b-upqhej) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net_traits/lib.rs#L398)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

You sure?
</blockquote></details>

i'm just faster with the done button than the push button :)

---

*[components/script/webdriver_handlers.rs, line 192 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGW-r1-192:-KeA45lcl9T1X_VDbSDP:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/webdriver_handlers.rs#L192)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Is this type annotation even necessary?
</blockquote></details>

Done.

---

*[components/script/webdriver_handlers.rs, line 243 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGW-r1-243:-KeA3kFW3h5xH-7yXInf:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/webdriver_handlers.rs#L243)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Why clone `cookie`?
</blockquote></details>

Done.

---

*[components/script/webdriver_handlers.rs, line 244 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGW-r1-244:-KeA3lITQK5r5vR_JorQ:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/webdriver_handlers.rs#L244)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Why clone `cookie`'s domain?
</blockquote></details>

Done.

---

*[components/webdriver_server/lib.rs, line 112 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrG_-r1-112:-KeA3px1G9d88d8NLQEX:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/webdriver_server/lib.rs#L112)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Oh, nice catch.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-01 23:58 UTC, avadacatavra commented
Review status: 24 of 27 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/net/cookie_storage.rs, line 39 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGM-r1-39:-KeBIqx6DmwPd_p7SuJS:b5gobyi) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/cookie_storage.rs#L39)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I have no clue. the only change I made was domain -> domain()

---

*[components/script/dom/websocket.rs, line 506 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGV-r1-506:-KeBHnNGwU2_opIpC-BW:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/dom/websocket.rs#L506)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Could you use `SetCookiesForUrlWithData` instead, parsing each `String` from the `SetCookie` header to a `Cookie` before sending it? I would rather not roundtrip through a longer string only to split it again afterwards.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-02 00:12 UTC, nox commented
Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/webdriver_handlers.rs, line 192 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGW-r1-192:-KeBLsmx-HC2IRK_QMr6:b-j6gf8h) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/webdriver_handlers.rs#L192)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is still one remaining.

---

*[components/script/dom/websocket.rs, line 502 at r4](https://reviewable.io:443/reviews/servo/servo/15775#-KeBL5aT35T4qt5TgEWS:-KeBL5aT35T4qt5TgEWT:b-c8kr96) ([raw file](https://github.com/servo/servo/blob/e0de1727c96702a01dd17639dae0720da0335196/components/script/dom/websocket.rs#L502)):*
> ```Rust
>         // Step 5: Cookies.
>         if let Some(cookies) =  self.headers.get::<hyper::header::SetCookie>() {
>             for cookie in cookies.iter() {
> ```

Sorry my previous comment wasn't clear enough.

I meant to first parse each cookie, collecting that in a `Vec` and sending that `Vec`.

```rust
let cookies = cookies.into_iter().filter_map(|cookie| {
    cookie_rs::Cookie::parse(cookie.to_string()).ok()
});
```

Note that we use `filter_map`, because AFAIK some parts of the header could be invalid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-02 00:29 UTC, avadacatavra commented
Review status: 26 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/webdriver_handlers.rs, line 192 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGW-r1-192:-KeBPimWNEo5IF4gouaR:b-896fix) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/script/webdriver_handlers.rs#L192)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

There is still one remaining.
</blockquote></details>

Done.

---

*[components/script/dom/websocket.rs, line 502 at r4](https://reviewable.io:443/reviews/servo/servo/15775#-KeBL5aT35T4qt5TgEWS:-KeBPjbUs68ibHQtdSFX:b8es8yo) ([raw file](https://github.com/servo/servo/blob/e0de1727c96702a01dd17639dae0720da0335196/components/script/dom/websocket.rs#L502)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Sorry my previous comment wasn't clear enough.

I meant to first parse each cookie, collecting that in a `Vec` and sending that `Vec`.

```rust
let cookies = cookies.into_iter().filter_map(|cookie| {
    cookie_rs::Cookie::parse(cookie.to_string()).ok()
});
```

Note that we use `filter_map`, because AFAIK some parts of the header could be invalid.
</blockquote></details>

SetCookiesForUrl apparently only takes one cookie. Do you want me to change it to take a vec?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-02 00:33 UTC, nox commented
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/net_traits/lib.rs, line 383 at r5](https://reviewable.io:443/reviews/servo/servo/15775#-KeBQTSEv0IXuoBj7qf9:-KeBQTSEv0IXuoBj7qfA:b-m6befx) ([raw file](https://github.com/servo/servo/blob/56bfb9394c3863fde679599f7bcf754695040a81/components/net_traits/lib.rs#L383)):*
> ```Rust
>                         #[serde(deserialize_with = "hyper_serde::deserialize",
>                                 serialize_with = "hyper_serde::serialize")]
>                         Cookie<'static>,
> ```

Change that to `Vec<Serde<Cookie<'static>>>`.

---

*[components/net_traits/lib.rs, line 389 at r5](https://reviewable.io:443/reviews/servo/servo/15775#-KeBQ_JOF9x7JWG6km-r:-KeBQ_JOF9x7JWG6km-s:b-a60mja) ([raw file](https://github.com/servo/servo/blob/56bfb9394c3863fde679599f7bcf754695040a81/components/net_traits/lib.rs#L389)):*
> ```Rust
>     /// Get a cookie by name for a given originating URL
>     GetCookiesDataForUrl(ServoUrl, IpcSender<Vec<Serde<Cookie<'static>>>>, CookieSource),
>      /// Store a cookie for a given originating URL
> ```

This seems to be the comment for `SetCookieHeaderForUrl`.

---

*[components/script/dom/websocket.rs, line 502 at r4](https://reviewable.io:443/reviews/servo/servo/15775#-KeBL5aT35T4qt5TgEWS:-KeBQGQbhY9G408TsPYW:bncy2n9) ([raw file](https://github.com/servo/servo/blob/e0de1727c96702a01dd17639dae0720da0335196/components/script/dom/websocket.rs#L502)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

SetCookiesForUrl apparently only takes one cookie. Do you want me to change it to take a vec?
</blockquote></details>

You changed it to a single cookie, it used to take a `Vec<Serde<Cookie>>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775#-:-KeBQo74CctaBttL4kgn:bo47p9t)*
<!-- Sent from Reviewable.io -->

2017-03-02 12:01 UTC, nox commented
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/net/cookie.rs, line 153 at r1](https://reviewable.io:443/reviews/servo/servo/15775#-Ke7nHVVA-wddq30NrGL-r1-153:-KeDtFc0UaWectmVIymk:b53q7f8) ([raw file](https://github.com/servo/servo/blob/43bb670cd8beb4ea29160b9d5b0ff72a303a9dda/components/net/cookie.rs#L153)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

@jdm Are you ok with this? As for myself, I am.
</blockquote></details>

@jdm didn't reply so I guess he doesn't mind the followup.

---

*[components/net/resource_thread.rs, line 168 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDqqm-H7_l1HVIfOGr:-KeDqqm-H7_l1HVIfOGs:b-dsxhzs) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/net/resource_thread.rs#L168)):*
> ```Rust
>                 self.resource_manager.set_cookie_header_for_url(request, cookie_list, source, group),
>             CoreResourceMsg::SetCookiesForUrl(request, cookies, source) =>
>                 self.resource_manager.set_cookies_for_url(request, cookies, source, group),
> ```

This used to be a loop over `cookies` with a call to `set_cookie_for_url`, please go back to that version.

---

*[components/net/resource_thread.rs, line 337 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDr2oZtIsBb996kKTx:-KeDr2oZtIsBb996kKTy:b-l1b95g) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/net/resource_thread.rs#L337)):*
> ```Rust
>                 cookie_jar.push(cookie, &request, source)
>             }
>         }
> ```

Please make that the old `set_cookie_for_url` method that was taking a plain old `cookie_rs::Cookie`.

---

*[components/net_traits/lib.rs, line 377 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDrEV1fsBxBgYkpE5B:-KeDrEV1fsBxBgYkpE5C:b-jq3jdb) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/net_traits/lib.rs#L377)):*
> ```Rust
>     /// Try to make a websocket connection to a URL.
>     WebsocketConnect(WebSocketCommunicate, WebSocketConnectData),
>     /// Store a set of cookies for a given originating URL
> ```

This comment is still wrong.

---

*[components/net_traits/lib.rs, line 385 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDrCsSoehhD4vMi_21:-KeDrCsSoehhD4vMi_22:bcxsidq) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/net_traits/lib.rs#L385)):*
> ```Rust
>     /// Get a cookie by name for a given originating URL
>     GetCookiesDataForUrl(ServoUrl, IpcSender<Vec<Serde<Cookie<'static>>>>, CookieSource),
>      /// Store a cookie for a given originating URL
> ```

This comment is still out of place.

---

*[components/script/webdriver_handlers.rs, line 248 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDt6NKEBzyI-OUIg8o:-KeDsESkLaxr5MQ6Cl37:b5xo41p) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/script/webdriver_handlers.rs#L248)):*
> ```Rust
>         (false, Some(ref domain)) if url.host_str().map(|x| { x == domain }).unwrap_or(false) => {
>             let _ = document.window().upcast::<GlobalScope>().resource_threads().send(
>                 SetCookiesForUrl(url, vec!(Serde(cookie)), method)
> ```

See the comment in `document.rs` about a follow-up issue.

---

*[components/script/dom/document.rs, line 3106 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDsa_UNnEGy_sm0In7:-KeDsa_UNnEGy_sm0In8:bpdcu7) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/script/dom/document.rs#L3106)):*
> ```Rust
>                     .upcast::<GlobalScope>()
>                     .resource_threads()
>                     .send(SetCookieHeaderForUrl(self.url(), String::from(cookie), NonHTTP));
> ```

So I've come to realise that we shouldn't have touched `SetCookieForUrl` at all, and that this code here should use `SetCookiesForUrl`, parsing the header and then each part as a cookie like in `websocket.rs`.

This way we still have only two commands `SetCookieForUrl` and `SetCookiesForUrl` just like before, and we can avoid the silly `vec![]` expression in `webdriver_handlers.rs`.

Please do it now or file a follow-up about it.

---

*[components/script/dom/websocket.rs, line 505 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDs5a2Zlq9RV5yYDkM:-KeDs5a2Zlq9RV5yYDkN:b-cq6kip) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/script/dom/websocket.rs#L505)):*
> ```Rust
>             let cookies = cookies.0.iter().filter_map(|cookie| {
>                 cookie_rs::Cookie::parse(cookie.to_string()).ok().map(Serde)
>             }).collect::<Vec<Serde<cookie_rs::Cookie>>>();
> ```

Remove the type annotation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775#-:-KeDtMj0o0EKCPUIxn_n:bo47p9t)*
<!-- Sent from Reviewable.io -->

2017-03-02 13:47 UTC, avadacatavra commented
Review status: 25 of 27 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/net/resource_thread.rs, line 337 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDr2oZtIsBb996kKTx:-KeE5o1oCgMB2ccSNtfe:b-896fix) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/net/resource_thread.rs#L337)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Please make that the old `set_cookie_for_url` method that was taking a plain old `cookie_rs::Cookie`.
</blockquote></details>

Done.

---

*[components/net_traits/lib.rs, line 383 at r5](https://reviewable.io:443/reviews/servo/servo/15775#-KeBQTSEv0IXuoBj7qf9:-KeE5klFvS9vb6077YcW:b-896fix) ([raw file](https://github.com/servo/servo/blob/56bfb9394c3863fde679599f7bcf754695040a81/components/net_traits/lib.rs#L383)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Change that to `Vec<Serde<Cookie<'static>>>`.
</blockquote></details>

Done.

---

*[components/net_traits/lib.rs, line 389 at r5](https://reviewable.io:443/reviews/servo/servo/15775#-KeBQ_JOF9x7JWG6km-r:-KeE5mDb7aVesvu1rbZK:b-896fix) ([raw file](https://github.com/servo/servo/blob/56bfb9394c3863fde679599f7bcf754695040a81/components/net_traits/lib.rs#L389)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This seems to be the comment for `SetCookieHeaderForUrl`.
</blockquote></details>

Done.

---

*[components/net_traits/lib.rs, line 377 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDrEV1fsBxBgYkpE5B:-KeE5jzq6knkTySWLNxr:b-896fix) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/net_traits/lib.rs#L377)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This comment is still wrong.
</blockquote></details>

Done.

---

*[components/net_traits/lib.rs, line 385 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDrCsSoehhD4vMi_21:-KeE5leXODYBfuk7Rhdg:b-896fix) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/net_traits/lib.rs#L385)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This comment is still out of place.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-02 13:58 UTC, nox commented
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/net_traits/lib.rs, line 377 at r7](https://reviewable.io:443/reviews/servo/servo/15775#-KeEImGgSJwY1HEcguo5:-KeEImGgSJwY1HEcguo6:b-ht4wzz) ([raw file](https://github.com/servo/servo/blob/5160bcc14e130de872cf2f04e7aca7185355e8a5/components/net_traits/lib.rs#L377)):*
> ```Rust
>     /// Try to make a websocket connection to a URL.
>     WebsocketConnect(WebSocketCommunicate, WebSocketConnectData),
>     /// Store a set of cookies and set cookies for header for a given originating URL
> ```

"Store a set of cookies from a raw cookie header."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775#-:-KeEJ798Aj-QZZN08_59:bo47p9t)*
<!-- Sent from Reviewable.io -->

2017-03-02 16:30 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15798) made this pull request unmergeable. Please resolve the merge conflicts.

2017-03-03 06:45 UTC, jdm commented
FYI: I haven't been following any of the discussion due to travel. Use your best judgement.

2017-03-03 09:28 UTC, nox commented
@jdm We will just lowercase all the things and file a followup then.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/net/resource_thread.rs, line 329 at r8](https://reviewable.io:443/reviews/servo/servo/15775#-KeISYFSwt5X3ER30b8J:-KeISYFSwt5X3ER30b8K:bhvyioh) ([raw file](https://github.com/servo/servo/blob/66add34c3457eaf243dc0c6fce4ae6a23064c4f2/components/net/resource_thread.rs#L329)):*
> ```Rust
>             }
>         }
>     }*/
> ```

Just remove the method.

---

*[components/net_traits/lib.rs, line 377 at r8](https://reviewable.io:443/reviews/servo/servo/15775#-KeIRmmJbip6fLwHIQ34:-KeIRmmJbip6fLwHIQ35:biwkh21) ([raw file](https://github.com/servo/servo/blob/66add34c3457eaf243dc0c6fce4ae6a23064c4f2/components/net_traits/lib.rs#L377)):*
> ```Rust
>     /// Try to make a websocket connection to a URL.
>     WebsocketConnect(WebSocketCommunicate, WebSocketConnectData),
>     /// Store a set of cookies from a raw cookie header
> ```

I'm afraid my friend that this comment suggestion was for when `SetCookieForUrl` was holding a `String`. :P

The good news though is that you can just use the comment that was here before your changes.

---

*[components/script/dom/document.rs, line 3113 at r8](https://reviewable.io:443/reviews/servo/servo/15775#-KeITkV232oMYY6AQUBE:-KeIS28hw6uvaOeylAD9:b-t3y610) ([raw file](https://github.com/servo/servo/blob/66add34c3457eaf243dc0c6fce4ae6a23064c4f2/components/script/dom/document.rs#L3113)):*
> ```Rust
>                           },
>             Err(_) => return Err(Error::Security)
>         }
> ```

A few final changes needed:

 * This should first parse the input (`cookie`) as a `SetCookie` header.
 * This should use `SetCookiesForUrl`.
 * This should not fail on parsing errors.

```rust
if let Ok(cookie_header) = SetCookie::parse_header(&[cookie.into_bytes()]) {
    let cookies = cookie_header.1.into_iter().filter_map(|cookie| {
        cookie_rs::Cookie::parse(cookie).ok().map(Serde)
    });
    let _ = self.window....;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775#-:-KeIUuE96oofB9cesOA9:b-8z3to3)*
<!-- Sent from Reviewable.io -->

2017-03-06 00:32 UTC, avadacatavra commented
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/net/resource_thread.rs, line 168 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDqqm-H7_l1HVIfOGr:-KeW0yKHdY24C0vKkM3q:b-896fix) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/net/resource_thread.rs#L168)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

This used to be a loop over `cookies` with a call to `set_cookie_for_url`, please go back to that version.
</blockquote></details>

Done.

---

*[components/net/resource_thread.rs, line 329 at r8](https://reviewable.io:443/reviews/servo/servo/15775#-KeISYFSwt5X3ER30b8J:-KeW-BbSy3_2cFIq3-ep:b-pqg2v5) ([raw file](https://github.com/servo/servo/blob/66add34c3457eaf243dc0c6fce4ae6a23064c4f2/components/net/resource_thread.rs#L329)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

Just remove the method.
</blockquote></details>

sorry forgot to delete that :) done

---

*[components/net_traits/lib.rs, line 377 at r8](https://reviewable.io:443/reviews/servo/servo/15775#-KeIRmmJbip6fLwHIQ34:-KeW-chSAGnvsYeNFJg1:b-896fix) ([raw file](https://github.com/servo/servo/blob/66add34c3457eaf243dc0c6fce4ae6a23064c4f2/components/net_traits/lib.rs#L377)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

I'm afraid my friend that this comment suggestion was for when `SetCookieForUrl` was holding a `String`. :P

The good news though is that you can just use the comment that was here before your changes.
</blockquote></details>

Done.

---

*[components/script/dom/document.rs, line 3106 at r6](https://reviewable.io:443/reviews/servo/servo/15775#-KeDsa_UNnEGy_sm0In7:-KeW-hgtB1Q5ZwRXgYOD:b-896fix) ([raw file](https://github.com/servo/servo/blob/83011fb6e8552689289b6a3a2436c2fd6d6f2de9/components/script/dom/document.rs#L3106)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

So I've come to realise that we shouldn't have touched `SetCookieForUrl` at all, and that this code here should use `SetCookiesForUrl`, parsing the header and then each part as a cookie like in `websocket.rs`.

This way we still have only two commands `SetCookieForUrl` and `SetCookiesForUrl` just like before, and we can avoid the silly `vec![]` expression in `webdriver_handlers.rs`.

Please do it now or file a follow-up about it.
</blockquote></details>

Done.

---

*[components/script/dom/document.rs, line 3113 at r8](https://reviewable.io:443/reviews/servo/servo/15775#-KeITkV232oMYY6AQUBE:-KeW0uq9Pbk4BffSqsgv:b-896fix) ([raw file](https://github.com/servo/servo/blob/66add34c3457eaf243dc0c6fce4ae6a23064c4f2/components/script/dom/document.rs#L3113)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

A few final changes needed:

 * This should first parse the input (`cookie`) as a `SetCookie` header.
 * This should use `SetCookiesForUrl`.
 * This should not fail on parsing errors.

```rust
if let Ok(cookie_header) = SetCookie::parse_header(&[cookie.into_bytes()]) {
    let cookies = cookie_header.1.into_iter().filter_map(|cookie| {
        cookie_rs::Cookie::parse(cookie).ok().map(Serde)
    });
    let _ = self.window....;
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-06 13:37 UTC, avadacatavra commented
Review status: 24 of 27 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/net/resource_thread.rs, line 329 at r8](https://reviewable.io:443/reviews/servo/servo/15775#-KeISYFSwt5X3ER30b8J:-KeW26X9Mf4hi1sVZZ3W:b-896fix) ([raw file](https://github.com/servo/servo/blob/66add34c3457eaf243dc0c6fce4ae6a23064c4f2/components/net/resource_thread.rs#L329)):*
<details><summary><i>Previously, avadacatavra (Diane Hosfelt) wrote…</i></summary><blockquote>

sorry forgot to delete that :) done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775)*
<!-- Sent from Reviewable.io -->

2017-03-07 08:37 UTC, nox commented
-S-awaiting-review -S-needs-rebase +S-needs-code-changes 

---

Reviewed 8 of 8 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/15775#-KebtdhkH3nXzIZb47kD:-KebtdhkH3nXzIZb47kE:bvc72k6) (no related file):*
You seem to have ran `./mach cargo-update -a`, don't do that, and please revert the unrelated bumps from Cargo.lock.

---

*[components/net_traits/lib.rs, line 377 at r9](https://reviewable.io:443/reviews/servo/servo/15775#-Kebttmtvd_9ut-QOEGj:-Kebttmtvd_9ut-QOEGk:bcujtcb) ([raw file](https://github.com/servo/servo/blob/fc0c616e8812ad87ea24a4f3bc20e152c16371f7/components/net_traits/lib.rs#L377)):*
> ```Rust
>     /// Try to make a websocket connection to a URL.
>     WebsocketConnect(WebSocketCommunicate, WebSocketConnectData),
>     /// Store a set of cookies and set cookies for header for a given originating URL
> ```

That comment is still wrong?

---

*[components/script/dom/document.rs, line 3113 at r8](https://reviewable.io:443/reviews/servo/servo/15775#-KeITkV232oMYY6AQUBE:-KebuKARURT-g-fQZ7AR:b-odnqj) ([raw file](https://github.com/servo/servo/blob/66add34c3457eaf243dc0c6fce4ae6a23064c4f2/components/script/dom/document.rs#L3113)):*
There should be no error case for failing to parse, check the code before all your changes.

As I said earlier:

> This should not fail on parsing errors.

Remove the whole `else` branch thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775#-:-Kebtj7PxPyKifqXotuk:bey972u)*
<!-- Sent from Reviewable.io -->

2017-03-08 08:15 UTC, nox commented
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/Cargo.toml, line 61 at r10](https://reviewable.io:443/reviews/servo/servo/15775#-KegyxyZS6tfYc9dyJcR:-KegyxyZS6tfYc9dyJcS:bvozp9j) ([raw file](https://github.com/servo/servo/blob/c9df2b0989960f6cb6021cf1c3dae6af02afda59/components/script/Cargo.toml#L61)):*
> ```TOML
> mime_guess = "1.8.0"
> msg = {path = "../msg"}
> net = {path = "../net"}
> ```

This is unneeded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15775#-:-Kegz3OgAjC05rHGSAl_:bo47p9t)*
<!-- Sent from Reviewable.io -->

2017-03-08 10:52 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15849) made this pull request unmergeable. Please resolve the merge conflicts.

2017-03-08 11:04 UTC, nox commented
Fixed that last nit myself and rebased it in #15868. Congrats @avadacatavra.

2017-03-08 11:04 UTC, closed without merging