Make SSL tests work in some configurations
servo/servo pull request #15784
Opened 2017-03-01 19:00 UTC by jdm

I got this working on the plane and want other people to take a look at it. I discovered that:
* if I have a proper /etc/hosts setup per the wpt/README.md
* I disable Servo's host replacement code
* I make Servo use the certs generated by openssl during the harness setup
then I can run SSL tests successfully as part of WPT. The host replacement gets in the way because the openssl host verification code sees 127.0.0.1 when we do Servo-side replacement, and that doesn't match the web-platform.test domain. @jgraham do you know how Firefox handles this? I'm pretty sure it doesn't require every person who wants to run https tests to modify their hosts file.

2017-03-01 19:00 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @jgraham: tests/wpt/harness/wptrunner/executors/executorservo.py, tests/wpt/harness/wptrunner/browsers/servo.py
 * @fitzgen: components/script/dom/document.rs, components/script/dom/htmlimageelement.rs, components/script/document_loader.rs, components/script/script_thread.rs
 * @kichjang: components/script/dom/document.rs, components/script/dom/htmlimageelement.rs, components/script/document_loader.rs, components/script/script_thread.rs, components/net/connector.rs

2017-03-01 19:00 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-03-01 19:01 UTC, jdm commented
This addresses the issue tracked in #6919.

2017-03-01 19:01 UTC, jdm commented
Whoops, I only meant to include the last commit in this branch. Anyways, ignore the others.

2017-03-02 12:02 UTC, jgraham commented
Firefox has a pref that mimics the behaviour of /etc/hosts so from the point of view of the networking code the domain and certificate match [1] and uses certutil to actually install the certificates into the local certificate database [2].

[1] https://dxr.mozilla.org/mozilla-central/source/testing/web-platform/harness/wptrunner/browsers/firefox.py#139
[2] https://dxr.mozilla.org/mozilla-central/source/testing/web-platform/harness/wptrunner/browsers/firefox.py#227

2017-03-08 13:20 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15771) made this pull request unmergeable. Please resolve the merge conflicts.

2017-04-06 08:51 UTC, jdm commented
@nox, the network changes should be familiar to you now. @jgraham could you sign off on the wptrunner changes?

2017-04-06 09:03 UTC, nox requested changes
Commits "Update mozilla/ WPT results." and "Update results for remaining https tests in WPT." need to be squashed with "Only replace hosts when making TCP connections, not when verifying SSL certificates."

And you would please the old man I am if you would shorten that last commit title I had trouble pasting.

2017-04-06 09:03 UTC, nox commented on components/net/connector.rs
> +    };
Wait, so the argument is ignored if there is a `certificate_path`? Please either pass the `certificate_path` option to the function in callers, or remove the argument altogether; it feels weird that the option takes precedence over the argument.

2017-04-06 09:03 UTC, nox commented on components/net/http_loader.rs
> +        self.connector.connect(host, port, scheme)
<s>This implementation exists only to do that `replace_host` call, now that it is gone you can pass `&self.connector` again to `HyperRequest::with_connector` in `NetworkHttpRequestFactory::create` and remove this impl altogether.</s>

Hah, you killed the whole wrapper in next commit, nice!

2017-04-06 09:03 UTC, nox commented on components/net/http_loader.rs
> +    let wrapped_response = obtain_response(context.connector.clone(), &url, &request.method,
AFAIK this clone is pointless, and you can pass `&Pool<Connector>` to `obtain_response`.

2017-04-06 09:11 UTC, jdm commented on components/net/http_loader.rs
> +    let wrapped_response = obtain_response(context.connector.clone(), &url, &request.method,
That was what I tried originally, and Rust's type checker became _so confused_ that I didn't want to try to debug. Please don't make me investigate it; it ends up trying to use the closure connector feature instead and it's not worth it.

2017-04-06 09:40 UTC, jgraham commented
Reviewed 1 of 3 files at r1.
Review status: 1 of 942 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15784)*
<!-- Sent from Reviewable.io -->

2017-04-06 09:41 UTC, jgraham commented
wptrunner changes look fine; please remember to upstream them.

2017-04-06 09:51 UTC, jdm commented
@bors-servo: r=nox,jgraham

2017-04-06 09:51 UTC, bors-servo commented
:pushpin: Commit ca2cc00 has been approved by `nox,jgraham`

<!-- @bors-servo r=nox,jgraham ca2cc001969fe82b2e8d97c4b70e21492c267a3f -->

2017-04-06 09:51 UTC, bors-servo commented
:hourglass: Testing commit ca2cc001969fe82b2e8d97c4b70e21492c267a3f with merge cd1dbf71e1b8567011e6f85de3f7fe360f18468e...

2017-04-06 10:13 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3204)

2017-04-06 10:26 UTC, jdm commented
@bors-servo: r=nox,jgraham

2017-04-06 10:26 UTC, bors-servo commented
:pushpin: Commit 6f590a8 has been approved by `nox,jgraham`

<!-- @bors-servo r=nox,jgraham 6f590a87bfaefd6daeafa6e422e9f1eee5c0cd94 -->

2017-04-06 10:53 UTC, bors-servo commented
:hourglass: Testing commit 6f590a87bfaefd6daeafa6e422e9f1eee5c0cd94 with merge f3fd8238ce1f7b2eb74d4fccbe76cfac8aa2335a...

2017-04-06 11:27 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6161), [arm32](http://build.servo.org/builders/arm32/builds/6381), [arm64](http://build.servo.org/builders/arm64/builds/6414), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6516), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3247), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3269), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6521), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6550), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3206), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3273), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1689)
Approved by: nox,jgraham
Pushing f3fd8238ce1f7b2eb74d4fccbe76cfac8aa2335a to master...

2017-04-06 11:27 UTC, merged