Replace manual host parsing code with parse-host crate
servo/servo pull request #15783
Opened 2017-03-01 16:52 UTC by ferjm

This patch is replacing the code to parse the hosts file with the [parse-hosts](https://crates.io/crates/parse-hosts) crate. This crate has a [CC0 1.0 Universal License](https://creativecommons.org/publicdomain/zero/1.0/deed.en).

I could have used [HostsFile::load()](https://clarcharr.github.io/parse-hosts/parse_hosts/struct.HostsFile.html#method.load) directly, but this method loads `/etc/hosts` by default and does not allow to override the default path (for example with [env::var("HOST_FILE")](https://dxr.mozilla.org/servo/source/components/net_traits/hosts.rs#19)), so I kept the existing code to open and read the content of `env::var("HOST_FILE")` and also kept the [parse_hostsfile](https://dxr.mozilla.org/servo/source/components/net_traits/hosts.rs#42) method (used by the unit tests), but I modified it to use [HostsFile::read_buffered](https://clarcharr.github.io/parse-hosts/parse_hosts/struct.HostsFile.html#method.read_buffered), which is doing the actual hosts parsing for a given string buffer.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15756 .
- [X] There are tests for these changes (tests/unit/net/resource_thread.rs and tests/unit/net/http_loader.rs)

2017-03-02 01:00 UTC, KiChjang commented
r? @avadacatavra

2017-03-08 12:30 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15865) made this pull request unmergeable. Please resolve the merge conflicts.

2017-03-08 22:42 UTC, avadacatavra reviewed
It looks like the most current version of parse-host is 0.3.0. Is there any reason we're using 0.2.0 instead?

2017-03-09 09:20 UTC, ferjm commented
@avadacatavra no reason at all. I saw 0.2.0 being used in the documentation and I didn't realize that there is a newer version. I just updated the PR. Thank you!

2017-03-09 20:33 UTC, avadacatavra requested changes
It looks good to me. Please squash the commits first though

2017-03-09 21:36 UTC, ferjm commented
@avadacatavra done. Thanks!

2017-03-09 22:31 UTC, avadacatavra approved these changes

2017-03-09 22:38 UTC, KiChjang commented
@bors-servo r=avadacatavra

2017-03-09 22:38 UTC, bors-servo commented
:pushpin: Commit 79b7b9d has been approved by `avadacatavra`

<!-- @bors-servo r=avadacatavra 79b7b9de54e42469b6d1a1ad096ea8edebeefd2d -->

2017-03-09 22:38 UTC, bors-servo commented
:hourglass: Testing commit 79b7b9d with merge 8372869...

2017-03-09 23:02 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2790)

2017-03-09 23:11 UTC, avadacatavra commented
@bors-servo r+

2017-03-09 23:11 UTC, bors-servo commented
@avadacatavra: :key: Insufficient privileges: Not in reviewers

2017-03-09 23:18 UTC, Manishearth commented
@bors-servo r=avadacatavra delegate=avadacatavra

2017-03-09 23:18 UTC, bors-servo commented
:v: @avadacatavra can now approve this pull request

2017-03-09 23:18 UTC, bors-servo commented
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.
- There's another pull request that is currently being tested, blocking this pull request: #15893

2017-03-09 23:18 UTC, bors-servo commented
:pushpin: Commit 79b7b9d has been approved by `avadacatavra`

<!-- @bors-servo r=avadacatavra 79b7b9de54e42469b6d1a1ad096ea8edebeefd2d -->

2017-03-09 23:22 UTC, avadacatavra commented
@bors-servo try

2017-03-10 01:17 UTC, KiChjang commented
@bors-servo try- retry
* #15898

2017-03-10 01:17 UTC, bors-servo commented
:hourglass: Testing commit 79b7b9d with merge 8f7c69e...

2017-03-10 01:57 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5696), [arm32](http://build.servo.org/builders/arm32/builds/5929), [arm64](http://build.servo.org/builders/arm64/builds/5952), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6065), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2772), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2793), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6060), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6088), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2735), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2812), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1227), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1226)
Approved by: avadacatavra
Pushing 8f7c69e15f0b9beddad2ba67e3419f88aca0d579 to master...

2017-03-10 01:57 UTC, merged