Implement EventListenerOptions for EventTarget
servo/servo pull request #15803
Opened 2017-03-02 23:14 UTC by GuillaumeGomez

It still needs to update tests and confirm that the code is the one expected. Reopening of #12952.

2017-03-02 23:14 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/eventtarget.rs, components/script/dom/mediaquerylist.rs, components/script/dom/webidls/EventTarget.webidl
 * @kichjang: components/script/dom/eventtarget.rs, components/script/dom/mediaquerylist.rs, components/script/dom/webidls/EventTarget.webidl

2017-03-02 23:14 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-03-03 09:49 UTC, nox commented
It's not. In https://github.com/servo/servo/pull/12952#issuecomment-241336248 @Ms2ger mentions we only want to support the `capture` key for now, given we don't implement the features related to the other keys.

2017-03-03 21:42 UTC, GuillaumeGomez commented
So you want me to comment all `::Boolean` cases for now?

2017-03-09 08:17 UTC, nox commented
I don't understand the question.

I want:

```webidl
dictionary EventListenerOptions {
  boolean capture = false;
};

dictionary AddEventListenerOptions : EventListenerOptions {
  // boolean passive = false;
  // boolean once = false;
};
```

2017-03-09 10:16 UTC, GuillaumeGomez commented
Ok, makes more sense. I thought you were only speaking of the usage, not the declaration.

2017-03-15 09:21 UTC, Ms2ger commented
@GuillaumeGomez ping

2017-03-15 09:59 UTC, GuillaumeGomez commented
Sorry, was busy because of rustdoc. Will finish it this week-end.

2017-03-18 14:17 UTC, GuillaumeGomez commented
Updated.

2017-03-19 12:46 UTC, nox commented on components/script/dom/eventtarget.rs
> +    removed: bool,
Don't add fields for which we don't support the corresponding thing, so just add `capture`.

2017-03-19 21:31 UTC, GuillaumeGomez commented
Updated.

2017-03-21 08:23 UTC, nox requested changes

2017-03-21 08:23 UTC, nox commented on components/script/dom/eventtarget.rs
> +    // removed: bool,
Remove that.

2017-03-21 08:23 UTC, nox commented on components/script/dom/eventtarget.rs
> +                        // removed: false,
Remove that.

2017-03-21 08:23 UTC, nox commented on components/script/dom/eventtarget.rs
> +            };
```rust
let capture = match options {
    AddEventListenerOptionsOrBoolean::AddEventListenerOptions(options) => options.capture,
    AddEventListenerOptionsOrBoolean::Boolean(capture) => capture,
};

2017-03-21 08:23 UTC, nox commented on components/script/dom/eventtarget.rs
> +        if let Some(listener) = listener {
Why that change? Please early return just like before.

2017-03-21 08:23 UTC, nox commented on components/script/dom/eventtarget.rs
> +                // removed: false,
Remove.

2017-03-21 08:23 UTC, nox commented on components/script/dom/eventtarget.rs
> +        if let Some(ref listener) = listener {
Early return just like before.

2017-03-21 08:23 UTC, nox commented on components/script/dom/eventtarget.rs
> +    capture: bool,
This new field is useless for now, given `phase` already covers it, please remove.

2017-03-21 08:23 UTC, nox commented on components/script/dom/eventtarget.rs
> +                    // removed: false,
Remove that.

2017-03-22 22:47 UTC, GuillaumeGomez commented
Updated.

2017-03-24 10:50 UTC, nox commented
@bors-servo try

2017-03-24 10:50 UTC, nox approved these changes

2017-03-24 10:50 UTC, bors-servo commented
:hourglass: Trying commit 078931af7826e7a0e50f6b517f35c36050d5df24 with merge a8afb0c3fd011eab309b5a7d32394412a9c39a0d...

2017-03-24 11:34 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3028)

2017-03-24 14:00 UTC, jdm commented
All tests are failing with errors like:
```
  │ ERROR:script::dom::bindings::error: Error at http://web-platform.test:8000/resources/testharness.js:663:9 Value not an object.
  │ ERROR:script::dom::bindings::error: Error at http://web-platform.test:8000/resources/testharnessreport.js:8:1 setup is not defined
  └ ERROR:script::dom::bindings::error: Error at http://web-platform.test:8000/css-flexbox-1_dev/html/flexbox_computedstyle_flex-direction-column-reverse.htm:16:1 test is not defined
```

2017-04-12 03:47 UTC, jdm commented
@GuillaumeGomez Are you planning to return to this?

2017-04-12 11:18 UTC, GuillaumeGomez commented
Yes, I'm currently working on it (slowly but still).

2017-04-13 12:28 UTC, GuillaumeGomez commented
Actually I'm completely stuck in here and I have no idea what change broke everything. If anyone could help, it'd very appreciated!

2017-07-21 23:55 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17822) made this pull request unmergeable. Please resolve the merge conflicts.

2017-09-24 14:01 UTC, nox commented
Superseded by #18612. Thanks for your contribution!

2017-09-24 14:01 UTC, closed without merging