Update border.mako.rs
servo/servo pull request #15820
Opened 2017-03-04 19:22 UTC by snehasi

added check for w and o

Subject: Fixes #15770 
Content:
Added a check on line 225 of border.mako.rs, if `w` and `o` are none.
Fixed issue #15770

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-03-04 19:23 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @asajeffrey (or someone else) soon.

2017-03-04 19:23 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/properties/shorthand/border.mako.rs
 * @emilio: components/style/properties/shorthand/border.mako.rs

2017-03-04 19:23 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2017-03-04 23:10 UTC, SimonSapin commented
Please edit this pull request’s title and initial message to be descriptive of what changes it makes, not just with a file name or an issue number.

2017-03-05 08:58 UTC, KiChjang commented on components/style/properties/shorthand/border.mako.rs
> +                            if ${w}.is_none() && ${o}.is_none {
Looks wrong. Both w and o are not python mako template variables, they're actual Rust variables.

2017-03-05 14:13 UTC, nox commented
"Added check for w and o in border.mako.rs" is not descriptive. Please describe in a very short sentence what that PR actually fixes, not how it fixes it.

2017-03-07 05:42 UTC, snehasi commented
Sorry for the rookie errors. 
I have fixed the PR statement and the error in the code.

2017-03-07 09:07 UTC, nox commented
No problem, thanks for keeping up with it. :)

2017-03-07 09:08 UTC, nox commented
r? @Kic

2017-03-07 09:09 UTC, nox commented
r? @KiChjang

2017-03-07 10:57 UTC, KiChjang requested changes

2017-03-07 10:57 UTC, KiChjang commented on components/style/properties/shorthand/border.mako.rs
> +                            if ${w}.is_none() && ${o}.is_none() {
Still looks wrong. If it wasn't clear in my last comment, `${}` is used in the Python mako template as Python expression evaluation, and w and o here are Rust variables.

2017-03-08 05:05 UTC, KiChjang commented
Looks good. Now please squash your commits into 1 and I'll merge this!

2017-03-08 07:01 UTC, snehasi commented
@KiChjang commits have been squashed.

2017-03-08 07:58 UTC, KiChjang commented
@bors-servo r+

Thanks!

2017-03-08 07:58 UTC, bors-servo commented
:pushpin: Commit 2aaf1ee has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 2aaf1ee2d48239137e513060673148285ed1aa68 -->

2017-03-08 07:58 UTC, bors-servo commented
:hourglass: Testing commit 2aaf1ee with merge 3e1f6af...

2017-03-08 08:09 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/6011)

2017-03-08 18:41 UTC, KiChjang commented
```
Checking files for tidiness...

./components/style/properties/shorthand/border.mako.rs:249: trailing whitespace
```

2017-03-14 09:07 UTC, nox commented
@snehasi Are you planning to fix the tidy issue?

2017-03-14 16:01 UTC, KiChjang commented
@bors-servo r+

2017-03-14 16:01 UTC, bors-servo commented
:pushpin: Commit 79393fd has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 79393fd189d13bfdc99c916882e8b70486688887 -->

2017-03-14 16:01 UTC, bors-servo commented
:hourglass: Testing commit 79393fd with merge 5e0a83d...

2017-03-14 16:02 UTC, KiChjang commented
@bors-servo r-
Sorry, needs swuashing

2017-03-14 20:20 UTC, KiChjang commented
@bors-servo r+

2017-03-14 20:20 UTC, bors-servo commented
:pushpin: Commit 3002895 has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 30028959b8a23afac15f9fb0b8f7443d39c069ae -->

2017-03-14 20:20 UTC, bors-servo commented
:hourglass: Testing commit 3002895 with merge 94a2262...

2017-03-14 20:56 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5768), [arm32](http://build.servo.org/builders/arm32/builds/5995), [arm64](http://build.servo.org/builders/arm64/builds/6023), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6132), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2844), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2865), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6135), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6159), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2805), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2882), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1291), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1296)
Approved by: KiChjang
Pushing 94a2262821aae8139ef8cef5a6f2c5e5780aea00 to master...

2017-03-14 20:57 UTC, merged