Implement ImageData constructors #15671 -- 1
servo/servo pull request #15821
Opened 2017-03-04 23:28 UTC by montrivo

Implement ImageData constructors
* new constructors in the imagedata.rs file
* modification of the ImageData::new method
* new method ImageData::from_vec
* new wpt test file imagedata.html 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes affect #15671  (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-03-04 23:28 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @cbrewster (or someone else) soon.

2017-03-04 23:28 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/canvasrenderingcontext2d.rs, components/script/dom/imagedata.rs, components/script/dom/webidls/ImageData.webidl
 * @kichjang: components/script/dom/canvasrenderingcontext2d.rs, components/script/dom/imagedata.rs, components/script/dom/webidls/ImageData.webidl

2017-03-04 23:28 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.
* These commits modify **unsafe code**. Please review it carefully!

2017-03-05 14:09 UTC, nox requested changes
I haven't yet reviewed whether this follows the spec, nor the tests.

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +            Some(jsobject) => (*imagedata).data.set(jsobject),
This needs various checks, such as whether the given object is indeed a proper typed array.

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +    pub fn Constructor(global: &GlobalScope, width: u32, height: u32) -> Fallible<Root<Self>> {
Nit: spec link.

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +        } else {
Nit: remove the `else` and short-circuit in the error case by returning early.

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +    pub fn Constructor_(cx: *mut JSContext,
Nit: spec link.

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +        };
```rust
let mut array = data_res.map_err(|_| {
    Error::Type("Argument to ImageData is not an ArrayBufferView".to_owned())
});
```

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +        }
```rust
let byte_len = unsafe { array.as_slice().len() as u32 };
```

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +    pub fn new(global: &GlobalScope, width: u32, height: u32, data: Option<*mut JSObject>) -> Root<ImageData> {
The whole method should be unsafe, and please rename with to `new_with_jsobject`.

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +        } else {
Nit: remove the `else` and short-circuit in the error case by returning early.

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +            len /= 4;
```rust
let len = byte_len / 4;
```

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +            } else if opt_height.is_some() && height != opt_height.unwrap() {
Nit: remove the `else` and short-circuit in the error case by returning early.

2017-03-05 14:09 UTC, nox commented on components/script/dom/imagedata.rs
> +            } else if opt_height.is_some() && height != opt_height.unwrap() {
```rust
if opt_height.map_or(false, |x| x != height) {
    return Err(Error::IndexSize);
}
```

2017-03-05 14:09 UTC, nox commented on components/script/dom/webidls/ImageData.webidl
> + Constructor(object data, unsigned long sw, optional unsigned long sh),
Nit: remove the commented-out line and instead write the first argument as:

```
/*Uint8Array*/ object data
```

2017-03-05 21:55 UTC, montrivo commented on components/script/dom/imagedata.rs
> +            Some(jsobject) => (*imagedata).data.set(jsobject),
Should I repeat various checks already done in `Constructor` and `Constructor_` or should I remove the `pub` modifier and comment arguments preconditions?

2017-03-05 22:02 UTC, montrivo commented on components/script/dom/imagedata.rs
> +    pub fn from_vec(global: &GlobalScope, width: u32, height: u32, mut data: Option<Vec<u8>>) -> Root<ImageData> {
The `new` method doesn't validate arguments, neither returns a `Faillible<Root<ImageData>>`. Should it do the same kind of validations as the two new constructors ?

2017-03-07 08:47 UTC, nox commented
Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/script/dom/imagedata.rs, line 31 at r1](https://reviewable.io:443/reviews/servo/servo/15821#-KeQdu7pqa6UUmV7orPn-r1-31:-KebwgWNAI59YZ4d4oj7:b-lan7r1) ([raw file](https://github.com/servo/servo/blob/b065bc872ddc2709f8bdac7e3a387070f61f15e5/components/script/dom/imagedata.rs#L31)):*
<details><summary><i>Previously, montrivo wrote…</i></summary><blockquote>

The `new` method doesn't validate arguments, neither returns a `Faillible<Root<ImageData>>`. Should it do the same kind of validations as the two new constructors ?
</blockquote></details>

You can reuse `new_with_jsobject`, but the whole method should panic in case of an error.

---

*[components/script/dom/imagedata.rs, line 59 at r1](https://reviewable.io:443/reviews/servo/servo/15821#-KeQdu7pqa6UUmV7orPn-r1-59:-KebwSu2p7ceaXgwJ_SI:bif9tvl) ([raw file](https://github.com/servo/servo/blob/b065bc872ddc2709f8bdac7e3a387070f61f15e5/components/script/dom/imagedata.rs#L59)):*
<details><summary><i>Previously, montrivo wrote…</i></summary><blockquote>

Should I repeat various checks already done in `Constructor` and `Constructor_` or should I remove the `pub` modifier and comment arguments preconditions?
</blockquote></details>

Make this method return `Fallible<Root<ImageData>>` and reuse that in every other method.

---

*[components/script/dom/imagedata.rs, line 109 at r1](https://reviewable.io:443/reviews/servo/servo/15821#-KeQdu7pqa6UUmV7orPn-r1-109:-KebwFo9-B_dsjDqDl2i:bwyxmfa) ([raw file](https://github.com/servo/servo/blob/b065bc872ddc2709f8bdac7e3a387070f61f15e5/components/script/dom/imagedata.rs#L109)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary><blockquote>

```rust
let mut array = data_res.map_err(|_| {
    Error::Type("Argument to ImageData is not an ArrayBufferView".to_owned())
});
```
</blockquote></details>

You didn't address this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15821)*
<!-- Sent from Reviewable.io -->

2017-03-08 11:58 UTC, nox commented
-S-awaiting-review 

Seems ok! Running try because I think there will be test expectations to change.

@bors-servo try

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15821#-:-Kehm7gcEfHeAYR0RVay:bbkxame)*
<!-- Sent from Reviewable.io -->

2017-03-08 11:58 UTC, bors-servo commented
:hourglass: Trying commit de8201e with merge ab27289...

2017-03-08 12:15 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/5647)

2017-03-08 12:18 UTC, nox commented
```
diff --git a/tests/wpt/metadata/MANIFEST.json b/tests/wpt/metadata/MANIFEST.json
index 6c2c84a..c1b47c4 100644
--- a/tests/wpt/metadata/MANIFEST.json
+++ b/tests/wpt/metadata/MANIFEST.json
@@ -175569,7 +175569,7 @@
    "testharness"
   ],
   "html/semantics/embedded-content/the-canvas-element/imagedata.html": [
-   "b0dade5b5f0a3e8b7798f52dbcb2ae0f23fed150",
+   "04c670c9a045d924725bedfb09be665f73c3a0ad",
    "testharness"
   ],
   "html/semantics/embedded-content/the-canvas-element/initial.colour.html": [
```

I'll check whether the other build jobs finish successfully.

2017-03-08 12:18 UTC, nox approved these changes

2017-03-08 12:38 UTC, nox commented
```
  ▶ Unexpected subtest result in /2dcontext/pixel-manipulation/2d.imageData.object.ctor.html:
  │ FAIL [expected PASS] ImageData does not have a usable constructor
  │   → assert_throws: function "function () { new window.ImageData(1,1); }" did not throw
  │ 
  │ @http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.ctor.html:23:1
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  │ _addTest/</<@http://web-platform.test:8000/common/canvas-tests.js:62:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  └ _addTest/<@http://web-platform.test:8000/common/canvas-tests.js:59:9

  ▶ Unexpected subtest result in /html/dom/interfaces.worker.html:
  └ PASS [expected FAIL] ImageData interface object length

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ImageData interface object length
```

The 2 `PASS` are good news, the `FAIL` isn't.

2017-03-08 12:44 UTC, nox commented
The test `/2dcontext/pixel-manipulation/2d.imageData.object.ctor.html` doesn't pass in either Safari nor Firefox, it's probably outdated.

2017-03-08 12:44 UTC, nox commented
@jdm Should it be marked as `FAIL`, or should we fix the test right now in this PR?

2017-03-13 11:39 UTC, nox commented
@Ms2ger What do you think about the failing test? Should we just mark it as FAIL and report the erroneous test upstream?

2017-03-13 14:05 UTC, Ms2ger commented
Mark it as fail; I want wpt CI to run on the change.

2017-03-13 14:15 UTC, Ms2ger commented on tests/wpt/web-platform-tests/html/semantics/embedded-content/the-canvas-element/imagedata.html
> +        try {
Use `assert_throws`

2017-03-14 08:57 UTC, nox submitted a review, later dismissed
A few cosmetic changes on the test and this will be ready.

2017-03-14 08:57 UTC, nox commented on tests/wpt/web-platform-tests/html/semantics/embedded-content/the-canvas-element/imagedata.html
> +<title></title>
Add a title.

2017-03-14 08:57 UTC, nox commented on tests/wpt/web-platform-tests/html/semantics/embedded-content/the-canvas-element/imagedata.html
> +}, "ImagaData(w, h), exposed attributes check");
Please reindent all tests to look like this one.

2017-03-14 08:57 UTC, nox commented on tests/wpt/web-platform-tests/html/semantics/embedded-content/the-canvas-element/imagedata.html
> +    "ImagaData(w, h), width cannot be 0");
Please fix all the spelling errors, it's `ImageData`.

2017-03-15 09:23 UTC, Ms2ger approved these changes

2017-03-15 09:23 UTC, Ms2ger commented
@bors-servo r+

2017-03-15 09:23 UTC, bors-servo commented
:pushpin: Commit 46a25d6 has been approved by `Ms2ger`

<!-- @bors-servo r=Ms2ger 46a25d621c47f6d860c1fda1c4eec30f3ea324de -->

2017-03-15 09:23 UTC, bors-servo commented
:hourglass: Testing commit 46a25d6 with merge 5bfa87a...

2017-03-15 10:42 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5781), [arm32](http://build.servo.org/builders/arm32/builds/6007), [arm64](http://build.servo.org/builders/arm64/builds/6035), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6143), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2856), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2878), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6146), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6172), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2816), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2895), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1304), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1309)
Approved by: Ms2ger
Pushing 5bfa87a8e27e125fced2c8824e3ce784f8dc5405 to master...

2017-03-15 10:42 UTC, merged