Reject negative border radius
servo/servo pull request #15869
Opened 2017-03-08 12:03 UTC by Iakis

Replacerd Parse in parse_one_set_of_border_values with parse_non_negative and added tests for it
---

- [X ] `./mach build -d` does not report any errors
- [ X] `./mach test-tidy` does not report any errors
- [X ] These changes fix #15345 (github issue number if applicable).

- [X ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-03-08 12:03 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @mbrubeck (or someone else) soon.

2017-03-08 12:03 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/values/specified/basic_shape.rs
 * @emilio: components/style/values/specified/basic_shape.rs

2017-03-08 12:09 UTC, nox commented on components/style/values/specified/basic_shape.rs
> +    let a = try!(LengthOrPercentage::parse_non_negative(input));
Shouldn't the other calls to `LengthOrPercentage::parse` in that method be replaced too?

2017-03-08 12:11 UTC, nox commented on tests/unit/style/parsing/basic_shape.rs
> +    assert!(parse(BorderRadius::parse, "borderRadius(-10px 20px 30px 40px)").is_err());
What is `borderRadius` in this?

2017-03-08 12:22 UTC, Iakis commented on components/style/values/specified/basic_shape.rs
> +    let a = try!(LengthOrPercentage::parse_non_negative(input));
i tried both but the other didnt seem to make a difference in the tests at all so i thought it would be be better to leave it as it is

2017-03-08 12:22 UTC, Iakis commented on tests/unit/style/parsing/basic_shape.rs
> +    assert!(parse(BorderRadius::parse, "borderRadius(-10px 20px 30px 40px)").is_err());
I believe thats the context

2017-03-08 12:24 UTC, Iakis commented on components/style/values/specified/basic_shape.rs
> +    let a = try!(LengthOrPercentage::parse_non_negative(input));
Also replacing all the parses would result in context becoming an unused variable

2017-03-08 17:42 UTC, ghost requested changes
Note that all calls to be `parse` should be changed to `parse_non_negative`

2017-03-08 17:42 UTC, Wafflespeanut commented on tests/unit/style/parsing/basic_shape.rs
> +    assert!(parse(BorderRadius::parse, "borderRadius(-10px 20px 30px 40px)").is_err());
This will obviously be an error, because it should be `border-radius`

2017-03-08 17:42 UTC, Wafflespeanut commented on components/style/values/specified/basic_shape.rs
> +    let a = try!(LengthOrPercentage::parse_non_negative(input));
The `context` becoming unused is fine, but what do you mean by, "other didn't seem to make a difference"? Are you saying that `border-radius: 2px -5px` didn't show a difference before and after you made your changes? After your changes, this should serialize to `border-radius: 2px`.

2017-03-08 17:42 UTC, Wafflespeanut commented
Also, tidy fails:

    ./components/style/values/specified/basic_shape.rs:773: found an empty line following a {

2017-03-09 03:47 UTC, Iakis commented
@Wafflespeanut thats very strange, when i run tidy i get no errors. Do you have any idea of why this might be?

2017-03-09 04:53 UTC, Wafflespeanut commented
Not sure, but we'll know once the Travis build ends :)

2017-03-09 04:54 UTC, Iakis commented
Ive made the requested changes, my mistake I had some misunderstandings on how the code was working

2017-03-09 04:57 UTC, Wafflespeanut commented
No worries! The changes look good to me. Please squash your commits :)

2017-03-09 08:15 UTC, nox commented
There is now a merge and 11 commits in this PR. There should be only one commit.

2017-03-09 12:13 UTC, Iakis commented
Hi I have squashed the commits but I made a mistake during the squash and ended up changing some of the commit messages of unrelated files, will this cause problems? If so is there some way I can fix it? Should i start a new branch + pull request?

2017-03-09 12:21 UTC, Wafflespeanut commented on components/style/values/specified/basic_shape.rs
> +fn parse_one_set_of_border_values(_context: &ParserContext, mut input: &mut Parser)
One final change. I didn't notice this earlier. This function is private, and it's used only by `BorderRadius`. So, let's pass only the `Parser` to this function (which will make `BorderRadius::parse` ignore the `ParserContext`.

2017-03-09 12:22 UTC, Wafflespeanut commented
And no, there doesn't seem to be a problem with your commit. Please amend the future changes and we'll land this :)

2017-03-09 12:35 UTC, Iakis commented
Ok i have made the change, however i did have to declare the context in border radius unused since after removing context as a parameter for parse_one_set_of_border_values there is no use of context in parse for border radius is that alright?

2017-03-09 12:39 UTC, Wafflespeanut commented
It looks great! Can you please change your commit message to only include the actual message? (the squashed commits don't really have any useful information)

2017-03-09 12:52 UTC, Wafflespeanut commented
Thanks!

@bors-servo r+

2017-03-09 12:52 UTC, bors-servo commented
:pushpin: Commit f5253c9 has been approved by `Wafflespeanut`

<!-- @bors-servo r=Wafflespeanut f5253c9f090dd3edc4afdfdf7992f9160b5cf1d7 -->

2017-03-09 12:52 UTC, bors-servo commented
:hourglass: Testing commit f5253c9 with merge e7efdfc...

2017-03-09 13:09 UTC, bors-servo commented
:broken_heart: Test failed - [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1211)

2017-03-09 13:10 UTC, nox commented
https://github.com/servo/servo/pull/15852#issuecomment-285343543

2017-03-09 13:37 UTC, nox commented
@bors-servo retry

2017-03-09 13:37 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/5679), [arm32](http://build.servo.org/builders/arm32/builds/5913), [arm64](http://build.servo.org/builders/arm64/builds/5935), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6049), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2755), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2776), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6045), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6071), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2719), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2795), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1209) are reusable. Rebuilding only [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1211)...

2017-03-09 13:59 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5679), [arm32](http://build.servo.org/builders/arm32/builds/5913), [arm64](http://build.servo.org/builders/arm64/builds/5935), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6049), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2755), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2776), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6045), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6071), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2719), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2795), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1212), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1209)
Approved by: Wafflespeanut
Pushing e7efdfc6551433feb037dfeb3cbbd1f0c22b8ea1 to master...

2017-03-09 13:59 UTC, merged