making image element areas good at finding areas
servo/servo pull request #15904
Opened 2017-03-10 05:58 UTC by sendilkumarn

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15884

2017-03-10 05:58 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmlimageelement.rs
 * @kichjang: components/script/dom/htmlimageelement.rs

2017-03-10 05:58 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-03-14 10:45 UTC, nox requested changes

2017-03-14 10:45 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +                      .GetRootNode()
Use the document instead.

```rust
document_from_node(self).traverse_preorder()
```

2017-03-14 10:45 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +        }
This would be shorter as `map.map(|elem| { ... })`, probably with a different name for `map`, for clarity.

2017-03-14 10:45 UTC, nox commented
https://github.com/servo/servo/pull/15914 partly covers the same changes.

2017-03-14 10:48 UTC, Wafflespeanut commented on components/script/dom/htmlimageelement.rs
> +        match map {
```rust
map.and_then(|map_elem| {
    // elements ...
})
```

2017-03-14 10:49 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +        match map {
Not `and_then`, `map`.

2017-03-14 10:54 UTC, Wafflespeanut commented on components/script/dom/htmlimageelement.rs
> +        match map {
Yeah, got confused by `Some` returning another `Some`

2017-03-15 10:39 UTC, nox requested changes
One nit, one fix, and one refactor.

2017-03-15 10:39 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +                      .GetRootNode()
Use the document here as I mentioned in my previous comment, also the indentation is wrong.

2017-03-15 10:39 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +        let useMapElements =  self.upcast::<Node>()
Nit: double space.

2017-03-15 10:39 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +        })
Actually I just realised that you should rather add a method on `HTMLMapElement` itself that returns the `Vec<Root<HTMLAreaElement>>`, and call it here.

2017-03-15 11:33 UTC, sendilkumarn commented on components/script/dom/htmlimageelement.rs
> +                      .GetRootNode()
want to replace node by document ?

2017-03-15 11:54 UTC, sendilkumarn commented on components/script/dom/htmlimageelement.rs
> +                      .GetRootNode()
I don't understand this here.

2017-03-15 11:57 UTC, Wafflespeanut commented on components/script/dom/htmlimageelement.rs
> +                      .GetRootNode()
Previously nox had mentioned this,

``` rust
document_from_node(self).traverse_preorder()
```

2017-03-15 12:37 UTC, sendilkumarn commented on components/script/dom/htmlimageelement.rs
> +                      .GetRootNode()
Dont we have to cast the doc into node to traverse?

2017-03-15 12:45 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +                      .GetRootNode()
Yes we do.

```rust
document_from_node(self).upcast::<Node>().traverse_preorder()
```

Still better than using `GetRootNode`.

2017-03-15 23:49 UTC, nox commented
@bors-servo try

2017-03-15 23:49 UTC, bors-servo commented
:hourglass: Trying commit 7a3644a with merge b32bef8...

2017-03-16 00:15 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2894)

2017-03-16 04:38 UTC, jdm commented
The only test that failed that wasn't recognized in that run was an instance of #14323.

2017-03-16 12:23 UTC, nox commented
@sendilkumarn The code is correct, but it needs a test.

2017-03-17 15:13 UTC, sendilkumarn commented
I am on it.

2017-03-17 15:16 UTC, sendilkumarn commented
where / what you want to add in tests?

2017-03-22 16:08 UTC, sendilkumarn commented
@nox sorry for the delay. Here it is 👍

2017-03-25 04:13 UTC, Wafflespeanut commented
Tidy fails.

    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:17: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:18: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:19: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:26: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:27: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:32: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:33: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:34: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:41: trailing whitespace
    ./tests/wpt/mozilla/tests/mozilla/img-find-areas.html:42: trailing whitespace

Also, the WPT manifest needs to be updated. Please read `tests/wpt/README.md`

2017-03-28 08:02 UTC, nox commented
@jdm Does the test look good to you?

2017-03-28 14:19 UTC, jdm requested changes
The test is a good start, but we can write it without timeouts and separate the cases that it is testing.

2017-03-28 14:19 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img-find-areas.html
> +                test.step(function() {
```js
document.addEventListener("DOMContentLoaded", test.step_func(function() {
    img.click();
});
```

2017-03-28 14:19 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img-find-areas.html
> +            };
```js
img.onclick = test.step_func_done();
```

2017-03-28 14:19 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img-find-areas.html
> +            var test = async_test("ImageShouldFindTheMapEvenWhenItIsNotItsSibiling");
`async_test("Image should find a non-sibling map")`

2017-03-28 14:19 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img-find-areas.html
> +        <img usemap="#img_no_map" src="2x2.png" id="img_no"/>
`img` and `area` elements are self-closing; we don't need the `/` at all.

2017-03-28 14:19 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img-find-areas.html
> +            }, 500);
We can remove this with the earlier changes.

2017-03-28 14:19 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img-find-areas.html
> +            img_no.onclick = function(e) {
`img_no.onclick = test2.unreached_func("click event should not be fired for image without map");`

2017-03-28 14:19 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img-find-areas.html
> +            var img_no = document.getElementById('img_no');
We should declare a separate async_test for the case with no map.

2017-03-28 14:19 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/img-find-areas.html
> +            }, 500);
```js
document.addEventListener("DOMContentLoaded", test2.step(function() {
    img_no.click();
});
window.addEventListener("load", test2.step_func_done(function() {
    assert_false(img_no_map_clicked, "Image no map click expected");
});
```

2017-04-04 15:13 UTC, sendilkumarn commented
Thanks @jdm for the awesome help 👍

2017-04-05 12:01 UTC, sendilkumarn commented
added tests and the builds are green.

2017-04-05 13:31 UTC, jdm commented
@bors-servo: r+
Thanks!

2017-04-05 13:31 UTC, bors-servo commented
:pushpin: Commit 31dafcc has been approved by `jdm`

<!-- @bors-servo r=jdm 31dafcc5f3e503655cc3e72ae10a815c47f55801 -->

2017-04-05 13:49 UTC, bors-servo commented
:hourglass: Testing commit 31dafcc5f3e503655cc3e72ae10a815c47f55801 with merge c12b17d276df5e6960358b33b9c9ff2fc414e083...

2017-04-05 14:27 UTC, merged