Access browsing context safely
servo/servo pull request #15906
Opened 2017-03-10 10:42 UTC by mchv

Current browsing context accessor in `Document` unwraps the browsing context `Option` which prevents document to handle correctly the case when there is no browsing context.

This is the reason servo panics with `session-history.max-length=1` (https://github.com/servo/servo/issues/15877).

As it is my first contribution, I added a `safe` method to retrieve the browsing context rather than change the existing method, but I am happy to change if you think this is the right approach. I did not as well replace all existing method call to the `safe` method, to focus on fixing the issue.

If someone can give me a bit of guidance for the test, I will try to contribute one.

---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes fix #15877.
- [ ] There are tests for these changes

2017-03-10 10:42 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2017-03-10 10:42 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/document.rs, components/script/dom/window.rs
 * @kichjang: components/script/dom/document.rs, components/script/dom/window.rs

2017-03-10 13:19 UTC, emilio commented on components/script/dom/window.rs
> +        if self.safe_browsing_context().map(|c| c.is_discarded()).unwrap_or(true) {
nit: you can use `map_or(true, |c| c.is_discarded())`

2017-03-10 13:19 UTC, emilio commented
r? @asajeffrey

2017-03-10 16:06 UTC, mchv commented on components/script/dom/window.rs
> +        if self.safe_browsing_context().map(|c| c.is_discarded()).unwrap_or(true) {
@emilio thanks updated the code

2017-03-10 17:11 UTC, asajeffrey commented
My take on how we got here...

The only place we're creating a `Window` is in https://github.com/servo/servo/blob/master/components/script/script_thread.rs#L1674, and we immediately call `init_browsing_context` at https://github.com/servo/servo/blob/master/components/script/script_thread.rs#L1703 or https://github.com/servo/servo/blob/master/components/script/script_thread.rs#L1708.

The only thing I can think of is that we're accessing the `Window` after it's been discarded https://github.com/servo/servo/blob/master/components/script/dom/window.rs#L272, which is certainly possible if the `Document` calls methods on the `Window` after the browsing context has been discarded.

Since it is possible for (e.g.) a `Document` to be accessed after its browsing context has been discarded, it looks like the thing to do is to make sure that `Window` methods are safe to call even if there is no browsing context.

This PR will certainly help for that! We could be more drastic, and just make `wiindow.browsing_context()` return an `Option<BrowsingContext>`, but that's not a must-do.

@mchv: thanks for looking into this!

2017-03-10 17:14 UTC, asajeffrey reviewed
Looks good! Just some minor nits.

2017-03-10 17:14 UTC, asajeffrey commented on components/script/dom/window.rs
> +    /// Retrieve unsafely the browsing context
Add a comment, something like "This can panic if it is called after the browsing context has been discarded".

2017-03-10 17:14 UTC, asajeffrey commented on components/script/dom/window.rs
> +        if self.safe_browsing_context().map_or(true, |c| c.is_discarded()) {
Can this be `map_or(true, BrowsingContext::is_discarded)`?

2017-03-10 17:14 UTC, asajeffrey commented on components/script/dom/window.rs
> +        if self.safe_browsing_context().map_or(true, |c| c.is_discarded()) {
Ditto?

2017-03-13 11:31 UTC, nox requested changes
Some questions.

2017-03-13 11:31 UTC, nox commented on components/script/dom/window.rs
> +    pub fn safe_browsing_context(&self) -> Option<Root<BrowsingContext>> {
The only place this method is used outside of `dom::window` is in `Document::browsing_context`, which checks whether `self.has_browsing_context` is true.

Why is `self.has_browsing_context` ever true without a corresponding browsing context in the document's window?

2017-03-13 11:31 UTC, nox commented on components/script/dom/window.rs
> +        if self.safe_browsing_context().map_or(true, |c| c.is_discarded()) {
No it can't, because `BrowsingContext::is_discarded` takes a `&BrowsingContext` and the contents of the option is a `Root<BrowsingContext>`.

2017-03-13 11:31 UTC, nox commented on components/script/dom/window.rs
> +    /// Retrieve unsafely the browsing context
Don't use the word "unsafely", which has a precise meaning in Rust.

2017-03-13 11:31 UTC, nox commented on components/script/dom/window.rs
> +    pub fn safe_browsing_context(&self) -> Option<Root<BrowsingContext>> {
Please rename method to something like `maybe_browsing_context` or something like that. Safety is a different concept.

2017-03-13 12:23 UTC, mchv commented on components/script/dom/window.rs
> +    /// Retrieve unsafely the browsing context
@nox sure I will update

2017-03-13 12:23 UTC, mchv commented on components/script/dom/window.rs
> +    pub fn safe_browsing_context(&self) -> Option<Root<BrowsingContext>> {
@nox make sense I will do the update

2017-03-14 14:09 UTC, asajeffrey commented on components/script/dom/window.rs
> +        if self.safe_browsing_context().map_or(true, |c| c.is_discarded()) {
Oh that's annoying, oh well.

2017-03-14 14:14 UTC, asajeffrey commented on components/script/dom/window.rs
> +    pub fn safe_browsing_context(&self) -> Option<Root<BrowsingContext>> {
The problem is that `document.has_browsing_context` is immutable, so if a document originally had a browsing context, but then that browsing context was discarded, we don't update the document. We could make `document.has_browsing_context` mutable, or we could just remove it and replace it by a method which checks to see if the window exists and has a browsing context.

2017-03-14 14:32 UTC, nox commented on components/script/dom/window.rs
> +    pub fn safe_browsing_context(&self) -> Option<Root<BrowsingContext>> {
Given a document can now lose its browsing context, `has_browsing_context` should probably not be immutable.

2017-03-14 14:46 UTC, asajeffrey commented on components/script/dom/window.rs
> +    pub fn safe_browsing_context(&self) -> Option<Root<BrowsingContext>> {
The problem is we're being a bit vague about the distinction between not having a browsing context, and having one that's been discarded. Sigh.

2017-03-14 14:53 UTC, mchv commented
@nox @asajeffrey I have updated the code based on your comments. Let me know if you think we need other changes or add tests before being ready to merge.

2017-03-16 19:40 UTC, asajeffrey commented
LGTM. @bors-servo r+

2017-03-16 19:40 UTC, bors-servo commented
:pushpin: Commit f8c7235 has been approved by `asajeffrey`

<!-- @bors-servo r=asajeffrey f8c7235f73865705f2f1104619ea3c753fbb3c9b -->

2017-03-16 22:41 UTC, bors-servo commented
:hourglass: Testing commit f8c7235 with merge e62d029...

2017-03-16 23:19 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5811), [arm32](http://build.servo.org/builders/arm32/builds/6036), [arm64](http://build.servo.org/builders/arm64/builds/6066), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6173), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2886), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2910), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6175), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6202), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2846), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2925), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1334), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1339)
Approved by: asajeffrey
Pushing e62d029ed643e5ce503cfbc7525da75a705ccf71 to master...

2017-03-16 23:19 UTC, merged

2017-03-17 00:20 UTC, asajeffrey commented
Yay!