Add gradient border support.
servo/servo pull request #15905
Opened 2017-03-10 07:59 UTC by mephisto41

webrender add gradient border support in https://github.com/servo/webrender/pull/953. This pr add support in servo.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] These changes do not require tests because it should be covered by wpt

2017-03-10 07:59 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @cbrewster (or someone else) soon.

2017-03-10 07:59 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @emilio: components/layout/display_list_builder.rs, components/layout/webrender_helpers.rs

2017-03-10 07:59 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify gfx and layout code, but no tests are modified. Please consider adding a test!

2017-03-10 08:47 UTC, glennw commented
@bors-servo try

2017-03-10 08:47 UTC, bors-servo commented
:hourglass: Trying commit 25f2216 with merge 1573aa5...

2017-03-10 08:50 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6069)

2017-03-10 10:26 UTC, nox requested changes
2 nits.

2017-03-10 10:26 UTC, nox commented on components/gfx/display_list/mod.rs
> +    pub gradient: Gradient,
Nit: document this.

2017-03-10 10:26 UTC, nox commented on components/gfx/display_list/mod.rs
> +    /// Fields common to all display items.
Nit: singular, not plural.

2017-03-12 04:10 UTC, cbrewster commented
r? @emilio or someone else

2017-03-12 15:17 UTC, emilio commented
@bors-servo retry

2017-03-12 15:18 UTC, bors-servo commented
:hourglass: Trying commit 25f2216 with merge 74de319...

2017-03-12 15:18 UTC, emilio commented
Any chance to add a test for this if none pass?

2017-03-12 15:58 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5729), [arm32](http://build.servo.org/builders/arm32/builds/5960), [arm64](http://build.servo.org/builders/arm64/builds/5984), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6096), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2805), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2826), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6094), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6120), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2766), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2843), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1258), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1257)
State: approved= try=True

2017-03-13 02:33 UTC, mephisto41 commented
Looks like none test pass. I'll add a new test and also address nox's comment. Thanks.

2017-03-13 11:32 UTC, nox commented
Shouldn't this particular test live in WPT?

2017-03-13 12:49 UTC, emilio commented
You also need to update the manifest:

```
24.81s$ bash etc/ci/manifest_changed.sh
diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json
index 29267dbb2..85c151816 100644
--- a/tests/wpt/mozilla/meta/MANIFEST.json
+++ b/tests/wpt/mozilla/meta/MANIFEST.json
@@ -20345,7 +20345,7 @@
    "support"
   ],
   "css/border-image-linear-gradient.html": [
-   "3548e2a77693afb8c61c07c74e95185c4205ac99",
+   "40ea388a8a920eaecb2d0d12f998ed60ac3b56e8",
    "reftest"
   ],
   "css/border_black_groove.html": [
```

2017-03-13 18:15 UTC, jdm commented
The manifest can be updated using `./mach update-manifest`.

2017-03-26 09:29 UTC, emilio commented
@bors-servo r+

2017-03-26 09:29 UTC, bors-servo commented
:pushpin: Commit 4895c6d has been approved by `emilio`

<!-- @bors-servo r=emilio 4895c6df832fc5624c213e4d306796cec9430510 -->

2017-03-26 09:29 UTC, bors-servo commented
:hourglass: Testing commit 4895c6df832fc5624c213e4d306796cec9430510 with merge fd8127b23b177886217eb1f21963e6c02528647a...

2017-03-26 10:08 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3047)

2017-03-26 16:44 UTC, emilio commented
@bors-servo retry

 * https://github.com/servo/servo/issues/14237

2017-03-26 16:58 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/5973), [arm32](http://build.servo.org/builders/arm32/builds/6194), [arm64](http://build.servo.org/builders/arm64/builds/6227), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6329), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3077), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6333), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6362), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3016), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3084), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1501) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3047)...

2017-03-26 17:17 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5973), [arm32](http://build.servo.org/builders/arm32/builds/6194), [arm64](http://build.servo.org/builders/arm64/builds/6227), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6329), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3053), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3077), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6333), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6362), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3016), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3084), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1501)
Approved by: emilio
Pushing fd8127b23b177886217eb1f21963e6c02528647a to master...

2017-03-26 17:17 UTC, merged