Issue #15858: Don't crash if an image uses a map that is defined before it
servo/servo pull request #15914
Opened 2017-03-11 13:51 UTC by simartin

The map referenced in an img element might have been declared before, while the code expected it to always be after. This patch fixes this.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15858
- [X] There are tests for these changes

2017-03-11 13:51 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmlimageelement.rs
 * @kichjang: components/script/dom/htmlimageelement.rs

2017-03-12 10:44 UTC, nox requested changes

2017-03-12 10:44 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +                        .find(|n| n.upcast::<Element>().get_string_attribute(&LocalName::from("name")) == last);
That doesn't seem right to me. The whole method can still panic if there was no `HTMLMapElement` in the image's parent's children.

2017-03-12 15:02 UTC, simartin commented on components/script/dom/htmlimageelement.rs
> +                        .find(|n| n.upcast::<Element>().get_string_attribute(&LocalName::from("name")) == last);
Yes indeed, thanks. Patch amended, and associated test case added

2017-03-13 10:52 UTC, nox requested changes
Functionality is still not correct.

2017-03-13 10:52 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +                        .find(|n| n.upcast::<Element>().get_string_attribute(&LocalName::from("name")) == last);
> The usemap attribute, if specified, must be a valid hash-name reference to a map element.

The map element can be anywhere in the whole tree, AFAIK, not just in the image's parent.

2017-03-13 10:52 UTC, nox commented on components/script/dom/htmlimageelement.rs
> +        };
```rust
let map = match map {
    Some(map) => map,
    None => return None,
}
```

2017-03-16 12:26 UTC, nox commented
Closing as duplicate of #15904.

2017-03-16 12:26 UTC, closed without merging