Fix crop_area_bytes_length calculation and add tests
servo/servo pull request #15929
Opened 2017-03-13 19:05 UTC by n0max

- Fix crop_area_bytes_length calculation (the height was multiplied by itself)
- Add tests for this error and for the case that the width is multiplied by itself

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15386

- [X] There are tests for these changes

2017-03-13 19:05 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @pcwalton (or someone else) soon.

2017-03-13 19:05 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.

2017-03-14 08:51 UTC, nox requested changes
Do not forget to update the manifest when you fix the tests.

2017-03-14 08:51 UTC, nox commented on tests/wpt/web-platform-tests/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_14.html
> +<title></title>
Add a title.

2017-03-14 08:51 UTC, nox commented on tests/wpt/web-platform-tests/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_15.html
> +<title></title>
Add a title.

2017-03-15 10:37 UTC, nox commented
Seems good to go now, just needs a squash.

2017-03-15 23:47 UTC, nox commented
```
diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json
index b848a0645..366654cac 100644
--- a/tests/wpt/mozilla/meta/MANIFEST.json
+++ b/tests/wpt/mozilla/meta/MANIFEST.json
@@ -9583,11 +9583,6 @@
      {}
     ]
    ],
-   "mozilla/referrer-policy/generic/subresource/mozresource.pyc": [
-    [
-     {}
-    ]
-   ],
    "mozilla/referrer-policy/generic/subresource/stash.py": [
     [
      {}
@@ -25742,10 +25737,6 @@
    "333a80e3d4aec4a8be5566605fae5675a821085b",
    "support"
   ],
-  "mozilla/referrer-policy/generic/subresource/mozresource.pyc": [
-   "d4588e13a26732b38edb79fc11487a0542e87c40",
-   "support"
-  ],
   "mozilla/referrer-policy/generic/subresource/stash.py": [
    "97450e21d3280bb5950d3ad015d9b0041a5b9b2e",
    "support"
```

You need to update the manifest.

2017-03-16 04:24 UTC, jdm commented
(That requires running `./mach update-manifest` and committing the changes).

2017-03-17 08:08 UTC, nox approved these changes

2017-03-17 08:08 UTC, nox commented
@bors-servo r+

2017-03-17 08:08 UTC, bors-servo commented
:pushpin: Commit 6f470e4 has been approved by `nox`

<!-- @bors-servo r=nox 6f470e497f51cd37ad2da726464e855a9d1c8190 -->

2017-03-17 08:47 UTC, bors-servo commented
:hourglass: Testing commit 6f470e4 with merge 3be9b34...

2017-03-17 08:47 UTC, bors-servo commented
:snowman: The build was interrupted to prioritize another pull request.

2017-03-17 08:55 UTC, bors-servo commented
:hourglass: Testing commit 6f470e4 with merge 594a679...

2017-03-17 10:09 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5827), [arm32](http://build.servo.org/builders/arm32/builds/6052), [arm64](http://build.servo.org/builders/arm64/builds/6082), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6189), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2902), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2927), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6191), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6218), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/2862), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/2941), [windows-gnu-dev](http://build.servo.org/builders/windows-gnu-dev/builds/1350), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1355)
Approved by: nox
Pushing 594a679002a5d74da761c17574ad5383a130b55a to master...

2017-03-17 10:09 UTC, merged