Make writing-mode affect computed display
servo/servo pull request #16044
Opened 2017-03-20 13:14 UTC by bd339

The first manual test-case in #15754 passes now, but the second test-case still renders "Text" horizontally, which is apparently because of servo's experimental support for writing-mode.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15754 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-03-20 13:14 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2017-03-20 13:14 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/properties/properties.mako.rs
 * @emilio: components/style/properties/properties.mako.rs

2017-03-20 13:14 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2017-03-20 13:46 UTC, emilio requested changes
We need to add a test for this. Even if the rendering it's not the expected one, we can test this with `getComputedStyle`, let's write a WPT test that does that.

2017-03-20 13:46 UTC, emilio commented on components/style/properties/properties.mako.rs
> +               style.mutate_box().set_display(display::inline_block);
nit: Indent this and the following line to the left, four spaces from the `if`.

2017-03-20 13:46 UTC, emilio commented on components/style/properties/properties.mako.rs
> +        if context.layout_parent_style.writing_mode != style.writing_mode &&
Let's add here:

 * A quote and link to the spec.
 * A link to Boris' www-style mail.
 * (optionally) A link to the issue we're fixing to see the discussion.

2017-03-23 17:54 UTC, bd339 commented
r?@emilio

2017-03-23 18:24 UTC, emilio commented
Awesome, thank you for doing this!

@bors-servo r+

2017-03-23 18:24 UTC, bors-servo commented
:pushpin: Commit 8db0fca has been approved by `emilio`

<!-- @bors-servo r=emilio 8db0fcaa2945d178b4434732b0e20fff2653a2df -->

2017-03-23 18:36 UTC, emilio approved these changes

2017-03-23 18:39 UTC, bors-servo commented
:hourglass: Testing commit 8db0fcaa2945d178b4434732b0e20fff2653a2df with merge eb0bb872467db2556e1b7ec384ea9513a462badb...

2017-03-23 19:08 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3044)

2017-03-24 09:38 UTC, bd339 commented
Was that test failure because of these changes @emilio ?

2017-03-24 13:57 UTC, jdm commented
@bors-servo: retry
* #14323 
It was not.

2017-03-24 13:58 UTC, bors-servo commented
:hourglass: Testing commit 8db0fcaa2945d178b4434732b0e20fff2653a2df with merge eb4a1e75d0acf613e390787f6b154240fa2b0eca...

2017-03-24 14:24 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3062)

2017-03-24 14:51 UTC, jdm commented
@bors-servo: retry
* #14323

2017-03-24 15:05 UTC, bors-servo commented
:hourglass: Testing commit 8db0fcaa2945d178b4434732b0e20fff2653a2df with merge 0f2c71aa662d268e75aa1a6ead214a201e57bc73...

2017-03-24 15:47 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/5960), [arm32](http://build.servo.org/builders/arm32/builds/6181), [arm64](http://build.servo.org/builders/arm64/builds/6214), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6316), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3034), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3064), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6320), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6349), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3001), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3071), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1488)
Approved by: emilio
Pushing 0f2c71aa662d268e75aa1a6ead214a201e57bc73 to master...

2017-03-24 15:47 UTC, merged

2017-03-24 17:20 UTC, bzbarsky commented
This broke a bunch of Gecko tests, because it's examining the value of the "writing mode" as defined at https://drafts.csswg.org/css-writing-modes-3/#writing-mode whereas it should be examining the value of the writing-mode property as defined at https://drafts.csswg.org/css-writing-modes-3/#propdef-writing-mode

As a simple example, this testcase: `<span direction="ltr">some <span direction="rtl">long text that needs to wrap</span></span>` gets broken because it makes the inner span an inline-block and then the wrapping is all wrong.

Emilio told me how to fix; I'll create a PR once I verify the fix actually does the right thing.

2017-03-24 17:21 UTC, bzbarsky commented
But I don't have time today to figure out how to run servo reftests and in particular how to add new ones.

We really need to figure out some way to share reftests with Gecko.  :(

2017-03-24 20:05 UTC, bzbarsky commented
https://github.com/servo/servo/pull/16123 merged.

I really wish the CSS spec didn't have this naming confusion...

2017-03-24 20:29 UTC, bzbarsky commented
For what it's worth, this commit made the following previously-failing Gecko tests pass: layout/reftests/css-display/display-contents-writing-mode-2.html , layout/reftests/writing-mode/1134849-orthogonal-inline.html, layout/reftests/writing-mode/1196887-1-computed-display-inline-block.html

which is excellent.  ;)