Block scripts with text/csv, audio/*, video/* and image/* mime types
servo/servo pull request #16126
Opened 2017-03-24 19:03 UTC by ferjm

This patch implements step 12 of the Main Fetch section of the Fetch API standard. It blocks the load of scripts with `text/csv`, `audio/*`, `video/*` and `image/*` mime types.

Credit for the logic of `should_block_mime_type` function should go to the author of #14770.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14520
- [X] There are tests for these changes

2017-03-24 19:03 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net/fetch/methods.rs

2017-03-24 19:03 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.

2017-03-24 19:04 UTC, ferjm commented
r? @asajeffrey

2017-03-25 10:06 UTC, nox requested changes
Some improvements can be made.

2017-03-25 10:06 UTC, nox commented on components/net/fetch/methods.rs
> +    request.type_ == Type::Script && mime_type.is_some() && match *mime_type.unwrap() {
You can first unwrap `mime_type` and return early if it is `None`.

```rust
let mime_type = match response.headers.get::<ContentType>() {
    Some(header) => header,
    None => return false,
};
```

2017-03-25 10:06 UTC, nox commented on components/net/fetch/methods.rs
> +        ContentType(ref m_type) => *m_type == csv
No need to allocate a `Mime` value for `csv`.

```rust
match *mime_type {
    ...
    ContentType(Mime(TopLevel::Text, SubLevel::Ext(ref ext), _)) => ext == "csv",
    _ => false,
}
```

2017-03-25 23:10 UTC, KiChjang commented on components/net/fetch/methods.rs
> +    request.type_ == Type::Script && mime_type.is_some() && match *mime_type.unwrap() {
I'd also improve this by not pre-allocating `"text/csv".parse()` at all and pattern-match directly against `ContentType(Mime(TopLevel::Text, SubLevel::Csv, _))`.

2017-03-26 12:21 UTC, nox commented on components/net/fetch/methods.rs
> +    request.type_ == Type::Script && mime_type.is_some() && match *mime_type.unwrap() {
`SubLevel::Csv` doesn't exist, and I already suggested a way to not parse the CSV mimetype below. :)

2017-03-27 11:07 UTC, ferjm commented
Thanks for the feedback @nox. Could you take another look, please?

2017-03-28 07:17 UTC, nox approved these changes

2017-03-28 07:18 UTC, nox commented
Squash the two commits together and this is ready to be merged.

2017-03-28 08:13 UTC, ferjm commented
Thank you @nox. Rebased and squashed.

2017-03-28 08:14 UTC, nox commented
@jdm Shouldn't `tests/wpt/mozilla/tests/mozilla/block-mime-as-script.html` be in `tests/wpt/web-platform-tests` instead?

2017-03-29 09:15 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #16160) made this pull request unmergeable. Please resolve the merge conflicts.

2017-03-29 12:23 UTC, ferjm commented
Rebased and moved tests to `tests/wpt/web-platform-tests`

2017-04-03 13:29 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #16214) made this pull request unmergeable. Please resolve the merge conflicts.

2017-04-03 14:46 UTC, jdm commented
Seems good to me.

2017-04-03 15:43 UTC, nox commented on components/net/fetch/methods.rs
> +                    NetworkError::Internal("Blocked by nosniff or mime type".into()));
Please instead do a `else if` block and separate the two blocking errors.

2017-04-03 17:12 UTC, ferjm commented
Done. r? @nox

2017-04-05 07:15 UTC, nox commented
@bors-servo r+

2017-04-05 07:15 UTC, bors-servo commented
:pushpin: Commit 29a56c4 has been approved by `nox`

<!-- @bors-servo r=nox 29a56c4d1a0a19166320ef47a6cdcf20524d8272 -->

2017-04-05 07:34 UTC, bors-servo commented
:hourglass: Testing commit 29a56c4d1a0a19166320ef47a6cdcf20524d8272 with merge 1071c3339fd858014382b4e9938584279555b5ec...

2017-04-05 08:14 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6143), [arm32](http://build.servo.org/builders/arm32/builds/6363), [arm64](http://build.servo.org/builders/arm64/builds/6396), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6498), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3229), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3251), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6503), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6532), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3188), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3255), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1671)
Approved by: nox
Pushing 1071c3339fd858014382b4e9938584279555b5ec to master...

2017-04-05 08:14 UTC, merged