Terminate timer scheduler thread during shutdown
servo/servo pull request #16184
Opened 2017-03-29 18:43 UTC by ferjm

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #16153 

r? @jdm

2017-03-29 18:43 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/pipeline.rs, components/constellation/constellation.rs, components/constellation/timer_scheduler.rs
 * @fitzgen: components/script/timers.rs, components/script/dom/globalscope.rs, components/script/script_thread.rs, components/script/dom/window.rs, components/script_traits/lib.rs, components/script_traits/lib.rs
 * @kichjang: components/script/timers.rs, components/script/dom/globalscope.rs, components/script/script_thread.rs, components/script/dom/window.rs, components/script_traits/lib.rs, components/script_traits/lib.rs

2017-03-29 18:43 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-03-29 18:44 UTC, ferjm commented
r? @jdm

2017-03-30 00:48 UTC, jdm requested changes
This looks really good!

2017-03-30 00:48 UTC, jdm commented on components/constellation/timer_scheduler.rs
>                      timeout_thread.unpark();
We should probably unpark the thread before breaking out of this loop.

2017-03-30 12:12 UTC, jdm commented
Looks good. Squash and r=me!
@bors-servo: delegate+

2017-03-30 12:12 UTC, bors-servo commented
:v: @ferjm can now approve this pull request

2017-03-30 12:12 UTC, jdm approved these changes

2017-03-30 12:30 UTC, ferjm commented
Thank you Josh!

@bors-servo r=jdm

2017-03-30 12:30 UTC, bors-servo commented
:pushpin: Commit fb878f3 has been approved by `jdm`

<!-- @bors-servo r=jdm fb878f33d1a15425c59f94ce5202010c5400f9ed -->

2017-03-30 12:31 UTC, bors-servo commented
:hourglass: Testing commit fb878f33d1a15425c59f94ce5202010c5400f9ed with merge a3d968833ba3653dd2b91f67adeb6c3faa1a256c...

2017-03-30 13:07 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6051), [arm32](http://build.servo.org/builders/arm32/builds/6271), [arm64](http://build.servo.org/builders/arm64/builds/6304), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6406), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3137), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3158), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6410), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6440), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3096), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3161), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1579)
Approved by: jdm
Pushing a3d968833ba3653dd2b91f67adeb6c3faa1a256c to master...

2017-03-30 13:07 UTC, merged