Update WR (various optimizations, gradient improvements).
servo/servo pull request #16200
Opened 2017-03-31 04:15 UTC by glennw

2017-03-31 04:15 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @emilio: components/layout/webrender_helpers.rs, components/canvas/webgl_paint_thread.rs

2017-03-31 04:15 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify layout code, but no tests are modified. Please consider adding a test!

2017-03-31 04:15 UTC, glennw commented
r? @emilio or @mrobinson

2017-03-31 04:15 UTC, glennw commented
@bors-servo try

2017-03-31 04:15 UTC, bors-servo commented
:hourglass: Trying commit b91cce3ec66193caf966117447a3b0072c4659a9 with merge 8c5c1a212f731e70e85f0e53656e06cf1f55a703...

2017-03-31 04:55 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6064), [arm32](http://build.servo.org/builders/arm32/builds/6284), [arm64](http://build.servo.org/builders/arm64/builds/6317), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6419), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3150), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3172), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6423), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6453), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3109), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3174), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1592)
State: approved= try=True

2017-03-31 05:13 UTC, jdm requested changes

2017-03-31 05:13 UTC, jdm commented on components/canvas/webgl_paint_thread.rs
> +                        // the spurious clone().
No such thing any more.

2017-03-31 05:13 UTC, jdm commented on components/compositing/compositor.rs
> +        ScrollRootId(*self as usize)
Maybe update the inner type in ScrollRootId?

2017-03-31 05:27 UTC, glennw commented
@jdm Fixed the comment.

I left the internal type as usize because it relies on an AtomicUsize. The AtomicU64 type is marked as unstable - I thought it would be best to not introduce a requirement for the unstable AtomicU64 (it's also not clear to me if 32bit android guarantees AtomicU64 is available). Switching the type to u64 but keeping the atomic as usize introduces more casts than the current PR, I think. Thoughts?

2017-03-31 05:41 UTC, jdm commented
That seems like a reasonable choice.

2017-03-31 09:26 UTC, emilio reviewed
Looks good to me with nits, thanks!

2017-03-31 09:26 UTC, emilio commented on components/canvas/canvas_paint_thread.rs
> +                                width: size.width as u32,
nit: Indentation looks weird here. Either indent membersfour spaces from `webrender_traits`, or move it to the left so the members are aligned with `descriptor`

2017-03-31 09:26 UTC, emilio commented on components/compositing/compositor.rs
> +        ScrollRootId(*self as usize)
The problem with this is that is lossy in 32-bit platforms... But probably that's ok assuming we only pass `usize`s to WR. Perhaps leave a comment or something?

2017-03-31 17:30 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #15868) made this pull request unmergeable. Please resolve the merge conflicts.

2017-04-02 20:49 UTC, glennw commented
@emilio Rebased and fixed nits.

2017-04-02 22:04 UTC, emilio commented
@bors-servo r+

2017-04-02 22:04 UTC, bors-servo commented
:pushpin: Commit 6dd3bc2 has been approved by `emilio`

<!-- @bors-servo r=emilio 6dd3bc29e15927ed1250f2ee49d8c3979709125f -->

2017-04-02 22:05 UTC, bors-servo commented
:hourglass: Testing commit 6dd3bc29e15927ed1250f2ee49d8c3979709125f with merge e45d7e0e2e5d47945d3d821db5767feff64d7634...

2017-04-02 22:47 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6097), [arm32](http://build.servo.org/builders/arm32/builds/6317), [arm64](http://build.servo.org/builders/arm64/builds/6350), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6452), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3183), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3205), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6457), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6486), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3142), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3207), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1625)
Approved by: emilio
Pushing e45d7e0e2e5d47945d3d821db5767feff64d7634 to master...

2017-04-02 22:47 UTC, merged