Overwrite default RunInfo values with the first real ones encountered.
servo/servo pull request #16258
Opened 2017-04-04 13:18 UTC by jdm

TextRunScanner::flush_clump_to_list compares the values in the RunInfo object against the ones determined from the current fragment, but these values can be arbitrary defaults that don't mean anything useful.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14783
- [X] There are tests for these changes

2017-04-04 13:18 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @emilio: components/layout/text.rs

2017-04-04 13:18 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.

2017-04-04 13:18 UTC, jdm commented
@stshine Is this something you could review?

2017-04-04 13:19 UTC, jdm commented
@bors-servo: try

2017-04-04 13:19 UTC, bors-servo commented
:hourglass: Trying commit 60f09b7328bb4973af82d93b2cffe8353f2d9be3 with merge 4a3a69208aa8db98204837627f15b674540a8db4...

2017-04-04 13:44 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3237)

2017-04-04 13:52 UTC, jdm commented
Sigh. The new test passes on my machine and fails on both the linux and mac builders.

2017-04-05 19:41 UTC, stshine requested changes
This looks good to me. However, to make `text-overflow` actually working we need #16265 get merged first.

2017-04-05 19:44 UTC, stshine commented on components/layout/text.rs
> +                    if !initialized_run_info {
During the iteration every time we start to deal with a fragment if the font changed we may create an empty mapping, and when we are done with a fragment we flush all the remaining text to mapping, so instead using a temp variable for the whole iteration we should check if end_position is zero.

2017-04-06 00:41 UTC, stshine commented
@bors-servo try

2017-04-06 00:42 UTC, stshine commented
@bors-servo retry

2017-04-06 00:42 UTC, bors-servo commented
:hourglass: Trying commit 60f09b7328bb4973af82d93b2cffe8353f2d9be3 with merge d93d627287008fad8a263e0b4c57149d3876f48f...

2017-04-06 01:20 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6155), [arm32](http://build.servo.org/builders/arm32/builds/6375), [arm64](http://build.servo.org/builders/arm64/builds/6408), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6510), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3241), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3263), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6515), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6544), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3200), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3267), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1683)
State: approved= try=True

2017-04-11 05:02 UTC, jdm commented on components/layout/text.rs
> +                    if !initialized_run_info {
Fixed.

2017-04-11 05:36 UTC, stshine approved these changes
Looks good!

2017-04-11 06:52 UTC, jdm commented
@bors-servo: r=stshine

2017-04-11 06:52 UTC, bors-servo commented
:pushpin: Commit a2e8ab4 has been approved by `stshine`

<!-- @bors-servo r=stshine a2e8ab4af30ab57f8920da0d002638ff9cb834b8 -->

2017-04-11 06:52 UTC, bors-servo commented
:hourglass: Testing commit a2e8ab4af30ab57f8920da0d002638ff9cb834b8 with merge a5b035e2b890cdb776579cbc02e2967747989ecf...

2017-04-11 07:18 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6621)

2017-04-11 11:43 UTC, stshine commented
IMO the failure is caused by `run_info` not flushed at time. This code is quite complicated, so for a simple solution, you can only flush the mappings when the `end_position` is not 0. Like:

```
                    if flush_mapping {
                        if end_position != 0 {
                            mapping.flush(&mut mappings,
                            ...
```

2017-04-12 04:44 UTC, jdm commented
The tests still fail with changes like the one suggested.

2017-04-12 04:59 UTC, jdm commented
@bors-servo: try

2017-04-12 04:59 UTC, bors-servo commented
:hourglass: Trying commit 7c9efa6f2bd0437176badf74a54e90b4dadfbedc with merge e07f4842cf4ef77e432efbf5fb982d5e1cb13249...

2017-04-12 05:46 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6256), [arm32](http://build.servo.org/builders/arm32/builds/6474), [arm64](http://build.servo.org/builders/arm64/builds/6508), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6610), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3344), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3367), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6614), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6648), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3300), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3370), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1785)
State: approved= try=True

2017-04-12 06:36 UTC, jdm commented
@pcwalton Could you verify that this makes sense?

2017-04-12 23:43 UTC, pcwalton commented
Looks good overall. Only one nit: maybe rename `flush_mapping` to `new_mapping_needed`. With this patch as is, the `flush_mapping` Boolean doesn't necessarily mean the mapping is flushed, which could be confusing.

2017-04-12 23:57 UTC, jdm commented
@bors-servo: r=pcwalton,stshine

2017-04-12 23:57 UTC, bors-servo commented
:pushpin: Commit a20d0bc has been approved by `pcwalton,stshine`

<!-- @bors-servo r=pcwalton,stshine a20d0bccef0706cdfaac8d932e80782581ad542f -->

2017-04-12 23:57 UTC, bors-servo commented
:hourglass: Testing commit a20d0bccef0706cdfaac8d932e80782581ad542f with merge 628ba1d802a85acb2bffdf452564ba68d4d6b835...

2017-04-13 00:04 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/6291)

2017-04-13 04:07 UTC, jdm commented
@bors-servo: retry

2017-04-13 04:09 UTC, bors-servo commented
:hourglass: Testing commit a20d0bccef0706cdfaac8d932e80782581ad542f with merge 9c0d8e44a005ef68f805569f535a6ffa1f46d627...

2017-04-13 04:57 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6301), [arm32](http://build.servo.org/builders/arm32/builds/6513), [arm64](http://build.servo.org/builders/arm64/builds/6548), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6649), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3386), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3409), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6653), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6690), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3339), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3410), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1826)
Approved by: pcwalton,stshine
Pushing 9c0d8e44a005ef68f805569f535a6ffa1f46d627 to master...

2017-04-13 04:57 UTC, merged

2017-04-13 05:05 UTC, stshine commented
@jdm Thank you for letting me review.