(Do not merge) Partially implement blocking as mixed content
servo/servo pull request #16320
Opened 2017-04-09 15:45 UTC by nox

2017-04-09 15:45 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/request.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/htmlscriptelement.rs, components/script/dom/window.rs, components/script_traits/lib.rs, components/script_traits/lib.rs, components/script/dom/document.rs, components/script/dom/workerglobalscope.rs, components/script/dom/htmlmediaelement.rs, components/script/stylesheet_loader.rs, components/script/dom/dedicatedworkerglobalscope.rs, components/script/dom/htmlimageelement.rs, components/script/script_thread.rs, components/script/dom/htmliframeelement.rs, components/script/dom/globalscope.rs, components/script/dom/bindings/trace.rs, components/script/dom/eventsource.rs, components/script/dom/serviceworkerglobalscope.rs
 * @kichjang: components/script/dom/request.rs, components/script/dom/xmlhttprequest.rs, components/script/dom/htmlscriptelement.rs, components/net_traits/response.rs, components/net_traits/response.rs, components/script/dom/window.rs, components/script_traits/lib.rs, components/script_traits/lib.rs, components/script/dom/document.rs, components/net/http_loader.rs, components/script/dom/workerglobalscope.rs, components/net_traits/lib.rs, components/net_traits/lib.rs, components/script/dom/htmlmediaelement.rs, components/script/stylesheet_loader.rs, components/net/blob_loader.rs, components/script/dom/dedicatedworkerglobalscope.rs, components/script/dom/htmlimageelement.rs, components/script/script_thread.rs, components/script/dom/htmliframeelement.rs, components/net/fetch/methods.rs, components/script/dom/globalscope.rs, components/script/dom/bindings/trace.rs, components/script/dom/eventsource.rs, components/net_traits/request.rs, components/net_traits/request.rs, components/script/dom/serviceworkerglobalscope.rs

2017-04-09 15:45 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify gfx, net, and script code, but no tests are modified. Please consider adding a test!

2017-04-09 15:45 UTC, nox commented
@bors-servo try

2017-04-09 15:45 UTC, bors-servo commented
:hourglass: Trying commit 93a5f07ce6ef183cbd0418cf839d0e602135ffba with merge 887456fd4ea8c35aa9ff4093a7aa68a91475034c...

2017-04-09 16:22 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6208), [arm32](http://build.servo.org/builders/arm32/builds/6427), [arm64](http://build.servo.org/builders/arm64/builds/6461), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6563), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3294), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3319), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6568), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6597), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3253), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3320), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1736)
State: approved= try=True

2017-04-09 16:43 UTC, nox commented
This covers the script and style cases from https://github.com/servo/servo/issues/8582, AFAICT.

2017-04-09 21:07 UTC, jdm commented
This should modify script/layout_image.rs as well.

2017-04-09 23:50 UTC, jdm commented
I'm interested in having @avadacatavra review this.

2017-04-11 21:59 UTC, avadacatavra commented on components/net/http_loader.rs
> +        let http_message = res.response.get_ref().downcast_ref::<Http11Message>().unwrap();
all of this is to figure out if the response is served over https, right?

2017-04-11 22:01 UTC, nox commented on components/net/http_loader.rs
> +        let http_message = res.response.get_ref().downcast_ref::<Http11Message>().unwrap();
Yes. I could more simply just check that the request's URL scheme was "https", but this checks that the very stream that handles the bits over the wire actually uses an `HttpsStream`, so I think that is better. And we will need that code when we will finally look at the actual cypher anyway.

2017-04-11 22:10 UTC, avadacatavra commented on components/net/http_loader.rs
> +        let http_message = res.response.get_ref().downcast_ref::<Http11Message>().unwrap();
i agree :)

2017-04-11 22:24 UTC, avadacatavra commented on components/net/Cargo.toml
> +hyper = "0.10.8"
why do we need to specify 0.10.8 instead of just 0.10?

2017-04-11 22:24 UTC, avadacatavra commented on components/net/Cargo.toml
> +hyper-openssl = "0.2.6"
same question--why do we need to specify past 0.2?

2017-04-11 22:38 UTC, nox commented on components/net/Cargo.toml
> +hyper = "0.10.8"
Good practice, the `get_ref` functions are in hyper 0.10.8.

2017-04-11 22:39 UTC, nox commented on components/net/Cargo.toml
> +hyper-openssl = "0.2.6"
Same reason, though I ended up not using the `lock` function I introduced in `0.2.6`, given we don't need to look at the cipher yet.

2017-04-11 22:46 UTC, jdm requested changes

2017-04-11 22:46 UTC, jdm commented on components/net/fetch/methods.rs
> +            if should_replace_with_mixed_content_error {
Please remove the TODO comment about mixed content above this line.

2017-04-11 22:46 UTC, jdm commented on components/net/fetch/methods.rs
> +/// https://www.w3.org/TR/secure-contexts/#is-url-trustworthy
https://w3c.github.io/webappsec-secure-contexts/#is-url-trustworthy

2017-04-11 22:46 UTC, jdm commented on components/net/fetch/methods.rs
> +/// https://www.w3.org/TR/secure-contexts/#is-origin-trustworthy
https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy

2017-05-01 11:58 UTC, nox commented
r? @jdm

2017-05-01 15:36 UTC, jdm requested changes

2017-05-01 15:36 UTC, jdm commented on components/script/dom/xmlhttprequest.rs
> +            // TODO: handle request's client.
This is handled now.

2017-05-01 15:36 UTC, jdm commented on components/net/fetch/methods.rs
> +    // https://github.com/servo/servo/issues/16355
This hasn't been addressed yet.

2017-05-01 15:36 UTC, jdm commented on components/script/dom/window.rs
> +        self.is_top_level()
This check is backwards.

2017-05-01 15:36 UTC, jdm commented on components/script/dom/window.rs
> +            match responsible_document.window().parent_info() {
This is broken for cross-origin iframes. We will need to talk to the constellation to make this work correctly.

2017-05-01 19:22 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #16677) made this pull request unmergeable. Please resolve the merge conflicts.

2017-11-14 11:13 UTC, avadacatavra commented
@nox what's the status on this?

2017-11-15 22:36 UTC, jdm commented
Closing due to inactivity; tracking in https://github.com/servo/servo/issues/19243.

2017-11-15 22:36 UTC, closed without merging