Unminify JS and dump it to a file before executing it
servo/servo pull request #16348
Opened 2017-04-11 12:41 UTC by ferjm

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14824

2017-04-11 12:41 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmlscriptelement.rs, components/script/dom/window.rs
 * @kichjang: components/script/dom/htmlscriptelement.rs, components/script/dom/window.rs

2017-04-11 12:41 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-04-11 21:52 UTC, jdm requested changes
This is fantastic! Very readable changes, too. Nice work.

2017-04-11 21:52 UTC, jdm commented on components/script/dom/htmlscriptelement.rs
> +                              .expect("Failed to execute js-beautify");
Instead of making this a fatal error, let's dump the unmodified script into the file if js-beautify isn't available and leave an informative debug!.

2017-04-11 21:52 UTC, jdm commented on components/script/dom/htmlscriptelement.rs
> +            let path_parts = url.split("/").collect::<Vec<&str>>();
Let's use `script.url.path_segments().unwrap()` instead.

2017-04-11 21:52 UTC, jdm commented on components/script/dom/htmlscriptelement.rs
> +        }
Let's add a message if creating the file fails for some reason.

2017-04-12 09:45 UTC, ferjm commented
Thank you @jdm! I just addressed your feedback.

2017-04-12 12:55 UTC, jdm approved these changes

2017-04-12 12:55 UTC, jdm commented
@bors-servo: r+
Wonderful!

2017-04-12 12:55 UTC, bors-servo commented
:pushpin: Commit 11f227b has been approved by `jdm`

<!-- @bors-servo r=jdm 11f227b4fff8e832f1bd140ee7db70d10475aea0 -->

2017-04-12 16:11 UTC, bors-servo commented
:hourglass: Testing commit 11f227b4fff8e832f1bd140ee7db70d10475aea0 with merge bc9d7863b6763e59f7efed3d5c9870b19bafb195...

2017-04-12 17:03 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6282), [arm32](http://build.servo.org/builders/arm32/builds/6497), [arm64](http://build.servo.org/builders/arm64/builds/6532), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6633), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3370), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3393), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6637), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6674), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3323), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3394), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/1810)
Approved by: jdm
Pushing bc9d7863b6763e59f7efed3d5c9870b19bafb195 to master...

2017-04-12 17:03 UTC, merged