Included block to handle application/xml
servo/servo pull request #16341
Opened 2017-04-11 05:38 UTC by pcpeters

Hey @jdm, based on my understanding of the issue, I have added a new branch in the match to handle application/xml content type. So now when the block encounters application/xml, it  does nothing special and proceeds to process the rest of the page as usual.  The "Unknown content type" message is no longer displayed when application/xml is encountered.

Is this the update that was expected? It seems like a very simple fix and I was wondering if there was something that I was missing out on doing (like adding a new and more relevant message on encountering application/xml)
 
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15850 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-04-11 05:38 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @nox (or someone else) soon.

2017-04-11 05:38 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/servoparser/mod.rs
 * @kichjang: components/script/dom/servoparser/mod.rs

2017-04-11 05:38 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-04-11 06:47 UTC, jdm commented
@bors-servo: try

2017-04-11 06:47 UTC, bors-servo commented
:hourglass: Trying commit f962fade7e23636f294dba493f6591b45ae86c60 with merge fc9b056f0941fe258dcd6bbebaf3b2e9e6a928ee...

2017-04-11 07:08 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3274)

2017-04-11 07:25 UTC, KiChjang requested changes

2017-04-11 07:25 UTC, KiChjang commented on components/script/dom/servoparser/mod.rs
> +            Some(ContentType(Mime(TopLevel::Application, SubLevel::Xml, _))) => {}, // Handle application/xml
I don't think adding a new match arm here is the correct move; the issue says that `application/xml` should be treated the same as `text/xml`, so both enum variants should be on the same match arm.

2017-04-11 07:29 UTC, KiChjang commented
Also, your changes have made numerous test cases pass (yay!), but our test infrastructure expects them to fail. You'll also need to update your PR to change the test expectations accordingly. Here's the list of tests that passed:

<details>

```
  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("1foo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("1:foo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("fo o") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("}foo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f}oo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo}") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("\\ufffffoo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f\\uffffoo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo\\uffff") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("<foo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("foo>") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("<foo>") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("f<oo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement("-foo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElement.html:
  └ PASS [expected FAIL] createElement(".foo") in XML document

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,null,null

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,undefined,null

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"foo",null

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"1foo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"f1oo",null

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"foo1",null

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"}foo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"f}oo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"foo}","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"\\ufffffoo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"f\\uffffoo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"foo\\uffff","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"<foo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"foo>","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"<foo>","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"f<oo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"^^","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"fo o","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"-foo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,".foo","INVALID_CHARACTER_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,":foo","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"f:oo","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"foo:","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"f:o:o","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,":","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"xml",null

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"xmlns","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"xmlfoo",null

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"xml:foo","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"xmlns:foo","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"xmlfoo:bar","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in XML document: null,"null:xml","NAMESPACE_ERR"

  ▶ Unexpected subtest result in /dom/nodes/Document-createElementNS.html:
  └ PASS [expected FAIL] createElementNS test in  [...]

2017-04-11 07:40 UTC, jdm commented
`./mach test-wpt tests/wpt/web-platform-tests/dom/nodes --log-raw /tmp/servo && ./mach update-wpt /tmp/servo` then commit the changes that appear.

2017-04-11 15:27 UTC, pcpeters commented on components/script/dom/servoparser/mod.rs
> +            Some(ContentType(Mime(TopLevel::Application, SubLevel::Xml, _))) => {}, // Handle application/xml
Can I move the branches for text/xml and application/xml under the last block, i.e. this block? https://github.com/pcpeters/servo/blob/f962fade7e23636f294dba493f6591b45ae86c60/components/script/dom/servoparser/mod.rs#L591

So the way I handle text/xml and application/xml will be similar to the way application/xhtml+xml is currently being handled. 

Would that be ok? Or would it be better to have a separate branch just for text/xml and application/xml like you first suggested?

2017-04-11 21:29 UTC, KiChjang commented on components/script/dom/servoparser/mod.rs
> +            Some(ContentType(Mime(TopLevel::Application, SubLevel::Xml, _))) => {}, // Handle application/xml
I don't think moving there is appropriate. That branch is specifically for MIME types that we don't know how to parse. What we can do instead is move the matching of `application/xhtml+xml` up to the branch with `text/xml` and `application/xml`. You can use `Sublevel::Ext("xhtml+xml".to_owned())` to match against a sublevel extension type.

2017-04-27 19:08 UTC, KiChjang commented
@pcpeters Planning to finish this off?

2017-04-28 13:59 UTC, pcpeters commented
Hi @KiChjang, I do intend on completing it, however, I am currently caught up with schoolwork and finals, so I won’t be able to for another week. If it’s not urgent, can I have some extra time?

2017-04-28 14:33 UTC, jdm commented
That's fine!

2017-05-12 18:43 UTC, jdm commented
How's it going, @pcpeters?

2017-06-22 03:26 UTC, jdm commented
Closing due to lack of activity.

2017-06-22 03:26 UTC, closed without merging