[WIP] Cross origin wrappers
servo/servo pull request #16501
Opened 2017-04-17 20:38 UTC by avadacatavra

This PR adds some infrastructure required for XOWs.

Addresses #16243 and #2382

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-04-17 20:38 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/script_thread.rs, components/script/dom/window.rs, components/script/script_runtime.rs, components/script/dom/bindings/interface.rs, components/script/dom/bindings/utils.rs
 * @kichjang: components/script/script_thread.rs, components/script/dom/window.rs, components/script/script_runtime.rs, components/script/dom/bindings/interface.rs, components/script/dom/bindings/utils.rs

2017-04-17 20:38 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-04-17 22:30 UTC, asajeffrey commented
Yay, security policy!

2017-04-24 14:46 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #16592) made this pull request unmergeable. Please resolve the merge conflicts.

2017-05-01 16:54 UTC, jdm requested changes

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +    let origin = GetPrincipalOrigin(principal.0) as *mut Box<MutableOrigin>;
Casting to a `*mut Box` is incorrect; we need `*mut MutableOrigin` here so we can use [from_raw](http://doc.servo.org/std/boxed/struct.Box.html#method.from_raw) and cause its destructor to run.

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +// avadacatavra: destroy will need to retrieved the boxed origin pointer, turn it back into a box and allow it to be freed
We'll want to remove this.

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +//TODO make principal.rs
Yep.

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +        _ => CrossOriginObjectType::CrossOriginOpaque,
```rust
let name = CStr::from_ptr((*obj_class).name).to_bytes();
match name {
    b"Location" => ...,
    b"Window" => ...,
    _ => ...,
}
```

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +unsafe fn target_subsumes_obj(cx: *mut JSContext, obj: HandleObject) -> bool {
Let's call this `obj_subsumes_current_compartment`.

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +    //step 5 if nested, get base uri
We have no nested URIs in Servo.

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/codegen/CodegenRust.py
> +let origin = object.origin().clone();
Do we need this clone if we pass a reference to `create_global_object`?

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +    let other = &ServoJSPrincipal(other);
The &s aren't necessary here.

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +    //false
Since these are all covered by subsumes afaict, we don't need to leave references to them here.

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +    if !security_wrapper {
This will be easier to reason about as `if target_subsumes_obj(cx, obj) {`.

2017-05-01 16:54 UTC, jdm commented on components/script/dom/bindings/utils.rs
>      // https://github.com/servo/servo/issues/2382
These comments can go away.

2017-05-13 13:13 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #16845) made this pull request unmergeable. Please resolve the merge conflicts.

2017-11-15 22:37 UTC, jdm commented
We're waiting to return to this work until we have a more recent spidermonkey.

2017-11-15 22:37 UTC, closed without merging

2018-09-10 21:51 UTC, atouchet commented
@jdm @avadacatavra should this be re-opened now that SpiderMonkey has been updated?

2018-09-10 23:05 UTC, jdm commented
No need to do that until someone is actually working on it.