Convert nightly upload script to Python 3
servo/servo pull request #16565
Opened 2017-04-21 23:36 UTC by aneeshusa

Now that MinGW and MSYS have been removed from the Windows builders,
bash is not available to run the previous upload_nightlies.sh script.
Convert the script to Python 3 for cross-platform support.

Also, hard-code the paths to the packages instead of using
globs to look for them, as the paths are static.
(The paths used to contain timestamps,
but we now insert timestamps when uploading to S3
to improve reproducibility.)

This requires servo/saltfs#642.

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #16560 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because Buildbot will test them.

2017-04-21 23:37 UTC, aneeshusa commented
r? @larsbergstrom

2017-04-27 16:42 UTC, metajack requested changes

2017-04-27 16:42 UTC, metajack commented on etc/ci/upload_nightly
> +        'echo',
Are these calls supposed to run s3cmd not echo?

2017-04-27 16:42 UTC, metajack commented on etc/ci/upload_nightly
> +                ['echo', 'git', '-C', tmp_dir] + cmd,
Same here.

2017-04-27 21:58 UTC, aneeshusa commented
s3cmd apparently is not (well) supported on Windows, so I'll rework this to use a different tool.

2017-04-27 21:59 UTC, metajack commented
Can we just use the aws cli tool directly?

2017-05-08 19:08 UTC, metajack commented
@aneeshusa I'm happy to drive this across the line if you are busy, btw.

2017-05-10 04:41 UTC, aneeshusa commented
@metajack I would appreciate that! Here's where I was thinking of taking this:

- Avoid installing anything globally/pushing anything via saltfs.
- Port this to Python 2 and move this into `mach`.
- Use `boto3` as a python library instead of `s3cmd` via the command line. Install `boto3` as part of the `mach` Python requirements.

This should hopefully sidestep any Windows compatibility issues.

2017-05-18 20:51 UTC, aneeshusa commented
I've done the steps from my last comment and this is ready for review. I did some light smoke testing, but haven't tested actually uploading to S3 or the `update_brew` code.

2017-05-19 22:42 UTC, atouchet commented
Is this still a WIP or can that tag be removed?

2017-05-20 13:57 UTC, larsbergstrom commented
@metajack @edunham 

It looks to me like this is good to go. Should we r+ and then check to see what happens on the nightly builds?

cc @jonathandturner

2017-05-22 22:09 UTC, metajack commented
@bors-servo r+

2017-05-22 22:09 UTC, bors-servo commented
:pushpin: Commit 043f78d has been approved by `metajack`

<!-- @bors-servo r=metajack 043f78db53818431ef20d24107e445128e856822 -->

2017-05-22 22:09 UTC, metajack commented
Great work @aneeshusa. This looks like a huge improvement.

2017-05-22 23:11 UTC, bors-servo commented
:hourglass: Testing commit 043f78db53818431ef20d24107e445128e856822 with merge 9468fae0d443b2a8b9a7694f917dc097ac6c7e60...

2017-05-23 01:12 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7109), [arm32](http://build.servo.org/builders/arm32/builds/7323), [arm64](http://build.servo.org/builders/arm64/builds/7361), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7458), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4207), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4222), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7430), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/7467), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4134), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4202), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2673)
Approved by: metajack
Pushing 9468fae0d443b2a8b9a7694f917dc097ac6c7e60 to master...

2017-05-23 01:13 UTC, merged