Auto clean old nightlies on Travis
servo/servo pull request #16573
Opened 2017-04-22 19:38 UTC by UK992

This could solve no space left problem.

2017-04-22 22:20 UTC, UK992 commented
r? @aneeshusa

2017-04-22 23:01 UTC, aneeshusa requested changes
This is a good idea, thanks @UK992! I'm not sure if it will help with running out of space or not, but it doesn't hurt.

2017-04-22 23:01 UTC, aneeshusa commented on .travis.yml
> +         - ./mach clean-nightlies --keep 2 --force
Let's put this into `before_cache` instead of `script`. Docs: https://docs.travis-ci.com/user/caching/#before_cache-phase

2017-04-22 23:01 UTC, aneeshusa commented on python/servo/bootstrap_commands.py
> +                    if line.startswith("+") and "+++" not in line:
`"+++" not in line` -> `not line.startswith("+++")`

2017-04-22 23:01 UTC, aneeshusa commented on python/servo/bootstrap_commands.py
> +                    ['git', 'log', '--pretty=oneline', '--no-color', '-n', keep, '-p', commit_file],
Use `--oneline` instead of `--pretty=oneline`, and change `-p` to `--patch`.

2017-04-22 23:12 UTC, UK992 commented
done.

2017-04-22 23:21 UTC, aneeshusa commented
Looks good, I'll wait for Travis to see how it affects the output.

2017-04-22 23:25 UTC, aneeshusa approved these changes

2017-04-22 23:43 UTC, aneeshusa commented
@bors-servo r+

2017-04-22 23:43 UTC, bors-servo commented
:pushpin: Commit c5f1306 has been approved by `aneeshusa`

<!-- @bors-servo r=aneeshusa c5f13063a52f4ca415f90f3f259072af368ba79c -->

2017-04-23 00:17 UTC, bors-servo commented
:hourglass: Testing commit c5f13063a52f4ca415f90f3f259072af368ba79c with merge cc74b5b36f03dca9bd543885222ed0e6d91fedcd...

2017-04-23 00:38 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3509)

2017-04-23 02:42 UTC, jdm commented
@bors-servo: retry
* #16574

2017-04-23 03:17 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/6470), [arm32](http://build.servo.org/builders/arm32/builds/6683), [arm64](http://build.servo.org/builders/arm64/builds/6719), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6818), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3556), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3581), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6822), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6861), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3583), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2004) are reusable. Rebuilding only [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3509)...

2017-04-23 03:28 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6470), [arm32](http://build.servo.org/builders/arm32/builds/6683), [arm64](http://build.servo.org/builders/arm64/builds/6719), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6818), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3556), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3581), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6822), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6861), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3512), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3583), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2004)
Approved by: aneeshusa
Pushing cc74b5b36f03dca9bd543885222ed0e6d91fedcd to master...

2017-04-23 03:28 UTC, merged