style: Move all the fixup code into a StyleAdjuster struct.
servo/servo pull request #16608
Opened 2017-04-25 21:18 UTC by emilio

This will allow reusing it from text styles, which we need for some corner
cases, like text-align: -moz-center and similar stuff.

2017-04-25 21:18 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/lib.rs, components/style/properties/longhand/box.mako.rs, components/style/style_adjuster.rs, components/style/properties/properties.mako.rs

2017-04-25 21:18 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style and layout code, but no tests are modified. Please consider adding a test!

2017-04-25 21:18 UTC, emilio commented
@bors-servo try

2017-04-25 21:18 UTC, bors-servo commented
:hourglass: Trying commit 75cce524f5fe57a17c0f2b2ab5962c887f68599f with merge 9d86f52d902972ca99e6518bcb39ffc46db6db79...

2017-04-25 21:19 UTC, bors-servo commented
:broken_heart: Test failed - [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2066)

2017-04-25 21:22 UTC, emilio commented
@jryans wanted to take this review, since he's been looking at this lately, so...

r? @jryans

2017-04-25 21:29 UTC, emilio commented
@bors-servo retry

2017-04-25 21:29 UTC, emilio commented
@bors-servo try

2017-04-25 21:29 UTC, bors-servo commented
:hourglass: Trying commit 0be84aee4c8aaf79140edbffb76c857c3ee9ea1c with merge a22c2fd271fa2838437189ce1f3534e760c45a49...

2017-04-25 21:32 UTC, emilio commented on components/style/style_adjuster.rs
> +        self.style.mutate_box().set_position(position::absolute);
whoopsies

2017-04-25 21:35 UTC, jryans requested changes

2017-04-25 21:35 UTC, jryans commented on components/style/properties/properties.mako.rs
> +                    //
Probably don't need this extra comment line?

2017-04-25 21:35 UTC, jryans commented on components/style/properties/properties.mako.rs
> -    % if product == "gecko":
`adjust_for_top_layer` seems to be missing these conditions, is it correct?

2017-04-25 21:39 UTC, emilio commented
@bors-servo try

2017-04-25 21:39 UTC, bors-servo commented
:hourglass: Trying commit 5812ada47aa7978b7def2847d1e0843beadcde70 with merge 2e03a24c0c545ef3d23dc0d2070193ff3ff0f2c0...

2017-04-25 21:42 UTC, jryans commented
Okay, looks good to me!

@bors-servo delegate+

2017-04-25 21:42 UTC, bors-servo commented
:v: @emilio can now approve this pull request

2017-04-25 21:53 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #16597) made this pull request unmergeable. Please resolve the merge conflicts.

2017-04-25 22:03 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/6880)

2017-04-25 22:05 UTC, emilio commented
I deserved that.

@bors-servo try

2017-04-25 22:05 UTC, bors-servo commented
:hourglass: Trying commit 25d76d29e270f9527141a8fee7704bd988e2f016 with merge bb861ebb351fd8705165b38f89ad105953a60630...

2017-04-25 22:40 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3620)

2017-04-25 23:07 UTC, emilio commented
@bors-servo try

That failure is due to the display for hypothetical box stuff. I can leave it untouched, but I want to check if the obvious thing works (probably not).

2017-04-25 23:10 UTC, emilio commented
@bors-servo try

2017-04-25 23:10 UTC, bors-servo commented
:hourglass: Trying commit e394bb5be0804b0917a3629b46cf7db94a38fe7b with merge 2cb83d4f8f0d37b1ecbb5bd5e58b248e667b673a...

2017-04-26 00:32 UTC, emilio commented
Gecko is perfectly green: https://treeherder.mozilla.org/#/jobs?repo=try&revision=5e557ace33f57b0c5869a26b28c8a2bd8f2dc887

So if Servo's fine, then this is good to merge, otherwhise I'll need to add a trivial change to preserve the previous behavior in servo (add a bool to set_adjusted_display).

@bors-servo r=jryans

2017-04-26 00:32 UTC, bors-servo commented
:pushpin: Commit e394bb5 has been approved by `jryans`

<!-- @bors-servo r=jryans e394bb5be0804b0917a3629b46cf7db94a38fe7b -->

2017-04-26 00:32 UTC, bors-servo commented
:hourglass: Testing commit e394bb5be0804b0917a3629b46cf7db94a38fe7b with merge e68629029a0277e007e39e6bd3a38904ab30c1cc...

2017-04-26 01:06 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3626)

2017-04-26 01:28 UTC, emilio commented
@bors-servo r=jryans

There are a few interesting potential passes showing up the brokennes of our current approach too, but this stuff is tricky to fix, and I don't have time for it right now.

2017-04-26 01:28 UTC, bors-servo commented
:pushpin: Commit ccf15c0 has been approved by `jryans`

<!-- @bors-servo r=jryans ccf15c0a267e1ee6dac67a1392aec1860dbcd294 -->

2017-04-26 01:31 UTC, bors-servo commented
:hourglass: Testing commit ccf15c0a267e1ee6dac67a1392aec1860dbcd294 with merge 09f0ff74811405eb95200ee78d936b4378de65fb...

2017-04-26 02:31 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6543), [arm32](http://build.servo.org/builders/arm32/builds/6754), [arm64](http://build.servo.org/builders/arm64/builds/6789), [linux-dev](http://build.servo.org/builders/linux-dev/builds/6889), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3628), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/3657), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/6892), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/6931), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3582), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/3651), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2078)
Approved by: jryans
Pushing 09f0ff74811405eb95200ee78d936b4378de65fb to master...

2017-04-26 02:31 UTC, merged