Upgrade unicode-bid to ^0.3
servo/servo pull request #16779
Opened 2017-05-09 01:18 UTC by behnam

Depends on https://github.com/servo/unicode-bidi/pull/27 , which
upgrades `unicode-bidi` crate to `0.3.0`.

Summary of changes:

* Use `unicode_bidi::Level` (instead of `u8`) in all relevant places and
replace magic computations with (inline) method calls to Level API.

* Doing so required adding `unicode-bidi` crate dependency to two more
components here: `style` and `gfx`. IMHO, totally makes sense, as
replaces local integer manipulations/checks with well-tested ones
already available in a common dependency.

TODO, while other aspects of the diff are being reviewed:
* Upgrade `idna` crate, which would fix `./mach test-tidy`.

---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-05-09 01:18 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @glennw (or someone else) soon.

2017-05-09 01:18 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/Cargo.toml, components/style/properties/longhand/inherited_text.mako.rs, components/style/lib.rs, components/style/logical_geometry.rs
 * @emilio: components/style/Cargo.toml, components/style/properties/longhand/inherited_text.mako.rs, components/style/lib.rs, components/layout/Cargo.toml, components/style/logical_geometry.rs and 2 more

2017-05-09 01:18 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style, layout, and gfx code, but no tests are modified. Please consider adding a test!

2017-05-09 01:49 UTC, behnam commented
r? @emilio @mbrubeck

2017-05-16 19:37 UTC, behnam commented
`unicode-bidi` API is now going stable for `0.3.0`. This should be good to go after https://github.com/servo/unicode-bidi/pull/31 is landed.

2017-05-17 09:11 UTC, emilio commented
`./mach test-tidy` is failing:
```
./Cargo.lock:1: duplicate versions for package `unicode-bidi`
	The following packages depend on version 0.2.5 from 'crates.io':
		idna
	The following packages depend on version 0.3.0 from '':
		gfx
		layout
		style

./Cargo.lock:1: duplicate versions for package `serde`
	The following packages depend on version 0.9.15 from 'crates.io':
		webvr_traits
		app_units
		bincode
		bluetooth_traits
		canvas_traits
		constellation
		core-graphics
		cssparser
		devtools
		devtools_traits
		dwrote
		euclid
		gfx
		gfx_traits
		hyper_serde
		ipc-channel
		layout
		msg
		net
		net_traits
		offscreen_gl_context
		profile
		profile_traits
		range
		rust-webvr
		script
		script_traits
		serde_json
		servo_config
		servo_url
		string_cache
		style
		style_traits
		unicode-bidi
		url_serde
		uuid
		webrender_traits
	The following packages depend on version 1.0.5 from 'crates.io':
		serde_test

2017-05-17 17:37 UTC, behnam commented
Right, crates.io is not updated with the latest version yet. The `idna` crate is compatible with `unicode-bidi:0.3.0` already, so getting `0.3.0` on crates.io should fix all the problems here.

I'll update here when it's ready. Thanks.

2017-05-17 19:22 UTC, behnam commented
Okay, new `unicode-bidi` versions are published on crates.io and here's the latest state of this PR:
```
$ ./mach test-tidy
Checking the config file...
Checking directories for correct file extensions...
Checking files for tidiness...
./Cargo.lock:1: duplicate versions for package `unicode-bidi`
	The following packages depend on version 0.2.6 from 'crates.io':
		idna
	The following packages depend on version 0.3.0 from 'crates.io':
		gfx
		layout
		style
  Progress: 100% (11/11)
```

I have tried manually editing `Cargo.lock` to address this, but `./mach build` puts `0.2.6` back in for `idna`. I'm guessing that it's because of `servo` depending on `unicode-bidi`'s `with_servo` feature, but `idna` doesn't.

I suppose an eventual `cargo update` would fix this, but that changes just too much dependencies.

Anyways, I don't know what's the right fix here. Any suggestions, @emilio, @mbrubeck?

2017-05-17 19:34 UTC, jdm commented
@behnam https://github.com/servo/rust-url/blob/master/idna/Cargo.toml#L22 needs to be updated, and a new version of idna needs to be published, and then Servo needs to update to the new idna version.

2017-05-19 02:48 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #16941) made this pull request unmergeable. Please resolve the merge conflicts.

2017-05-19 17:44 UTC, mbrubeck commented
Looks good!  r=mbrubeck for the code changes.  This should also fix some tests, so it should get a `try` run once it is mergeable.

2017-05-19 17:44 UTC, mbrubeck approved these changes

2017-05-22 17:26 UTC, behnam commented
Now good to go.

FYI, this triggers the following warning:
```
warning: use of deprecated item: please use `BidiInfo::visual_runs()` instead.
   --> /Users/behnam/code/servo/servo/components/layout/inline.rs:313:28
    |
313 |                 let runs = bidi::deprecated::visual_runs(range, &levels);
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default
```

I'm still not sure what's the expected behavior on this call-site, so the code is not updated. The new implementation of that function, `BidiInfo::visual_runs()`, needs access to the text (for the char length data) and their original bidi-type, and that's why it's now an instance method of `BidiInfo`.

2017-05-23 00:04 UTC, behnam commented
Okay, fixed all the little side issues I caused here and all the tests are passing in `idna` and `servo`.

@mbrubeck, @emilio, r?

2017-05-23 00:51 UTC, mbrubeck requested changes
r=mbrubeck with one minor change.

2017-05-23 00:51 UTC, mbrubeck commented on components/layout/inline.rs
> +                let runs = bidi::deprecated::visual_runs(range, &levels);
Please add `#[allow(deprecated)]` above this line, to silence the warning.

2017-05-23 01:05 UTC, behnam commented
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/inline.rs, line 313 at r1](https://reviewable.io:443/reviews/servo/servo/16779#-KjemM6CrymUSqZ61zua-r1-313:-Kkmpe0pTcDly66fWqC9:b-896fix) ([raw file](https://github.com/servo/servo/blob/2523e555938649678de0dde5a587fddb998722e1/components/layout/inline.rs#L313)):*
<details><summary><i>Previously, mbrubeck (Matt Brubeck) wrote…</i></summary><blockquote>

Please add `#[allow(deprecated)]` above this line, to silence the warning.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16779)*
<!-- Sent from Reviewable.io -->

2017-05-23 02:32 UTC, mbrubeck commented
@bors-servo r+

2017-05-23 02:32 UTC, bors-servo commented
:pushpin: Commit 14c524d has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck 14c524df4f38a8b8262b3ba458c100966377d072 -->

2017-05-23 04:06 UTC, bors-servo commented
:hourglass: Testing commit 14c524df4f38a8b8262b3ba458c100966377d072 with merge edd6c2cecb2c245f9f8bcab04ff8e57f1c5d1333...

2017-05-23 05:16 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7111), [arm32](http://build.servo.org/builders/arm32/builds/7325), [arm64](http://build.servo.org/builders/arm64/builds/7363), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7460), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4209), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4224), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7432), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/7469), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4136), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4204), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2675)
Approved by: mbrubeck
Pushing edd6c2cecb2c245f9f8bcab04ff8e57f1c5d1333 to master...

2017-05-23 05:17 UTC, merged