Implement Houdini worklets
servo/servo pull request #16814
Opened 2017-05-11 16:17 UTC by asajeffrey

This PR implements the current draft Houdini Worklets specification (https://drafts.css-houdini.org/worklets/).

The implementation is intended to provide a responsive environment for worklet execution, and in particular to ensure that the primary worklet executor does not garbage collect, and does not block loading module code. The implementation does this by providing a thread pool, and performing GC and module loading in a backup thread, not in the primary thread.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #16206 
- [x] There are tests for these changes

2017-05-11 16:17 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/tidy/servo_tidy/tidy.py
 * @fitzgen: components/script/dom/webidls/Console.webidl, components/script/dom/testworkletglobalscope.rs, components/script/dom/mod.rs, components/script/dom/window.rs, components/script/dom/webidls/Window.webidl and 20 more
 * @kichjang: components/script/dom/webidls/Console.webidl, components/script/dom/testworkletglobalscope.rs, components/script/dom/mod.rs, components/script/dom/window.rs, components/script/dom/webidls/Window.webidl and 17 more

2017-05-11 16:17 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-05-11 16:17 UTC, asajeffrey commented
r? @jdm

2017-05-12 15:55 UTC, asajeffrey commented
cc @tschneidereit @metajack

2017-05-12 16:03 UTC, metajack commented
cc @bfgeek

2017-05-12 16:12 UTC, asajeffrey commented
Some things that should probably be fixed before this lands:
 * the methods in `globalscope` which use downcasting are missing some `WorkletGlobalScope` cases.
 * threads should be named.
 * add time reporting code.
 * think about how to configure SM for worklet threads (in particular how to discourage GC).

The code is ready for review as-is though.

2017-05-12 16:21 UTC, asajeffrey commented
Hi @bfgeek! This is implementation of worklets in Servo, using a thread pool to ensure worklet execution isn't blocked by GC or by module loading. Mostly the spec was pretty straightforward to implement, you'll be pleased to hear!

2017-05-12 17:01 UTC, asajeffrey commented
The spec issues raised by implementing worklets (and starting on paint worklets):

* Speculative evalution (https://github.com/w3c/css-houdini-drafts/issues/406)
* Fetching and invoking a worklet script which reports an exception (https://github.com/w3c/css-houdini-drafts/issues/407)

2017-05-12 17:51 UTC, bfgeek commented
cc/ @nhiroki who works on our implementation. 

That's great to see! Thanks for filing spec issues.

2017-05-13 13:13 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #16845) made this pull request unmergeable. Please resolve the merge conflicts.

2017-05-16 15:30 UTC, jdm requested changes

2017-05-16 15:30 UTC, jdm commented on components/script/dom/webidls/Window.webidl
> +   [Pref="dom.worklet.testing.enabled"] DOMString? testWorkletLookup(DOMString key);
What if we made a separate DOM interface with a constructor so we don't need to include test-only fields in Window?

2017-05-16 15:30 UTC, jdm commented on components/script/dom/workletglobalscope.rs
> +    /// Chan to devtools
Let's use channel instead of chan in these comments.

2017-05-16 15:30 UTC, jdm commented on components/script/dom/worklet.rs
> +use uuid::Uuid;
Any reason not to collapse some of these import statements from the same modules?

2017-05-16 15:30 UTC, jdm commented on components/script/dom/worklet.rs
> +        }
We should use `reflect_dom_object` instead.

2017-05-16 15:30 UTC, jdm commented on components/script/dom/worklet.rs
> +    #[allow(dead_code)]
?

2017-05-16 15:30 UTC, jdm commented on components/script/dom/worklet.rs
> +known_heap_size!(0, WorkletId);
I would prefer using `#[ignore_heap_size_of = "Can't measure uuid"]` instead.

2017-05-16 15:30 UTC, jdm commented on components/script/dom/worklet.rs
> +        self.0.fetch_sub(offset, Ordering::AcqRel)
Why AcqRel instead of SeqCst?

2017-05-16 15:30 UTC, jdm commented on components/script/dom/worklet.rs
> +                // TODO: trigger a reflow?
This happens automatically when events run in the script thread. Did you mean something more specific?

2017-05-16 15:30 UTC, jdm commented on components/script/dom/worklet.rs
> +    ///g https://drafts.css-houdini.org/worklets/#fetch-and-invoke-a-worklet-script
nit: g

2017-05-16 15:31 UTC, jdm commented
As usual, I found these changes to be a pleasant and straightforward read. Good job!

2017-05-16 15:34 UTC, jdm commented on components/script/dom/worklet.rs
> +            .. RequestInit::default()
We should be using CORS mode here, per https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-single-module-script. We'll need to include a real origin, too.

2017-05-16 16:04 UTC, asajeffrey reviewed
Thanks for the review!

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/webidls/Window.webidl
> +   [Pref="dom.worklet.testing.enabled"] DOMString? testWorkletLookup(DOMString key);
Will do.

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/workletglobalscope.rs
> +    /// Chan to devtools
Will do.

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +use uuid::Uuid;
Minimizing the chance of annoying merge conflicts.

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +        }
I don't think you can use `reflect_dom_object` to create globals can you?

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +    #[allow(dead_code)]
This is dead code, just in for future-proofing. I can get rid of it.

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +known_heap_size!(0, WorkletId);
Will do.

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +        self.0.fetch_sub(offset, Ordering::AcqRel)
Using the weakest ordering that does the job. In this case it doesn't matter a huge amount, this isn't hot code.

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +    ///g https://drafts.css-houdini.org/worklets/#fetch-and-invoke-a-worklet-script
Oops.

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +            .. RequestInit::default()
CORS mode isn't a problem, but I'm not sure which origin to use here. One snag is that this is being done in a different thread, so we don't have access to the `MutableOrigin` of the window.

2017-05-16 16:04 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +                // TODO: trigger a reflow?
At this point, we have loaded a worklet, but not actually run it (e.g. to get a paint worklet to do its painting).

2017-05-16 16:20 UTC, jdm commented on components/script/dom/worklet.rs
> +        }
WorkletBinding isn't a global.

2017-05-16 16:21 UTC, jdm commented on components/script/dom/worklet.rs
> +            .. RequestInit::default()
Send an ImmutableOrigin from the window as part of the initiation?

2017-05-16 17:02 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +        }
Oh good point, we're in `Worklet` not `WorkletGlobalScope`.

2017-05-16 19:42 UTC, jdm approved these changes

2017-05-16 19:43 UTC, jdm commented
Squash and r=me.

2017-05-16 20:06 UTC, asajeffrey commented
@bors-servo r=jdm

2017-05-16 20:06 UTC, bors-servo commented
:pushpin: Commit 67eed3e has been approved by `jdm`

<!-- @bors-servo r=jdm 67eed3e12b102ecb287038b0c1d155261906ea79 -->

2017-05-16 21:14 UTC, asajeffrey commented
@bors-servo r=jdm

2017-05-16 21:14 UTC, bors-servo commented
:pushpin: Commit de96995 has been approved by `jdm`

<!-- @bors-servo r=jdm de9699595ef8f8745ee1390cefa421ca761afaf5 -->

2017-05-17 02:42 UTC, bors-servo commented
:hourglass: Testing commit de9699595ef8f8745ee1390cefa421ca761afaf5 with merge d8f4b59a134c6009fca9dff6af9205146c26b174...

2017-05-17 03:13 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4086)

2017-05-17 03:50 UTC, jdm commented
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface Worklet to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:73:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:13:1
```
We can either hide the Worklet interface behind an off-by-default pref or update the test to include the interface in the expected list.

2017-05-17 14:02 UTC, asajeffrey commented
I added `Worklet` to the interfaces test. @bors-servo r=jdm

2017-05-17 14:02 UTC, bors-servo commented
:pushpin: Commit af8436c has been approved by `jdm`

<!-- @bors-servo r=jdm af8436c9be4c69c07265ab1095f89982b48cdd00 -->

2017-05-17 21:20 UTC, bors-servo commented
:hourglass: Testing commit af8436c9be4c69c07265ab1095f89982b48cdd00 with merge ac99a48aeaa184d3acdb39d249636a140c4b7393...

2017-05-17 23:10 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6997), [arm32](http://build.servo.org/builders/arm32/builds/7207), [arm64](http://build.servo.org/builders/arm64/builds/7246), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7346), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4092), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4105), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7322), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/7366), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4022), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4099), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2556)
Approved by: jdm
Pushing ac99a48aeaa184d3acdb39d249636a140c4b7393 to master...

2017-05-17 23:11 UTC, merged