Renamed BrowsingContext to WindowProxy in script.
servo/servo pull request #16845
Opened 2017-05-12 20:06 UTC by asajeffrey

Renamed `script::dom::BrowsingContext` to `script::dom::WindowProxy`.

The browsing context is mostly maintained in the constellation, not in script. It would be nice to rename `constellation::Frame` to `constellation::BrowsingContext`, but that will be very confusing if there are two `BrowsingContext` types.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because renamings aren't externally visible

2017-05-12 20:06 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/script_thread.rs, components/script/dom/browsingcontext.rs and 6 more
 * @kichjang: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/script_thread.rs, components/script/dom/browsingcontext.rs and 6 more

2017-05-12 20:06 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-05-12 20:06 UTC, asajeffrey commented
cc @jdm @cbrewster

2017-05-12 21:06 UTC, jdm requested changes

2017-05-12 21:06 UTC, jdm commented on components/script/dom/bindings/codegen/Bindings.conf
> +    'path': 'dom::windowproxy::WindowProxy',
This probably isn't needed any more.

2017-05-12 21:06 UTC, jdm commented
Otherwise this looks good to me.

2017-05-12 22:22 UTC, asajeffrey commented on components/script/dom/bindings/codegen/Bindings.conf
> +    'path': 'dom::windowproxy::WindowProxy',
I tried removing it and got:
```
error[E0432]: unresolved import `dom::types::WindowProxy`
   --> /home/ajeffrey/github/asajeffrey/servo/target/debug/build/script-dcc60cde0df0c3a0/out/Bindings/DissimilarOriginWindowBinding.rs:339:5
    |
339 | use dom::types::WindowProxy;
    |     ^^^^^^^^^^^^^^^^^^^^^^^ no `WindowProxy` in `dom::types`

error[E0432]: unresolved import `dom::types::WindowProxy`
   --> /home/ajeffrey/github/asajeffrey/servo/target/debug/build/script-dcc60cde0df0c3a0/out/Bindings/HTMLIFrameElementBinding.rs:342:5
    |
342 | use dom::types::WindowProxy;
    |     ^^^^^^^^^^^^^^^^^^^^^^^ no `WindowProxy` in `dom::types`

error[E0432]: unresolved import `dom::types::WindowProxy`
   --> /home/ajeffrey/github/asajeffrey/servo/target/debug/build/script-dcc60cde0df0c3a0/out/Bindings/WindowBinding.rs:647:5
    |
647 | use dom::types::WindowProxy;
    |     ^^^^^^^^^^^^^^^^^^^^^^^ no `WindowProxy` in `dom::types`
```

2017-05-12 23:18 UTC, jdm commented on components/script/dom/bindings/codegen/Bindings.conf
> +    'path': 'dom::windowproxy::WindowProxy',
Ah, ok!

2017-05-12 23:18 UTC, jdm commented
@bors-servo: r+

2017-05-12 23:18 UTC, bors-servo commented
:pushpin: Commit 43ca260 has been approved by `jdm`

<!-- @bors-servo r=jdm 43ca26068935e014b1a41a6a02f45d05436577b4 -->

2017-05-13 12:09 UTC, bors-servo commented
:hourglass: Testing commit 43ca26068935e014b1a41a6a02f45d05436577b4 with merge 34d0e59849a0a3e231e47fe10d66484340b8b80c...

2017-05-13 13:12 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6904), [arm32](http://build.servo.org/builders/arm32/builds/7112), [arm64](http://build.servo.org/builders/arm64/builds/7151), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7252), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/3999), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4010), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7229), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/7279), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/3928), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4009), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2457)
Approved by: jdm
Pushing 34d0e59849a0a3e231e47fe10d66484340b8b80c to master...

2017-05-13 13:12 UTC, merged