Renamed constellation::Frame to constellation::BrowsingContext
servo/servo pull request #16876
Opened 2017-05-15 19:14 UTC by asajeffrey

Now that script has `WindowProxy` rather than `BrowsingContext` objects, we can rename `Frame` in the constellation to `BrowsingContext`. In particular, this means that `FrameId`s are now `BrowsingContextid`s, which better captures their purpose (and they are used in a lot of places, not just the constellation).

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because renaming

2017-05-15 19:14 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @jgraham: components/webdriver_server/lib.rs
 * @kichjang: components/script/dom/dissimilaroriginwindow.rs, components/script_traits/lib.rs, components/script_traits/lib.rs, components/script/dom/document.rs, components/script_traits/script_msg.rs and 12 more
 * @fitzgen: components/script/dom/dissimilaroriginwindow.rs, components/script_traits/lib.rs, components/script_traits/lib.rs, components/script/dom/document.rs, components/script_traits/script_msg.rs and 12 more
 * @emilio: components/layout/display_list_builder.rs, components/layout/fragment.rs

2017-05-15 19:14 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify layout and script code, but no tests are modified. Please consider adding a test!

2017-05-15 19:14 UTC, asajeffrey commented
r? @cbrewster

2017-05-15 19:15 UTC, asajeffrey commented
This is part of the effort to introduce `TopLevelBrowsingContextId`s. cc @paulrouget

2017-05-15 21:08 UTC, cbrewster requested changes
Yay for better naming!

2017-05-15 21:08 UTC, cbrewster commented on components/script/dom/windowproxy.rs
>      /// The frame id of the browsing context.
Update `frame id` to new terminology here and below

2017-05-15 21:08 UTC, cbrewster commented on components/script/script_thread.rs
>      /// Notify the containing document of a child frame that has completed loading.
Should we change `frame` to `iframe` here and in `handle_frame_load_event`?

2017-05-15 21:08 UTC, cbrewster commented on components/script_traits/script_msg.rs
> +    FrameSizes(Vec<(BrowsingContextId, TypedSize2D<f32, CSSPixel>)>),
Should we rename `FrameSizes` to `IFrameSizes`?

2017-05-15 21:08 UTC, cbrewster commented on components/webdriver_server/lib.rs
> +    frame_id: Option<BrowsingContextId>,
`frame_id` -> `browsing_context_id`

2017-05-15 21:28 UTC, asajeffrey reviewed
Fixups done.

2017-05-15 21:28 UTC, asajeffrey commented on components/constellation/browsingcontext.rs
> +    pub prev: Vec<SessionHistoryEntry>,
Thanks!

2017-05-15 21:28 UTC, asajeffrey commented on components/constellation/constellation.rs
> +                if self.get_activity(source_id) == DocumentActivity::Inactive {
The problem with doing that is if we then traverse so the browsing context is fully active again, then the change will have been lost.

2017-05-15 21:28 UTC, asajeffrey commented on components/script/dom/windowproxy.rs
>      /// The frame id of the browsing context.
Done.

2017-05-15 21:28 UTC, asajeffrey commented on components/script/script_thread.rs
>      /// Notify the containing document of a child frame that has completed loading.
Done.

2017-05-15 21:28 UTC, asajeffrey commented on components/script_traits/script_msg.rs
> +    FrameSizes(Vec<(BrowsingContextId, TypedSize2D<f32, CSSPixel>)>),
Done.

2017-05-15 21:28 UTC, asajeffrey commented on components/webdriver_server/lib.rs
> +    frame_id: Option<BrowsingContextId>,
Done.

2017-05-15 21:41 UTC, cbrewster approved these changes
LGTM, squash and r=me

2017-05-16 02:04 UTC, asajeffrey commented
@bors-servo r=cbrewster

2017-05-16 02:04 UTC, bors-servo commented
:pushpin: Commit 607e011 has been approved by `cbrewster`

<!-- @bors-servo r=cbrewster 607e011b050f22e10a69fc7d57d7e2dc473d979e -->

2017-05-16 08:02 UTC, bors-servo commented
:hourglass: Testing commit 607e011b050f22e10a69fc7d57d7e2dc473d979e with merge fde75e8602db024ff17f70e3770a550fa1cac807...

2017-05-16 09:00 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4064)

2017-05-16 13:46 UTC, asajeffrey commented
Crashes? Hmm, unexpected. [Goes and looks.]

2017-05-16 14:15 UTC, jdm commented
@asajeffrey That's #13480.

2017-05-16 14:15 UTC, jdm commented
@bors-servo: retry
* #13480

2017-05-16 14:21 UTC, asajeffrey commented
@jdm: on the bright side, it got me to go and have a look at #16574.

2017-05-17 04:10 UTC, bors-servo commented
:hourglass: Testing commit 607e011b050f22e10a69fc7d57d7e2dc473d979e with merge 837531992864f920342020462830b933d5ed0280...

2017-05-17 06:07 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/6980), [arm32](http://build.servo.org/builders/arm32/builds/7190), [arm64](http://build.servo.org/builders/arm64/builds/7229), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7329), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4075), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4088), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7305), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/7350), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4005), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4083), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2539)
Approved by: cbrewster
Pushing 837531992864f920342020462830b933d5ed0280 to master...

2017-05-17 06:08 UTC, merged