-Z wr-no-batch option
servo/servo pull request #16958
Opened 2017-05-19 20:47 UTC by kvark

This new debug option exposes https://github.com/servo/webrender/pull/1186

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _____ it's a debug option

2017-05-19 20:47 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2017-05-19 22:24 UTC, jdm requested changes
This looks good, but please add an entry to the list at https://github.com/kvark/servo/blob/7bbc7ba9080ef4cb9a2076673f44781eee46251a/components/config/opts.rs#L412

2017-05-20 01:44 UTC, kvark commented
Thanks @jdm , fixed now.

2017-05-20 14:21 UTC, jdm commented
@bors-servo: r+

2017-05-20 14:21 UTC, bors-servo commented
:pushpin: Commit b548e6a has been approved by `jdm`

<!-- @bors-servo r=jdm b548e6aa1c29207a88f71ab1b201a80ba1135cc9 -->

2017-05-22 00:07 UTC, bors-servo commented
:hourglass: Testing commit b548e6aa1c29207a88f71ab1b201a80ba1135cc9 with merge b42ee29c1bc66484406c289c70aa5c4795728743...

2017-05-22 02:47 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7091), [arm32](http://build.servo.org/builders/arm32/builds/7305), [arm64](http://build.servo.org/builders/arm64/builds/7343), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7439), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4189), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4203), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7412), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/7450), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4117), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4185), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2655)
Approved by: jdm
Pushing b42ee29c1bc66484406c289c70aa5c4795728743 to master...

2017-05-22 02:47 UTC, merged