Split out some mac builds
servo/servo pull request #17003
Opened 2017-05-23 11:31 UTC by larsbergstrom

Splits out the WPT and CSS tests on mac to twice as many builders, each.

2017-05-23 11:31 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @aneeshusa: etc/ci/buildbot_steps.yml

2017-05-23 11:31 UTC, larsbergstrom commented
This should not be landed until https://github.com/servo/saltfs/issues/674 is complete.

2017-05-25 23:24 UTC, larsbergstrom commented
r? @jdm or @metajack 

I think this is actually set to go, now that @edunham set up a TON of additional macs! Yay!

2017-05-26 02:50 UTC, wafflespeanut commented
... and homu queue is empty 😄

2017-05-26 03:22 UTC, jdm requested changes

2017-05-26 03:22 UTC, jdm commented on etc/ci/buildbot_steps.yml
> +  - ./mach build --release
clean-nightlies?

2017-05-26 23:50 UTC, larsbergstrom commented
r? @jdm 

I think it's fixed :-)

2017-05-27 04:11 UTC, jdm commented
@bors-servo: r+

2017-05-27 04:11 UTC, bors-servo commented
:pushpin: Commit bf5728c has been approved by `jdm`

<!-- @bors-servo r=jdm bf5728c750f4c650bbb717c0a9cfcc8c9e8fafed -->

2017-05-27 04:11 UTC, bors-servo commented
:hourglass: Testing commit bf5728c750f4c650bbb717c0a9cfcc8c9e8fafed with merge fab771612ebc1bc75d39b8980363922c0f020c4d...

2017-05-27 04:12 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/7538)

2017-05-27 15:22 UTC, larsbergstrom commented
oh, gah, I forgot that I will need to make changes to:
https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/master.cfg

And get them landed & deployed first.

@aneeshusa @edunham I need to stage that carefully, right? i.e., need to roll it out on buildbot and then immediately land this? I am kinda forgetting the exact details on adding/changing builder names.

2017-05-28 01:04 UTC, larsbergstrom commented
@bors-servo retry

2017-05-28 01:04 UTC, bors-servo commented
:hourglass: Testing commit bf5728c750f4c650bbb717c0a9cfcc8c9e8fafed with merge 9ae10c53417aef3978893044e6441b24a483e81a...

2017-05-28 02:08 UTC, larsbergstrom commented
@bors-servo retry

2017-05-28 02:08 UTC, bors-servo commented
:hourglass: Testing commit bf5728c750f4c650bbb717c0a9cfcc8c9e8fafed with merge 4ec2e8b4c56c914af9fd570acaef85460f322fa9...

2017-05-28 03:23 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7193), [arm32](http://build.servo.org/builders/arm32/builds/7407), [arm64](http://build.servo.org/builders/arm64/builds/7445), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7538), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4293), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4311), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7515), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4222), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4287), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2758)
Approved by: jdm
Pushing 4ec2e8b4c56c914af9fd570acaef85460f322fa9 to master...

2017-05-28 03:23 UTC, merged