Putting the system fonts in their own struct
servo/servo pull request #17030
Opened 2017-05-24 21:18 UTC by SimranGujral

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-05-24 21:18 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2017-05-24 21:18 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/properties/gecko.mako.rs, components/style/properties/longhand/font.mako.rs, components/style/properties/properties.mako.rs
 * @emilio: components/style/properties/gecko.mako.rs, components/style/properties/longhand/font.mako.rs, components/style/properties/properties.mako.rs

2017-05-24 21:18 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2017-05-24 21:45 UTC, emilio commented on components/style/properties/gecko.mako.rs
> +    pub stash:Stash
nit: Needs a space here. Also, `Stash` doesn't look like a great name. Perhaps `FontComputationData`? @Manishearth?

2017-05-24 21:45 UTC, emilio commented on components/style/properties/properties.mako.rs
> +/// Addresses bug 16518. This creates a separate struct for
This comment isn't particularly helpful.

2017-05-24 21:45 UTC, emilio commented on components/style/properties/properties.mako.rs
> +   pub cached_system_font: Option<longhands::system_font::ComputedSystemFont>
I don't see any usage of `cached_system_font`, I think this can be completely removed.

2017-05-24 21:57 UTC, Manishearth commented on components/style/properties/gecko.mako.rs
> +    pub stash:Stash
Works for me!

2017-05-24 23:59 UTC, Manishearth requested changes

2017-05-24 23:59 UTC, Manishearth commented on components/style/properties/gecko.mako.rs
> +    pub font_computation_data:FontComputationData
nit: space after colon, comma after Data

2017-05-24 23:59 UTC, Manishearth commented on components/style/properties/properties.mako.rs
> +/// Addresses bug 16518. The cached_system_font
No need to mention which bug this addresses.

Just say the last part; "This is where we store extra font data ..."

2017-05-24 23:59 UTC, Manishearth commented on components/style/properties/properties.mako.rs
> +/// Assigns default values for variables in struct FontComputationData
comment should be indented

2017-05-24 23:59 UTC, Manishearth commented on components/style/properties/properties.mako.rs
> +    //pub font_size_keyword: Option<(longhands::font_size::KeywordSize, f32)>,
remove this line

2017-05-24 23:59 UTC, Manishearth commented on components/style/properties/properties.mako.rs
> +            //font_size_keyword: font_size_keyword,
remove this line

2017-05-24 23:59 UTC, Manishearth commented on components/style/properties/properties.mako.rs
> +                            //self.font_size_keyword
remove this line

2017-05-25 00:40 UTC, Manishearth commented
@bors-servo r+ rollup

2017-05-25 00:40 UTC, bors-servo commented
:pushpin: Commit 46ded79 has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth 46ded79cbdf342232f98eea4c797d3afd9171391 -->

2017-05-25 02:17 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17032) made this pull request unmergeable. Please resolve the merge conflicts.

2017-05-25 14:01 UTC, bors-servo commented
:lock: Merge conflict

2017-05-25 17:15 UTC, Manishearth commented
@bors-servo r+

2017-05-25 17:15 UTC, bors-servo commented
:pushpin: Commit af124f2 has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth af124f2d89f7f0c40a38ae7b9b1b1e335d3497d6 -->

2017-05-25 17:16 UTC, bors-servo commented
:hourglass: Testing commit af124f2d89f7f0c40a38ae7b9b1b1e335d3497d6 with merge a6acf2fbb37d00069e4803b5a23f64adb3ebc4c1...

2017-05-25 17:17 UTC, bors-servo commented
:snowman: The build was interrupted to prioritize another pull request.

2017-05-25 17:18 UTC, bors-servo commented
:hourglass: Testing commit af124f2d89f7f0c40a38ae7b9b1b1e335d3497d6 with merge cd168e4a56999d0eb5d555548be825d378e6d867...

2017-05-25 17:20 UTC, bors-servo commented
:snowman: The build was interrupted to prioritize another pull request.

2017-05-25 18:53 UTC, bors-servo commented
:hourglass: Testing commit af124f2d89f7f0c40a38ae7b9b1b1e335d3497d6 with merge 8daa4ef070f0996b482a96e04bc86ecc21f7efcd...

2017-05-25 19:02 UTC, Manishearth commented
@bors-servo retry

2017-05-26 00:59 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17041) made this pull request unmergeable. Please resolve the merge conflicts.

2017-05-26 00:59 UTC, merged

2017-05-27 15:03 UTC, KiChjang commented
Why did Homu merge this PR when there is an outstanding merge conflict?

2017-05-27 15:04 UTC, Manishearth commented
This was subsumed by another pull request. So it merged, but before that it got confused. That is normal.