Separate waking the event loop, from CompositorProxy
servo/servo pull request #17068
Opened 2017-05-28 03:58 UTC by gterzian

@paulrouget first step of 15934, please take a look...

One question: one do I add the `warn!` macro to `servolib`? Also perhaps we would also want to add `box`, since I had to switch to using `Box::new`...

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-05-28 13:22 UTC, jdm commented
r? @paulrouget

2017-05-30 01:55 UTC, gterzian commented
UPDATE: also added the implementation for the cef port...

2017-05-30 09:09 UTC, paulrouget reviewed
Looks good to me. There are some nits to address. Also, I'm not 100% sure you need to use Box<CompositorProxy>.

Once these addressed, I'd like @asajeffrey to take a look as well.

2017-05-30 09:09 UTC, paulrouget commented on ports/glutin/window.rs
> +        } as Box<EventLoopRiser + Send>
Is the `as …` necessary?

2017-05-30 09:10 UTC, paulrouget commented on ports/glutin/window.rs
> +                } as Box<EventLoopRiser + Send>
Is the `as …` necessary?

2017-06-04 01:58 UTC, gterzian commented
@paulrouget Ok, I replaced the traits with structs, and addressed the other comments too... 

I'm wondering if we need to add some sort of "clone" method to `CompositorReceiver`?

2017-06-05 08:36 UTC, paulrouget requested changes

2017-06-05 08:36 UTC, paulrouget commented on ports/cef/window.rs
> +        struct CefEventLoopRiser
Add a `;` at the end after `CefEventLoopRiser`.

2017-06-05 08:36 UTC, paulrouget commented on ports/cef/window.rs
> +                } as Box<EventLoopRiser + Send>
I think you can just do:
```rust
fn clone() {
  box CefEventLoopRiser
}
```

2017-06-05 08:39 UTC, paulrouget commented
Thank you Greg. This looks good to me now (beside a nit).

I'd like to get a review from Alan.

@asajeffrey - this is the first step to clarify the Embedder <-> Constellation communication. Can you take a look too?

2017-06-05 12:22 UTC, paulrouget approved these changes

2017-06-05 14:19 UTC, asajeffrey approved these changes
LGTM, I just have an annoying bikeshedding name change. `EventLoopWakeup`?

2017-06-05 14:19 UTC, asajeffrey commented on components/compositing/compositor_thread.rs
> +pub trait EventLoopRiser : 'static + Send {
Nit: not sure about the name. A riser is a part of a staircase :)

2017-06-05 23:56 UTC, gterzian commented on components/compositing/compositor_thread.rs
> +pub trait EventLoopRiser : 'static + Send {
How about `EventLoopAwaker`, so that we have a noun? https://en.wiktionary.org/wiki/awaker

2017-06-06 03:39 UTC, paulrouget commented
```
ajeffrey> "Waker" would probably be more colloquial English: "Awaker" sounds like "I am more awake than you".
```

2017-06-06 07:47 UTC, gterzian commented
Ok, `EventLoopWaker` it is...

2017-06-07 00:53 UTC, gterzian commented
It looks like approving in Github isn't enough, and somebody needs to do a r+ at the bot...

2017-06-07 01:13 UTC, asajeffrey commented
@bors-servo r+

2017-06-07 01:13 UTC, bors-servo commented
:clipboard: Looks like this PR is still in progress, ignoring approval

2017-06-07 01:22 UTC, asajeffrey commented
Hmm, I wonder why bors reckons this is still a WIP. Is it the unchecked boxes in the PR description?

2017-06-07 03:13 UTC, paulrouget commented
Probably the title. I changed it. Do you need to re-approve?

2017-06-07 03:18 UTC, paulrouget commented
https://github.com/bundler/homu/blob/288bda90d87f6500f7dd9dd779b633f7615f72e4/homu/main.py#L352

2017-06-07 12:18 UTC, asajeffrey commented
@bors-servo r+

2017-06-07 12:18 UTC, bors-servo commented
:pushpin: Commit 3a693c7 has been approved by `asajeffrey`

<!-- @bors-servo r=asajeffrey 3a693c7a23e7c3cc1d3e57f12d1eff4b83152134 -->

2017-06-07 12:24 UTC, gterzian commented
@paulrouget @asajeffrey thanks for the review.

2017-06-07 12:52 UTC, bors-servo commented
:hourglass: Testing commit 3a693c7a23e7c3cc1d3e57f12d1eff4b83152134 with merge 7e273d6c9b86d6ffbf216e84ae7326976888e5ef...

2017-06-07 13:49 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7366), [arm32](http://build.servo.org/builders/arm32/builds/7580), [arm64](http://build.servo.org/builders/arm64/builds/7619), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7708), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4464), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4488), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7691), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/175), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/174), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4394), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4458), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/174), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/177), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2935)
Approved by: asajeffrey
Pushing 7e273d6c9b86d6ffbf216e84ae7326976888e5ef to master...

2017-06-07 13:49 UTC, merged

2017-06-07 18:46 UTC, paulrouget commented
Thank you @gterzian

2017-06-08 04:01 UTC, asajeffrey commented
@gterzian thanks!