Remove heapsize dependency from msg.
servo/servo pull request #17111
Opened 2017-05-31 14:46 UTC by jdm

This removes a bunch of unnecessary rebuilds when modifying rust-cssparser.

2017-05-31 15:34 UTC, mbrubeck requested changes
Needs a Cargo.lock update, and the commit message should be changed to say "cssparser" instead of "heapsize".  r=mbrubeck with those fixed.

2017-05-31 15:36 UTC, jdm commented
@bors-servo: r=mbrubeck

2017-05-31 15:36 UTC, bors-servo commented
:pushpin: Commit d4d4861 has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck d4d486197d120ecf93f84483a22303c831bb7d0d -->

2017-05-31 15:37 UTC, mbrubeck approved these changes

2017-05-31 22:30 UTC, bors-servo commented
:hourglass: Testing commit d4d486197d120ecf93f84483a22303c831bb7d0d with merge bf45c81a0ce38d707b252f429db4ed57792bec49...

2017-05-31 23:07 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4357)

2017-06-01 00:26 UTC, jdm commented
@bors-servo: retry
* #17109

2017-06-01 01:06 UTC, bors-servo commented
:hourglass: Testing commit d4d486197d120ecf93f84483a22303c831bb7d0d with merge 04d84a26247b04457f21ac017e956b4709556545...

2017-06-01 02:28 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7262), [arm32](http://build.servo.org/builders/arm32/builds/7477), [arm64](http://build.servo.org/builders/arm64/builds/7514), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7602), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4360), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4380), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7586), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/70), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/69), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4288), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4353), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/71), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/72), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2830)
Approved by: mbrubeck
Pushing 04d84a26247b04457f21ac017e956b4709556545 to master...

2017-06-01 02:28 UTC, merged