Implement custom element registry
servo/servo pull request #17112
Opened 2017-05-31 16:15 UTC by cbrewster

Implements https://html.spec.whatwg.org/multipage/#customelementregistry

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-05-31 16:15 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/mod.rs, components/script/dom/customelementregistry.rs, components/script/dom/webidls/CustomElementRegistry.webidl, components/script/dom/window.rs, components/script/dom/webidls/Window.webidl
 * @kichjang: components/script/dom/mod.rs, components/script/dom/customelementregistry.rs, components/script/dom/webidls/CustomElementRegistry.webidl, components/script/dom/window.rs, components/script/dom/webidls/Window.webidl

2017-05-31 16:15 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-05-31 16:16 UTC, cbrewster commented
r? @jdm 

part of #9372

2017-05-31 16:18 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +                // Check that the element interface for extends is not HTMLUnknownElement
I'm not entirely sure the best way to go about this. AFAICT we only determine the _element interface_ here: https://dxr.mozilla.org/servo/rev/779edd7c4aaf900f12fab378a378b0fc52d4c628/components/script/dom/create.rs#129-272.

2017-06-02 08:49 UTC, nox requested changes
First review pass.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +            let c_name = CString::new("prototype").unwrap();
You don't need this here, just use `b"prototype\0"`.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +    fn check_prototype(&self, constructor: HandleObject) -> ErrorResult {
Why make a separate method?

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +                return Err(Error::Type("constructor.protoype is not an object".to_owned()));
Typo: `prototype`.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +    #[allow(unsafe_code, unrooted_must_root)]
Why is `unrooted_must_root` required?

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +            return Err(Error::Type("Second argument of CustomElementRegistry.defin is not a constructor".to_owned()));
Typo: `define`.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +        let local_name = match *extends {
Nit: `if let` would be cleaner.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +        if let Err(error) = result {
Nit: `result?;`

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +                // Check that the element interface for extends is not HTMLUnknownElement
Yeah, you need a similar match expression for this step to be implemented.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +            return Err(Error::Syntax);
Wrong. You should return a rejected `Promise` here.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +    fn WhenDefined(&self, name: DOMString) -> Fallible<Rc<Promise>> {
This method isn't actually fallible.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +        let promise = match map.get(&name).cloned() {
Using `Option::unwrap_or_else` would be cleaner.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +    }
```rust
if !name.chars().next().map_or(false, |c| c >= 'a' && c >= 'z') {
    return false;
}
```

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +        if c != '-' && c != '.' && c != '_' && c != '\u{B7}' &&
Please make a `is_potential_custom_element_char` function and use that here, all the reversed conditions don't help readability.

2017-06-02 08:49 UTC, nox commented on components/script/dom/customelementregistry.rs
> +            has_dash = true;
Nit: you can `continue` here.

2017-06-02 17:06 UTC, cbrewster reviewed
Thanks for the review @nox!

2017-06-02 19:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +            let c_name = CString::new("prototype").unwrap();
Other places use `b"foo\0".as_ptr() as *const _`.

2017-06-02 19:46 UTC, jdm commented on tests/wpt/metadata/custom-elements/CustomElementRegistry.html.ini
>    [customElements.whenDefined must return a rejected promise when the given name is not a valid custom element name]
I suspect this test passes now.

2017-06-02 20:25 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +            let c_name = CString::new("prototype").unwrap();
Ok, will change it to that

2017-06-02 22:19 UTC, jdm requested changes
This is a really readable implementation!

2017-06-02 22:19 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        {
nit: { on the previous line.

2017-06-02 22:19 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +            has_dash = true;
Should we return false if has_dash is already true?

2017-06-02 22:19 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        match self.definitions.borrow_mut().get(&name) {
`borrow()`, right?

2017-06-02 22:19 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +            // Check that the element interface for extends is not HTMLUnknownElement
I don't see any way around it but duplicating the relevant data from create.rs, unfortunately.

2017-06-02 22:23 UTC, jdm commented on tests/wpt/metadata/custom-elements/CustomElementRegistry.html.ini
>    [customElements.define must not throw when defining another custom element in a different global object during Get(constructor, "prototype")]
Can we look into why this test fails?

2017-06-03 03:32 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +        match self.definitions.borrow_mut().get(&name) {
Done.

2017-06-03 03:32 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +            has_dash = true;
The name can have more than one dash, it just needs at a minimum one.

2017-06-03 03:32 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +        {
Done.

2017-06-03 03:32 UTC, cbrewster commented on tests/wpt/metadata/custom-elements/CustomElementRegistry.html.ini
>    [customElements.define must not throw when defining another custom element in a different global object during Get(constructor, "prototype")]
The test relies on `createElement` creating a custom element which isn't implemented yet:
```
assert_true(iframe.contentDocument.createElement('another-custom-element') instanceof InnerCustomElement);
```

2017-06-03 03:32 UTC, cbrewster commented on tests/wpt/metadata/custom-elements/custom-element-registry/define.html.ini
> +  [If constructor is arrow function, should throw a TypeError]
I am not sure how I should check for this, is there anything other than `IsConstructor` that I need to do?

2017-06-03 19:21 UTC, jdm commented on tests/wpt/metadata/custom-elements/custom-element-registry/define.html.ini
> +  [If constructor is arrow function, should throw a TypeError]
I suspect it's a limitation of our old version of Spider monkey. It would be worth seeing if Gecko passes that test.

2017-06-04 04:07 UTC, cbrewster commented on tests/wpt/metadata/custom-elements/custom-element-registry/define.html.ini
> +  [If constructor is arrow function, should throw a TypeError]
Ahh probably, Gecko does pass.

2017-06-05 03:28 UTC, jdm commented
@bors-servo: r+

2017-06-05 03:29 UTC, bors-servo commented
:pushpin: Commit 5bcf748 has been approved by `jdm`

<!-- @bors-servo r=jdm 5bcf748db8240e05d6bd3c6672b9265cc6b1b5b7 -->

2017-06-05 03:42 UTC, bors-servo commented
:hourglass: Testing commit 5bcf748db8240e05d6bd3c6672b9265cc6b1b5b7 with merge fccaefa7aeb82e1a153c1821d410bced425d2f89...

2017-06-05 04:41 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4437)

2017-06-05 12:16 UTC, jdm commented
You should add a Preference annotation to the CustomElementRegistry interface as well.

2017-06-05 15:19 UTC, cbrewster commented
@bors-servo r=jdm

2017-06-05 15:19 UTC, bors-servo commented
:pushpin: Commit 87bf4ca has been approved by `jdm`

<!-- @bors-servo r=jdm 87bf4ca2ef71ccc5ef29a025b4137825cd00369b -->

2017-06-05 15:38 UTC, bors-servo commented
:hourglass: Testing commit 87bf4ca2ef71ccc5ef29a025b4137825cd00369b with merge b584944f1731c71920abf9a03e1f3cd1e790f7c4...

2017-06-05 17:06 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7326), [arm32](http://build.servo.org/builders/arm32/builds/7540), [arm64](http://build.servo.org/builders/arm64/builds/7579), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7668), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4425), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4447), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7651), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/135), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/134), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4354), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4418), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/135), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/137), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2895)
Approved by: jdm
Pushing b584944f1731c71920abf9a03e1f3cd1e790f7c4 to master...

2017-06-05 17:07 UTC, merged