Implemented the plumbing for paint worklets
servo/servo pull request #17150
Opened 2017-06-03 17:26 UTC by asajeffrey

This PR implements the plumbing for paint worklets:

* Adding CSS values for paint worklets.
* Implementing a skeleton for the `PaintWorkletGlobalScope` webidl.
* Implementing an executor for paint worklet tasks, and passing it from script to layout.
* Building the display list items for paint worklet images.

This PR does not implement registering or calling paint worklets in JS.

Before it merges, this PR needs a reftest added for basic paint worklet functionality.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] There are tests for these changes

2017-06-03 17:26 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/values/specified/image.rs, components/style/values/generics/image.rs
 * @kichjang: components/script_layout_interface/message.rs, components/script/dom/webidls/PaintWorkletGlobalScope.webidl, components/script/dom/mod.rs, components/script_traits/Cargo.toml, components/script_traits/Cargo.toml and 10 more
 * @fitzgen: components/script_layout_interface/message.rs, components/script/dom/webidls/PaintWorkletGlobalScope.webidl, components/script/dom/mod.rs, components/script_traits/Cargo.toml, components/script_traits/Cargo.toml and 7 more
 * @emilio: components/layout/display_list_builder.rs, components/style/values/specified/image.rs, components/style/values/generics/image.rs, components/layout/context.rs

2017-06-03 17:26 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify style, layout, net, and script code, but no tests are modified. Please consider adding a test!

2017-06-03 17:26 UTC, asajeffrey commented
cc @jdm @metajack @tschneidereit

2017-06-03 17:58 UTC, emilio commented on components/style/values/specified/image.rs
> +        if let Ok(paint_worklet) = input.try(|i| PaintWorklet::parse(context, i)) {
You're going to remove this path for Gecko, I think.

2017-06-03 17:58 UTC, emilio commented on components/style/values/specified/image.rs
> +        input.try(|i| i.expect_function_matching("paint"))?;
No `input.try` needed here, afaict.

2017-06-03 18:03 UTC, emilio commented on components/script/dom/worklet.rs
> +        receiver.recv_timeout(timeout)?
Heh, glad `recv_timeout` was useful after all!

2017-06-03 18:03 UTC, emilio commented on components/script/dom/paintworkletglobalscope.rs
> +    pub fn draw_a_paint_image(&self,
Probably no need to be `pub`?

2017-06-03 18:03 UTC, emilio commented on components/script/dom/window.rs
> +    pub fn new_paint_worklet(&self) -> Root<Worklet> {
no need for pub here either.

2017-06-03 18:03 UTC, emilio commented on components/layout_thread/lib.rs
> +                self.paint_worklet_executor = Some(executor);
`debug_assert!(self.paint_worklet_executor.is_none())`? This would need to be refactored if/when we fix https://github.com/servo/servo/issues/14885

2017-06-03 18:04 UTC, emilio commented on components/style/values/specified/image.rs
> +        if let Ok(paint_worklet) = input.try(|i| PaintWorklet::parse(context, i)) {
Err, that sounded quite inquisitive, I meant "You're going to need to remove" :)

2017-06-03 19:19 UTC, asajeffrey reviewed
Thanks for the quick review!

2017-06-03 19:19 UTC, asajeffrey commented on components/layout_thread/lib.rs
> +                self.paint_worklet_executor = Some(executor);
Done.

2017-06-03 19:19 UTC, asajeffrey commented on components/script/dom/paintworkletglobalscope.rs
> +    pub fn draw_a_paint_image(&self,
Done.

2017-06-03 19:19 UTC, asajeffrey commented on components/script/dom/window.rs
> +    pub fn new_paint_worklet(&self) -> Root<Worklet> {
Done.

2017-06-03 19:19 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +        receiver.recv_timeout(timeout)?
Indeed!

2017-06-03 19:19 UTC, asajeffrey commented on components/style/values/specified/image.rs
> +        if let Ok(paint_worklet) = input.try(|i| PaintWorklet::parse(context, i)) {
Done.

2017-06-03 19:19 UTC, asajeffrey commented on components/style/values/specified/image.rs
> +        input.try(|i| i.expect_function_matching("paint"))?;
Done.

2017-06-03 19:46 UTC, emilio approved these changes
The CSS and display list building bits look fine to me with the nits, assuming `build_display_list_for_webrender_image` is just moved code.

The dom bits look harmless, but I haven't been following along enough the worklet stuff to consider myself confident enough to stamp it, so better if you get @jdm to do that.

Also, as you've already pointed out, a test would be quite nice :)

2017-06-03 19:46 UTC, emilio commented on components/script/dom/paintworkletglobalscope.rs
> +                              sender: Sender<Result<Image, PaintWorkletError>>)
nit: indentation :)

2017-06-03 19:46 UTC, emilio commented on components/script/dom/worklet.rs
> +            .or_else(|_| ServoUrl::parse("about:blank"))
nit: `unwrap_or_else` instead?

2017-06-03 19:46 UTC, emilio commented on components/style/values/generics/image.rs
> +        dest.write_str(&*self.name)?;
this needs to use `serialize_identifier` to handle escaping properly.

2017-06-03 20:45 UTC, asajeffrey reviewed
Thanks!

2017-06-03 20:45 UTC, asajeffrey commented on components/script/dom/paintworkletglobalscope.rs
> +                              sender: Sender<Result<Image, PaintWorkletError>>)
Done,

2017-06-03 20:45 UTC, asajeffrey commented on components/script/dom/worklet.rs
> +            .or_else(|_| ServoUrl::parse("about:blank"))
Done.

2017-06-03 20:45 UTC, asajeffrey commented on components/style/values/generics/image.rs
> +        dest.write_str(&*self.name)?;
Done.

2017-06-03 20:46 UTC, asajeffrey commented
r? @jdm do you want to have a look at the script/worklet side of things?

2017-06-05 15:22 UTC, jdm requested changes

2017-06-05 15:22 UTC, jdm commented on components/script/dom/paintworkletglobalscope.rs
> +    // A buffer to draw into
Make these ///?

2017-06-05 15:22 UTC, jdm commented on components/script/dom/paintworkletglobalscope.rs
> +            buffer: DOMRefCell::new(Vec::new()),
Default::default()

2017-06-05 15:22 UTC, jdm commented on components/script/dom/paintworkletglobalscope.rs
> +    {
nit: { on the previous line

2017-06-06 16:37 UTC, asajeffrey reviewed
Made changes.

2017-06-06 16:37 UTC, asajeffrey commented on components/script/dom/paintworkletglobalscope.rs
> +    // A buffer to draw into
Fixed.

2017-06-06 16:37 UTC, asajeffrey commented on components/script/dom/paintworkletglobalscope.rs
> +            buffer: DOMRefCell::new(Vec::new()),
Fixed.

2017-06-06 16:37 UTC, asajeffrey commented on components/script/dom/paintworkletglobalscope.rs
> +    {
Fixed, though I prefer the brace-on-its-own-line style when the fn defn ended up being multi-line.

2017-06-06 17:30 UTC, jdm commented
Looks good. Just needs squashing and a test.

2017-06-06 17:30 UTC, jdm commented
And this:
```
cargo build -v

error: failed to parse lock file at: /home/travis/build/servo/servo/Cargo.lock

Caused by:

  package `app_units 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)` is specified as a dependency, but is missing from the package list
```

2017-06-07 18:50 UTC, asajeffrey commented
@bors-servo r=jdm

2017-06-07 18:50 UTC, bors-servo commented
:pushpin: Commit fd17dcd has been approved by `jdm`

<!-- @bors-servo r=jdm fd17dcd60442e71f75010a34c6bcfe1c04aca3e5 -->

2017-06-07 18:57 UTC, bors-servo commented
:hourglass: Testing commit fd17dcd60442e71f75010a34c6bcfe1c04aca3e5 with merge bf46da065db58549a74c489d521f9375f4137637...

2017-06-07 19:49 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7376), [arm32](http://build.servo.org/builders/arm32/builds/7590), [arm64](http://build.servo.org/builders/arm64/builds/7629), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7718), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4474), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4498), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7701), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/185), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/184), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4404), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4468), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/183), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/186), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/2945)
Approved by: jdm
Pushing bf46da065db58549a74c489d521f9375f4137637 to master...

2017-06-07 19:49 UTC, merged