[WIP] WebIDL HTMLConstructor support
servo/servo pull request #17224
Opened 2017-06-08 05:10 UTC by cbrewster

spec: https://html.spec.whatwg.org/multipage/#htmlconstructor

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17194 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-06-08 05:10 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/webidls/HTMLElement.webidl, components/script/dom/webidls/HTMLDataListElement.webidl, components/script/dom/webidls/HTMLBaseElement.webidl, components/script/dom/webidls/HTMLSpanElement.webidl, components/script/dom/bindings/codegen/parser/tests/test_constructor.py and 67 more
 * @kichjang: components/script/dom/webidls/HTMLElement.webidl, components/script/dom/webidls/HTMLDataListElement.webidl, components/script/dom/webidls/HTMLBaseElement.webidl, components/script/dom/webidls/HTMLSpanElement.webidl, components/script/dom/bindings/codegen/parser/tests/test_constructor.py and 67 more

2017-06-08 05:10 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-06-08 05:11 UTC, cbrewster commented
This is getting close to done. I am new to a lot of the jsapi stuff and codegen, so any feedback there would be very helpful!

cc @jdm

2017-06-08 16:04 UTC, cbrewster commented on components/script/dom/bindings/interface.rs
> +            // TODO: Step 5
I'm not quite sure how to do step 5. I think there are two potential options:
1. Get a list of local names from the callee. I am not even sure if this is possible.
2. Get a `ConstructorObject` from the definition's local name and compare it to the `callee`. But we don't generate `GetConstructorObject` for most of the HTML interfaces.

2017-06-09 10:18 UTC, nox commented
Changes to `WebIDL.py` need to be versioned as standalone patch files in the repository. But in your case you don't need to do it, because the upstream parser in mozilla-central already supports `[HTMLConstructor]`. Will do a PR to update ours.

2017-06-09 12:00 UTC, nox commented
https://github.com/servo/servo/pull/17254

2017-06-12 15:39 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17254) made this pull request unmergeable. Please resolve the merge conflicts.

2017-06-12 17:11 UTC, jdm requested changes
Good start!

2017-06-12 17:11 UTC, jdm commented on components/script/dom/bindings/interface.rs
> +pub fn create_html_element(window: &Window, call_args: CallArgs) -> Fallible<Root<HTMLElement>> {
&CallArgs

2017-06-12 17:11 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +    Element(Root<HTMLElement>),
This should be `JS<HTMLElement>`, and the type should be marked `#[must_root]`.

2017-06-12 17:11 UTC, jdm commented on components/script/dom/bindings/interface.rs
> +                ConstructionEntry::Element(ref mut element) => {
No need for mut.

2017-06-12 17:12 UTC, jdm commented
```
failures:

    size_of::size_div

    size_of::size_element

    size_of::size_htmlelement

    size_of::size_span
```

2017-06-12 17:38 UTC, cbrewster commented on components/script/dom/bindings/interface.rs
> +            // TODO: Step 5
We only generate GetConstructorObject for interfaces that are a namespace, callback, or have descendants.
[Configuration.py#L397-L401](https://github.com/servo/servo/blob/85585d93345be93588545c2c7c6766421c12602f/components/script/dom/bindings/codegen/Configuration.py#L397-L401)

2017-06-12 17:38 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +    definitions: DOMRefCell<HashMap<DOMString, Rc<CustomElementDefinition>>>,
The spec<sup>1</sup> says each `Element` has an associated definition. It seems like `Rc` would be the best way to go about that.

1: https://dom.spec.whatwg.org/#concept-element-custom-element-definition

2017-06-12 17:38 UTC, cbrewster commented on components/script/dom/bindings/codegen/CodegenRust.py
>          if self.constructor.isHTMLConstructor():
Will do! Didn't take the time to cleanup the commits yet

2017-06-12 22:44 UTC, jdm commented on components/script/dom/bindings/interface.rs
> +            // TODO: Step 5
Gecko is much more liberal; we can follow their lead: https://dxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py#12826-12828

2017-06-13 07:11 UTC, nox commented on components/script/dom/bindings/interface.rs
> +            // TODO: Step 5
Yeah, not generating `GetConstructorObject` for leaf interfaces was just me trimming a bit of unneeded codegen, but if it's not unneeded anymore, just make it generate the function again.

2017-06-15 19:23 UTC, jdm approved these changes
r=me once the function is moved.

2017-06-15 19:23 UTC, jdm commented on components/script/dom/bindings/utils.rs
> +pub fn get_constructor_object_from_local_name(name: LocalName,
Let's move this to dom/bindings/interfaces.rs.

2017-06-16 03:41 UTC, cbrewster commented
@bors-servo r=jdm

2017-06-16 03:41 UTC, bors-servo commented
:pushpin: Commit e4ff934 has been approved by `jdm`

<!-- @bors-servo r=jdm e4ff934e82ec865dd9bb0626f012ff1464f80c2f -->

2017-06-16 04:47 UTC, bors-servo commented
:hourglass: Testing commit e4ff934e82ec865dd9bb0626f012ff1464f80c2f with merge c58bcc23ea5c4b5f83944e111ce9a2d0ec2b5400...

2017-06-16 05:50 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7515), [arm32](http://build.servo.org/builders/arm32/builds/7731), [arm64](http://build.servo.org/builders/arm64/builds/7770), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7859), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4615), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4640), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7842), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/326), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/325), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4545), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4611), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/321), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/324), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3087)
Approved by: jdm
Pushing c58bcc23ea5c4b5f83944e111ce9a2d0ec2b5400 to master...

2017-06-16 05:51 UTC, merged