Unwrap function before calling IsConstructor
servo/servo pull request #17250
Opened 2017-06-09 05:40 UTC by cbrewster

IsConstructor returns true for all wrappers that are callable. Wrapped
arrow functions are callable and thus IsConstructor will return true
if given one; however, if we unwrap the arrow function, IsConstructor
will return false. The latter is the correct behavior here.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-06-09 05:40 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/customelementregistry.rs
 * @kichjang: components/script/dom/customelementregistry.rs

2017-06-09 05:40 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-06-09 05:41 UTC, cbrewster commented
r? @jdm

2017-06-12 17:13 UTC, jdm requested changes

2017-06-12 17:13 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        rooted!(in(global_scope.get_cx()) let unwrapped_constructor = unsafe { UnwrapObject(constructor.get(), 1) });
We should be storing this unwrapped constructor later, too.

2017-06-12 17:23 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +        rooted!(in(global_scope.get_cx()) let unwrapped_constructor = unsafe { UnwrapObject(constructor.get(), 1) });
Should I be storing the unwrapped constructor in `CustomElementDefinition` instead of `Rc<Function>`? Or do we need to store both?

2017-06-12 21:52 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        rooted!(in(global_scope.get_cx()) let unwrapped_constructor = unsafe { UnwrapObject(constructor.get(), 1) });
That's an interesting question I looked more carefully at Gecko, and they have two different hashmaps. One is keyed on the unwrapped constructor and stores local name values. The other table is keyed on local name values and stores the CustomElementDefinition, which contains the original constructor value. This means that all lookups by the constructor pointer are performed on unwrapped constructors, but the actual value that originated from script is used.

2017-06-13 03:23 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +        rooted!(in(global_scope.get_cx()) let unwrapped_constructor = unsafe { UnwrapObject(constructor.get(), 1) });
Ok, in that case I think this should be ok without storing the unwrapped constructor. If we did go the Gecko route of using two different HashMaps with different keys, that locks us into using `Rc` even more. If we do go that route, that could be saved for a followup.

2017-06-24 05:16 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17381) made this pull request unmergeable. Please resolve the merge conflicts.

2017-08-16 20:50 UTC, jdm commented
@bors-servo: r+

2017-08-16 20:50 UTC, bors-servo commented
:pushpin: Commit d8510ba has been approved by `jdm`

<!-- @bors-servo r=jdm d8510baa29ebff55040ac684c357c65ba0748d64 -->

2017-08-16 22:09 UTC, bors-servo commented
:hourglass: Testing commit d8510baa29ebff55040ac684c357c65ba0748d64 with merge cdd4de9c06024d2b92adb44ed7b74392a0ba0e86...

2017-08-16 23:17 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8352), [arm32](http://build.servo.org/builders/arm32/builds/8578), [arm64](http://build.servo.org/builders/arm64/builds/8611), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8695), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5462), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5499), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8695), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1171), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1174), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5391), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5451), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1173), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1178), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3941)
Approved by: jdm
Pushing cdd4de9c06024d2b92adb44ed7b74392a0ba0e86 to master...

2017-08-16 23:17 UTC, merged