Correctly test CSSStyleRule.style.
servo/servo pull request #17260
Opened 2017-06-09 18:51 UTC by jyc

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] These changes do not require tests

2017-06-09 18:51 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @jdm (or someone else) soon.

2017-06-12 17:25 UTC, jdm requested changes

2017-06-12 17:25 UTC, jdm commented on tests/wpt/web-platform-tests/cssom/CSSStyleRule.html
> +            assert_true(rule.style === style);
Use assert_equals for all of the assert_true(... === ...) in this PR.

2017-06-12 17:25 UTC, jdm commented on tests/wpt/web-platform-tests/cssom/CSSStyleRule.html
> +            assert_true(rule.style === style);
This border subtest seems redundant.

2017-06-12 21:43 UTC, emilio commented
@bors-servo r=emilio,jdm

Thanks for the tests :)

2017-06-12 21:43 UTC, bors-servo commented
:pushpin: Commit 0218c15 has been approved by `emilio,jdm`

<!-- @bors-servo r=emilio,jdm 0218c15ecc7c1a0b6e0d7e9f4c43d7286304117e -->

2017-06-12 21:59 UTC, bors-servo commented
:hourglass: Testing commit 0218c15ecc7c1a0b6e0d7e9f4c43d7286304117e with merge cbb57d9c5bdb31eb03cf650be829b0f37cf36480...

2017-06-12 22:28 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4571)

2017-06-12 22:31 UTC, jyc commented
That's very strange, looks like this is the test that's failing:

```
{"status": "FAIL", "stack": "@http://web-platform.test:8000/cssom/CSSStyleRule.html:67:13\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20\ntest@http://web-platform.test:8000/resources/testharness.js:497:9\n@http://web-platform.test:8000/cssom/CSSStyleRule.html:66:9\n", "subtest": "Existence and type of CSSStyleRule attributes", "action": "test_result", "test": "/cssom/CSSStyleRule.html", "line": 78421, "message": "assert_idl_attribute: property \"selectorText\" not found in prototype chain", "expected": "PASS"}
```

Not sure how it was actually passing before, because `selectorText` is not implemented. Going to ask @Manishearth what to do!

2017-06-12 22:51 UTC, jyc commented
Oh, found out why. @Manishearth commented that there wasn't a test with that name and I replied that that was because I'd changed the name of the test to remove the "writability" part (because the field in question isn't actually supposed to be writable per se). Anyways, the .html.ini file which marks that test as expected to fail had it with the old name, which explains why previously we didn't see an error although the test failed (which makes sense, as Servo doesn't yet implement selectorText--future patch in this series!). Anyways, updating to fix that.

2017-06-22 09:28 UTC, emilio commented
@bors-servo r=jdm,emilio

2017-06-22 09:28 UTC, bors-servo commented
:pushpin: Commit 18dbfce has been approved by `jdm,emilio`

<!-- @bors-servo r=jdm,emilio 18dbfced528bc8464dec9e6cad062bcb1c4a7958 -->

2017-06-22 10:19 UTC, bors-servo commented
:hourglass: Testing commit 18dbfced528bc8464dec9e6cad062bcb1c4a7958 with merge 3e686b7d1e0ebe565765c73a4456ffe0176bdd37...

2017-06-22 11:17 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7628), [arm32](http://build.servo.org/builders/arm32/builds/7847), [arm64](http://build.servo.org/builders/arm64/builds/7883), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7973), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4728), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4760), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7960), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/441), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/438), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4667), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4726), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/438), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/443), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3205)
Approved by: jdm,emilio
Pushing 3e686b7d1e0ebe565765c73a4456ffe0176bdd37 to master...

2017-06-22 11:17 UTC, merged