Make filter property animatable.
servo/servo pull request #17288
Opened 2017-06-13 02:00 UTC by mantaroh

This is a PR for https://bugzilla.mozilla.org/show_bug.cgi?id=1362897

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

There are tests for these changes, a test case will be landed in web-platform-tests in https://bugzilla.mozilla.org/show_bug.cgi?id=1362897

2017-06-13 02:00 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/properties/longhand/effects.mako.rs, components/style/gecko/url.rs, components/style/properties/gecko.mako.rs, components/style/properties/helpers/animated_properties.mako.rs
 * @emilio: components/style/properties/longhand/effects.mako.rs, components/style/gecko/url.rs, components/style/properties/gecko.mako.rs, components/style/properties/helpers/animated_properties.mako.rs

2017-06-13 02:00 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify style code, but no tests are modified. Please consider adding a test!

2017-06-13 02:02 UTC, mantaroh commented
This patche have been reviewed by @birtles, @heycam, @hiikezoe, @BorisChiou

2017-06-13 04:42 UTC, mantaroh commented
Ah,  I removed unnecessary line before sending PR in order to build servo.(Because servo don't need the `use properties::longhands::filter::computed_value::Filter::*;`)
But this modification made unresolved the DropShadow when building the geckolib.

2017-06-13 09:31 UTC, nox commented
> Ah, I removed unnecessary line before sending PR in order to build servo.(Because servo don't need the `use properties::longhands::filter::computed_value::Filter::*;`)
> But this modification made unresolved the DropShadow when building the geckolib.

You have to qualify the variants name by `Filter::` instead of glob-importing all of those enum's variants.

2017-06-13 09:34 UTC, nox commented on components/style/properties/gecko.mako.rs
> +                    filters.push(DropShadow(shadow_val));
AFAICT you could just do:

```rust
filters.push(unsafe {
    (**filter.__bindgen_anon_1.mDropShadow.as_ref()).mArray[0].to_shadow()
});
```

2017-06-14 01:42 UTC, mantaroh commented on components/style/properties/gecko.mako.rs
> +                    filters.push(DropShadow(shadow_val));
Thanks, @nox !

I addressed it, and changed to use `Filter::` in order to qualify the variant name.

2017-06-14 13:33 UTC, nox commented
@bors-servo r=birtles,heycam,hiikezoe,BorisChiou,nox

2017-06-14 13:33 UTC, bors-servo commented
:pushpin: Commit c91f67d has been approved by `birtles,heycam,hiikezoe,BorisChiou,nox`

<!-- @bors-servo r=birtles,heycam,hiikezoe,BorisChiou,nox c91f67d9aec08d6b3e85e01227b24d1c86e870a1 -->

2017-06-14 13:33 UTC, bors-servo commented
:hourglass: Testing commit c91f67d9aec08d6b3e85e01227b24d1c86e870a1 with merge 07f1060e9af285ca712b4e8bb1acf0013068adb5...

2017-06-14 14:25 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/293)

2017-06-14 14:53 UTC, jdm commented
```
  ▶ TIMEOUT [expected PASS] /css-animations-1_dev/html/css-filters-animation-blur.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-brightness.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-combined-001.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-contrast.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected PASS] /css-animations-1_dev/html/css-filters-animation-drop-shadow.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-grayscale.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-hue-rotate.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-invert.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-opacity.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-saturate.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected FAIL] /css-animations-1_dev/html/css-filters-animation-sepia.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1
```

2017-06-14 23:11 UTC, emilio commented
Presumably those tests were broken before, and animations were just not running. The story to stop the compositor to take a screenshot in Servo when animations have finished is not great :(

2017-06-15 03:39 UTC, mantaroh commented
I thought this cause is simply forgetting to remove meta file, but I faced test timeout even if remove meta file. I'm not sure why servo will be TIMEOUT..
If I understand correct, this reftest take a screenshot when load event firing, it looks like servo don't fire the load event..

I tried the `reftest-wait`, however the result is same timeout.

2017-06-15 04:55 UTC, mantaroh commented
Umm,, If remove animation, reftest are success, and it is success when animation has finished. It looks like that unfinished animation caused reftest timeout. 

@emilio , @SimonSapin , @Manishearth 
The reftest with unfinished animation will cause timeout in Servo.
Do you know something about this phenomenon?

2017-06-15 07:28 UTC, mantaroh commented
I want to separate this problem into another issue. I filed the issue #17335, in this PR, I'll skip those tests.

2017-06-16 01:48 UTC, hiikezoe commented
@bors-servo try

2017-06-16 01:48 UTC, bors-servo commented
:hourglass: Trying commit 4da244261557f8c505316bd907ff0d9b2e843e45 with merge 9520af5a61fde0380e90ea85fe927265dd102454...

2017-06-16 03:09 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4612)

2017-06-16 03:18 UTC, mantaroh commented
@bors-servo retry

2017-06-16 03:18 UTC, bors-servo commented
@mantaroh: :key: Insufficient privileges: and not in try users

2017-06-16 03:21 UTC, birtles commented
@bors-servo retry

2017-06-16 03:21 UTC, bors-servo commented
:hourglass: Trying commit 4da244261557f8c505316bd907ff0d9b2e843e45 with merge 3a5a028889f1fda7db01e89b679583e236fe80e4...

2017-06-16 03:23 UTC, birtles commented
Looks like they're still timing out though.

2017-06-16 03:25 UTC, hiikezoe commented
yeah, other tests in tests/wpt/css-tests/filters-1_dev.

2017-06-16 03:32 UTC, jdm requested changes

2017-06-16 03:32 UTC, jdm commented on tests/wpt/metadata-css/css-animations-1_dev/html/css-filters-animation-brightness.htm.ini
> +  disabled: The reftest of servo with non-expired animations failed(issue 17335).
There is no need to disable these tests. We should use `expected: TIMEOUT` instead, and add a separate `bug: https://github.com/servo/servo/issues/17335` as well.

2017-06-16 04:00 UTC, mantaroh commented
Thanks, @hiikezoe , @birtles , @jdm .
I overlooked that I need to change the ini file of filters-1_dev.
I updated init file of tests/wpt/css-tests/filters-1_dev and tests/wpt/css-tests/css-animations-1_dev by using `expected: TIMEOUT`.

2017-06-16 04:57 UTC, birtles commented
@bors-servo retry

2017-06-16 04:58 UTC, birtles commented
@bors-servo p=10

2017-06-16 06:55 UTC, Manishearth commented
@bors-servo r=birtles

2017-06-16 06:55 UTC, bors-servo commented
:pushpin: Commit ac75e0e has been approved by `birtles`

<!-- @bors-servo r=birtles ac75e0ec4788d31eadcb34e03f213bfa14993dd1 -->

2017-06-16 06:56 UTC, birtles commented
@bors-servo r=hiro

2017-06-16 06:56 UTC, bors-servo commented
:bulb: This pull request was already approved, no need to approve it again.

- There's another pull request that is currently being tested, blocking this pull request: #17353

2017-06-16 06:56 UTC, bors-servo commented
:pushpin: Commit ac75e0e has been approved by `hiro`

<!-- @bors-servo r=hiro ac75e0ec4788d31eadcb34e03f213bfa14993dd1 -->

2017-06-16 07:49 UTC, bors-servo commented
:hourglass: Testing commit ac75e0ec4788d31eadcb34e03f213bfa14993dd1 with merge bceae420479e9a15f5ea52f70a0ca0a3edd12f3e...

2017-06-16 08:21 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4643)

2017-06-16 08:21 UTC, birtles commented
@bors-servo retry

2017-06-16 09:31 UTC, bors-servo commented
:hourglass: Testing commit ac75e0ec4788d31eadcb34e03f213bfa14993dd1 with merge 1721fa20603fecfe64ef9da1477181eb27be674c...

2017-06-16 10:32 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4621)

2017-06-16 13:00 UTC, jdm commented
```
  ▶ FAIL [expected TIMEOUT] /css-animations-1_dev/html/css-filters-animation-contrast.htm
  └   → /css-animations-1_dev/html/css-filters-animation-contrast.htm 0f0e0e7166718073fb1271121f89e4aecfbc750d
/css-animations-1_dev/html/reference/css-filters-animation-contrast-ref.htm 7e54b8d874be52ec34436f49bd8b3230e7f70e17
Testing 0f0e0e7166718073fb1271121f89e4aecfbc750d == 7e54b8d874be52ec34436f49bd8b3230e7f70e17

  ▶ PASS [expected TIMEOUT] /filters-1_dev/html/css-filters-animation-drop-shadow.htm
```
Oh good, these animation filter tests give us intermittent results, too!

2017-06-16 13:31 UTC, jdm commented
I have filed issues so that they will be classified as intermittent failures. You can retry this PR without any changes.

2017-06-16 23:53 UTC, birtles commented
@bors-servo retry

2017-06-16 23:53 UTC, bors-servo commented
:hourglass: Testing commit ac75e0ec4788d31eadcb34e03f213bfa14993dd1 with merge 29483eb14a5d03e5de00447edd5149af38ffe0fd...

2017-06-17 00:37 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4635)

2017-06-17 00:41 UTC, birtles commented
Looks like a few more intermittents?

2017-06-18 16:02 UTC, jdm commented
Updated.

2017-06-18 23:42 UTC, birtles commented
@bors-servo retry

2017-06-18 23:42 UTC, bors-servo commented
:hourglass: Testing commit ac75e0ec4788d31eadcb34e03f213bfa14993dd1 with merge 244d8aaa42c5a846fabd5f5ff3c7c59ba80a053c...

2017-06-19 00:26 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4651)

2017-06-19 00:39 UTC, jdm commented
Nevermind. It's clearly going to be a laborious process to keep the tests enabled; just disable them all instead (both the filter animation ones in /css-animations-1_dev/html/ and /filters-1_dev/html/).

2017-06-19 01:17 UTC, mantaroh commented
Thanks @jdm, @birtles 
I updated those tests meta file with the disabled annotation.

2017-06-19 01:25 UTC, birtles commented
I'm not sure if we use exactly the same format for these meta files as we do in Gecko, but if so I guess we just need a `__dir__.ini` that specifies `disabled: https://github.com/servo/servo/issues/17335`
(As per https://developer.mozilla.org/en-US/docs/Mozilla/QA/web-platform-tests#Per-directory_settings)

Also, let's drop the unrelated changes to MANIFEST.json

2017-06-19 01:49 UTC, mantaroh commented
Thanks @birtles 
In those tests directory contain another tests, so I updated the disable annotation's comment, and removed the changes of metadata-css/MANIFEST.json.

2017-06-19 01:51 UTC, birtles commented
@bors-servo delegate+

2017-06-19 01:51 UTC, bors-servo commented
:v: @mantaroh can now approve this pull request

2017-06-19 03:19 UTC, mantaroh commented
@bors-servo retry

2017-06-19 03:28 UTC, mantaroh commented
@bors-servo r=hiro

2017-06-19 03:28 UTC, bors-servo commented
:pushpin: Commit d32948c has been approved by `hiro`

<!-- @bors-servo r=hiro d32948c46abc6e37e1c341801e94873c96154db7 -->

2017-06-19 04:34 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7553), [arm32](http://build.servo.org/builders/arm32/builds/7769), [arm64](http://build.servo.org/builders/arm64/builds/7808), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7896), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4653), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4678), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7879), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/364), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/363), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4583), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4649), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/359), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/362), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3125)
Approved by: hiro
Pushing e41b7d06b473544755902be2c1334a7622c84940 to master...

2017-06-19 04:34 UTC, merged