stylo: make font-weight descriptor in @font-face preserve keyword values
servo/servo pull request #17343
Opened 2017-06-15 19:35 UTC by ferjm

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix https://bugzilla.mozilla.org/show_bug.cgi?id=1355368

2017-06-15 19:35 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/properties/gecko.mako.rs, components/style/properties/properties.mako.rs, components/style/properties/longhand/font.mako.rs, components/style/properties/helpers/animated_properties.mako.rs, components/style/style_adjuster.rs and 1 more
 * @emilio: components/style/properties/gecko.mako.rs, components/style/properties/properties.mako.rs, components/style/properties/longhand/font.mako.rs, components/style/properties/helpers/animated_properties.mako.rs, components/style/style_adjuster.rs and 1 more

2017-06-15 19:35 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify style and gfx code, but no tests are modified. Please consider adding a test!

2017-06-15 19:36 UTC, ferjm commented
r? @upsuper

2017-06-16 09:46 UTC, emilio commented on components/style/properties/helpers/animated_properties.mako.rs
> +    fn get_zero_value(&self) -> Option<Self> { Some(FontWeight {
Please indent this properly, moving `Some` to the next line.

2017-06-16 10:20 UTC, upsuper requested changes

2017-06-16 10:20 UTC, upsuper commented on components/style/gecko/rules.rs
> +            FontWeight::Bolder =>
`border` and `lighter` are invalid values for `font-weight` descriptor in `@font-face` rule.

2017-06-16 10:21 UTC, upsuper commented
What... the other comment is lost?!

2017-06-16 10:21 UTC, upsuper requested changes

2017-06-16 10:21 UTC, upsuper commented on components/style/properties/longhand/font.mako.rs
> +        pub struct T {
I... don't understand. Why do you want to change `font_weight::computed::T`? I don't think we want to change type of computed value of `font-weight` property. What we want to change is the value of `font-weight` descriptor in `@font-face` rule.

I think it is probably better just having a separate type like
```rust
enum FontWeight {
    Weight(font_weight::Weight),
    Normal,
    Bold,
}
```
for `font-weight` descriptor.

2017-06-20 12:27 UTC, upsuper approved these changes
I guess I'm fine with this for now. I'm going to refactor the font-weight to storing integer directly, which should simplify the related code.

2017-06-20 13:46 UTC, emilio commented
@bors-servo r=upsuper

2017-06-20 13:46 UTC, bors-servo commented
:pushpin: Commit 632c557 has been approved by `upsuper`

<!-- @bors-servo r=upsuper 632c5571a9382d77222dc49e14b5f3ad458fbec8 -->

2017-06-20 16:01 UTC, bors-servo commented
:hourglass: Testing commit 632c5571a9382d77222dc49e14b5f3ad458fbec8 with merge af0032f1fd335ee3cc853f7832016149050dbb37...

2017-06-21 03:19 UTC, bors-servo commented
:hourglass: Testing commit 632c5571a9382d77222dc49e14b5f3ad458fbec8 with merge d6f0496d5da7787a7cac44490d3e5105cede26cf...

2017-06-21 04:14 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/411)

2017-06-21 04:25 UTC, upsuper commented
@bors-servo retry

2017-06-21 05:16 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/7600), [arm32](http://build.servo.org/builders/arm32/builds/7818), [arm64](http://build.servo.org/builders/arm64/builds/7855), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7943), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4700), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4728), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7928), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/413), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/409), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4633), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4695), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/407), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3176) are reusable. Rebuilding only [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/411)...

2017-06-21 06:13 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/413)

2017-06-21 15:06 UTC, emilio commented
@bors-servo retry

2017-06-21 17:40 UTC, bors-servo commented
:hourglass: Testing commit 632c5571a9382d77222dc49e14b5f3ad458fbec8 with merge 3e698340ac704921cb7bd98e623c8eaf349dfff4...

2017-06-21 19:10 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7615), [arm32](http://build.servo.org/builders/arm32/builds/7833), [arm64](http://build.servo.org/builders/arm64/builds/7870), [linux-dev](http://build.servo.org/builders/linux-dev/builds/7958), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4715), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4743), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/7943), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/428), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/424), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4648), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4710), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/422), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/427), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3191)
Approved by: upsuper
Pushing 3e698340ac704921cb7bd98e623c8eaf349dfff4 to master...

2017-06-21 19:10 UTC, merged