Implement paint worklet properties
servo/servo pull request #17364
Opened 2017-06-16 17:17 UTC by asajeffrey

This is the final PR to get basic paint worklet support. It adds support for paint worklet properties (https://drafts.css-houdini.org/css-paint-api/#paint-definition-input-properties). When a paint worklet is registered, it specifies a list of CSS properties, and is provided with their computed values when it is invoked.

This is a dependent PR:
* "Implemented paint worklets invoking worklet scripts" is #17239.
* "Implemented paint worklets rendering contexts" is #17326.

There should be tests added for this, hopefully the existing wpt houdini tests.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #16839
- [ ] There are tests for these changes

2017-06-16 17:17 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/script/dom/webidls/PaintWorkletGlobalScope.webidl, components/script/dom/webidls/StylePropertyMapReadOnly.webidl, components/script_layout_interface/lib.rs, components/script/dom/testworkletglobalscope.rs, components/script/dom/mod.rs and 23 more
 * @fitzgen: components/script/dom/webidls/PaintWorkletGlobalScope.webidl, components/script/dom/webidls/StylePropertyMapReadOnly.webidl, components/script_layout_interface/lib.rs, components/script/dom/testworkletglobalscope.rs, components/script/dom/mod.rs and 23 more
 * @emilio: components/layout/display_list_builder.rs, components/layout/context.rs, components/layout/Cargo.toml, components/layout/lib.rs

2017-06-16 17:17 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-06-16 17:17 UTC, asajeffrey commented
cc @metajack @tschneidereit @jdm.

2017-06-16 17:21 UTC, asajeffrey commented
![The simplest Google demo now renders](https://user-images.githubusercontent.com/403333/27237323-5048c3b6-528e-11e7-8725-e62881df32a4.png)

2017-06-22 16:10 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17456) made this pull request unmergeable. Please resolve the merge conflicts.

2017-06-23 00:29 UTC, asajeffrey commented
![out](https://user-images.githubusercontent.com/403333/27461675-0617b6d8-5781-11e7-8b5a-d8b7e5faa334.gif)

2017-06-30 09:23 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17239) made this pull request unmergeable. Please resolve the merge conflicts.

2017-07-03 19:20 UTC, asajeffrey commented
Rebased. This PRs dependencies have all landed, so it's ready for review.

2017-07-06 03:36 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17615) made this pull request unmergeable. Please resolve the merge conflicts.

2017-07-06 15:40 UTC, asajeffrey commented
The wpt css-paint-api tests are now in `/_mozilla/mozilla/css-paint-api`, so we have tests!

r? @jdm

2017-07-11 00:23 UTC, jdm requested changes

2017-07-11 00:23 UTC, jdm commented on components/script/dom/styepropertymapreadonly.rs
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Typoed filename that doesn't belong here.

2017-07-11 00:23 UTC, jdm commented on components/layout/display_list_builder.rs
> +                    .filter_map(|(name, id)| id.as_shorthand().err().map(|id| (name, id)))
Didn't we already filter them when registering?

2017-07-11 18:56 UTC, asajeffrey reviewed
Oops, removed that filetypo!

2017-07-11 18:56 UTC, asajeffrey commented on components/script/dom/styepropertymapreadonly.rs
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Oops.

2017-07-11 18:56 UTC, asajeffrey commented on components/layout/display_list_builder.rs
> +                    .filter_map(|(name, id)| id.as_shorthand().err().map(|id| (name, id)))
Yes, but very annoyingly shorthand property ids have a lifetime, so we can't store them in the properties map.

2017-07-11 19:45 UTC, jdm commented
Looks good to merge after squashing, in that case.

2017-07-11 19:46 UTC, jdm approved these changes

2017-07-11 20:23 UTC, asajeffrey commented
Squashed. @bors-servo: r=jdm

2017-07-11 20:23 UTC, bors-servo commented
:pushpin: Commit 7fbd9c5 has been approved by `jdm`

<!-- @bors-servo r=jdm 7fbd9c56b2d0de9922a2eae38dd02b0cfe65169d -->

2017-07-11 20:40 UTC, bors-servo commented
:hourglass: Testing commit 7fbd9c56b2d0de9922a2eae38dd02b0cfe65169d with merge 0da75a2b379f4fb604e60a8e8690215664d91104...

2017-07-11 21:29 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/659)

2017-07-11 21:50 UTC, jdm commented
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface CSSStyleValue to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:73:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:13:1
```

2017-07-11 22:30 UTC, asajeffrey commented
Made the new interfaces just exposed to Worklet, not Window. @bors-servo r=jdm

2017-07-11 22:30 UTC, bors-servo commented
:pushpin: Commit ef033b8 has been approved by `jdm`

<!-- @bors-servo r=jdm ef033b8362b143f3671863313bcd792c4bf17f45 -->

2017-07-11 22:30 UTC, bors-servo commented
:evergreen_tree: The tree is currently closed for pull requests below priority 9000, this pull request will be tested once the tree is reopened

2017-07-11 23:24 UTC, bors-servo commented
:hourglass: Testing commit ef033b8362b143f3671863313bcd792c4bf17f45 with merge bc44246fc682d9f2362eaca6bba07b45c293eb42...

2017-07-12 00:28 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7845), [arm32](http://build.servo.org/builders/arm32/builds/8067), [arm64](http://build.servo.org/builders/arm64/builds/8101), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8189), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4947), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4980), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8181), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/659), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/657), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4886), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4942), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/658), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/663), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3424)
Approved by: jdm
Pushing bc44246fc682d9f2362eaca6bba07b45c293eb42 to master...

2017-07-12 00:28 UTC, merged