Custom element creation
servo/servo pull request #17381
Opened 2017-06-17 04:46 UTC by cbrewster

This implements the CE-related steps when creating elements. `is` is now support by `document.createElement` and is stored on `Element`s. Only synchronously created autonomous elements are supported as async element creation and customized built-in elements both require custom element upgrade reactions.

Spec: https://dom.spec.whatwg.org/#concept-create-element

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17191 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-06-17 04:46 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/customelementregistry.rs, components/script/dom/servoparser/mod.rs, components/script/dom/document.rs, components/script/dom/element.rs, components/script/dom/create.rs and 3 more
 * @kichjang: components/script/dom/customelementregistry.rs, components/script/dom/servoparser/mod.rs, components/script/dom/document.rs, components/script/dom/element.rs, components/script/dom/create.rs and 3 more

2017-06-17 04:46 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-06-17 04:46 UTC, cbrewster commented
r? @jdm

2017-06-17 04:47 UTC, cbrewster commented on tests/wpt/metadata/custom-elements/reactions/Element.html.ini
> +  expected: CRASH
This test and the other crashing test are caused by #17366

2017-06-20 18:45 UTC, jdm requested changes
I found these changes pretty straightforward to review; nice job.

2017-06-20 18:45 UTC, jdm commented on components/script/dom/create.rs
> +                    // Step 6.1
6.1.1

2017-06-20 18:45 UTC, jdm commented on components/script/dom/create.rs
> +                    // Step 6.2
6.1.2

2017-06-20 18:45 UTC, jdm commented on components/script/dom/create.rs
> +                    let global = document.global();
This should probably be GlobalScope::current() instead.

2017-06-20 18:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +    /// https://dom.spec.whatwg.org/#interface-element Step 6.1
https://dom.spec.whatwg.org/#concept-create-element

2017-06-20 18:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +            let _ac = JSAutoCompartment::new(cx, constructor.to_object());
self.constructor.callback()

2017-06-20 18:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +            Root::from_jsval(cx, element_val.handle(), ()).unwrap()
Instead of unwrapping we should return Error::JSFailed here.

2017-06-20 18:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +
What about step 10?

2017-06-20 18:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        Ok(element)
What about step 11? I don't see it in the next commit either.

2017-06-20 18:45 UTC, jdm commented on tests/wpt/web-platform-tests/custom-elements/Document-createElement.html
> +<script src="./resources/custom-elements-helpers.js"></script>
Use `resources/custom-elements-helpers.js` instead.

2017-06-20 20:13 UTC, cbrewster commented on components/script/dom/create.rs
> +                    // Step 6.1
Done.

2017-06-20 20:13 UTC, cbrewster commented on components/script/dom/create.rs
> +                    // Step 6.2
Done.

2017-06-20 20:13 UTC, cbrewster commented on components/script/dom/create.rs
> +                    let global = document.global();
After that change I got this assertion failure running one of the tests:
<details>

```
  ▶ TIMEOUT [expected OK] /custom-elements/parser/parser-fallsback-to-unknown-element.html
  │
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ assertion failed: !global.is_null() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /Users/connor/Development/servo/servo/components/script/dom/globalscope.rs:577)
  │ stack backtrace:
  │    0:        0x10b9e6664 - backtrace::backtrace::trace<closure>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
  │    1:        0x10b9e15bf - backtrace::capture::Backtrace::new::h08bbd1a61f799546
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
  │    2:        0x106aac6d6 - servo::main::{{closure}}
  │                         at /Users/connor/Development/servo/servo/ports/servo/main.rs:129
  │    3:        0x10c3393a6 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
  │                         at src/libstd/panicking.rs:550
  │    4:        0x107dc3135 - std::panicking::begin_panic<&str>
  │                         at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:511
  │    5:        0x109a28737 - script::dom::globalscope::global_scope_from_global
  │                         at /Users/connor/Development/servo/servo/components/script/dom/globalscope.rs:577
  │    6:        0x109a285cb - script::dom::globalscope::GlobalScope::current::ha8895ac41f143906
  │                         at /Users/connor/Development/servo/servo/components/script/dom/globalscope.rs:551
  │    7:        0x109174cbf - script::dom::create::create_html_element
  │                         at /Users/connor/Development/servo/servo/components/script/dom/create.rs:133
  │    8:        0x10917b5de - script::dom::create::create_element
  │                         at /Users/connor/Development/servo/servo/components/script/dom/create.rs:324
  │    9:        0x1099fad7d - script::dom::element::Element::create::hfb3b8bc9fcafdc2c
  │                         at /Users/connor/Development/servo/servo/components/script/dom/element.rs:210
  │   10:        0x109a913e2 - _$LT$script..dom..servoparser..Sink$u20$as$u20$markup5ever..interface..tree_builder..TreeSink$GT$::create_element::h6ba8e182ae6c3b46
  │                         at /Users/connor/Development/servo/servo/components/script/dom/servoparser/mod.rs:785
  │   11:        0x10840b9a9 - markup5ever::interface::tree_builder::create_element<script::dom::servoparser::Sink>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/markup5ever-0.3.0/interface/tree_builder.rs:86
  │   12:        0x108d44536 - html5ever::tree_builder::actions::{{impl}}::insert_element<script::dom::bindings::js::JS<script::dom::node::Node>,script::dom::servoparser::Sink>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tree_builder/actions.rs:794
  │   13:        0x108d4ea6f - html5ever::tree_builder::actions::{{impl}}::insert_element_for<script::dom::bindings::js::JS<script::dom::node::Node>,script::dom::servoparser::Sink>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tree_builder/actions.rs:826
  │   14:        0x108d33d93 - html5ever::tree_builder::rules::{{impl}}::step<script::dom::bindings::js::JS<script::dom::node::Node>,script::dom::servoparser::Sink>
  │                         at /Users/connor/Development/servo/servo/target/debug/build/html5ever-65d8b6ff1eb7d5d3/out/rules.rs:780
  │   15:        0x108fdb945 - html5ever::tree_builder::{{impl}}::process_to_completion<script::dom::bindings::js::JS<script::dom::node::Node>,script::dom::servoparser::Sink>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tree_builder/mod.rs:311
  │   16:        0x108d072c1 - html5ever::tree_builder::{{impl}}::process_token<script::dom::bindings::js::JS<script::dom::node::Node>,script::dom::servoparser::Sink>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tree_builder/mod.rs:474
  │   17:        0x1096e0a7f - html5ever::tokenizer::{{impl}}::process_token<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servoparser::Sink>>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tokenizer/mod.rs:233
  │   18:        0x1096e308f - html5ever::tokenizer::{{impl}}::emit_current_tag<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servoparser::Sink>>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tokenizer/mod.rs:426
  │   19:        0x1096f14e4 - html5ever::tokenizer::{{impl}}::step<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servoparser::Sink>>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tokenizer/mod.rs:780
  │   20:        0x1096e7ad0 - html5ever::tokenizer::{{impl}}::run<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servoparser::Sink>>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tokenizer/mod.rs:362
  │   21:        0x1096e7d52 - html5ever::tokenizer::{{impl}}::feed<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servoparser::Sink>>
  │                         at /Users/connor/Development/servo/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.18.0/src/tokenizer/mod.rs:220
  │   22:        0x10835dbea - script::dom::servoparser::html::{{impl}}::feed
  │                         at /Users/connor/Development/servo/servo/components/script/dom/servoparser/html.rs:79
  │   23:        0x109a8dc19 - script::dom::servoparser::{{impl}}::feed
  │                         at /Users/connor/Development/servo/servo/components/script/dom/servoparser/mod.rs:505
  │   24:        0x109a8ccf1 - script::dom::servoparser::{{impl}}::do_parse_sync::{{closure}}
  │                         at /Users/connor/Development/servo/servo/components/script/dom/servoparser/mod.rs:395
  │   25:        0x109a8d42b - script::dom::servoparser::{{impl}}::tokenize<closure>
  │                         at /Users/connor/Development/servo/servo/components/script/dom/servoparser/mod.rs:432
  │   26:        0x109a8cb34 - script::dom::servoparser::{{impl}}::do_parse_sync
  │                         at /Users/connor/Development/servo/servo/components/script/dom/servoparser/mod.rs:395
  │   27:        0x109a8c917 - script::dom::servoparser::{{impl}}::parse_sync::{{closure}}
  │                         at /Users/connor/Development/servo/servo/components/script/dom/servoparser/mod.rs:381
  │   28:        0x10943b382 - profile_traits::time::profile<(),closure>
  │                         at /Users/connor/Development/servo/servo/components/profile_traits/time.rs:121
  │   29:        0x109a8c87b - script::dom::servoparser::{{impl}}::parse_sync
  │                         at /Users/connor/Development/servo/servo/components/script/dom/servoparser/mod.rs:378
  │   30:        0x109a8aad7 - script::dom::servoparser::ServoParser::resume_with_pe [...]

2017-06-20 20:13 UTC, cbrewster commented on tests/wpt/web-platform-tests/custom-elements/Document-createElement.html
> +<script src="./resources/custom-elements-helpers.js"></script>
Done.

2017-06-23 16:50 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +
I guess so!

2017-06-23 16:53 UTC, jdm commented on components/script/dom/create.rs
> +                    let global = document.global();
Since GlobalScope::current now returns an option, you should be able to fallback to the given document's global if it's not available.

2017-06-23 20:23 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +
Done.

2017-06-23 20:23 UTC, cbrewster commented on components/script/dom/create.rs
> +                    let global = document.global();
Done.

2017-06-23 20:23 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +
Done.

2017-06-23 21:07 UTC, jdm commented
```
failures:

    size_of::size_div

    size_of::size_element

    size_of::size_htmlelement

    size_of::size_span
```

2017-06-23 21:10 UTC, jdm requested changes
This looks good to me with a single change.

2017-06-23 21:10 UTC, jdm commented on components/script/dom/create.rs
> +                                let _ac = JSAutoCompartment::new(cx, document.reflector().get_jsobject().get());
This should be using the global that was obtained, rather than the document.

2017-06-23 23:20 UTC, cbrewster commented
@bors-servo r=jdm

2017-06-23 23:20 UTC, bors-servo commented
:pushpin: Commit 68cda8a has been approved by `jdm`

<!-- @bors-servo r=jdm 68cda8af3c614e57bf1c3322ee1373a8955f38ec -->

2017-06-24 00:02 UTC, bors-servo commented
:hourglass: Testing commit 68cda8af3c614e57bf1c3322ee1373a8955f38ec with merge cb8ac66890efadb13a5c08bb929ac17388e4bb53...

2017-06-24 00:45 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/492)

2017-06-24 02:41 UTC, cbrewster commented
Hmm, I am unsure how `CustomElementRegistry` is being exposed
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface CustomElementRegistry to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:73:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:13:1
```

2017-06-24 03:02 UTC, jdm commented
I suspect that it's caused by https://github.com/servo/servo/pull/17381/commits/1fea4fd7d037c993c7b0d3ad2d1e33a0f00ac0ba#diff-30a18e04d7e0b66aafdf192e416cad44R2012 . We should be able to avoid it by checking the preference in lookup_custom_element_definition and returning None immediately if it's false.

2017-06-24 03:11 UTC, cbrewster commented
@jdm that was it!

@bors-servo r=jdm

2017-06-24 03:11 UTC, bors-servo commented
:pushpin: Commit 37e8b89 has been approved by `jdm`

<!-- @bors-servo r=jdm 37e8b89377302e9e981e1268eab97e7bbebbfdb6 -->

2017-06-24 04:08 UTC, bors-servo commented
:hourglass: Testing commit 37e8b89377302e9e981e1268eab97e7bbebbfdb6 with merge bc3ec0ce1bc0ea55ac60def8b3e75948c7085162...

2017-06-24 05:14 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7681), [arm32](http://build.servo.org/builders/arm32/builds/7900), [arm64](http://build.servo.org/builders/arm64/builds/7936), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8026), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4780), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4813), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8013), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/493), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/490), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4720), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4777), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/491), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/496), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3258)
Approved by: jdm
Pushing bc3ec0ce1bc0ea55ac60def8b3e75948c7085162 to master...

2017-06-24 05:15 UTC, merged