Treat application/xml like text/xml in ParserContext::process_response
servo/servo pull request #17474
Opened 2017-06-22 16:25 UTC by rigelk

- components/script/dom/servoparser/mod.rs: merged existing xml-related branches into one and added application/xml as a supported type in that branch.
- tests updated to expect the new result

Fixes #15850

2017-06-22 16:26 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2017-06-22 16:26 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/servoparser/mod.rs
 * @kichjang: components/script/dom/servoparser/mod.rs

2017-06-22 18:06 UTC, jdm requested changes

2017-06-22 18:06 UTC, jdm commented on components/script/dom/servoparser/mod.rs
> +            Some(ContentType(Mime(TopLevel::Text, ref sublevel @ _, _)))
This means that we also accept text/xhtml+xml, which is not a MIME type that we want to support.

2017-06-22 19:31 UTC, rigelk commented on components/script/dom/servoparser/mod.rs
> +            Some(ContentType(Mime(TopLevel::Text, ref sublevel @ _, _)))
Indeed! I didn't spot it :/ Changing that right away

2017-06-22 20:37 UTC, jdm requested changes

2017-06-22 20:37 UTC, jdm commented on components/script/dom/servoparser/mod.rs
> +                ((toplevel == &TopLevel::Text) && (sublevel == &SubLevel::Xml))
We should be using || instead of | here.

2017-06-23 02:52 UTC, KiChjang commented on components/script/dom/servoparser/mod.rs
> +            ) => {},
I'm actually not quite fond of using a match guard for this purpose; I'd rather have multiple match arms that matches exactly the TopLevel and SubLevel types.

2017-06-23 03:08 UTC, jdm commented on components/script/dom/servoparser/mod.rs
> +            ) => {},
I'm ok with it in this case. I think it makes sense to have the XML types grouped together in this way.

2017-06-23 03:08 UTC, jdm commented
@bors-servo: r+

2017-06-23 03:08 UTC, bors-servo commented
:pushpin: Commit d5bc204 has been approved by `jdm`

<!-- @bors-servo r=jdm d5bc204710df6d38db0aed504ca975504c73a68f -->

2017-06-23 06:04 UTC, bors-servo commented
:hourglass: Testing commit d5bc204710df6d38db0aed504ca975504c73a68f with merge a62959bda4c66028c75210b726c3451cb7b2bccb...

2017-06-23 06:36 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4786)

2017-06-23 11:47 UTC, rigelk commented
not sure as to how to reproduce/fix the [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4786) test that failed ;

after running repeatedly the `./mach test-wpt tests/wpt/web-platform-tests/dom/nodes --log-raw /tmp/servo && ./mach update-wpt /tmp/servo` command, I noticed the first command yields different results for each run - maybe I'm doing something wrong?

2017-06-30 09:21 UTC, bors-servo commented
:hourglass: Testing commit d5bc204710df6d38db0aed504ca975504c73a68f with merge 5c6bf016a2a0bbee96719bea5be02b5a2e41d8ab...

2017-06-30 09:53 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4869)

2017-07-05 19:58 UTC, jdm commented
@rigelk You aren't doing anything wrong; that suggests that there may be some intermittent test results. Go ahead and submit the result of doing that and we'll see what the build machines think. Sorry for the delay in responding!

2017-07-18 15:52 UTC, bors-servo commented
:hourglass: Testing commit d5bc204710df6d38db0aed504ca975504c73a68f with merge fa54efdb17da7683e8fc0dd5c3de932007651bf2...

2017-07-18 16:23 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5100)

2017-07-21 23:55 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17822) made this pull request unmergeable. Please resolve the merge conflicts.

2017-07-28 06:36 UTC, bors-servo commented
:hourglass: Testing commit d5bc204710df6d38db0aed504ca975504c73a68f with merge 8816bc63114c0487a7e1cc0d50aa42f7250d6fe1...

2017-07-28 07:08 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5240)

2017-07-31 05:26 UTC, bors-servo commented
:hourglass: Testing commit d5bc204710df6d38db0aed504ca975504c73a68f with merge f6b78d2917650f672f840a6556882252996475f4...

2017-07-31 05:44 UTC, KiChjang commented
Did someone issue a command to homu? Why did homu suddenly start building this PR?

2017-07-31 05:51 UTC, KiChjang commented
@bors-servo r-

* Someone pressed the synchronize button

2017-07-31 05:58 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5279)

2017-11-08 22:36 UTC, jdm commented
Closing this PR due to lack of activity.

2017-11-08 22:36 UTC, closed without merging