Don't return window proxy if it has been discarded
servo/servo pull request #17527
Opened 2017-06-27 05:33 UTC by cbrewster

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #17479 (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-06-27 05:33 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/window.rs
 * @kichjang: components/script/dom/window.rs

2017-06-27 05:33 UTC, cbrewster commented
r? @asajeffrey

2017-06-27 15:02 UTC, jdm requested changes
Good find!

2017-06-27 15:02 UTC, jdm commented on tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe-append-to-child-document.html.ini
>      bug: https://github.com/servo/servo/issues/17479
We should be able to remove this whole file now.

2017-06-27 18:12 UTC, asajeffrey reviewed
LGTM, if you address the nitpicking by me and @jdm, you can r=me.

2017-06-27 18:12 UTC, asajeffrey commented on components/script/dom/window.rs
>      pub fn maybe_window_proxy(&self) -> Option<Root<WindowProxy>> {
Bikeshed: rename this to `undiscarded_window_proxy`? There may be some places where the spec will require us to use a window proxy, even if it has been discarded. Might also be worth putting a spec link in to explain what "discarded" means here.

2017-06-27 18:12 UTC, asajeffrey commented on tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe-append-to-child-document.html.ini
>      bug: https://github.com/servo/servo/issues/17479
Yay!

2017-06-28 08:08 UTC, cbrewster commented
@bors-servo r=asajeffrey

2017-06-28 08:08 UTC, bors-servo commented
:pushpin: Commit e194d00 has been approved by `asajeffrey`

<!-- @bors-servo r=asajeffrey e194d00bf94da6c40c4e69349a3fc4447cc87e4a -->

2017-06-28 08:14 UTC, cbrewster commented
woops, forgot to add the comment about what discarded means
@bors-servo r=asajeffrey

2017-06-28 08:14 UTC, bors-servo commented
:pushpin: Commit 79f3237 has been approved by `asajeffrey`

<!-- @bors-servo r=asajeffrey 79f3237692fa5894eccb4cf3615b6da4a49dc3c8 -->

2017-06-28 08:59 UTC, bors-servo commented
:hourglass: Testing commit 79f3237692fa5894eccb4cf3615b6da4a49dc3c8 with merge 51dd0c65cd6799f0dc61eb380fdbd08db60c10bd...

2017-06-28 09:59 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7708), [arm32](http://build.servo.org/builders/arm32/builds/7927), [arm64](http://build.servo.org/builders/arm64/builds/7963), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8053), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4807), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4840), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8040), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/520), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/517), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4747), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4804), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/518), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/523), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3285)
Approved by: asajeffrey
Pushing 51dd0c65cd6799f0dc61eb380fdbd08db60c10bd to master...

2017-06-28 10:00 UTC, merged