Update fetch methods
servo/servo pull request #17521
Opened 2017-06-26 04:25 UTC by KiChjang

Includes updates to main fetch, scheme fetch, HTTP fetch, HTTP-redirect fetch, HTTP-network fetch, HTTP-network-or-cache fetch and CORS preflight fetch.

2017-06-26 04:25 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net_traits/response.rs, components/net_traits/response.rs, components/net/fetch/methods.rs, components/net/websocket_loader.rs, components/net_traits/request.rs and 2 more

2017-06-26 04:25 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2017-06-26 04:38 UTC, jdm commented on components/net/fetch/methods.rs
> -            current_url.scheme() == "file" ||
I am 99% sure this is going to hit the same problem as https://github.com/servo/servo/pull/14515#issuecomment-266173937 .

2017-06-26 04:41 UTC, KiChjang commented on components/net/fetch/methods.rs
> -            current_url.scheme() == "file" ||
How unfortunate. Looks like I'll have to drop those changes then.

2017-06-26 08:00 UTC, KiChjang commented
Huh... looks like this update failed some unit tests, will look into them.

2017-07-02 04:04 UTC, KiChjang commented
@bors-servo try

2017-07-02 04:04 UTC, bors-servo commented
:hourglass: Trying commit 81fa345953399ca5add0b8ee0719ed2ecae2b8bb with merge aaccbcefde944ab4e995b099c4cccb85589188cf...

2017-07-02 04:38 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4894)

2017-07-03 05:04 UTC, KiChjang commented
I found out what's wrong with the tests, and it's because of the redirection code that lives in `network_listener.rs`. Since `http_redirect_fetch` does not check the headers to see whether there is a `Location` header anymore, we will need to create a `location_url` field on `ResponseInit`. I'm currently stuck on that, because `location_url` needs to implement `serde::Serialize` and `serde::Deserialize`, which means `url::ParseError` needs to have those implementations as well, but it is not quite simple implementing those two traits on `url::ParseError`.

2017-07-05 05:00 UTC, KiChjang commented
Ok, instead of storing an `Option<Result<ServoUrl, url::ParseError>>`, I'm replacing the `ParseError` with a `String`.

@bors-servo try

2017-07-05 05:00 UTC, bors-servo commented
:hourglass: Trying commit 65c1409b5e0f0acf6c3b57ed44a1f6830c0d121a with merge dc3171dde971e2c160f211010dcc82af930c1be3...

2017-07-05 06:02 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7784), [arm32](http://build.servo.org/builders/arm32/builds/8004), [arm64](http://build.servo.org/builders/arm64/builds/8040), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8129), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4884), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4917), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8118), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/597), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/594), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4824), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4881), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/595), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/600), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3363)
State: approved= try=True

2017-08-07 20:47 UTC, jdm requested changes
Thanks for doing this work!

2017-08-07 20:47 UTC, jdm commented on components/net/fetch/methods.rs
> +                    if list.iter().any(|s| **s == "*".to_owned()) {
We should be checking if list.len() == 1 and the first element is "*".

2017-08-07 20:47 UTC, jdm commented on components/net/fetch/methods.rs
> +// https://fetch.spec.whatwg.org/#cors-safelisted-method
///

2017-08-07 20:47 UTC, jdm commented on components/net/http_loader.rs
> +    let same_origin = location_url.origin() == request.current_url().origin();
Let's use the correct origin here. We can [create](https://doc.servo.org/servo_url/origin/enum.ImmutableOrigin.html#method.new) an ImmutableOrigin value from the url's origin and compare them.

2017-08-07 20:47 UTC, jdm commented on components/net/http_loader.rs
> +        code == StatusCode::SeeOther) {
I don't think that this change is an improvement. I found it easier to read the code before.

2017-08-07 20:47 UTC, jdm commented on components/net/http_loader.rs
> +        // We basically pretend that the user declined to enter credentials
This comment is incorrect if we don't return response like the old code did.

2017-08-07 20:47 UTC, jdm commented on components/net/http_loader.rs
> +    preflight.origin = request.origin.clone();
Good catch!

2017-08-07 20:47 UTC, jdm commented on components/net/http_loader.rs
> +            header_names.iter().any(|hn| **hn == "*".to_owned())) &&
Can we do `***hn == "*"` instead?

2017-08-07 20:47 UTC, jdm commented on components/net/http_loader.rs
> +            |header| header.name().to_ascii_lowercase() == "authorization" &&
No need for lowercasing; UniCase ignores string case when comparing.

2017-08-07 20:47 UTC, jdm commented on components/net/http_loader.rs
> +                     header_names.iter().all(|hn| *hn != UniCase(header.name().to_owned()))) {
Can we do UniCase(header.name()) instead?

2017-08-08 16:58 UTC, KiChjang commented on components/net/http_loader.rs
> +    let same_origin = location_url.origin() == request.current_url().origin();
That shouldn't be neccessary either. All code paths that come from `RequestInit` should already have an `ImmutableOrigin` set for them.

2017-08-08 17:00 UTC, KiChjang commented on components/net/http_loader.rs
> +        code == StatusCode::SeeOther) {
The improvement here is that the code doesn't panic when it encounters a None on the status field of the actual response.

2017-08-08 18:00 UTC, KiChjang commented
Force-pushed with comments addressed.

2017-08-09 16:11 UTC, jdm approved these changes

2017-08-09 16:12 UTC, jdm commented
@bors-servo: r+

2017-08-09 16:12 UTC, bors-servo commented
:pushpin: Commit 3b3d823 has been approved by `jdm`

<!-- @bors-servo r=jdm 3b3d8237ad7910c41bcbb1d8d87541d9b8a60ada -->

2017-08-09 16:23 UTC, bors-servo commented
:hourglass: Testing commit 3b3d8237ad7910c41bcbb1d8d87541d9b8a60ada with merge 943b9fe823e957952ea68b827f438e44654261e5...

2017-08-09 16:58 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5389)

2017-08-09 17:16 UTC, jdm commented
```
  ▶ TIMEOUT [expected PASS] /_mozilla/css/transition_calc_implicit.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ Unexpected subtest result in /cors/redirect-userinfo.htm:
  │ FAIL [expected PASS] Allow redirect without userinfo (@ is trimmed during URL parsing)
  └   → assert_unreached: Reached unreachable code

  ▶ Unexpected subtest result in /cors/redirect-origin.htm:
  │ FAIL [expected PASS] remote (*) to local (http://web-platform.test:8000), expect to fail
  │   → assert_false: Got response expected false got true
  │ FAIL [expected PASS] remote (http://web-platform.test:8000) to local (http://web-platform.test:8000), expect to fail
  │   → assert_false: Got response expected false got true
  │ 
  │ shouldFail/</client.onreadystatechange<@http://web-platform.test:8000/cors/redirect-origin.htm:162:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1430:20

  ▶ Unexpected subtest result in /cors/redirect-origin.htm:
  │ FAIL [expected PASS] remote (*) to remote (http://web-platform.test:8000), expect origin=http://web-platform.test:8000
  │   → assert_true: Got response expected true got false
  │ FAIL [expected PASS] remote (http://web-platform.test:8000) to remote (http://web-platform.test:8000), expect origin=http://web-platform.test:8000
  │   → assert_true: Got response expected true got false
  │ 
  │ shouldPass/</client.onreadystatechange<@http://web-platform.test:8000/cors/redirect-origin.htm:138:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1430:20

  ▶ Unexpected subtest result in /cors/redirect-origin.htm:
  │ FAIL [expected PASS] remote (*) to remote (*), expect origin=http://web-platform.test:8000
  │   → assert_equals: Origin Header expected (string) "http://web-platform.test:8000" but got (undefined) undefined
  │ FAIL [expected PASS] remote (http://web-platform.test:8000) to remote (*), expect origin=http://web-platform.test:8000
  │   → assert_equals: Origin Header expected (string) "http://web-platform.test:8000" but got (undefined) undefined
  │ 
  │ shouldPass/</client.onreadystatechange<@http://web-platform.test:8000/cors/redirect-origin.htm:140:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1430:20

  ▶ Unexpected subtest result in /cors/redirect-preflight.htm:
  │ FAIL [expected PASS] Should allow redirect 301 after succesful (200) preflight
  │   → assert_equals: Successfull redirect expected 200 but got 0
  │ FAIL [expected PASS] Should allow redirect 302 after succesful (200) preflight
  │   → assert_equals: Successfull redirect expected 200 but got 0
  │ FAIL [expected PASS] Should allow redirect 303 after succesful (200) preflight
  │   → assert_equals: Successfull redirect expected 200 but got 0
  │ FAIL [expected PASS] Should allow redirect 307 after succesful (200) preflight
  │   → assert_equals: Successfull redirect expected 200 but got 0
  │ FAIL [expected PASS] Should allow redirect 308 after succesful (200) preflight
  │   → assert_equals: Successfull redirect expected 200 but got 0
  │ 
  │ redir_after_successfull_preflight/</client.onreadystatechange<@http://web-platform.test:8000/cors/redirect-preflight.htm:39:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1430:20

  ▶ Unexpected subtest result in /fetch/api/cors/cors-filtering.html:
  └ PASS [expected FAIL] CORS filter on Set-Cookie header

  ▶ Unexpected subtest result in /fetch/api/cors/cors-filtering.html:
  │ FAIL [expected PASS] CORS filter on Set-Cookie2 header
  └   → promise_test: Unhandled rejection with value: object "TypeError: Network error occurred"

  ▶ Unexpected subtest result in /fetch/api/cors/cors-filtering.html:
  └ PASS [expected FAIL] CORS filter on Set-Cookie header, header is forbidden

  ▶ Unexpected subtest result in /fetch/api/cors/cors-filtering.html:
  │ FAIL [expected PASS] CORS filter on Set-Cookie2 header, header is forbidden
  └   → promise_test: Unhandled rejection with value: object "TypeError: Network error occurred"

  ▶ Unexpected subtest result in /fetch/api/cors/cors-filtering-worker.html:
  └ PASS [expected FAIL] CORS filter on Set-Cookie header

  ▶ Unexpected subtest result in /fetch/api/cors/cors-filtering-worker.html:
  │ FAIL [expected PASS] CORS filter on Age header, header is exposed
  └   → promise_test: Unhandled rejection with value: object "TypeError: Network error occurred"

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.html:
  └ PASS [expected FAIL] CORS [DELETE], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.html:
  └ PASS [expected FAIL] CORS [PUT], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.html:
  └ PASS [expected FAIL] CORS [PUT] [only safe headers], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.worker.html:
  └ PASS [expected FAIL] CORS [DELETE], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.worker.html:
  └ PASS [expected FAIL] CORS [PUT], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.worker.html:
  └ PASS [expected FAIL] CORS [PUT] [only safe headers], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-redirect.any.html:
  │ FAIL [expected PASS] Redirect 301: cors to same cors
  │   → assert_equals: Origin is correctly set after redirect expected "http://web-platform.test:8000" but got ""
  │ FAIL [expected PASS] Redirect 302: cors to same cors
  │   → assert_equals: Origin is correctly set after redirect expected "http://web-platform.test:8000" but got ""
  │ FAIL [expected PASS] Redirect 303: cors to same cors
  │   → assert_equals: Origin is correctly set after redirect expected "http://web-platform.test:8000" but got ""
  │ FAIL [expected PASS] Redirect 307: cors to same cors
  │   → assert_equals: Origin is correctly set after redirect expected "http://web-platform.test:8000" but got ""
  │ FAIL [expected PASS] Redirect 308: cors to same cors
  │   → assert_equals: Origin is correctly set after redirect expected "http://web-platform.test:8000" but got ""
  │ 
  └ corsRedirect/</</<@http://web-platform.test:8000/fetch/api/cors/cors-redirect.any.js:19:9

  ▶ TIMEOUT [expected OK] /eventsource/eventsource-cross-origin.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ Unexpected subtest result in /eventsource/eventsource-cross-origin.htm:
  │ TIMEOUT [expected PASS] EventSource: cross-origin redirect use
  └   → Test timed out
```

2017-08-17 09:44 UTC, KiChjang commented
@bors-servo try

2017-08-17 09:44 UTC, KiChjang commented
@bors-servo r- try

2017-08-17 09:44 UTC, KiChjang commented
@bors-servo retry

2017-08-17 09:45 UTC, KiChjang commented
@bors-servo r- retry try clean

2017-08-17 09:46 UTC, KiChjang commented
@bors-servo retry clean

2017-08-17 09:47 UTC, KiChjang commented
@bors-servo retry

2017-08-17 09:47 UTC, KiChjang commented
@bors-servo ping

2017-08-17 09:50 UTC, KiChjang commented
@bors-servo try

2017-08-17 09:51 UTC, KiChjang commented
@bors-servo ping

2017-08-17 10:00 UTC, bors-servo commented
:hourglass: Trying commit 339c9ca9e3f477748f088f5c1613b5c9f0dcd349 with merge aa814bc92c04be5117e1462cfdddd0c0c3f58c17...

2017-08-17 10:00 UTC, bors-servo commented
:sleepy: I'm awake I'm awake

2017-08-17 10:00 UTC, bors-servo commented
:sleepy: I'm awake I'm awake

2017-08-17 10:01 UTC, bors-servo commented
:sleepy: I'm awake I'm awake

2017-08-17 10:04 UTC, bors-servo commented
:hourglass: Trying commit 339c9ca9e3f477748f088f5c1613b5c9f0dcd349 with merge 8066d8a17aaba9353a8b9f4716e68560861d9f2e...

2017-08-17 10:38 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5509)

2017-08-17 20:13 UTC, KiChjang commented
@jdm I'm not sure what to make of these test results. Comparing the request's current URL's origin with the location URL's origin is actually *more* correct than using the request's origin for comparison.

2017-08-17 22:39 UTC, jdm commented
More correct in terms of tests that pass? That just suggests to me that our request's origin is not what we expect, which means we should fix it :)

2017-08-18 01:41 UTC, KiChjang commented
```
  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.html:
  └ PASS [expected FAIL] CORS [DELETE], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.html:
  └ PASS [expected FAIL] CORS [PUT], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.html:
  └ PASS [expected FAIL] CORS [PUT] [only safe headers], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.worker.html:
  └ PASS [expected FAIL] CORS [DELETE], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.worker.html:
  └ PASS [expected FAIL] CORS [PUT], server allows

  ▶ Unexpected subtest result in /fetch/api/cors/cors-preflight.any.worker.html:
  └ PASS [expected FAIL] CORS [PUT] [only safe headers], server allows
```

2017-08-18 10:07 UTC, KiChjang commented
Mind if I file the investigation as a follow-up? I'd rather land this first.

2017-08-18 15:54 UTC, jdm commented
Sure. I have a suspicion that we end up using Origin::Client instead of a real origin.

2017-08-18 15:54 UTC, jdm commented
This can r=me with the WIP commit merged into the original related change.

2017-08-18 23:32 UTC, KiChjang commented
@bors-servo r=jdm

2017-08-18 23:32 UTC, bors-servo commented
:pushpin: Commit 268f78e has been approved by `jdm`

<!-- @bors-servo r=jdm 268f78e5c8eb06854b4538116af8904a8517520b -->

2017-08-18 23:33 UTC, bors-servo commented
:hourglass: Testing commit 268f78e5c8eb06854b4538116af8904a8517520b with merge 35f99c371992e5cc4887bd8ee018517e2b119666...

2017-08-18 23:33 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1233)

2017-08-18 23:38 UTC, KiChjang commented
@bors-servo retry
* infra

2017-08-18 23:39 UTC, bors-servo commented
:hourglass: Testing commit 268f78e5c8eb06854b4538116af8904a8517520b with merge 9f64630eaa5731db10b113ce0a2b967dbc4de15a...

2017-08-19 00:58 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8412), [arm32](http://build.servo.org/builders/arm32/builds/8637), [arm64](http://build.servo.org/builders/arm64/builds/8668), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8750), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5519), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5556), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8754), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1228), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1232), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5448), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5509), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1234), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1236), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4001)
Approved by: jdm
Pushing 9f64630eaa5731db10b113ce0a2b967dbc4de15a to master...

2017-08-19 00:58 UTC, merged