Add cli options to write profiler output to InfluxDB
servo/servo pull request #17536
Opened 2017-06-27 23:05 UTC by ferjm

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

This patch adds the command line options and associated code to write the output of running the profiler to an InfluxDB instance, so we can create graphs like [1] https://screenshots.firefox.com/j6sSZrN7pTuPK2kX/localhost with Grafana.

This is part of the work required to record and watch PWM results during CI to catch performance regressions.

[1] https://screenshots.firefox.com/j6sSZrN7pTuPK2kX/localhost

2017-06-27 23:05 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/profile/lib.rs, components/profile/Cargo.toml, components/profile/time.rs

2017-06-30 16:43 UTC, ferjm commented
r? @jdm

2017-06-30 16:50 UTC, jdm requested changes
If it's useful to put the profiler data into a database, then this looks like a fine way to do it.

2017-06-30 16:50 UTC, jdm commented on components/config/opts.rs
> +    ///  - an InfluxDB hostname to store profiling info upon's Servo's termination.
upon

2017-06-30 16:50 UTC, jdm commented on components/profile/time.rs
> +                };
```rust
let user = user.as_ref().unwrap_or("");
let password = password.as_ref().unwrap_or("");
let database = dbname.as_ref().unwrap_or("");
```

2017-06-30 16:50 UTC, jdm commented on components/profile/time.rs
> +                    data.sort_by(|a, b| {
I think you can use `data.sort()` instead.

2017-06-30 16:50 UTC, jdm commented on components/profile/time.rs
> +                            Err(_) => warn!("Could not write measurement to profiler db"),
```rust
if client.write_one(...).is_err() {
    ...
}
```

2017-07-03 08:29 UTC, ferjm commented on components/profile/time.rs
> +                    data.sort_by(|a, b| {
The trait `std::cmp::Ord` is not implemented for `f64`

2017-07-04 14:37 UTC, ferjm commented
r? @jdm

2017-07-06 14:34 UTC, jdm commented
@bors-servo: r+

2017-07-06 14:34 UTC, bors-servo commented
:pushpin: Commit 360f2cc has been approved by `jdm`

<!-- @bors-servo r=jdm 360f2cc4922a21d5e3482a951b7d80b25a8f977c -->

2017-07-06 15:27 UTC, bors-servo commented
:hourglass: Testing commit 360f2cc4922a21d5e3482a951b7d80b25a8f977c with merge 901525c9116ee0945781811c97fd3395db7c5cf9...

2017-07-06 16:28 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7801), [arm32](http://build.servo.org/builders/arm32/builds/8023), [arm64](http://build.servo.org/builders/arm64/builds/8057), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8146), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4903), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4936), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8137), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/615), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/613), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4841), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4898), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/614), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/619), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3380)
Approved by: jdm
Pushing 901525c9116ee0945781811c97fd3395db7c5cf9 to master...

2017-07-06 16:28 UTC, merged