Fix cef to follow new Browser::new() interface
servo/servo pull request #17548
Opened 2017-06-28 17:12 UTC by sadmansk

Changes the call to `Browser::new()` in cef to contain the target_url.

cc @paulrouget 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #17273.

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-06-28 17:12 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-06-30 10:12 UTC, paulrouget requested changes

2017-06-30 10:12 UTC, paulrouget commented on ports/cef/browser.rs
> -
No need to remove this line.

2017-06-30 10:12 UTC, paulrouget commented on ports/cef/browser.rs
> +    };
Could you do something like this:

```rust
    let target_url = url_string
        .and_then(|val| ServoUrl::parse(&val[..]).ok())
        .or(ServoUrl::parse("about:blank").ok())
        .unwrap();
```

2017-07-01 21:06 UTC, KiChjang commented on ports/cef/browser.rs
> +    };
I think `&val[..]` here can be simplified to `&val` as well.

2017-07-01 21:11 UTC, sadmansk commented on ports/cef/browser.rs
> -
sorry, that was an oversight, i'll fix it

2017-07-01 21:17 UTC, sadmansk commented
@paulrouget fixed according to your review comments.

2017-07-03 00:02 UTC, sadmansk commented
so `./mach test-unit` is failing on Travis, but it's passing on my local machine, any idea why that could be the case?

2017-07-03 00:41 UTC, jdm commented
I'm pretty sure the error while linking is caused by travis running out of disk space.

2017-07-03 02:01 UTC, sadmansk commented
Can that error be ignored then? Or is there a fix that I can do?

2017-07-03 02:16 UTC, jdm commented
It can be ignored.

2017-07-03 14:57 UTC, jdm commented
@bors-servo: delegate=paul

2017-07-03 14:57 UTC, bors-servo commented
:v: @paul can now approve this pull request

2017-07-03 17:30 UTC, cbrewster commented
@bors-servo delegate- delegate=paulrouget

2017-07-03 17:30 UTC, bors-servo commented
:v: @paulrouget can now approve this pull request

2017-07-03 17:36 UTC, bors-servo commented
:v: @paulrouget can now approve this pull request

2017-07-04 02:25 UTC, paulrouget commented
@bors-servo r+

2017-07-04 02:25 UTC, bors-servo commented
:pushpin: Commit 185aa20 has been approved by `paulrouget`

<!-- @bors-servo r=paulrouget 185aa20279b0724884b24eb85e449d7c50562af9 -->

2017-07-04 02:25 UTC, paulrouget approved these changes

2017-07-04 02:25 UTC, bors-servo commented
:hourglass: Testing commit 185aa20279b0724884b24eb85e449d7c50562af9 with merge b55b9dc78ef1405ef23af589cd79587f2749743c...

2017-07-04 03:29 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7776), [arm32](http://build.servo.org/builders/arm32/builds/7996), [arm64](http://build.servo.org/builders/arm64/builds/8032), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8121), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4876), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4909), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8110), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/589), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/586), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4816), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4873), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/587), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/592), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3355)
Approved by: paulrouget
Pushing b55b9dc78ef1405ef23af589cd79587f2749743c to master...

2017-07-04 03:29 UTC, merged