Implement the InputEvent
servo/servo pull request #17578
Opened 2017-06-30 20:04 UTC by pyfisch

Add WebIDL, from UI Events working draft.
Implement script type for event.

Note that actually firing InputEvents is not part of this commit.

As part of my effort to improve [keyboard handling](https://groups.google.com/forum/#!topic/mozilla.dev.servo/e6R7eBDjo4M) it is necessary to introduce the InputEvent. While I have a working prototype using the input event this still needs a lot of work  before it can be merged into servo.

cc @jdm

2017-06-30 20:04 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/mod.rs, components/script/dom/inputevent.rs, components/script/dom/webidls/InputEvent.webidl
 * @kichjang: components/script/dom/mod.rs, components/script/dom/inputevent.rs, components/script/dom/webidls/InputEvent.webidl

2017-06-30 20:04 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-06-30 20:08 UTC, jdm requested changes

2017-06-30 20:08 UTC, jdm commented on components/script/dom/inputevent.rs
> +    is_composing: Cell<bool>,
We can remove the DOMRefCell and Cell if we remove new_uninitialized and make new_inherited take the initial values.

2017-06-30 20:17 UTC, pyfisch commented on components/script/dom/inputevent.rs
> +    is_composing: Cell<bool>,
The current definition with DOMRefCell and Cell is similiar to [KeyboardEvent](https://github.com/servo/servo/blob/master/components/script/dom/keyboardevent.rs). Is there a reason they should be different?

2017-06-30 20:51 UTC, jdm commented on components/script/dom/inputevent.rs
> +    is_composing: Cell<bool>,
KeyboardEvent can be created with document.createEvent so it needs to support uninitialized default values. InputEvent cannot: https://dom.spec.whatwg.org/#dom-document-createevent

2017-06-30 21:28 UTC, pyfisch commented
@jdm thanks for explaining. Removed Cell and DOMRefCell.

2017-07-01 00:02 UTC, jdm commented
You will need to add the interface to https://dxr.mozilla.org/servo/source/tests/wpt/mozilla/tests/mozilla/interfaces.html#12 so the test does not fail.

2017-07-01 08:50 UTC, pyfisch commented
Added the interface.

@bors-servo try

2017-07-01 08:50 UTC, bors-servo commented
:hourglass: Trying commit 9b8da61c1ed1d2ce9a44f332334fa10e0d951ccb with merge 72d424beb656b83c5c2ca5c6c5bd038840e6d167...

2017-07-01 09:12 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8091)

2017-07-01 10:49 UTC, pyfisch commented
@bors-servo try

2017-07-01 10:49 UTC, bors-servo commented
:hourglass: Trying commit 3dd1a4eafb14a98f2e169e6b0d3f8ca31dc9b948 with merge f0bb894663ee483bb8730ab6830a5023be0740a5...

2017-07-01 11:19 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4891)

2017-07-01 11:36 UTC, pyfisch commented
@bors-servo try

2017-07-01 11:36 UTC, bors-servo commented
:hourglass: Trying commit 0669b1e2475e43dd07426b93094a2fc4cecb66c1 with merge b3350c740ab7d52e2cb246ebad61ea7ca3845c4b...

2017-07-01 12:06 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4892)

2017-07-01 13:01 UTC, pyfisch commented
Travis had a LLVM panic with:
``` 
   Compiling style v0.0.1 (file:///home/travis/build/servo/servo/components/style)
LLVM ERROR: IO failure on output stream.
error: Could not compile `style`.

To learn more, run the command again with --verbose.

The command "./mach test-unit" exited with 101.
```
I guess this is an intermittent failure but I did not find an issue for it.

The failing wpt test is because `InputEventInit.data` has `""` as default value but according to the test it should be null. I have submitted a PR at w3c/uievents#148.

2017-07-06 14:32 UTC, jdm commented
@bors-servo: r+

2017-07-06 14:32 UTC, bors-servo commented
:pushpin: Commit 0669b1e has been approved by `jdm`

<!-- @bors-servo r=jdm 0669b1e2475e43dd07426b93094a2fc4cecb66c1 -->

2017-07-06 14:37 UTC, pyfisch commented
I have not yet changed the InputEventInit.data default value. The tests will fail again wit the same message.
Thought that my PR to the specification would get some review from the people at w3c and I planned to update this afterwards but I can also change it here.

2017-07-06 14:41 UTC, jdm commented
@bors-servo: r-

2017-07-06 17:41 UTC, pyfisch commented
@jdm Added null. r+?

2017-07-06 17:55 UTC, jdm commented
@bors-servo: r+

2017-07-06 17:55 UTC, bors-servo commented
:pushpin: Commit 1102660 has been approved by `jdm`

<!-- @bors-servo r=jdm 11026600151af2ad51486a7d9ee56b8f1d7391ce -->

2017-07-06 17:55 UTC, bors-servo commented
:hourglass: Testing commit 11026600151af2ad51486a7d9ee56b8f1d7391ce with merge f18782fb0e10e150f44719d9899a62b84ecb7adc...

2017-07-06 18:44 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7802), [arm32](http://build.servo.org/builders/arm32/builds/8024), [arm64](http://build.servo.org/builders/arm64/builds/8058), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8147), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4904), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4937), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8138), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/616), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/614), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4842), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4899), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/615), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/620), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3381)
Approved by: jdm
Pushing f18782fb0e10e150f44719d9899a62b84ecb7adc to master...

2017-07-06 18:45 UTC, merged