Fix incremental layout bugs for absolute and cleared elements
servo/servo pull request #17581
Opened 2017-06-30 21:44 UTC by mbrubeck

Fixes #17307.  There were two underlying bugs:

* Nodes were not marked dirty when their style attribute changed.

* BaseFlow flags set during flow construction could get out of sync with the element's style if repair_style was called.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #17307
- [x] There are tests for these changes

2017-06-30 21:44 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/servo/restyle_damage.rs
 * @kichjang: components/script/dom/element.rs
 * @fitzgen: components/script/dom/element.rs
 * @emilio: components/layout/Cargo.toml, components/style/servo/restyle_damage.rs, components/layout/flow.rs

2017-06-30 21:44 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits include an empty title element (`<title></title>`). Consider adding appropriate metadata.

2017-06-30 21:45 UTC, mbrubeck commented
r? @pcwalton

2017-06-30 21:58 UTC, mbrubeck commented
@bors-servo try

2017-06-30 21:58 UTC, bors-servo commented
:hourglass: Trying commit 3ec643c904dcc417c6ee8093fb4a06eca0818ccf with merge b6fb1aabfdbb69c3234b9cc27c0467b70a3e0190...

2017-06-30 22:10 UTC, emilio requested changes

2017-06-30 22:10 UTC, emilio commented on components/script/dom/element.rs
> +                node.dirty(NodeDamage::NodeStyleDamaged);
This shouldn't be needed. We handle that already here: https://github.com/servo/servo/blob/master/components/script/dom/document.rs#L2418.

2017-06-30 22:30 UTC, pcwalton commented on components/layout/flow.rs
> +        }
How about making this a new incremental reflow flag, along the lines of `RECONSTRUCT_FLOW` or `REFLOW_OUT_OF_FLOW`?

2017-06-30 22:30 UTC, bors-servo commented
:broken_heart: Test failed - [arm32](http://build.servo.org/builders/arm32/builds/7968)

2017-06-30 22:32 UTC, emilio commented
So with this patch:

```diff
diff --git a/components/layout/query.rs b/components/layout/query.rs
index ae7a506124..f1a5747419 100644
--- a/components/layout/query.rs
+++ b/components/layout/query.rs
@@ -824,11 +824,13 @@ fn process_resolved_style_request_internal<'a, N>(requested_node: N,
             iterator.result.map(|r| r.to_css_string()).unwrap_or(String::new())
         },
 
+        /*
         LonghandId::Bottom | LonghandId::Top | LonghandId::Right | LonghandId::Left
         if applies && positioned && style.get_box().display !=
                 display::computed_value::T::none => {
             used_value_for_position_property(layout_el, layout_root, requested_node, longhand_id)
         }
+        */
         LonghandId::Width | LonghandId::Height
         if applies && style.get_box().display !=
                 display::computed_value::T::none => {
```

And printing the computed style:

```
<!DOCTYPE html>
<style>
  #rect {
    position: absolute;
    border: 1px solid red;
    width: 40px;
    height: 40px;
  }
</style>
<div id="rect"></div>
<script>
  var x = 10;
  var tick = function() {
    x += 4;
    var e = document.getElementById("rect");
    e.style.left = x + "px";
    console.log(getComputedStyle(e).left)
    window.requestAnimationFrame(tick);
  }
  requestAnimationFrame(tick);
</script>
```

I see the computed value updated properly, so now the thing is why the flow tree isn't getting properly updated without the `dirty(..)` call.

2017-06-30 23:05 UTC, emilio commented
The demo definitely works with this series but removing the first patch, so it should be dropped IMO.

2017-06-30 23:08 UTC, mbrubeck commented on components/script/dom/element.rs
> +                node.dirty(NodeDamage::NodeStyleDamaged);
Confirmed. I'll drop this change.

2017-06-30 23:24 UTC, mbrubeck commented on components/layout/flow.rs
> +        }
Done. This increases the size of RestyleDamage from `u8` to `u16` and adds a bit more code. Let me know if you think it's worth the slight complexity cost.

2017-06-30 23:34 UTC, mbrubeck commented
@bors-servo try

2017-06-30 23:34 UTC, bors-servo commented
:hourglass: Trying commit a57149a0fc6b6b49ce8f76d88bdefc14d5484a40 with merge 6a87c6ef5fa9bf823a0b3cdbf09773bdcc5f816a...

2017-06-30 23:52 UTC, emilio approved these changes
Comments on my side were addressed, looks good to me assuming @pcwalton is fine with `UPDATE_FLOW_FLAGS`.

2017-06-30 23:52 UTC, emilio commented on components/layout/flow.rs
> +        // to get out of date:
Perhaps note that we don't need to update the `IS_ABSOLUTELY_POSITIONED` flag because we reconstruct on position changes?

2017-06-30 23:52 UTC, emilio commented on components/layout/flow.rs
> +        mut_base(self).update_flags(style);
(And maybe call the function `update_flags_if_needed`?)

2017-07-01 00:09 UTC, mbrubeck commented on components/layout/flow.rs
> +        mut_base(self).update_flags(style);
Done

2017-07-01 00:09 UTC, mbrubeck commented on components/layout/flow.rs
> +        // to get out of date:
Done

2017-07-01 00:10 UTC, mbrubeck commented
Removed the new RestyleDamage flag; we can just use `REFLOW_OUT_OF_FLOW` as @pcwalton suggested on IRC.

2017-07-01 00:32 UTC, pcwalton commented
Looks good. r=me if you like

2017-07-01 01:02 UTC, mbrubeck commented
@bors-servo r=pcwalton

2017-07-01 01:02 UTC, bors-servo commented
:pushpin: Commit 3981884 has been approved by `pcwalton`

<!-- @bors-servo r=pcwalton 3981884a40f3a567c396acd70cd1831f01c08ae0 -->

2017-07-01 02:06 UTC, bors-servo commented
:hourglass: Testing commit 3981884a40f3a567c396acd70cd1831f01c08ae0 with merge 496eb4c80a1ac07d3c19cc3beb3fbc7f3e5b6a83...

2017-07-01 02:43 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/563)

2017-07-01 05:15 UTC, mbrubeck commented
@bors-servo r=pcwalton

* Updated test metadata

2017-07-01 05:15 UTC, bors-servo commented
:pushpin: Commit 2aef2af has been approved by `pcwalton`

<!-- @bors-servo r=pcwalton 2aef2af9b839873a6961b3a3815776505f31cfe7 -->

2017-07-01 05:15 UTC, bors-servo commented
:hourglass: Testing commit 2aef2af9b839873a6961b3a3815776505f31cfe7 with merge ece35f9caa7c6882adf2927ca7d7ce2bc7d8cef8...

2017-07-01 06:17 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7754), [arm32](http://build.servo.org/builders/arm32/builds/7974), [arm64](http://build.servo.org/builders/arm64/builds/8010), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8099), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4854), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4887), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8088), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/567), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/564), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4794), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4851), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/565), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/570), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3333)
Approved by: pcwalton
Pushing ece35f9caa7c6882adf2927ca7d7ce2bc7d8cef8 to master...

2017-07-01 06:17 UTC, merged