WebVR 1.1 spec compatibility
servo/servo pull request #17608
Opened 2017-07-05 18:16 UTC by MortimerGoro

Servo WebVR implementation started when WebVR spec 1.2 was about to be released. 1.2 API included some minor breaking changes from spec 1.1 in order to improve the support of the API in WebWorkers.

But eventually the WebVR  committee decided not to release 1.2 and make it a major version number whith a lot more changes. WebVR API 2.0 is still under heavy churn.

This PR removes the WebVR changes that non-released 1.2 version introduced to support full WebVR 1.1 spec.

I pushed some GC fixes in a separate commit. See https://github.com/servo/servo/issues/17076 and https://github.com/servo/rust-mozjs/issues/351

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-07-05 18:16 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/vrdisplayevent.rs, components/script/dom/webidls/EventHandler.webidl, components/script/dom/navigator.rs, components/script/dom/macros.rs, components/script/dom/vrframedata.rs and 10 more
 * @kichjang: components/script/dom/vrdisplayevent.rs, components/script/dom/webidls/EventHandler.webidl, components/script/dom/navigator.rs, components/script/dom/macros.rs, components/script/dom/vrframedata.rs and 10 more

2017-07-05 18:16 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-07-05 18:31 UTC, KiChjang commented
Is there a link to the specs you mentioned?

2017-07-05 18:41 UTC, MortimerGoro commented
The link is not available anymore: https://github.com/w3c/webvr/pulls?q=is%3Aopen+is%3Apr+milestone%3A1.2

The changes were:
- Use navigator.vr.getDisplays instead of navigator.getVRDisplays()
- Use addEventListeners from VRDisplay objects instead of window.addEventListener

2017-07-05 18:48 UTC, jdm requested changes

2017-07-05 18:48 UTC, jdm commented on components/script/dom/vr.rs
> +        event.upcast::<Event>().fire(self.global().as_window().upcast::<EventTarget>());
It should be possible to do `self.global().upcast::<EventTarget>()`.

2017-07-05 18:48 UTC, jdm commented on components/script/dom/vrdisplay.rs
> +        event.upcast::<Event>().fire(self.global().as_window().upcast::<EventTarget>());
`self.global().upcast::`.

2017-07-05 18:48 UTC, jdm commented on components/script/dom/webidls/VR.webidl
>  interface VR: EventTarget {
Let's remove the parent interface, as well as from the source implementation.

2017-07-06 14:25 UTC, jdm commented
@bors-servo: r+

2017-07-06 14:25 UTC, bors-servo commented
:pushpin: Commit e936eac has been approved by `jdm`

<!-- @bors-servo r=jdm e936eac831e4dd3abefc940903480d8594f31419 -->

2017-07-06 14:25 UTC, bors-servo commented
:hourglass: Testing commit e936eac831e4dd3abefc940903480d8594f31419 with merge ddd3a15b50213931ad7c90312112275ae958d4a0...

2017-07-06 15:27 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7800), [arm32](http://build.servo.org/builders/arm32/builds/8022), [arm64](http://build.servo.org/builders/arm64/builds/8056), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8145), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4902), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4935), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8136), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/614), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/612), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4840), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4897), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/613), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/618), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3379)
Approved by: jdm
Pushing ddd3a15b50213931ad7c90312112275ae958d4a0 to master...

2017-07-06 15:28 UTC, merged