Don't delete webrender image keys immediately.
servo/servo pull request #17606
Opened 2017-07-05 15:50 UTC by asajeffrey

We currently delete webrender image id's immediately on resizing a canvas, which can cause panics. This PR delays deleting the image id until an epoch has passed.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17534
- [X] These changes do not require tests because the intermittent failure is already triggered by the css-paint-api tests.

2017-07-05 15:50 UTC, asajeffrey commented
r? @glennw

2017-07-10 13:48 UTC, jdm commented
@asajeffrey Could you do the same for the webgl thread as well? https://github.com/servo/servo/issues/13035#issuecomment-313937156 suggests that it is needed there too.

2017-07-10 13:56 UTC, MortimerGoro requested changes

2017-07-10 13:59 UTC, MortimerGoro commented
@jdm I'm working on a major WebGL refactor. See https://github.com/servo/webrender/issues/1353 and https://github.com/servo/webrender/issues/607. 

I'll submit a PR soon. Will be better to wait for that because WebGL thread and WR code are going to be changed (to use WR external image API)

2017-07-11 19:02 UTC, asajeffrey commented on components/canvas/canvas_paint_thread.rs
> +        if let Some(image_key) = self.old_image_key.take() {
Oops. Fixed.

2017-07-11 19:03 UTC, asajeffrey commented
OK, we can hold off if the WebGL refactor will land soon. This bug is causing some intermittents, so it would be nice to merge it.

2017-07-13 06:03 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17694) made this pull request unmergeable. Please resolve the merge conflicts.

2017-07-17 16:57 UTC, asajeffrey commented
@glennw @MortimerGoro I rebased against #17694, can this land now, or should we continue to hold off?

2017-07-17 18:51 UTC, MortimerGoro commented
@asajeffrey yes, this can land now

2017-07-17 19:25 UTC, asajeffrey commented
@jdm, do the changes for WebGL look good to you?

2017-07-17 19:57 UTC, jdm approved these changes

2017-07-17 19:57 UTC, jdm commented on components/canvas/webgl_paint_thread.rs
> +        // An old webrender image key that can be deleted when the current epoch ends.
Use /// on these.

2017-07-17 20:25 UTC, asajeffrey commented on components/canvas/webgl_paint_thread.rs
> +        // An old webrender image key that can be deleted when the current epoch ends.
Done.

2017-07-17 20:25 UTC, asajeffrey commented
@bors-servo r=jdm

2017-07-17 20:25 UTC, bors-servo commented
:pushpin: Commit 3002c45 has been approved by `jdm`

<!-- @bors-servo r=jdm 3002c45184bfe9b5af907b44478aeb13d9ad1933 -->

2017-07-17 20:25 UTC, bors-servo commented
:hourglass: Testing commit 3002c45184bfe9b5af907b44478aeb13d9ad1933 with merge 7f1278a3297d6d41b7dcf750ef7fb6eabb8a92e5...

2017-07-17 21:25 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7946), [arm32](http://build.servo.org/builders/arm32/builds/8168), [arm64](http://build.servo.org/builders/arm64/builds/8202), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8288), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5049), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5082), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8282), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/760), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/758), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4985), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5043), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/761), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/766), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3526)
Approved by: jdm
Pushing 7f1278a3297d6d41b7dcf750ef7fb6eabb8a92e5 to master...

2017-07-17 21:26 UTC, merged