[WIP] Implement custom element reactions
servo/servo pull request #17614
Opened 2017-07-05 22:18 UTC by cbrewster

Initial work for implementing custom element reactions: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-reactions

`[CEReactions]` is functional, it just needs to be added to the various WebIDL files.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17433 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-07-05 22:18 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/customelementregistry.rs, components/script/dom/webidls/CustomElementRegistry.webidl, components/script/dom/element.rs, components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/create.rs and 5 more
 * @kichjang: components/script/dom/customelementregistry.rs, components/script/dom/webidls/CustomElementRegistry.webidl, components/script/dom/element.rs, components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/create.rs and 5 more

2017-07-05 22:18 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-07-06 02:26 UTC, jdm commented
```
failures:

    size_of::size_div

    size_of::size_element

    size_of::size_htmlelement

    size_of::size_span
```

2017-07-07 21:20 UTC, cbrewster commented
Ready for review. r? @jdm 

I am going to submit the changes for `[CEReactions]` as a separate PR since it would add quite a lot of noise here. This means that all reactions are triggered via the backup element queue through a microtask. This is why many reaction-related tests are failing, they should be passing after `[CEReactions]` is implemented.

2017-07-11 11:40 UTC, nox commented
The unit tests are still failing.

2017-07-12 00:30 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17364) made this pull request unmergeable. Please resolve the merge conflicts.

2017-07-12 16:24 UTC, jdm requested changes

2017-07-12 16:24 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +                    args.push(Heap::default());
`let mut args = vec![Heap::default(), Heap::default(), Heap::default(), Heap::default()];`

2017-07-12 16:24 UTC, jdm commented on components/script/dom/element.rs
> +    custom_element_definition: DOMRefCell<Option<Rc<CustomElementDefinition>>>,
Add links to appropriate specification concepts?

2017-07-12 16:24 UTC, jdm commented on components/script/dom/element.rs
> +            custom_element_definition: DOMRefCell::new(None),
Default::default() works here.

2017-07-12 16:24 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +            element.invoke_reactions()
Can these reactions end up appending an element to this queue?

2017-07-12 16:24 UTC, jdm commented on components/script/dom/element.rs
> +            reaction.invoke(Root::from_ref(self));
Can these reactions end up appending reactions to the queue?

2017-07-12 16:24 UTC, jdm commented on components/script/dom/node.rs
> +            if let Some(element) = node.downcast::<Element>() {
Add a link to https://dom.spec.whatwg.org/#concept-node-remove step 14 here.

2017-07-12 16:24 UTC, jdm commented on components/script/dom/node.rs
> +                    if element.get_custom_element_definition().is_some() {
We may want to write a `Node::as_custom_element` helper which combines the downcast and custom check into one.

2017-07-12 16:24 UTC, jdm commented on tests/wpt/metadata/custom-elements/reaction-timing.html.ini
> +  expected: CRASH
?

2017-07-13 15:09 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +            element.invoke_reactions()
I do not believe so, there are two queues an element can be added to:
1. The current element queue.
2. The backup element queue.

For the first case, the current element queue is popped from the custom element reaction stack thus it is no longer the current element queue which means no element will be added to it.

The second case is the backup element queue has the `processing_backup_element_queue` flag which prevents elements being enqueued until the flag is set to `NotProcessing`.

2017-07-13 16:43 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +                    args.get_mut(3).unwrap().set(namespace_value.get());
Done.

2017-07-13 16:43 UTC, cbrewster commented on components/script/dom/element.rs
> +            custom_element_definition: DOMRefCell::new(None),
Done.

2017-07-13 16:43 UTC, cbrewster commented on components/script/dom/element.rs
> +    custom_element_definition: DOMRefCell<Option<Rc<CustomElementDefinition>>>,
Done.

2017-07-13 16:43 UTC, cbrewster commented on components/script/dom/element.rs
> +            reaction.invoke(Root::from_ref(self));
See other comment

2017-07-13 16:43 UTC, cbrewster commented on components/script/dom/node.rs
> +                    if element.get_custom_element_definition().is_some() {
Done.

2017-07-13 16:52 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +            element.invoke_reactions()
Oh actually in the second case, an element can be appended to the backup element queue is being invoked. The flag check occurs after the element is appended to the queue. This is what causes the crash in the test expectations.

I want to change it so the queue is not borrowed for the duration of the loop. Instead if element are popped and processed, new element can be appended to the queue. But I always run into unrooted must root errors. any ideas?

```
while let Some(element) = self.queue.borrow_mut().pop_front().map(|e| Root::from_ref(&*e)) {
    element.invoke_reactions()
}
```

2017-07-17 21:02 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +            element.invoke_reactions()
Avoiding the closure appears to appease the lint
```
self.queue.borrow_mut().pop_front().as_ref().map(JS::deref).map(Root::from_ref)
```

2017-07-17 23:24 UTC, jdm approved these changes

2017-07-17 23:24 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        self.queue.borrow_mut().clear();
This shouldn't be necessary since we now pop, right?

2017-07-17 23:25 UTC, jdm commented
Looks like the sizeof unit tests are failing again, too.

2017-07-18 04:24 UTC, cbrewster commented
@bors-servo r=jdm

2017-07-18 04:24 UTC, bors-servo commented
:pushpin: Commit 9b587a4 has been approved by `jdm`

<!-- @bors-servo r=jdm 9b587a4f2d1d8abc70fa6d6220ac31e6dac32c72 -->

2017-07-18 05:58 UTC, bors-servo commented
:hourglass: Testing commit 9b587a4f2d1d8abc70fa6d6220ac31e6dac32c72 with merge 7b134440fc736450cc87470a78e94f80b9161679...

2017-07-18 07:03 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7957), [arm32](http://build.servo.org/builders/arm32/builds/8180), [arm64](http://build.servo.org/builders/arm64/builds/8213), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8299), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5060), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5093), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8294), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/771), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/770), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4996), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5054), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/772), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/777), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3538)
Approved by: jdm
Pushing 7b134440fc736450cc87470a78e94f80b9161679 to master...

2017-07-18 07:04 UTC, merged