Move Ctrl-F12 keybindings outside of libservo
servo/servo pull request #17652
Opened 2017-07-10 21:41 UTC by Tremoneck

Creates a new WindowEvent called ToggleProfiller, when this Event is queued the profiler is toggled. 
When Crtl + F12 are pressed the Event is queued.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17647 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-07-10 21:41 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @asajeffrey (or someone else) soon.

2017-07-11 01:58 UTC, paulrouget commented on components/compositing/windowing.rs
> +    //Toggles the profiler on and off
Use 3 slashes + space: `//` -> `/// `

2017-07-11 02:00 UTC, paulrouget commented on components/compositing/compositor.rs
> +            WindowEvent::ToggleProfiler => {
Can you rename this to ToggleWebRenderProfiler? Because their is also a regular profiler.

2017-07-11 02:02 UTC, paulrouget requested changes
Maybe use a better commit message: "Move WR profiler keybindings to /ports/"

2017-07-11 02:11 UTC, paulrouget commented on ports/glutin/window.rs
> +            (CMD_OR_CONTROL, None, Key::F12) => {
Use just "CONTROL" here, not "CMD_OR_CONTROL".

2017-07-11 02:19 UTC, paulrouget commented
Also:

I realize this is probably not necessary anymore: 

https://github.com/servo/servo/blob/2475039e40ec898e377c433836edafa5637d63ae/components/servo/lib.rs#L247 and https://github.com/servo/servo/blob/2475039e40ec898e377c433836edafa5637d63ae/components/compositing/compositor.rs#L1642 - remote these functions.

… and when you catch `WindowEvent::ToggleProfiler`, after calling `self.webrender.set_profiler_enabled`, you want to refresh WR, so add this: `self.webrender_api.generate_frame(None);`

2017-07-11 02:44 UTC, emilio commented
@bors-servo delegate=paulroget

2017-07-11 02:44 UTC, bors-servo commented
:v: @paulroget can now approve this pull request

2017-07-11 02:45 UTC, emilio commented
@bors-servo delegate=paulrouget 

 * Someday I'll learn to write

2017-07-11 02:45 UTC, bors-servo commented
:v: @paulrouget can now approve this pull request

2017-07-11 05:38 UTC, Tremoneck commented on components/compositing/windowing.rs
> +    //Toggles the profiler on and off
Is there a use for just `//`, if not maybe this schould be added to `test-tidy`

2017-07-11 05:43 UTC, paulrouget commented on components/compositing/windowing.rs
> +    //Toggles the profiler on and off
Yes. double slashes are for regular comments. triple are for documentation.

2017-07-11 05:55 UTC, Tremoneck commented on components/compositing/windowing.rs
> +    //Toggles the profiler on and off
Ah ok, that makes sense

2017-07-11 07:06 UTC, Tremoneck commented
I just run the failing tests `test-unit` myself, and the compiling of style_tests, which fails in travis, works for me. Is here a way to rerun the test?

2017-07-11 07:13 UTC, paulrouget commented
@Tremoneck that's just a travis issue.

The retry will happen once you push again (or explicitly ask for a retry).

Your changes look good. Once you address https://github.com/servo/servo/pull/17652#issuecomment-314303849 it should be fine.

2017-07-11 07:15 UTC, paulrouget commented
@bors-servo: retry

2017-07-11 07:58 UTC, paulrouget approved these changes
@bors-servo r+

This looks good to me. Thank you.

2017-07-11 08:10 UTC, KiChjang commented
@bors-servo r=paulrouget

2017-07-11 08:10 UTC, bors-servo commented
:pushpin: Commit 6309d51 has been approved by `paulrouget`

<!-- @bors-servo r=paulrouget 6309d516bde99b5f1fff5074e12ae64aaa0ff20b -->

2017-07-11 08:17 UTC, bors-servo commented
:hourglass: Testing commit 6309d516bde99b5f1fff5074e12ae64aaa0ff20b with merge ee95bda3bff01d4ca0e1987a0355d01238d60cf6...

2017-07-11 09:12 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7833), [arm32](http://build.servo.org/builders/arm32/builds/8055), [arm64](http://build.servo.org/builders/arm64/builds/8089), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8177), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4935), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4968), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8169), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/647), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/645), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4873), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4930), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/646), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/651), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3412)
Approved by: paulrouget
Pushing ee95bda3bff01d4ca0e1987a0355d01238d60cf6 to master...

2017-07-11 09:13 UTC, merged

2017-07-11 14:47 UTC, paulrouget commented
Thank you @Tremoneck

2017-07-12 09:02 UTC, Tremoneck commented
I enjoyed it and will probably start doing more, when I have more time available