Use boxed slice instead of vec for FuntionTimerCallback
servo/servo pull request #17672
Opened 2017-07-11 20:52 UTC by sadmansk

Added `fn trace()` implementation for `Box<[T]>` type, and change FunctionTimerCallback to store boxed slices for heap values instead of Vector.

---

- [x `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #17611

- [x] These changes do not require tests

2017-07-11 20:52 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/timers.rs, components/script/dom/bindings/trace.rs
 * @kichjang: components/script/timers.rs, components/script/dom/bindings/trace.rs

2017-07-11 20:52 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-07-11 20:56 UTC, jdm requested changes

2017-07-11 20:56 UTC, jdm commented on components/script/dom/bindings/trace.rs
> +unsafe impl<T: JSTraceable> JSTraceable for Box<[T]> {
Does it work if we use `for [T]` instead?

2017-07-11 21:08 UTC, sadmansk commented on components/script/dom/bindings/trace.rs
> +unsafe impl<T: JSTraceable> JSTraceable for Box<[T]> {
It indeed works! Thanks for pointing this out.

2017-07-11 21:51 UTC, jdm commented
@bors-servo: r+
Thanks!

2017-07-11 21:51 UTC, bors-servo commented
:pushpin: Commit fa67899 has been approved by `jdm`

<!-- @bors-servo r=jdm fa678992fff4f32aa71a1e1314c91d8263f0f103 -->

2017-07-12 01:55 UTC, bors-servo commented
:hourglass: Testing commit fa678992fff4f32aa71a1e1314c91d8263f0f103 with merge 749891e48ec6faa14447b299c48887754872e497...

2017-07-12 03:09 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/7848), [arm32](http://build.servo.org/builders/arm32/builds/8070), [arm64](http://build.servo.org/builders/arm64/builds/8104), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8192), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/4950), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/4983), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8184), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/662), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/660), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/4889), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/4945), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/661), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/666), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3427)
Approved by: jdm
Pushing 749891e48ec6faa14447b299c48887754872e497 to master...

2017-07-12 03:10 UTC, merged