Wait for actual paint before setting paint related metrics
servo/servo pull request #17876
Opened 2017-07-26 18:31 UTC by ferjm

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

2017-07-26 18:31 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/constellation.rs
 * @fitzgen: components/script_traits/lib.rs, components/script_traits/lib.rs
 * @kichjang: components/script_traits/lib.rs, components/script_traits/lib.rs

2017-07-26 18:33 UTC, ferjm commented
@jdm this will likely break the existing unit tests, but I'd love to hear your feedback about this approach before fixing them. Thank you!

2017-07-26 18:43 UTC, ferjm commented on components/constellation/constellation.rs
> +                    if let Err(e) = pipeline.layout_chan.send(LayoutControlMsg::PaintedEpoch(*epoch)) {
I am particularly unsure if it is worth introducing all this extra IPC here to get a slightly more accurate metric.

2017-07-28 19:33 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17892) made this pull request unmergeable. Please resolve the merge conflicts.

2017-07-29 14:02 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17908) made this pull request unmergeable. Please resolve the merge conflicts.

2017-08-10 14:01 UTC, ferjm commented
@jdm feedback ping :) Do you think it is worth taking this approach?

2017-08-15 08:29 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #17425) made this pull request unmergeable. Please resolve the merge conflicts.

2017-08-15 22:46 UTC, jdm requested changes
As I describe in my comments, I believe that these changes will reduce the accuracy of our measurements because the measurement occurs in the wrong thread; instead of consistently undershooting, we will now consistently overshoot.

2017-08-15 22:46 UTC, jdm commented on components/compositing/compositor.rs
> +            if let Err(e) = self.constellation_chan.send(msg) {
An effect of this design (collect epochs, send them to constellation, then send info to layout) is that the time recorded for the metric is not when compositing finished - it is when the layout thread finished processing the notification that compositing finished.

2017-08-15 22:46 UTC, jdm commented on components/constellation/constellation.rs
> +                    if let Err(e) = pipeline.layout_chan.send(LayoutControlMsg::PaintedEpoch(*epoch)) {
I agree. I suspect that a more efficient design would require the layout thread sending a notification to the compositor along with the display indicating that it the compositor should record the current time after compositing instead.

2017-08-18 14:25 UTC, ferjm commented
r? @jdm Thank you for the feedback, Josh! I think it looks better this way.

2017-08-21 23:47 UTC, jdm requested changes
This looks much better!

2017-08-21 23:47 UTC, jdm commented on components/compositing/compositor.rs
> +            {
nit: { on the previous line.

2017-08-21 23:47 UTC, jdm commented on components/compositing/compositor.rs
> +                if let Some(pending_epoch) = self.pending_paint_metrics.get(id) {
Why not iterate over just pending metrics tables keys instead of all the pipelines?

2017-08-21 23:47 UTC, jdm commented on components/script_traits/script_msg.rs
> +    /// Requests that the constellation informs the compositor that it needs to record
nit: `inform`

2017-08-22 14:42 UTC, ferjm commented
r? @jdm PR updated. Thanks!

2017-08-22 14:55 UTC, jdm commented
@bors-servo: r+

2017-08-22 14:55 UTC, bors-servo commented
:pushpin: Commit 1b12340 has been approved by `jdm`

<!-- @bors-servo r=jdm 1b123400eb70fa4710f21caab8d716396beacfb0 -->

2017-08-22 15:06 UTC, bors-servo commented
:hourglass: Testing commit 1b123400eb70fa4710f21caab8d716396beacfb0 with merge 43d1f45b73baa6b70e647f32f1637e05604bcc57...

2017-08-22 16:45 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8457), [arm32](http://build.servo.org/builders/arm32/builds/8682), [arm64](http://build.servo.org/builders/arm64/builds/8713), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8794), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5564), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5602), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8798), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1273), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1276), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5491), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5553), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1280), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1280), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4046)
Approved by: jdm
Pushing 43d1f45b73baa6b70e647f32f1637e05604bcc57 to master...

2017-08-22 16:45 UTC, merged