Custom element upgrades
servo/servo pull request #17935
Opened 2017-08-01 18:22 UTC by cbrewster

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-08-01 18:22 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/customelementregistry.rs, components/script/dom/document.rs, components/script/dom/element.rs, components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/create.rs and 4 more
 * @kichjang: components/script/dom/customelementregistry.rs, components/script/dom/document.rs, components/script/dom/element.rs, components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/create.rs and 4 more

2017-08-01 18:22 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-08-01 18:22 UTC, cbrewster commented
r? @jdm

2017-08-09 16:45 UTC, jdm requested changes
Great work! These changes were quite readable and straightforward to review.

2017-08-09 16:45 UTC, jdm commented on components/script/dom/bindings/interface.rs
> +        Some(ConstructionStackEntry::AlreadyConstructedMarker) => return Err(Error::InvalidState),
No need for `return` here.

2017-08-09 16:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        // Step 8
This is 7.2.

2017-08-09 16:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        // Step 7
7.1

2017-08-09 16:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +            // TODO: Throw InvalidStateError
?

2017-08-09 16:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +        // Step 1
Let's move this to Document::lookup_custom_element_definition instead.

2017-08-09 16:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +                (is.is_none() || is.as_ref() == Some(&name))
Don't we need to check `extends` here?

2017-08-09 16:45 UTC, jdm commented on components/script/dom/customelementregistry.rs
> +fn run_upgrade_constructor(constructor: &Rc<Function>, element: &Element) -> ErrorResult {
Add a spec link here.

2017-08-09 16:45 UTC, jdm commented on components/script/dom/element.rs
> +    custom_element_state: Cell<CustomElementState>,
Add a link to https://dom.spec.whatwg.org/#concept-element-custom-element-state .

2017-08-09 16:45 UTC, jdm commented on components/script/dom/element.rs
> +pub enum CustomElementState {
Add a link to https://dom.spec.whatwg.org/#concept-element-custom-element-state .

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/bindings/interface.rs
> +        Some(ConstructionStackEntry::AlreadyConstructedMarker) => return Err(Error::InvalidState),
Done.

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +            // TODO: Throw InvalidStateError
Sorry, this was implemented in a later commit.

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +        // Step 7
Done.

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +        // Step 8
Done.

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +        // Step 1
Done.

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +                (is.is_none() || is.as_ref() == Some(&name))
Oops, yup. Fixed.

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/customelementregistry.rs
> +fn run_upgrade_constructor(constructor: &Rc<Function>, element: &Element) -> ErrorResult {
Done.

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/element.rs
> +    custom_element_state: Cell<CustomElementState>,
Done.

2017-08-09 17:40 UTC, cbrewster commented on components/script/dom/element.rs
> +pub enum CustomElementState {
Done.

2017-08-09 18:20 UTC, jdm commented
@bors-servo: r+

2017-08-09 18:20 UTC, bors-servo commented
:pushpin: Commit 0c2725d has been approved by `jdm`

<!-- @bors-servo r=jdm 0c2725d6269a10552ef01b0d18c731fd290edeb4 -->

2017-08-09 19:10 UTC, bors-servo commented
:hourglass: Testing commit 0c2725d6269a10552ef01b0d18c731fd290edeb4 with merge 866c8e958e05aeb74d6732a8496a34b6f50d887e...

2017-08-09 19:42 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5392)

2017-08-09 19:59 UTC, jdm commented
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/collections.html:
  │ FAIL [expected PASS] test_binding\n    page   43
  │   → assert_true: Should be function HTMLUnknownElement() {
    [native code]
} expected true got false
  │ 
  │ check_collection/<@http://web-platform.test:8000/_mozilla/mozilla/:86:11
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  │ check_collection@http://web-platform.test:8000/_mozilla/mozilla/:71:5
  │ check_tag@http://web-platform.test:8000/_mozilla/mozilla/:95:7
  │ @http://web-platform.test:8000/_mozilla/mozilla/:145:3
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/:69:1

  ▶ Unexpected subtest result in /_mozilla/mozilla/prototypes.html:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: Should be HTMLUnknownElement expected true got false
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/prototypes.html:21:3
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/prototypes.html:10:1
```

2017-08-09 20:37 UTC, cbrewster commented
@bors-servo r=jdm

2017-08-09 20:37 UTC, bors-servo commented
:pushpin: Commit aa9b9c1 has been approved by `jdm`

<!-- @bors-servo r=jdm aa9b9c10f315179df5d9fd6dcbf8a36129092b19 -->

2017-08-09 20:37 UTC, bors-servo commented
:hourglass: Testing commit aa9b9c10f315179df5d9fd6dcbf8a36129092b19 with merge 931e205033bb5a68a1209af020fa73267db5f53a...

2017-08-09 21:16 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5360)

2017-08-09 21:26 UTC, jdm commented
@bors-servo: retry

2017-08-09 22:22 UTC, bors-servo commented
:hourglass: Testing commit aa9b9c10f315179df5d9fd6dcbf8a36129092b19 with merge a087fee4b4daa76c7e1677b0adae512fb6c87d04...

2017-08-09 23:24 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8256), [arm32](http://build.servo.org/builders/arm32/builds/8480), [arm64](http://build.servo.org/builders/arm64/builds/8513), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8598), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5362), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5396), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8596), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1072), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1075), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5296), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5354), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1074), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1078), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3838)
Approved by: jdm
Pushing a087fee4b4daa76c7e1677b0adae512fb6c87d04 to master...

2017-08-09 23:25 UTC, merged