Hyper sync rustls 0.6.1
servo/servo pull request #17938
Opened 2017-08-01 22:31 UTC by SimranGujral

This change removes Hyper-OpenSSL and integrates HyperSyncRustls v 0.6.1 with servo.
It also removes ciphers depending on DHE and SHA1
---

- [X ] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-08-01 22:31 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @pcwalton (or someone else) soon.

2017-08-01 22:31 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @edunham: servo-tidy.toml
 * @kichjang: components/net/Cargo.toml, components/net/lib.rs, components/net/http_loader.rs, components/net/connector.rs

2017-08-01 22:31 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2017-08-01 22:32 UTC, SimranGujral commented
r? @avadacatavra

2017-08-02 00:05 UTC, avadacatavra requested changes

2017-08-02 00:05 UTC, avadacatavra commented on components/net/connector.rs
> +    let client = TlsClient { cfg: tls };
`TlsClient { cfg: Arc::new(tls) }`
Rust automatically returns the last expression of a function: https://rustbyexample.com/fn.html

2017-08-02 00:06 UTC, avadacatavra commented
This also needs to be squashed into one commit -- we can go over that tomorrow

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2017-08-02 23:11 UTC, SimranGujral commented
All changes have been made and are ready for review.

2017-08-03 15:25 UTC, avadacatavra requested changes
The squash is good--I would clean up the commit comments to be more succinct. Currently they restate the same thing multiple times

2017-08-03 15:25 UTC, avadacatavra commented on components/net/connector.rs
> -
nit: put this line back in

2017-08-03 15:25 UTC, avadacatavra commented on components/net/connector.rs
> +    let mut ca = {
`let mut ca = {
let f = fs::File::open(ca_file).expect("cannot open CA file");
io::BufReader::new(f)
}`

2017-08-03 15:25 UTC, avadacatavra commented on components/net/lib.rs
> -
nit: put this line back in

2017-08-03 20:56 UTC, SimranGujral commented
Changes have been made. Ready for review.

2017-08-04 14:10 UTC, jdm commented
`test fetch::test_fetch_with_hsts has been running for over 60 seconds`
That's worrying! I bet that running any HTTPS WPT test will end up timing out.
@bors-servo: try

2017-08-04 14:10 UTC, bors-servo commented
:hourglass: Trying commit ad07861d08320eb1215dec3d84e102281eba57bf with merge 90aac87fd71ee44afe92040c5d89cf2d38bc0074...

2017-08-04 14:16 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/8194)

2017-08-04 15:21 UTC, jdm commented
```
	thread 'fetch::test_fetch_with_hsts' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:22
  11: net_tests::fetch::test_fetch_with_hsts
             at ./fetch.rs:557
  12: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1477
             at /checkout/src/libcore/ops/function.rs:143
             at /checkout/src/libtest/lib.rs:138
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
```
WPT tests worked, so that's good.  The android build appears to break while building `ring`.

2017-08-07 13:57 UTC, avadacatavra commented
@jdm my suspicion is that we'll need to specify android to ring in the build command based on https://github.com/briansmith/ring/blob/master/build.rs#L613

2017-08-07 15:06 UTC, jdm commented
The target is provided automatically since we're invoking Cargo with --target, and the C commands have android-specific include directories appended to them:
```
running "arm-linux-androideabi-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "--sysroot" "/home/servo/android/ndk/current/platforms/android-18/arch-arm" "-I/home/servo/android/ndk/current/sources/android/support/include" "-g" "-march=armv7-a" "-march=armv7-a" "-mfpu=vfpv3-d16" "-mfloat-abi=softfp" "-I" "include" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-fdata-sections" "-ffunction-sections" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-fstack-protector" "-g3" "-D_XOPEN_SOURCE=700" "-D__ANDROID_API__=18" "-c" "-o/home/servo/buildbot/slave/android/build/target/armv7-linux-androideabi/debug/build/ring-a621dfbd7d7ae5c7/out/ecp_nistz256.o" "crypto/ec/ecp_nistz256.c"
```

2017-08-07 15:09 UTC, jdm commented
https://github.com/briansmith/ring/blob/5f8d332ed0f38415ee003712d1bb93647ed34afe/build.rs#L560 is the line that is adding the include directory that contains the standard library headers that clang does not like:
```
In file included from include/GFp/base.h:60:0,
                 from include/GFp/bn.h:126,
                 from crypto/bn/montgomery_inv.c:15:
/home/servo/android/ndk/current/sources/android/support/include/stdint.h:31:2: error: #include_next is a GCC extension
 #include_next <stdint.h>
  ^
thread '<unnamed>' panicked at 'execution failed', /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.11.0/build.rs:658:8
```

2017-08-07 22:01 UTC, SimranGujral commented
The android issue is still in progress, Other issues have been resolved. Ready for review.
r? @avadacatavra

2017-08-07 23:13 UTC, avadacatavra approved these changes

2017-08-08 12:47 UTC, jdm commented
`test fetch::test_fetch_with_hsts has been running for over 60 seconds`. TravisCI still does not like running that test now.

2017-08-10 21:48 UTC, Manishearth commented
Apparently if we pass `--disable-werror` as a cflag when compiling this should go away.

But I'm not sure, since the warning doesn't actually mention Werror.

2017-08-10 22:01 UTC, jdm commented
@Manishearth What should go away?

2017-08-10 22:02 UTC, Manishearth commented
Oh. The GCC extension warning.

2017-08-18 00:11 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18096) made this pull request unmergeable. Please resolve the merge conflicts.

2017-11-02 10:00 UTC, avadacatavra commented
I'm going to close this until I have more time to bring it up to date :)

2017-11-02 10:00 UTC, closed without merging