Do not merge: Testing a solution to end TreeBuilder's reliance on DOM.
servo/servo pull request #18056
Opened 2017-08-12 11:22 UTC by cynicaldevil

---

Fixed h5e's TreeBuilder so that it does not use `same_tree` and `has_parent_node` methods: https://github.com/cynicaldevil/html5ever/commit/d8c2ea5cb62a1a755bb78b9f5de05d966776883a

2017-08-12 11:23 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/servoparser/mod.rs, components/script/dom/servoparser/async_html.rs
 * @kichjang: components/script/dom/servoparser/mod.rs, components/script/dom/servoparser/async_html.rs

2017-08-12 11:23 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-08-12 11:23 UTC, cynicaldevil commented
cc @nox @jdm

2017-08-12 11:23 UTC, cynicaldevil commented
@bors-servo try

2017-08-12 11:23 UTC, bors-servo commented
:hourglass: Trying commit 0b9b90028e8984b20319a075e3d62744b108d8dd with merge dab8d68dd942eef0c693fc162081b953bbb56da9...

2017-08-12 12:31 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8286), [arm32](http://build.servo.org/builders/arm32/builds/8508), [arm64](http://build.servo.org/builders/arm64/builds/8541), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8627), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5393), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5426), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8624), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1102), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1103), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5326), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5384), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1104), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1108), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3869)
State: approved= try=True

2017-08-17 07:40 UTC, nox requested changes
This looks great!

2017-08-17 07:40 UTC, nox commented on components/script/dom/servoparser/async_html.rs
> +                };
```rust
let tree_node = prev_element.map_or(element, |prev| {
    if self.has_parent_node(element) { element } else { prev }
});
```

No need for `unwrap` or `expect`.

2017-08-17 07:40 UTC, nox commented on components/script/dom/servoparser/async_html.rs
> +        nodes: (&Self::Handle, Option<&Self::Handle>)) {
Nit: block indenting, the arguments list closing paren and opening brace should be on their own line.

2017-08-17 07:40 UTC, nox commented on components/script/dom/servoparser/mod.rs
> +        child: NodeOrText<JS<Node>>) {
Nit: indentation again.

2017-08-17 07:40 UTC, nox commented on components/script/dom/servoparser/mod.rs
> +        };
Same remark about `unwrap` and `expect`.

2017-08-17 07:40 UTC, nox commented on components/script/dom/servoparser/async_html.rs
> +        child: HtmlNodeOrText<Self::Handle>) {
Nit: indentation here.

2017-08-18 14:44 UTC, nox commented on components/script/dom/servoparser/async_html.rs
> +    fn same_tree(&self, _: &Self::Handle, _: &Self::Handle) -> bool {
Why does this still exist?

2017-08-18 15:34 UTC, jdm commented
@bors-servo: r=nox

2017-08-18 15:34 UTC, bors-servo commented
:pushpin: Commit 2cc7199 has been approved by `nox`

<!-- @bors-servo r=nox 2cc7199f42bfb25055cb3b73a2cf8e25c5e7141c -->

2017-08-18 15:44 UTC, bors-servo commented
:hourglass: Testing commit 2cc7199f42bfb25055cb3b73a2cf8e25c5e7141c with merge 60aad6c390d1ae6d722748571b09b45452bd50e2...

2017-08-18 15:44 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1220)

2017-08-18 16:08 UTC, jdm commented
@bors-servo: retry

2017-08-18 16:34 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/8400), [arm32](http://build.servo.org/builders/arm32/builds/8625), [arm64](http://build.servo.org/builders/arm64/builds/8656), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8739), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5508), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5544), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1217), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1220), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5498), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1224), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3989) are reusable. Rebuilding only [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8741), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5437), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1220)...

2017-08-18 16:36 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1222)

2017-08-18 16:44 UTC, jdm commented
@bors-servo: retry
* git

2017-08-18 16:44 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/8400), [arm32](http://build.servo.org/builders/arm32/builds/8625), [arm64](http://build.servo.org/builders/arm64/builds/8656), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8739), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5508), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5544), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1217), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1220), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5437), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5498), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1224), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3989) are reusable. Rebuilding only [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8743), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1222)...

2017-08-18 16:44 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1223)

2017-08-18 20:32 UTC, cynicaldevil commented
@bors-servo retry

2017-08-18 21:27 UTC, bors-servo commented
:hourglass: Testing commit 2cc7199f42bfb25055cb3b73a2cf8e25c5e7141c with merge 62d0de349debf54c32e865e813eac43fb83df7be...

2017-08-18 22:54 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8408), [arm32](http://build.servo.org/builders/arm32/builds/8634), [arm64](http://build.servo.org/builders/arm64/builds/8665), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8747), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5516), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5553), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8751), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1225), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1229), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5445), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5506), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1231), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1233), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/3998)
Approved by: nox
Pushing 62d0de349debf54c32e865e813eac43fb83df7be to master...

2017-08-18 22:54 UTC, merged