Add CompositionEvent bindings
servo/servo pull request #18093
Opened 2017-08-15 19:51 UTC by pyfisch

Needed for better keyboard input. See also #17578

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-08-15 19:52 UTC, pyfisch commented
@bors-servo try

2017-08-15 19:56 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/mod.rs, components/script/dom/compositionevent.rs, components/script/dom/webidls/CompositionEvent.webidl
 * @kichjang: components/script/dom/mod.rs, components/script/dom/compositionevent.rs, components/script/dom/webidls/CompositionEvent.webidl

2017-08-15 19:56 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-08-15 19:57 UTC, bors-servo commented
:hourglass: Trying commit b0b656edd07c7b6cc818baf2aaabc8603ba9bb08 with merge b9ee9b46de93bd38a2a6547a7a6f33d763500934...

2017-08-15 20:12 UTC, bors-servo commented
:broken_heart: Test failed - [arm32](http://build.servo.org/builders/arm32/builds/8548)

2017-08-15 20:29 UTC, jdm commented
@bors-servo: retry

2017-08-15 20:29 UTC, bors-servo commented
:hourglass: Trying commit b0b656edd07c7b6cc818baf2aaabc8603ba9bb08 with merge a9f8d4c3f513e8edb04a868cfc1990f19bda6f26...

2017-08-15 20:55 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/8666)

2017-08-15 21:21 UTC, jdm commented
```
./components/script/dom/compositionevent.rs:64: no newline at EOF
```

2017-08-16 05:50 UTC, pyfisch commented
Fix newline and configure editor to always insert newline at end of file.

@bors-servo: try

2017-08-16 05:50 UTC, bors-servo commented
:hourglass: Trying commit 7d4a840a93226e0a2e469c9d133208b00032dd1a with merge 8526ae60fa6fdadafc67fde31618c067e13d0c34...

2017-08-16 16:29 UTC, bors-servo commented
:boom: Test timed out

2017-08-16 17:19 UTC, pyfisch commented
@bors-servo: retry

2017-08-16 17:19 UTC, bors-servo commented
:hourglass: Trying commit 7d4a840a93226e0a2e469c9d133208b00032dd1a with merge 33f1d7774cb2a67759d951d15867948a9b09fa79...

2017-08-16 17:51 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5493)

2017-08-16 18:48 UTC, pyfisch commented
> assert_true: If this is failing: DANGER, are you sure you want to expose the new interface CompositionEvent to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false

@jdm, @Ms2ger do you agree to expose the new interface?

2017-08-16 18:49 UTC, jdm commented
Yep.

2017-08-16 19:18 UTC, pyfisch commented
@bors-servo try

2017-08-16 19:18 UTC, bors-servo commented
:hourglass: Trying commit 301c5afbda2f7afc3d542599beeaa6f62ee32c3c with merge 2b969ca83827d2ae755eb492a77e1e418830e64a...

2017-08-16 19:22 UTC, jdm commented
One thing to be aware of - I would hesitate to merge this PR as-is, since we don't have any code that uses the CompositionEvent interface. If websites use it for feature-detection, they would get incorrect results.

2017-08-16 19:29 UTC, pyfisch commented
Feature-detection is a good point. Should I feature gate composition events or do you propose something else? I try to propose my changes as small, self-contained PRs but they not always use all of the new code immediately.

2017-08-16 19:34 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/8348)

2017-08-16 19:47 UTC, pyfisch commented
@bors-servo try

Out of curiosity, why is `./mach update-manifest` needed?

2017-08-16 19:47 UTC, bors-servo commented
:hourglass: Trying commit 18f6375f54a031b70eb77bd50ff0d3df18236acd with merge 8535f5b80dadf1158dbc3ca4b3013cd3a2d7912b...

2017-08-16 19:50 UTC, jdm commented
MANIFEST.json contains hashes of the test files, unfortunately. I would accept a PR that hides the CompositionEvent interface behind a `[Pref="dom.compositionevent.enabled"]` annotation; this would require reverting the test-related changes.

2017-08-16 20:25 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/8349)

2017-08-17 18:35 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18028) made this pull request unmergeable. Please resolve the merge conflicts.

2017-08-21 23:12 UTC, jdm requested changes

2017-08-21 23:12 UTC, jdm commented on components/script/dom/webidls/CompositionEvent.webidl
> +interface CompositionEvent : UIEvent {
Please add a `Pref="dom.compositionevent.enabled"` annotation and add a new preference to resources/prefs.json.

2017-08-21 23:12 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/interfaces.html
> +  "CompositionEvent",
All of the changes under tests/ can be reverted.

2017-08-22 10:05 UTC, pyfisch commented
requested changes done

2017-08-22 14:56 UTC, jdm commented
@bors-servo: r+

2017-08-22 14:56 UTC, bors-servo commented
:pushpin: Commit 982c4ea has been approved by `jdm`

<!-- @bors-servo r=jdm 982c4ea2d8c9d0ae414ea69f20d561022f3b98cc -->

2017-08-22 21:03 UTC, bors-servo commented
:hourglass: Testing commit 982c4ea2d8c9d0ae414ea69f20d561022f3b98cc with merge 111e9951c9e4669302eed0a5109437cfa8a446b6...

2017-08-22 22:12 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8465), [arm32](http://build.servo.org/builders/arm32/builds/8691), [arm64](http://build.servo.org/builders/arm64/builds/8721), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8802), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5572), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5611), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8806), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1281), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1285), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5499), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5561), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1288), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1288), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4055)
Approved by: jdm
Pushing 111e9951c9e4669302eed0a5109437cfa8a446b6 to master...

2017-08-22 22:12 UTC, merged