[WIP] Chrome DevTools Protocol implementation
servo/servo pull request #18133
Opened 2017-08-17 21:07 UTC by spinda

This builds on [devtools-html/cdp](https://github.com/devtools-html/cdp) and [devtools-html/tokio-cdp](https://github.com/devtools-html/tokio-cdp) to implement a [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) server into Servo. The top-level browsing context is exposed as the single "tab" supported (and thus creating new tabs and switching between active tabs is not supported). One command is implemented so far, Page.navigate, to navigate the tab to a particular URL.

Similar to the Firefox DevTools Server, the Chrome DevTools Server can be started by passing the --cdp flag to Servo. The default port is 9222; a different one can be specified by passing a port to the flag.

Video Demo: https://streamable.com/ypohw

[cdp](https://github.com/devtools-html/cdp) exposes a fully-typed interface to the Chrome DevTools Protocol, autogenerated from the protocol definition JSON (complete with [rustdoc entries](https://www.spinda.net/files/mozilla/cdp/doc/cdp/ws/index.html) for each type in the protocol). [tokio-cdp](https://github.com/devtools-html/tokio-cdp) plugs this into tokio-proto, hyper, and rust-websocket to implement a Tokio-based CDP client and server.

Currently this depends on forked versions of a couple of dependencies (specifically serde and hyper), and the cdp and tokio-cdp crates (as well as the hyper-websocket crate for handling WebSocket upgrades) are not yet fully stabilized and published to crates.io. Only the [Page.navigate command](https://www.spinda.net/files/mozilla/cdp/doc/cdp/ws/page/struct.NavigateParams.html) is wired up to Servo so far, and support for sending events back to clients (eg. [Page.domContentEventFired](https://www.spinda.net/files/mozilla/cdp/doc/cdp/ws/enum.Event.html#variant.PageDomContentEventFired)) is forthcoming.

## Todo

- [ ] Implement Page.refresh command
- [ ] Implement events sending support in tokio-cdp
- [ ] Implement Page.domContentEventFired event (and Page.enable/Page.disable commands for enabling/disabling Page events)
- [ ] Add tests
- [ ] Upstream serde changes (https://github.com/serde-rs/serde/pull/1015)
- [ ] Upstream hyper changes (https://github.com/hyperium/hyper/pull/1287)
- [ ] Publish cdp, tokio-cdp, and hyper-websocket crates in crates.io

(cc @jimblandy)

---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-08-17 21:08 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @cbrewster (or someone else) soon.

2017-08-17 21:08 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/Cargo.toml, components/constellation/constellation.rs, components/constellation/lib.rs
 * @fitzgen: components/script/dom/document.rs
 * @kichjang: components/script/dom/document.rs

2017-08-17 21:08 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify gfx and script code, but no tests are modified. Please consider adding a test!

2017-08-18 00:11 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18096) made this pull request unmergeable. Please resolve the merge conflicts.

2017-08-21 20:46 UTC, fitzgen commented
This is super awesome 👍

2017-08-26 02:48 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18171) made this pull request unmergeable. Please resolve the merge conflicts.

2017-09-07 18:25 UTC, jdm requested changes
Sorry about the long delay here! I've got no tokio experience, so I'm assuming that the control flow there is sensible.

2017-09-07 18:25 UTC, jdm commented on components/cdp/lib.rs
> +        Box::new(
Stylistically, it might be easier to read if we did:
```rust
let result = ipc::wrap_receive_ipc(...)
    .and_then(...);
Box::new(result)
```

2017-09-07 18:25 UTC, jdm commented on components/cdp/lib.rs
> +        Box::new(
Same stylistic comment as previous.

2017-09-07 18:25 UTC, jdm commented on servo-tidy.toml
> +  "tokio-proto", # only used in a test, see https://github.com/tokio-rs/tokio-proto/pull/179
Is there a newer version we can use yet that does not need this?

2017-09-07 18:25 UTC, jdm commented on components/cdp/lib.rs
> +                    debug!("CDP server now accpeting clients.");
`accepting`

2017-09-07 18:25 UTC, jdm commented on components/cdp/lib.rs
> +#![crate_type = "rlib"]
The previous two #! bits should not be required, I believe.

2017-09-07 18:25 UTC, jdm commented on components/cdp_traits/lib.rs
> +extern crate futures;
Nit: missing license header.

2017-09-07 18:25 UTC, jdm commented on components/cdp_traits/lib.rs
> +#[inline]
Why the inline marking? I can't imagine that this is a performance hit if it's not there.

2017-11-15 22:24 UTC, jdm commented
Closing due to inactivity.

2017-11-15 22:24 UTC, closed without merging