Add paint metrics to Performance Timeline API
servo/servo pull request #18155
Opened 2017-08-19 17:24 UTC by ferjm

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18111
- [X] There are tests for these changes

2017-08-19 17:24 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/pipeline.rs, components/constellation/constellation.rs
 * @wafflespeanut: python/tidy/servo_tidy/tidy.py
 * @edunham: python/tidy/servo_tidy/tidy.py
 * @fitzgen: components/script/dom/mod.rs, components/script_traits/lib.rs, components/script_traits/lib.rs, components/script_traits/script_msg.rs, components/script_traits/script_msg.rs and 7 more
 * @kichjang: components/script/dom/mod.rs, components/script_traits/lib.rs, components/script_traits/lib.rs, components/script_traits/script_msg.rs, components/script_traits/script_msg.rs and 7 more

2017-08-19 17:25 UTC, ferjm commented
r? @jdm

2017-08-22 00:04 UTC, jdm requested changes
The implementation looks fine to me.

2017-08-22 00:04 UTC, jdm commented on components/script/dom/performancepainttiming.rs
> +           name: DOMString,
Let's accept the enum here and convert it into a string in `new_inherited`.

2017-08-22 00:04 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/paint_timing.html
> +});
Let's do `var t = async_test("Performance entries observer");` instead.

2017-08-22 00:04 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/paint_timing.html
> +var observer = new PerformanceObserver(list => {
Let's do `new PerformanceObserver(t.step_func_done(list => {`

2017-08-22 00:04 UTC, jdm commented on tests/wpt/mozilla/tests/mozilla/paint_timing.html
> +  done();
We don't need the explicit `done()` any more.

2017-08-22 18:18 UTC, ferjm commented
r? @jdm. Thank you Josh. PR updated

2017-08-22 18:53 UTC, jdm commented
@bors-servo: r+

2017-08-22 18:53 UTC, bors-servo commented
:pushpin: Commit 3924ab5 has been approved by `jdm`

<!-- @bors-servo r=jdm 3924ab5da2ce031cb875792e76efa4eb701c7201 -->

2017-08-22 22:12 UTC, bors-servo commented
:hourglass: Testing commit 3924ab5da2ce031cb875792e76efa4eb701c7201 with merge e1adb94d5469c6f8bbd9c680effb4a4fcd270ef6...

2017-08-22 22:44 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5612)

2017-08-22 23:45 UTC, jdm commented
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface PerformancePaintTiming to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:73:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:13:1

  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.worker.html:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface PerformancePaintTiming to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:73:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.worker.js:9:1
```
Go ahead.

2017-08-23 07:10 UTC, ferjm commented
@bors-servo retry

2017-08-23 08:15 UTC, ferjm commented
Hmm... I used to be able to trigger retries :\

2017-08-23 15:18 UTC, jdm commented
@bors-servo: delegate+
This needs to update the manifest before it can merge.

2017-08-23 15:18 UTC, bors-servo commented
:v: @ferjm can now approve this pull request

2017-08-23 16:17 UTC, ferjm commented
@bors-servo: r=jdm

2017-08-23 16:17 UTC, bors-servo commented
:pushpin: Commit 2d0037f has been approved by `jdm`

<!-- @bors-servo r=jdm 2d0037f1957f749b65a1205c54b4a1513f988f03 -->

2017-08-23 18:23 UTC, bors-servo commented
:hourglass: Testing commit 2d0037f1957f749b65a1205c54b4a1513f988f03 with merge ad351bd09df9a4538926413745c8beeaa5674816...

2017-08-23 18:28 UTC, bors-servo commented
:snowman: The build was interrupted to prioritize another pull request.

2017-08-23 20:06 UTC, bors-servo commented
:hourglass: Testing commit 2d0037f1957f749b65a1205c54b4a1513f988f03 with merge 173079c14498f0ef4810ffbaf8f4c03acf557eed...

2017-08-23 21:04 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8494), [arm32](http://build.servo.org/builders/arm32/builds/8721), [arm64](http://build.servo.org/builders/arm64/builds/8751), [linux-dev](http://build.servo.org/builders/linux-dev/builds/8831), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5604), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5642), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/8836), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1310), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1315), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5528), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5590), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1318), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1318), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4086)
Approved by: jdm
Pushing 173079c14498f0ef4810ffbaf8f4c03acf557eed to master...

2017-08-23 21:05 UTC, merged