User Timing API
servo/servo pull request #18283
Opened 2017-08-28 19:45 UTC by ferjm

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18109 
- [X] There are tests for these changes. I enabled the peformance-timeline API WPTs but some of them are still failing because of implementation bugs or missing APIs (Resource Timing, for instance) the tests are dependent of. I'll file issues to fix them.

2017-08-28 19:45 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @jgraham: tests/wpt/include.ini
 * @fitzgen: components/script/dom/performance.rs, components/script/dom/webidls/PerformanceMark.webidl, components/script/dom/macros.rs, components/script/dom/performanceobserver.rs, components/script/dom/performancemark.rs and 4 more
 * @kichjang: components/script/dom/performance.rs, components/script/dom/webidls/PerformanceMark.webidl, components/script/dom/macros.rs, components/script/dom/performanceobserver.rs, components/script/dom/performancemark.rs and 4 more

2017-08-28 19:46 UTC, ferjm commented
r? @jdm

2017-08-28 21:22 UTC, jdm commented
@bors-servo: r+
Thanks!

2017-08-28 21:22 UTC, bors-servo commented
:pushpin: Commit 8cbd47e has been approved by `jdm`

<!-- @bors-servo r=jdm 8cbd47edc0a281ba7e42b76c14f32721e4b5def7 -->

2017-08-29 05:23 UTC, bors-servo commented
:hourglass: Testing commit 8cbd47edc0a281ba7e42b76c14f32721e4b5def7 with merge a91250ed592c18a74857f456ce22abf2f13017c1...

2017-08-29 05:58 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5751)

2017-08-29 07:52 UTC, ferjm commented
@bors-servo: try

2017-08-29 07:52 UTC, bors-servo commented
:hourglass: Trying commit 221aef9f23f27e028d3110028f5c0d8381fbcb4b with merge 845a6eaf0a18ddb19e919ac7d14c5a93a554ad52...

2017-08-29 08:56 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5755)

2017-08-29 18:10 UTC, ferjm commented
I'll try to fix #18286 before merging this one.

2017-09-01 02:23 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18317) made this pull request unmergeable. Please resolve the merge conflicts.

2017-09-02 13:35 UTC, ferjm commented
@bors-servo: try

2017-09-02 13:36 UTC, bors-servo commented
:hourglass: Trying commit 179e55608d937c0c37268565aabe769a3c0b0022 with merge 51c16a5543c7be8037678ba81aa057bc74e468bb...

2017-09-02 13:55 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/9019)

2017-09-02 16:07 UTC, ferjm commented
@bors-servo: try

2017-09-02 16:07 UTC, bors-servo commented
:hourglass: Trying commit 5675249d046b7f57deed12be24ccbc0ff52f320b with merge 212f2d57f375a25de5d9a7806174ddc2238e96b0...

2017-09-02 16:44 UTC, jdm requested changes

2017-09-02 16:44 UTC, jdm commented on components/script/dom/performance.rs
> +    fn new_inherited(timing: Option<JS<PerformanceTiming>>,
`Option<&PerformanceTiming>` will allow removing the unrooted_must_root.

2017-09-02 16:44 UTC, jdm commented on components/script/task_source/performance_timeline.rs
> +    fn main_thread_handler(self: Box<NotifyPerformanceObserverRunnable>,
This can be removed; we default to calling the handler method.

2017-09-02 16:44 UTC, jdm commented on components/script/dom/performance.rs
> +    #[allow(unrooted_must_root)]
We should be able to remove this unrooted_must_root by modifying new_inherited.

2017-09-02 16:44 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5853)

2017-09-03 22:42 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18361) made this pull request unmergeable. Please resolve the merge conflicts.

2017-09-04 09:30 UTC, ferjm commented
@bors-servo: try

2017-09-04 09:30 UTC, bors-servo commented
:hourglass: Trying commit 24daea38acb3a820a43c4b8cb010084c97c47c69 with merge 6c6ce439d2ffddd8fb00356328d0f79e7df26f78...

2017-09-04 10:37 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8706), [arm32](http://build.servo.org/builders/arm32/builds/8939), [arm64](http://build.servo.org/builders/arm64/builds/8969), [linux-dev](http://build.servo.org/builders/linux-dev/builds/9030), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5821), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5862), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9065), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1529), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1537), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5763), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5822), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1552), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1546), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4324)
State: approved= try=True

2017-09-05 17:24 UTC, jdm requested changes

2017-09-05 17:24 UTC, jdm commented on components/script/dom/performance.rs
> +            return Err((Error::Syntax));
Nit: remove the extra ()s.

2017-09-05 17:24 UTC, jdm commented on components/script/dom/webidls/Performance.webidl
> +// http://www.w3.org/TR/user-timing/
https://w3c.github.io/user-timing/#extensions-performance-interface

2017-09-07 16:31 UTC, ferjm commented
r? @jdm

2017-09-07 17:11 UTC, jdm commented
@bors-servo: r+

2017-09-07 17:11 UTC, bors-servo commented
:pushpin: Commit 8412f54 has been approved by `jdm`

<!-- @bors-servo r=jdm 8412f5403aec58eef3b29119c5dec9a73d4c414a -->

2017-09-07 17:11 UTC, jdm approved these changes

2017-09-07 17:45 UTC, bors-servo commented
:hourglass: Testing commit 8412f5403aec58eef3b29119c5dec9a73d4c414a with merge 1e93749941d2e3569c7c907832658c57ffb18c72...

2017-09-07 18:52 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8771), [arm32](http://build.servo.org/builders/arm32/builds/9004), [arm64](http://build.servo.org/builders/arm64/builds/9035), [linux-dev](http://build.servo.org/builders/linux-dev/builds/9095), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5887), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5934), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9136), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1595), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1602), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5831), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5888), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1619), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1613), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4390)
Approved by: jdm
Pushing 1e93749941d2e3569c7c907832658c57ffb18c72 to master...

2017-09-07 18:53 UTC, merged