stylo: Remove calc support from media queries
servo/servo pull request #18349
Opened 2017-09-01 18:30 UTC by canaltinova

Gecko currently doesn't support calc inside media queries. We should
also remove the calc support temporarily for parity with gecko. We can
add this support back in next releases.

Reviewed by emilio in Bugzilla.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix [Bug 1390339](https://bugzilla.mozilla.org/show_bug.cgi?id=1390339)

2017-09-01 18:30 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/gecko/media_queries.rs
 * @emilio: components/style/gecko/media_queries.rs

2017-09-01 18:30 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2017-09-01 18:31 UTC, canaltinova commented
@bors-servo r=emilio

2017-09-01 18:31 UTC, bors-servo commented
:pushpin: Commit e0f30ed has been approved by `emilio`

<!-- @bors-servo r=emilio e0f30ed4b9756fd42b77ec0c55c80077666942ae -->

2017-09-01 19:49 UTC, emilio requested changes

2017-09-01 19:49 UTC, emilio commented on components/style/gecko/media_queries.rs
> +                    // with gecko. We should remove this check when we want to support it.
Please mention the bug you filed.

2017-09-01 19:50 UTC, emilio commented
@bors-servo r-

r=me, but mentioning the bug is necessary.

2017-09-01 20:25 UTC, canaltinova commented
@bors-servo r=emilio

2017-09-01 20:25 UTC, bors-servo commented
:pushpin: Commit 7ba0667 has been approved by `emilio`

<!-- @bors-servo r=emilio 7ba0667ed96bf667a5ff3558544b59402cd68dd3 -->

2017-09-02 06:59 UTC, bors-servo commented
:hourglass: Testing commit 7ba0667ed96bf667a5ff3558544b59402cd68dd3 with merge 06c469343ecbb01a0ccd8a2afc2f940949576d98...

2017-09-02 07:49 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1523)

2017-09-02 14:37 UTC, jdm commented
@bors-servo retry
* Build timed out

2017-09-02 14:37 UTC, bors-servo commented
:hourglass: Testing commit 7ba0667ed96bf667a5ff3558544b59402cd68dd3 with merge f36580cb9187b99793f89cf60e5989979f83efca...

2017-09-02 15:49 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8696), [arm32](http://build.servo.org/builders/arm32/builds/8929), [arm64](http://build.servo.org/builders/arm64/builds/8959), [linux-dev](http://build.servo.org/builders/linux-dev/builds/9020), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5811), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5852), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9055), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1519), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1527), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5753), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5812), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1542), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1536), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4314)
Approved by: emilio
Pushing f36580cb9187b99793f89cf60e5989979f83efca to master...

2017-09-02 15:49 UTC, merged