Clean imports in hashglobe
servo/servo pull request #18385
Opened 2017-09-05 20:56 UTC by Manishearth

2017-09-05 20:59 UTC, mbrubeck requested changes

2017-09-05 20:59 UTC, mbrubeck commented on components/hashglobe/src/hash_map.rs
>  #[allow(deprecated)]
This got got detached from its `use` statement.

2017-09-05 21:00 UTC, bors-servo commented
:pushpin: Commit 02fe616 has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck 02fe616b8650952dcb112cbfadd66a18ed419cb7 -->

2017-09-06 03:47 UTC, bors-servo commented
:hourglass: Testing commit 02fe616b8650952dcb112cbfadd66a18ed419cb7 with merge 0b87d8dbef5bb24db087c66422813d0dcabd49a6...

2017-09-06 04:20 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5900)

2017-09-06 04:41 UTC, Manishearth commented
@bors-servo retry

```
{"status": "FAIL", "group": "default", "message": "/_mozilla/css/css-position-3/position-sticky-table-th-left.html 6989f695a802d6b00630a8e7a361ac83382756d0\n/_mozilla/css/css-position-3/position-sticky-table-th-left-ref.html a75f0e1a5e75cd58ca571efe3893dbd431c3f6f6\nTesting 6989f695a802d6b00630a8e7a361ac83382756d0 == a75f0e1a5e75cd58ca571efe3893dbd431c3f6f6", "stack": null, "subtest": null, "test": "/_mozilla/css/css-position-3/position-sticky-table-th-left.html", "line": 69873, "action": "test_result", "expected": "PASS"}
```

2017-09-06 05:32 UTC, bors-servo commented
:hourglass: Testing commit 02fe616b8650952dcb112cbfadd66a18ed419cb7 with merge f29fd7757396e8763753215b8e7d82cb437f8f5a...

2017-09-06 06:39 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/8743), [arm32](http://build.servo.org/builders/arm32/builds/8976), [arm64](http://build.servo.org/builders/arm64/builds/9007), [linux-dev](http://build.servo.org/builders/linux-dev/builds/9067), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/5858), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/5902), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9108), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/1566), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/1573), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/5803), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/5860), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/1591), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1584), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4362)
Approved by: mbrubeck
Pushing f29fd7757396e8763753215b8e7d82cb437f8f5a to master...

2017-09-06 06:39 UTC, merged