Switch to using WebRender hit testing
servo/servo pull request #18704
Opened 2017-10-02 10:32 UTC by mrobinson

This trades quite a bit of complicated code in Servo for few more
messages and a significant performance improvement. In particular,
WebRender can search the entire display list at once instead of
ping-ponging down the pipeline tree. This allows us to send mouse
events to the correct pipeline immediately.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they should not change behavior.

2017-10-02 10:32 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @jgraham: tests/wpt/grouping_formatter.py
 * @emilio: components/layout/webrender_helpers.rs, components/layout/query.rs
 * @fitzgen: components/script/dom/document.rs, components/script/dom/window.rs, components/script/script_thread.rs, components/script_layout_interface/message.rs, components/script_traits/lib.rs and 2 more
 * @kichjang: components/script/dom/document.rs, components/script/dom/window.rs, components/script/script_thread.rs, components/script_layout_interface/message.rs, components/script_traits/lib.rs and 2 more
 * @asajeffrey: components/constellation/constellation.rs
 * @paulrouget: components/compositing/compositor.rs, components/constellation/constellation.rs, components/compositing/compositor_thread.rs

2017-10-02 10:32 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2017-10-02 10:32 UTC, mrobinson commented
@bors-servo try

2017-10-02 10:32 UTC, bors-servo commented
:hourglass: Trying commit 52d356edc8ef87b753d0ec2d05ae0dce3c1b9ada with merge 64a4ea8fb4159a0a1f46703af905a7e464f70e22...

2017-10-02 10:37 UTC, mrobinson commented
This PR isn't quite ready to review, as I need to update the code style.

2017-10-02 10:49 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/9448)

2017-10-02 11:11 UTC, mrobinson commented
@bors-servo try

2017-10-02 11:11 UTC, bors-servo commented
:hourglass: Trying commit 227be2a27ac48ef4220618070f15ff171a003b9c with merge e6038147531faf5da8f5af2be4ba526bfad7558c...

2017-10-02 12:14 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/1981)

2017-10-02 12:54 UTC, jdm commented
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/scrollBy.html:
  │ FAIL [expected PASS] Ensure that the window.scrollBy function affects scroll position as expected
  │   → assert_equals: expected Element node <body>
    <a id="link" href="http://mozilla.org">This is... but got Element node <a id="link" href="http://mozilla.org">This is some link ...
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/scrollBy.html:23:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/scrollBy.html:10:5
```

2017-10-02 15:23 UTC, mrobinson commented
@bors-servo try

2017-10-02 15:23 UTC, bors-servo commented
:hourglass: Trying commit 83a960310e10c039f8c786c1a3d148a1e385cd80 with merge 33f85dd8d8ce4b499eb9fd28bd10b9422e018c33...

2017-10-02 16:19 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6256)

2017-10-02 16:32 UTC, mrobinson commented
```
  ▶ CRASH [expected OK] /css-transitions-1_dev/html/before-DOMContentLoaded-001.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 17.2.0-devel
  │ called `Option::unwrap()` on a `None` value (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(1)) }, at /checkout/src/libcore/option.rs:335)
  │ stack backtrace:
  │    0:     0x7fb5a595605c - backtrace::backtrace::trace::hc558941d466d8278
  │    1:     0x7fb5a5956092 - backtrace::capture::Backtrace::new::ha6795f2bcb9f5158
  │    2:     0x7fb5a40533b5 - servo::main::{{closure}}::h525ba2edc1f14706
  │    3:     0x7fb5a63e0596 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7fb5a63e03b4 - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7fb5a63e0329 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7fb5a63e02ba - std::panicking::rust_begin_panic
  │                         at /checkout/src/libstd/panicking.rs:498
  │    7:     0x7fb5a641a680 - core::panicking::panic_fmt
  │                         at /checkout/src/libcore/panicking.rs:71
  │    8:     0x7fb5a641a5b6 - core::panicking::panic
  │                         at /checkout/src/libcore/panicking.rs:51
  │    9:     0x7fb5a42c5617 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::hf58c3db4beedaa2e
  │   10:     0x7fb5a42c2d3d - layout_thread::LayoutThread::tick_all_animations::h27d058b230c3b980
  │   11:     0x7fb5a42b00ad - layout_thread::LayoutThread::handle_request_helper::h25bf1197f760cbdf
  │   12:     0x7fb5a42ab834 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::hee39b95ba0800712
  │   13:     0x7fb5a420b8c5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6656dd04e3083ef0
  │   14:     0x7fb5a42144a5 - std::panicking::try::do_call::hf425695f73c12133
  │   15:     0x7fb5a63e772c - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:99
  │   16:     0x7fb5a423eaf2 - <F as alloc::boxed::FnBox<A>>::call_box::h165d5e26aa343cdd
  │   17:     0x7fb5a63df21b - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:738
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:24
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   18:     0x7fb5a1d0c183 - start_thread
  │   19:     0x7fb5a1822ffc - clone
  │   20:                0x0 - <unknown>
  │ ERROR:servo: called `Option::unwrap()` on a `None` value
  └ Pipeline failed in hard-fail mode.  Crashing!
```

2017-10-02 17:09 UTC, jdm commented
That's the same panic and backtrace that was observed in #18701.

2017-10-03 07:12 UTC, mrobinson commented
Going to retry this in case it is an intermittent.

2017-10-03 07:12 UTC, mrobinson commented
@bors-servo try

2017-10-03 07:20 UTC, jdm commented
@bors-servo retry

2017-10-03 07:24 UTC, bors-servo commented
:hourglass: Trying commit 83a960310e10c039f8c786c1a3d148a1e385cd80 with merge 07a45689bfc1128b7c884ccef2fa78067919cb78...

2017-10-03 17:40 UTC, bors-servo commented
:boom: Test timed out

2017-10-03 19:32 UTC, KiChjang commented
@bors-servo retry

2017-10-03 19:32 UTC, bors-servo commented
:lock: Merge conflict

2017-10-04 07:19 UTC, bors-servo commented
:hourglass: Trying commit 85abc996fac68c1ab667495aeff4d8fbae2c950a with merge 0245fc9f4d134114f5850fdc30d9172d8fd26994...

2017-10-04 07:19 UTC, bors-servo commented
:broken_heart: Test failed - [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4840)

2017-10-04 10:08 UTC, mrobinson commented
@bors-servo retry
 * Problems with Windows build bot

2017-10-04 10:08 UTC, bors-servo commented
:hourglass: Trying commit 85abc996fac68c1ab667495aeff4d8fbae2c950a with merge 0e990695273ea33136affe5f7bda23abc40e4444...

2017-10-04 10:38 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6257)

2017-10-04 22:58 UTC, jdm commented
@bors-servo: retry
* problems with mac buildbot

2017-10-04 22:58 UTC, bors-servo commented
:hourglass: Trying commit 85abc996fac68c1ab667495aeff4d8fbae2c950a with merge 34ffe345b85bc306f62a144283aebd8a94994024...

2017-10-04 23:52 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18735) made this pull request unmergeable. Please resolve the merge conflicts.

2017-10-05 01:39 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/9201), [arm32](http://build.servo.org/builders/arm32/builds/9430), [arm64](http://build.servo.org/builders/arm64/builds/9468), [linux-dev](http://build.servo.org/builders/linux-dev/builds/9496), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6311), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/6355), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9575), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2007), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2018), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6270), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6328), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2051), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2041), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/4859)
State: approved= try=True

2017-10-05 09:18 UTC, mrobinson commented
Okay. Sorry for all the builder churn here, but I think this PR is now ready to review.

2017-10-12 21:49 UTC, glennw commented
Reviewed 8 of 18 files at r1.
Review status: 8 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18704)*
<!-- Sent from Reviewable.io -->

2017-10-12 21:50 UTC, glennw commented
I started looking at this, but it touches a lot of code that I'm not very familiar with - @mbrubeck would you have time to look over the layout / compositor parts? @jdm Would you have time to look over the script / style parts (or perhaps suggest someone else?).

2017-10-12 21:57 UTC, jdm commented
@nox Would you like to look at this?

2017-10-13 19:11 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18854) made this pull request unmergeable. Please resolve the merge conflicts.

2017-10-16 15:52 UTC, jdm requested changes
The changes to script/ look fine to me. I like how much duplicated code is being removed!

2017-10-16 15:52 UTC, jdm commented on components/script_traits/lib.rs
> +    /// Requests that the constellation inform the compositor of the a cursor change.
This comment doesn't make sense, since the compositor is the one that sends this message.

2017-10-16 15:52 UTC, jdm commented on components/script_traits/lib.rs
> +    TouchpadPressureEvent(Point2D<f32>, f32, TouchpadPressurePhase, Option<u64>),
I would prefer to use something like `struct OpaqueNodeAddress(usize)` instead of a direct u64 here.

2017-10-16 16:54 UTC, mrobinson commented
@jdm Thanks for the review. I think I've fix all the issues you've raised.

2017-10-16 17:52 UTC, mbrubeck commented
I'll review the layout/compositor changes.

2017-10-16 19:44 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #18890) made this pull request unmergeable. Please resolve the merge conflicts.

2017-10-17 16:30 UTC, mbrubeck approved these changes
r+ for the layout and compositor changes.

2017-10-17 19:13 UTC, jdm commented
@bors-servo: r=jdm,glennw,mbrubeck

2017-10-17 19:13 UTC, bors-servo commented
:pushpin: Commit 7692145 has been approved by `jdm,glennw,mbrubeck`

<!-- @bors-servo r=jdm,glennw,mbrubeck 769214509cc8f147640a79be07e714458f3dfbf2 -->

2017-10-17 19:45 UTC, bors-servo commented
:hourglass: Testing commit 769214509cc8f147640a79be07e714458f3dfbf2 with merge a12ba649f192776e8686b32e69b6b7a80cc8a208...

2017-10-17 19:50 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6524)

2017-10-17 20:35 UTC, jdm commented
```
error[E0433]: failed to resolve. Use of undeclared type or module `NonZeroU32`
   --> /home/servo/buildbot/slave/linux-rel-css/build/components/msg/constellation_msg.rs:255:38
    |
255 |                 index: PipelineIndex(NonZeroU32::new_unchecked(index)),
    |                                      ^^^^^^^^^^ Use of undeclared type or module `NonZeroU32`
```

2017-10-17 20:35 UTC, jdm commented
I think you can use NonZero::new_unchecked now instead.

2017-10-17 21:33 UTC, mrobinson commented
Rebased and ready to go.

@bors-servo: r=jdm,glennw,mbrubeck

2017-10-17 21:33 UTC, bors-servo commented
:pushpin: Commit b5d51dd has been approved by `jdm,glennw,mbrubeck`

<!-- @bors-servo r=jdm,glennw,mbrubeck b5d51dd2636935471447fc741ffbb95c62e37f94 -->

2017-10-17 22:09 UTC, bors-servo commented
:hourglass: Testing commit b5d51dd2636935471447fc741ffbb95c62e37f94 with merge ca08271345f78fa881c174545f5b69a8ccb78143...

2017-10-17 23:23 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/9424), [arm32](http://build.servo.org/builders/arm32/builds/9653), [arm64](http://build.servo.org/builders/arm64/builds/9686), [linux-dev](http://build.servo.org/builders/linux-dev/builds/9708), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6527), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/6561), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9782), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2202), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2216), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6474), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6531), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2264), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2245), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5081)
Approved by: jdm,glennw,mbrubeck
Pushing ca08271345f78fa881c174545f5b69a8ccb78143 to master...

2017-10-17 23:23 UTC, merged

2017-10-18 06:16 UTC, mrobinson commented
Thanks for the reviews!

2017-10-18 15:06 UTC, jrmuizel commented
@mrobinson How does this handle hit testing transparent backgrounds?

2017-10-18 15:11 UTC, mrobinson commented
@jrmuizel Transparent backgrounds are handled by sending transparent rectangles with the display lit. They are added to the list of hit testing items, but are culled early from rendering.