Update domparsing spec links to not point at WHATWG
servo/servo pull request #18869
Opened 2017-10-13 16:58 UTC by kafji

Change domparsing spec links from domparsing.spec.whatwg.org to w3c.github.io/DOM-Parsing.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14555
- [X] These changes do not require tests because these only affect documentation

2017-10-13 16:58 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @kichjang (or someone else) soon.

2017-10-13 16:58 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/tidy/servo_tidy/tidy.py
 * @edunham: python/tidy/servo_tidy/tidy.py

2017-10-13 17:04 UTC, jdm requested changes

2017-10-13 17:04 UTC, jdm commented on python/tidy/servo_tidy/tidy.py
> +    "//w3c.github.io/DOM-Parsing",
We can remove this line now; it's already covered by the w3c.github.io further down in the list.

2017-10-13 17:45 UTC, jdm commented
@bors-servo: r+
Thanks!

2017-10-13 17:45 UTC, bors-servo commented
:pushpin: Commit b0c9c27 has been approved by `jdm`

<!-- @bors-servo r=jdm b0c9c2780b5b801e730a82ede56508767528db15 -->

2017-10-14 02:20 UTC, bors-servo commented
:hourglass: Testing commit b0c9c2780b5b801e730a82ede56508767528db15 with merge faeda2f7f2b9537afcc28ca744219ed54700bf43...

2017-10-14 02:42 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/9635)

2017-10-14 02:49 UTC, jdm commented
You will need to run `./mach update-manifest` to accommodate the changes to the test files.

2017-10-14 12:38 UTC, jdm commented
Could you squash the three commits into one, since they're all related?

2017-10-14 14:57 UTC, kafji commented
squashed & rebased

2017-10-14 15:08 UTC, jdm approved these changes

2017-10-14 15:08 UTC, jdm commented
@bors-servo: r+
Thanks!

2017-10-14 15:08 UTC, bors-servo commented
:pushpin: Commit ad22e6e has been approved by `jdm`

<!-- @bors-servo r=jdm ad22e6edfe3df6cb2198f7b15e67ecaa58d7e932 -->

2017-10-14 16:16 UTC, bors-servo commented
:hourglass: Testing commit ad22e6edfe3df6cb2198f7b15e67ecaa58d7e932 with merge ac5da66a4f2cace3675e34abf74f7ab7e80533b2...

2017-10-14 18:26 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/9358), [arm32](http://build.servo.org/builders/arm32/builds/9586), [arm64](http://build.servo.org/builders/arm64/builds/9620), [linux-dev](http://build.servo.org/builders/linux-dev/builds/9645), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6464), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/6500), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9721), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2141), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2155), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6415), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6468), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2196), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2182), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5014)
Approved by: jdm
Pushing ac5da66a4f2cace3675e34abf74f7ab7e80533b2 to master...

2017-10-14 18:26 UTC, merged