changed f64 to u64 for navigation start timing until it had to be float
servo/servo pull request #19077
Opened 2017-10-31 23:38 UTC by avadacatavra

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18997 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-10-31 23:39 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @paulrouget: components/compositing/compositor.rs
 * @fitzgen: components/script/dom/document.rs, components/script/dom/performance.rs, components/script/dom/workerglobalscope.rs, components/script_traits/lib.rs, components/script_traits/lib.rs and 4 more
 * @kichjang: components/script/dom/document.rs, components/script/dom/performance.rs, components/script/dom/workerglobalscope.rs, components/script_traits/lib.rs, components/script_traits/lib.rs and 4 more

2017-10-31 23:39 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-11-01 11:21 UTC, avadacatavra commented
@jdm r?

2017-11-01 13:17 UTC, jdm requested changes

2017-11-01 13:17 UTC, jdm commented on components/script/dom/performance.rs
> +        let navigation_start_precise = navigation_start_precise as f64;
Let's change PerformanceTiming to accept a u64 as well, and make PerformanceTiming::navigation_start_precise() return u64. We can simplify Performace::now() to only cast the result of the calculation instead.

2017-11-01 20:12 UTC, avadacatavra commented
...oops i messed up my rebase

2017-11-01 20:22 UTC, jdm requested changes

2017-11-01 20:22 UTC, jdm commented on components/script/dom/performance.rs
> +        let navigation_start_precise = navigation_start_precise;
This isn't necessary now.

2017-11-01 20:22 UTC, jdm commented on components/script/dom/performance.rs
> +        (time::precise_time_ns() as f64 - nav_start as f64) / 1000000 as f64
We should be able to write this as `(time::precise_time_ns() - nav_start) as f64 / 1000000.` now.

2017-11-01 21:48 UTC, jdm commented
@bors-servo: r+
That is much nicer to read!

2017-11-01 21:48 UTC, bors-servo commented
:pushpin: Commit 0a09ee5 has been approved by `jdm`

<!-- @bors-servo r=jdm 0a09ee5cd863aebcffa648398ca7c1b027d44ae0 -->

2017-11-01 21:56 UTC, bors-servo commented
:hourglass: Testing commit 0a09ee5cd863aebcffa648398ca7c1b027d44ae0 with merge fa319170ebb34afcdfc120b7c3e47fe5b1c21210...

2017-11-01 23:00 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/9619), [arm32](http://build.servo.org/builders/arm32/builds/9850), [arm64](http://build.servo.org/builders/arm64/builds/9882), [linux-dev](http://build.servo.org/builders/linux-dev/builds/9900), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6723), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/6754), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/9959), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2390), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2407), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6653), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6719), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2470), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2433), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5276)
Approved by: jdm
Pushing fa319170ebb34afcdfc120b7c3e47fe5b1c21210 to master...

2017-11-01 23:01 UTC, merged