Fire 'select' event in SetSelection{Start,End}
servo/servo pull request #19202
Opened 2017-11-13 16:06 UTC by jonleighton

See #19171.

2017-11-13 16:06 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2017-11-13 16:06 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/htmlinputelement.rs
 * @kichjang: components/script/dom/htmlinputelement.rs

2017-11-13 16:33 UTC, tigercosmos requested changes
You can delete the pass test cases in  `tests/wpt/metadata/html/semantics/forms/textfieldselection/selection-start-end.html.ini` 
We only need to remain the unexpected ones

2017-11-13 16:33 UTC, tigercosmos commented on tests/wpt/metadata/html/semantics/forms/textfieldselection/selection-start-end.html.ini
If Pass, You can delete it directly

2017-11-14 00:33 UTC, KiChjang requested changes
👍 Great start! I only have minor comments about adding comments ;). Once you've addressed them, you can r=me.

2017-11-14 00:33 UTC, KiChjang commented on components/script/dom/htmlinputelement.rs
> +    fn set_selection_range(&self, start: u32, end: u32, direction: SelectionDirection) {
Let's add a spec link comment above this function (https://html.spec.whatwg.org/multipage/#set-the-selection-range).

2017-11-14 00:33 UTC, KiChjang commented on components/script/dom/htmlinputelement.rs
> +        let _ = window.user_interaction_task_source().queue_event(
Let's also add step annotations for this function. For example, this particular line here follows step 6 of the linked algorithm (albeit incorrectly).

2017-11-15 07:51 UTC, jonleighton commented
Thanks, requested changes implemented

2017-11-15 07:51 UTC, jonleighton commented
r? @KiChjang

2017-11-15 07:54 UTC, KiChjang requested changes
One final nit!

2017-11-15 07:54 UTC, KiChjang commented on tests/wpt/metadata/html/semantics/forms/textfieldselection/selection-start-end.html.ini
> +  expected: OK
You can remove this line now.

2017-11-15 07:56 UTC, KiChjang commented
Also, after you've made the changes, can you squash your commits into one, please?

2017-11-15 09:55 UTC, jonleighton commented
Sure, done

2017-11-15 10:08 UTC, KiChjang commented
@bors-servo r+

Thanks!

2017-11-15 10:08 UTC, bors-servo commented
:pushpin: Commit 93b047a has been approved by `KiChjang`

<!-- @bors-servo r=KiChjang 93b047a91be55577be475ed9d55ba7a368353de5 -->

2017-11-15 10:08 UTC, bors-servo commented
:hourglass: Testing commit 93b047a91be55577be475ed9d55ba7a368353de5 with merge 2efbf2230a61a2fda1ecc4cd12618177d4ca50cd...

2017-11-15 11:19 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/9769), [arm32](http://build.servo.org/builders/arm32/builds/10002), [arm64](http://build.servo.org/builders/arm64/builds/10033), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10051), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6881), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/6907), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10109), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2543), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2559), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6804), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6869), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2622), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2584), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5426)
Approved by: KiChjang
Pushing 2efbf2230a61a2fda1ecc4cd12618177d4ca50cd to master...

2017-11-15 11:20 UTC, merged