Move custom elements stuff to their own dom::bindings submodule
servo/servo pull request #19254
Opened 2017-11-16 19:29 UTC by olmanz

r? @jdm 
Moved the following functions from components/script/dom/bindings/interface.rs to a new file components/script/dom/bindings/htmlconstructor.rs:

- html_constructor()
- get_constructor_object_from_local_name()
- pop_current_element_queue()
- push_new_element_queue()

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #19179.

- [X] These changes do not require tests

2017-11-16 19:29 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @jdm (or someone else) soon.

2017-11-16 19:29 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/bindings/htmlconstructor.rs, components/script/dom/bindings/interface.rs, components/script/dom/bindings/mod.rs
 * @kichjang: components/script/dom/bindings/codegen/CodegenRust.py, components/script/dom/bindings/htmlconstructor.rs, components/script/dom/bindings/interface.rs, components/script/dom/bindings/mod.rs

2017-11-16 19:29 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-11-16 19:42 UTC, cbrewster commented
```
Checking files for tidiness...

./components/script/dom/bindings/htmlconstructor.rs:1: incorrect license

./components/script/dom/bindings/htmlconstructor.rs:172: trailing whitespace

./components/script/dom/bindings/htmlconstructor.rs:173: Line is longer than 120 characters

./components/script/dom/bindings/htmlconstructor.rs:77: use statement is not in alphabetical order

	expected: html5ever::interface::QualName

	found: html5ever::LocalName

./components/script/dom/bindings/htmlconstructor.rs:78: use statement contains braces for single import

./components/script/dom/bindings/htmlconstructor.rs:80: use statement is not in alphabetical order

	expected: js::jsapi::HandleObject

	found: js::jsapi::{CallArgs, CurrentGlobalOrNull}
```

2017-11-16 20:01 UTC, jdm requested changes
Once the test-tidy errors are fixed this should be good to merge!

2017-11-16 20:01 UTC, jdm commented on components/script/dom/bindings/htmlconstructor.rs
> +                                  /// Returns the constructor object for the element associated with the given local name.
nit: remove the extra indentation.

2017-11-17 11:10 UTC, olmanz commented
I fixed the tidy-test issues, now it schould be OK.

2017-11-17 14:09 UTC, jdm commented
@bors-servo r+
Thanks!

2017-11-17 14:09 UTC, bors-servo commented
:pushpin: Commit b08d455 has been approved by `jdm`

<!-- @bors-servo r=jdm b08d455b7587457664585dddb0dfebc60d52b9ae -->

2017-11-17 14:10 UTC, bors-servo commented
:hourglass: Testing commit b08d455b7587457664585dddb0dfebc60d52b9ae with merge 3d28d8da579e8e4e24722924eb0e49d04d2a9f0d...

2017-11-17 14:54 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2587)

2017-11-17 22:01 UTC, olmanz commented
I saw that one of the tests has still failed, but I'm not sure why....
./mach test-tidy has worked, but the test that has failed is ./mach filter-intermittents..... How can this be fixed?

2017-11-17 22:04 UTC, KiChjang commented
```
  ▶ Unexpected subtest result in /css/cssom-view/elementsFromPoint-iframes.html:
  └ PASS [expected FAIL] elementsFromPoint on inner documents
```
Is this a legitimate PASS?

2017-11-17 22:06 UTC, jdm commented
Can't be; this is just moving code around. I've filed #19273.

2017-11-17 22:06 UTC, jdm commented
@bors-servo: retry
* #19273

2017-11-17 22:06 UTC, bors-servo commented
:hourglass: Testing commit b08d455b7587457664585dddb0dfebc60d52b9ae with merge 07fd6155aae8579f1a30ea99af3549c413240f24...

2017-11-17 23:13 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/9817), [arm32](http://build.servo.org/builders/arm32/builds/10051), [arm64](http://build.servo.org/builders/arm64/builds/10081), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10099), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6930), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/6956), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10157), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2591), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2607), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6852), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6917), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2671), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2631), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5474)
Approved by: jdm
Pushing 07fd6155aae8579f1a30ea99af3549c413240f24 to master...

2017-11-17 23:14 UTC, merged