Add RAII guard for cancelling fetch when the consumer no longer cares about it
servo/servo pull request #19329
Opened 2017-11-21 23:34 UTC by Manishearth

2017-11-21 23:34 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @fitzgen: components/script/fetch.rs, components/script/dom/xmlhttprequest.rs
 * @kichjang: components/script/fetch.rs, components/script/dom/xmlhttprequest.rs

2017-11-21 23:34 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-11-22 00:46 UTC, Manishearth commented
r? @jdm 

We can add this to more consumers but I think it's better to make easy bugs out of this. XHR and loading are the main two consumers anyway.

2017-11-22 19:09 UTC, jdm requested changes

2017-11-22 19:09 UTC, jdm commented on components/script_traits/script_msg.rs
> +    InitiateNavigateRequest(RequestInit, /* cancellation_chan */ Option<IpcReceiver<()>>),
It's not clear why this is optional.

2017-11-22 22:30 UTC, jdm commented
@bors-servo: r+

2017-11-22 22:30 UTC, bors-servo commented
:pushpin: Commit 3900f5e has been approved by `jdm`

<!-- @bors-servo r=jdm 3900f5e616397ac7f9fae2875a6b58557796ef90 -->

2017-11-22 22:30 UTC, bors-servo commented
:hourglass: Testing commit 3900f5e616397ac7f9fae2875a6b58557796ef90 with merge cd35dc12fbca365de04ec9364ea208a9c0bddd95...

2017-11-22 23:09 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7022)

2017-11-22 23:11 UTC, Manishearth commented
@bors-servo retry

2017-11-22 23:11 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/9883), [arm32](http://build.servo.org/builders/arm32/builds/10117), [arm64](http://build.servo.org/builders/arm64/builds/10147), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10166), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10225), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2737), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5541) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6996), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7022), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2658), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2673), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6918), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6984), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2697)...

2017-11-22 23:21 UTC, bors-servo commented
:snowman: The build was interrupted to prioritize another pull request.

2017-11-23 00:30 UTC, bors-servo commented
:hourglass: Testing commit 3900f5e616397ac7f9fae2875a6b58557796ef90 with merge 976f9e3d13b6a7676dd863dd397dd6c60e868d58...

2017-11-23 01:42 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/9885), [arm32](http://build.servo.org/builders/arm32/builds/10119), [arm64](http://build.servo.org/builders/arm64/builds/10149), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10168), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6998), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7025), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10227), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2660), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2675), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6920), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6986), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2739), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2699), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5543)
Approved by: jdm
Pushing 976f9e3d13b6a7676dd863dd397dd6c60e868d58 to master...

2017-11-23 01:43 UTC, merged