Report an errror if a package has duplicates allowed but there are no duplicates
servo/servo pull request #19325
Opened 2017-11-21 18:24 UTC by m-novikov

Resolves: #19306

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #19306 (github issue number if applicable).

- [X] There are tests for these changes

2017-11-21 18:24 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @kichjang (or someone else) soon.

2017-11-21 18:24 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/tidy/servo_tidy_tests/test_tidy.py, python/tidy/servo_tidy/tidy.py
 * @edunham: python/tidy/servo_tidy_tests/test_tidy.py, python/tidy/servo_tidy/tidy.py

2017-11-21 19:21 UTC, KiChjang requested changes

2017-11-21 19:21 UTC, KiChjang commented on python/tidy/servo_tidy/tidy.py
> +        if not (has_duplicates or duplicates_allowed):
This combined with the line above looks like an exclusive-or to me. Perhaps you can combine the two conditions and use `==` instead?

2017-11-21 19:21 UTC, KiChjang commented on python/tidy/servo_tidy/tidy.py
> +            message = 'duplicates for {} is allowed, but only signle version found'.format(name)
`single`

2017-11-21 19:22 UTC, KiChjang commented
My python-fu is still subpar, so I'm going to have to redirect this. r? @jdm

2017-11-21 20:01 UTC, jdm requested changes
I agree with KiChjang's comments.

2017-11-22 17:49 UTC, jdm commented
@bors-servo: r+
Thanks for fixing this!

2017-11-22 17:49 UTC, bors-servo commented
:pushpin: Commit e6d9fd8 has been approved by `jdm`

<!-- @bors-servo r=jdm e6d9fd8a4ff9351d5e06c092a9ddc43de5cb73b8 -->

2017-11-22 17:49 UTC, bors-servo commented
:hourglass: Testing commit e6d9fd8a4ff9351d5e06c092a9ddc43de5cb73b8 with merge a812af51d614bd96402da91d8f648ce51b301a1b...

2017-11-22 18:54 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/9880), [arm32](http://build.servo.org/builders/arm32/builds/10114), [arm64](http://build.servo.org/builders/arm64/builds/10144), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10163), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/6993), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7019), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10222), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2655), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2670), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/6915), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/6981), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/2734), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2694), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5538)
Approved by: jdm
Pushing a812af51d614bd96402da91d8f648ce51b301a1b to master...

2017-11-22 18:54 UTC, merged