Implement the create an element for token algorithm
servo/servo pull request #19397
Opened 2017-11-27 19:58 UTC by cbrewster

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #19392 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2017-11-27 19:58 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/servoparser/mod.rs, components/script/dom/servoparser/async_html.rs
 * @fitzgen: components/script/dom/servoparser/mod.rs, components/script/dom/servoparser/async_html.rs
 * @kichjang: components/script/dom/servoparser/mod.rs, components/script/dom/servoparser/async_html.rs

2017-11-27 19:58 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2017-11-27 19:59 UTC, cbrewster commented
r? @jdm 
Was there a specific test case that I could add here?
Also do we have a way of determining if the JavaScript execution context stack is empty?

2017-11-27 20:38 UTC, jdm commented
The test that led me to discover this was to take parser-fallsback-to-unknown-element.html and add a `document.write()` call in an `onerror` handler. Without #19393 the parser is in an unexpected state and we get a borrow panic.

2017-11-27 20:49 UTC, jdm requested changes

2017-11-27 20:49 UTC, jdm commented on components/script/dom/servoparser/mod.rs
> +        // TODO: If the JavaScript execution context stack is empty, then perform a microtask checkpoint.
We should add an API to https://github.com/servo/servo/blob/master/components/script/dom/bindings/settings_stack.rs to check this.

2017-11-27 20:49 UTC, jdm commented on components/script/dom/servoparser/mod.rs
> +    let will_execute_scrtipt = definition.is_some();
`script`

2017-11-27 20:49 UTC, jdm commented on components/script/dom/servoparser/mod.rs
> +    // TODO: Check if the parser was created for the HTML fragment parsing algorithm
We should add a field to ServoParser with this information.

2017-11-27 20:49 UTC, jdm commented on components/script/dom/servoparser/mod.rs
> +    // TODO: Step 12.
Step 12 is handled from the parser callback `associate_with_form`.

2018-01-04 18:09 UTC, jdm commented
@bors-servo: try

2018-01-04 18:09 UTC, bors-servo commented
:hourglass: Trying commit df301b5b552383ec8ff761deadfaf5b95b9d67e0 with merge 5f72baed867a40558623e381eeac4936455ceeb5...

2018-01-04 18:09 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7423)

2018-01-04 18:09 UTC, jdm commented
Bleah:
```
./components/script/dom/servoparser/mod.rs:110: derivable traits list is not in alphabetical order
	expected: Clone, Copy, JSTraceable, MallocSizeOf, PartialEq
	found: Clone, Copy, PartialEq, JSTraceable, MallocSizeOf
```

2018-01-08 23:19 UTC, jdm commented
@bors-servo try

2018-01-08 23:19 UTC, bors-servo commented
:hourglass: Trying commit f7e8f565985b143e2efe12faf8501d1fa57c0c08 with merge 3fc40f7f882194069025db8ca25a546d9d9e4223...

2018-01-09 00:00 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7361)

2018-01-09 02:07 UTC, CYBAI commented
Failed with #19495

2018-01-09 13:38 UTC, KiChjang commented
@bors-servo retry

2018-01-09 13:38 UTC, bors-servo commented
:hourglass: Trying commit f7e8f565985b143e2efe12faf8501d1fa57c0c08 with merge 141192d2129f2524919d8fb7ca59fd767e0b6dcc...

2018-01-09 13:56 UTC, jdm commented
I appreciate the support, but I was watching the build and it didn't need a retry.

2018-01-09 15:08 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10328), [arm32](http://build.servo.org/builders/arm32/builds/10563), [arm64](http://build.servo.org/builders/arm64/builds/10590), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10615), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7474), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7489), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10692), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3102), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3121), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7371), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7430), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3190), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3140), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5989)
State: approved= try=True

2018-01-11 16:15 UTC, jdm commented
r? @nox for the last commit. I've reviewed the rest of them.

2018-01-17 16:22 UTC, nox commented
@bors-servo r=jdm,nox

2018-01-17 16:22 UTC, bors-servo commented
:pushpin: Commit c55f25b has been approved by `jdm,nox`

<!-- @bors-servo r=jdm,nox c55f25b3aaeea7719f0864b1e6c1e71af7f05340 -->

2018-01-17 16:57 UTC, bors-servo commented
:hourglass: Testing commit c55f25b3aaeea7719f0864b1e6c1e71af7f05340 with merge fa82a6bbcef23c1ff4dc9d34f5f4ad75b622b3be...

2018-01-17 18:12 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10422), [arm32](http://build.servo.org/builders/arm32/builds/10659), [arm64](http://build.servo.org/builders/arm64/builds/10685), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10711), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7574), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7587), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10791), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3195), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3215), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7464), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7526), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3285), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3234), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6088)
Approved by: jdm,nox
Pushing fa82a6bbcef23c1ff4dc9d34f5f4ad75b622b3be to master...

2018-01-17 18:12 UTC, merged