style: Move text-align outside of the mako file.
servo/servo pull request #19576
Opened 2017-12-15 17:42 UTC by canaltinova

I will need this refactoring before my next job. I didn't actually fix the FIXME's along the way. My other PR probably will cover these.   

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

2017-12-15 17:42 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/properties/longhand/inherited_text.mako.rs, components/style/values/computed/text.rs, components/style/values/specified/mod.rs, components/style/values/computed/mod.rs, components/style/values/specified/text.rs and 1 more
 * @emilio: components/style/properties/longhand/inherited_text.mako.rs, components/style/values/computed/text.rs, components/style/values/specified/mod.rs, components/style/values/computed/mod.rs, components/style/values/specified/text.rs and 1 more

2017-12-15 17:42 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2017-12-15 17:43 UTC, canaltinova commented
r? @emilio or @Manishearth

2017-12-15 18:20 UTC, Manishearth approved these changes

2017-12-15 18:20 UTC, Manishearth commented on components/style/values/specified/text.rs
> +    Keyword(ComputedTextAlign),
Given that `ComputedTextAlign` is used in the specified value I'd prefer if it were in this file as `TextAlignKeyword` and `computed::TextAlign` is an alias

2017-12-15 18:30 UTC, emilio approved these changes
r=me with @Manishearth's comment addressed and mine.

2017-12-15 18:30 UTC, emilio commented on components/style/values/specified/text.rs
> +            if let Ok(_) = input.try(|i| i.expect_ident_matching("match-parent")) {
This doesn't need to use `if let`, just:

```rust
input.expect_ident_matching("match_parent")?;
return Ok(TextAlign::MatchParent);
```

2017-12-15 18:31 UTC, emilio commented on components/style/values/computed/text.rs
> +                match self {
This is super stupid btw (not your fault of course). I should just land the patch to `derive(Parse)` for keywords and use `self as u32`.

2017-12-15 18:39 UTC, emilio commented on components/style/values/computed/text.rs
> +                match self {
I'll actually land it, gimme a sec :)

2017-12-15 19:16 UTC, emilio commented on components/style/values/computed/text.rs
> +                match self {
#19578

2017-12-16 21:51 UTC, canaltinova commented
@emilio Added a small commit to do that Parse derive. Could you look at it?

2017-12-16 23:07 UTC, emilio approved these changes
Arrg, still unfortunate we need the macros just for `from_u32`, but it's fine for now. We can maybe auto-generate that in the future.

2017-12-16 23:10 UTC, emilio commented on components/style/values/specified/text.rs
> +        return Err(input.new_custom_error(StyleParseErrorKind::UnspecifiedError));
Travis has failed because this is unreachable on Gecko.

2017-12-17 03:58 UTC, canaltinova commented
Actually let me create a `ToKeywordEnum` proc macro to implement `from_u32`. So we can get rid of that macro.

2017-12-17 04:07 UTC, canaltinova commented
Can you look at it again to the new commit?

2017-12-17 11:32 UTC, emilio commented on components/style_derive/to_keyword_enum.rs
> +        impl #name {
It'd be nice to make it a real trait if possible. also, it's kind of unfortunate that we fix this to `u32` enums, isn't it?

I think the macro is ok for now if there's only one use case.

2017-12-18 17:54 UTC, canaltinova commented
Nvm, it doesn't worth the effort. Changed back to macro.
@bors-servo r=Manishearth,emilio

2017-12-18 17:54 UTC, bors-servo commented
:pushpin: Commit 8c2c478 has been approved by `Manishearth,emilio`

<!-- @bors-servo r=Manishearth,emilio 8c2c4787353be1d008aa7da39841a8dd29e6b3ef -->

2017-12-18 17:56 UTC, emilio requested changes

2017-12-18 17:56 UTC, emilio commented on components/style/values/specified/text.rs
> +            input.expect_ident_matching("match_parent")?;
`match-parent` (s/_/-/)

2017-12-18 17:57 UTC, emilio commented
@bors-servo r-

2017-12-18 17:57 UTC, emilio commented
(Feel free to land with that fixed and the rest of the patch sanity-checked, thanks!)

2017-12-18 18:01 UTC, canaltinova commented
Oops, thanks!
@bors-servo r=Manishearth,emilio

2017-12-18 18:01 UTC, bors-servo commented
:pushpin: Commit 9882d0b has been approved by `Manishearth,emilio`

<!-- @bors-servo r=Manishearth,emilio 9882d0bae5eba3820c6231858ae73ef2396f2cb9 -->

2017-12-18 18:12 UTC, bors-servo commented
:hourglass: Testing commit 9882d0bae5eba3820c6231858ae73ef2396f2cb9 with merge a9c17970c19a993920ce1ba2ff9faebd033c52b4...

2017-12-18 19:16 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10164), [arm32](http://build.servo.org/builders/arm32/builds/10401), [arm64](http://build.servo.org/builders/arm64/builds/10429), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10454), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7295), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7319), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10519), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/2944), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/2960), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7206), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7266), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3024), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/2980), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5823)
Approved by: Manishearth,emilio
Pushing a9c17970c19a993920ce1ba2ff9faebd033c52b4 to master...

2017-12-18 19:17 UTC, merged