Detect adjoining text fragments with no whitespace between them and avoid linebreaking there
servo/servo pull request #19688
Opened 2018-01-04 13:43 UTC by Manishearth

2018-01-04 13:43 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @emilio: components/layout/fragment.rs, components/layout/inline.rs

2018-01-04 13:43 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify layout code, but no tests are modified. Please consider adding a test!

2018-01-04 13:45 UTC, Manishearth commented
I'm very unfamiliar with the code here, and I figured that instead of trying to get a million questions answered over a 12 hour time difference, it would make more sense to try a simple attempt at a solution and be told what's wrong with it 😄 

feedback? @mbrubeck

2018-01-04 16:47 UTC, mbrubeck commented
Testing for whitespace alone will not suffice, since we still want to break on characters like hyphens in cases like `foo-<b>bar</b>`. Instead we need to use the UAX 14 line breaking algorithm to determine whether a breaking opportunity exists.

Currently we run UAX 14 in [TextRun::break_and_shape][1],  when constructing each TextRun. The text run is split on line-break opportunities, and the segments are stored as a `Vec<GlyphRun>` inside the TextRun. This is done by the [TextRunScanner][2] during flow construction. Since it runs on one TextRun at a time, it can't determine whether a line break exists between TextRuns.

(A text run is used in shaping and must be a contiguous slice of text with the same shaping options, so in the general case we can't simply combine all the text of a single "word" into a single TextRun.  The [overview][3] has some additional high-level description.)

At a conceptual level, we need to run UAX 14 on the entire inline flow as a single string of text. Maybe could do that by moving line-break scanning out of TextRun construction, to some other place that can process all the fragments together. An alternative would be to keep the current code for finding intra-run breaks, and do a separate check to determine whether to allow breaks between runs (similar to the approach in this PR).  This would be less intrusive, but I don't know how feasible or efficient it could be.

xi-unicode has a `LineBreakLeafIter` type looks useful for finding line breaks without having a contiguous `str` for the entire flow.  It still requires starting from the beginning of the flow, though; it doesn't offer any way to test for a break at an arbitrary point in the middle of a string/rope.

[1]: https://github.com/servo/servo/blob/7a9f99eda881d500ea344382d02037bfd11789da/components/gfx/text/text_run.rs#L194
[2]: https://github.com/servo/servo/blob/7a9f99eda881d500ea344382d02037bfd11789da/components/layout/text.rs
[3]: https://github.com/servo/servo/wiki/Layout-Overview#text-scanning

2018-01-04 18:16 UTC, mbrubeck commented
I guess we wouldn't need to scan the entire flow for line breaks all at once, as long as we can store and re-use the same `LineBreakLeafIter` for all the text runs in a flow.

2018-01-05 16:58 UTC, Manishearth commented
So it seems like the problem is not actually stuff between textruns? For the testcase at hand the entire thing is a single textrun. I can make it into two text runs if I do `<span style="font-size:10px">` (which still does not break in Firefox), and I can fix that case (for some reason LineBreakLeafIter doesn't seem to help distinguish between boundary breaks and I need to figure out why that's happening first)

2018-01-05 17:35 UTC, mbrubeck commented
Ah.  So, in the original test case there is a single TextRun, but it is split into multiple Fragments, each pointing to a separate range of the TextRun.  We use `TextRun::natural_word_slices_in_range` to find breaking opportunities within the range for each fragment, but we don't check whether the start of a new fragment is a breaking opportunity or not.

For a fragment that starts in the middle of a TextRun we can check whether it starts within a GlyphRun or between GlyphRuns.  For the first fragment in a TextRun, we hit the case that I mentioned previously, and we'll need to use LineBreakLeafIter during TextRun construction to record whether a break opportunity exists between this TextRun and the previous one.

2018-01-10 12:36 UTC, Manishearth commented
> For a fragment that starts in the middle of a TextRun we can check whether it starts within a GlyphRun, or between GlyphRuns. 

I'm not clear on _where_ we'd do this. During fragment construction? Or in `scan_for_lines`?

2018-01-10 15:53 UTC, mbrubeck commented
I think we'll want to add a "can break before" flag to `ScannedTextFragmentInfo`.  We *could* determine this by doing a linear or binary search of the GlyphRuns in its TextRun, to find where the fragment boundary falls (or by looking at a similar flag stored on the TextRun, for the first fragment in a run), but it's probably more efficient to track this during text scanning and record it as each scanned text fragment is constructed.  (There might still be cases where we need to search the GlyphRuns to initialize the flag when splitting a fragment...)

2018-01-10 16:06 UTC, Manishearth commented
> I think we'll want to add a "can break before" flag to ScannedTextFragmentInfo.

Right, that's the solution for the `foo<strong>bar</strong>` case (which I've almost got working), but not the `foo<span>bar</span>` case, right?

Maybe I've misunderstood your point.

2018-01-10 16:15 UTC, Manishearth commented
Oh, wait, i see your point. Yeah, we can use the same flag for both.

2018-01-10 16:16 UTC, Manishearth commented
Though, last I checked the creation of the fragment break in `foo<span>bar</span>` was not in `flush_clump_to_list`, where I'd expect it to be. I'll recheck, but are there other places where we split such fragments?

2018-01-12 07:31 UTC, Manishearth commented
Updated code. r? @mbrubeck 

Going to try some edge cases with mixed scripts, including Arabic ZWJ-ing (e.g. `الـ iPhone`)

2018-01-12 18:10 UTC, mbrubeck commented
@bors-servo try

2018-01-12 18:10 UTC, bors-servo commented
:hourglass: Trying commit 3743be1d617da7f30721d1869c7773c305f0de1e with merge 5dc0a967e829f10903e8aec09fe0067eda4e55e9...

2018-01-12 18:15 UTC, mbrubeck requested changes

2018-01-12 18:15 UTC, mbrubeck commented on components/gfx/text/text_run.rs
> +                break_at_zero = false;
Should this be `true`?

2018-01-12 18:43 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7524)

2018-01-13 04:19 UTC, Manishearth commented on components/gfx/text/text_run.rs
> +                break_at_zero = false;
yep.

2018-01-13 04:19 UTC, Manishearth commented
@bors-servo retry try

2018-01-13 04:20 UTC, bors-servo commented
:hourglass: Trying commit 1026c8a9e9f685944f4ba8044765e22520baf27e with merge ef5e71d433452798695bffeebc4d50901e01f176...

2018-01-13 04:45 UTC, Manishearth commented
Hm, even after fixing that it doesn't seem to want to line break anymore

2018-01-13 04:51 UTC, Manishearth commented
Oh, I didn't use a different bit for the bitflag. Oops.

Also, it seems like that assertion doesn't hold on Wikipedia, probably to pass down an option there.

@bors-servo try retry

2018-01-13 04:51 UTC, bors-servo commented
:hourglass: Trying commit 0621eafab1d3e835f96a70e546fb6fb871e421e6 with merge 1056a06861c71e8650b8a1dc2d17d5b2d663a463...

2018-01-13 05:22 UTC, Manishearth commented
Ah, it's not picking up breaks at the end of the run.

2018-01-13 05:24 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7528)

2018-01-16 11:49 UTC, Manishearth commented
Okay, so this fixes it for `foo<span style=...>bar`, but not for a span that uses the same style (i.e. one in the same clump)

The reason is that while it's processed as a single text run, it gets split up into multiple bits _later_ due to the `mappings` stuff. I don't quite understand how this works, but I'm trying to figure it out.

2018-01-16 13:33 UTC, Manishearth commented
Ah, this is basically an entirely different bug, we currently have fragments that are within glyph runs, and we should either not do that or detect when it has happened and not break in that case. Currently trying the latter.

2018-01-16 13:57 UTC, Manishearth commented
I think I solved it. r? @mbrubeck

2018-01-16 13:57 UTC, Manishearth commented
@bors-servo try retry

We still have cases where we hit the assertion; I'll fix that soon.

2018-01-16 13:57 UTC, bors-servo commented
:hourglass: Trying commit ab4a6b5582324f4d371f7374e2283dbfdc4b2856 with merge 81afdec523f122e6dad6978d2e8a41eb9cc34383...

2018-01-16 14:30 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7569)

2018-01-17 09:42 UTC, Manishearth commented
@bors-servo try retry

2018-01-17 09:42 UTC, bors-servo commented
:hourglass: Trying commit 92f91f645b884aad3d03face385c3c9633a8b3de with merge b7eef5b1fba4bfb289e7bbefaa33341c3e6f30eb...

2018-01-17 10:10 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7576)

2018-01-17 12:26 UTC, Manishearth commented
@bors-servo try 

accidentally broke non-text-fragments

2018-01-17 12:26 UTC, bors-servo commented
:hourglass: Trying commit 3325d07c88e065a65a738b18878394cdec0d2fee with merge c0630f30471ca60478dbb149d2373bc573dacb27...

2018-01-17 12:43 UTC, Manishearth commented
@bors-servo try

2018-01-17 12:43 UTC, bors-servo commented
:hourglass: Trying commit 76e6b55d818b8310beb30295fcae387f53305583 with merge 1370d2ab7d49a0b9895b097a923c1fe23c9d94a2...

2018-01-17 12:49 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7579)

2018-01-17 13:08 UTC, Manishearth commented
With these fixes the following tests still fail:

```
/css/CSS2/normal-flow/inline-block-width-002b.xht;
/css/CSS2/normal-flow/inline-block-width-002a.xht;
/css/css-text/line-breaking/line-breaking-009.html;
/css/CSS2/linebox/inline-formatting-context-012.xht;
/css/css-text/line-breaking/line-breaking-011.html;
/_mozilla/css/whitespace_nowrap_line_breaking_a.html;
/css/css-text/i18n/css3-text-line-break-baspglwj-083.html;
/css/css-text/i18n/css3-text-line-break-baspglwj-094.html;
```

2018-01-17 13:32 UTC, Manishearth commented
Minimal testcase for the line-breaking-011 failure:

```
<style type="text/css">
div {
    width: 1em;
    white-space: normal;
}
span {
    white-space: pre;
}
</style>
<div>X <span>X<span></div>
```

2018-01-17 13:42 UTC, Manishearth commented
Hm, I'm not quite sure what's happening here. @mbrubeck any ideas?

2018-01-17 15:28 UTC, Manishearth commented
Actually, no. That testcase is a testcase that was always broken for us.

This wpt test is failing because of something to do with the ahem font

reduced:

```html
<style type="text/css">
div {
    width: 1em;
    font-size: 20px;
    white-space: normal;
    font-family: ahem;
}
span {
    white-space: pre;
}
</style>

<div>X&#x200B;<span>Y<span></div>
```

These work identically if not using the ahem font both before and after my change (they both show "XY"), but if you include the ahem font, we get a linebreak between the X and Y in servo master but not with these changes. I'm not sure why changing the font affects this; perhaps the clumping changed (will look into it)

Without the ahem font in Firefox these show linebreaks anyway, as was mentioned before.

2018-01-18 15:37 UTC, mbrubeck commented on components/gfx/text/text_run.rs
> +            true
I *think* this case should never be reached.  If that's correct, maybe it should panic.

2018-01-19 10:36 UTC, Manishearth commented
@bors-servo try

so of the new failures a bunch of them are the white-space issue. Some of them are the nested div issue, and one of them as far as I can tell is lack of webfont support.

I'm not sure what's going on in the div issue; should I file a bug, mark expected, and land this?

2018-01-20 16:54 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #19819) made this pull request unmergeable. Please resolve the merge conflicts.

2018-01-22 17:42 UTC, mbrubeck requested changes

2018-01-22 17:42 UTC, mbrubeck commented
> I'm not sure what's going on in the div issue; should I file a bug, mark expected, and land this?

I'm not sure what's going on either; a follow-up issue sounds good.

2018-01-23 04:57 UTC, Manishearth commented
@bors-servo try retry

2018-01-23 04:57 UTC, bors-servo commented
:hourglass: Trying commit 27c0eebe85c4d1f0745fe1aee7594809d74e7d78 with merge 36db4d19d21811d6d334f13a04bba2ba17819731...

2018-01-23 05:06 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7650)

2018-01-23 05:24 UTC, Manishearth commented
@bors-servo try retry

2018-01-23 05:24 UTC, bors-servo commented
:hourglass: Trying commit 4eaf1c78c889d3186ada8270b02b5b86913b5bc0 with merge 3ab4dfc198a2bc367eb8417bc8c2b1c3752fed6e...

2018-01-23 05:52 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3343)

2018-01-23 06:19 UTC, Manishearth commented
@bors-servo try retry

2018-01-23 06:19 UTC, bors-servo commented
:hourglass: Trying commit 178f75a591eaa26f30564803f27670403c08c8ee with merge e5e19f00095dcfa230a7dabf6732af071686d507...

2018-01-23 06:50 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7652)

2018-01-23 06:51 UTC, Manishearth commented
Oh looks like wpt no longer git adds things

@bors-servo try retry

2018-01-23 06:52 UTC, bors-servo commented
:hourglass: Trying commit 9b12b3e28997d7a3f5dd79efbe9c84d4e53627de with merge 5013488cac4815c6535d13e486733cb1f014461b...

2018-01-23 07:09 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3253)

2018-01-23 07:10 UTC, Manishearth commented
@bors-servo try retry

2018-01-23 07:10 UTC, bors-servo commented
:hourglass: Trying commit 9b12b3e28997d7a3f5dd79efbe9c84d4e53627de with merge dc0380361d59893f6460609d72af60d8310dd339...

2018-01-23 07:38 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7655)

2018-01-23 07:48 UTC, Manishearth commented
update-wpt seems to be a bit wonky

@bors-servo try retry

2018-01-23 07:48 UTC, bors-servo commented
:hourglass: Trying commit c4285ae440609e43b6d6900579cb7b760a8fb186 with merge 4d6dfd797099b0b283b6d5562efc8dcffd291905...

2018-01-23 08:18 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7656)

2018-01-23 08:44 UTC, Manishearth commented
@bors-servo try retry

unsure why it shows new failures

2018-01-23 08:44 UTC, bors-servo commented
:hourglass: Trying commit b599dea665d3082b70b7e0d4924d5283ad97889d with merge e726fd71db8fbac1f1556e69aeb7f7a205534cef...

2018-01-23 09:12 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7657)

2018-01-23 09:22 UTC, Manishearth commented
@bors-servo try retry

manually doing ini updates _sucks_

2018-01-23 09:22 UTC, bors-servo commented
:hourglass: Trying commit 9099f4fe7841455375e11e223c165a68447d9fb6 with merge 021bd9f0c955d5b8a5176d4428a921fb52cb6d80...

2018-01-23 09:49 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7658)

2018-01-23 09:56 UTC, Manishearth commented
@bors-servo try retry

typo

2018-01-23 09:57 UTC, bors-servo commented
:hourglass: Trying commit 1af5cf558b738838be8d38aab67e12f0cf2e561f with merge b4c789d39a9fba2c7093873d86d12f01a752bc83...

2018-01-23 10:30 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7644)

2018-01-23 13:45 UTC, Manishearth commented
@bors-servo try retry

2018-01-23 13:46 UTC, bors-servo commented
:hourglass: Trying commit 3c1ed326afcef70aa545e605c51db54e102939f1 with merge b7526e81dfcab84efa4fcfc923b24567d672a864...

2018-01-23 14:14 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3354)

2018-01-23 14:19 UTC, CYBAI commented
In `filtered-wpt-errorsummary.log`,

```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-normal-022.xht", "line": 3213, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-011.xht", "line": 3274, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-015.xht", "line": 3331, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-normal-024.xht", "line": 3371, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-013.xht", "line": 3443, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-017.xht", "line": 3502, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-normal-021.xht", "line": 3505, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-normal-023.xht", "line": 3635, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-012.xht", "line": 3639, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-014.xht", "line": 3699, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-016.xht", "line": 3716, "action": "test_result", "expected": "FAIL"}
```

2018-01-23 14:55 UTC, Manishearth commented
@bors-servo try retry

we need a try mode that waits for all builders and keeps posting updates or something.

2018-01-23 14:55 UTC, bors-servo commented
:hourglass: Trying commit 64c72b3c4598b5f87ccaf5367f9161fb57da2461 with merge 6d0b6d91e90531ff3eba2599bafe4bc0ff50037a...

2018-01-23 15:16 UTC, bors-servo commented
:broken_heart: Test failed - [arm64](http://build.servo.org/builders/arm64/builds/10753)

2018-01-23 15:17 UTC, Manishearth commented
@bors-servo try retry

 - infra

2018-01-23 15:17 UTC, bors-servo commented
:hourglass: Trying commit 64c72b3c4598b5f87ccaf5367f9161fb57da2461 with merge 8e5da097bfce95b8a657138d9f09479b6ccc3105...

2018-01-23 15:45 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7666)

2018-01-23 15:54 UTC, Manishearth commented
.... what. It's the same tests.

```
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-normal-022.xht 01f97645f8129e2ff870d3cb5a1359f01f74e0a6\n/css/css-text/line-break/reference/line-break-normal-022-ref.xht 60799dde0181593549207ed5ed6390df0bd3c4af\nTesting 01f97645f8129e2ff870d3cb5a1359f01f74e0a6 == 60799dde0181593549207ed5ed6390df0bd3c4af", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-normal-022.xht", "line": 27865, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-strict-015.xht 01f97645f8129e2ff870d3cb5a1359f01f74e0a6\n/css/css-text/line-break/reference/line-break-strict-015-ref.xht 60799dde0181593549207ed5ed6390df0bd3c4af\nTesting 01f97645f8129e2ff870d3cb5a1359f01f74e0a6 == 60799dde0181593549207ed5ed6390df0bd3c4af", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-015.xht", "line": 28138, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-normal-024.xht 0f100dd353a41e56987c44105b9b246607d12e1c\n/css/css-text/line-break/reference/line-break-normal-024-ref.xht 883eb8027053e5b30b4e5b8bae7cd4c7d262d202\nTesting 0f100dd353a41e56987c44105b9b246607d12e1c == 883eb8027053e5b30b4e5b8bae7cd4c7d262d202", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-normal-024.xht", "line": 28766, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-strict-016.xht 2cfd615404e54e6b8f67b8b84b22827c116a7840\n/css/css-text/line-break/reference/line-break-strict-016-ref.xht 32695efb3c89bab8a3e8e5e7b5cd9116c6f39224\nTesting 2cfd615404e54e6b8f67b8b84b22827c116a7840 == 32695efb3c89bab8a3e8e5e7b5cd9116c6f39224", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-016.xht", "line": 28995, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-strict-013.xht 2664ad19645dc943fb70003a931df11972d61fbc\n/css/css-text/line-break/reference/line-break-strict-013-ref.xht 3c0df9336f3a81b43c998b291e1869a0a48a25e3\nTesting 2664ad19645dc943fb70003a931df11972d61fbc == 3c0df9336f3a81b43c998b291e1869a0a48a25e3", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-013.xht", "line": 29061, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-normal-021.xht 5c74ed954a4b832c20d2126254ddae2c2ce97822\n/css/css-text/line-break/reference/line-break-normal-021-ref.xht 4546f42e9f37578425acbd9902fed4ec3a2c6c47\nTesting 5c74ed954a4b832c20d2126254ddae2c2ce97822 == 4546f42e9f37578425acbd9902fed4ec3a2c6c47", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-normal-021.xht", "line": 29314, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-strict-012.xht 7acf572170d004196a1261f05ca4334240554a30\n/css/css-text/line-break/reference/line-break-strict-012-ref.xht 87c3e560195991abc3cb9d02729a9b47501cd05b\nTesting 7acf572170d004196a1261f05ca4334240554a30 == 87c3e560195991abc3cb9d02729a9b47501cd05b", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-012.xht", "line": 29407, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-strict-017.xht 0f100dd353a41e56987c44105b9b246607d12e1c\n/css/css-text/line-break/reference/line-break-strict-017-ref.xht 883eb8027053e5b30b4e5b8bae7cd4c7d262d202\nTesting 0f100dd353a41e56987c44105b9b246607d12e1c == 883eb8027053e5b30b4e5b8bae7cd4c7d262d202", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-017.xht", "line": 30178, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-normal-023.xht 2cfd615404e54e6b8f67b8b84b22827c116a7840\n/css/css-text/line-break/reference/line-break-normal-023-ref.xht 32695efb3c89bab8a3e8e5e7b5cd9116c6f39224\nTesting 2cfd615404e54e6b8f67b8b84b22827c116a7840 == 32695efb3c89bab8a3e8e5e7b5cd9116c6f39224", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-normal-023.xht", "line": 46648, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-strict-014.xht 5c74ed954a4b832c20d2126254ddae2c2ce97822\n/css/css-text/line-break/reference/line-break-strict-014-ref.xht 4546f42e9f37578425acbd9902fed4ec3a2c6c47\nTesting 5c74ed954a4b832c20d2126254ddae2c2ce97822 == 4546f42e9f37578425acbd9902fed4ec3a2c6c47", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-014.xht", "line": 46723, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/line-break/line-break-strict-011.xht 5c74ed954a4b832c20d2126254ddae2c2ce97822\n/css/css-text/line-break/reference/line-break-strict-011-ref.xht 4546f42e9f37578425acbd9902fed4ec3a2c6c47\nTesting 5c74ed954a4b832c20d2126254ddae2c2ce97822 == 4546f42e9f37578425acbd9902fed4ec3a2c6c47", "stack": null, "subtest": null, "test": "/css/css-text/line-break/line-break-strict-011.xht", "line": 46742, "action": "test_result", "expected": "PASS"}
```

2018-01-23 15:55 UTC, Manishearth commented
@mbrubeck ... any idea what's happening here?

2018-01-23 15:56 UTC, Manishearth commented
They all seem to use WOFF webfonts -- do we support them? If so, are there platform distinctions between the two?

2018-01-24 05:42 UTC, Manishearth commented
So on my macbook stuff seems to be working. The font is loading correctly, and the test passes.

On my Linux box it fails; looking at the analyzer the font didn't load at all, showing tofu (which probably broke the linebreaking behavior). Reftest-analyzer compatible log below:

<details>
```
REFTEST   IMAGE 1 (TEST): data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAAJYCAIAAAAVFBUnAAAge0lEQVR4nO3dC3JcWW4t0KdB2EPzKHoOCs2h51tvM+CA4PvJpNSgPsy1HAI3cE4mk7zVVYgOV/SXf/755/8BALDHggUAsMyCBQCwzIIFALDMggUAsMyCBQCwzIIFALDMggUAsMyCBQCwzIIFALDMggUAsMyCBQCwzIIFALDMggUAfnaWWbAAAJZZsAAAllmwAACWWbAAAJZZsAAAlt0uWF++fEm9dPeSzy2/kPmDp00tc36pLj+99tjjN8np3dGUa6nnmzWPeZThbO/kWup7br5fvWf80NvWq37oJX+j/Ji//WfMZ0j90I+Rb7H4/nm31LL4tr9S/wh/6ef/afWDv9pP/XF2f595t623+mn5DKnx2z/Jwe2vJp+4j5JTq02u8KN++oV/gnz41Pn5M6m2w3Qenic/4e5NMk+9PDrL5bub8yg5tdvHcvnu5oOjx/LC1B99bV71oy9Z9Au+e75F6kd/l/fIJ/m4j5E3T118/7xhvVuHj/Chb15+wbf4aE9/hPOF8+SP9Vd81K0PmfdJXXmrS3n/97/5D13+NW4/0PysyanVJlf4UT/9wj/T4x/nfHqe/ISPfpMHR489eOGDo8fywtQffW1e9aMvWfR7v/sv9nf9sL/m0/6C7/ILvsVHe/ojnC+cJ3+sv+Kj/hUfMn7oc/7Q5V/jXR8onzv18maO3jk/T+5c3rwclsujy2H86PzO4/vn0550OLibT32nwwN3d3reoZ0nB3cXet6hnSfl6TwhtfKd3Dlc6EmH6XI4HS4c2oPz6XlS7ublcHpo3++dL7y7djcv59OedHjq8ubl8IGn9y8vXA7PztfOk3Y+Ok/icjhdXrgcxuX8chh38+npnfOF8+TS3bW7eTtf6EmHg7v52ftvlsf3z6fnydnlncvhNC/MfPDgqPWdDgd38/L49IHHLzyfnidxOYy7+W/0rg+Uz516uNnDDqnR7SG0TFKn84VMUpMjOTVth9TSkw6pnTukRrcdUqPbDqkHh6NqSw/LPIo+vZtHHWXSIfVSXWh9s+bdRk0O6sLhqIYlR90mp3YbNTmoC4ejB8OoedoOqaUm0zyd6mZOO6RGte0wT9shtdRkymkNZ0htPTyElklq1Dxth9SodspRDWdIPTgcVTv10VldzoUOqdFth9TWww6pUW3r+XS+k0lqciSnpu2QWg6Taqc+mupajjqkRrWlh22elrpT8+QOqaUnh9AySa1hcofUUpPp8WnUhRxVKGlTM+mQGt12SD3oow6ppSZTndY8uUPqWZ92SI1qW8/b3YW7edRRJh1SL/WFDqmVSybddp4htfXwEFomqQd1J0cdUjt3SC01mXI6h2lTS80z6ZB6qS60ebOOMumQGtVOOaphQmpUOx2O0nZIjWqnOjrM5zC5Q2rL8DD57d71gfK5U+fNwyTtD+VLhwvddiizvcwdonNCauVI+zQfHI4O7cH5dE6SU6udOdJ2PpunyamznTn1QTtz6mw7x2yTUx+0M6fOtnOkTe1J2plT79rpcJT2LqdWm1yhPGgrV01bZpucOtvLHGlTe5K2c8y2ctW0MfPB4Wi2yandToejtJc5ZpucOtu7nNrtQU7nUbcdyvvbmVuGqT1P2zkO7cE8rZyanJAaaWdOne1ljve3yanVzhzndubU2T7N02H+oK2cmpyQGmk7HxyOHrdn5wtzkpxa7cyRtvNBjlL7NG3n6LZDzByzTU6d7WU+m6edO5QHbXLqbGdOnW3ns3manFrtzJG2c8y2c4d4kFNn2zlmm5w6287xQ+2f4F0fKJ87dd7M5NCm1mTmKfPzcDpcOLRtzpNTuy13wzlJm1qTmR/ItXnn0B6cT+ckObXa5AolbeqcTDnto+TU2V7mSJvak7Qzp862c8x25kib2pO0M6fOtnOc29SaJFcoaVPnpOXoch7zKDm12ylHc35oz+aFmQ8OR+c2tSdpO5dMUg/Ds1ybd2abnNrtlKM5T5s6Jy1HPZ/5YB4lp3Z7kNN5dGjbYf64PTtcSJvak7Sdz86nh0na1JokVzh7cBSH09kmp1abXKGkTe1J2sscaVNrMvM75SXz/qGNwyRt6pzcyc157dCenS/MSXJqtckVStrUOWk5mvO0qT2pNnpyljt9OvPBg6PIaeqDC5E788Jsk1Nne5kjbeqcTDnto+TUapMrlLSpPUnbub1neG5Te5J25tTZdj47nB7aP8G7PlA+d+q8WZODvtCnPYkMZ3t2uDDb5NTW8+ijx8OeTOfTnpzlzjw9tAfn0zlJTq228kEdneVyHyWnzvYyR9rUnqSdOXW2nWO2M0fa1J6knTl1tp0jbepBXchRhZI2dU5aji7nMY+SUw9t63nkaLYlw9TWFzLvfHA4Spt60Bdy2rllmBrno5Y783S2yandTnV00DcPp3Pe+WAeJad2e5DTeTTb5NTW88jRg/bscCFtak/Sdj47n2aSelB3clTh7HyUSWqbpznqNjm12uQKJW1qT9LOnHpwPu3JWd8p82aOZhuZpB4c7rTD5XktR7M9O1+Yk+TUaisf1NHB05t1YU6ihq1PM+988OCo5EJqzGs9LIejbpNTZztz6kGfHuRyHyWnVptcoaRN7Unazu08zCR1DjM5tKk9STtz6mw7l0xS2zzN0Wz/BO/6QPncqfNmJrO9lDupfS1t50uHC912KIe2ZJh6mM9hcoUHcif17lpO59GhPTifzklyarXJFd5jXk5One1ljrSpPUk7c+psO8dsZ460qT1JO3PqbDvHoZ0OR2lT56Tl6HKeNI+SU6tNrlAet3GYzHbmg8PRoT14cJqj1Aen82i2yandTjm6nMfhaLYzH8yj5NRuD3I6j7rtUH6oPTtcSJvak7Sdz86n50l7/9H72+TUapMrlLSpPUl7me/kTurltRzN+eM2zpM7h5uP27PzhTlJTq02ucJTT2/mQuq8k8ldO/PBg6Mp11LrZnKF8qBNTp3tZX5qXk5OrTa5Qkmb2pO0ndt5+HSSNrUnaWdOnW3n+KH2T/CuD5TPnTpvZjLbOE8iw9SaJ1e4c7jQbYdyaFvmqYejHiakJrfzJDJMPc8jR3N+aA/Op3OSnFptcoV2nrR5lJw628scaVN7knbm1Nl2jtnOHGlTe5J25tTZdo5DGz3pUNKmzknL0ZzP9pBTq02uUB63cZjMduaY7cxxaGNOZj7LaerlhRzN+WyTU7udcnSY96RDme3MMdtDTu32IKfzqNsO5Yfas8OFtKk9Sdv57Hz6YNKhzHbmeH+bnFptcoWSNrUnaS9zOU8iw9TL+Rw+buM9k3KYP27PzhfmJDm12uQK7Twp5/mcVE5NTkiNtJ1jtjPHbGd+LDdTczkhNbk8aJNTZ3uZy3nS5lFyarXJFUra1J6k7dwOw0NbDsO0qT1JO3PqbDvHD7V/gnd9oHzu1HnzMEl7l1OrTT6EgzlPTq02uUIkp8525tS0CanJkZyatkNqpL3Lqd1OOZrzQ3vQp+cQyanVzhxpO5/N0+TU2c6c+qCdOXW2nWO2yakP2plTZ1u5QmpyQmqknTn1rp0OR2nvcmq1yRUiObXbyGS2MSfJqQ/ac66QmpyQGmk7x6GNOUlO7XbK0ZzPNjm12+lwlPYupz5o73Jqtwc57aPk1GqTK0RyareRyYP2LBdS+07aznFoD86nmaT2MO3MqbM95wpV00ZyareRSbfJqdXOHOd25tTZ3uXUblvmPUxO7TYymW1kktrDtJ0P5lFyareRSbUdDnp+DpGcWu3MkbbzQY5S+zRt5+g2IbVzhUhOfdCec4dpDpNT0yakJkdyareRSbfJqbOdOXW2nc/maXJqtTNH2s5xaMscJqfOtnJCauVI2zlmm5w628oVqqaN5NRuI5PZ/gmef6B86NQyL8959NHTeU8O+kLpa3OeYbUJqZXbg2H86HzqO3XabdTkoC/U6Ww7R9rUOYkanvW1XOgcs01OjZ60Oup52s4HOUrt02qjJ62Oep62c6RN7Um10ZPS8zgclXmhzZt9oYeZdI67NiG1cqlJHIbVJqRGtaWH0fMe9qRczi+H0fOp79TpbDtH2tSDeSH6zpxnWG1CalRbzsNMOkfa1IN5IfrOnGdYbUJq5Ti0UZNLd9fu5uXudM7j7uhyXsNuI5NqE1IrR9rOkTZ1Tkrmc5g2NeYwns6neScXqk1IrVxqUuY85tE0r+VOtQmpUW305OBwYbadI23qnEQNL13e7GHaznHXJqRGtaWH0fM5bH1a6s4cZlJtQmrlSNs5ZpucGj0pPT/oa7nQOdKmniflct7DmnTbah7zqIfR8ww7R9rUnhzayKTaDiVt6h/i+YL1y+R39Od8mM8kv9jU3d/tR7wnn1X+avGXyk/Lby/VLxD+On/Q3/jy95E/58P81Q6/yUP7cw5vcmjhAX+1/JDDr+vQAn+LP+I/uvk7SGr5Ez7P365+n/WbnPk/Md9nZnig/lIp/oJ5p/ql1a9rZuDv8kcsWHyEj/hb80e8J3DmP2vwt7NgAQAss2ABACyzYAEALPt1C9aXZ/8uzNMLAAB/hV+002R5Sp3fK5NDmzonAAB/qf+z5fxK2ah+17cGAPjQy+/dcu72oR+dt6cXyuNrj08BAH6L2wUlu0tqy7VMUpNL2tRMOqRGtx1Sz7nNYeXSkw6pUe3URwAAf4L/szOdZZuZF7pNSK0caX8ox6GNOUlOnW3nmG1yarcAAL/d903lUtaXeaHbDiVtak1mnjKfw0MbczJzpE3tSdqZU7sFAPjtvm8ql7K+zAvddihpU3tSbfQkMnzQxpzMHGlTe5J25tRuAQB+u++byqWsL/NCtx1K2tQ5icMwbec4tDEnM0fa1J6knTm1WwCA3+77pnIp68u80G2HkjZ1TsqcJ1cohzbmZOZIm9qTtDOndgsA8Nt931QuZX3pC8mp1c4cae9yarXJFUq35xDJqbPtHLNNTp1tZwCA3+LJOpJ9JbXNy/Pobh511MNq4zA5tNGT6GH0PMPO0W1CKgDA7/J8wXp8AQCAgyf7kwULAOBH3e5PWa1Sy90dAADObhcsAAB+jgULAB8BllmwAACWWbAAAJZZsAAAllmwAACWWbAAAJZZsAAAllmwAACWWbAAAJZZsAAAllmwAACWWbAAAJZZsAAAllmwAACWWbDAjwLAstsF69u3b6l8bl+/fk0FAHY9WrD80/f9vuTPQ//kzx/GIwaAD2LB2mHBAgCaBWuHBQsAaBasHRYsAKA9WbC+3CwO9SKnJac3J9/lDR68PD7u9E494gQAYNfzBet83sMOUw87TD3sMPWww9TDDlMPO0w97DD1sMPUww5TDW82nO/yurp50MMOUw87TD3sMF0Op3rECQDALgvWmx52mHrYYaqhBQsAaBasNz3sMPWww1RDCxYA0CxYb3rYYephh6mGFiwAoFmw3vSww9TDDlMNLVgAQLNgvelhh6mHHaYaWrAAgGbBetPDDlMPO0w1tGABgK/NgvWmhx2mHnaYamjBAgCaBetNDztMPeww1fB/F6x8mRdGm69186CHHaYedph62GG6HE71iBMAgF0WrDc97DD1sMNUw6xSb/JlXhhtvtbNgx52mHrYYephh+lyONUjTgAAdlmw3vSww9TDDlMNs0o9ltfVzYMedph62GHqYYfpcjjVI04AAHZZsN70sMPUww5TDS1YAEB7vmBdqhc5LTm9Ofkub/Dg5fFxp3fqEScAALueLFgJvMfNhvPdP/nzh/GIAeCDWLBel0cMAB/EgvW6PGIA+CAWrNflEQPAB7FgvS6PGAA+yJMF6+f+9TT+CvWIEwCAXc8XrPP55ZC/Tj3iBABglwXrddUjTgBEYJcF63XVI04AAHZZsF5XPeIEAGCXBet11SNOAAB2WbBeVz3iBABglwXrddUjTgAAdlmwXlc94gQAYJcF63XVI04AAHZZsF5XPeIEAGCXBet11SNOAAB2WbBeVz3iBABg1/MF69LNi/ib1CNOAAB2PVmwEvisPGIA+CCPFqxUPjcLFgB8hNsFC3wrAPg5FiwAgGUWLACAZRYsAIBlFiwAgGUWLACAZRYsAIBlFiwAgGUWLACAZRYsAIBlFiwAgGUWLACAZRYsAIBlFiwAwFsts2ABACyzYAEALLtdsL59+5bK5/b169dUAGDXowXLP30/N48YAD6IBet1ecQA8EEsWK/LIwaAD/JkwfryJfFCvejVTj+ZesQJAMCu5wvW+byHHaYedph62GHqYYephx2mHnaYethh6mGH6XL4CdQjTgAAdlmw3vSww3Q5/ATqEScAALssWG962GG6HH4C9YgTAIBdFqw3PewwXQ4/gXrECQDALgvWmx52mC6Hn0A94gQAYJcF600PO0yXw0+gHnECALDLgvWmhx2my+EnUI84AfCZgF0WrDc97DBdDj+BesQJAMAuC9abHnaYLoefQD3iBABglwXrTQ87TJfDT6AecQIAsMuC9aaHHabL4SdQjzgBANhlwXrTww7T5fATqEecAADser5gXaoXvdrpJ1OPOAEA2PVkwUrgs/KIAeCD/PyCdfPf9Xz3T/7wB3v6iAGAn2PBel1PHzEA8HMsWK/r6SMGAH6OBet1PX3EAMDPebJgPfi36m5Ovsv7Pnh5/K5TSj3iBABg1/MF63xew5sd5ru8rm4e9LDD1MMOUw87TD3sMF0OX1k94gQAYJcF63V9+/b2iD/hDwYAv5sF63XVI04AAHZZsF5XPeIEAGCXBet11SNOAAB2WbBeVz3iBABglwXrddUjTgAAdlmwXlc94gQAYNd/vGDly7ww2nytmwc97DD1sMPUww5TDztMl8NXVo84AQDYZcF6XfWIEwCAXf/xgnUvr6ubBz3sMPWww9TDDlMPO0yXw1dWjzgBANhlwXpd9YgTAIBdzxesS3nRzcl3ed8HL4/fdUqpR5wAAOx6smAl3LnZYb77J3/4gz19xADAz3m0YKXyuVmwAPDjfITbBQsAgJ9jwQIAWGbBAgBYZsECAFhmwQIAWGbBAgBYZsECAFhmwQIAWGbBAgBYZsECAFhmwQIAWGbBAgBYZsECAFhmwQKcACyzYAEALLNgAQAsu12w/ud//icVAIBL//3f//3vf/874ex2wfrXv/71X//1XwkAAFz6+vVr6tntggUAwM+xYAEALLNgAQAss2ABACyzYAEALLNgAQAss2ABACyzYAEALLNgAQAss2D5DgDAMgsWAMAyCxYAwDILFgDAMgsWAMAyCxYAwDILFgDAstsF69u3b6l8bl+/fk0FAHY9WrD80/f9vuTPj/gnf343jxgAPogFa4cFCwBoFqwdFiwAoFmwdliwAID2ZMH6crM41IuclpzenNzK+z14t/i401aPOAEA2PV8wTqf97DD1MMOUw87TD3sMPWww9TDDlMPO0w97DD1sMNUw5uV5lbepl540MMOUw87TD3sMJ2H9YgTAPDe7LJgvelhh6mHHaYaWrAAgGbBetPDDlMPO0w1tGABAM2C9aaHHaYedphqaMECAJoF600PO0w97DDV0IIFADQL1psedph62GGqoQULAGgWrDc97DD1sMNUQwsWANAsWG962GHqYYephhYsAKBZsN70sMPUww5TDf93wcqXeeG+zdd64UEPO0w97DD1sMN0HtY [...]

2018-01-24 05:46 UTC, Manishearth commented
@bors-servo try retry

2018-01-24 05:47 UTC, bors-servo commented
:hourglass: Trying commit 971b3af5c20b6101a6feec74c234a515b0c0032c with merge a294e9dffe13c117b6c9bba6cfed6ef7560c0d4c...

2018-01-24 06:28 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7538)

2018-01-24 06:30 UTC, CYBAI commented
```
{"status": "FAIL", "group": "default", "message": "/css/css-text/i18n/css3-text-line-break-jazh-159.html 99d8c261669d518d91bb1f898e098c9e186f52de\n/css/css-text/i18n/reference/css3-text-line-break-jazh-159-ref.html 3b23355891fc5045a1e8afce20b3a7c09b1273d3\nTesting 99d8c261669d518d91bb1f898e098c9e186f52de == 3b23355891fc5045a1e8afce20b3a7c09b1273d3", "stack": null, "subtest": null, "test": "/css/css-text/i18n/css3-text-line-break-jazh-159.html", "line": 16662, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/i18n/css3-text-line-break-jazh-377.html 99d8c261669d518d91bb1f898e098c9e186f52de\n/css/css-text/i18n/reference/css3-text-line-break-jazh-377-ref.html 3b23355891fc5045a1e8afce20b3a7c09b1273d3\nTesting 99d8c261669d518d91bb1f898e098c9e186f52de == 3b23355891fc5045a1e8afce20b3a7c09b1273d3", "stack": null, "subtest": null, "test": "/css/css-text/i18n/css3-text-line-break-jazh-377.html", "line": 17145, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-text/i18n/css3-text-line-break-opclns-005.html 7baaeaf81d4fd78a690fef3d39084f6e5c38253a\n/css/css-text/i18n/reference/css3-text-line-break-opclns-005-ref.html e5aea6686a375a3b8c93183e3977b50fd69f0142\nTesting 7baaeaf81d4fd78a690fef3d39084f6e5c38253a == e5aea6686a375a3b8c93183e3977b50fd69f0142", "stack": null, "subtest": null, "test": "/css/css-text/i18n/css3-text-line-break-opclns-005.html", "line": 18149, "action": "test_result", "expected": "PASS"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-text/i18n/css3-text-line-break-opclns-006.html", "line": 18498, "action": "test_result", "expected": "FAIL"}
```

2018-01-24 06:37 UTC, Manishearth commented
@bors-servo try retry

2018-01-24 06:37 UTC, bors-servo commented
:hourglass: Trying commit 4bcca6dd7ec87f7abf67cecf232223d58c4f6bd1 with merge b58c6be90b2f520678d0fad3ee5061a5d92a5967...

2018-01-24 07:19 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10500), [arm32](http://build.servo.org/builders/arm32/builds/10742), [arm64](http://build.servo.org/builders/arm64/builds/10764), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10795), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7661), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7677), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10873), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3273), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3294), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7539), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7607), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3367), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3314), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6177)
State: approved= try=True

2018-01-24 07:20 UTC, Manishearth commented
😮 😮 😮 😮 😮 😮 😮 😮 

r? @mbrubeck

2018-01-24 07:23 UTC, Manishearth commented
The main followups to do are handling split `pre` and also removing the binary search

2018-01-24 13:54 UTC, Manishearth commented
@bors-servo try retry

ensuring the split fix doesn't break anything

2018-01-24 13:54 UTC, bors-servo commented
:hourglass: Trying commit fc97f0b4640c0aa8ae7368a02ba5ce2b455261e7 with merge 3233401f855f78ef35bdfbe656a921d41ed814c9...

2018-01-24 14:03 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/10502)

2018-01-24 14:11 UTC, Manishearth commented
@bors-servo try retry


 - infra

2018-01-24 14:11 UTC, bors-servo commented
:hourglass: Trying commit fc97f0b4640c0aa8ae7368a02ba5ce2b455261e7 with merge 2e7eb94daec2b268008f639f3b81b5f59c6e5f5b...

2018-01-24 16:23 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10505), [arm32](http://build.servo.org/builders/arm32/builds/10747), [arm64](http://build.servo.org/builders/arm64/builds/10770), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10799), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7665), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7682), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10877), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3276), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3300), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7542), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7612), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3372), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3319), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6181)
State: approved= try=True

2018-01-24 22:53 UTC, mbrubeck commented
@bors-servo r+

2018-01-24 22:53 UTC, bors-servo commented
:pushpin: Commit fc97f0b has been approved by `mbrubeck`

<!-- @bors-servo r=mbrubeck fc97f0b4640c0aa8ae7368a02ba5ce2b455261e7 -->

2018-01-25 00:03 UTC, bors-servo commented
:hourglass: Testing commit fc97f0b4640c0aa8ae7368a02ba5ce2b455261e7 with merge c63b94b4d3d99ee9f817905754358301bdf1baaf...

2018-01-25 00:33 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7675)

2018-01-25 03:03 UTC, Manishearth commented
Nothing changed between this and the try, so it's an intermittent. Had a quick look and doesn't seem related, but might investigate further if it keeps cropping up.

@bors-servo retry

2018-01-25 03:03 UTC, bors-servo commented
:hourglass: Testing commit fc97f0b4640c0aa8ae7368a02ba5ce2b455261e7 with merge e53663e34e9cfca661241b8a5aec041bc1fdd735...

2018-01-25 03:20 UTC, bors-servo commented
:broken_heart: Test failed - [arm64](http://build.servo.org/builders/arm64/builds/10787)

2018-01-25 03:23 UTC, Manishearth commented
@bors-servo retry

 - infra, "unable to read response"

2018-01-25 03:36 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/10519), [arm32](http://build.servo.org/builders/arm32/builds/10761), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10813), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7679), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10889) are reusable. Rebuilding only [arm64](http://build.servo.org/builders/arm64/builds/10787), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7696), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3287), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3310), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7553), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7623), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3384), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3330), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6195)...

2018-01-25 03:52 UTC, bors-servo commented
:broken_heart: Test failed - [arm64](http://build.servo.org/builders/arm64/builds/10789)

2018-01-25 04:04 UTC, Manishearth commented
arm64 is permafail on

```
error: failed to execute compile
caused by: error reading compile response from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
error: Could not compile `script`.
```

for both this PR and another. Trying to ssh and fix

2018-01-25 04:09 UTC, Manishearth commented
@bors-servo retry try-

(rehighstated the builder, cleaned up processes)

2018-01-25 04:43 UTC, bors-servo commented
:hourglass: Testing commit fc97f0b4640c0aa8ae7368a02ba5ce2b455261e7 with merge 9c1307307575637f5ad360413c6a8395579ab511...

2018-01-25 05:57 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10521), [arm32](http://build.servo.org/builders/arm32/builds/10763), [arm64](http://build.servo.org/builders/arm64/builds/10791), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10815), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7681), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7698), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10891), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3289), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3312), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7555), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7625), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3386), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3332), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6197)
Approved by: mbrubeck
Pushing 9c1307307575637f5ad360413c6a8395579ab511 to master...

2018-01-25 05:57 UTC, merged

2018-01-25 05:58 UTC, Manishearth commented
Yay! Will Mark the intermittent and file follow-ups when I get back

On Jan 25, 2018 11:27 AM, "bors-servo" <notifications@github.com> wrote:

> ☀️ Test successful - android
> <http://build.servo.org/builders/android/builds/10521>, arm32
> <http://build.servo.org/builders/arm32/builds/10763>, arm64
> <http://build.servo.org/builders/arm64/builds/10791>, linux-dev
> <http://build.servo.org/builders/linux-dev/builds/10815>, linux-rel-css
> <http://build.servo.org/builders/linux-rel-css/builds/7681>, linux-rel-wpt
> <http://build.servo.org/builders/linux-rel-wpt/builds/7698>, mac-dev-unit
> <http://build.servo.org/builders/mac-dev-unit/builds/10891>, mac-rel-css1
> <http://build.servo.org/builders/mac-rel-css1/builds/3289>, mac-rel-css2
> <http://build.servo.org/builders/mac-rel-css2/builds/3312>, mac-rel-wpt1
> <http://build.servo.org/builders/mac-rel-wpt1/builds/7555>, mac-rel-wpt2
> <http://build.servo.org/builders/mac-rel-wpt2/builds/7625>, mac-rel-wpt3
> <http://build.servo.org/builders/mac-rel-wpt3/builds/3386>, mac-rel-wpt4
> <http://build.servo.org/builders/mac-rel-wpt4/builds/3332>,
> windows-msvc-dev
> <http://build.servo.org/builders/windows-msvc-dev/builds/6197>
> Approved by: mbrubeck
> Pushing 9c13073
> <https://github.com/servo/servo/commit/9c1307307575637f5ad360413c6a8395579ab511>
> to master...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/servo/servo/pull/19688#issuecomment-360369192>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABivSKZESIuGsrHfDpWQwWTmR7sH95g1ks5tOBfagaJpZM4RTB9X>
> .
>

2018-01-25 11:02 UTC, Manishearth commented
followups : https://github.com/servo/servo/issues/19862  , https://github.com/servo/servo/issues/19863