style: Implement GeckoElement::assigned_slot.
servo/servo pull request #19721
Opened 2018-01-08 10:34 UTC by emilio

This allows to selector-match ::slotted, though we still don't parse it.

Bug: 1425755
Reviewed-by: heycam
MozReview-Commit-ID: ItELHkf2PMl

2018-01-08 10:34 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/gecko/generated/bindings.rs, components/style/gecko/wrapper.rs, components/style/gecko/generated/atom_macro.rs, components/style/invalidation/element/element_wrapper.rs, components/style/gecko/generated/structs.rs
 * @canaltinova: components/style/gecko/generated/bindings.rs, components/style/gecko/wrapper.rs, components/style/gecko/generated/atom_macro.rs, components/style/invalidation/element/element_wrapper.rs, components/style/gecko/generated/structs.rs

2018-01-08 10:34 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify style code, but no tests are modified. Please consider adding a test!

2018-01-08 10:34 UTC, emilio commented
@bors-servo r=heycam p=1

2018-01-08 10:34 UTC, bors-servo commented
:pushpin: Commit 9079f65 has been approved by `heycam`

<!-- @bors-servo r=heycam 9079f65b0028f1f46359d3815eb6e5509aecea9b -->

2018-01-08 10:35 UTC, bors-servo commented
:hourglass: Testing commit 9079f65b0028f1f46359d3815eb6e5509aecea9b with merge 567a1bb21b597c736c5b64b7ac74c5e0e6155459...

2018-01-08 10:52 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3101)

2018-01-08 10:55 UTC, emilio commented
@bors-servo retry

 * Gecko-media build fail

2018-01-08 11:25 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/10309), [arm32](http://build.servo.org/builders/arm32/builds/10544), [arm64](http://build.servo.org/builders/arm64/builds/10571), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10596), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7466), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10670), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7411), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3169), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3121), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5970) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7450), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3083), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3101), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7351)...

2018-01-08 12:07 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3103)

2018-01-08 12:34 UTC, emilio commented
@bors-servo r=heycam

2018-01-08 12:34 UTC, bors-servo commented
:pushpin: Commit 8347875 has been approved by `heycam`

<!-- @bors-servo r=heycam 83478758dea454824fd5f5d0cf76ccdca91f848c -->

2018-01-08 12:46 UTC, bors-servo commented
:hourglass: Testing commit 83478758dea454824fd5f5d0cf76ccdca91f848c with merge e9dade4cb322460f705ca84ed4ff4d5f61686c93...

2018-01-08 12:51 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7468)

2018-01-08 14:09 UTC, tigercosmos commented
```
error: no rules expected the token `"slot"`
   --> components/style/dom.rs:424:48
    |
424 |         self.get_local_name() == &*local_name!("slot") &&
    |                                                ^^^^^^
```

2018-01-08 14:13 UTC, CYBAI commented
@tigercosmos No worries, I think it will be fixed soon lol

2018-01-08 14:13 UTC, nox commented
I published markup5ever 0.7.1, now we just need to bump it in this PR.

2018-01-08 18:01 UTC, emilio commented
@bors-servo r=heycam

2018-01-08 18:01 UTC, bors-servo commented
:pushpin: Commit 59a3d2f has been approved by `heycam`

<!-- @bors-servo r=heycam 59a3d2f1ec6260cfd3f7af9ba22c8c74d3d81706 -->

2018-01-08 18:01 UTC, bors-servo commented
:pushpin: Commit 96cb7cf has been approved by `heycam`

<!-- @bors-servo r=heycam 96cb7cff68a6fe9c13fe6377333a421aefc82a81 -->

2018-01-08 18:19 UTC, bors-servo commented
:hourglass: Testing commit 96cb7cff68a6fe9c13fe6377333a421aefc82a81 with merge 55ea8e74a079be72e7fcf9fa8f00c861d7693910...

2018-01-08 18:30 UTC, bors-servo commented
:broken_heart: Test failed - [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10674)

2018-01-08 18:33 UTC, jdm commented
```
error[E0046]: not all trait items implemented, missing: `is_html_element`
   --> components/layout_thread/dom_wrapper.rs:352:1
    |
352 | / impl<'le> TElement for ServoLayoutElement<'le> {
353 | |     type ConcreteNode = ServoLayoutNode<'le>;
354 | |     type TraversalChildrenIterator = DomChildren<Self::ConcreteNode>;
355 | |
...   |
534 | |     }
535 | | }
    | |_^ missing `is_html_element` in implementation
    |
    = note: `is_html_element` from trait: `fn(&Self) -> bool`

error: aborting due to previous error

error: Could not compile `layout_thread`.

```

2018-01-08 19:16 UTC, emilio commented
@bors-servo r=heycam

2018-01-08 19:16 UTC, bors-servo commented
:pushpin: Commit 93f7647 has been approved by `heycam`

<!-- @bors-servo r=heycam 93f764739b8e2a83d487a6bd7669193d1716129d -->

2018-01-08 19:16 UTC, bors-servo commented
:hourglass: Testing commit 93f764739b8e2a83d487a6bd7669193d1716129d with merge f7fd262956c9fb400a4d1d025ef0fda98fceb7a6...

2018-01-08 19:47 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7472)

2018-01-08 22:19 UTC, jdm commented
@bors-servo retry
Let's see if it was an isolated problem.

2018-01-08 22:19 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/10315), [arm32](http://build.servo.org/builders/arm32/builds/10550), [arm64](http://build.servo.org/builders/arm64/builds/10577), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10602), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10676), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3089), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3108), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7357), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7417), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3176), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3127), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5976) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7456), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7472)...

2018-01-08 22:50 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7474)

2018-01-09 00:45 UTC, jdm requested changes

2018-01-09 00:45 UTC, jdm commented on ports/glutin/Cargo.toml
> +# osmesa-src = {git = "https://github.com/servo/osmesa-src"}
This change is causing the errors with loading OSMesa during testing.

2018-01-09 08:32 UTC, emilio commented
Welp, I should really really update osmesa :)

@bors-servo r=heycam

2018-01-09 08:32 UTC, bors-servo commented
:pushpin: Commit 26cd599 has been approved by `heycam`

<!-- @bors-servo r=heycam 26cd5997ff4a1ca9772c5659d04508799580fba3 -->

2018-01-09 08:32 UTC, bors-servo commented
:hourglass: Testing commit 26cd5997ff4a1ca9772c5659d04508799580fba3 with merge b71f6944c427568ba4e24eae7e07faff60b0ded3...

2018-01-09 09:41 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7468)

2018-01-09 10:31 UTC, emilio commented
@bors-servo retry

2018-01-09 10:31 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/10324), [arm32](http://build.servo.org/builders/arm32/builds/10560), [arm64](http://build.servo.org/builders/arm64/builds/10587), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10612), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10688), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3098), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3117), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7367), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7427), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3187), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3136), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5986) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7468), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7483)...

2018-01-09 11:12 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7484)

2018-01-09 11:29 UTC, emilio commented
@bors-servo retry

 * Timeouts look flaky.

2018-01-09 11:29 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/10324), [arm32](http://build.servo.org/builders/arm32/builds/10560), [arm64](http://build.servo.org/builders/arm64/builds/10587), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10612), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10688), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3098), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3117), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7367), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7427), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3187), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3136), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5986) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7469), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7484)...

2018-01-09 12:05 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7485)

2018-01-09 13:16 UTC, emilio commented
@bors-servo r=heycam

2018-01-09 13:16 UTC, bors-servo commented
:pushpin: Commit 504667d has been approved by `heycam`

<!-- @bors-servo r=heycam 504667d8968f1a66f1e5f145ee1d530a79d619cb -->

2018-01-09 13:16 UTC, bors-servo commented
:hourglass: Testing commit 504667d8968f1a66f1e5f145ee1d530a79d619cb with merge b609f61b26d1708536fed60943ffb71fd9d63d64...

2018-01-09 13:23 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7486)

2018-01-09 13:26 UTC, emilio commented
@bors-servo r=heycam

2018-01-09 13:26 UTC, bors-servo commented
:pushpin: Commit bfc91c5 has been approved by `heycam`

<!-- @bors-servo r=heycam bfc91c5e1244dcd567545e10e3fe83b7e77a79e7 -->

2018-01-09 13:26 UTC, bors-servo commented
:hourglass: Testing commit bfc91c5e1244dcd567545e10e3fe83b7e77a79e7 with merge bb34b7f54aa85cde600c6d675360d03714cf1f8b...

2018-01-09 14:22 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10327), [arm32](http://build.servo.org/builders/arm32/builds/10562), [arm64](http://build.servo.org/builders/arm64/builds/10589), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10614), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7472), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7487), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10690), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3101), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3120), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7370), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7429), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3189), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3139), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5988)
Approved by: heycam
Pushing bb34b7f54aa85cde600c6d675360d03714cf1f8b to master...

2018-01-09 14:22 UTC, merged