Update buildbot_steps lint to handle env variables
servo/servo pull request #19720
Opened 2018-01-08 05:22 UTC by aneeshusa

https://github.com/servo/saltfs/pull/687 added support
for specifying environment variables in `buildbot_steps.yml`.
Update the servo-tidy buildbot_steps.yml linter to reflect this.

Use the voluptuous Python library (BSD 3-clause license) for validation
in lieu of a much larger hand-written implementation.

Extracted out of #17171. Helps with servo/saltfs#770.

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they change the tests

2018-01-08 05:22 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/requirements.txt, python/tidy/servo_tidy/tidy.py
 * @edunham: python/tidy/servo_tidy/tidy.py

2018-01-08 05:22 UTC, aneeshusa commented
cc @jdm

2018-01-08 05:26 UTC, aneeshusa commented
I've added a second commit which redoes #19612 (denying warnings in CI) with this new support as an example of its usefulness.

2018-01-08 08:32 UTC, aneeshusa commented
Fixed tidy's self test and updated `.travis.yml` and `appveyor.yml` as well.

2018-01-08 17:34 UTC, jdm commented
This is a nice improvement. Thanks!
@bors-servo r+

2018-01-08 17:34 UTC, bors-servo commented
:pushpin: Commit 94febf4 has been approved by `jdm`

<!-- @bors-servo r=jdm 94febf43d6a989e0859e0c5454a3e4e7c317cacc -->

2018-01-08 18:31 UTC, bors-servo commented
:hourglass: Testing commit 94febf43d6a989e0859e0c5454a3e4e7c317cacc with merge 5e110ee0b2cf98d4e731ba437cad6a02d884724b...

2018-01-08 18:55 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/10601)

2018-01-08 19:07 UTC, jdm requested changes

2018-01-08 19:07 UTC, jdm commented on etc/ci/buildbot_steps.yml
> +  - env ./mach build-geckolib
We'll need to remove all of the now-unnecessary env prefixes.

2018-01-09 15:18 UTC, SimonSapin commented
@aneeshusa I’ve pushed a fixup commit to your branch

@bors-servo try

2018-01-09 15:19 UTC, bors-servo commented
:hourglass: Trying commit be1f769ada8180b82fa11f2bcf38fe9478f02092 with merge 440275f8090cbd1a696fb0eb560656485c46f515...

2018-01-09 15:58 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/10619)

2018-01-09 16:10 UTC, SimonSapin commented
```
env CC=gcc-5 CXX=g++-5 "" ./mach build-cef
[…]
env: : No such file or directory
```

That `""` comes form having two consecutive spaces in `etc/ci/buildbot_steps.yml`, with the empty string between them being interpreted as a separate argument. Some bit of Python in servo/saltfs probably need to use `foo.split()` instead of `foo.split(" ")`, or something like that. I’ve removed the extra space.

2018-01-09 16:15 UTC, jdm commented
@bors-servo r+

2018-01-09 16:15 UTC, bors-servo commented
:pushpin: Commit e9eaadc has been approved by `jdm`

<!-- @bors-servo r=jdm e9eaadc913c62ee62d90bcacdf61436034543a54 -->

2018-01-09 16:25 UTC, bors-servo commented
:hourglass: Testing commit e9eaadc913c62ee62d90bcacdf61436034543a54 with merge e8015fd0f31aa8b6f9fde95e1a6a343cc50de671...

2018-01-09 17:32 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10332), [arm32](http://build.servo.org/builders/arm32/builds/10568), [arm64](http://build.servo.org/builders/arm64/builds/10594), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10620), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7480), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7495), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10697), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3106), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3125), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7375), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7435), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3195), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3144), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5995)
Approved by: jdm
Pushing e8015fd0f31aa8b6f9fde95e1a6a343cc50de671 to master...

2018-01-09 17:40 UTC, SimonSapin commented
@bors-servo retry

2018-01-09 17:40 UTC, bors-servo commented
:hourglass: Testing commit e9eaadc913c62ee62d90bcacdf61436034543a54 with merge 6a6dda526961b7bb7b856e8310ffc165d8bd39aa...

2018-01-09 18:38 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10333), [arm32](http://build.servo.org/builders/arm32/builds/10569), [arm64](http://build.servo.org/builders/arm64/builds/10595), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10621), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7481), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7497), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10699), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3107), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3126), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7376), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7436), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3196), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3145), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/5996)
Approved by: jdm
Pushing 6a6dda526961b7bb7b856e8310ffc165d8bd39aa to master...

2018-01-09 18:38 UTC, merged