Use more WebRender types in gfx
servo/servo pull request #19824
Opened 2018-01-20 17:15 UTC by pyfisch

Removes ImageBorder details from gfx.
Use WebRender BorderRadius in BoxShadow.
Stores cursors as integer.
Use FilterOp, BorderWidths from WebRender.
Store content_rect as LayoutRect.

This amends #19782.

2018-01-20 17:15 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @emilio: components/layout/display_list/webrender_helpers.rs, components/layout/display_list/builder.rs

2018-01-20 17:15 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify gfx and layout code, but no tests are modified. Please consider adding a test!

2018-01-20 18:22 UTC, pyfisch commented
@bors-servo try

2018-01-20 18:22 UTC, bors-servo commented
:hourglass: Trying commit 46b9b52135cfb87dfeb3771cdf35920a5d9c6c5a with merge 4a2aa7cb3ca8e8d744e4943f9495d8a93843a606...

2018-01-20 19:07 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #19798) made this pull request unmergeable. Please resolve the merge conflicts.

2018-01-20 19:39 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10460), [arm32](http://build.servo.org/builders/arm32/builds/10698), [arm64](http://build.servo.org/builders/arm64/builds/10723), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10751), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7615), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7631), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10830), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3231), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3253), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7500), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7564), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3324), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3272), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6133)
State: approved= try=True

2018-01-21 09:29 UTC, pyfisch commented
Rebased.

2018-01-22 14:40 UTC, jdm commented
r? @glennw

2018-01-29 14:04 UTC, pyfisch commented
r? @mrobinson 

As you already reviewed the previous PR (#19782) can you have a look here too?

The *S-needs-rebase* is outdated.

2018-01-29 17:01 UTC, mrobinson requested changes
This looks really great. Feel free to land when the nit is fixed.

2018-01-29 17:01 UTC, mrobinson commented on components/layout/display_list/builder.rs
> +                left: webrender_api::BorderSide {
I think it would be better to just include BorderSide and use it directly.

2018-01-29 17:01 UTC, mrobinson commented
@bors-servo delegate+

2018-01-29 17:01 UTC, bors-servo commented
:v: @pyfisch can now approve this pull request

2018-01-30 10:42 UTC, pyfisch commented
@bors-servo r+ r=mrobinson

2018-01-30 10:42 UTC, bors-servo commented
:pushpin: Commit 8bb50ac has been approved by `mrobinson`

<!-- @bors-servo r=mrobinson 8bb50ac0b9ceee4fbf3ab0f53b9ad16ee2b9d094 -->

2018-01-30 10:42 UTC, bors-servo commented
:pushpin: Commit 8bb50ac has been approved by `pyfisch`

<!-- @bors-servo r=pyfisch 8bb50ac0b9ceee4fbf3ab0f53b9ad16ee2b9d094 -->

2018-01-30 10:42 UTC, bors-servo commented
:hourglass: Testing commit 8bb50ac0b9ceee4fbf3ab0f53b9ad16ee2b9d094 with merge bad46383bd6c9091fe0213703e24345160bdf56a...

2018-01-30 11:27 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10563), [arm32](http://build.servo.org/builders/arm32/builds/10806), [arm64](http://build.servo.org/builders/arm64/builds/10835), [linux-dev](http://build.servo.org/builders/linux-dev/builds/10857), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/7724), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/7739), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10932), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3330), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3354), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7596), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7667), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3427), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3374), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6238)
Approved by: pyfisch
Pushing bad46383bd6c9091fe0213703e24345160bdf56a to master...

2018-01-30 11:28 UTC, merged