WIP : added AutoCloseWorker for closing related workers when a page/another worker is closed.
servo/servo pull request #20068
Opened 2018-02-18 20:31 UTC by nupurbaghel

Followed steps as suggested in issue. 
Error is not yet resolved!
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #17977 (https://github.com/servo/servo/issues/17977?).

- [ ] These changes do not require tests because it will have manual test case.

2018-02-18 20:31 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/worker.rs, components/script/dom/globalscope.rs, components/script/dom/workerglobalscope.rs, components/script/dom/dissimilaroriginwindow.rs, components/script/dom/workletglobalscope.rs and 1 more
 * @fitzgen: components/script/dom/worker.rs, components/script/dom/globalscope.rs, components/script/dom/workerglobalscope.rs, components/script/dom/dissimilaroriginwindow.rs, components/script/dom/workletglobalscope.rs and 1 more
 * @kichjang: components/script/dom/worker.rs, components/script/dom/globalscope.rs, components/script/dom/workerglobalscope.rs, components/script/dom/dissimilaroriginwindow.rs, components/script/dom/workletglobalscope.rs and 1 more

2018-02-18 20:31 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-02-18 20:39 UTC, nupurbaghel commented
Wanted to confirm about the following -
1. Used Ordering::SeqCst for the drop function, also tried using Relaxed. What is more valid here?
2. Used the Default::default() for all places which were using GlobalScope::new_inherited. Is this fine?
3. Domrefcell< Vector > for global scope( emilio suggested RefCell < Option < > > ) Will it make any difference here ?

2018-02-20 18:18 UTC, jdm commented
What if you add a method to GlobalScope that clears the vector, and call that from Window::clear_js_runtime?

2018-02-20 18:20 UTC, jdm requested changes

2018-02-20 18:20 UTC, jdm commented on components/script/dom/globalscope.rs
> +        list_auto_close_worker: DomRefCell<Vec<AutoCloseWorker>>,
We don't need to pass this in as an argument. We can simply initialize it with a default value instead.

2018-02-20 18:20 UTC, jdm commented on components/script/dom/globalscope.rs
> +    pub fn update_list(&self, closing_worker: Arc<AtomicBool>) {
Let's call this `track_worker` instead.

2018-02-20 18:29 UTC, asajeffrey commented
For the ordering in the drop code, script is single-threaded, so you may be able to get away with just a `Cell<bool>`, and not need to worry about atomics.

2018-02-20 18:41 UTC, nupurbaghel commented
@jdm When will the window call clear_js_runtime function ? Instead of passing the clone, we should do that ?
@asajeffrey I think we used atomic because we were adding a clone of closing from worker which was of atomic type. So should I try converting that now?

2018-02-20 18:44 UTC, jdm commented
@nupurbaghel Window::clear_js_runtime is called from ScriptThread::handle_exit_pipeline_msg, which is called when the script thread receives a notification from the constellation that to close a pipeline. This happens when the constellation is notified that an iframe was removed, which is what happens in the testcase.

@asajeffrey The atomic boolean is shared with a worker thread, so that won't work.

2018-02-20 19:48 UTC, asajeffrey commented
@jdm we have some uses of shared-memory concurrency in script? You learn something new every day.

2018-02-21 18:56 UTC, nupurbaghel commented
I have added test file along with the suggested changes. I verified that the function to clear the vector gets called. The output of the test file still causes an endless printing of statements.  Can anything else be verified ?

2018-02-22 14:34 UTC, jdm commented
Ah, the test file isn't quite right. I recommend the following:
parent.html
```html
<script>
var iframe = document.createElement('iframe');
iframe.src = "child.html";
iframe.onload = function() { iframe.remove(); }
document.body.appendChild(iframe);
</script>
```
child.html
```html
<script>
var w = new Worker('work.js');
</script>
```
work.js
```js
setInterval(function() {
  console.log('hi');
}, 500);
```
Does that change the behaviour for you?

2018-02-22 15:16 UTC, nupurbaghel commented
Running the parent.html file raises the document.body is null error now :)

2018-02-22 16:11 UTC, jdm commented
@bors-servo r+

2018-02-22 16:11 UTC, bors-servo commented
:pushpin: Commit 36991b9 has been approved by `jdm`

<!-- @bors-servo r=jdm 36991b9d7963bcf72a71e3cd5c0e0823960cfe32 -->

2018-02-22 18:34 UTC, bors-servo commented
:hourglass: Testing commit 36991b9d7963bcf72a71e3cd5c0e0823960cfe32 with merge 9c484452c0688205044a632b18083f85a3697693...

2018-02-22 19:36 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/10824), [arm32](http://build.servo.org/builders/arm32/builds/11064), [arm64](http://build.servo.org/builders/arm64/builds/11093), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11127), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8003), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8017), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11189), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3588), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3611), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/7855), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/7925), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3687), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3631), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6511)
Approved by: jdm
Pushing 9c484452c0688205044a632b18083f85a3697693 to master...

2018-02-22 19:36 UTC, merged