[WIP] script: Partially implement sequential focus navigation
servo/servo pull request #20075
Opened 2018-02-19 16:49 UTC by CYBAI

This PR originally aims to take over #15936 and #13460.
But, after checking the spec and asking jdm in [comment in #15936](https://github.com/servo/servo/pull/15936#discussion_r159151457), I'd like to change the implementation in previous two PRs.
There're still some algorithms which need to be implemented so I add `WIP` in PR title.
I'll keep updating this PR and remove WIP after all algorithms for sequential focus navigation done.

r? @nox or @jdm or @emilio 

---
- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #3982 
- [ ] There are tests for these changes

2018-02-19 16:49 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/document.rs, components/script/dom/htmlanchorelement.rs, components/script/dom/element.rs
 * @fitzgen: components/script/dom/document.rs, components/script/dom/htmlanchorelement.rs, components/script/dom/element.rs
 * @kichjang: components/script/dom/document.rs, components/script/dom/htmlanchorelement.rs, components/script/dom/element.rs

2018-02-19 16:49 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-09-20 00:43 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #21737) made this pull request unmergeable. Please resolve the merge conflicts.

2019-01-29 09:19 UTC, CYBAI commented
Just rebased.

2019-01-30 00:40 UTC, jdm requested changes
It's a start!

2019-01-30 00:41 UTC, jdm commented
Sorry for taking 11 months to look at this 😞

2019-01-30 03:32 UTC, CYBAI commented on components/script/dom/element.rs
> +            doc.get_focus_starting_point().is_none()
That sounds reasonable to me! Will update!

2019-01-30 03:33 UTC, CYBAI commented on components/script/dom/document.rs
> +        if let Some(ref key_event) = event.downcast::<KeyboardEvent>() {
Thanks for pointing me to the embedding layer! It must be the right place to detect the tab key :D Will update!

2019-01-30 14:41 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #22771) made this pull request unmergeable. Please resolve the merge conflicts.

2020-04-20 22:15 UTC, jdm commented
Closing due to inactivity.

2020-04-20 22:15 UTC, closed without merging