[WIP] Profiler for blocked IpcReceiver::recv()
servo/servo pull request #20132
Opened 2018-02-27 09:38 UTC by nakul02

Implements feature #19223 

---

- [x ] `./mach build -d` does not report any errors
- [x ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

WIP.
@jdm - this is the new profiler : "Blocked at IPC Receive"
Should I dig through all the calls to `ipc::channel` and replace them with this profiled `IpcReceiver`?

![screenshot from 2018-02-27 01-35-37](https://user-images.githubusercontent.com/5394361/36721061-b46edea4-1b5e-11e8-91d6-7faba742f237.png)

2018-02-27 09:38 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @metajack (or someone else) soon.

2018-02-27 09:38 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/screen.rs
 * @fitzgen: components/profile/time.rs, components/script/dom/screen.rs, components/profile_traits/lib.rs, components/profile_traits/time.rs, components/profile_traits/Cargo.toml and 1 more
 * @kichjang: components/script/dom/screen.rs

2018-02-27 09:38 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-02-27 14:18 UTC, jdm commented
Yes, replacing all the users would be really useful!

2018-03-01 08:38 UTC, nakul02 commented
@jdm - I've gone ahead and replaced calls to `ipc_channel::ipc::channel` to the newly introduced `profile_traits::receiver::channel` where calls were made to `recv` in the `components/script/dom` folder.
Do you want this done project wide for every call to `ipc_channel::ipc::channel`.
In most other places, there may not be a simple way to get a handle on the `ProfilerChan` instance.

2018-03-05 22:17 UTC, nakul02 commented
Ping @jdm

2018-03-05 22:29 UTC, jdm commented
From my point of view, the more we use this API, the more confident we can be that we're actually noticing the biggest offenders. That being said, if you would prefer to merge the changes that you've made so far, we can also continue changing other channels in followup PRs.

2018-03-05 23:22 UTC, nakul02 commented
@jdm - if you have suggestions or guidelines for components that I should check for, I can go in and change those. Otherwise, for now, I'd prefer to merge this.
Does the name `profiler_traits::receiver` look ok? It is invoked everywhere as `receiver::channel`.

2018-03-08 16:15 UTC, jdm commented
@nakul02 What if we used `profiler_traits::ipc` instead? I think this is a good set of channels to start with, and we can file follow up issues for other instances that make sense, because there are a lot of uses of channels where they are expected to spend a lot of time waiting in recv() and we don't want to report that.

2018-03-08 16:19 UTC, jdm commented
Also, I bet we could write a test for this functionality in https://github.com/servo/servo/blob/master/tests/unit/profile/time.rs. Something like:
1. create a regular channel to mimic the time profiler
1. create a profiled channel
1. create a thread that waits for 2 seconds then sends a value with the sender
1. call recv() in the original thread
1. call recv() on the time profiler receiver, assert the its reports a realistic value for the time spent waiting on the first recv()
Does that make sense?

2018-03-11 10:31 UTC, nakul02 commented
@jdm - I've added a test, but can't figure out why its failing for the life of me. This is the output from its failure:
```
---- time::channel_profiler_test stdout ----
	thread 'time::channel_profiler_test' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })', libcore/result.rs:916:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: profile_tests::time::channel_profiler_test
             at tests/unit/profile/time.rs:59
  12: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1441
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:788
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102


failures:
    time::channel_profiler_test
```

In this PR, there is a new enum type in the `ProfilerMsg` enum to be able to ask for a vector of recorded times, given information about a `ProfilerBuckets`. I've also `Serialize`-d and `Deserialize`-d the data that is sent through the channel (or so I hope), but none of it seems to be doing the trick. 
Could you please take a look at the code from the *last* commit to see if anything pops out to you. If it doesn't any suggestion about a simpler way of testing this will help.

2018-03-11 13:30 UTC, jdm requested changes
These changes look great!

2018-03-11 13:30 UTC, jdm commented on tests/unit/profile/time.rs
> +    thread::spawn(move || {
No need to create a new thread here.

2018-03-11 13:33 UTC, jdm commented
Hmm. Unfortunately, this is probably hitting a know bug in ipc-channel that we haven't been able to track down yet. Is there any change if you clone the channel before passing it as an argument?

2018-03-11 20:25 UTC, nakul02 commented
@jdm - cloning the channel didn't help either. Anything else I can try.
What would be the fallback, in case I can't get around the ipc-channel bug?

2018-03-12 18:57 UTC, nakul02 commented
@jdm - since rebasing with master, the test is now either blocked or deadlocked.

2018-03-15 22:33 UTC, nakul02 commented
Ping @jdm

2018-03-15 22:52 UTC, jdm commented
Sorry, I spent a few hours looking into what could cause the deadlocking behaviour and got sidetracked by other fires that needed to be put out. It's really curious, because I can't reproduce the problem if I import all of the same code into a different project.

2018-03-15 23:09 UTC, jdm commented
If you run `./mach test-unit -p profile -v`, it should show you the binary that's being executed. If you run that binary with `--nocapture`, you should be able to see output from the tests, and adding `eprintln!("...")` to parts of the code may help you figure out where it's becoming blocked.

2018-03-16 22:17 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #20071) made this pull request unmergeable. Please resolve the merge conflicts.

2018-03-21 02:12 UTC, nakul02 commented
@jdm - I figured out what the problem was. It was in the change I put in while creation of the `time_profile_chan`. That particular unit test now runs and passes.

2018-03-22 08:27 UTC, nakul02 commented
Ping @jdm

2018-03-22 12:14 UTC, jdm commented
There are many more updates to Cargo.lock than this change requires. Did you run `cargo update -a`? Could you revert the changes to that file and run `./mach build` again instead?

2018-03-22 12:19 UTC, jdm approved these changes
Apart from the Cargo.lock changes, this looks great!

2018-03-22 13:51 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #20228) made this pull request unmergeable. Please resolve the merge conflicts.

2018-03-22 16:31 UTC, nakul02 commented
Thanks @jdm!
I deleted the Cargo.lock and ran `mach build -d`. That is what caused all those updates to `Cargo.lock`.

2018-03-22 16:34 UTC, jdm commented
@bors-servo r+

2018-03-22 16:34 UTC, bors-servo commented
:pushpin: Commit ac40d61 has been approved by `jdm`

<!-- @bors-servo r=jdm ac40d61f2ba601d0bd4e11714c3b974c057759d7 -->

2018-03-22 18:46 UTC, bors-servo commented
:hourglass: Testing commit ac40d61f2ba601d0bd4e11714c3b974c057759d7 with merge 8660555c7d70acbc7538b4bed5faa1805a4312a8...

2018-03-22 19:32 UTC, jdm commented
@bors-servo r+

2018-03-22 19:32 UTC, bors-servo commented
:pushpin: Commit 7d4e2b1 has been approved by `jdm`

<!-- @bors-servo r=jdm 7d4e2b11e940545eaa74877b75908e1e02f6eeb5 -->

2018-03-22 19:41 UTC, nakul02 commented
@jdm - is there a way to just cause `Taskcluster` to run again?

2018-03-22 20:38 UTC, bors-servo commented
:hourglass: Testing commit 7d4e2b11e940545eaa74877b75908e1e02f6eeb5 with merge f467bdce1ba95e950b01f59ba284873137bca5d5...

2018-03-22 21:28 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/11107), [arm32](http://build.servo.org/builders/arm32/builds/11343), [arm64](http://build.servo.org/builders/arm64/builds/11376), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11414), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8296), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8310), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11470), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3864), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3892), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8138), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8205), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3965), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3913), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6805)
Approved by: jdm
Pushing f467bdce1ba95e950b01f59ba284873137bca5d5 to master...

2018-03-22 21:29 UTC, merged