Rebump toml and error-chain
servo/servo pull request #20204
Opened 2018-03-05 19:07 UTC by Eijebong

2018-03-05 19:07 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/Cargo.toml, components/style/build_gecko.rs
 * @canaltinova: components/style/Cargo.toml, components/style/build_gecko.rs
 * @emilio: components/style/Cargo.toml, components/style/build_gecko.rs

2018-03-05 19:07 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2018-03-08 20:02 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #20245) made this pull request unmergeable. Please resolve the merge conflicts.

2018-03-09 03:03 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #19895) made this pull request unmergeable. Please resolve the merge conflicts.

2018-03-12 22:54 UTC, Eijebong commented
Woups, forgot to rebase this one. This is now done :)

2018-03-13 08:54 UTC, nox requested changes

2018-03-13 08:54 UTC, nox commented on components/style/build_gecko.rs
> +        match contents.parse::<toml::Value>() {
AFAICT you can use `toml::from_str` directly with `toml::Table` and avoid the nondescript `unwrap` call.

2018-03-13 08:54 UTC, nox commented on components/style/build_gecko.rs
> +                println!("1");
wat

2018-03-13 08:54 UTC, nox commented on components/style/build_gecko.rs
> +                println!("2");
wat

2018-03-13 08:54 UTC, nox commented on components/style/build_gecko.rs
> +        where F: FnMut(Builder, &'a Table) -> Builder {
Put the trait bound on its own line, after `where`.

2018-03-13 08:56 UTC, Eijebong commented on components/style/build_gecko.rs
> +                println!("1");
MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

2018-03-13 08:57 UTC, Eijebong commented on components/style/build_gecko.rs
> +                println!("2");
MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEHHHHHHHHHHHHHHHHHHHHHHHHHHHHH²

2018-03-13 09:23 UTC, Eijebong commented on components/style/build_gecko.rs
> +        -> Builder {
Oh...

2018-03-13 09:36 UTC, nox commented
@bors-servo r+

2018-03-13 09:36 UTC, bors-servo commented
:pushpin: Commit fcc64e6 has been approved by `nox`

<!-- @bors-servo r=nox fcc64e659d371a2d1479d905a8721566b74563f3 -->

2018-03-13 09:36 UTC, bors-servo commented
:hourglass: Testing commit fcc64e659d371a2d1479d905a8721566b74563f3 with merge 7e0f45b1c7047d9e1b16f39c005de7f92e462df7...

2018-03-13 10:36 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/11019), [arm32](http://build.servo.org/builders/arm32/builds/11257), [arm64](http://build.servo.org/builders/arm64/builds/11289), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11327), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8206), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8221), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11382), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3778), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3804), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8050), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8117), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3880), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3823), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6718)
Approved by: nox
Pushing 7e0f45b1c7047d9e1b16f39c005de7f92e462df7 to master...

2018-03-13 10:36 UTC, merged