refactor(counter_style): parse int via parse_non_negative
servo/servo pull request #20368
Opened 2018-03-20 19:07 UTC by kwonoj

Relates to #20332.

This PR intends to refactor `counter_style` to use `parse_non_negative` where applicable, mostly which uses `expect_integer` currently. Change still grabs value from parsed result then assign it into each struct as needed and does not change definition of struct (i.e `AdditiveTuple`) itself.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #20332 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____
- This PR has locally built & ran unit test on macOS.

2018-03-20 19:08 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @bholley: components/style/counter_style/mod.rs
 * @canaltinova: components/style/counter_style/mod.rs
 * @emilio: components/style/counter_style/mod.rs

2018-03-20 19:08 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style code, but no tests are modified. Please consider adding a test!

2018-03-21 10:07 UTC, emilio approved these changes
Thanks for working on this!

2018-03-21 10:07 UTC, emilio commented on components/style/counter_style/mod.rs
> +                let first_symbol_value = Integer::parse_non_negative(context, input)
This is wrong, this needs to be:

```rust
let first_symbol_value = input.try(|i| Integer::parse_non_negative(context, i)).ok();
```

instead.

2018-03-21 10:07 UTC, emilio commented on components/style/counter_style/mod.rs
> +                let first_symbol_value = Integer::parse_non_negative(context, input)
And `first_symbol_value` needs to start taking an `Integer` instead of an i32.

2018-03-21 10:07 UTC, emilio commented on components/style/counter_style/mod.rs
> +            weight: weight.value() as u32,
`weight` should become an `Integer`.

2018-03-21 10:07 UTC, emilio commented on components/style/counter_style/mod.rs
> +        Ok(Pad(min_length.value() as u32, pad_with))
The first member of `Pad` should become an Integer, not a `u32`.

2018-03-21 10:07 UTC, emilio requested changes
Err, I meant to request changes above :)

2018-03-21 10:08 UTC, emilio commented on components/style/counter_style/mod.rs
> +                let first_symbol_value = Integer::parse_non_negative(context, input)
Err, and this doesn't really need to be non-negative, so should be:

```rust
let first_symbol_value = input.try(|i| Integer::parse(context, i)).ok();

2018-03-21 15:43 UTC, kwonoj commented
@emilio appreciate for review, tried to update as suggested. Wasn't entirely sure if I could update types to take `Integer` directly.

2018-03-21 20:29 UTC, emilio approved these changes
Looks great! Mind sqashing the commits?

2018-03-21 20:29 UTC, emilio commented
*squashing, that is :)

2018-03-21 22:04 UTC, kwonoj commented
@emilio sure, rebased to master and squashed into single commit.

2018-03-21 22:18 UTC, emilio commented
@bors-servo r+

Thank you!

2018-03-21 22:18 UTC, bors-servo commented
:pushpin: Commit c8592ea has been approved by `emilio`

<!-- @bors-servo r=emilio c8592ead6fc3b957f7e7ef0f93d7c1bec6266ca5 -->

2018-03-21 22:18 UTC, bors-servo commented
:hourglass: Testing commit c8592ead6fc3b957f7e7ef0f93d7c1bec6266ca5 with merge 4e26212d5e661b21392f59bdbe5518d047fe0531...

2018-03-21 23:06 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8285)

2018-03-22 01:21 UTC, jdm commented
@bors-servo retry
#13479

2018-03-22 01:21 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/11097), [arm32](http://build.servo.org/builders/arm32/builds/11333), [arm64](http://build.servo.org/builders/arm64/builds/11366), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11404), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8300), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11460), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3854), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3882), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8128), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8195), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3955), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3902), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6795) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8285)...

2018-03-22 01:38 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/11097), [arm32](http://build.servo.org/builders/arm32/builds/11333), [arm64](http://build.servo.org/builders/arm64/builds/11366), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11404), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8286), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8300), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11460), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3854), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3882), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8128), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8195), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/3955), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3902), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6795)
Approved by: emilio
Pushing 4e26212d5e661b21392f59bdbe5518d047fe0531 to master...

2018-03-22 01:38 UTC, merged