History: update document URL on pushState/replaceState
servo/servo pull request #20453
Opened 2018-03-27 09:18 UTC by talklittle

Update Document URL when calling pushState and replaceState on History.

https://html.spec.whatwg.org/multipage/#dom-history-pushstate
Steps 6, 7, 10

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #19157 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because WPT tests are used for testing: tests/wpt/web-platform-tests/html/browsers/history/the-history-interface/

2018-03-27 09:18 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/history.rs, components/constellation/constellation.rs
 * @cbrewster: components/constellation/constellation.rs
 * @paulrouget: components/constellation/constellation.rs
 * @fitzgen: components/script/dom/history.rs, components/script_traits/script_msg.rs
 * @kichjang: components/script/dom/history.rs, components/script_traits/script_msg.rs

2018-03-27 14:33 UTC, jdm commented
cc @cbrewster

2018-03-27 14:33 UTC, jdm commented
r? @asajeffrey

2018-04-16 16:31 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #20638) made this pull request unmergeable. Please resolve the merge conflicts.

2018-04-17 17:02 UTC, cbrewster requested changes
@talklittle sorry for taking a while on this one!

Looks good, I think we can get the current entry URL from the document rather than going to the constellation.

This will need to be rebased since #20638. The next steps will be to make the constellation aware of the URL in the session history. If you'd like to do that work as a followup, I'd be happy to mentor. (ping me on mozilla IRC: cbrewster)

2018-04-17 17:02 UTC, cbrewster commented on components/script/dom/history.rs
> +                let browsing_context_id = self.window.window_proxy().browsing_context_id();
I think we should be able to get the URL from the document itself rather than going via the constellation.

2018-04-18 20:35 UTC, talklittle commented
@cbrewster Thanks for the review. I've rebased and applied your suggestions.

> The next steps will be to make the constellation aware of the URL in the session history. If you'd like to do that work as a followup, I'd be happy to mentor.

Thanks for the offer, but I am becoming busy again at the moment. If you want to continue the rest of the History work please feel free.

2018-04-18 23:33 UTC, cbrewster commented
@talklittle no worries, thanks for doing this!

@bors-servo r+

2018-04-18 23:33 UTC, bors-servo commented
:pushpin: Commit 1371dc3 has been approved by `cbrewster`

<!-- @bors-servo r=cbrewster 1371dc3d15634b56204b807669fc53027ff2cb88 -->

2018-04-18 23:33 UTC, bors-servo commented
:hourglass: Testing commit 1371dc3d15634b56204b807669fc53027ff2cb88 with merge f2218d86465fc9da1ed23a60fa66b294b5e0719a...

2018-04-18 23:53 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8351)

2018-04-19 00:08 UTC, cbrewster commented
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "location search", "test": "/html/browsers/history/the-location-interface/location_search.html", "line": 66417, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Check if button.formAction is the document's new address when formaction content attribute is missing and pushState has been used", "test": "/html/semantics/forms/attributes-common-to-form-controls/formAction_document_address.html", "line": 113350, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Check if input.formAction is the document's new address when formaction content attribute is missing and pushState has been used", "test": "/html/semantics/forms/attributes-common-to-form-controls/formAction_document_address.html", "line": 113351, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "location hash", "test": "/html/browsers/history/the-location-interface/location_hash.html", "line": 129937, "action": "test_result", "expected": "FAIL"}
```

2018-04-19 03:14 UTC, asajeffrey commented
Yay! Lots more passing tests! @bors-servo r=cbrewster

2018-04-19 03:14 UTC, bors-servo commented
:pushpin: Commit 68c4791 has been approved by `cbrewster`

<!-- @bors-servo r=cbrewster 68c4791c7d5ff71e60ab0edf966e9888a945b1a3 -->

2018-04-19 03:30 UTC, bors-servo commented
:hourglass: Testing commit 68c4791c7d5ff71e60ab0edf966e9888a945b1a3 with merge 805a15e84d36d1c3226da37b64a2a030a0c19faa...

2018-04-19 03:50 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4075)

2018-04-19 14:28 UTC, asajeffrey commented
@bors-servo retry
 * infra

2018-04-19 14:38 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/11319), [arm32](http://build.servo.org/builders/arm32/builds/11553), [arm64](http://build.servo.org/builders/arm64/builds/11594), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11632), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8525), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8530), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11684), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4110), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8354), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8419), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4126), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7024) are reusable. Rebuilding only [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4075), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4176)...

2018-04-19 14:59 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4079)

2018-04-19 15:04 UTC, cbrewster commented
@bors-servo retry
 * servo-mac7 is broken, hopefully its not used this time

2018-04-19 16:29 UTC, bors-servo commented
:hourglass: Testing commit 68c4791c7d5ff71e60ab0edf966e9888a945b1a3 with merge 3c5f0a85debcb2fc7417137e2ea3a991fb6c5549...

2018-04-19 16:59 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8534)

2018-04-19 18:42 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/11323), [arm32](http://build.servo.org/builders/arm32/builds/11557), [arm64](http://build.servo.org/builders/arm64/builds/11598), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11636), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8529), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11688), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4081), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4114), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8360), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8423), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4181), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4130), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7028) are reusable. Rebuilding only [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8534)...

2018-04-19 19:11 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/11323), [arm32](http://build.servo.org/builders/arm32/builds/11557), [arm64](http://build.servo.org/builders/arm64/builds/11598), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11636), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8529), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8538), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11688), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4081), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4114), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8360), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8423), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4181), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4130), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7028)
Approved by: cbrewster
Pushing 3c5f0a85debcb2fc7417137e2ea3a991fb6c5549 to master...

2018-04-19 19:11 UTC, merged