Properly rethrow any exceptions from parsing JSON in Body mixin's `Json()`
servo/servo pull request #20450
Opened 2018-03-27 05:31 UTC by ysimonson

This fixes #13464 by rethrowing exceptions from parsing JSON.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #__ (github issue number if applicable).
- [X] There are tests for these changes

2018-03-27 05:32 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @glennw (or someone else) soon.

2018-03-27 05:32 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/body.rs
 * @fitzgen: components/script/body.rs
 * @kichjang: components/script/body.rs

2018-03-27 14:30 UTC, jdm requested changes

2018-03-27 14:30 UTC, jdm commented on components/script/body.rs
> +            JS_GetPendingException(cx, exception.handle_mut());
Let's assert that this return true.

2018-03-28 02:31 UTC, jdm commented
@bors-servo r+
Thanks for working on this!

2018-03-28 02:31 UTC, bors-servo commented
:pushpin: Commit ac1e024 has been approved by `jdm`

<!-- @bors-servo r=jdm ac1e02405d062f1f1051e27321306a140e9aad9f -->

2018-03-28 02:44 UTC, bors-servo commented
:hourglass: Testing commit ac1e02405d062f1f1051e27321306a140e9aad9f with merge 25dcd0ecfd4cb7a844f00696730cb0d3ab4b198c...

2018-03-28 03:45 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/11163), [arm32](http://build.servo.org/builders/arm32/builds/11398), [arm64](http://build.servo.org/builders/arm64/builds/11433), [linux-dev](http://build.servo.org/builders/linux-dev/builds/11470), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8357), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8367), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/11528), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/3921), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/3949), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8196), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8263), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4021), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/3970), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/6862)
Approved by: jdm
Pushing 25dcd0ecfd4cb7a844f00696730cb0d3ab4b198c to master...

2018-03-28 03:45 UTC, merged

2018-03-28 05:21 UTC, ysimonson commented
Thanks again for all of the help @jdm!