[WIP] delegate resource reading to embedder
servo/servo pull request #20473
Opened 2018-03-29 07:59 UTC by paulrouget

WIP. I'm not happy with all these init functions.

/cc @jdm 

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2018-03-29 08:00 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net_traits/pub_domains.rs, components/net/resource_thread.rs, components/net/hsts.rs, components/net_traits/lib.rs, components/net_traits/Cargo.toml and 1 more

2018-03-29 08:00 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2018-03-30 10:05 UTC, jdm requested changes

2018-03-30 11:19 UTC, paulrouget commented on ports/servo/browser.rs
> +pub struct FileChromeReader;
Thanks. I like this better.

But how would it work for `neterror.html` and `badcert.html`, or even for `rippy.png`? Using a `chrome://` URL made it easy.

2018-03-31 14:15 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #20483) made this pull request unmergeable. Please resolve the merge conflicts.

2018-04-04 14:00 UTC, paulrouget commented
Better PR coming. Closing.

2018-04-04 14:00 UTC, closed without merging