Ignore navigation input if key state is Released
servo/servo pull request #20628
Opened 2018-04-12 13:08 UTC by piotr-szpetkowski

Hi. As my first PR in Servo and also my first commit in any Rust project I've fixed issue with `Navigation` event being sent twice on a single shortcut press. I'm not entirely happy about nested ifs, but AFAIK it's not possible to use `if let` and a conditional in one line.

I'm a newcomer to Rust, so I'd be grateful for feedback for improvements. 

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach build-geckolib` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #20478 

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because the change is trivial.

2018-04-12 13:09 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @manishearth (or someone else) soon.

2018-04-12 13:09 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @paulrouget: ports/servo/browser.rs

2018-04-12 14:19 UTC, paulrouget requested changes
We need to do the same thing for the other bindings too. Like reload, loadurl, Cmd-Q, …

2018-04-12 16:05 UTC, piotr-szpetkowski commented on ports/servo/browser.rs
> +                if state != KeyState::Released {
I've followed the suggestion of @cbrewster that both `KeyState::Repeated` and `KeyState::Pressed` might be a valid state and therefore to check for state not being equal to `KeyState::Released` - https://github.com/servo/servo/issues/20478#issuecomment-380125378

2018-04-12 16:54 UTC, piotr-szpetkowski commented
@paulrouget is it desirable to disallow the `KeyState::Released` for all of the input processed by `handle_key_from_window` or would you rather see it as an individual decision for each of the `match` arms?

2018-04-13 07:02 UTC, paulrouget commented
@piotr-szpetkowski You'll see that in `handle_key_from_window`, in the `_` branch of the main match, that events are sent to Servo as `WindowEvent::KeyEvent` if they are not used in any of the other branch. So we can't have a global check. We will need individual checks.

For the record: Servo will never receive these key events ever. Even if 1) it's no-op (if we press a goForward binding, but we know we can't go forward), and 2) on Release.

2018-04-20 10:12 UTC, paulrouget commented
@piotr-szpetkowski let me know if you need help moving forward.

2018-04-21 14:44 UTC, piotr-szpetkowski commented
@paulrouget I've updated my PR and it should (hopefully) comply with your review. I've changed the if expression into the match guard and I've also added it to every other match branch except the `_`. Sorry I didn't take care of this earlier, but I've been extremely short on spare time during the week.

2018-04-25 06:34 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #20687) made this pull request unmergeable. Please resolve the merge conflicts.

2018-04-28 05:37 UTC, paulrouget commented
Looks better. Can you rebase and use `== Pressed` instead of `!= Released`?

2018-05-22 19:05 UTC, jdm commented
@piotr-szpetkowski Will you have time to address Paul's last comment?

2018-05-22 19:29 UTC, piotr-szpetkowski commented
Hi @jdm - I'll be able to take care of it on this Friday's evening or Saturday. Also, I've finally finished dealing with real life stuff, so I should have more of a spare time :slightly_smiling_face: 
Sorry for the amount of time it takes to close the issue.

2018-05-31 13:15 UTC, piotr-szpetkowski commented
Hey @paulrouget - I've applied your change request and rebased from master. I've already done it few days ago, but I've forgot to poke you about it, so here, I've rebased once again now and awaiting review.

2018-06-01 02:09 UTC, paulrouget requested changes
Thank you for the update.

2018-06-01 02:09 UTC, paulrouget commented on ports/servo/browser.rs
> +            if state == KeyState::Pressed && mods ^ KeyModifiers::CONTROL == KeyModifiers::SHIFT {
Because you moved the modifier check after `=>`, it means that just pressing "3" will never make it to Servo.

Keep the modifier check before `=>`.

2018-07-30 20:08 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #21250) made this pull request unmergeable. Please resolve the merge conflicts.

2018-07-31 07:03 UTC, paulrouget commented
#21250 fixed this.

2018-07-31 07:03 UTC, closed without merging