handle case of refreshed cache entry still receiving data
servo/servo pull request #21079
Opened 2018-06-22 04:38 UTC by gterzian

When refreshing cached entries, handle the case the the entry is still "receiving"...

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #20802 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2018-06-22 04:38 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net/http_cache.rs

2018-06-22 04:38 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2018-06-22 04:38 UTC, gterzian commented
r? @jdm

2018-06-22 04:40 UTC, gterzian commented
r? @jdm 
I've tested manually with `./mach run -d --pref dom.mutation_observer.enabled https://aframe.io/examples/showcase/a-blast/` and it indeed seems to fix the issue...

2018-06-22 13:08 UTC, gterzian commented
I just realized we probably don't want to keep the `done_chan` created by the fetch worker, since that is related to the 304 response, not the refreshed cached response...

Looking into it and will update this shortly...

2018-06-22 15:41 UTC, gterzian commented
Ok, this seems to do the trick. 

So the problem is the `DoneChannel` will have been set to `Some(..)` by the network fetch, but that is the channel related to the 304 response, not the cached resource that is to be refreshed.

In the case that the cached resource is actually still receiving data(from another fetch worker), then we set the channel to a new `Some(..)`, and we wait on it until the data has been received(like is done 'normally' when the cache constructs a resource that is still receiving bytes). 

Once the response is 'done', we set the channel back to None...

Ready for review.

2018-06-22 16:20 UTC, jdm commented
@gterzian Is it possible to write a unit test or web platform test for this behaviour?

2018-06-22 16:28 UTC, jdm requested changes

2018-06-22 16:28 UTC, jdm commented on components/net/http_cache.rs
> +                        cached_resource.awaiting_body.lock().unwrap().push(done_sender);
Is there a risk of deadlock here while the cached_resource.body lock is held? Would it be safer to do something like:
```rust
let in_progress_channel = match *cached_resource.body.lock().unwrap() {
    ResponseBody::Receiving(..) => Some(channel())
    ResponseBody::Empty | ResponseBody::Done(..) => None
};
match in_progress_channel {
    Some((done_sender, done_receiver)) => {
        cached_resource.awaiting_body.lock().unwrap().push(done_sender.clone());
        *done_chan = Some((done_sender, done_receiver));
    }
    None => *done_chan = None,
}
```

2018-06-23 13:00 UTC, gterzian commented
@jdm I ended up adding a fairly focused unit-test, mainly because I couldn't reproduce the error with either a wpt or a more integration like fetch test. I'm fairly satisfied because the unit test did initially fail, and it covers the logical error...

2018-06-23 14:15 UTC, jdm commented
@bors-servo r+
Thanks for adding that!

2018-06-23 14:15 UTC, bors-servo commented
:pushpin: Commit 96c1242 has been approved by `jdm`

<!-- @bors-servo r=jdm 96c124230b367c0c9658e3628bcb0a33533cc96c -->

2018-06-23 14:16 UTC, bors-servo commented
:hourglass: Testing commit 96c124230b367c0c9658e3628bcb0a33533cc96c with merge d70e131247fcd5fb8ad2aad98a38e61e5f738cf2...

2018-06-23 15:16 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8848)

2018-06-23 15:45 UTC, CYBAI commented
@bors-servo retry

- #20734

2018-06-23 15:45 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/11803), [arm32](http://build.servo.org/builders/arm32/builds/12026), [arm64](http://build.servo.org/builders/arm64/builds/12074), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12117), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9024), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9027), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12168), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4581), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4601), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8901), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4666), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4600), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7511) are reusable. Rebuilding only [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8848)...

2018-06-23 16:43 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/11803), [arm32](http://build.servo.org/builders/arm32/builds/12026), [arm64](http://build.servo.org/builders/arm64/builds/12074), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12117), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9024), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9027), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12168), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4581), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4601), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8849), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8901), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4666), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4600), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7511)
Approved by: jdm
Pushing d70e131247fcd5fb8ad2aad98a38e61e5f738cf2 to master...

2018-06-23 16:44 UTC, merged