"./mach env" cause unclear message.
servo/servo pull request #21104
Opened 2018-06-29 17:27 UTC by wayling

We did't use "LD_LIBRARY_PATH" and no need display this.

Remove the print message.

---

- [ X] `./mach build -d` does not report any errors
- [ X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/servo/21104)

2018-07-02 08:59 UTC, KiChjang commented
Is there a more justifiable reason than "we didn't use this"? {DY}LD_LIBRARY_PATH seems to be a useful environment variable to keep track of.

2018-07-02 14:51 UTC, wayling commented
@KiChjang 
Thanks review.

When i build down and run "./mach env" get unclear message(below).
And i check the "bootstrap_commands.py" found env["LD_LIBRARY_PATH"] don't any value so i think is  no  use in servo that could remove.
+++++++++++++++++++++++
export RUSTFLAGS= -C link-args=-fuse-ld=gold -W unused-extern-crates
export PATH=/home/wayling/test_tmp/servo/python/_virtualenv/bin:/home/wayling/systemtap:/home/wayling/.cargo/bin:/home/wayling/bin:/home/wayling/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/wayling/android_tool/SDK/platform-tools
Error running mach:

    ['env']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command. Consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

KeyError: u'LD_LIBRARY_PATH'

  File "/home/wayling/test_tmp/servo/python/servo/bootstrap_commands.py", line 46, in env
    print("export LD_LIBRARY_PATH=%s" % env["LD_LIBRARY_PATH"])
++++++++++++++++++++++++

2018-07-02 14:54 UTC, wayling commented
Other solution ,we could set a default value in env["LD_LIBRARY_PATH"] avoid unclear message.

2018-07-11 18:24 UTC, shinglyu commented
The error message is indeed confusing:
> The error occurred in the implementation of the invoked mach command.
> This should never occur and is likely a bug in the implementation of that command. Consider filing a bug for this issue.

Maybe we should just print something like:

```
LD_LIBRARY_PATH=(not set)
```
using the default value method you described?

2018-07-11 18:31 UTC, jdm requested changes

2018-07-11 18:31 UTC, jdm commented on python/servo/bootstrap_commands.py
> -            print("export LD_LIBRARY_PATH=%s" % env["LD_LIBRARY_PATH"])
Using shing's suggestion, we could use `env.get("LD_LIBRARY_PATH", "")` instead to avoid the error.

2018-07-17 18:45 UTC, jdm commented
Rather than setting the variable to an invalid value, it would be better to change the code which assumes that it exists like I suggested.

2018-07-28 14:07 UTC, jdm commented
@bors-servo r+
Thanks!

2018-07-28 14:07 UTC, bors-servo commented
:pushpin: Commit 2ad37bd has been approved by `jdm`

<!-- @bors-servo r=jdm 2ad37bda2c58cd8b79c645316bd1e4580a881a37 -->

2018-07-28 14:07 UTC, bors-servo commented
:hourglass: Testing commit 2ad37bda2c58cd8b79c645316bd1e4580a881a37 with merge 00c2489af0e774cfdfdcbac36008a77c841b940b...

2018-07-28 15:21 UTC, merged