[WIP] Introduce granular "per task source" cancellation
servo/servo pull request #21126
Opened 2018-07-05 04:35 UTC by gterzian

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #21119 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2018-07-05 04:35 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/task_source/file_reading.rs, components/script/task_source/user_interaction.rs, components/script/dom/websocket.rs, components/script/fetch.rs, components/script/dom/globalscope.rs and 14 more
 * @kichjang: components/script/task_source/file_reading.rs, components/script/task_source/user_interaction.rs, components/script/dom/websocket.rs, components/script/fetch.rs, components/script/dom/globalscope.rs and 14 more

2018-07-05 04:35 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-07-05 05:42 UTC, gterzian commented
This one is ready for review, although I'm wondering about the right testing strategy for this one...

2018-07-05 14:13 UTC, gterzian commented
For clarity this isn't suppose to 'change' anything about the behavior of the system, it only lays the groundwork to start changing behavior, for example in https://github.com/servo/servo/issues/21114, which will require using a dedicated task source for `EventSource` and then only cancelling the `networking tasks` as part of [document.abort](https://github.com/servo/servo/blob/0125e96555d86e27097172fe6132f32fcf3c8870/components/script/dom/document.rs#L2034), and letting the event source tasks run. 

So perhaps a good way to test is 'making sure everything still works as before', and then it is the follow up work that will include tests specifically asserting that certain tasks are cancelled while others still run?

2018-07-10 00:27 UTC, jdm requested changes

2018-07-10 04:45 UTC, gterzian commented on components/script/layout_image.rs
> +        canceller: Some(window.task_canceller(TaskSourceName::Networking)),
I've filed https://github.com/servo/servo/issues/21154

2018-07-10 05:04 UTC, gterzian commented
@jdm Thanks for the pointers, comments have been addressed...

2018-07-10 13:30 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/11870), [arm32](http://build.servo.org/builders/arm32/builds/12089), [arm64](http://build.servo.org/builders/arm64/builds/12137), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12176), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9084), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9088), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12227), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4643), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4666), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/8916), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/8967), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4729), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4663), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7575)
Approved by: jdm
Pushing 8988d674d0cbea59eaaa8c80f36f29d214682a0b to master...

2018-07-10 13:31 UTC, merged