WebAudio API
servo/servo pull request #21158
Opened 2018-07-10 15:55 UTC by ferjm

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #6710 (github issue number if applicable).
- [X] There are tests for these changes

This PR adds basic support for the WebAudio API using [servo-media](https://github.com/servo/media) with GStreamer as the audio backend.

There are still some major stuff to fix like:

- [ ] Detach ArrayBuffer during the [AudioBuffer "acquire the content" operation](https://webaudio.github.io/web-audio-api/#acquire-the-content). I am naively using JS_StealArrayBufferContents() directly, because it is what Gecko uses, but this should probably be part of the rust-mozjs typedarray API. And, in any case, I am not even sure if that's the proper way to do it. According to the results of the WPTs it may not even be right since [this assertion](https://github.com/servo/rust-mozjs/blob/master/src/typedarray.rs#L285) is failing in some cases. I need to dig more about this.
- [ ] Disable the GStreamer dependency on Android. Unfortunately gstreamer-rs requires an NDK version upgrade, so we need to disable this for Android until then. I tried adding [different features to servo-media](https://github.com/servo/media/pull/79), but I am currently hitting [this issue](https://github.com/rust-lang/cargo/issues/1197#issuecomment-268203727)

I still need to run servo-tidy, change the servo-media dependency to use the git repo and add/fix some comments and TODOs.

The remaining feature work should be done in future PRs.

Note that most of the failing WPTs are failing because we don't implement the tested features yet (we only implement a few AudioNodes) and we have no OfflineAudioContext support, which most WPTs rely on.

2018-07-10 15:55 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/periodicwave.rs, components/script/dom/webidls/OscillatorNode.webidl, components/script/Cargo.toml, components/script/dom/webidls/AudioBuffer.webidl, components/script/dom/mod.rs and 22 more
 * @jgraham: tests/wpt/include.ini
 * @kichjang: components/script/dom/periodicwave.rs, components/script/dom/webidls/OscillatorNode.webidl, components/script/Cargo.toml, components/script/dom/webidls/AudioBuffer.webidl, components/script/dom/mod.rs and 22 more

2018-07-10 15:55 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2018-07-10 16:00 UTC, Manishearth commented
r? @nox

2018-07-10 20:14 UTC, Manishearth commented
We should use a git dependency for servo-media, not a path dependency.

Either that or use a versioned dep but I'm okay with sticking to git while we're still working on it.

For the servo media stuff, how about we set things via stuff like https://github.com/ferjm/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/Cargo.toml#L26 ?

2018-07-10 21:01 UTC, Manishearth requested changes
> Reviewed 4 of 175 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servo/servo/21158)* status: 4 of 175 files reviewed, 11 unresolved discussions (waiting on @ferjm and @nox)

___
*[components/script/Cargo.toml, line 89 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4pgPe4Ab8AtpHpGUu:-LH4pgPgDFiu-5faav6m:bgwmmj3) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/Cargo.toml#L89)):*
> ```TOML
> servo_config = {path = "../config"}
> servo_geometry = {path = "../geometry" }
> servo_media = {path = "../../../media/servo-media"}
> ```

Should be a git or path dep
___
*[components/script/lib.rs, line 16 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4pkMu0h9YVylYRqDj:-LH4pkMu0h9YVylYRqDk:b-bqt4ls) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/lib.rs#L16)):*
> ```Rust
> #![allow(non_snake_case)]
> 
> #![recursion_limit = "128"]
> ```

This snuck in in one of my commits, we don't need it. This was an accident.
___
*[components/script/dom/audiobuffer.rs, line 26 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4qrU8DuegDqdEdWzW:-LH4qrU8DuegDqdEdWzX:b-iy0xju) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffer.rs#L26)):*
> ```Rust
> pub struct AudioBuffer {
>     reflector_: Reflector,
>     js_channels: DomRefCell<Vec<JSAudioChannel>>,
> ```

@nox should have a look at the arraybuffer code in this file
___
*[components/script/dom/audiobuffer.rs, line 38 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4qD7JEszeA2YeDbgH:-LH4qD7JEszeA2YeDbgI:b-8lsdjq) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffer.rs#L38)):*
> ```Rust
>     #[allow(unrooted_must_root)]
>     #[allow(unsafe_code)]
>     pub fn new_inherited(cx: *mut JSContext,
> ```

safe functions should never take raw pointers. We should pass global here.
___
*[components/script/dom/audiobuffer.rs, line 86 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4rcXR2CY_C49o-zGN:-LH4rcXSEKiY6IB9iqDE:b-184lqo) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffer.rs#L86)):*
> ```Rust
>     }
> 
>     pub fn Constructor(window: &Window,
> ```

spec link please
___
*[components/script/dom/audiobuffer.rs, line 89 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4rvtG9oQs1MI-cXPd:-LH4rvtH8VkqGaCl9Ob1:bgx1h3r) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffer.rs#L89)):*
> ```Rust
>                        options: &AudioBufferOptions) -> Fallible<DomRoot<AudioBuffer>> {
>         if options.numberOfChannels > MAX_CHANNEL_COUNT {
>             return Err(Error::NotSupported);
> ```

spec doesn't mention that we should error here?
___
*[components/script/dom/audiobuffer.rs, line 95 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4sEC_-GQd7osVFjfX:-LH4sEC_-GQd7osVFjfY:b-ah936h) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffer.rs#L95)):*
> ```Rust
> 
>     #[allow(unsafe_code)]
>     fn restore_js_channel_data(&self, cx: *mut JSContext) -> bool {
> ```

must be unsafe if we're operating on a raw pointer

(it is a safe operation to construct invalid raw pointers)

Though it's no big deal since this is private anywayn
___
*[components/script/dom/audiobuffersourcenode.rs, line 45 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4sf5YER5WSSvooZlD:-LH4sf5YER5WSSvooZlE:b-fnqnch) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffersourcenode.rs#L45)):*
> ```Rust
>     #[allow(unrooted_must_root)]
>     fn new_inherited(
>         window: &Window,
> ```

nit: rustfmt this
___
*[components/script/dom/audiobuffersourcenode.rs, line 123 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4tZI09q_by3_OY-Bh:-LH4tZI09q_by3_OY-Bi:b7zj1fl) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffersourcenode.rs#L123)):*
> ```Rust
>                 let buffer = buffer.acquire_contents();
>                 self.source_node.node().message(
>                     AudioNodeMessage::AudioBufferSourceNode(
> ```

this seems to be missing from the spec? perhaps we should add it.x
___
*[components/script/dom/audiocontext.rs, line 80 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4wXFo4jUZpkdiQE6P:-LH4wXFp5lmUCR-mG0aA:brduw7j) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiocontext.rs#L80)):*
> ```Rust
>         if self.context.is_allowed_to_start() {
>             // Step 6.
>             self.context.resume();
> ```

should we be queueing a statechange event here?
___
*[components/script/dom/audiocontext.rs, line 140 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4x3NA9TRGBnG8rKiY:-LH4x3NBEH5Zr0wPaWO_:btdkgy7) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiocontext.rs#L140)):*
> ```Rust
>                             atom!("statechange"),
>                             &window
>                             );
> ```

nit: rustfmt


<!-- Sent from Reviewable.io -->

2018-07-10 21:40 UTC, Manishearth requested changes
> Reviewed 169 of 175 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servo/servo/21158)* status: 173 of 175 files reviewed, 22 unresolved discussions (waiting on @ferjm and @nox)

___
*[components/script/dom/audionode.rs, line 78 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH53Pj42X0jgbtuV3mx:-LH53Pj42X0jgbtuV3my:btdkgy7) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audionode.rs#L78)):*
> ```Rust
> 
>         if output >= self.NumberOfOutputs() ||
>             input >= destination.NumberOfInputs() {
> ```

nit: rustfmt
___
*[components/script/dom/audionode.rs, line 82 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH53K4F4S8D1ZYrqaxp:-LH53K4F4S8D1ZYrqaxq:b-rad4ja) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audionode.rs#L82)):*
> ```Rust
>             }
> 
>         // XXX Check previous connections.
> ```

nit: this is unnecessary, `connect_ports` handles this and the spec doesn't ask for an error
___
*[components/script/dom/audionode.rs, line 178 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH53YhxB2PwpFgSLPtI:-LH53Yhy3iIcKqE6AJEs:b-b0bkrp) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audionode.rs#L178)):*
> ```Rust
> 
>     fn SetChannelCountMode(&self, value: ChannelCountMode) -> ErrorResult {
>         self.channel_count_mode.set(value);
> ```

we need to also message the nodes with SetChannelCountMode (you can `message_node` this), same for the count and interpretationx

And we must verify validity, we can do this by writing all the checks from https://webaudio.github.io/web-audio-api/#AudioNode-attributes, or we can have the SetChannelCountMode messages respond with an error state. I prefer the former.x
___
*[components/script/dom/audioparam.rs, line 78 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH54dDL1QfEIA5ZqbhO:-LH54dDM5nm7FWWSADWm:bokk4dp) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audioparam.rs#L78)):*
> ```Rust
> 
>     fn Value(&self) -> Finite<f32> {
>         // XXX
> ```

can you file issues on servo-media for all these todos and link to them in the comment?
___
*[components/script/dom/audioscheduledsourcenode.rs, line 46 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH55_5u8-4iDwtcQlyd:-LH55_5u8-4iDwtcQlye:b-waxucw) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audioscheduledsourcenode.rs#L46)):*
> ```Rust
> impl AudioScheduledSourceNodeMethods for AudioScheduledSourceNode {
>     // https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-onended
>     event_handler!(ended, GetOnended, SetOnended);
> ```

we should dispatch this when we reach the end (or have a fixme comment for the same)
___
*[components/script/dom/audioscheduledsourcenode.rs, line 56 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH55WX4-BOY2FIA9n9J:-LH55WX4-BOY2FIA9n9K:btdkgy7) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audioscheduledsourcenode.rs#L56)):*
> ```Rust
>         self.node.message(
>             AudioNodeMessage::AudioScheduledSourceNode(AudioScheduledSourceNodeMessage::Start(*when))
>             );
> ```

nit: rustfmt
___
*[components/script/dom/baseaudiocontext.rs, line 55 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH56LSP8QNDAGEaoDbm:-LH56LSP8QNDAGEaoDbn:b6h6pxr) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/baseaudiocontext.rs#L55)):*
> ```Rust
> 
> #[derive(JSTraceable)]
> #[allow(unrooted_must_root)]
> ```

I think this should be marked `#[must_root]`
___
*[components/script/dom/baseaudiocontext.rs, line 127 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH56utc6O0jWlGfkZoe:-LH56utc6O0jWlGfkZof:bqyrxbl) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/baseaudiocontext.rs#L127)):*
> ```Rust
>     }
> 
>     #[allow(unrooted_must_root)]
> ```

I'm not sure if we should be doing this?
___
*[components/script/dom/macros.rs, line 631 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH576-y8IAWY-GGjFEd:-LH576-y8IAWY-GGjFEe:b-dkcv0) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/macros.rs#L631)):*
> ```Rust
>         handle_potential_webgl_error!($context, $call, ());
>     };
> }
> ```

nit: no newline at end of file
___
*[components/script/dom/periodicwave.rs, line 15 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH57YyM3BYRPcJnP8ln:-LH57YyM3BYRPcJnP8lo:btvu0gx) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/periodicwave.rs#L15)):*
> ```Rust
> 
> #[dom_struct]
> pub struct PeriodicWave {
> ```

given that we don't yet support SetPeriodicWave perhaps we should just leave this unimplemented?
___
*[components/script/dom/webidls/PeriodicWave.webidl, line 5 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH57lfm57-06c3PYbNF:-LH57lfm57-06c3PYbNG:bnksgih) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/webidls/PeriodicWave.webidl#L5)):*
> ```WebIDL
>  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
> /*
>  * The origin of this IDL file is
> ```

ditto re: unimplemented stuff should be removed


<!-- Sent from Reviewable.io -->

2018-07-10 21:40 UTC, Manishearth commented
Reviewed everything except BaseAudioContext and AudioBuffer. I may start pushing fixes for some of these issues.

2018-07-10 21:48 UTC, Manishearth commented
Pushed some fixes for the basic stuff to this PR directly

2018-07-11 08:05 UTC, ferjm commented
> We should use a git dependency for servo-media, not a path dependency.

Yes. I mentioned this as pending task in the description :).

> For the servo media stuff, how about we set things via stuff like https://github.com/ferjm/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/Cargo.toml#L26 ?

Yes, that was the plan. Ideally we should be able to do something like https://github.com/servo/servo/issues/20475. But since that's currently not possible, I wanted to set servo-media as a dependency with different features (to use the dummy or the gst backend) depending on the platform. But I hit [this issue](https://github.com/rust-lang/cargo/issues/1197). I am trying to find a workaround. Setting `default-features = false` as suggested [here](https://github.com/rust-lang/cargo/issues/5005#issuecomment-362919288) does not work. Having different git branches with different default features does not work either. So I am afraid that I may end up:

- creating a new `servo-media-dummy` crate with the dummy backend as the default one and using stuff from `servo-media` or `servo-media-dummy` depending on the platform, like:

```rust
#[cfg(not(target_os = "android"))]
use servo_media::audio::buffer_source_node::AudioBuffer as ServoMediaAudioBuffer;
#[cfg(target_os = "android")]
use servo_media_dummy::audio::buffer_source_node::AudioBuffer as ServoMediaAudioBuffer;
``` 

- or messing up the entire patch with `cfg` clauses and `unimplemented!()` like:

```rust
#[cfg(not(target_os = "android"))]
pub fn Foo() {
  // Use servo-media stuff
}

#[cfg(target_os = "android")]
pub fn Foo() {
  unimplemented!()
}
```

I am really looking forward to hear about cleaner options :)

2018-07-11 14:44 UTC, ferjm reviewed
> *[Reviewable](https://reviewable.io/reviews/servo/servo/21158)* status: 161 of 175 files reviewed, 16 unresolved discussions (waiting on @Manishearth, @ferjm, and @nox)

___
*[components/script/dom/audiobuffer.rs, line 89 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4rvtG9oQs1MI-cXPd:-LH7Q1Ns3BBKpGqSao7p:b-klvzm9) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffer.rs#L89)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary><blockquote>

spec doesn't mention that we should error here?
</blockquote></details>

No, it doesn't. But I did what [Gecko](https://dxr.mozilla.org/mozilla-central/source/dom/media/webaudio/AudioBuffer.cpp#170) and [Blink](https://chromium.googlesource.com/chromium/blink/+/master/Source/modules/webaudio/AudioBuffer.cpp#58) do for this case. This may be missing from the spec. What's the alternative, down-mixing in this case?
___
*[components/script/dom/audiobuffersourcenode.rs, line 123 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4tZI09q_by3_OY-Bh:-LH7aAqu08-yhJI7GErD:bgyb2fk) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffersourcenode.rs#L123)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary><blockquote>

this seems to be missing from the spec? perhaps we should add it.x
</blockquote></details>

It's [there](https://webaudio.github.io/web-audio-api/#dom-audiobuffersourcenode-buffer), step 5.
___
*[components/script/dom/audiocontext.rs, line 80 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4wXFo4jUZpkdiQE6P:-LH7bF-58o8fONwbokfu:b4sekis) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiocontext.rs#L80)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary><blockquote>

should we be queueing a statechange event here?
</blockquote></details>

`BaseAudioContext.resume()` takes care of that [here](https://github.com/servo/servo/pull/21158/files#diff-8ce023e66ef9a7d2fc15319b24efecfbR206)
___
*[components/script/dom/audionode.rs, line 178 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH53YhxB2PwpFgSLPtI:-LH81TRi9nADS83RoB7l:b2qitvh) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audionode.rs#L178)):*
> And we must verify validity, we can do this by writing all the checks from https://webaudio.github.io/web-audio-api/#AudioNode-attributes, or we can have the SetChannelCountMode messages respond with an error state. I prefer the former.x

Note that with the set of nodes that we currently implement the two only constraint that applies are the ones for OfflineAudioContext (which we can implement by elimination) and the one for channel count and AudioDestinationNodes. In the latter case the constraint was already enforced by the `if` condition at the top of the function. The error thrown was not correct for AudioDestinationNodes though, it should be IndexSize instead of NotSupported. I fixed that and I left comments in the code so we don't forget about the other nodes.
___
*[components/script/dom/baseaudiocontext.rs, line 127 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH56utc6O0jWlGfkZoe:-LH8hmSD1rIuEJ_FaCho:b-8g5su9) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/baseaudiocontext.rs#L127)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary><blockquote>

I'm not sure if we should be doing this?
</blockquote></details>

I took this pattern from the [HTMLMediaElement implementation](https://dxr.mozilla.org/servo/source/components/script/dom/htmlmediaelement.rs#753) that has similar needs.


<!-- Sent from Reviewable.io -->

2018-07-11 16:30 UTC, Manishearth requested changes
> *[Reviewable](https://reviewable.io/reviews/servo/servo/21158)* status: 157 of 173 files reviewed, 13 unresolved discussions (waiting on @Manishearth, @ferjm, and @nox)

___
*[components/script/dom/audiobuffer.rs, line 89 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4rvtG9oQs1MI-cXPd:-LH98bAj4M8wBoOPJgig:b-35mqe7) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffer.rs#L89)):*
<details><summary><i>Previously, ferjm (Fernando Jiménez Moreno) wrote…</i></summary><blockquote>

No, it doesn't. But I did what [Gecko](https://dxr.mozilla.org/mozilla-central/source/dom/media/webaudio/AudioBuffer.cpp#170) and [Blink](https://chromium.googlesource.com/chromium/blink/+/master/Source/modules/webaudio/AudioBuffer.cpp#58) do for this case. This may be missing from the spec. What's the alternative, down-mixing in this case?
</blockquote></details>

I think we should get this added to the spec then
___
*[components/script/dom/audionode.rs, line 178 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH53YhxB2PwpFgSLPtI:-LH99tbuAtAPuOpZaC1-:b-hfghm4) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audionode.rs#L178)):*
<details><summary><i>Previously, ferjm (Fernando Jiménez Moreno) wrote…</i></summary><blockquote>

> And we must verify validity, we can do this by writing all the checks from https://webaudio.github.io/web-audio-api/#AudioNode-attributes, or we can have the SetChannelCountMode messages respond with an error state. I prefer the former.x

Note that with the set of nodes that we currently implement the two only constraint that applies are the ones for OfflineAudioContext (which we can implement by elimination) and the one for channel count and AudioDestinationNodes. In the latter case the constraint was already enforced by the `if` condition at the top of the function. The error thrown was not correct for AudioDestinationNodes though, it should be IndexSize instead of NotSupported. I fixed that and I left comments in the code so we don't forget about the other nodes.
</blockquote></details>

Sounds good


<!-- Sent from Reviewable.io -->

2018-07-11 23:47 UTC, Manishearth commented
https://github.com/servo/media/pull/84 fixes it for android. Once merged, you'll have to make a minor change -- script/Cargo.toml will have to call it `dependencies.servo-media` with a dash

2018-07-12 20:09 UTC, Manishearth commented
Okay, so one problem is that the travis builders are on trusty, and `libgstreamer1.0-dev` is pretty old (1.2.4) on that outdated distro.

Perhaps there's a PPA that we can get this from? I'm not sure how this works. cc @sdroege

2018-07-12 20:28 UTC, sdroege commented
Check the travis.yml of the gstreamer bindings. Basically a tarball with 1.14.1 binaries built for trusty. Not ideal but simple

2018-07-13 07:22 UTC, ferjm reviewed
> *[Reviewable](https://reviewable.io/reviews/servo/servo/21158)* status: 156 of 176 files reviewed, 13 unresolved discussions (waiting on @Manishearth, @ferjm, and @nox)

___
*[components/script/dom/audiobuffer.rs, line 89 at r1](https://reviewable.io/reviews/servo/servo/21158#-LH4rvtG9oQs1MI-cXPd:-LHHWFOaAp144Ay0W_3w:b-qyppnj) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/audiobuffer.rs#L89)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary><blockquote>

I think we should get this added to the spec then
</blockquote></details>

Actually, it is [there](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-createbuffer)


<!-- Sent from Reviewable.io -->

2018-07-13 07:40 UTC, sdroege commented on .travis.yml
> +            - libgtk-3-dev
You don't need libxml2 and gtk in your case, that's only needed for some of the (gtk-based) example applications in the GStreamer bindings repo :)

2018-07-13 07:40 UTC, sdroege commented on .travis.yml
> +        - curl -L https://people.freedesktop.org/~slomo/gstreamer.tar.gz | tar xz
I would recommend hosting this yourself as I might update this at any point to a newer version as required for my own uses of it. But if there's an update it shouldn't really affect how it works so maybe that's acceptable for you

2018-07-13 07:42 UTC, sdroege commented
> Disable the GStreamer dependency on Android. Unfortunately gstreamer-rs requires an NDK version upgrade, so we need to disable this for Android until then.

@ferjm Can you give some details why older NDK versions won't work and what exactly is needed?

2018-07-13 09:17 UTC, ferjm commented
> @ferjm Can you give some details why older NDK versions won't work and what exactly is needed?

I honestly don't remember the details of why I needed to upgrade from r12b to r16b to make gstreamer-rs build on Android. I need to revisit all that work soon, so I'll probably have more details then.

2018-07-13 20:02 UTC, Manishearth commented
Fixed the duplicate dependency thing, should be green on travis now

2018-07-13 20:32 UTC, Manishearth approved these changes

2018-07-13 21:13 UTC, Manishearth commented
Oh uh we need to figure out Appveyor too. Though we can also disable that for now

2018-07-13 21:31 UTC, sdroege commented
> Oh uh we need to figure out Appveyor too. Though we can also disable that for now

https://gstreamer.freedesktop.org/data/pkg/windows/1.14.1/ the two .msi files :)

2018-07-13 21:48 UTC, Manishearth reviewed
> Reviewed 1 of 2 files at r13, 2 of 5 files at r14, 9 of 10 files at r16, 1 of 2 files at r17, 1 of 1 files at r18, 10 of 11 files at r20.
> *[Reviewable](https://reviewable.io/reviews/servo/servo/21158)* status: 180 of 181 files reviewed, 12 unresolved discussions (waiting on @ferjm, @Manishearth, @sdroege, and @nox)



<!-- Sent from Reviewable.io -->

2018-07-13 22:23 UTC, Manishearth requested changes
> Reviewed 1 of 11 files at r20.
> *[Reviewable](https://reviewable.io/reviews/servo/servo/21158)* status: all files reviewed, 15 unresolved discussions (waiting on @ferjm, @Manishearth, @sdroege, and @nox)

___
*[components/script/dom/audiobuffer.rs, line 240 at r20](https://reviewable.io/reviews/servo/servo/21158#-LHKiaTXE0zDdTkWD4eY:-LHKiaTXE0zDdTkWD4eZ:b-6s880c) ([raw file](https://github.com/servo/servo/blob/7759bd454737a30cad1681b316117c5512e14119/components/script/dom/audiobuffer.rs#L240)):*
> ```Rust
>         let offset = start_in_channel as usize;
>         let mut dest = Vec::with_capacity(destination.len());
>         // let destination = unsafe { destination.as_mut_slice() };
> ```

remove this ?
___
*[components/script/dom/audiobuffer.rs, line 267 at r20](https://reviewable.io/reviews/servo/servo/21158#-LHKjNuX-7FRxMcNiOSo:-LHKjNuY-21i7NkLKjxi:b5t48je) ([raw file](https://github.com/servo/servo/blob/7759bd454737a30cad1681b316117c5512e14119/components/script/dom/audiobuffer.rs#L267)):*
> ```Rust
>     // https://webaudio.github.io/web-audio-api/#dom-audiobuffer-copytochannel
>     #[allow(unsafe_code)]
>     fn CopyToChannel(
> ```

should this method also be notifying consumers of the buffer?
___
*[components/script/dom/baseaudiocontext.rs, line 317 at r1](https://reviewable.io/reviews/servo/servo/21158#-LHKgAbF03lKxF_CIiuT:-LHKgAbG4pdoXdkMENMl:bjro0e4) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/baseaudiocontext.rs#L317)):*
> ```Rust
>     }
> 
>     #[allow(unrooted_must_root)]
> ```

what do we need this one for?
___
*[components/script/dom/baseaudiocontext.rs, line 351 at r13](https://reviewable.io/reviews/servo/servo/21158#-LHKgoTU2SeamHv0Gyk7:-LHKgoTU2SeamHv0Gyk8:b-dk23v4) ([raw file](https://github.com/servo/servo/blob/f2e9774ac0e5e57343c66e40e33cf275894a9e1d/components/script/dom/baseaudiocontext.rs#L351)):*
> ```Rust
>     fn DecodeAudioData(
>         &self,
>         audio_data: CustomAutoRooterGuard<ArrayBuffer>,
> ```

r? @nox on the typedarray / CustomAutoRooter stuff


<!-- Sent from Reviewable.io -->

2018-07-16 04:51 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #21182) made this pull request unmergeable. Please resolve the merge conflicts.

2018-07-16 08:39 UTC, ferjm reviewed
> *[Reviewable](https://reviewable.io/reviews/servo/servo/21158)* status: all files reviewed, 15 unresolved discussions (waiting on @ferjm, @Manishearth, @sdroege, and @nox)

___
*[components/script/dom/audiobuffer.rs, line 267 at r20](https://reviewable.io/reviews/servo/servo/21158#-LHKjNuX-7FRxMcNiOSo:-LHX9L5sAiHniplUUNGW:b-8o4doa) ([raw file](https://github.com/servo/servo/blob/7759bd454737a30cad1681b316117c5512e14119/components/script/dom/audiobuffer.rs#L267)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary><blockquote>

should this method also be notifying consumers of the buffer?
</blockquote></details>

The spec does not say anything about notifications in this case.
___
*[components/script/dom/baseaudiocontext.rs, line 317 at r1](https://reviewable.io/reviews/servo/servo/21158#-LHKgAbF03lKxF_CIiuT:-LHXEGzC06l45vJ6d7NJ:bsz96iq) ([raw file](https://github.com/servo/servo/blob/d4ca6a43854116ad8ca3438ea311a65b2c4d6f60/components/script/dom/baseaudiocontext.rs#L317)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary><blockquote>

what do we need this one for?
</blockquote></details>

Because of the Promise


<!-- Sent from Reviewable.io -->

2018-07-16 15:03 UTC, Manishearth commented
Right, the spec considers the AudioBuffer to be a single entity, whereas we've split it, so our AudioBuffer methods need to sync with the render thread

2018-07-16 16:09 UTC, ferjm commented
Sorry, I misunderstood the concept of <i>consumer</i> here. I thought you were referring to the web API consumers.

I believe there is no need to notify the render thread with every call to `CopyToChannel`. The render thread gets the content of the buffer through the `acquire_contents` method in the cases specified [here](https://webaudio.github.io/web-audio-api/#acquire-the-content). Basically, in our case so far: on `AudioBufferSourceNode.start` and on the `AudioBufferSourceNode.buffer` setter.

According to the spec:

> This means that copyToChannel() cannot be used to change the content of an AudioBuffer currently in use by an AudioNode that has acquired the content of an AudioBuffer since the AudioNode will continue to use the data previously acquired.

That's why we throw [here](https://github.com/servo/servo/pull/21158/files#diff-283a0876813dfac4e3e438183e043a12R284)

2018-07-16 20:47 UTC, Manishearth commented
Note that Appveyor fails before the gstreamer crate on glib-sys:

```
    Running `rustc --crate-name gl_generator C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gl_generator-0.9.0\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=c1477e6709ca0b0a -C extra-filename=-c1477e6709ca0b0a --out-dir C:\projects\servo\target\debug\deps -L dependency=C:\projects\servo\target\debug\deps --extern khronos_api=C:\projects\servo\target\debug\deps\libkhronos_api-d4071c769d177165.rlib --extern log=C:\projects\servo\target\debug\deps\liblog-dacbe27e19dfbf76.rlib --extern xml=C:\projects\servo\target\debug\deps\libxml-bbc771db5150d339.rlib --cap-lints allow -Dwarnings -W unused-extern-crates`
     Running `C:\projects\servo\target\debug\build\libz-sys-b5e64aa39b0ab78c\build-script-build`
     Running `C:\projects\servo\target\debug\build\glib-sys-e17e8543623df82a\build-script-build`
error: failed to run custom build command for `glib-sys v0.6.0`
process didn't exit successfully: `C:\projects\servo\target\debug\build\glib-sys-e17e8543623df82a\build-script-build` (exit code: 1)
--- stderr
MSVC target detected. If you are using the MSVC ABI rust build, please use the GNU ABI build instead.
warning: build failed, waiting for other jobs to finish...
```

I don't think we want to switch to a GNU build on appveyor?

2018-07-16 22:32 UTC, Manishearth commented
Appveyor seems stuck :/

2018-07-16 22:33 UTC, Manishearth commented
removing the appveyor part for now -- @sdroege do you have examples for the full set of steps here?

2018-07-17 06:44 UTC, ferjm commented
> I don't think we want to switch to a GNU build on appveyor?

https://github.com/sdroege/gstreamer-rs/issues/90 :\

We may need to go back to the GNU build until that's fixed or disable for Windows.

2018-07-17 06:48 UTC, sdroege commented
> sdroege/gstreamer-rs#90 :\
> 
> We may need to go back to the GNU build until that's fixed or disable for Windows.

For someone who cares trying, https://github.com/alexcrichton/pkg-config-rs/issues/59 might be a one-liner :)

But no, I'm not running builds on appveyor yet. Didn't get to it so far. But I've done manual builds on Windows with the mingw toolchain

2018-07-17 08:15 UTC, nox commented
```
let mut js_channels: Vec<JSAudioChannel> = Vec::with_capacity(number_of_channels as usize);
```

Those things need to be rooted.

2018-07-18 06:43 UTC, ferjm commented
> For someone who cares trying, alexcrichton/pkg-config-rs#59 might be a one-liner :)

https://github.com/alexcrichton/pkg-config-rs/pull/70

2018-07-18 09:37 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #21196) made this pull request unmergeable. Please resolve the merge conflicts.

2018-07-18 14:43 UTC, ferjm commented
There is something fishy with the AudioBuffer/AudioBufferSource implementation :\ . I see [this crash](https://gist.github.com/ferjm/785c05ab696b003f5b6c63f38978ffa3) trying to run a simple test like https://ferjm.github.io/web-api-tests/webaudio/decode.html

2018-07-18 15:40 UTC, jdm commented
You may need to enter a compartment. Building with debug-mozjs would probably make the problem more clear.

2018-07-18 22:30 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #21202) made this pull request unmergeable. Please resolve the merge conflicts.

2018-07-19 08:10 UTC, ferjm commented
> You may need to enter a compartment. Building with debug-mozjs would probably make the problem more clear.

I don't understand why, but entering a compartment fixed the issue. Thanks!

2018-07-19 19:57 UTC, Manishearth commented
FWIW this is reviewed, we can land this r=me,nox

Probably still need infra stuff though.

@bors-servo try

2018-07-19 19:57 UTC, bors-servo commented
:lock: Merge conflict

2018-07-19 20:29 UTC, Manishearth commented
Yeah but we also need to make sure it works on buildbot while I look into fixing that

2018-07-19 20:37 UTC, jdm commented
https://github.com/servo/saltfs/pull/857 will need to be merged and deployed, and travisCI macOS is busted on saltfs right now.

2018-07-20 22:10 UTC, Manishearth commented
This still errors on `  = note: LINK : fatal error LNK1181: cannot open input file 'gstaudio-1.0.lib'` in appveyor, even though the msis are installed. Not sure what's going on.

2018-07-23 12:00 UTC, ferjm commented
> This still errors on = note: LINK : fatal error LNK1181: cannot open input file 'gstaudio-1.0.lib' in appveyor, even though the msis are installed. Not sure what's going on.

This works now. We needed to set the path to the gstreamer libs.

2018-07-23 16:20 UTC, Manishearth commented
appveyor builds!

Now we need to land https://github.com/servo/saltfs/pull/857 (and the corresponding windows one) which depends on the salt build being fixed

2018-07-24 14:52 UTC, ferjm commented
> This should be fixed by alexcrichton/pkg-config-rs#71. Providing the library path manually is wrong, that's exactly what pkg-config is good for :)

Ah, nice. I'll test the fix and remove the workaround from the appveyor config (after reinstalling my Windows VM :-) ). Thanks!

2018-07-25 23:31 UTC, Manishearth commented
@bors-servo try

deployed gstreamer changes temporarily

expect windows to break, but everything else should work

2018-07-25 23:31 UTC, bors-servo commented
:hourglass: Trying commit b5ab1202fa0d6f563ded25248dc55902985c114e with merge 9a2abd7a9cdb6fe2781c3ccb8853349536ddfa42...

2018-07-25 23:34 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9215)

2018-07-25 23:40 UTC, Manishearth commented
Perhaps we should have the servo-media build fetch gstreamer?

2018-07-26 22:33 UTC, Manishearth commented
@bors-servo retry 

got it into the environment, trying again

2018-07-26 22:46 UTC, Manishearth commented
@bors-servo retry try

2018-07-26 22:46 UTC, bors-servo commented
:hourglass: Trying commit b5ab1202fa0d6f563ded25248dc55902985c114e with merge d27c3b2f58afac879d67e087535ea0b64fe987cf...

2018-07-26 22:49 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9220)

2018-07-26 22:55 UTC, Manishearth commented
@bors-servo retry try

2018-07-26 22:55 UTC, bors-servo commented
:hourglass: Trying commit b5ab1202fa0d6f563ded25248dc55902985c114e with merge 65c8145766109a3eb39d74b6098ab0ecfabd3039...

2018-07-26 23:04 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/12305)

2018-07-26 23:13 UTC, Manishearth commented
@bors-servo retry try

2018-07-26 23:13 UTC, bors-servo commented
:hourglass: Trying commit b5ab1202fa0d6f563ded25248dc55902985c114e with merge 4f3bfcb537f4c5983985d0af986646619175c316...

2018-07-26 23:13 UTC, bors-servo commented
:broken_heart: Test failed - [arm64](http://build.servo.org/builders/arm64/builds/12262)

2018-07-26 23:18 UTC, Manishearth commented
@bors-servo retry try

2018-07-26 23:18 UTC, bors-servo commented
:hourglass: Trying commit b5ab1202fa0d6f563ded25248dc55902985c114e with merge bc5fc0e51c5e86b3d751cd8eb9602897ce834194...

2018-07-26 23:18 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4782)

2018-07-26 23:47 UTC, Manishearth commented
@bors-servo retry try

2018-07-26 23:48 UTC, bors-servo commented
:hourglass: Trying commit b5ab1202fa0d6f563ded25248dc55902985c114e with merge 10399f72a0dea5594b17828215b635ea086eab5e...

2018-07-26 23:48 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4864)

2018-07-26 23:51 UTC, Manishearth commented
```
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-analysernode-interface/test-analyser-output.html", "line": 117369, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-analysernode-interface/test-analysernode.html", "line": 124336, "action": "test_result", "expected": "OK"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nthrow@http://web-platform.test:8000/webaudio/resources/audit.js:334:14\n@http://web-platform.test:8000/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.html:24:13\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1177:7\n_runNextTask@http://web-platform.test:8000/webaudio/resources/audit.js:1236:9\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1306:7\n@http://web-platform.test:8000/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.html:200:7\n", "subtest": "X new OfflineAudioContext(3) threw \"ReferenceError\" instead of function TypeError() {\n    [native code]\n}.", "test": "/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.html", "line": 127994, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nthrow@http://web-platform.test:8000/webaudio/resources/audit.js:334:14\n@http://web-platform.test:8000/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.html:29:13\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1177:7\n_runNextTask@http://web-platform.test:8000/webaudio/resources/audit.js:1236:9\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1306:7\n@http://web-platform.test:8000/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.html:200:7\n", "subtest": "X new OfflineAudioContext(3, 42) threw \"ReferenceError\" instead of function TypeError() {\n    [native code]\n}.", "test": "/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.html", "line": 127995, "action": "test_result", "expected": "PASS"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-audioworklet-interface/audioworkletnode-construction.https.html", "line": 131351, "action": "test_result", "expected": "ERROR"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-messageport.https.html", "line": 137982, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-audioparam-interface/audioparam-method-chaining.html", "line": 138712, "action": "test_result", "expected": "ERROR"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-constantsourcenode-interface/test-constantsourcenode.html", "line": 138946, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-analysernode-interface/test-analyser-scale.html", "line": 144745, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-basic.html", "line": 145710, "action": "test_result", "expected": "ERROR"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-addmodule-resolution.https.html", "line": 165221, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-audioworklet-interface/audioworkletprocessor-options.https.html", "line": 165442, "action": "test_result", "expected": "ERROR"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-constantsourcenode-interface/constant-source-basic.html", "line": 165732, "action": "test_result", "expected": "ERROR"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-pannernode-interface/pannernode-basic.html", "line": 166150, "action": "test_result", "expected": "ERROR"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-audiobuffer-interface/audiobuffer-getChannelData.html", "line": 167128, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-audioworklet-interface/baseaudiocontext-audioworklet.https.html", "line": 169983, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-stereopanner-interface/stereopannernode-basic.html", "line": 170420, "action": "test_result", "expected": "ERROR"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/webaudio/the-audio-api/the-gainnode-interface/gain-basic.html", "line": 197545, "action": "test_result", "expected": "OK"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@https://web-platform.test:8443/webaudio/resources/audit.js:50:7\nTest.prototype.step@https://web-platform.test:8443/resources/testharness.js:1538:20\ntest@https://web-platform.test:8443/resources/testharness.js:545:9\n_logFailed@https://web-platform.test:8443/webaudio/resources/audit.js:49:5\n_finalize@https://web-platform.test:8443/webaudio/resources/audit.js:215:9\n_assert@https://web-platform.test:8443/webaudio/resources/audit.js:228:7\nnotThrow@https://web-platform.test:8443/webaudio/resources/audit.js:362:14\n@https://web-platform.test:8443/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-audioparam-size.https.html:24:9\nrun@https://web-platform.test:8443/webaudio/resources/audit.js:1177:7\n_runNextTask@https://web-platform.test:8443/webaudio/resources/audit.js:1236:9\nrun@https://web-platform.test:8443/webaudio/resources/audit.js:1306:7\n@https://web-platform.test:8443/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-audioparam-size.https.html:93:7\n", "subtest": "X Creating offline context for testing incorrectly threw ReferenceError: \"OfflineAudioContext is not defined\".", "test": "/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-audioparam-size.https.html", "line": 19926 [...]

2018-07-26 23:56 UTC, Manishearth commented
https://github.com/servo/media/pull/96 for the ARM failures.

OSX seems to be somewhat broken wrt certs

2018-07-27 07:15 UTC, ferjm commented
> @ferjm while I still work on the infra stuff, want to figure these out? Most of them are minor, but a bunch have a crash on .resume()

Yes.

I expect to finish the OfflineAudioContext bits today, which should also help us reduce the number of WPTs failures.

2018-07-27 16:53 UTC, Manishearth commented
@bors-servo try retry

Want to ensure the builds all work now, and also let's see what WPT looks like

done with infra so i can chip away at WPT today

2018-07-27 17:56 UTC, Manishearth commented
@bors-servo try retry

2018-07-27 19:39 UTC, Manishearth commented
@bors-servo try retry

2018-07-27 19:51 UTC, Manishearth commented
@bors-servo try retry clean

2018-07-27 19:55 UTC, Manishearth commented
@bors-servo try-

2018-07-27 19:55 UTC, Manishearth commented
@bors-servo r- clean

2018-07-27 19:55 UTC, Manishearth commented
@bors-servo retry try

2018-07-27 19:56 UTC, Manishearth commented
@bors-servo retry try

2018-07-27 19:56 UTC, bors-servo commented
:hourglass: Trying commit 4bc9e01139c3d42bd935b5079856f3b42ff5657b with merge ac1a0bc3f9f75f78cf042adee5e8ff7acacaa8ab...

2018-07-27 20:05 UTC, Manishearth approved these changes

2018-07-27 20:36 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/12312)

2018-07-27 20:52 UTC, Manishearth commented
```
 0:10.61 INFO Diffing old and new manifests /home/servo/buildbot/slave/linux-dev/build/tests/wpt/metadata/MANIFEST.json
 0:13.93 INFO Diffing old and new manifests /home/servo/buildbot/slave/linux-dev/build/tests/wpt/mozilla/meta/MANIFEST.json
 0:14.27 WARNING Manifest /home/servo/buildbot/slave/linux-dev/build/tests/wpt/mozilla/meta/MANIFEST.json contains correct tests but file hashes changed.
 0:14.28 ERROR Manifest /home/servo/buildbot/slave/linux-dev/build/tests/wpt/mozilla/meta/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
```


```
 (view as text)

{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nthrow@http://web-platform.test:8000/webaudio/resources/audit.js:334:14\ntestDistanceLimits@http://web-platform.test:8000/webaudio/the-audio-api/the-pannernode-interface/panner-distance-clamping.html:37:9\n@http://web-platform.test:8000/webaudio/the-audio-api/the-pannernode-interface/panner-distance-clamping.html:21:9\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1177:7\n_runNextTask@http://web-platform.test:8000/webaudio/resources/audit.js:1236:9\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1306:7\n@http://web-platform.test:8000/webaudio/the-audio-api/the-pannernode-interface/panner-distance-clamping.html:230:7\n", "subtest": "X new PannerNode(c, {refDistance: -1}) threw \"ReferenceError\" instead of function RangeError() {\n    [native code]\n}.", "test": "/webaudio/the-audio-api/the-pannernode-interface/panner-distance-clamping.html", "line": 126637, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "(Stack trace unavailable)", "subtest": "X Number of discontinuities is not less than 100. Got 100.", "test": "/webaudio/the-audio-api/the-audioparam-interface/audioparam-setValueAtTime.html", "line": 132039, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nbeEqualTo@http://web-platform.test:8000/webaudio/resources/audit.js:488:14\nverifyDiscontinuities@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:309:9\ncompareSignals@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:354:9\ncheckResultFunction/<@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:406:7\n", "subtest": "X Discontinuity at index is not equal to 14553. Got 14552.", "test": "/webaudio/the-audio-api/the-audioparam-interface/audioparam-setValueAtTime.html", "line": 132049, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nbeEqualTo@http://web-platform.test:8000/webaudio/resources/audit.js:488:14\nverifyDiscontinuities@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:309:9\ncompareSignals@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:354:9\ncheckResultFunction/<@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:406:7\n", "subtest": "X Discontinuity at index is not equal to 19845. Got 19844.", "test": "/webaudio/the-audio-api/the-audioparam-interface/audioparam-setValueAtTime.html", "line": 132050, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nbeEqualTo@http://web-platform.test:8000/webaudio/resources/audit.js:488:14\nverifyDiscontinuities@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:309:9\ncompareSignals@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:354:9\ncheckResultFunction/<@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:406:7\n", "subtest": "X Discontinuity at index is not equal to 25137. Got 25136.", "test": "/webaudio/the-audio-api/the-audioparam-interface/audioparam-setValueAtTime.html", "line": 132051, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nbeEqualTo@http://web-platform.test:8000/webaudio/resources/audit.js:488:14\nverifyDiscontinuities@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:309:9\ncompareSignals@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:354:9\ncheckResultFunction/<@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:406:7\n", "subtest": "X Discontinuity at index is not equal to 29106. Got 29105.", "test": "/webaudio/the-audio-api/the-audioparam-interface/audioparam-setValueAtTime.html", "line": 132052, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nbeEqualTo@http://web-platform.test:8000/webaudio/resources/audit.js:488:14\nverifyDiscontinuities@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:309:9\ncompareSignals@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:354:9\ncheckResultFunction/<@http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:406:7\n", "subtest": "X Discontinuity at index is not equal to  [...]

2018-07-27 23:04 UTC, Manishearth commented
I'm having weird issues running the tests locally:

```
 0:04.32 pid:28302 ERROR 2018-07-27T22:02:58Z: script::dom::bindings::error: Error at http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:509:5 ArrayBuffer object required
```

I _suspect_ this is due to how we construct the array buffer, we shouldn't be doing any rooting in new_inherited

I'm trying a better way:

<details>

```patch
diff --git a/components/script/dom/audiobuffer.rs b/components/script/dom/audiobuffer.rs
index 3f1c5f2f44..0e7a758d19 100644
--- a/components/script/dom/audiobuffer.rs
+++ b/components/script/dom/audiobuffer.rs
@@ -11,12 +11,11 @@ use dom::bindings::reflector::{DomObject, Reflector, reflect_dom_object};
 use dom::bindings::root::DomRoot;
 use dom::window::Window;
 use dom_struct::dom_struct;
-use js::jsapi::{DetachDataDisposition, Heap, JSAutoCompartment, JSContext, JSObject, JS_DetachArrayBuffer};
+use js::jsapi::{DetachDataDisposition, Heap, JSContext, JSObject, JS_DetachArrayBuffer};
 use js::rust::CustomAutoRooterGuard;
 use js::typedarray::{CreateWith, Float32Array};
 use servo_media::audio::buffer_source_node::AudioBuffer as ServoMediaAudioBuffer;
 use std::cmp::min;
-use std::mem;
 use std::ptr::{self, NonNull};
 
 // This range is defined by the spec.
@@ -42,47 +41,15 @@ impl AudioBuffer {
     #[allow(unrooted_must_root)]
     #[allow(unsafe_code)]
     pub fn new_inherited(
-        global: &Window,
         number_of_channels: u32,
         length: u32,
         sample_rate: f32,
-        initial_data: Option<&[f32]>,
     ) -> AudioBuffer {
-        let cx = global.get_cx();
-        let _ac = JSAutoCompartment::new(cx, global.reflector().get_jsobject().get());
-        rooted_vec!(let mut js_channels_);
-        for channel in 0..number_of_channels {
-            rooted!(in (cx) let mut array = ptr::null_mut::<JSObject>());
-            let offset = (channel * length) as usize;
-            match initial_data {
-                Some(data) => {
-                    let _ = unsafe {
-                        Float32Array::create(
-                            cx,
-                            CreateWith::Slice(&data[offset..offset + (length as usize) - 1]),
-                            array.handle_mut(),
-                        )
-                    };
-                },
-                None => {
-                    let _ = unsafe {
-                        Float32Array::create(
-                            cx,
-                            CreateWith::Slice(&vec![0.; length as usize]),
-                            array.handle_mut(),
-                        )
-                    };
-                }
-            }
-            let js_channel = Heap::default();
-            js_channel.set(array.get());
-            js_channels_.push(js_channel);
-        }
-        let js_channels = DomRefCell::new(Vec::new());
-        mem::swap(&mut *js_channels.borrow_mut(), &mut *js_channels_);
+        let vec = (0..number_of_channels).map(|_| Heap::default()).collect();
+
         AudioBuffer {
             reflector_: Reflector::new(),
-            js_channels,
+            js_channels: DomRefCell::new(vec),
             shared_channels: DomRefCell::new(ServoMediaAudioBuffer::new(
                 number_of_channels as u8,
                 length as usize,
@@ -103,13 +70,13 @@ impl AudioBuffer {
         initial_data: Option<&[f32]>,
     ) -> DomRoot<AudioBuffer> {
         let buffer = AudioBuffer::new_inherited(
-            global,
             number_of_channels,
             length,
             sample_rate,
-            initial_data,
         );
-        reflect_dom_object(Box::new(buffer), global, AudioBufferBinding::Wrap)
+        let buffer = reflect_dom_object(Box::new(buffer), global, AudioBufferBinding::Wrap);
+        buffer.set_channels(initial_data);
+        buffer
     }
 
     // https://webaudio.github.io/web-audio-api/#dom-audiobuffer-audiobuffer
@@ -188,6 +155,37 @@ impl AudioBuffer {
 
         Some((*self.shared_channels.borrow()).clone())
     }
+
+    #[allow(unsafe_code)]
+    pub fn set_channels(&self, initial_data: Option<&[f32]>) {
+        let cx = self.global().get_cx();
+        let chans = self.js_channels.borrow_mut();
+        for channel in 0..self.number_of_channels {
+            rooted!(in (cx) let mut array = ptr::null_mut::<JSObject>());
+            let offset = (channel * self.length) as usize;
+            match initial_data {
+                Some(data) => {
+                    let _ = unsafe {
+                        Float32Array::create(
+                            cx,
+                            CreateWith::Slice(&data[offset..offset + (self.length as usize) - 1]),
+                            array.handle_mut(),
+                        )
+                    };
+                },
+                None => {
+                    let _ = unsafe {
+                        Float32Array::create(
+                            cx,
+                            CreateWith::Slice(&vec![0.; self.length as usize]),
+                            array.handle_mut(),
+                        )
+                    };
+                }
+            }
+            chans[channel as usize].set(array.get());
+        }
+    }
 }
 
 impl AudioBufferMethods for AudioBuffer {
```
</details>

but then I get the same error _and_ a weird crash:

<details>

```
 0:05.90 pid:10253 Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }"
 0:05.90 pid:10253 stack backtrace:
 0:05.90 pid:10253    0:     0x55afe83d9a25 - backtrace::backtrace::libunwind::trace::hc38180d489d66153
 0:05.91 pid:10253                         at /home/manishearth/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
 0:05.91 pid:10253                          - backtrace::backtrace::trace::h78a15d6884d51e5b
 0:05.91 pid:10253                         at /home/manishearth/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
 0:05.91 pid:10253    1:     0x55afe83d77ee - backtrace::capture::Backtrace::new::h9229778bab1a1cd5
 0:05.91 pid:10253                         at /home/manishearth/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
 0:05.91 pid:10253    2:     0x55afe0d6a854 - servo::install_crash_handler::handler::h4ab049dfff60ae2d
 0:05.91 pid:10253                         at ports/servo/main.rs:86
 0:05.91 pid:10253    3:     0x55afe78e2324 - AsmJSFaultHandler
 0:05.91 pid:10253                         at /home/manishearth/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.51.4/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
 0:05.91 pid:10253    4:     0x7f80fa8b288f - <unknown>
 0:05.91 pid:10253    5:     0x55afe743dd08 - _ZN7mozilla7VariantIJN2js17ImmediateMetadataENS1_13DelayMetadataEP8JSObjectEEC4ERKS6_
 0:05.91 pid:10253                         at /home/manishearth/mozilla/servo/target/debug/build/mozjs_sys-278912b5aff76e16/out/dist/include/mozilla/Variant.h:456
 0:05.91 pid:10253                          - _ZN2js24AutoSetNewObjectMetadataC2EPNS_16ExclusiveContextE
 0:05.91 pid:10253                         at /home/manishearth/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.51.4/mozjs/js/src/jscompartment.cpp:1248
 0:05.91 pid:10253    6:     0x55afe7525a94 - _ZN2js17ArrayBufferObject6createEP9JSContextjNS0_14BufferContentsENS0_9OwnsStateEN2JS6HandleIP8JSObjectEENS_13NewObjectKindE
 0:05.91 pid:10253                         at /home/manishearth/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.51.4/mozjs/js/src/vm/ArrayBufferObject.cpp:657
 0:05.91 pid:10253    7:     0x55afe7525e17 - _ZN2js17ArrayBufferObject6createEP9JSContextjN2JS6HandleIP8JSObjectEENS_13NewObjectKindE
 0:05.91 pid:10253                         at /home/manishearth/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.51.4/mozjs/js/src/vm/ArrayBufferObject.cpp:6 [...]

2018-07-27 23:04 UTC, Manishearth commented
@jdm do you notice anything off in audiobuffer.rs? It does a lot of ArrayBuffer stuff which may not be working right.

2018-07-27 23:05 UTC, Manishearth commented
Also worth mentioning I can't reproduce that error outside of the WPT test at all

2018-07-30 11:39 UTC, ferjm commented
> I'm having weird issues running the tests locally:
 0:04.32 pid:28302 ERROR 2018-07-27T22:02:58Z: script::dom::bindings::error: Error at http://web-platform.test:8000/webaudio/resources/audioparam-testing.js:509:5 ArrayBuffer object require

This is happening inside [SM's `JS_DetachArrayBuffer`](https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/src/vm/ArrayBufferObject.cpp#L1181).

> but then I get the same error and a weird crash

This crash is similar to the one I mentioned [here](https://github.com/servo/servo/pull/21158#issuecomment-405956289) that was fixed by entering a compartment, as @jdm suggested.

2018-07-30 14:21 UTC, ferjm commented
> This is happening inside SM's JS_DetachArrayBuffer.

I have no idea how to get an ArrayBuffer from the Float32Array, which is what `JS_DetachArrayBuffer` expects.

2018-07-30 17:01 UTC, Manishearth commented
Oh, I removed the autocompartment thing because it seemed unused. Adding it again :smile:

2018-07-30 17:06 UTC, ferjm commented
I wanted to test if your patch made any difference, so I already pushed the changes with the autocompartment thing.

2018-07-30 17:21 UTC, Manishearth commented
Oh, I didn't realize that. Neat! With the compartment thing it doesn't crash, but I still get the arraybuffer error when testing locally.

2018-07-30 18:40 UTC, jdm requested changes

2018-07-30 18:40 UTC, jdm commented on components/script/dom/audiobuffer.rs
> +                        JS_DetachArrayBuffer(cx, channel.handle(), DetachDataDisposition::KeepData);
This needs to be passed the result of [JS_GetArrayBufferViewBuffer](https://github.com/servo/mozjs/blob/master/mozjs/js/src/jsfriendapi.h#L2094-L2100) like https://searchfox.org/mozilla-central/source/dom/media/webaudio/AudioBuffer.cpp#445.

2018-07-30 22:46 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9264)

2018-07-31 00:36 UTC, Manishearth commented
There are a couple of weird failures with audioparams, I fixed some but I feel like we should focus on getting this landed first so we can whittle away at the failures later.

2018-07-31 00:36 UTC, Manishearth commented
@bors-servo try retry

2018-07-31 00:36 UTC, bors-servo commented
:hourglass: Trying commit c77991c5e658ad4f5bc3b1ed918742cb01fe823d with merge 58c1f352162d84c2c98f490b318605f20ed3e894...

2018-07-31 01:03 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9273)

2018-07-31 01:52 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9275)

2018-07-31 06:44 UTC, Manishearth commented
@bors-servo r=manishearth,nox,ferjm

2018-07-31 06:44 UTC, bors-servo commented
:pushpin: Commit 2daf9ff has been approved by `manishearth,nox,ferjm`

<!-- @bors-servo r=manishearth,nox,ferjm 2daf9ff3eb3006101b36aa2e1a31b9024d9f3b0d -->

2018-07-31 06:44 UTC, bors-servo commented
:hourglass: Testing commit 2daf9ff3eb3006101b36aa2e1a31b9024d9f3b0d with merge e8554b5c6731efb873462d53d78738df6b77cf1d...

2018-07-31 06:44 UTC, Manishearth commented
@bors-servo delegate+

2018-07-31 06:44 UTC, bors-servo commented
:v: @ferjm can now approve this pull request

2018-07-31 07:10 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/12060)

2018-07-31 09:36 UTC, ferjm commented
@bors-servo retry

- Disk space issues?

2018-07-31 09:45 UTC, bors-servo commented
:zap: Previous build results for [android-x86](http://build.servo.org/builders/android-x86/builds/176), [arm32](http://build.servo.org/builders/arm32/builds/12264), [arm64](http://build.servo.org/builders/arm64/builds/12308), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12356), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9272), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9276), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12400), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4829), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4835), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9141), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4909), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4850), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7757) are reusable. Rebuilding only [android](http://build.servo.org/builders/android/builds/12060), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9102)...

2018-07-31 10:29 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/12063)

2018-07-31 10:31 UTC, ferjm commented
```
install: error writing '/home/servo/buildbot/slave/android/build/target/armv7-linux-androideabi/debug/apk/jniLibs/armeabi-v7a/libservo.so': No space left on device
install: failed to extend '/home/servo/buildbot/slave/android/build/target/armv7-linux-androideabi/debug/apk/jniLibs/armeabi-v7a/libservo.so': No space left on device
make: *** [/home/servo/buildbot/slave/android/build/target/armv7-linux-androideabi/debug/apk/jniLibs/armeabi-v7a/libservo.so] Error 1
make: *** Deleting file `/home/servo/buildbot/slave/android/build/target/armv7-linux-androideabi/debug/apk/jniLibs/armeabi-v7a/libservo.so'
```

2018-07-31 12:59 UTC, jdm commented
@bors-servo retry
* cleaned up build machine

2018-07-31 13:00 UTC, bors-servo commented
:hourglass: Testing commit 2daf9ff3eb3006101b36aa2e1a31b9024d9f3b0d with merge 0051597525797c4404cdc460389fe27780729626...

2018-07-31 13:39 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9276)

2018-07-31 13:48 UTC, ferjm commented
@bors-servo retry

* #21292

2018-07-31 13:48 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/12065), [android-x86](http://build.servo.org/builders/android-x86/builds/180), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12360), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9280), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12404) are reusable. Rebuilding only [arm32](http://build.servo.org/builders/arm32/builds/12268), [arm64](http://build.servo.org/builders/arm64/builds/12312), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9276), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4833), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4839), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9107), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9145), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4913), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4855), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7761)...

2018-07-31 15:47 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12065), [android-x86](http://build.servo.org/builders/android-x86/builds/180), [arm32](http://build.servo.org/builders/arm32/builds/12268), [arm64](http://build.servo.org/builders/arm64/builds/12312), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12360), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9278), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9280), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12404), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/4833), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/4839), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9107), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9145), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/4913), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4855), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/7761)
Approved by: manishearth,nox,ferjm
Pushing 0051597525797c4404cdc460389fe27780729626 to master...

2018-07-31 15:47 UTC, merged