Properly check limit in gl.activeTexture()
servo/servo pull request #21341
Opened 2018-08-03 16:29 UTC by nox

2018-08-03 16:29 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webglrenderingcontext.rs, components/script/dom/webgl_validations/tex_image_2d.rs
 * @kichjang: components/script/dom/webglrenderingcontext.rs, components/script/dom/webgl_validations/tex_image_2d.rs

2018-08-03 16:29 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-08-03 17:14 UTC, jdm requested changes
I haven't looked at the rest of the changes, but this stuck out to me.

2018-08-03 17:14 UTC, jdm commented on components/canvas/webgl_thread.rs
> +                        ctx.gl().get_integer_v(
This duplicates https://github.com/servo/rust-offscreen-rendering-context/blob/master/src/gl_limits.rs#L86.

2018-08-03 17:14 UTC, jdm commented on components/canvas_traits/webgl.rs
> +    pub max_combined_texture_image_units: u32,
This duplicates https://github.com/servo/rust-offscreen-rendering-context/blob/master/src/gl_limits.rs#L11.

2018-08-23 12:50 UTC, avadacatavra requested changes
lgtm

2018-08-23 12:50 UTC, avadacatavra commented on components/canvas/webgl_thread.rs
> +    #[allow(unsafe_code)]
I don't think this is needed

2018-08-23 13:15 UTC, nox commented on components/canvas/webgl_thread.rs
> +    #[allow(unsafe_code)]
Good catch. I removed it.

2018-08-23 13:16 UTC, avadacatavra commented
@bors-servo r+

2018-08-23 13:16 UTC, bors-servo commented
:pushpin: Commit 8b1c753 has been approved by `avadacatavra`

<!-- @bors-servo r=avadacatavra 8b1c753c6c7bb6359e9cfb27ada86185a966dce1 -->

2018-08-23 13:16 UTC, bors-servo commented
:hourglass: Testing commit 8b1c753c6c7bb6359e9cfb27ada86185a966dce1 with merge a1abdde8c62d01a144d12ae4b425d6b062bad41b...

2018-08-23 13:17 UTC, avadacatavra approved these changes

2018-08-23 13:40 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9536)

2018-08-23 14:16 UTC, jdm commented
@bors-servo retry
* #21492

2018-08-23 16:00 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/12312), [android-x86](http://build.servo.org/builders/android-x86/builds/424), [arm32](http://build.servo.org/builders/arm32/builds/12508), [arm64](http://build.servo.org/builders/arm64/builds/12551), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12610), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9538), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12638), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5081), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9348), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9391), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5153), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5097), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8014) are reusable. Rebuilding only [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9536), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5079)...

2018-08-23 16:53 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12312), [android-x86](http://build.servo.org/builders/android-x86/builds/424), [arm32](http://build.servo.org/builders/arm32/builds/12508), [arm64](http://build.servo.org/builders/arm64/builds/12551), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12610), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9538), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9537), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12638), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5081), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5081), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9348), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9391), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5153), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5097), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8014)
Approved by: avadacatavra
Pushing a1abdde8c62d01a144d12ae4b425d6b062bad41b to master...

2018-08-23 16:53 UTC, merged