Various webgl fixes for framebuffer attachment test
servo/servo pull request #21461
Opened 2018-08-20 12:44 UTC by jdm

These changes resolve all panics on macOS when running framebuffer-object-attachment.html in headless and headful testing.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes OR

2018-08-20 12:44 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webgltexture.rs, components/script/dom/webglrenderingcontext.rs, components/script/dom/webglframebuffer.rs
 * @kichjang: components/script/dom/webgltexture.rs, components/script/dom/webglrenderingcontext.rs, components/script/dom/webglframebuffer.rs

2018-08-20 12:45 UTC, jdm commented
r? @nox

2018-08-20 13:09 UTC, nox commented
@bors-servo r+

2018-08-20 13:09 UTC, bors-servo commented
:pushpin: Commit 226a60a has been approved by `nox`

<!-- @bors-servo r=nox 226a60a81e963c635ce44fba703659c594f049e4 -->

2018-08-20 13:09 UTC, bors-servo commented
:hourglass: Testing commit 226a60a81e963c635ce44fba703659c594f049e4 with merge 86dddb36a37d775f0f040722f4567ba7f6c2562f...

2018-08-20 13:44 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9518)

2018-08-24 21:43 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9567)

2018-08-24 22:01 UTC, jdm commented
Need to look at:
* /_mozilla/webgl/conformance-1.0.3/conformance/misc/object-deletion-behaviour.html
* /_mozilla/webgl/conformance-1.0.3/conformance/textures/texture-fakeblack.html

2018-08-29 09:52 UTC, nox commented on components/canvas/webgl_thread.rs
> +}
Why is this on the GL side when it could be on the DOM side?

2018-08-29 09:53 UTC, nox commented on components/canvas/webgl_thread.rs
> +}
I'm strongly against caching *some* stuff on the GL side and *some* stuff on the DOM side. All of the bookkeeping I've implemented this year has been put on the DOM side to be able, I see no reason to put those values on the GL side.

2018-08-29 09:55 UTC, nox commented on components/canvas/webgl_thread.rs
> +}
Never mind I see why now.

2018-08-29 09:56 UTC, nox commented on components/canvas/webgl_thread.rs
> +    #[allow(unsafe_code)]
This doesn't use any unsafe code.

2018-08-29 09:57 UTC, nox commented on components/script/dom/webglrenderingcontext.rs
> +    #[ignore_malloc_size_of = "Because it's small"]
Why is this suddenly needed?

2018-08-30 21:05 UTC, jdm commented
@bors-servo try=wpt

2018-08-30 21:05 UTC, bors-servo commented
:hourglass: Trying commit b6160c796461a435632302ec9933d05e203636ed with merge 3c9da249b8425e248f0776df68fa5ebbe551cd3d...

2018-08-31 15:34 UTC, jdm commented
Note to self - DeleteRenderbuffer already contains some code to deal with deleting a renderbuffer that is bound to the current framebuffer. Need to figure out how to merge that with my reimplementation in this PR.

2018-08-31 20:15 UTC, jdm commented
@bors-servo try=wpt

2018-08-31 20:15 UTC, bors-servo commented
:hourglass: Trying commit f84e66c80ced4af2828c3b8b4c414f048a65c5cd with merge 4a685fc8fd685b1752662839e7fc2d23e18eed25...

2018-08-31 20:49 UTC, jdm commented
This is ready for review.

2018-09-03 09:50 UTC, nox requested changes
An expectation nit, and a question about some binding tracking.

2018-09-03 09:50 UTC, nox commented on components/script/dom/webglrenderbuffer.rs
> +    attached_framebuffers: DomRefCell<Vec<Dom<WebGLFramebuffer>>>,
I don't understand why this is needed and why we can't just keep track of a refcount.

2018-09-03 09:50 UTC, nox commented on tests/wpt/webgl/meta/conformance2/rendering/framebuffer-texture-level1.html.ini
> +
The previous failures are now outdated and should be removed.

2018-09-07 11:26 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #21634) made this pull request unmergeable. Please resolve the merge conflicts.

2018-09-10 20:32 UTC, jdm commented
You were correct; it wasn't necessary to track the attached framebuffers. The resulting code is easier to follow, which is nice.

2018-09-10 20:32 UTC, jdm commented
4edb7b1 is the only commit that's new.

2018-09-10 21:38 UTC, nox commented
The following expectations reference #13710:

* `tests/wpt/webgl/meta/conformance/misc/uninitialized-test.html.ini`
* `tests/wpt/webgl/meta/conformance/renderbuffers/depth-renderbuffer-initialization.html.ini`
* `tests/wpt/webgl/meta/conformance/renderbuffers/renderbuffer-initialization.html.ini`
* `tests/wpt/webgl/meta/conformance/renderbuffers/stencil-renderbuffer-initialization.html.ini`

AFAICT they are not all changed in your PR. Could you reenable them? Looks good to me otherwise, r=me.

2018-09-10 23:27 UTC, jdm commented
@bors-servo r=nox

2018-09-10 23:27 UTC, bors-servo commented
:pushpin: Commit ba25d06 has been approved by `nox`

<!-- @bors-servo r=nox ba25d065d10f159cc2a4e54fb51aaf6f8251b924 -->

2018-09-11 01:55 UTC, bors-servo commented
:hourglass: Testing commit ba25d065d10f159cc2a4e54fb51aaf6f8251b924 with merge ffe256fc3e409f9e408dbb7116bb5bb459404bca...

2018-09-12 13:35 UTC, nox commented
@jdm Could you disable the tests about uninitialised buffers again and make this land?

2018-09-12 13:47 UTC, jdm commented
@bors-servo r=nox

2018-09-12 13:47 UTC, bors-servo commented
:pushpin: Commit 4edb7b1 has been approved by `nox`

<!-- @bors-servo r=nox 4edb7b194c99a1d394dddaeac2f5064ed8e93f62 -->

2018-09-12 18:38 UTC, bors-servo commented
:hourglass: Testing commit 4edb7b194c99a1d394dddaeac2f5064ed8e93f62 with merge a43837421aca0fff8c7bd50420a70d506c673b8e...

2018-09-12 19:33 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9611)

2018-09-12 19:41 UTC, jdm commented
@bors-servo retry
* #21493 21493

2018-09-12 20:36 UTC, bors-servo commented
:hourglass: Testing commit 4edb7b194c99a1d394dddaeac2f5064ed8e93f62 with merge 26745b27419f687dec1e23434a5be827d4342768...

2018-09-12 21:32 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12524), [android-x86](http://build.servo.org/builders/android-x86/builds/637), [arm32](http://build.servo.org/builders/arm32/builds/12715), [arm64](http://build.servo.org/builders/arm64/builds/12756), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12822), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9796), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9797), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12849), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5298), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5293), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9561), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9612), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5365), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5307), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8217)
Approved by: nox
Pushing 26745b27419f687dec1e23434a5be827d4342768 to master...

2018-09-12 21:32 UTC, merged