Some more drive-by WebGL fixes and cleanups
servo/servo pull request #21523
Opened 2018-08-25 17:52 UTC by nox

2018-08-25 17:52 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webglvertexarrayobjectoes.rs, components/script/dom/webglrenderingcontext.rs, components/script/dom/webidls/WebGLRenderingContext.webidl
 * @jgraham: tests/wpt/webgl/meta/conformance/rendering/preservedrawingbuffer-leak.html.ini, tests/wpt/webgl/meta/conformance/renderbuffers/framebuffer-state-restoration.html.ini, tests/wpt/webgl/meta/conformance/canvas/to-data-url-test.html.ini, tests/wpt/webgl/meta/conformance/attribs/gl-vertex-attrib.html.ini, tests/wpt/webgl/meta/conformance/more/conformance/methods.html.ini and 43 more
 * @kichjang: components/script/dom/webglvertexarrayobjectoes.rs, components/script/dom/webglrenderingcontext.rs, components/script/dom/webidls/WebGLRenderingContext.webidl

2018-08-25 17:53 UTC, nox commented
@bors-servo try

2018-08-25 17:53 UTC, bors-servo commented
:hourglass: Trying commit 26f90daabcff0ec213594b93920ba8cd60fd8f1d with merge 0d45913d584bc7302f858d2a8bb97b10db8caa79...

2018-08-25 18:32 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5115)

2018-08-25 19:04 UTC, nox commented
Disabled many more tests, notably everything related to texture sources that we don't support at all.

@bors-servo try

2018-08-25 19:04 UTC, bors-servo commented
:hourglass: Trying commit eb204573e0884d12fed76e4f6b6b6a8dd689217b with merge 59f9b1d5239f8e3ae841413fb7f5b5a637593134...

2018-08-25 19:41 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9427)

2018-08-25 20:46 UTC, nox commented
Only unrelated failures again.

2018-08-27 13:01 UTC, avadacatavra requested changes

2018-08-27 15:57 UTC, nox reviewed
I still need to add a few issue links but it's gym time.

2018-08-27 15:57 UTC, nox commented on tests/wpt/webgl/meta/conformance/textures/canvas/__dir__.ini
> +disabled: canvas textures are not implemented yet
I was actually completely wrong about this specific folder of tests.

2018-08-28 14:17 UTC, avadacatavra commented on tests/wpt/webgl/meta/conformance/textures/misc/tex-video-using-tex-unit-non-zero.html.ini
> +  disabled: video textures are not supported yet
file and link to issue

2018-08-28 14:17 UTC, avadacatavra commented on tests/wpt/webgl/meta/conformance/textures/misc/texture-corner-case-videos.html.ini
> +  disabled: video textures are not supported yet
link to issue

2018-08-28 14:17 UTC, avadacatavra commented on tests/wpt/webgl/meta/conformance/textures/misc/texture-npot-video.html.ini
> +  disabled: video textures are not supported yet
link to issue

2018-08-28 14:17 UTC, avadacatavra commented on tests/wpt/webgl/meta/conformance/textures/svg_image/__dir__.ini
> +disabled: SVG support is not implemented yet
iirc we don't have plans to implement this right now, so if that's the case I don't see the need to file an issue for it

2018-08-28 14:17 UTC, avadacatavra commented on tests/wpt/webgl/meta/conformance/textures/video/__dir__.ini
> +disabled: video textures are not implemented yet
link to issue

2018-08-28 14:17 UTC, avadacatavra commented on tests/wpt/webgl/meta/conformance/textures/webgl_canvas/__dir__.ini
> +disabled: canvas textures are not implemented yet
file/link to issue

2018-08-28 14:17 UTC, avadacatavra commented on tests/wpt/webgl/meta/conformance/canvas/draw-static-webgl-to-multiple-canvas-test.html.ini
> +  disabled: drawing webgl canvas in 2d canvas is not supported yet
link to issue

2018-08-28 14:17 UTC, avadacatavra commented on tests/wpt/webgl/meta/conformance/canvas/draw-webgl-to-canvas-test.html.ini
> +  disabled: drawing webgl canvas in 2d canvas is not supported yet
link to issue

2018-08-30 10:59 UTC, nox commented
@jdm You need to sign on two things: disabling the quickcheck test and deleting the Servo-specific WebGL tests. @avadacatavra reviewed everything else.

2018-08-30 11:45 UTC, bors-servo commented
:hourglass: Testing commit 63076413817055dd32a66939a9c533baaa4af9bb with merge 4fec3335b9604b135d2d0bcb008689f7182b273e...

2018-08-30 11:47 UTC, jdm requested changes

2018-08-30 11:47 UTC, jdm commented on tests/wpt/webgl/tests/js/js-test-pre.js
> +  window.onerror = t.step_func_done(oldNotify);
This doesn't use oldOnError.

2018-08-30 11:48 UTC, jdm commented
@bors-servo r-

2018-08-30 12:29 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5129)

2018-08-30 14:16 UTC, nox commented on tests/wpt/webgl/tests/js/js-test-pre.js
> +  window.onerror = t.step_func_done(oldNotify);
I used `addEventListener` instead.

2018-08-30 16:13 UTC, bors-servo commented
:hourglass: Testing commit 900a19058e5f282fdb914ac16801d11f4a2c0159 with merge 8af3bf28d32a4178ec1d0c6746d313fad5e6d46a...

2018-08-30 16:13 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9600)

2018-08-30 16:18 UTC, jdm commented
@bors-servo retry
* infra problems

2018-08-30 16:33 UTC, bors-servo commented
:broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/12665)

2018-08-30 16:52 UTC, jdm commented
@bors-servo retry
* busted build machine

2018-08-30 17:04 UTC, bors-servo commented
:zap: Previous build results for [android-x86](http://build.servo.org/builders/android-x86/builds/479), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5136), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9447), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5209) are reusable. Rebuilding only [android](http://build.servo.org/builders/android/builds/12368), [arm32](http://build.servo.org/builders/arm32/builds/12562), [arm64](http://build.servo.org/builders/arm64/builds/12604), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12665), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9602), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9605), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12693), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5138), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9405), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5150), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8068)...

2018-08-30 17:17 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5138)

2018-08-30 17:29 UTC, jdm commented
@bors-servo retry

2018-08-30 17:40 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/12368), [android-x86](http://build.servo.org/builders/android-x86/builds/479), [arm32](http://build.servo.org/builders/arm32/builds/12562), [arm64](http://build.servo.org/builders/arm64/builds/12604), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12666), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9602), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9605), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12693), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5136), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9447), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5209), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8068) are reusable. Rebuilding only [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5138), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9405), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5150)...

2018-08-30 18:27 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12368), [android-x86](http://build.servo.org/builders/android-x86/builds/479), [arm32](http://build.servo.org/builders/arm32/builds/12562), [arm64](http://build.servo.org/builders/arm64/builds/12604), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12666), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9602), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9605), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12693), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5140), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5136), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9405), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9447), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5209), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5150), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8068)
Approved by: avadacatavra,jdm
Pushing 6f81ed49f6a7281341d079766de0601286c4802c to master...

2018-08-30 18:27 UTC, merged