Make bootstrap handle linux setup, include gstreamer
servo/servo pull request #21586
Opened 2018-09-03 08:28 UTC by Manishearth

Previously `./mach bootstrap` wasn't very useful on Linux, it would just install salt. This PR moves that to `./mach bootstrap-salt`, and has `./mach bootstrap` perform the installation steps mentioned in the README.

With these changes `./mach bootstrap` is a valid way of setting up the servo build. Additionally, this adds gstreamer setup to this for cases where gstreamer is not up to date.

r? @jdm

2018-09-03 08:28 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/bootstrap.py, python/servo/command_base.py, python/servo/bootstrap_commands.py, python/servo/testing_commands.py

2018-09-03 08:29 UTC, Manishearth commented on support/linux/gstreamer/gstreamer.sh
> +wget https://github.com/ferjm/gstreamer-1.14.1-ubuntu-trusty/raw/master/gstreamer.tar.gz -O gstreamer.tar.gz
Should I just make this part of the python file?

Also, should we try to host these binaries on our s3 bucket? (I don't know how, but I can ask)

2018-09-03 08:31 UTC, Manishearth commented on python/servo/bootstrap.py
> +            raise Exception("mach bootstrap does not support %s, please file a bug" % distro)
I'll open an issue for filling this in for macs

2018-09-03 09:15 UTC, Manishearth commented
An annoying bit is that mach itself is pretty heavyweight and needs a bunch of deps like libffi to work. I can try and make mach bootstrap work independently of mach, if that is desired, that way folks just have to have rust installed and run `./mach bootstrap`.

(I'm currently testing this on a VM)

2018-09-03 11:45 UTC, Manishearth commented
I've got the independent bootstrap working in my [bootstrap-next](http://github.com/manishearth/servo/tree/bootstrap-next) branch but I'm still working out some small issues.

I wonder if the gstreamer setup should be in `./mach bootstrap` or `mach_bootstrap.py`. Stuff is kinda scattered between the two, currently. I feel like it belongs in `./mach bootstrap` because while the `support/linux/gstreamer` based setup doesn't require sudo, the `apt-get` one does, and `mach_bootstrap.py` is all about silent non-sudo installation.

2018-09-03 12:33 UTC, Manishearth commented
Merged in the branch. We can now recommend _just_ running `./mach bootstrap` for Ubuntu and Fedora.

We don't install rust, though (but mach bootstrap could if we wanted it to). 

Also found out a couple trusty-only dependency changes from the spidermonkey upgrade, which are also now installed via bootstrap.

2018-09-04 07:17 UTC, Manishearth commented
@bors-servo try=linux

2018-09-04 07:17 UTC, bors-servo commented
:hourglass: Trying commit c91594ca339730fa236ab7c5c3c672aa7fe47748 with merge 25f9fa8ffe600e6f4f3315978b8565b477900982...

2018-09-04 07:27 UTC, bors-servo commented
:sunny: Test successful - [linux-dev](http://build.servo.org/builders/linux-dev/builds/12709)
State: approved= try=True

2018-09-04 07:34 UTC, Manishearth commented
wow, try=linux is _fast_

2018-09-05 16:38 UTC, jdm requested changes
These changes look like a really nice improvement for common pain points. Thanks!

2018-09-05 16:38 UTC, jdm commented on python/servo/bootstrap.py
> +        run_as_root(["apt-add-repository" "deb http://apt.llvm.org/trusty/ llvm-toolchain-xenial-4.0 main"], force)
Missing comma(s?)

2018-09-05 16:41 UTC, Manishearth commented on servo-tidy.toml
> +  "./support/linux/gstreamer/gstreamer.sh",
It can't, it contains giant URLs that can't really be split up further. Most of its lines are too long anyway, the tidy script doesn't get us much

2018-09-06 07:31 UTC, Manishearth commented
Updated

2018-09-06 11:27 UTC, jdm commented
@bors-servo r+

2018-09-06 11:27 UTC, bors-servo commented
:pushpin: Commit 19f74d5 has been approved by `jdm`

<!-- @bors-servo r=jdm 19f74d5ec10a5665b211dc96191e73de1ec36d22 -->

2018-09-06 14:45 UTC, bors-servo commented
:hourglass: Testing commit 1b1be2f1d5627b9f1d1d44c1e44283449590adde with merge 0901489ef6d184e6f52941596fb435c17f8c9ab0...

2018-09-06 14:45 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9689)

2018-09-07 04:45 UTC, Manishearth commented
@bors-servo r=jdm

2018-09-07 04:45 UTC, bors-servo commented
:pushpin: Commit 1809985 has been approved by `jdm`

<!-- @bors-servo r=jdm 1809985f251e99778b292869d399df48cfd21699 -->

2018-09-07 04:45 UTC, bors-servo commented
:hourglass: Testing commit 1809985f251e99778b292869d399df48cfd21699 with merge 4c4f4f1e09dce83709d30a63c29634e9be662446...

2018-09-07 04:46 UTC, bors-servo commented
:broken_heart: Test failed - [arm32](http://build.servo.org/builders/arm32/builds/12640)

2018-09-07 09:12 UTC, Manishearth commented
@bors-servo r=jdm

2018-09-07 09:12 UTC, bors-servo commented
:pushpin: Commit 4d6a987 has been approved by `jdm`

<!-- @bors-servo r=jdm 4d6a987c9f4a65f05b771611ca5ed7068b2e9276 -->

2018-09-07 10:13 UTC, bors-servo commented
:hourglass: Testing commit 4d6a987c9f4a65f05b771611ca5ed7068b2e9276 with merge 2f8e03268bdb0efc2316fbce1ca334f2a5f518a7...

2018-09-07 10:30 UTC, Manishearth commented
@bors-servo r=jdm

2018-09-07 10:30 UTC, bors-servo commented
:pushpin: Commit 5c297fa has been approved by `jdm`

<!-- @bors-servo r=jdm 5c297fa61b34080bdaf658db936ce59062777bf3 -->

2018-09-07 11:27 UTC, bors-servo commented
:broken_heart: Test failed - [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8148)

2018-09-07 11:40 UTC, Manishearth commented
I'm bypassing the checks on Windows, AIUI we can't do the same pkg-config thing there.

@bors-servo r=jdm

2018-09-07 11:40 UTC, bors-servo commented
:pushpin: Commit 49e7aa9 has been approved by `jdm`

<!-- @bors-servo r=jdm 49e7aa9a6f7d6a4b397e500fa6ea0e83d7dd42c8 -->

2018-09-07 11:40 UTC, bors-servo commented
:hourglass: Testing commit 49e7aa9a6f7d6a4b397e500fa6ea0e83d7dd42c8 with merge 0d9283fd8e75bc47b13d5390d95f369464f4050a...

2018-09-07 11:47 UTC, Manishearth commented
A better solution is to just silently ignore it when there's no pkg-config. The GStreamer build script does the same (it just hopes for the best and asks cargo to link to whatever it finds)

@bors-servo r=jdm

2018-09-07 11:47 UTC, bors-servo commented
:pushpin: Commit 86dd518 has been approved by `jdm`

<!-- @bors-servo r=jdm 86dd51850e1789e646620c8ca5fa343ca324fe5a -->

2018-09-07 11:48 UTC, bors-servo commented
:hourglass: Testing commit 86dd51850e1789e646620c8ca5fa343ca324fe5a with merge d326aed30717950ca776c39932b741fcd389e160...

2018-09-07 12:13 UTC, bors-servo commented
:broken_heart: Test failed - [android](http://build.servo.org/builders/android/builds/12450)

2018-09-07 12:15 UTC, Manishearth commented
Hmmm... we bail out early for non-x86 systems, what gives?

2018-09-07 12:19 UTC, Manishearth commented
Just sshd to the server to try this, it works fine if I run it directly. Hm.

2018-09-11 14:12 UTC, Manishearth commented
@bors-servo try=android

mach build calls mach package, which doesn't pass down the target.

2018-09-11 14:12 UTC, bors-servo commented
:hourglass: Trying commit 0e252a179f105eb10b4235a50aee693648f48188 with merge de4f008f3ad5ac78864152edd56e507f8a6f3111...

2018-09-11 15:30 UTC, bors-servo commented
:broken_heart: Test failed - [android-x86](http://build.servo.org/builders/android-x86/builds/604)

2018-09-11 15:58 UTC, Manishearth commented
@bors-servo try=android

also test-wpt-android has similar issues

2018-09-11 15:58 UTC, bors-servo commented
:hourglass: Trying commit 5d6701179c71abcd6a020091ec7d2cb6d47351ed with merge 508653ba81f29127719070e3cb6fa117b1995d0f...

2018-09-11 16:44 UTC, Manishearth commented
@bors-servo try=android

2018-09-11 16:44 UTC, bors-servo commented
:hourglass: Trying commit 2cc4e1dcdcdee9505d4d790386b1df0a680549d5 with merge 8a4eda56492f3945e4f0ac097894d952a70bdc7b...

2018-09-11 17:11 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12493), [android-x86](http://build.servo.org/builders/android-x86/builds/606)
State: approved= try=True

2018-09-11 17:21 UTC, Manishearth commented
@bors-servo r=jdm

2018-09-11 17:21 UTC, bors-servo commented
:pushpin: Commit 2cc4e1d has been approved by `jdm`

<!-- @bors-servo r=jdm 2cc4e1dcdcdee9505d4d790386b1df0a680549d5 -->

2018-09-11 20:07 UTC, bors-servo commented
:hourglass: Testing commit 2cc4e1dcdcdee9505d4d790386b1df0a680549d5 with merge 9dd85e3a515843fc210fbd44fea4ea884c3f6a48...

2018-09-11 20:48 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5268)

2018-09-11 21:34 UTC, jdm commented
@bors-servo retry
* #20734

2018-09-11 22:36 UTC, bors-servo commented
:hourglass: Testing commit 2cc4e1dcdcdee9505d4d790386b1df0a680549d5 with merge 02dc71ec1e89ff31cb2b31ba71917ae0fbd206bc...

2018-09-11 23:39 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5285)

2018-09-12 03:27 UTC, jdm commented
@bors-servo retry

2018-09-12 04:56 UTC, bors-servo commented
:hourglass: Testing commit 2cc4e1dcdcdee9505d4d790386b1df0a680549d5 with merge babed6c3c16ecf0442e2e0abb870b97a710ea958...

2018-09-12 05:52 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12509), [android-x86](http://build.servo.org/builders/android-x86/builds/622), [arm32](http://build.servo.org/builders/arm32/builds/12700), [arm64](http://build.servo.org/builders/arm64/builds/12741), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12807), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9770), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9770), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12834), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5280), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5278), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9546), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9597), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5350), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5292), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8202)
Approved by: jdm
Pushing babed6c3c16ecf0442e2e0abb870b97a710ea958 to master...

2018-09-12 05:52 UTC, merged