Current pixel density
servo/servo pull request #21628
Opened 2018-09-06 16:43 UTC by paavininanda

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix a subset of #11416.

- [x] There are tests for these changes OR

2018-09-06 16:43 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/document.rs, components/script/dom/node.rs, components/script/dom/htmlimageelement.rs, components/script/dom/window.rs
 * @kichjang: components/script/dom/document.rs, components/script/dom/node.rs, components/script/dom/htmlimageelement.rs, components/script/dom/window.rs
 * @emilio: components/layout/fragment.rs, components/layout/construct.rs

2018-09-06 16:43 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2018-09-06 16:44 UTC, paavininanda commented
r? @jdm

2018-09-06 19:04 UTC, jdm requested changes
Looking good!

2018-09-06 19:04 UTC, jdm commented on components/script/dom/htmlimageelement.rs
> +            }
nit: `Some(data) => data`,

2018-09-06 19:04 UTC, jdm commented on components/script/dom/htmlimageelement.rs
> +        let pixel_density = (*self).current_request.borrow().current_pixel_density.clone().unwrap_or(1f64);
Let's do:
```rust
let request = self.current_request.borrow();
let pixel_density = request.current_pixel_density.unwrap_or(1f64);
match request.metadata {
    Some(ref metadata) => (metadata.width as f64 / pixel_density) as u32,
    None => 0,
}
```

2018-09-06 19:04 UTC, jdm commented on components/script/dom/htmlimageelement.rs
> +        let pixel_density = (*self).current_request.borrow().current_pixel_density.clone().unwrap_or(1f64);
Same as previous comment.

2018-09-06 19:04 UTC, jdm commented on components/layout/construct.rs
> +                    node.image_density(),
I expect this to break because the node won't be an image element. We should just pass None here.

2018-09-06 19:04 UTC, jdm commented on components/layout/construct.rs
> +                    node.image_density(),
This will break because the node is not an image element. We should pass None here.

2018-09-06 20:34 UTC, paavininanda commented on components/layout/fragment.rs
> +                        ..(*i).clone()
@jdm Due to the Arc wrapper, without dereferencing, it shows an error.

2018-09-06 21:12 UTC, jdm approved these changes

2018-09-06 21:13 UTC, jdm commented
This can merge after #21280 merges.

2018-09-12 17:35 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #21280) made this pull request unmergeable. Please resolve the merge conflicts.

2018-09-12 18:56 UTC, jdm commented
@bors-servo r+

2018-09-12 18:56 UTC, bors-servo commented
:pushpin: Commit 25027e4 has been approved by `jdm`

<!-- @bors-servo r=jdm 25027e476c89ce438a85a631d66f5f4c261be895 -->

2018-09-12 22:16 UTC, bors-servo commented
:hourglass: Testing commit 25027e476c89ce438a85a631d66f5f4c261be895 with merge 44394a56e58e521af3067f4798fe85e49e8fe5eb...

2018-09-12 22:36 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9799)

2018-09-12 22:46 UTC, jdm commented
@bors-servo retry
* #21698

2018-09-12 22:57 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/12525), [android-x86](http://build.servo.org/builders/android-x86/builds/638), [arm32](http://build.servo.org/builders/arm32/builds/12716), [arm64](http://build.servo.org/builders/arm64/builds/12757), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12823), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9800), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12850), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9613), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5366), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5308) are reusable. Rebuilding only [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9799), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5299), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5294), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9562), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8218)...

2018-09-12 23:11 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9801)

2018-09-13 02:56 UTC, jdm commented
@bors-servo retry
* #13480

2018-09-13 04:16 UTC, bors-servo commented
:hourglass: Testing commit 25027e476c89ce438a85a631d66f5f4c261be895 with merge b0de9c53153ce7f08d0e5f221ab58fa8a8c490d9...

2018-09-13 05:13 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12534), [android-x86](http://build.servo.org/builders/android-x86/builds/648), [arm32](http://build.servo.org/builders/arm32/builds/12724), [arm64](http://build.servo.org/builders/arm64/builds/12766), [linux-dev](http://build.servo.org/builders/linux-dev/builds/12833), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/9810), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/9810), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/12859), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5309), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5304), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9571), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9621), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5375), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5316), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8225)
Approved by: jdm
Pushing b0de9c53153ce7f08d0e5f221ab58fa8a8c490d9 to master...

2018-09-13 05:13 UTC, merged