Add task source for media element
servo/servo pull request #21879
Opened 2018-10-06 05:39 UTC by chansuke

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #21612 .
- [x] These changes do not require tests because the existing test should cover this code.

2018-10-06 05:39 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/script_thread.rs, components/script/dom/window.rs, components/script/dom/htmlmediaelement.rs, components/script/task_source/mod.rs, components/script/task_source/media_element.rs
 * @kichjang: components/script/script_thread.rs, components/script/dom/window.rs, components/script/dom/htmlmediaelement.rs, components/script/task_source/mod.rs, components/script/task_source/media_element.rs

2018-10-06 05:39 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-10-09 13:46 UTC, ferjm commented on components/script/dom/htmlmediaelement.rs
> -        // FIXME(nox): Why are errors silenced here?
This FIXME is still valid :) Do not remove it, please.

2018-10-09 13:51 UTC, ferjm requested changes
Thanks for working on this @chansuke :)

The task source related changes looks good to me. However, it would be great if you could remove the second commit and rebase on top of master instead of creating a merge commit.

Thanks!

2018-10-09 13:55 UTC, chansuke commented
@ferjm Ok.Thanks for your review.

2018-10-10 09:37 UTC, ferjm requested changes
Looks better now :) Thanks for the rebase.

I think there are only two things left to fix here:

- The `servo_channel::Sender` related build error.
- These tidy issues https://travis-ci.org/servo/servo/jobs/439453305#L447

2018-10-10 09:37 UTC, ferjm commented on components/script/task_source/media_element.rs
> +pub struct MediaElementTaskSource(pub Sender<MainThreadScriptMsg>, pub PipelineId);
This `Sender` needs to be a `servo_channel::Sender` instead of a `std::sync::mpsc::Sender`

2018-10-10 12:53 UTC, ferjm commented
One last change ;)

https://travis-ci.org/servo/servo/jobs/439558351#L447

Tip: you can check that tidy is happy with the patch by running `./mach test-tidy` locally.

2018-10-10 13:31 UTC, ferjm commented
@bors-servo try

2018-10-10 13:31 UTC, bors-servo commented
:hourglass: Trying commit 7b3cf27c69f1ed2d5372e2f1e50ce2aab84e05a7 with merge 7c41e75cf2c1b154ca97336b787200a5e2a54aa7...

2018-10-10 13:34 UTC, bors-servo commented
:broken_heart: Test failed - [android-x86](http://build.servo.org/builders/android-x86/builds/888)

2018-10-10 16:06 UTC, CYBAI commented
@bors-servo retry

-  #21205

2018-10-10 16:06 UTC, bors-servo commented
:hourglass: Trying commit 7b3cf27c69f1ed2d5372e2f1e50ce2aab84e05a7 with merge 1523000f50d0407085e996f7107c21f4e2f2c9cf...

2018-10-10 16:32 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10125)

2018-10-10 17:53 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/VJugwgODQI6PARQc1r242g)

2018-10-11 07:36 UTC, ferjm commented
@bors-servo r+

2018-10-11 07:36 UTC, bors-servo commented
:pushpin: Commit 7b3cf27 has been approved by `ferjm`

<!-- @bors-servo r=ferjm 7b3cf27c69f1ed2d5372e2f1e50ce2aab84e05a7 -->

2018-10-11 07:36 UTC, bors-servo commented
:hourglass: Testing commit 7b3cf27c69f1ed2d5372e2f1e50ce2aab84e05a7 with merge ae0a5a8eada818652be8b65d1d1220a434981e65...

2018-10-11 08:00 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10140)

2018-10-11 09:50 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/12788), [android-x86](http://build.servo.org/builders/android-x86/builds/904), [arm32](http://build.servo.org/builders/arm32/builds/12969), [arm64](http://build.servo.org/builders/arm64/builds/13005), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13083), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10116), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13099), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5560), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5566), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9825), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9875), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5633), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5569), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/SGCecW5URnGjP_rsE1-vgQ), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8462) are reusable. Rebuilding only [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10140)...

2018-10-11 10:15 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12788), [android-x86](http://build.servo.org/builders/android-x86/builds/904), [arm32](http://build.servo.org/builders/arm32/builds/12969), [arm64](http://build.servo.org/builders/arm64/builds/13005), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13083), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10116), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10145), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13099), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5560), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5566), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9825), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/9875), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5633), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5569), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/SGCecW5URnGjP_rsE1-vgQ), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8462)
Approved by: ferjm
Pushing ae0a5a8eada818652be8b65d1d1220a434981e65 to master...

2018-10-11 10:15 UTC, merged