Assign a name to iframes when loading the initial about:blank
servo/servo pull request #21976
Opened 2018-10-17 20:55 UTC by notriddle

Before, it would assign the name too late, causing scripts (which will not wait for another tick) to accidentally spawn pop-up windows instead of loading into the iframe.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #21886
- [x] There are tests for these changes

2018-10-17 20:55 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/htmliframeelement.rs
 * @kichjang: components/script/dom/htmliframeelement.rs

2018-10-17 20:56 UTC, servo-wpt-sync commented
Opened new PR for upstreamable changes.

Completed upstream sync of web-platform-test changes at https://github.com/web-platform-tests/wpt/pull/13585.

2018-10-17 21:01 UTC, notriddle commented
# Warning: the test case in this PR doesn't pass yet

This PR allows slither.io to be opened and played.

However, due to a second bug in the iframe implementation, the `load` event handler which performs the assertion is being called too early. It should be called only when the form is finished, but is instead being called by the initial `about:blank` document.

2018-10-17 21:04 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#13585.

2018-10-17 21:07 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#13585.

2018-10-19 00:29 UTC, notriddle commented
@bors-servo try=wpt

2018-10-19 00:29 UTC, bors-servo commented
:hourglass: Trying commit eafcd91760afbd0287b31aa6215c9528f6275b0d with merge 5dbf83a035dcd2d83b451b635e39be86fcb79c40...

2018-10-19 00:53 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10283)

2018-10-19 01:35 UTC, notriddle commented
```
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "Targeting nested browsing contexts", "test": "/html/browsers/windows/targeting-cross-origin-nested-browsing-contexts.html", "line": 170625, "action": "test_result", "expected": "FAIL"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/html/browsers/windows/targeting-cross-origin-nested-browsing-contexts.html", "line": 170626, "action": "test_result", "expected": "OK"}
```

2018-10-23 00:56 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#13585.

2018-10-23 17:37 UTC, notriddle commented
@bors-servo try=wpt

2018-10-23 17:37 UTC, bors-servo commented
:hourglass: Trying commit 7270333487ace93b260205e0fddc252299ee4718 with merge ff8cadf906b4102be2055bdb6b6d6afe26503bf5...

2018-10-23 18:03 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10277), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10303)
State: approved= try=True

2018-10-29 12:20 UTC, jdm requested changes
Thanks for looking into this so carefully!

2018-10-29 12:20 UTC, jdm commented on tests/wpt/web-platform-tests/html/semantics/forms/form-submission-target/form-target-iframe.html
> +  window.addEventListener("load", function() {
This should pass `t.step_func(function() {` instead.

2018-10-29 12:20 UTC, jdm commented on tests/wpt/web-platform-tests/html/semantics/forms/form-submission-target/form-target-iframe.html
> +    frame.addEventListener("load", function() {
This should also pass `t.step_func(function() {`

2018-10-29 12:20 UTC, jdm commented on tests/wpt/web-platform-tests/html/semantics/forms/form-submission-target/form-target-iframe.html
> +      if (frame.contentWindow.location.href != "about:blank") {
Could we make this check for the actual expected value instead? Maybe using `new URL("form-target-iframe-helper.py", window.location)`?

2018-10-29 18:55 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#13585.

2018-10-29 19:17 UTC, jdm commented
@bors-servo r+

2018-10-29 19:17 UTC, bors-servo commented
:pushpin: Commit 10442ae has been approved by `jdm`

<!-- @bors-servo r=jdm 10442ae894004ac18847793bc11bfa1c4653cb79 -->

2018-10-29 19:29 UTC, bors-servo commented
:hourglass: Testing commit 10442ae894004ac18847793bc11bfa1c4653cb79 with merge 2f8dc655191455c285d4b4b5952d493fd4dc0782...

2018-10-29 19:57 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10348)

2018-10-29 20:12 UTC, notriddle commented
@bors-servo retry

Out-of-memory

2018-10-29 20:12 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/12948), [android-mac](http://build.servo.org/builders/android-mac/builds/278), [android-x86](http://build.servo.org/builders/android-x86/builds/1065), [arm32](http://build.servo.org/builders/arm32/builds/13124), [arm64](http://build.servo.org/builders/arm64/builds/13161), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13245), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10317), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13238), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5716), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5795), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/PVHXRSSARRWL8c3FxfdO8A), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8617) are reusable. Rebuilding only [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10348), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5711), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9982), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10028), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5722)...

2018-10-29 20:45 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12948), [android-mac](http://build.servo.org/builders/android-mac/builds/278), [android-x86](http://build.servo.org/builders/android-x86/builds/1065), [arm32](http://build.servo.org/builders/arm32/builds/13124), [arm64](http://build.servo.org/builders/arm64/builds/13161), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13245), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10317), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10349), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13238), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5711), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5716), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9982), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10028), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5795), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5722), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/PVHXRSSARRWL8c3FxfdO8A), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8617)
Approved by: jdm
Pushing 2f8dc655191455c285d4b4b5952d493fd4dc0782 to master...

2018-10-29 20:45 UTC, merged