[WIP] Support building for Magic Leap.
servo/servo pull request #21985
Opened 2018-10-19 23:43 UTC by asajeffrey

This PR gets Servo to build for Magic Leap, and provides a dummy Servo2D app.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because it's a port to a new architecture

2018-10-19 23:43 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/build_commands.py
 * @edunham: servo-tidy.toml
 * @kichjang: components/script/Cargo.toml

2018-10-19 23:43 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify gfx and script code, but no tests are modified. Please consider adding a test!

2018-10-19 23:44 UTC, asajeffrey commented
It depends on https://github.com/servo/mozjs/pull/158 and https://github.com/servo/media/pull/158.

2018-10-22 15:09 UTC, asajeffrey commented
Filed #21999 to get servo-media updated.

2018-10-22 20:18 UTC, jdm requested changes

2018-10-22 20:18 UTC, jdm commented on support/magicleap/Servo2D/code/src/Servo2D.cpp
> +  return glm::vec3(0.5f, 0.5f, 0.5f);
Do these relate to the 500s in libmlservo, or is that just coincidence?

2018-10-22 20:18 UTC, jdm commented on support/magicleap/Servo2D/code/src/Servo2D.cpp
> +  // Get the panar resource that holds the EGL context
panar?

2018-10-22 20:18 UTC, jdm commented on support/magicleap/Servo2D/code/src/Servo2D.cpp
> +  glViewport(0, 0, 500, 500);
Does this need to match the 500s in libmlservo? Can we pass this value in to Rust?

2018-10-22 20:18 UTC, jdm commented on support/magicleap/Servo2D/code/src/main.cpp
> +  Servo2D myApp;
Does argv contain meaningful values for us? Can we accept a URL on the command line?

2018-10-22 20:18 UTC, jdm commented on support/magicleap/Servo2D/code/src/Servo2D.cpp
> +  glViewport(0, 0, 500, 500);
Let's make this a named constant somewhere.

2018-10-23 16:10 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #20755) made this pull request unmergeable. Please resolve the merge conflicts.

2018-10-23 21:15 UTC, asajeffrey commented
I did some fixes, but can't test the C++ code because I'm at home rather than in the office.

2018-10-23 21:50 UTC, asajeffrey commented
Rebased.

2018-10-23 22:55 UTC, asajeffrey commented
Updated `mozjs_sys` which was the last external blocker.

2018-10-24 04:58 UTC, paulrouget commented
I see that you introduced a new port. Did you consider using the c api of libsimpleservo instead of libmlservo?

2018-10-24 13:44 UTC, asajeffrey commented
@paulrouget yes, originally I was using libsimpleservo but ran into horrible linking problems which went away if I used libservo directly. My suspicion is that the ML is going to be a different enough target from Android that we're going to need a different port at some point anyway.

2018-10-24 15:31 UTC, paulrouget commented
libsimpleservo can be compiled without any android stuff (it compiles on Desktop for example). It's supposed to be capable of being dynamically loaded like libservo. I'd be interested to know what kind of issues you ran into.

I don't want to block this, but maybe later we could look at how to re-use libsimpleservo for ML.

2018-10-24 16:23 UTC, asajeffrey commented
It's been a while, but there was some issue about `libsimpleservo` being dynamically loaded causing symbols not to be found. I may have fixed that in the mean time, e.g. by statically loading openssl.

2018-10-29 10:06 UTC, ferjm commented on support/magicleap/README.md
> +From inside the `ports/magicleap/Servo2D` directory:
s/ports/support

2018-10-29 10:10 UTC, ferjm commented on support/magicleap/README.md
> +From inside the `ports/magicleap/Servo2D` directory:
s/ports/support

2018-10-29 11:19 UTC, jdm commented
@bors-servo delegate+
I'm fine with keeping the question about the URL as a followup.

2018-10-29 11:19 UTC, bors-servo commented
:v: @asajeffrey can now approve this pull request

2018-10-29 13:50 UTC, asajeffrey commented
@bors-servo r=jdm

2018-10-29 13:50 UTC, bors-servo commented
:pushpin: Commit dab8f4a has been approved by `jdm`

<!-- @bors-servo r=jdm dab8f4a97fe8c122d24281ea7c62ccb3c7bba621 -->

2018-10-29 14:00 UTC, bors-servo commented
:hourglass: Testing commit dab8f4a97fe8c122d24281ea7c62ccb3c7bba621 with merge 0ec0f705b66f1d527e24ddd5f99bd29e402a6bb0...

2018-10-29 15:12 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/12945), [android-mac](http://build.servo.org/builders/android-mac/builds/275), [android-x86](http://build.servo.org/builders/android-x86/builds/1062), [arm32](http://build.servo.org/builders/arm32/builds/13121), [arm64](http://build.servo.org/builders/arm64/builds/13158), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13242), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10314), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10345), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13235), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5708), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5713), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/9979), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10025), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5792), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5719), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/LddzpVUzQNa8oE9BhHHSuQ), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8614)
Approved by: jdm
Pushing 0ec0f705b66f1d527e24ddd5f99bd29e402a6bb0 to master...

2018-10-29 15:13 UTC, merged