Added .webidl files.
servo/servo pull request #22070
Opened 2018-11-01 00:34 UTC by PrayaniSingh0106

@maharsh312 @chiaggs
Added 3 file as following:
1. OffscreenCanvasRenderingContext2d.webidl
2. OffscreenCanvas.webidl
3. resources/prefs.json

r? @jdm 
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2018-11-01 00:34 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @jdm (or someone else) soon.

2018-11-01 00:34 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webidls/OffscreenCanvas.webidl, components/script/dom/webidls/OffscreenCanvasRenderingContext2d.webidl
 * @kichjang: components/script/dom/webidls/OffscreenCanvas.webidl, components/script/dom/webidls/OffscreenCanvasRenderingContext2d.webidl

2018-11-01 00:34 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-11-01 00:38 UTC, jdm requested changes
This won't be able to merge until there's a corresponding Rust implementation. The bindings that are generated from the WebIDL file will complain, otherwise.

2018-11-01 00:38 UTC, jdm commented on components/script/dom/webidls/OffscreenCanvas.webidl
> +  ImageBitmap transferToImageBitmap();
This will need to be commented out until we also add the ImageBitmap interface. Servo currently does not implement it.

2018-11-01 00:38 UTC, jdm commented on resources/prefs.json
> +  "dom.offscreen_canvas.enabled": true,
We don't actually want to enable this preference by default until the implementation is ready.

2018-11-02 02:40 UTC, maharsh312 commented
@jdm Can you tell us which variables would be part of structure of OffscreenCanvas apart from height and width?

2018-11-02 02:56 UTC, jdm commented
You will also need to store a context member similar to https://github.com/servo/servo/blob/master/components/script/dom/htmlcanvaselement.rs#L58 . Apart from that, I don't know that there will need to be any other members for OffscreenCanvas.

2018-11-05 13:53 UTC, jdm commented
You are missing a reflector field in OffscreenCanvas. That stores the pointer to the JS object that represents this Rust object.

2018-11-09 01:50 UTC, maharsh312 commented
@jdm For initial step, which functionality should we implement for "offscreencanvasrenderingcontext2d.rs" ?

2018-11-09 06:32 UTC, maharsh312 commented
> The initial step only requires an implementation for OffscreenCanvas.getContext and the OffscreenCanvas constructor. transferToImageBitmap and convertToBlob can remain commented out. The OffscreenCanvasRenderingContext2D interface should have the `canvas` attribute implemented, but the various `includes` lines that add 2d drawing APIs can remain commented out. The work to share that code with CanvasRenderingContext2D is part of the next steps in the project. Does that make sense?

Yes it makes sense. What about "commit()" in OffscreenCanvasRenderingContext2D? Should it be implemented?

2018-11-09 13:36 UTC, jdm commented
I don't think it makes sense to implement it separately from the actual rendering.

2018-11-10 17:56 UTC, maharsh312 commented
@jdm Can you review this code. We are getting lots of error and are stuck. It would be great if you can suggest changes.

```rust
use dom::bindings::codegen::Bindings::OffscreenCanvasBinding::{OffscreenCanvasMethods, Wrap as OffscreenCanvasWrap};
use dom::bindings::codegen::Bindings::OffscreenCanvasBinding;
use dom::bindings::codegen::UnionTypes;
use dom::bindings::error::{Error, Fallible};
use dom::bindings::reflector::{DomObject, Reflector, reflect_dom_object};
use std::ptr;
use dom::bindings::root::{DomRoot, Dom};
use std::cell::Ref;
use dom::bindings::str::DOMString;
use dom::globalscope::GlobalScope;
use dom::htmlcanvaselement::{CanvasContext, HTMLCanvasElement};
use dom_struct::dom_struct;
use dom::bindings::cell::DomRefCell;
use ref_filter_map;
use dom::offscreencanvasrenderingcontext2d::OffscreenCanvasRenderingContext2D;
use js::rust::HandleValue;
use js::jsapi::JSContext;
use dom::node::{Node, window_from_node};


pub enum OffscreenCanvasContext {
    Context2D(Dom<OffscreenCanvasRenderingContext2D>),
    //WebGL(Dom<WebGLRenderingContext>),
    //WebGL2(Dom<WebGL2RenderingContext>),
}

#[dom_struct]
pub struct OffscreenCanvas{
    reflector_: Reflector,
    height: u64,
    width: u64,
    context: DomRefCell<Option<OffscreenCanvasContext>>,
    placeholder: Option<Dom<HTMLCanvasElement>>,
}

impl OffscreenCanvas{
    pub fn new_inherited(height: u64, width: u64, placeholder: Option<&HTMLCanvasElement>) -> OffscreenCanvas {
        OffscreenCanvas {
            reflector_: Reflector::new(),
            height: height,
            width: width,
            context: DomRefCell::new(None),
            placeholder: placeholder.map(|canvas| Dom::from_rooted(canvas)),
        }
    }

    pub fn new(global: &GlobalScope, height: u64, width: u64, placeholder: Option<&HTMLCanvasElement>) -> DomRoot<OffscreenCanvas> {
        reflect_dom_object(Box::new(OffscreenCanvas::new_inherited(height,width,placeholder)), global, OffscreenCanvasWrap)
    }

    pub fn Constructor (global: &GlobalScope, height: u64, width: u64) -> Fallible<DomRoot<OffscreenCanvas>> {
        //step 1
        let offscreencanvas = OffscreenCanvas::new(global,height,width,None);
        //step 2

        if offscreencanvas.context.borrow().is_some() {
            return Err(Error::InvalidState);
        }

        offscreencanvas.height = height;
        offscreencanvas.width = width;

        offscreencanvas.placeholder = None;

        //step 3
        Ok(offscreencanvas)
    }

    /*pub fn context(&self) -> Option<Ref<OffscreenCanvasContext>> {
        ref_filter_map::ref_filter_map(self.context.borrow(), |ctx| ctx.as_ref())
    }*/

    fn get_or_init_2d_context(&self) -> Option<DomRoot<OffscreenCanvasRenderingContext2D>> {
        if let Some(ctx) = self.context() {
            return match *ctx {
                OffscreenCanvasContext::Context2d(ref ctx) => Some(DomRoot::from_ref(ctx)),
                _ => None,
            };
        }
        let window = window_from_node(self);
        let size = self.get_size();
        let context = OffscreenCanvasRenderingContext2D::new(window.upcast::<GlobalScope>(), self, size);
        *self.context.borrow_mut() = Some(OffscreenCanvasContext::Context2d(Dom::from_ref(&*context)));
        Some(context)
    }

}


impl OffscreenCanvasMethods for OffscreenCanvas{
    #[allow(unsafe_code)]
    unsafe fn GetContext(&self,cx: *mut JSContext, contextID: DOMString, options: HandleValue) -> Option<UnionTypes::OffscreenCanvasRenderingContext2DOrWebGLRenderingContextOrWebGL2RenderingContext> {

        //let options =
        if !options.is_object() {
            options = HandleValue::null();
        }



        if(self.context.is_none())
        {
            if(contextID == "2d")
            {
                //self.get_or_init_2d_context();
            }
        }

    }



    fn Width(&self) -> u64 {
        return self.width;
    }
    fn SetWidth(&self, value: u64) -> () {
        self.width = value;
    }
    fn Height(&self) -> u64 {
        return self.height;
    }
    fn SetHeight(&self, value: u64) -> () {
        self.height = value;
    }
}
```
Errors: https://pastebin.com/jvN1u4NP

2018-11-11 22:12 UTC, jdm commented
@maharsh312 It would be useful if you specified the errors you are observing.

2018-11-11 22:14 UTC, jdm commented
Sorry, I missed the link to the errors.

2018-11-16 13:30 UTC, jdm commented
I'm closing this PR under the assumption that it's a duplicate of #22168.

2018-11-16 13:30 UTC, closed without merging