Unused scroll
servo/servo pull request #22097
Opened 2018-11-03 04:12 UTC by fabrizio8

Combined on_scroll_window_event with on_scroll_start_window_event and on_scroll_end_window_event

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22075  (github issue number if applicable).

- [X] There are tests for these changes:
- Ran unit-test, test-tidy with no errors,  and tested scrolling on webpages
- [ ] These changes do not require tests

2018-11-03 04:12 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2018-11-03 04:12 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @paulrouget: components/compositing/compositor.rs

2018-11-03 19:31 UTC, emilio requested changes
I don't think it's fine to use `on_scroll_window_event`, that also resets `in_scroll_transaction`. That being said, those are also unused, we just need to remove that too.

2018-11-03 20:36 UTC, fabrizio8 commented
@emilio,
Do you mean `on_scroll_window_event` should be removed as well as `in_scroll_transaction` or just `in_scroll_transaction`?

2018-11-04 13:58 UTC, emilio commented
Just `in_scroll_transaction` (and its usage on `on_scroll_window_event` of course).

2018-11-05 10:11 UTC, emilio approved these changes
Thanks!

2018-11-05 10:11 UTC, emilio commented
@bors-servo r+

2018-11-05 10:11 UTC, bors-servo commented
:pushpin: Commit b331936 has been approved by `emilio`

<!-- @bors-servo r=emilio b3319360b5d155abbfe658ec1e347e328f5ebe7b -->

2018-11-05 10:11 UTC, bors-servo commented
:hourglass: Testing commit b3319360b5d155abbfe658ec1e347e328f5ebe7b with merge 420b54197b63434d54a5b2a62f5e0f2078833cec...

2018-11-05 10:39 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10422)

2018-11-05 15:47 UTC, bors-servo commented
:hourglass: Testing commit b3319360b5d155abbfe658ec1e347e328f5ebe7b with merge 5e52992c6bd6400736f32399cb16bfb52a1b4e8b...

2018-11-05 17:51 UTC, jdm commented
@bors-servo retry

2018-11-05 17:51 UTC, bors-servo commented
:zap: Previous build results for [android](http://build.servo.org/builders/android/builds/13013), [android-mac](http://build.servo.org/builders/android-mac/builds/336), [android-x86](http://build.servo.org/builders/android-x86/builds/1135), [arm32](http://build.servo.org/builders/arm32/builds/13182), [arm64](http://build.servo.org/builders/arm64/builds/13218), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13309), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10391), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10428), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13289), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5770), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10039), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10083), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5850), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5777), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/NcIP7xI-T4-bBsxiWXGZbA), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8673) are reusable. Rebuilding only [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5765)...

2018-11-05 17:55 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/13013), [android-mac](http://build.servo.org/builders/android-mac/builds/336), [android-x86](http://build.servo.org/builders/android-x86/builds/1135), [arm32](http://build.servo.org/builders/arm32/builds/13182), [arm64](http://build.servo.org/builders/arm64/builds/13218), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13309), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10391), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10428), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13289), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5765), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5770), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10039), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10083), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5850), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5777), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/NcIP7xI-T4-bBsxiWXGZbA), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8673)
Approved by: emilio
Pushing 5e52992c6bd6400736f32399cb16bfb52a1b4e8b to master...

2018-11-05 17:56 UTC, merged