Hint ./mach fmt
servo/servo pull request #22141
Opened 2018-11-07 19:08 UTC by pyfisch

Just thought that a note how to fix if rustfmt fails would be nice.

2018-11-07 19:08 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/testing_commands.py

2018-11-07 19:08 UTC, pyfisch commented
r? @SimonSapin

2018-11-07 19:21 UTC, jdm requested changes

2018-11-07 19:32 UTC, pyfisch commented
text changed

2018-11-07 19:44 UTC, SimonSapin commented
@bors-servo r+

2018-11-07 19:44 UTC, bors-servo commented
:pushpin: Commit 694991a has been approved by `SimonSapin`

<!-- @bors-servo r=SimonSapin 694991ad7e74dcbe42544c049d834e4d664b353f -->

2018-11-08 01:57 UTC, bors-servo commented
:hourglass: Testing commit 694991ad7e74dcbe42544c049d834e4d664b353f with merge b1fd6237d1304f3d57abdafd3e6e738c1ece9f83...

2018-11-08 03:01 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/13068), [android-mac](http://build.servo.org/builders/android-mac/builds/386), [android-x86](http://build.servo.org/builders/android-x86/builds/1190), [arm32](http://build.servo.org/builders/arm32/builds/13237), [arm64](http://build.servo.org/builders/arm64/builds/13270), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13364), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10448), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10485), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13336), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/5817), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5822), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10095), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10137), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/5905), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5830), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8726)
Approved by: SimonSapin
Pushing b1fd6237d1304f3d57abdafd3e6e738c1ece9f83 to master...

2018-11-08 03:01 UTC, merged