OffscreenCanvas API
servo/servo pull request #22168
Opened 2018-11-10 22:43 UTC by PrayaniSingh0106

@maharsh312 @chiaggs
We have implemented .rs files for OffscreenCanvas and OffscreenCanvasRenderingContext2D. We are facing issues while building and not able to resolve it. Please suggest some changes that are required. 
r? @jdm
---

- [ ] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #14627 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2018-11-10 22:43 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @jdm (or someone else) soon.

2018-11-10 22:43 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/offscreencanvas.rs, components/script/dom/webidls/OffscreenCanvasRenderingContext2d.webidl, components/script/dom/mod.rs, components/script/dom/offscreencanvasrenderingcontext2d.rs, components/script/dom/webidls/OffscreenCanvas.webidl
 * @kichjang: components/script/dom/offscreencanvas.rs, components/script/dom/webidls/OffscreenCanvasRenderingContext2d.webidl, components/script/dom/mod.rs, components/script/dom/offscreencanvasrenderingcontext2d.rs, components/script/dom/webidls/OffscreenCanvas.webidl

2018-11-10 22:44 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-11-11 03:56 UTC, jdm requested changes

2018-11-11 03:56 UTC, jdm commented on components/script/dom/webidls/OffscreenCanvasRenderingContext2d.webidl
> +interface OffscreenCanvasRenderingContext2D {
TravisCI doesn't like that this file is named `OffscreenCanvasRenderingContext2d.webidl`, while the interface is named `OffscreenCanvasRenderingContext2D`. The filename should match the interface name (ie. `2D`, not `2d`).

2018-11-15 21:09 UTC, jdm commented
1. `./mach test-tidy` flags a bunch of style problems that will be fixed with `./mach fmt`.
1. `./mach test-tidy` also reports a bunch of a style problems that require manual correction.

```
error[E0583]: file not found for module `OffscreenCanvasRenderingContext2DBinding`
   --> /home/travis/build/servo/servo/target/debug/build/script-acb85a32eed9e872/out/Bindings/mod.rs:209:9
    |
209 | pub mod OffscreenCanvasRenderingContext2DBinding;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: name the file either OffscreenCanvasRenderingContext2DBinding.rs or OffscreenCanvasRenderingContext2DBinding/mod.rs inside the directory "/home/travis/build/servo/servo/target/debug/build/script-acb85a32eed9e872/out/Bindings"
                                                                                
error: aborting due to previous error
                                                                                
For more information about this error, try `rustc --explain E0583`.
error: Could not compile `script`.
```
This error is caused by the mismatch between `OffscreenCanvasRenderingContext2d` and `OffscreenCanvasRenderingContext2D` that I mentioned previously.

2018-12-06 02:00 UTC, maharsh312 commented
@jdm Our build is failing without giving any specific errors. It just says "Could not compile `script`". Can help us figure out this?

2018-12-17 20:59 UTC, closed without merging