Preload servo.org
servo/servo pull request #22263
Opened 2018-11-23 22:40 UTC by Darkspirit

Pending submissions of servo.org and searchfox.org were [merged](https://chromium.googlesource.com/chromium/src/net/+log/master/http/transport_security_state_static.json) into the HSTS Preload list today.
r? @jdm

---
- [x] `./mach test-tidy` does not report any errors

2018-11-23 22:40 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webidls/PerformanceResourceTiming.webidl, components/script/dom/webidls/PerformanceNavigationTiming.webidl, components/script/dom/performanceresourcetiming.rs, components/script/dom/performancenavigationtiming.rs
 * @wafflespeanut: python/servo/servo-binary-formula.rb.in
 * @kichjang: components/script/dom/webidls/PerformanceResourceTiming.webidl, components/script/dom/webidls/PerformanceNavigationTiming.webidl, components/script/dom/performanceresourcetiming.rs, components/script/dom/performancenavigationtiming.rs

2018-11-23 22:40 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-11-25 18:05 UTC, servo-wpt-sync commented
Opened new PR for upstreamable changes.

Completed upstream sync of web-platform-test changes at https://github.com/web-platform-tests/wpt/pull/14225.

2018-11-27 09:10 UTC, nox commented
Please squash the two last commits together.

2018-11-27 13:39 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#14225.

2018-11-27 17:12 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#14225.

2018-11-27 17:56 UTC, jdm requested changes

2018-11-27 17:56 UTC, jdm commented on tests/wpt/web-platform-tests/tools/third_party/certifi/LICENSE
> +one at https://mozilla.org/MPL/2.0/.
This is a vendored dependency from upstream, so let's not modify it.

2018-11-27 17:56 UTC, jdm commented on tests/wpt/web-platform-tests/html/semantics/embedded-content/the-iframe-element/stash.py
> +# file, You can obtain one at https://mozilla.org/MPL/2.0/.
I would rather not make any changes to upstream WPT files as part of our HTTP->HTTPS work. Let's revert any changes under tests/wpt/web-platform-tests.

2018-11-27 18:16 UTC, servo-wpt-sync commented
No upstreamable changes; closed existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#14225.

2018-11-28 06:15 UTC, Manishearth commented
@bors-servo r=jdm

2018-11-28 06:15 UTC, bors-servo commented
:pushpin: Commit f1f409f has been approved by `jdm`

<!-- @bors-servo r=jdm f1f409ffb6774efb3f7e7e5998153eb5b12c1590 -->

2018-11-28 07:34 UTC, bors-servo commented
:hourglass: Testing commit f1f409ffb6774efb3f7e7e5998153eb5b12c1590 with merge 3f0643c1def19b1d0b38204c0ed483643d8cdb81...

2018-11-28 08:45 UTC, bors-servo commented
:sunny: Test successful - [android](http://build.servo.org/builders/android/builds/13256), [android-mac](http://build.servo.org/builders/android-mac/builds/568), [android-x86](http://build.servo.org/builders/android-x86/builds/1387), [arm32](http://build.servo.org/builders/arm32/builds/13420), [arm64](http://build.servo.org/builders/arm64/builds/13452), [linux-dev](http://build.servo.org/builders/linux-dev/builds/13560), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/10906), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/10959), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/13512), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6004), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/5999), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10271), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10312), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6075), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/5999), [magicleap](http://build.servo.org/builders/magicleap/builds/181), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/J7AFgBQGQZWQWWjcxAzYmA), [windows-msvc-dev](http://build.servo.org/builders/windows-msvc-dev/builds/8901)
Approved by: jdm
Pushing 3f0643c1def19b1d0b38204c0ed483643d8cdb81 to master...

2018-11-28 08:45 UTC, merged