Update src/href attributes to be a USVString
servo/servo pull request #22456
Opened 2018-12-14 04:10 UTC by dlrobertson

The following IDLs have the src/href attributes typed as a `DOMString`
while in the spec the attribute has been updated to be a `USVString`:

 - [HTMLIFrameElement]
 - [HTMLImageElement]
 - [HTMLInputElement]
 - [HTMLLinkElement]
 - [HTMLMediaElement]
 - [HTMLScriptElement]

Fixes: #22454 

[HTMLIFrameElement]: https://html.spec.whatwg.org/multipage/#htmliframeelement
[HTMLImageElement]: https://html.spec.whatwg.org/multipage/#htmlimageelement
[HTMLInputElement]: https://html.spec.whatwg.org/multipage/#htmlinputelement
[HTMLLinkElement]: https://html.spec.whatwg.org/multipage/#htmllinkelement
[HTMLMediaElement]: https://html.spec.whatwg.org/multipage/#htmlmediaelement
[HTMLScriptElement]: https://html.spec.whatwg.org/multipage/#htmlscriptelement

2018-12-14 04:10 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/htmliframeelement.rs, components/script/dom/htmllinkelement.rs, components/script/dom/webidls/HTMLScriptElement.webidl, components/script/dom/macros.rs, components/script/dom/webidls/HTMLInputElement.webidl and 10 more
 * @kichjang: components/script/dom/htmliframeelement.rs, components/script/dom/htmllinkelement.rs, components/script/dom/webidls/HTMLScriptElement.webidl, components/script/dom/macros.rs, components/script/dom/webidls/HTMLInputElement.webidl and 10 more

2018-12-14 04:10 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2018-12-14 07:09 UTC, ferjm requested changes
LGTM. There are a couple of DOMStrings that should be USVStrings left though. Thanks!

2018-12-14 07:09 UTC, ferjm commented on components/script/dom/webidls/HTMLMediaElement.webidl
>    readonly attribute DOMString currentSrc;
According to the spec, `currentSrc` should also be an `USVString`

2018-12-14 07:09 UTC, ferjm commented on components/script/dom/webidls/HTMLImageElement.webidl
>             attribute DOMString srcset;
`srcset` and `currentSrc` should also be `USVString`s

2018-12-14 17:17 UTC, SimonSapin commented
Testing https://github.com/mozilla/treeherder/pull/4371

@bors-servo try=linux

2018-12-14 17:17 UTC, bors-servo commented
:hourglass: Trying commit 86f715a5a8f185aa01da3511b9078ede108ebf6c with merge d443b2a8f6cfe43ab3d3c92a154deefe9d0c0da9...

2018-12-14 18:31 UTC, bors-servo commented
:hourglass: Trying commit 86f715a5a8f185aa01da3511b9078ede108ebf6c with merge 8ca7be9e01368a77b97bd5f0b85aca2092b0f5bc...

2018-12-14 22:44 UTC, dlrobertson commented
@ferjm updated

2018-12-17 13:47 UTC, ferjm approved these changes
Looks good. Thanks!

2018-12-17 13:47 UTC, ferjm commented on components/script/dom/bindings/str.rs
> +impl<'a> From<&'a str> for USVString {
What do we need this for? I can't see us using it at the moment.

2018-12-17 13:47 UTC, ferjm commented on components/script/dom/bindings/str.rs
> +impl<'a> From<Cow<'a, str>> for USVString {
We do not seem to need this either.

2018-12-17 15:37 UTC, dlrobertson commented
:+1: Removed them. They were implemented for `DOMString`, so I thought they might be useful down the road, but we can add them later if we need them.

2018-12-17 15:41 UTC, ferjm commented
Thanks!

@bors-servo r+

2018-12-17 15:41 UTC, bors-servo commented
:pushpin: Commit c46508e has been approved by `ferjm`

<!-- @bors-servo r=ferjm c46508e497e503c8fd42deb26aa536060334a9c9 -->

2018-12-17 15:55 UTC, bors-servo commented
:hourglass: Testing commit c46508e497e503c8fd42deb26aa536060334a9c9 with merge d10ab83cba0fe0191f5f446ec3499dc3590d3d8f...

2018-12-17 16:46 UTC, ferjm commented
@bors-servo retry
- #15719

2018-12-17 17:07 UTC, bors-servo commented
:hourglass: Testing commit c46508e497e503c8fd42deb26aa536060334a9c9 with merge 378f65f42faf5c57deb142e072faf7f501c527c3...

2018-12-17 17:35 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/dDrl171dTY6J6M3E9AJ_Cw)

2018-12-17 20:01 UTC, ferjm commented
@bors-servo retry
- #16627

2018-12-17 20:20 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2018-12-17 20:31 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2018-12-17 20:31 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2018-12-17 20:34 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2018-12-17 20:34 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2018-12-17 20:34 UTC, bors-servo commented
:hourglass: Testing commit c46508e497e503c8fd42deb26aa536060334a9c9 with merge cf21b9c3b899234d47dd3602587c5128254562eb...

2018-12-17 21:05 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/VAb_LcXGSOSuXFg1Cz3oZA)

2018-12-17 21:07 UTC, dlrobertson commented
The same tests fail locally for me, but they also fail for `HEAD~`

2018-12-22 04:06 UTC, jdm commented
@bors-servo retry

2018-12-22 11:49 UTC, bors-servo commented
:hourglass: Testing commit c46508e497e503c8fd42deb26aa536060334a9c9 with merge d581e90b230262f77057f2316f4fe81bb6a11542...

2018-12-22 12:38 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6243)

2018-12-22 14:33 UTC, jdm commented
@bors-servo retry

2018-12-22 20:41 UTC, bors-servo commented
:hourglass: Testing commit c46508e497e503c8fd42deb26aa536060334a9c9 with merge 1751958633e6ef21357c2a0a789a47be1202636e...

2018-12-22 21:19 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6292)

2018-12-22 23:52 UTC, jdm commented
@bors-servo retry

2018-12-23 00:57 UTC, bors-servo commented
:hourglass: Testing commit c46508e497e503c8fd42deb26aa536060334a9c9 with merge 13fd9b05c9f6277fc94be1cf5b579f1e4ca3a488...

2018-12-23 01:48 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6218)

2018-12-23 04:50 UTC, bors-servo commented
:hourglass: Testing commit c46508e497e503c8fd42deb26aa536060334a9c9 with merge 27577955aa1c61a91809389a07846f0259a0a939...

2018-12-23 06:00 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/797), [arm32](http://build.servo.org/builders/arm32/builds/13664), [arm64](http://build.servo.org/builders/arm64/builds/13693), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11251), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11307), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6261), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6237), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10495), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10542), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6300), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6221), [magicleap](http://build.servo.org/builders/magicleap/builds/410), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/YX9NY6cXQdazh6D9ZLTT8g)
Approved by: ferjm
Pushing 27577955aa1c61a91809389a07846f0259a0a939 to master...

2018-12-23 06:00 UTC, merged