Serialize the children of void html elements as empty strings
servo/servo pull request #22542
Opened 2018-12-23 16:37 UTC by georgeroman

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22502  (GitHub issue number if applicable)

2018-12-23 16:37 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/element.rs
 * @kichjang: components/script/dom/element.rs

2018-12-23 17:06 UTC, CYBAI commented
I found the `menuitem` is not in the list of `Void Elements`; maybe it's worth removing it in this PR?

https://github.com/servo/servo/blob/29eb8bd2b426dbbb4f4f09ef60239fd489b20b23/components/script/dom/element.rs#L1099-L1101

Ref:
- https://html.spec.whatwg.org/#void-elements
- https://html.spec.whatwg.org/#serialising-html-fragments:void-elements

2018-12-23 17:12 UTC, CYBAI commented on components/script/dom/element.rs
> +            TraversalScope::ChildrenOnly(_) => {
Maybe we can use `if let` here?

```rust
if let TraversalScope::ChildrenOnly(_) = traversal_scope {
  if self.is_void() {
    return Ok(DOMString::from(""));
  }
}
```

2018-12-26 06:35 UTC, paulrouget commented
@bors-servo r+

2018-12-26 06:35 UTC, bors-servo commented
:pushpin: Commit 715ee7b has been approved by `paulrouget`

<!-- @bors-servo r=paulrouget 715ee7b6a5504cf9a6dce43af3b15bd716dc33f9 -->

2018-12-26 06:35 UTC, bors-servo commented
:hourglass: Testing commit 715ee7b6a5504cf9a6dce43af3b15bd716dc33f9 with merge 1862c8252ce11e81d6ba42c15534d638db679c0e...

2018-12-26 06:53 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/OHc1sMlpS0Gsp64TxCwDOw)

2018-12-26 13:38 UTC, jdm commented
It's not totally clear to me whether this code belongs in html5ever or Servo. I would like to review it further.

2019-01-02 14:00 UTC, jdm commented
I have reviewed the specification and this code change looks too specific to me. I'll add some more information to the github issue, since the code change likely belongs in the html5ever repository.

2019-01-02 14:56 UTC, jdm commented
I've changed my mind - I think this change is necessary, but I think it belongs in components/script/dom/servoparser/html.rs in Node::serialize instead.

2019-01-02 22:30 UTC, jdm requested changes

2019-01-02 22:30 UTC, jdm commented on components/script/dom/servoparser/html.rs
> +            if node.downcast::<Element>().unwrap().is_void() {
We should use `if node.downcast::<Element>().map_or(false, |e| e.is_void()) {` instead, so we do not panic when serializing non-element nodes.

2019-01-03 20:17 UTC, jdm commented
@bors-servo r+

2019-01-03 20:17 UTC, bors-servo commented
:pushpin: Commit a2d5d4f has been approved by `jdm`

<!-- @bors-servo r=jdm a2d5d4f3da809a5dcb6a4f73278a64660235cdfe -->

2019-01-03 20:17 UTC, bors-servo commented
:hourglass: Testing commit a2d5d4f3da809a5dcb6a4f73278a64660235cdfe with merge c19cc66b30569931f1d123affd58c7a4dc7843cf...

2019-01-03 20:40 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11384)

2019-01-03 22:46 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/862), [arm32](http://build.servo.org/builders/arm32/builds/13730), [arm64](http://build.servo.org/builders/arm64/builds/13758), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11329), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11385), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6334), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6304), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10557), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10609), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6365), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6286), [magicleap](http://build.servo.org/builders/magicleap/builds/477), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/BR8aCPFRQA-JjzXGWXmZGA)
Approved by: jdm
Pushing 7c34a70ca8d2087e5d1b7b29ae128b803cecacf9 to master...

2019-01-03 22:46 UTC, merged