PerformanceResourceTiming: RedirectEnd
servo/servo pull request #22561
Opened 2018-12-26 12:28 UTC by verma-varsha

---
 
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #21257  (GitHub issue number if applicable)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/servo/22561)

2019-01-10 07:56 UTC, verma-varsha commented
@jdm @avadacatavra Can you please help me get the changes reviewed?

2019-01-14 23:53 UTC, jdm requested changes
The changes in this PR implement the timing part, but we will also need to implement the DOM API in components/script/dom/webidls/PerformanceResourceTiming.webidl and components/script/dom/performanceresourcetiming.rs.

2019-01-14 23:53 UTC, jdm commented on components/net/http_loader.rs
> +        .set_attribute(ResourceAttribute::RedirectEnd);
Unfortunately I think the TODO was misleading. Much like my review comment in #22319, step 20 of https://w3c.github.io/resource-timing/#processing-model suggests that this should be set in a different part of the code, and will be very similar to how we implement responseEnd (#21263). This part of the code has only just received the HTTP headers, not the response body.

2019-01-29 05:05 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #22714) made this pull request unmergeable. Please resolve the merge conflicts.

2019-02-11 16:32 UTC, jdm commented
@verma-varsha Are you still planning to complete this work?

2019-02-13 07:16 UTC, verma-varsha commented
@jdm I was caught up with some other work which led me to losing track of this. Thanks for reminding. I'll try to update the PR in a few days.

2019-02-27 17:25 UTC, jdm commented
I'm going to go ahead and close this due to inactivity. If you return to it, go ahead and reopen it!

2019-02-27 17:25 UTC, closed without merging