Make XR/VR presenting code async
servo/servo pull request #22649
Opened 2019-01-08 02:06 UTC by Manishearth

Previously we only pretended to be async, we returned promises that were already resolved because we synchronously blocked on the channel.

This:

 - Moves XR presentation to session creation (where it belongs)
 - Factors out common presentation code in a way that supports asynchronously resolving promises
 - Uses this for `VRDisplay::RequestPresent()` and `XR::RequestSession()`

r? @jdm

2019-01-08 02:06 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/vrdisplay.rs, components/script/dom/xr.rs, components/script/dom/xrsession.rs
 * @kichjang: components/script/dom/vrdisplay.rs, components/script/dom/xr.rs, components/script/dom/xrsession.rs

2019-01-08 02:06 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-01-08 02:07 UTC, Manishearth commented
I haven't actually tested this, it _may_ blow up because the vr code doesn't expect an empty context

2019-01-08 02:07 UTC, Manishearth commented
Oh, it definitely will, we have some unwraps there.

2019-01-08 02:15 UTC, Manishearth commented
And the spec hasn't really ... decided what to do with empty contexts.

(now I remember why I didn't do this in the first place)

The RAF thread complicates this, but I might be able to do something relatively obvious until they decide the behavior.

2019-01-08 03:29 UTC, jdm requested changes

2019-01-08 03:54 UTC, Manishearth commented on components/script/dom/vrdisplay.rs
> +        thread::spawn(move || {
Oh, the recv() is supposed to be outside the task, my bad.

2019-01-08 03:54 UTC, Manishearth commented on components/script/dom/vrdisplay.rs
> +        thread::spawn(move || {
Oh, the recv() is supposed to be outside the task, my bad.

2019-01-08 23:00 UTC, jdm commented
@bors-servo r+

2019-01-08 23:00 UTC, bors-servo commented
:pushpin: Commit e2522d3 has been approved by `jdm`

<!-- @bors-servo r=jdm e2522d36ffa053b10296bbd1c16d60e502f1f452 -->

2019-01-08 23:00 UTC, jdm approved these changes

2019-01-08 23:33 UTC, bors-servo commented
:hourglass: Testing commit e2522d36ffa053b10296bbd1c16d60e502f1f452 with merge ce95b9643fdfeb80e95b2e43a276e11456838dd3...

2019-01-09 01:03 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/909), [arm32](http://build.servo.org/builders/arm32/builds/13781), [arm64](http://build.servo.org/builders/arm64/builds/13809), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11388), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11444), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6383), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6353), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10603), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10660), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6411), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6339), [magicleap](http://build.servo.org/builders/magicleap/builds/527), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/GXgsRz9DRXaJC18V3wb1rg)
Approved by: jdm
Pushing ce95b9643fdfeb80e95b2e43a276e11456838dd3 to master...

2019-01-09 01:03 UTC, bors-servo commented
:eyes: Test was successful, but fast-forwarding failed: 422 Update is not a fast forward

2019-01-09 01:42 UTC, jdm commented
@bors-servo retry

2019-01-09 01:42 UTC, bors-servo commented
:hourglass: Testing commit e2522d36ffa053b10296bbd1c16d60e502f1f452 with merge 44cbe969e24e65fc8f82f77bac6374ceb4aa0e71...

2019-01-09 03:04 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/910), [arm32](http://build.servo.org/builders/arm32/builds/13782), [arm64](http://build.servo.org/builders/arm64/builds/13810), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11389), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11445), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6384), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6354), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10604), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10661), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6412), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6340), [magicleap](http://build.servo.org/builders/magicleap/builds/528), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/Sheq_7EaQNycLzGKgFqMig)
Approved by: jdm
Pushing 44cbe969e24e65fc8f82f77bac6374ceb4aa0e71 to master...

2019-01-09 03:04 UTC, merged

2019-01-09 03:19 UTC, Manishearth commented
oh this wasn't supposed to merge, like I said this will panic unconditionally

(and that's a bit tricky to fix)

I've got a WIP for fixing this.

Since I'm the only one using XR rn it's fine to leave it as is though

2019-01-09 04:49 UTC, jdm commented
Oops!