refactor RenderNotifier into servo/lib.rs
servo/servo pull request #22713
Opened 2019-01-17 04:08 UTC by nikopen

Fixes #22707

2019-01-17 04:08 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @paulrouget (or someone else) soon.

2019-01-17 04:08 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @paulrouget: components/compositing/compositor.rs

2019-01-17 09:23 UTC, paulrouget commented
You also need to add the proper `use` in servo/lib.rs, and remove the useless one in compositor.rs.

2019-01-24 09:04 UTC, shanavas786 requested changes

2019-01-24 09:04 UTC, shanavas786 commented on components/servo/lib.rs
> +pub struct RenderNotifier {
since its not used anywhere else, we can remove `pub` from here

2019-02-14 00:35 UTC, jdm commented
@nikopen Are you going to finish this work?

2019-02-14 08:41 UTC, shanavas786 commented
I can take this over if @nikopen is not going to finish.

2019-02-28 10:52 UTC, shanavas786 commented
I have absorbed this into #22948

2019-02-28 14:16 UTC, closed without merging