Added fetch_start functionality
servo/servo pull request #22714
Opened 2019-01-17 06:45 UTC by aditj

Added the fetch_start functionality in http_loader.rs (http_fetch function)

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #21258 (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-01-17 06:45 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @simonsapin (or someone else) soon.

2019-01-17 06:45 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webidls/PerformanceResourceTiming.webidl, components/script/dom/performanceresourcetiming.rs
 * @kichjang: components/script/dom/webidls/PerformanceResourceTiming.webidl, components/net_traits/lib.rs, components/script/dom/performanceresourcetiming.rs, components/net/http_loader.rs

2019-01-17 06:46 UTC, servo-wpt-sync commented
Opened new PR for upstreamable changes.

Completed upstream sync of web-platform-test changes at https://github.com/web-platform-tests/wpt/pull/14919.

2019-01-17 11:56 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#14919.

2019-01-17 12:05 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#14919.

2019-01-17 13:22 UTC, SimonSapin commented
The `.wpt-update.lock` file presumably shouldn’t be added. (Should we even add it to some `.gitignore` file?)

r? @avadacatavra

2019-01-18 14:44 UTC, jdm requested changes
This looks like a good start!

2019-01-18 14:44 UTC, jdm commented on components/net/http_loader.rs
> +        .set_attribute(ResourceAttribute::FetchStart);
We should initialize our fetchStart value in https://github.com/servo/servo/blob/49cf3dd3d337689ac72bea1a8ffc5c3e89a2616c/components/net/fetch/methods.rs#L90 instead, so it encompasses all kinds of requests.

2019-01-18 14:44 UTC, jdm commented on components/net/http_loader.rs
> +        if request.redirect_count > 0 && request.headers.contains_key(header::LOCATION) {
We want to check the response headers, not the request ones. However, I think if we add this `set_attribute` call to the `http_redirect_fetch` function, that should automatically cover the cases we care about.

2019-01-18 14:44 UTC, jdm commented on tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/update/.wpt-update.lock
> +ccopy_reg
Please remove this file and run `./mach update-manifest`.

2019-01-18 16:32 UTC, jdm commented on components/net/http_loader.rs
> +        if request.redirect_count > 0 && request.headers.contains_key(header::LOCATION) {
I do not think the header check is needed. If we unconditionally update fetchStart each time http_redirect_fetch is called, then the last updated value will be the correct one.

2019-01-18 19:49 UTC, servo-wpt-sync commented
No upstreamable changes; closed existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#14919.

2019-01-18 20:51 UTC, jdm commented
```
error[E0433]: failed to resolve: use of undeclared type or module `ResourceAttribute`
  --> components/net/fetch/methods.rs:96:24
   |
96 |         .set_attribute(ResourceAttribute::FetchStart);
   |                        ^^^^^^^^^^^^^^^^^ use of undeclared type or module `ResourceAttribute`
error: aborting due to previous error
```
Also you didn't run `./mach update-manifest` like I asked.

2019-01-18 20:51 UTC, jdm commented
To be clear, the results of running `./mach update-manifest` were not included in the most recent commit.

2019-01-18 20:52 UTC, jdm requested changes

2019-01-18 20:52 UTC, jdm commented on components/net/fetch/methods.rs
> +        .set_attribute(ResourceAttribute::FetchStart);
This needs to happen before calling `fetch_with_cors_cache` or it will execute after the fetch is complete.

2019-01-19 07:53 UTC, aditj commented
> To be clear, the results of running `./mach update-manifest` were not included in the most recent commit.

I ran ./mach update-manifest but I dont think the .json file has changes w.r.t. the Servo Master branch , also should I update the test expectations?

2019-01-21 14:13 UTC, jdm commented
@bors-servo try=wpt

2019-01-21 14:13 UTC, bors-servo commented
:hourglass: Trying commit 3d51f14561bb5bd04a550ef55c9bcb9678624c5c with merge 276e36b5502bc4397b2652a2ea687da98d0275c1...

2019-01-21 14:39 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11552)

2019-01-21 14:51 UTC, jdm requested changes

2019-01-21 14:51 UTC, jdm commented on components/net/fetch/methods.rs
> +    context
Let's add a comment here like `// Step 7 of https://w3c.github.io/resource-timing/#processing-model`

2019-01-21 14:51 UTC, jdm commented on components/net/http_loader.rs
> +    context
Let's add a comment here like `// Step 1 of https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-fetchstart`

2019-01-28 14:13 UTC, aditj commented
@ferjm Are the test expectations fine now?

2019-01-28 14:22 UTC, ferjm commented
Let's see if they are.

@bors-servo try=wpt

2019-01-28 20:02 UTC, jdm commented
@bors-servo try=wpt

2019-01-28 20:02 UTC, jdm commented
@bors-servo try-

2019-01-28 20:03 UTC, jdm commented
@bors-servo try=wpt

2019-01-28 20:03 UTC, bors-servo commented
:hourglass: Trying commit 77c928578094d7c9ed2f0c584f9f63e318c7c8c4 with merge 4a3d81bd45b1e95649688f325ad8bcad299064a5...

2019-01-28 20:03 UTC, jdm commented
@bors-servo retry

2019-01-28 20:03 UTC, bors-servo commented
:hourglass: Trying commit 77c928578094d7c9ed2f0c584f9f63e318c7c8c4 with merge 8175dfedd5f9117230f040f0fee447258af42a28...

2019-01-28 20:56 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11532), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11587), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/DSXFocyNQtuamVkTiL-3eA)
State: approved= try=True

2019-01-28 20:57 UTC, jdm commented
@bors-servo r+

2019-01-28 20:57 UTC, bors-servo commented
:pushpin: Commit 77c9285 has been approved by `jdm`

<!-- @bors-servo r=jdm 77c928578094d7c9ed2f0c584f9f63e318c7c8c4 -->

2019-01-28 22:40 UTC, bors-servo commented
:hourglass: Testing commit 77c928578094d7c9ed2f0c584f9f63e318c7c8c4 with merge 20c899f1896751f93f3638a7882d587b9973c229...

2019-01-28 22:59 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11534)

2019-01-28 23:45 UTC, jdm commented
@bors-servo retry
* #13480

2019-01-28 23:45 UTC, bors-servo commented
:hourglass: Testing commit 77c928578094d7c9ed2f0c584f9f63e318c7c8c4 with merge fe07d2c575c797ad2ee88422adacea7806f5c5a1...

2019-01-29 05:04 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/1021), [arm32](http://build.servo.org/builders/arm32/builds/13895), [arm64](http://build.servo.org/builders/arm64/builds/13923), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11535), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11590), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6500), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6467), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10714), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10775), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6524), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6455), [magicleap](http://build.servo.org/builders/magicleap/builds/641), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/O3Vz7gFzR4iO8QhcU9C6wg)
Approved by: jdm
Pushing fe07d2c575c797ad2ee88422adacea7806f5c5a1 to master...

2019-01-29 05:04 UTC, merged