Changed return value of GetActiveCues
servo/servo pull request #22730
Opened 2019-01-18 16:50 UTC by aditj

Return an empty TextTrackCueList rather than Some inside the GetActiveCues.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes fix #22706 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-01-18 16:51 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @nox (or someone else) soon.

2019-01-18 16:51 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/texttrack.rs
 * @kichjang: components/script/dom/texttrack.rs

2019-01-18 17:20 UTC, ferjm requested changes

2019-01-18 17:20 UTC, ferjm commented on components/script/dom/texttrack.rs
> -        //      https://github.com/servo/servo/issues/22314
This comment is still valid. Do not remove it, please.

2019-01-21 08:07 UTC, ferjm approved these changes
Looks good. This is ready to merge after squashing the commits. Thanks!

2019-01-21 08:11 UTC, aditj commented
> Looks good. This is ready to merge after squashing the commits. Thanks!

Ya I was trying that , is there any way I can squash commits of a remote branch(which has not been edited locally) ?

2019-01-21 08:56 UTC, ferjm commented
`git rebase -i HEAD~2` should open the interactive rebase tool in your default text editor. Substitute the `pick` word before the second commit by an `s` or `squash`, save and exit.

2019-01-21 14:53 UTC, ferjm commented
@bors-servo try=wpt

2019-01-21 14:53 UTC, bors-servo commented
:hourglass: Trying commit df1119b7cba3f44c032450bb403c5be0948f08d0 with merge 69419b3569c6e44456d3b8c2c6d3ecd415932cf8...

2019-01-21 15:20 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11497), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11553), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/Ul0HAOORSOWjGENAYhFAkw)
State: approved= try=True

2019-01-21 15:25 UTC, ferjm commented
@bors-servo r+

2019-01-21 15:25 UTC, bors-servo commented
:pushpin: Commit df1119b has been approved by `ferjm`

<!-- @bors-servo r=ferjm df1119b7cba3f44c032450bb403c5be0948f08d0 -->

2019-01-21 15:25 UTC, bors-servo commented
:hourglass: Testing commit df1119b7cba3f44c032450bb403c5be0948f08d0 with merge 8557e159e596592e6c7f2f8364cabebf2a00a4f7...

2019-01-21 16:42 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/PqHIJPOpQbWdprg5opw24w)

2019-01-21 16:45 UTC, ferjm commented
@bors-servo retry

2019-01-21 17:14 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2019-01-21 17:15 UTC, bors-servo commented
:hourglass: Testing commit df1119b7cba3f44c032450bb403c5be0948f08d0 with merge 00148da264429cb4affc891b3828fa868e6baec0...

2019-01-21 18:49 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/995), [arm32](http://build.servo.org/builders/arm32/builds/13868), [arm64](http://build.servo.org/builders/arm64/builds/13896), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11500), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11556), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6473), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6440), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10688), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10748), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6498), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6428), [magicleap](http://build.servo.org/builders/magicleap/builds/614), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/ZgsKsMx6RrO6YY6yFjLvwA)
Approved by: ferjm
Pushing 00148da264429cb4affc891b3828fa868e6baec0 to master...

2019-01-21 18:50 UTC, merged