Refactor follow_hyperlink and its callers
servo/servo pull request #22771
Opened 2019-01-27 23:52 UTC by MaT1g3R

Now they follow the new spec stated at:
https://html.spec.whatwg.org/multipage/links.html#following-hyperlinks-2

It seems like choosing a browsing context is already done in the
follow_hyperlink method, so I have removed the TODO in
activation_behavior for HTMLAreaElement.

The tests in `tests/wpt/web-platform-tests/html/semantics/links/following-hyperlinks/`
pass in release builds, but still don't pass in dev build,
since the timeout in
`tests/wpt/web-platform-tests/html/semantics/links/following-hyperlinks/activation-behavior.window.js`
seems to be too short for dev builds.

Navigating to error page on failed URL parsing is still not implemented.

There seem to be potential code duplication in activation_behavior
methods for both htmlanchorelement.rs and htmlareaelement.rs, in:

    let referrer_policy = match self.RelList().Contains("noreferrer".into()) {
        true => Some(ReferrerPolicy::NoReferrer),
        false => None,
    };

I didn't pull them out to a separate function since I don't know
where I would put that new function.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22761 (GitHub issue number if applicable)

- [X] There are tests for these changes

2019-01-27 23:52 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @avadacatavra (or someone else) soon.

2019-01-27 23:52 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/htmlareaelement.rs, components/script/dom/htmlanchorelement.rs
 * @kichjang: components/script/dom/htmlareaelement.rs, components/script/dom/htmlanchorelement.rs

2019-01-27 23:52 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-01-28 04:04 UTC, CYBAI commented on components/script/dom/htmlanchorelement.rs
> +    // Step 1: If subject cannot navigate, then return.
Without implementing the step, it's fine to leave the `TODO:` with the step description.
As we've implemented it now, I think it's good to just leave the `step` instead; we can check the latest step description from spec :)

```suggestion
    // Step 1
```

2019-01-29 19:45 UTC, jdm requested changes
This looks good! I see one more simplification that we can make, then this should be good to merge.

2019-01-29 19:45 UTC, jdm commented on components/script/dom/htmlanchorelement.rs
>          let referrer_policy = match self.RelList().Contains("noreferrer".into()) {
We should remove this code and replace it by implementing the missing step 12 of `follow_hyperlink`. You can use the `determine_policy_for_token` helper function to get a ReferrerPolicy value from a string.

2019-01-29 19:45 UTC, jdm commented on components/script/dom/htmlareaelement.rs
>          let referrer_policy = match self.RelList().Contains("noreferrer".into()) {
We can remove this code as well.

2019-01-30 13:22 UTC, jdm commented
@bors-servo r+
Thanks!

2019-01-30 13:22 UTC, bors-servo commented
:pushpin: Commit 0bafa61 has been approved by `jdm`

<!-- @bors-servo r=jdm 0bafa61f7cfc4a5783828b8f64e819fd715fea63 -->

2019-01-30 13:22 UTC, bors-servo commented
:hourglass: Testing commit 0bafa61f7cfc4a5783828b8f64e819fd715fea63 with merge 65370f17c98225f7e71c72ea2e0cb2d0a81487f3...

2019-01-30 14:39 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/1031), [arm32](http://build.servo.org/builders/arm32/builds/13905), [arm64](http://build.servo.org/builders/arm64/builds/13933), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11546), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11601), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6510), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6477), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10724), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10785), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6534), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6465), [magicleap](http://build.servo.org/builders/magicleap/builds/651), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/F__UjACRTUSrelrbR1Opbw)
Approved by: jdm
Pushing 65370f17c98225f7e71c72ea2e0cb2d0a81487f3 to master...

2019-01-30 14:39 UTC, merged