[WIP] Support for ExternalVR implementation
servo/servo pull request #22773
Opened 2019-01-28 08:43 UTC by paulrouget

This PR adds the hook necessary for the ExternalVR rust-webvr driver.
Waiting on rust-webvr 0.9.3 to be published before landing.

2019-01-28 12:57 UTC, paulrouget commented
r? @jdm

2019-01-28 19:54 UTC, jdm requested changes

2019-01-28 19:54 UTC, jdm commented on ports/libsimpleservo/jniapi/src/lib.rs
> +        .map_err(|_| "height not an int")? as *mut c_void;
Wrong error message.

2019-01-28 19:55 UTC, jdm commented
@bors-servo delegate+

2019-01-28 19:55 UTC, bors-servo commented
:v: @paulrouget can now approve this pull request

2019-01-28 19:56 UTC, jdm commented
Appveyor:
```
error[E0432]: unresolved import `rust_webvr::api::VRExternalShmemPtr`
  --> components\webvr\lib.rs:12:9
   |
12 | pub use rust_webvr::api::VRExternalShmemPtr;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `VRExternalShmemPtr` in `api`
error[E0599]: no method named `register_vrexternal` found for type `rust_webvr::vr_manager::VRServiceManager` in the current scope
  --> components\webvr\webvr_thread.rs:61:21
   |
61 |             service.register_vrexternal(ptr);
   |                     ^^^^^^^^^^^^^^^^^^^
error: aborting due to 2 previous errors
```
Travis is extremely displeased by the rust-webvr upgrade.

2019-01-29 10:33 UTC, paulrouget commented
That fails because of Servo, not webvr. I'm going to make it so webvr exposes the same API no matter the platform: https://github.com/servo/rust-webvr/pull/44

2019-02-05 07:15 UTC, paulrouget commented
Fixed non-android builds on rust-webvr side.
Fixed the error message.

@bors-servo r=jdm

2019-02-05 07:15 UTC, bors-servo commented
:pushpin: Commit 6a8cfc1 has been approved by `jdm`

<!-- @bors-servo r=jdm 6a8cfc107d5372cefa306af2a8629ff21f7f15e6 -->

2019-02-05 15:00 UTC, bors-servo commented
:hourglass: Testing commit 6a8cfc107d5372cefa306af2a8629ff21f7f15e6 with merge 6592f7a9ff973d7593d12f20058a592a35ae17ef...

2019-02-05 15:15 UTC, bors-servo commented
:broken_heart: Test failed - [magicleap](http://build.servo.org/builders/magicleap/builds/667)

2019-02-05 15:20 UTC, jdm commented
```
error[E0560]: struct `api::vrexternal::android::mozgfx::VRLayer_Stereo_Immersive` has no field named `__bindgen_padding_0`
   --> /Users/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-webvr-0.9.15/src/api/vrexternal/android/display.rs:227:17
    |
227 |                 __bindgen_padding_0: 0,
    |                 ^^^^^^^^^^^^^^^^^^^ `api::vrexternal::android::mozgfx::VRLayer_Stereo_Immersive` does not have this field
    |
    = note: available fields are: `mTextureHandle`, `mTextureType`, `mFrameId`, `mInputFrameId`, `mLeftEyeRect`, `mRightEyeRect`

error[E0560]: struct `api::vrexternal::android::mozgfx::VRLayerState` has no field named `__bindgen_padding_0`
   --> /Users/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-webvr-0.9.15/src/api/vrexternal/android/display.rs:234:13
    |
234 |             __bindgen_padding_0: 0,
    |             ^^^^^^^^^^^^^^^^^^^ `api::vrexternal::android::mozgfx::VRLayerState` does not have this field
    |
    = note: available fields are: `type_`, `__bindgen_anon_1`

error: aborting due to 2 previous errors
```
The way we solve this in other places is:
```rust
        let layer_stereo_immersive = {
            let rendered_layer = self.rendered_layer.as_ref().unwrap();
            mozgfx::VRLayer_Stereo_Immersive {
                mTextureHandle: rendered_layer.texture_id as u64,
                mTextureType: mozgfx::VRLayerTextureType_LayerTextureType_GeckoSurfaceTexture,
                mFrameId: self.system_state.sensorState.inputFrameID,
                mLeftEyeRect: mozgfx::VRLayerEyeRect {
                    x: rendered_layer.left_bounds[0],
                    y: rendered_layer.left_bounds[1],
                    width: rendered_layer.left_bounds[2],
                    height: rendered_layer.left_bounds[3],
                },
                mRightEyeRect: mozgfx::VRLayerEyeRect {
                    x: rendered_layer.right_bounds[0],
                    y: rendered_layer.right_bounds[1],
                    width: rendered_layer.right_bounds[2],
                    height: rendered_layer.right_bounds[3],
                },
                mInputFrameId: 0,
                ...mozgfx::VRLayer_Stereo_Immersive::default()
            }
};
```

2019-02-06 06:41 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/eMqbmhEdRAiW05M73sn4Og)

2019-02-06 07:18 UTC, paulrouget commented
Android x86 build error.

2019-02-07 05:17 UTC, paulrouget commented
Hopefully this is the good one.

@bors-servo r=jdm

2019-02-07 05:17 UTC, bors-servo commented
:pushpin: Commit c055b74 has been approved by `jdm`

<!-- @bors-servo r=jdm c055b74e13f255b351efc969a19acfd9724076e4 -->

2019-02-07 05:17 UTC, bors-servo commented
:hourglass: Testing commit c055b74e13f255b351efc969a19acfd9724076e4 with merge 6c161e5037072daf9176c68dd0b0f481620ab887...

2019-02-07 06:41 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/1062), [arm32](http://build.servo.org/builders/arm32/builds/13936), [arm64](http://build.servo.org/builders/arm64/builds/13964), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11580), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11635), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6542), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6509), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10755), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10817), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6567), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6498), [magicleap](http://build.servo.org/builders/magicleap/builds/682), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/EnNJwywiQ5OwRnPsKUbkYg)
Approved by: jdm
Pushing 6c161e5037072daf9176c68dd0b0f481620ab887 to master...

2019-02-07 06:41 UTC, merged