WIP Add OpenGL support to libsimpleservo ...
servo/servo pull request #22805
Opened 2019-02-01 15:28 UTC by Hyperion101010

I have posted this first commit, just to take review that am i going on right track  ?

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #___ (GitHub issue number if applicable)

- [x] There are tests for these changes OR
- [x] These changes do not require tests because ___

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/servo/22805)

2019-02-01 15:31 UTC, jdm commented
@Hyperion101010 That looks like the right idea to me.

2019-02-03 05:07 UTC, paulrouget commented
If you need help compiling/testing on Windows, Linux and/or Mac, let me know.
If you don't want our CI to build your PR, prefix the title of your PR with "WIP ".

We should probably add a simple example (under libsimplerservo/example/) to check if this will work correctly. I can look at this if it helps.

2019-02-03 06:55 UTC, Hyperion101010 commented
I guess there wasn't a test case checking the new changes,but the file compiled successfully though 
Any rough idea what we are going to do next ?

2019-02-03 06:59 UTC, Hyperion101010 commented
If it is solved , i am turning to https://github.com/servo/servo/issues/22760.
It was the soul purpose i tried fixing this first :)

2019-02-03 07:14 UTC, paulrouget commented
The linux part doesn't look right to me.

You need to use glx (at least for now). See https://github.com/tomaka/glutin/blob/c16f997e4c6898bc3a3603c74c341c2a5497839c/src/platform/linux/x11.rs#L113

This is basically the hard part :)

The code I pointed to implement a `get_proc_address` method down the line (I think it's [here](https://github.com/tomaka/glutin/blob/c16f997e4c6898bc3a3603c74c341c2a5497839c/src/api/glx/mod.rs#L131]). You need to use that method inside `load_with`.

Basically, in the load_with method, you need to create a ffi::glx::Glx instance (as for EGL, you will need to create bindings. See how it's done [here](https://github.com/tomaka/glutin/blob/1ad6560860d37c1945cc9ffece645f66518f1d0f/src/api/glx/mod.rs#L24)) and call glx.GetProcAddress.

2019-02-03 07:17 UTC, paulrouget commented
> If it is solved , i am turning to #22760.
> It was the soul purpose i wanted to fix this :)

That's great! I guess you could patch up something to see if your PR works with a libsimpleservo-based glutin port (it should work on Mac at least).

2019-02-03 07:18 UTC, Hyperion101010 commented
lets add for linux first , then i can atleast test myself on mu linux platform

2019-02-03 08:47 UTC, Hyperion101010 commented
hey paul you can now check the patch for linux as well , let me know that have i properly implemented GetProcAddressfunction ".

2019-02-04 06:41 UTC, paulrouget commented
The linux code is not doing the right think. You need to dlopen the libgl. See https://github.com/tomaka/glutin/blob/c16f997e4c6898bc3a3603c74c341c2a5497839c/src/platform/linux/x11.rs#L42 - And use this instance of glx to call GetProcAddress.

2019-02-05 07:12 UTC, paulrouget requested changes
I have the feeling you're a bit unsure about the general mechanic here.

Let me summarize a bit how OpenGL is loaded:

`GLFns::load_with` returns a GL object.
The GL object is initialized from a callback (the one passed to `load_with`). Basically, This callback is called with a name of a GL function, and the callback needs to return a pointer to that GL function. So in that callback, we need to find, in memory, the address of the symbol.

So there are 2 things to do: first make sure the GL library is loaded (which will make all the symbol available in memory), second, find the address of the symbol.

To load, we use `dlopen("mylib.so")`. To find the address, we usually use `dlsym`. But in the case of GL, there's a helper function, called `GetProcAddress`. But loading a library doesn't magically make GetProcAddress available. `dlsym` is needed or, in the case of GLX, there's a helper: `Glx::load_with`.

Hope this clarifies a bit :)

2019-02-05 07:12 UTC, paulrouget commented on ports/libsimpleservo/api/src/gl_glue.rs
> +        let opengl_pointer = ffi::glx::Glx::load_with(|addr| {
I'm surprised this compiles. Does `Glx::load_with` return a `Gl` object?

2019-02-05 07:12 UTC, paulrouget commented on ports/libsimpleservo/api/src/gl_glue.rs
> +            unsafe { ffi::glx::Glx::GetProcAddress(addr_name.as_ptr() as *const _) as *const _ }
You can't just use `Glx` like that. You need to initialize it from the opened library.

See https://github.com/tomaka/glutin/blob/c16f997e4c6898bc3a3603c74c341c2a5497839c/src/platform/linux/x11.rs#L54

I haven't tested, but it should look like this:

```
let glx = Glx::load_with(|sym| {
  let sym = CString::new(sym).unwrap();
  unsafe { dlopen::dlsym(libglx, sym.as_ptr()) }
});

opengl_pointer = gl::GlFns::load_with(| addr|  glx.GetProcAddress(addr))
```

2019-02-06 07:21 UTC, paulrouget commented
> About extra bindings paul i haven't researched it, but i read that it might be required for some other specialized frameworks that req OpenGl.
> But anyways it is fair that we neglect it

The problem is that you declare it but never use it.

2019-02-07 08:00 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #22832) made this pull request unmergeable. Please resolve the merge conflicts.

2019-02-08 08:00 UTC, Hyperion101010 commented
I am closing this due to lack of my knowledge , I'll fix some simple bugs work on rust for a while .
In future I might try it . And sorry for any inconvenience caused 
See ya

2019-02-08 08:01 UTC, closed without merging