Make blank target imply noopener
servo/servo pull request #22851
Opened 2019-02-08 11:06 UTC by georgeroman

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22845

2019-02-08 11:06 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/htmlanchorelement.rs
 * @kichjang: components/script/dom/htmlanchorelement.rs

2019-02-08 11:06 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-02-08 14:12 UTC, CYBAI approved these changes
Other than the nit, the `Maketarget=_blank imply noopener` part looks fine to me. But, it seems we didn't support [rel=opener](https://html.spec.whatwg.org/multipage/#link-type-opener) yet so maybe let's update the PR description to `These changes fix part of #22845` ?

Besides, the WPT test PR for the spec update has not been merged yet. Let's wait the PR merged and then try wpt for this PR?

cc @jdm @gterzian

2019-02-08 14:12 UTC, CYBAI commented on components/script/dom/htmlanchorelement.rs
> +            match name.Value().to_lowercase().as_ref() {
nit: How about doing like following?

```rust
let target_is_blank = if let Some(name) = target_attribute_value.as_ref() {
    name.Value().to_lowercase() == "_blank"
} else {
  false
};
```

2019-02-08 14:20 UTC, gterzian commented
> But, it seems we didn't support [rel=opener](https://html.spec.whatwg.org/multipage/#link-type-opener) yet so maybe let's update the PR description to `These changes fix part of #22845` ?

The way I understand the change of the spec, is the an explicit `rel=opener` is now required for a `target=_blank` to open an new auxiliary, wherease previously the `rel=opener` was implied, unless an explicit `rel=noopener` was present(and we supported this via https://github.com/servo/servo/blob/71ba247942a95d1511c9fa62f06d860fcc03de1c/components/script/dom/windowproxy.rs#L456.)

2019-02-09 15:06 UTC, gterzian requested changes
Thanks for the contribution! Looks good so far!

As suggested earlier, we should also wait for https://github.com/web-platform-tests/wpt/pull/15188 to merge, and for servo to sync this change(which will look like https://github.com/servo/servo/pull/22859)...

2019-02-09 15:19 UTC, gterzian commented on components/script/dom/htmlanchorelement.rs
> +        let target_is_blank = if let Some(name) = target_attribute_value.as_ref() {
It is indeed relevant, just seeing step 6 of https://html.spec.whatwg.org/multipage/links.html#following-hyperlinks-2

2019-02-09 15:23 UTC, gterzian commented
I changed the title because I think this indeed implements the "opener" link type, since that is a result of checking for the presence of `opener` on a `_blank` link. Any link with a named target other than `_blank` will also have an `opener`(since the logic only sets `noopener` to `true` when the `opener` keyword is absent, **and it is a `_blank` target**...

2019-02-12 16:31 UTC, CYBAI commented
@bors-servo try=wpt

- The tests has been merged at #22867. Let's try it!

2019-02-12 16:31 UTC, bors-servo commented
:hourglass: Trying commit 151e035da29eb9060c9441221ad2afdb42786caf with merge 75c3568269c0ee79fab8c126b25a72a364c40471...

2019-02-12 16:57 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11601), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11657), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/eHt9Xh_AR4-pDsIkrggFeQ)
State: approved= try=True

2019-02-12 17:44 UTC, CYBAI commented
Hmm, @georgeroman, could you rebase to latest master and let's try again? thanks.

2019-02-12 17:51 UTC, jdm commented
Rebasing does not make a difference; try runs are merged with master, so the results reflect the most up to date code changes.

2019-03-07 16:27 UTC, pradyunsg commented
Is this good to go?

2019-03-07 16:57 UTC, jdm commented
I think we still would like to figure out why the tests aren't showing any different results.

2019-03-08 07:38 UTC, gterzian commented
The test that should go from `FAIL` to `PASS` is at https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/html/semantics/links/links-created-by-a-and-area-elements/target_blank_implicit_noopener.html, and can be run with `./mach test-wpt /html/semantics/links/links-created-by-a-and-area-elements/target_blank_implicit_noopener.html`. 

The test expectation, that should be update if we get the test to pass, is at https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/semantics/links/links-created-by-a-and-area-elements/target_blank_implicit_noopener.html.ini

2019-03-09 13:42 UTC, georgeroman commented
I ran the tests and they all fail with the message: `BroadcastChannel is not defined`.

2019-03-09 21:48 UTC, jdm commented
@bors-servo r=cybai,jdm
Thanks for checking!

2019-03-09 21:48 UTC, bors-servo commented
:pushpin: Commit 74d6af9 has been approved by `cybai,jdm`

<!-- @bors-servo r=cybai,jdm 74d6af94f6f4e79ea0089da38e89a1d5a83179ab -->

2019-03-09 21:49 UTC, bors-servo commented
:hourglass: Testing commit 74d6af94f6f4e79ea0089da38e89a1d5a83179ab with merge 169b8cf144e352b393fc84d3a1b547c3ae990cba...

2019-03-09 22:58 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/1185), [arm32](http://build.servo.org/builders/arm32/builds/14061), [arm64](http://build.servo.org/builders/arm64/builds/14089), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11729), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11785), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6667), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6635), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/10877), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/10941), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6691), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6622), [magicleap](http://build.servo.org/builders/magicleap/builds/804), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/GNCbjMuRSjSFvU-IQeLZ6g)
Approved by: cybai,jdm
Pushing 169b8cf144e352b393fc84d3a1b547c3ae990cba to master...

2019-03-09 22:58 UTC, merged