implement historical srcElement attribute for Event interface
servo/servo pull request #22918
Opened 2019-02-21 00:20 UTC by drexler

Implementation of `srcElement` attribute for Event interface. Reference: https://dom.spec.whatwg.org/#dom-event-srcelement

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22880 (GitHub issue number if applicable)

- [X] There are tests for these changes

2019-02-21 00:20 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @manishearth (or someone else) soon.

2019-02-21 00:20 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/event.rs, components/script/dom/webidls/Event.webidl
 * @kichjang: components/script/dom/event.rs, components/script/dom/webidls/Event.webidl

2019-02-21 00:20 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-02-21 02:00 UTC, jdm requested changes

2019-02-21 02:00 UTC, jdm commented on components/script/dom/event.rs
> +    src_element: MutNullableDom<EventTarget>,
No need to add a new member for this.

2019-02-25 06:38 UTC, Manishearth commented
@bors-servo r+

2019-02-25 06:38 UTC, bors-servo commented
:pushpin: Commit dd731aa has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth dd731aa519d7102f683d5eee9133fc988cc8559f -->

2019-02-25 06:38 UTC, bors-servo commented
:hourglass: Testing commit dd731aa519d7102f683d5eee9133fc988cc8559f with merge e88f9a5cc681fe9154e8b272c9d45495db050aad...

2019-02-25 06:39 UTC, Manishearth commented
Thanks!

2019-02-25 06:59 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11642)

2019-02-25 08:23 UTC, CYBAI commented
Need to update these test expectations!

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: attribute srcElement", 
    "test": "/dom/interfaces.html?exclude=Node", 
    "line": 89302, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: document.createEvent(\"Event\") must inherit property \"srcElement\" with the proper type", 
    "test": "/dom/interfaces.html?exclude=Node", 
    "line": 89329, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: new Event(\"foo\") must inherit property \"srcElement\" with the proper type", 
    "test": "/dom/interfaces.html?exclude=Node", 
    "line": 89354, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: new CustomEvent(\"foo\") must inherit property \"srcElement\" with the proper type", 
    "test": "/dom/interfaces.html?exclude=Node", 
    "line": 89390, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

2019-02-25 12:21 UTC, drexler commented
@Manishearth  updated the test expectations for this PR. Sorry for multiple commits - still getting to grips with my first PR into Servo.

2019-02-25 12:21 UTC, Manishearth commented
@bors-servo r+

2019-02-25 12:21 UTC, bors-servo commented
:pushpin: Commit 96bff3c has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth 96bff3cd55782395d59cd2c88174b8a3e480ffec -->

2019-02-25 12:21 UTC, bors-servo commented
:hourglass: Testing commit 96bff3cd55782395d59cd2c88174b8a3e480ffec with merge 5be88c7db16a79d7ab4fe85942ac61d156dd6202...

2019-02-25 12:51 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11702)

2019-02-25 12:59 UTC, Manishearth commented
More tests, sorry:

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Default prevention via preventDefault", 
    "test": "/dom/events/Event-defaultPrevented-after-dispatch.html", 
    "line": 72290, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Click event can be dispatched to an element that is not in the document.", 
    "test": "/dom/events/Event-dispatch-detached-click.html", 
    "line": 129020, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "calls `handleEvent` method of `EventListener`", 
    "test": "/dom/events/EventListener-handleEvent.html", 
    "line": 138791, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Custom event on an element in another document", 
    "test": "/dom/events/Event-dispatch-other-document.html", 
    "line": 143480, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

Also, please try and [squash the commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) if you're able to :)

2019-02-27 10:33 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #22917) made this pull request unmergeable. Please resolve the merge conflicts.

2019-02-27 15:41 UTC, drexler commented
@Manishearth rebased this patch updated the tests.

2019-02-27 16:15 UTC, jdm requested changes
Very close!

2019-02-27 16:15 UTC, jdm commented on tests/wpt/metadata/dom/interfaces.html.ini
>      expected: FAIL
These lines need to be removed, since they were removed in #22917.

2019-02-27 16:15 UTC, jdm commented on tests/wpt/metadata/dom/events/Event-dispatch-other-document.html.ini
>  [Event-dispatch-other-document.html]
The files with no more expected failures can be removed.

2019-03-07 15:45 UTC, drexler commented
@jdm  mind taking a look at this? Thanks.

2019-03-07 16:43 UTC, jdm commented
@bors-servo r+
Thanks for the reminder!

2019-03-07 16:43 UTC, bors-servo commented
:pushpin: Commit fff8a09 has been approved by `jdm`

<!-- @bors-servo r=jdm fff8a09ffdffd0d2b8a146628802251f3e795d10 -->

2019-03-07 16:43 UTC, bors-servo commented
:hourglass: Testing commit fff8a09ffdffd0d2b8a146628802251f3e795d10 with merge d364b28428b083cb30c0ca2294319d68530ecb5d...

2019-03-07 17:03 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11720)

2019-03-07 17:30 UTC, jdm commented
@bors-servo retry
* #13480

2019-03-07 17:30 UTC, bors-servo commented
:hourglass: Testing commit fff8a09ffdffd0d2b8a146628802251f3e795d10 with merge ee00aa006d1449f630be18649eb70e3629bdac83...

2019-03-07 17:54 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/11777)

2019-03-07 18:35 UTC, jdm commented
Need to update some more test results:
```

  ▶ Unexpected subtest result in /dom/events/Event-initEvent.html:
  └ PASS [expected FAIL] Properties of initEvent(type, true, true)

  ▶ Unexpected subtest result in /dom/events/Event-initEvent.html:
  └ PASS [expected FAIL] Properties of initEvent(type, true, false)

  ▶ Unexpected subtest result in /dom/events/Event-initEvent.html:
  └ PASS [expected FAIL] Properties of initEvent(type, false, true)

  ▶ Unexpected subtest result in /dom/events/Event-initEvent.html:
  └ PASS [expected FAIL] Properties of initEvent(type, false, false)
```

2019-03-07 19:03 UTC, drexler commented
@jdm is there a command i can run locally to discover these failing tests?

2019-03-07 19:27 UTC, jdm commented
@drexler I suggested that in my original issue comment in https://github.com/servo/servo/issues/22880#issue-410032816 :)

2019-05-02 21:06 UTC, jdm commented
@bors-servo r-

2019-05-27 17:42 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23465) made this pull request unmergeable. Please resolve the merge conflicts.

2019-06-24 15:10 UTC, jdm commented
@drexler Are you planning to finish updating the test results?

2019-06-24 15:28 UTC, drexler commented
@jdm ooops...totally slipped off my radar. I'll tackle it tonight and update the PR.

2019-09-04 17:14 UTC, jdm commented
Closing due to inactivity.

2019-09-04 17:14 UTC, closed without merging