Implement DocumentFragment XML serialization.
servo/servo pull request #23192
Opened 2019-04-11 18:10 UTC by jackxbritton

When serializing a DocumentFragment node, we should follow [this guy](https://w3c.github.io/DOM-Parsing/#dfn-xml-serializing-a-documentfragment-node) and serialize the node's immediate children. This commit makes that change.

---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes fix #23134 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because ___ well, they probably do, but I don't know how to do that and could use some help.

2019-04-11 18:10 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @ferjm (or someone else) soon.

2019-04-11 18:10 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/servoparser/html.rs
 * @kichjang: components/script/dom/servoparser/html.rs

2019-04-11 18:10 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-04-11 18:14 UTC, KiChjang commented
@bors-servo try=wpt

2019-04-11 18:14 UTC, bors-servo commented
:hourglass: Trying commit 2100cc20a63b281b66f1bd84d1ffa4486e0aaaf5 with merge edc598cbbbc71d7b5cf5b0d5bc5fcc6ad6b99ce0...

2019-04-11 18:43 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11950), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12009), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/LFpUSR0rS0SgYgaIS5zyHA)
State: approved= try=True

2019-04-11 18:48 UTC, jdm commented
I recommend following the example of #23153 and adding a test to tests/wpt/web-platform-tests/domparsing/XMLSerializer-serializeToString.html. You can run those tests with `./mach test-wpt tests/wpt/web-platform-tests/domparsing/XMLSerializer-serializeToString.html`.

2019-04-11 18:48 UTC, jdm commented
@bors-servo try=wpt

2019-04-12 15:58 UTC, jackxbritton commented
Cool, I'll get to it

2019-04-12 16:08 UTC, servo-wpt-sync commented
Opened new PR for upstreamable changes.

Completed upstream sync of web-platform-test changes at https://github.com/web-platform-tests/wpt/pull/16333.

2019-04-12 16:14 UTC, jdm requested changes
This looks great! One small change and then it's ready to merge :) Please squash the commits into one, as well.

2019-04-12 16:14 UTC, jdm commented on components/script/dom/servoparser/html.rs
> +        if skip_first || node.type_id() == NodeTypeId::DocumentFragment {
Let's use `node.is::<DocumentFragment>()` instead for clarity.

2019-04-12 16:15 UTC, jdm commented
You will need to run `./mach update-manifest` as well.

2019-04-12 16:51 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#16333.

2019-04-12 17:34 UTC, jdm commented
@bors-servo r+
Thanks!

2019-04-12 17:34 UTC, bors-servo commented
:pushpin: Commit 1dd1cb4 has been approved by `jdm`

<!-- @bors-servo r=jdm 1dd1cb4f4fc17d713cddff251b52221241c2b521 -->

2019-04-12 18:37 UTC, bors-servo commented
:hourglass: Testing commit 1dd1cb4f4fc17d713cddff251b52221241c2b521 with merge 9832feddf3b6111dbf648ab758faa312ab30fd07...

2019-04-12 20:09 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/1387), [arm32](http://build.servo.org/builders/arm32/builds/14265), [arm64](http://build.servo.org/builders/arm64/builds/14293), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/11964), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12023), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6880), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6839), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/11077), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/11143), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6894), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6821), [magicleap](http://build.servo.org/builders/magicleap/builds/1006), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/LqBGmcN7ROSAFc3gcrjaWw)
Approved by: jdm
Pushing 9832feddf3b6111dbf648ab758faa312ab30fd07 to master...

2019-04-12 20:09 UTC, merged