Refactor promise compartment
servo/servo pull request #23253
Opened 2019-04-24 17:48 UTC by AZWN

This PR adds a mechanism to verify that certain code is executed inside a ```JSAutoCompartment```, and applies this to the ```Promise::new_in_current_compartment``` constructor.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23167 

- [x] These changes do not require tests because they do not change existing functionality.

2019-04-24 17:48 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/navigator.rs, components/script/dom/rtcpeerconnection.rs, components/script/dom/vrdisplay.rs, components/script/dom/customelementregistry.rs, components/script/dom/baseaudiocontext.rs and 22 more
 * @kichjang: components/script/dom/navigator.rs, components/script/dom/rtcpeerconnection.rs, components/script/dom/vrdisplay.rs, components/script/dom/customelementregistry.rs, components/script/dom/baseaudiocontext.rs and 22 more

2019-04-24 17:48 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2019-04-24 17:56 UTC, AZWN commented
I have one open question/issue. The available ```Promise``` constructors now look like this:

```
impl Promise {
    pub fn new(global: &GlobalScope, comp: &InCompartment) -> Rc<Promise> {
        Promise::new_in_current_compartment(global, comp)
    }

    #[allow(unsafe_code)]
    pub fn new_in_current_compartment(global: &GlobalScope, _comp: &InCompartment) -> Rc<Promise> {
        // ...
    }
    // ...
```

To, me, having both ```Promise::new``` and ```Promise::new_in_current_compartment``` looks a bit redundant, since the first is just delegating to the second. Would it be better to remove ```Promise::new_in_current_compartment```?

2019-04-24 18:34 UTC, jdm commented
Promise::new should not accept an InCompartment argument. Instead it should enter the compartment for `global` before calling new_in_current_compartment.

2019-04-24 18:54 UTC, AZWN commented
Ok, so If I understand you well, it should use ```InCompartment::Entered``` like his:
impl Promise {
    pub fn new(global: &GlobalScope) -> Rc<Promise> {
        let comp = JSAutoCompartment::with_obj(&global.get_cx(), &global);
        Promise::new_in_current_compartment(global, &InCompartment::Entered(&comp))
    }

    #[allow(unsafe_code)]
    pub fn new_in_current_compartment(global: &GlobalScope, _comp: &InCompartment) -> Rc<Promise> {
        // ...
    }
    // ...
}
```?

2019-04-24 19:12 UTC, jdm commented
That's the idea! I think we can pass `InCompartment` by value, rather than by reference, however.

2019-04-24 19:42 UTC, AZWN commented
Ok, give me a moment, and I will implement it. 

I am not sure about the fact ```InCompartment``` should be passed by value though. The advantage of references in my opinion is that it is possible to reuse ```InCompartment``` values for multiple calls. For now, that is not that relevant yet, but if you are planning to extend this pattern to more use cases it might become an advantage.

2019-04-24 19:54 UTC, jdm commented
If you add `#[derive(Copy, Clone)]` to the InCompartment struct definition, it should be possible to reuse them.

2019-04-24 20:38 UTC, jdm commented
Fantastic! I can already see places where we can improve our safety guarantees based on these changes. Thanks for doing this work!
@bors-servo r+

2019-04-24 20:38 UTC, bors-servo commented
:pushpin: Commit eb73cce has been approved by `jdm`

<!-- @bors-servo r=jdm eb73ccee150ef7330fa4e5805f3851e2f224a90e -->

2019-04-24 21:11 UTC, bors-servo commented
:hourglass: Testing commit eb73ccee150ef7330fa4e5805f3851e2f224a90e with merge 486f235013586b237867e73e3454493a88b67b5c...

2019-04-24 21:16 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12105)

2019-04-24 21:33 UTC, jdm commented
```
error[E0308]: mismatched types
  --> components/script/body.rs:57:9
   |
57 |         &InCompartment::Already(&in_compartment_proof),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |         |
   |         expected enum `compartments::InCompartment`, found reference
   |         help: consider removing the borrow: `InCompartment::Already(&in_compartment_proof)`
   |
   = note: expected type `compartments::InCompartment<'_>`
              found type `&compartments::InCompartment<'_>`

error[E0599]: no function or associated item named `with_obj` found for type `js::jsapi::JSAutoCompartment` in the current scope
  --> components/script/dom/promise.rs:84:39
   |
84 |         let comp = JSAutoCompartment::with_obj(&global.get_cx(), &global);
   |                                       ^^^^^^^^ function or associated item not found in `js::jsapi::JSAutoCompartment`

error: aborting due to 2 previous errors
```

2019-04-25 17:27 UTC, jdm requested changes

2019-04-25 17:27 UTC, jdm commented on components/script/dom/promise.rs
> +        let comp = AlreadyInCompartment::assert(&global);
We want to always enter a compartment, not panic if we have not entered one. We need to use `let compartment = JSAutoCompartment::new(cx, global.reflector().get_jsobject().get());` here.

2019-04-29 14:45 UTC, jdm commented
@bors-servo r+

2019-04-29 14:45 UTC, bors-servo commented
:pushpin: Commit 3229af5 has been approved by `jdm`

<!-- @bors-servo r=jdm 3229af509f9931f85a1372323f90427d2ad5898d -->

2019-04-29 17:59 UTC, bors-servo commented
:hourglass: Testing commit 3229af509f9931f85a1372323f90427d2ad5898d with merge 852223b08a007e348d0c8e64b9eeed6ab0432b4f...

2019-04-29 19:37 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/1486), [arm32](http://build.servo.org/builders/arm32/builds/14365), [arm64](http://build.servo.org/builders/arm64/builds/14393), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/12083), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12142), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/6981), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/6939), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/11176), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/11243), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/6995), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6919), [magicleap](http://build.servo.org/builders/magicleap/builds/1104), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/WuCB709ASBG1-aUK3EojTA)
Approved by: jdm
Pushing 852223b08a007e348d0c8e64b9eeed6ab0432b4f to master...

2019-04-29 19:37 UTC, merged