Create performance resource timing entry for synchronous network fetch
servo/servo pull request #23322
Opened 2019-05-04 15:11 UTC by pylbrecht

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #23150 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-05-04 15:12 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @jdm (or someone else) soon.

2019-05-04 15:12 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/network_listener.rs
 * @kichjang: components/script/network_listener.rs

2019-05-04 15:12 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-05-04 15:19 UTC, pylbrecht commented
@jdm, regarding your idea of passing a function pointer to `load_whole_resource()`:
I'm not sure from where to get the required arguments for `submit_timing_data()` inside `load_whole_resource()`.

Should we just pass more arguments to `load_whole_resource()`?
I see `GlobalScope` and `ServoUrl` floating around in the code calling `load_whole_resource()`, but what about `InitiatorType`?

2019-05-06 15:09 UTC, jdm requested changes
Yes, passing more arguments to load_whole_resource is a fine choice. As for InitiatorType, the only callers of load_whole_resource fall into the Other category so we might as well hardcode that. I would expect us to remove these callers over time; the synchronous resource loading API isn't great for slow connections.

2019-05-06 15:09 UTC, jdm commented on components/script/network_listener.rs
> +    global: &DomRoot<GlobalScope>,
This can be `&GlobalScope`.

2019-05-06 18:18 UTC, pylbrecht commented
```
~jdm | pylbrecht: although we may nave a better solution
~jdm | pylbrecht: all of the callers of load_whole_resource live in script/
~jdm | we could just move load_whole_resource to script and make it call submit_timing_data itself              
~jdm | that's going to be more clear and require rebuilding fewer crates in the future
~jdm | load_whole_resource used to be used by lots of other code, but we're slowly getting rid of it            
```

2019-05-07 19:07 UTC, jdm approved these changes

2019-05-10 13:51 UTC, jdm commented
@bors-servo r+

2019-05-10 13:51 UTC, bors-servo commented
:pushpin: Commit e5217ee has been approved by `jdm`

<!-- @bors-servo r=jdm e5217eed0e75dea178c8d201c212470ea9a4eda5 -->

2019-05-10 14:11 UTC, bors-servo commented
:hourglass: Testing commit e5217eed0e75dea178c8d201c212470ea9a4eda5 with merge 623c5d064505003da83becc557605f3fcf5406b6...

2019-05-10 16:22 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/1604), [arm32](http://build.servo.org/builders/arm32/builds/14478), [arm64](http://build.servo.org/builders/arm64/builds/14506), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/12199), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12257), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/7088), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/7050), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/11280), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/11350), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/7102), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/7021), [magicleap](http://build.servo.org/builders/magicleap/builds/1201), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/fcBwqWoaSr6pNR1Ymnxihw)
Approved by: jdm
Pushing 623c5d064505003da83becc557605f3fcf5406b6 to master...

2019-05-10 16:22 UTC, merged