Changes for Ubuntu/Ubuntu 19.04 in bootstrap.py
servo/servo pull request #23324
Opened 2019-05-05 19:13 UTC by marcinwiacek

Update handling Ubuntu distributions:

1. script correctly returns error when some version is/was not supported (checked with Ubuntu 19.04)
2. for Ubuntu 19.04 Disco Dingo there are correct packages installed

Note: this is my commit to this project, please forgive any mistakes.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's updating bootstrap.py script

2019-05-05 19:13 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @nox (or someone else) soon.

2019-05-05 19:13 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/bootstrap.py

2019-05-06 15:18 UTC, jdm requested changes

2019-05-06 15:18 UTC, jdm commented on python/servo/bootstrap.py
> +        if context.distro_version == "17.04" or context.distro_version == "19.04":
Let's do `if context.distro_version in ["17.04", "19.04"]:`

2019-05-06 15:18 UTC, jdm commented on python/servo/bootstrap.py
> +            raise Exception('unsupported version of %s: %s' % (distro, version))
I believe we want to keep supporting earlier versions of Ubuntu. Can we revert this?

2019-05-06 19:03 UTC, jdm commented
@bors-servo r+
Thanks!

2019-05-06 19:03 UTC, bors-servo commented
:pushpin: Commit fcbba1d has been approved by `jdm`

<!-- @bors-servo r=jdm fcbba1df6dba1f6d3fd4b250a398ee17b23c29d7 -->

2019-05-06 19:09 UTC, bors-servo commented
:hourglass: Testing commit fcbba1df6dba1f6d3fd4b250a398ee17b23c29d7 with merge 26686db3647661eb2fb33cd9e59b71a7ab0724ed...

2019-05-06 19:30 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/7038)

2019-05-06 19:52 UTC, jdm commented
@bors-servo retry

2019-05-07 22:34 UTC, marcinwiacek commented
hmmm, trybot fail seems to be not related. What next?

2019-05-07 22:34 UTC, marcinwiacek commented
@bors-servo retry

2019-05-07 22:34 UTC, bors-servo commented
@marcinwiacek: :key: Insufficient privileges: not in try users

2019-05-07 23:26 UTC, jdm commented
@bors-servo retry

2019-05-07 23:27 UTC, jdm commented
Oh, we've just had problems with our CI queue for the past 24 hours. It'll get there eventually: https://build.servo.org/homu/queue/servo

2019-05-08 15:28 UTC, bors-servo commented
:hourglass: Testing commit fcbba1df6dba1f6d3fd4b250a398ee17b23c29d7 with merge 7f389f3eab4660587830ea81bffb85e404b06acf...

2019-05-08 16:17 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/Deiyxd50Si-CkZAdJPmbkA)

2019-05-08 16:28 UTC, jdm commented
@bors-servo retry

2019-05-08 16:51 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2019-05-08 16:51 UTC, bors-servo commented
:hourglass: Testing commit fcbba1df6dba1f6d3fd4b250a398ee17b23c29d7 with merge 5dbf7cfd6928e118571f2fd5dd509adb7dc2bcab...

2019-05-08 20:04 UTC, bors-servo commented
:broken_heart: Test failed - [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/7073/steps/test/logs/interrupt)

2019-05-08 20:05 UTC, jdm commented
@bors-servo retry

2019-05-08 21:38 UTC, bors-servo commented
:hourglass: Testing commit fcbba1df6dba1f6d3fd4b250a398ee17b23c29d7 with merge f821fc653388c0e865fb979ba7d0d8c4d52c0eb6...

2019-05-08 22:58 UTC, bors-servo commented
:sunny: Test successful - [android-mac](http://build.servo.org/builders/android-mac/builds/1566), [arm32](http://build.servo.org/builders/arm32/builds/14449), [arm64](http://build.servo.org/builders/arm64/builds/14477), [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/12169), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12227), [mac-rel-css1](http://build.servo.org/builders/mac-rel-css1/builds/7059), [mac-rel-css2](http://build.servo.org/builders/mac-rel-css2/builds/7020), [mac-rel-wpt1](http://build.servo.org/builders/mac-rel-wpt1/builds/11253), [mac-rel-wpt2](http://build.servo.org/builders/mac-rel-wpt2/builds/11321), [mac-rel-wpt3](http://build.servo.org/builders/mac-rel-wpt3/builds/7075), [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/6994), [magicleap](http://build.servo.org/builders/magicleap/builds/1178), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/Rkn-1PLrRYmt1ysRHb6tQw)
Approved by: jdm
Pushing f821fc653388c0e865fb979ba7d0d8c4d52c0eb6 to master...

2019-05-08 22:59 UTC, merged