Enter dom compartment wrapper
servo/servo pull request #23344
Opened 2019-05-08 07:00 UTC by KaczuH

I'm still not sure if the changes are entirely correct.
Replaced occurrences:
 `JSAutoCompartment::new(global.get_cx(), global.reflector().get_jsobject().get());` with `fn enter_compartment(object: &DomObject) -> JSAutoCompartment`

There are still occurrences of `JSAutoCompartment` that i was unable to replace. Could anyone give me a hint if it is possible?
```
→ rg -Fi --type rust "JSAutoCompartment::"
components/script/compartments.rs
38:    JSAutoCompartment::new(

components/script/dom/create.rs
159:                                let _ac = JSAutoCompartment::new(

components/script/dom/eventtarget.rs
527:                let _ac = JSAutoCompartment::new(cx, self.reflector().get_jsobject().get());

components/script/dom/windowproxy.rs
223:            let _ac = JSAutoCompartment::new(cx, window_jsobject.get());

components/script/dom/customelementregistry.rs
337:            let _ac = JSAutoCompartment::new(cx, proto_object.get());
349:            let _ac = JSAutoCompartment::new(cx, constructor.get());
538:            let _ac = JSAutoCompartment::new(cx, self.constructor.callback());
668:        let _ac = JSAutoCompartment::new(cx, constructor.callback());

components/script/dom/window.rs
2216:            let _ac = JSAutoCompartment::new(cx, obj.get());

components/script/dom/paintworkletglobalscope.rs
254:        let _ac = JSAutoCompartment::new(cx, self.worklet_global.reflector().get_jsobject().get());

components/script/dom/globalscope.rs
544:                let _ac = JSAutoCompartment::new(cx, globalhandle.get());

components/script/dom/websocket.rs
573:            let _ac = JSAutoCompartment::new(cx, ws.reflector().get_jsobject().get());

components/script/dom/workerglobalscope.rs
397:                        let _ac = JSAutoCompartment::new(

components/script/dom/promise.rs
144:        let _ac = JSAutoCompartment::new(cx, global.reflector().get_jsobject().get());
156:        let _ac = JSAutoCompartment::new(cx, global.reflector().get_jsobject().get());

components/script/dom/bindings/htmlconstructor.rs
118:        let _ac = JSAutoCompartment::new(window.get_cx(), callee.get());

components/script/dom/bindings/utils.rs
411:    let _ac = JSAutoCompartment::new(cx, obj.get());

components/script/dom/bindings/callback.rs
276:                let _ac = JSAutoCompartment::new(

components/script/dom/bindings/interface.rs
163:    let _ac = JSAutoCompartment::new(cx, rval.get());
```

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix  #23266

- [X] These changes do not require tests because no logic was changed only some code extracted to wrapper function

2019-05-11 05:51 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23163) made this pull request unmergeable. Please resolve the merge conflicts.

2019-05-18 10:13 UTC, KaczuH commented
Rebase done.

2019-05-19 14:32 UTC, jdm commented
I will review this on Tuesday. Sorry for the delay!

2019-05-23 14:04 UTC, jdm requested changes

2019-05-23 14:04 UTC, jdm commented on components/script/dom/eventtarget.rs
> +        let _ac = enter_realm(&*document);
Let's keep using `window` here instead of `document`.

2019-05-23 14:04 UTC, jdm commented on components/script/dom/windowproxy.rs
> +            let _ac = enter_realm(window);
Let's revert the changes in this file. We already have the cx and JSObject values, so calling this method to reacquire them is redundant.

2019-06-02 21:36 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23459) made this pull request unmergeable. Please resolve the merge conflicts.

2019-06-24 14:54 UTC, jdm commented
@KaczuH Are you planning to finish this work?

2019-06-29 16:43 UTC, KaczuH commented
All changes are now applied, sorry for long wait

2019-06-29 17:03 UTC, jdm commented
Looks good! Could you squash the commits together into one?

2019-06-29 17:24 UTC, KaczuH commented
@jdm squash done :)

2019-06-29 17:55 UTC, jdm commented
@bors-servo r+
Thanks!

2019-06-29 17:55 UTC, bors-servo commented
:pushpin: Commit adb4024 has been approved by `jdm`

<!-- @bors-servo r=jdm adb402487e7f8bf2cd0a1db360b16592f5c654ed -->

2019-06-29 17:55 UTC, bors-servo commented
:hourglass: Testing commit adb402487e7f8bf2cd0a1db360b16592f5c654ed with merge 23c49bbbea2299c56d71b0615173ec92a8c35d36...

2019-06-29 20:29 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/12661), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12722), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/fQXcE-AaS7GN-ngx-eJO9w)
Approved by: jdm
Pushing 23c49bbbea2299c56d71b0615173ec92a8c35d36 to master...

2019-06-29 20:29 UTC, merged