[WIP] Pass GL application parameters down to media player
servo/servo pull request #23483
Opened 2019-05-30 14:38 UTC by ceyusa

These patches aim to pass the application's OpenGL raw context  and the its native display address to the media player, in order to create an internal wrapped context, thus it will generate video frames as textures.

For now only EGL from glutin-based app and android are in place, though tested only in Linux glutin app.

2019-05-30 14:38 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/pipeline.rs, components/constellation/constellation.rs, components/script/dom/htmlmediaelement.rs, components/script/script_thread.rs, components/script/dom/window.rs
 * @cbrewster: components/constellation/pipeline.rs, components/constellation/constellation.rs
 * @paulrouget: components/constellation/pipeline.rs, ports/glutin/context.rs, components/compositing/Cargo.toml, ports/glutin/headless_window.rs, components/constellation/constellation.rs and 4 more
 * @kichjang: components/script/dom/htmlmediaelement.rs, components/script/script_thread.rs, components/script/dom/window.rs, components/script_traits/Cargo.toml, components/script_traits/lib.rs

2019-05-30 14:39 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-05-31 04:48 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23485) made this pull request unmergeable. Please resolve the merge conflicts.

2019-06-04 22:55 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23506) made this pull request unmergeable. Please resolve the merge conflicts.

2019-06-05 15:33 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23517) made this pull request unmergeable. Please resolve the merge conflicts.

2019-06-05 15:37 UTC, jdm commented
Is this waiting for review right now?

2019-06-07 07:43 UTC, ceyusa commented
> Is this waiting for review right now?

Is still a working progress :( 

It would be great a glance to check if the sketched ideas make senss.

2019-06-09 20:42 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23154) made this pull request unmergeable. Please resolve the merge conflicts.

2019-06-12 00:04 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23468) made this pull request unmergeable. Please resolve the merge conflicts.

2019-06-16 16:09 UTC, ceyusa commented
Ready for review :)

2019-06-22 15:38 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23600) made this pull request unmergeable. Please resolve the merge conflicts.

2019-06-24 18:56 UTC, jdm requested changes
Exciting! This looks like a sensible implementation.

2019-06-24 18:56 UTC, jdm commented on components/script/dom/htmlmediaelement.rs
> +    id: u64,
Let's use an Option and a more descriptive name. player_id?

2019-06-24 18:56 UTC, jdm commented on components/script/dom/htmlmediaelement.rs
> +                    txn.add_image(
Let's merge these blocks:
```rust
let image_data = if let Some(id) = self.player_id {
   ImageData::External(...)
} else {
   ImageData::Raw(frame.get_data())
};
txn.add_image(new_image_key, descriptor, image_data, None);
```

2019-06-24 18:56 UTC, jdm commented on components/script/dom/htmlmediaelement.rs
> +                } else if self.id != 0 {
Some comments as previous case - let's merge these blocks.

2019-06-24 18:59 UTC, jdm commented on ports/glutin/headless_window.rs
> +    fn get_gl_context(&self) -> MediaPlayerCtxt::GlContext {
The point of this comment is to spur conversation - it feels like something we _should_ test if possible; how much work is it to support OSMesa for the GL video rendering integration?

2019-06-25 19:01 UTC, jdm commented
Are the webrender external image changes ready for review? I saw some comments that suggested that some more work is expected.

2019-06-25 20:23 UTC, ferjm commented
Not ready for review yet. I need to add a few more changes.

El mar., 25 jun. 2019 21:01, Josh Matthews <notifications@github.com>
escribió:

> Are the webrender external image changes ready for review? I saw some
> comments that suggested that some more work is expected.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/servo/servo/pull/23483?email_source=notifications&email_token=AADVHSVS6IHP7R5IL5UHEKDP4JTQ3A5CNFSM4HRFVU42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYRIICI#issuecomment-505578505>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADVHSTUAH7EG2DR6V26OWDP4JTQ3ANCNFSM4HRFVU4Q>
> .
>

2019-06-26 22:53 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23636) made this pull request unmergeable. Please resolve the merge conflicts.

2019-07-01 14:25 UTC, ferjm commented on components/script/dom/window.rs
> +    #[ignore_malloc_size_of = "defined in script_thread"]
`WindowGLContext` has `GlContext`, `GlApi` and `NativeDisplay` members that are defined in servo-media. The 4th member is a `GLPlayerPipeline`, which is the only one defined in Servo, but it is basically an `IpcSender` or a `mpsc::Sender`, also defined outside of Servo.

2019-07-01 14:48 UTC, ferjm commented
@bors-servo try=wpt

2019-07-01 14:49 UTC, bors-servo commented
:hourglass: Trying commit 1b25a9ec10ee5c327a9d8283d32ec6a07002f75c with merge d1636eebc2fc145b01f88a9397bdc31c4fefebb5...

2019-07-01 14:49 UTC, ferjm commented
r? @jdm

2019-07-01 15:14 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/12672)

2019-07-01 16:07 UTC, ceyusa commented on components/webrender_traits/lib.rs
> +                uv: webrender_api::TexelRect::new(0.0, 0.0, size.width as f32, size.height as f32),
Sadly, textures from media and textures from WebGL don't have the same coordinates in texel space:

webgl: 0.0, size.height as f32, size.width as f32, 0.0

media (as gstreamer): 0.0, 0.0, size.width as f32, size.height as f32

2019-07-01 23:46 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23575) made this pull request unmergeable. Please resolve the merge conflicts.

2019-07-02 11:20 UTC, ferjm commented
@bors-servo try=wpt

2019-07-02 11:20 UTC, bors-servo commented
:hourglass: Trying commit 7b597ca07ab7abb0ac1d32d193bb096808641266 with merge 020433d821ba249b67fbfc88a039e80825f54cd6...

2019-07-02 12:08 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12747)

2019-07-02 13:29 UTC, ferjm commented
@bors-servo try=wpt

2019-07-02 13:29 UTC, bors-servo commented
:hourglass: Trying commit 216e1e500d191df7baf124c2015651d6a1f28ac3 with merge 86a8a392767a575d06efb37e912cfea3095cf296...

2019-07-02 13:45 UTC, ceyusa commented on ports/glutin/headless_window.rs
> +    fn get_gl_context(&self) -> MediaPlayerCtxt::GlContext {
I have never tried GstGL on OSMesa. So far I have no idea.

2019-07-02 14:19 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/12687), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12749), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/CNhiyeyKQ5u0lzwsS7hCPg)
State: approved= try=True

2019-07-03 15:48 UTC, jdm approved these changes
Looks good!

2019-07-03 15:48 UTC, jdm commented on components/media/lib.rs
> +#![crate_type = "rlib"]
These crate attributes shouldn't be necessary.

2019-07-03 15:48 UTC, jdm commented on components/webrender_traits/lib.rs
> +#![crate_type = "rlib"]
These crate attributes shouldn't be necessary.

2019-07-03 15:48 UTC, jdm commented on components/webrender_traits/lib.rs
> +        if let Some(handler_type) = self.external_images.get(&key) {
Let's use `expect` here instead.

2019-07-03 15:48 UTC, jdm commented on components/webrender_traits/lib.rs
> +        if let Some(handler_type) = self.external_images.get(&key) {
Let's use `expect` here instead.

2019-07-03 19:22 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23690) made this pull request unmergeable. Please resolve the merge conflicts.

2019-07-04 08:45 UTC, ferjm commented
@bors-servo r=jdm

2019-07-04 08:45 UTC, bors-servo commented
:pushpin: Commit 208473c has been approved by `jdm`

<!-- @bors-servo r=jdm 208473cdbce1e125338b461a3f0d55fb9d0bdd7c -->

2019-07-04 09:51 UTC, bors-servo commented
:hourglass: Testing commit 208473cdbce1e125338b461a3f0d55fb9d0bdd7c with merge 4a5c30257315cafc4bfe6ac71ad88f79197567a2...

2019-07-04 12:18 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/YhJNs8LjRQa5xmo1bIKhrA)

2019-07-04 13:01 UTC, jdm commented
Building simpleservo:
```
[0m[1m[38;5;9merror[E0063][0m[0m[1m: missing fields `gl_context_pointer`, `native_display_pointer` in initializer of `simpleservo::InitOptions`[0m
[0m   [0m[0m[1m[38;5;12m--> [0m[0mports/libsimpleservo/capi/src/lib.rs:120:16[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m120[0m[0m [0m[0m[1m[38;5;12m| [0m[0m    let opts = InitOptions {[0m
[0m    [0m[0m[1m[38;5;12m| [0m[0m               [0m[0m[1m[38;5;9m^^^^^^^^^^^[0m[0m [0m[0m[1m[38;5;9mmissing `gl_context_pointer`, `native_display_pointer`[0m

[0m[1m[38;5;9merror[0m[0m[1m: aborting due to previous error[0m
```

Building windows:
```
error: unused import: `servo::gl::GlesFns`
  --> ports\libsimpleservo\api\src\gl_glue.rs:12:9
   |
12 |     use servo::gl::GlesFns;
   |         ^^^^^^^^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`

error: unused import: `std::ffi::CString`
  --> ports\libsimpleservo\api\src\gl_glue.rs:13:9
   |
13 |     use std::ffi::CString;
   |         ^^^^^^^^^^^^^^^^^

error: unused import: `std::os::raw::c_void`
  --> ports\libsimpleservo\api\src\gl_glue.rs:14:9
   |
14 |     use std::os::raw::c_void;
   |         ^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

error: Could not compile `simpleservo`.
```

Building magic leap:
```
error[E0599]: no method named `clone` found for type `simpleservo::gl_glue::egl::EGLInitResult` in the current scope
   --> ports/libmlservo/src/lib.rs:148:52
    |
148 |             MagicLeapVRService::new(name, ctxt, gl.clone()).expect("Failed to create VR service");
    |                                                    ^^^^^

error[E0063]: missing fields `gl_context_pointer`, `native_display_pointer` in initializer of `simpleservo::InitOptions`
   --> ports/libmlservo/src/lib.rs:153:16
    |
153 |     let opts = InitOptions {
    |                ^^^^^^^^^^^ missing `gl_context_pointer`, `native_display_pointer`

error[E0308]: mismatched types
   --> ports/libmlservo/src/lib.rs:175:29
    |
175 |     simpleservo::init(opts, gl, wakeup, callbacks).expect("error initializing Servo");
    |                             ^^ expected struct `std::rc::Rc`, found struct `simpleservo::gl_glue::egl::EGLInitResult`
    |
    = note: expected type `std::rc::Rc<(dyn gleam::gl::Gl + 'static)>`
               found type `simpleservo::gl_glue::egl::EGLInitResult`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0063, E0308, E0599.
For more information about an error, try `rustc --explain E0063`.
error: Could not compile `libmlservo`.
```

2019-07-04 14:48 UTC, ferjm commented
@bors-servo try=windows

2019-07-04 14:48 UTC, bors-servo commented
:hourglass: Trying commit f09661b36e7afa6ddaf8b3f4ecca3dd6ef4203e0 with merge 802efcdec3fb4d766a90beca4ecb74174f3295e6...

2019-07-04 15:43 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/at2bGcl1Tkag_CFRlmi2Eg)

2019-07-04 15:46 UTC, jdm commented
You can test the simpleservo changes locally using `./mach build -d --libsimpleservo`.

2019-07-04 15:54 UTC, ferjm commented
Yes, that worked on my laptop (OSX)

```
~/dev/mozilla/servo player-context*
❯ ./mach build -d --libsimpleservo
   Compiling simpleservo v0.0.1 (/Users/ferjm/dev/mozilla/servo/ports/libsimpleservo/api)
   Compiling simpleservo_capi v0.0.1 (/Users/ferjm/dev/mozilla/servo/ports/libsimpleservo/capi)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 41s
Build Completed in 0:02:41
```

2019-07-04 21:10 UTC, jdm commented
@bors-servo try=windows

2019-07-04 21:10 UTC, bors-servo commented
:hourglass: Trying commit 23e4812b41ffb5c1154b5dd4f7c5bb2285551198 with merge 784945798ea324d998ee7bcf3ebd89637d31da55...

2019-07-04 21:57 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/cAd7h_5USmGUKy1hN4-Fgg)

2019-07-04 22:07 UTC, jdm commented
@bors-servo r+

2019-07-04 22:07 UTC, bors-servo commented
:pushpin: Commit 5d30716 has been approved by `jdm`

<!-- @bors-servo r=jdm 5d307160b4be4abb4b986cdc63d6650ae2b32895 -->

2019-07-04 22:22 UTC, bors-servo commented
:hourglass: Testing commit 5d307160b4be4abb4b986cdc63d6650ae2b32895 with merge 320ec43f1b6794ac8c818db00412da8819b29117...

2019-07-05 00:11 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/V6VPJ46DSP2GKGeyX1yt-A)

2019-07-05 02:07 UTC, CYBAI commented
In `magicleap` build:

```
error[E0560]: struct `simpleservo::InitOptions` has no field named `gl_context_points`
   --> ports/libmlservo/src/lib.rs:160:9
    |
160 |         gl_context_points: Some(gl.gl_context),
    |         ^^^^^^^^^^^^^^^^^ help: a field with a similar name exists: `gl_context_pointer`

error[E0560]: struct `simpleservo::InitOptions` has no field named `display`
   --> ports/libmlservo/src/lib.rs:161:9
    |
161 |         display: Some(gl.display),
    |         ^^^^^^^ `simpleservo::InitOptions` does not have this field
    |
    = note: available fields are: `args`, `url`, `coordinates`, `density`, `vr_init` ... and 3 others

error: aborting due to 2 previous errors
```

2019-07-05 03:28 UTC, jdm commented
@bors-servo r+

2019-07-05 03:28 UTC, bors-servo commented
:pushpin: Commit 4fe1291 has been approved by `jdm`

<!-- @bors-servo r=jdm 4fe129109bbc40a32e491825d77a67fa8e5e9662 -->

2019-07-05 03:28 UTC, bors-servo commented
:hourglass: Testing commit 4fe129109bbc40a32e491825d77a67fa8e5e9662 with merge 0dc17af7f0dab01f673894b6ac7c84cb50d03603...

2019-07-05 05:30 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/12728), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12790), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/EOQQN2vgThG9RNDEBg74Wg)
Approved by: jdm
Pushing 0dc17af7f0dab01f673894b6ac7c84cb50d03603 to master...

2019-07-05 05:31 UTC, merged