Fix panic when running test-background-fetch-permission.html
servo/servo pull request #23654
Opened 2019-06-28 04:58 UTC by julientregoat

* Propagate `Error::JSFailed` in `Permissions::create_descriptor`
* In `Error::to_jsval`, only check if a JS exception is not pending if `self` is not `Error::JSFailed` 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23645 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's a test runner, so by nature if the test runs the test runner is also working as expected.

2019-06-28 04:58 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @emilio (or someone else) soon.

2019-06-28 04:58 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/bindings/error.rs, components/script/dom/permissions.rs
 * @kichjang: components/script/dom/bindings/error.rs, components/script/dom/permissions.rs

2019-06-28 04:58 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-06-28 14:16 UTC, jdm requested changes
This looks great! Please squash all the commits together into one commit, too.

2019-06-28 14:16 UTC, jdm commented on components/script/dom/permissions.rs
> +//    "Can't convert to an IDL value of type PermissionDescriptor";
Let's remove this instead of commenting it out.

2019-07-03 15:34 UTC, jdm commented
@bors-servo r+

2019-07-03 15:34 UTC, bors-servo commented
:pushpin: Commit d4bdaa5 has been approved by `jdm`

<!-- @bors-servo r=jdm d4bdaa5e16ff2f13f8f3c38cc1f234d0c2d539da -->

2019-07-03 16:28 UTC, bors-servo commented
:hourglass: Testing commit d4bdaa5e16ff2f13f8f3c38cc1f234d0c2d539da with merge 11569dc05b67c24958c3380d2b11a76cec109022...

2019-07-03 17:12 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12771)

2019-07-03 17:28 UTC, jdm commented
If you run the following:
```
wget https://build.servo.org/builders/linux-rel-wpt/builds/12771/steps/test__1/logs/test-wpt.log/text >/tmp/log
./mach update-wpt /tmp/log
git add tests/wpt/metadata/permissions
git commit --amend
``
And push the result, then we should be able to merge :)

2019-07-03 17:33 UTC, julientregoat commented
Okay, so trying to understand the failed tests / servo builder logs in general.  as I undertstand, `wpt` is the web platform tests - so that's just the error summary. What's `intermittents.log`?

I see 
```
Throws \"TypeError: \"this\" object does not implement interface Permissions.\" instead of rejecting promise Reached unreachable code", 
```
assuming this is related to my code changes and not a side effect, I'm guessing that means the returned value from `Ok(ConversionResult::Success(descriptor)) => Ok(descriptor)` is returning something invalid?

2019-07-03 17:33 UTC, julientregoat commented
> If you run the following:
> 
> ```
> wget https://build.servo.org/builders/linux-rel-wpt/builds/12771/steps/test__1/logs/test-wpt.log/text >/tmp/log
> ./mach update-wpt /tmp/log
> git add tests/wpt/metadata/permissions
> git commit --amend
> ``
> And push the result, then we should be able to merge :)
> ```

just saw this! ok, will dow when I get back to my computer

2019-07-03 17:42 UTC, jdm commented
wpt-wpt actually updates the expected test result metadata which is stored in tests/wpt/metadata. This allows us to keep running tests that currently fail, and then when PRs like this one cause them to start passing we are alerted to that fact and need to update the expected results to reflect the change.

2019-07-03 17:43 UTC, jdm commented
You will need to rebase this branch against servo's master branch, since ini files for those tests were added in #23647.

2019-07-03 17:49 UTC, julientregoat commented
thanks for the explanation!

2019-07-03 18:04 UTC, jdm commented
@bors-servo r+

2019-07-03 18:04 UTC, bors-servo commented
:pushpin: Commit 28fcde9 has been approved by `jdm`

<!-- @bors-servo r=jdm 28fcde9e10ba19bfd96bc758f2de3ca1c3688b7a -->

2019-07-03 23:56 UTC, bors-servo commented
:hourglass: Testing commit 28fcde9e10ba19bfd96bc758f2de3ca1c3688b7a with merge af295bcefe2399f11277917dcb60945327dcfd7c...

2019-07-04 02:33 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/12713), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/12775), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/Jq7b6iugSDCTqwGUxNRygw)
Approved by: jdm
Pushing af295bcefe2399f11277917dcb60945327dcfd7c to master...

2019-07-04 02:33 UTC, merged