Issue 20377
servo/servo pull request #23872
Opened 2019-07-27 18:17 UTC by marmeladema

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #20377 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-07-27 18:17 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/bindings/constant.rs, components/script/dom/bindings/guard.rs, components/script/dom/customelementregistry.rs, components/script/dom/filereader.rs, components/script/dom/htmlcanvaselement.rs and 18 more
 * @kichjang: components/script/dom/bindings/constant.rs, components/script/dom/bindings/guard.rs, components/script/dom/customelementregistry.rs, components/script/dom/filereader.rs, components/script/dom/htmlcanvaselement.rs and 18 more

2019-07-27 18:17 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2019-07-27 18:18 UTC, marmeladema commented
@jdm i went forward with removing some of the manual code that deal with raw `JSContext`

2019-08-08 20:38 UTC, jdm requested changes
Looks great!

2019-08-08 20:38 UTC, jdm commented on components/script/dom/promise.rs
>      #[allow(unsafe_code)]
This annotation can be removed now.

2019-08-08 20:38 UTC, jdm commented on components/script/dom/testbinding.rs
>      #[allow(unsafe_code)]
This annotation can be removed now.

2019-08-08 20:38 UTC, jdm commented on components/script/dom/bindings/interface.rs
> +pub fn create_global_object(
We still take a `*const libc::c_void` argument, so this method should still be marked unsafe, unfortunately.

2019-08-08 20:38 UTC, jdm commented
I am so pleased by these changes. I love seeing the unsafe blocks scope the actual pieces of unsafety!

2019-08-08 23:03 UTC, marmeladema commented
Fixed your comments and rebased over current master :+1:

2019-08-08 23:48 UTC, marmeladema commented
Fixed your comments and rebased over current master :+1:

2019-08-09 01:53 UTC, jdm commented
@bors-servo r+

2019-08-09 01:53 UTC, bors-servo commented
:pushpin: Commit 357b6c5 has been approved by `jdm`

<!-- @bors-servo r=jdm 357b6c54ff053fdd9e17832c06d7acdcbcb07991 -->

2019-08-09 02:21 UTC, bors-servo commented
:hourglass: Testing commit 357b6c54ff053fdd9e17832c06d7acdcbcb07991 with merge da559d47b93854e4c7d4acf0a0d2029a9e643794...

2019-08-09 04:48 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13050), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13109), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/L0SiN5lRQFaOwweqFxn13A)
Approved by: jdm
Pushing da559d47b93854e4c7d4acf0a0d2029a9e643794 to master...

2019-08-09 04:48 UTC, merged