ISSUE-21803: Implement ConstantSourceNode audionode
servo/servo pull request #23919
Opened 2019-08-06 12:28 UTC by tdelacour

More or less followed the steps outlined in `components/script/dom/mod.rs` (and also used the [previous PR](https://github.com/servo/servo/pull/23152) on this issue as reference). Updated `wpt` tests as well.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #21803 (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-08-06 12:28 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webidls/BaseAudioContext.webidl, components/script/dom/webidls/ConstantSourceNode.webidl, components/script/dom/constantsourcenode.rs, components/script/dom/mod.rs, components/script/dom/baseaudiocontext.rs
 * @kichjang: components/script/dom/webidls/BaseAudioContext.webidl, components/script/dom/webidls/ConstantSourceNode.webidl, components/script/dom/constantsourcenode.rs, components/script/dom/mod.rs, components/script/dom/baseaudiocontext.rs

2019-08-09 10:27 UTC, paulrouget commented
r? @ferjm / @jdm

2019-08-09 14:40 UTC, jdm requested changes
Looks good! Please squash all the commits.

2019-08-09 14:40 UTC, jdm commented on tests/wpt/metadata/webaudio/the-audio-api/the-constantsourcenode-interface/constant-source-basic.html.ini
>    [X Factory method: node = context.createConstantSource() incorrectly threw TypeError: "context.createConstantSource is not a function".]
I believe this whole file can be deleted now.

2019-08-09 14:40 UTC, jdm commented on tests/wpt/metadata/webaudio/the-audio-api/the-constantsourcenode-interface/ctor-constantsource.html.ini
>    [X node0 = new ConstantSourceNode(context) incorrectly threw TypeError: "window[name\] is not a constructor".]
This whole file can be deleted.

2019-08-10 09:29 UTC, paulrouget commented
r? @ferjm / @jdm

2019-08-10 14:21 UTC, tdelacour commented
OK @jdm, done!

2019-08-10 14:29 UTC, jdm commented
@bors-servo r+
Thanks!

2019-08-10 14:29 UTC, bors-servo commented
:pushpin: Commit b0a5d02 has been approved by `jdm`

<!-- @bors-servo r=jdm b0a5d02def6bdccfe0e4c6889250c25a524412d0 -->

2019-08-10 15:34 UTC, bors-servo commented
:hourglass: Testing commit b0a5d02def6bdccfe0e4c6889250c25a524412d0 with merge 1fd80158599232b819671e1129e68f40cc62f155...

2019-08-10 16:03 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13065)

2019-08-10 16:42 UTC, jdm commented
Surprising new failures:
```
  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] X Linear+SetTarget: At time 0.01556396484375 (frame 255) output is not close to 2.9921875 within a relative error of 0 (RelErr=0.6657963446475196). Got 1.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5
  │ _finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9
  │ _assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:12
  │ beCloseTo@http://web-platform.test:8000/webaudio/resources/audit.js:876:19
  └ @http://web-platform.test:8000/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:183:24

  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] < [Insert same event at same time] 2 out of 15 assertions were failed.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5
  │ done@http://web-platform.test:8000/webaudio/resources/audit.js:1217:9
  └ @http://web-platform.test:8000/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:104:34

  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] < [Multiple exponential ramps at the same time] 2 out of 6 assertions were failed.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5
  │ done@http://web-platform.test:8000/webaudio/resources/audit.js:1217:9
  └ @http://web-platform.test:8000/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:237:32

  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] < [Linear + Expo] 2 out of 6 assertions were failed.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5
  │ done@http://web-platform.test:8000/webaudio/resources/audit.js:1217:9
  └ @http://web-platform.test:8000/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:125:34

  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] X Multiple linear ramps: Output at frame 63 is not close to 1.984375 within a relative error of 0 (RelErr=2.4795649971548968). Got 6.904761791229248.
  │   → assert_true: expected true got false
  │ FAIL [expected PASS] X Multiple exponential ramps: Output at frame 63 is not close to 1.978456026387951 within a relative error of 5.3924e-7 (RelErr=2.4304996397067242). Got 6.787092685699463.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5
  │ _finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9
  │ _assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:12
  │ beCloseTo@http://web-platform.test:8000/webaudio/resources/audit.js:876:19
  └ testMultipleSameEvents/<@http://web-platform.test:8000/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:379:16

  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] # AUDIT TASK RUNNER FINISHED: 6 out of 6 tasks were failed.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5
  │ _finish@http://web-platform.test:8000/webaudio/resources/audit.js:1276:9
  │ _runNextTask@http://web-platform.test:8000/webaudio/resources/audit.js:1263:14
  │ done@http://web-platform.test:8000/webaudio/resources/audit.js:1220:24
  └ @http://web-platform.test:8000/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:237:32

  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] < [Multiple linear ramps at the same time] 2 out of 6 assertions were failed.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5
  │ done@http://web-platform.test:8000/webaudio/resources/audit.js:1217:9
  └ @http://web-platform.test:8000/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:224:32

  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] X Linear+Expo: At time 0.015625 (frame 256) and later, output: Expected 3 for all values but found 256 unexpected values: \n\tIndex\tActual\n\t[0]\t99\n\t[1]\t99\n\t[2]\t99\n\t[3]\t99\n\t...and 252 more errors.
  │   → assert_true: expected true got false
  │ FAIL [expected PASS] X Expo+Linear: At time 0.015625 (frame 256) and later, output: Expected 2 for all values but found 256 unexpected values: \n\tIndex\tActual\n\t[0]\t99\n\t[1]\t99\n\t[2]\t99\n\t[3]\t99\n\t...and 252 more errors.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5
  │ _finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9
  │ _assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:12
  │ beConstantValueOf@http://web-platform.test:8000/webaudio/resources/audit.js:662:19
  └ expectConstant/<@http://web-platform.test:8000/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:321:16

  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audioparam-interface/event-insertion.html:
  │ FAIL [expected PASS] < [Linear + SetTarget] 2 out of 7 assertions were failed.
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resourc [...]

2019-08-10 16:44 UTC, jdm commented
I think we should probably go ahead and mark all of the new test failures as expected for the time being, and file a followup issue to investigate them. I suspect there's something wrong with either the backend processing of constant source nodes, or the automation implementation that is used by these tests.

2019-08-10 16:45 UTC, jdm commented
More delightful passes:
```
  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] BaseAudioContext interface: operation createConstantSource()

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] BaseAudioContext interface: context must inherit property "createConstantSource()" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] BaseAudioContext interface: new OfflineAudioContext(1, 1, sample_rate) must inherit property "createConstantSource()" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode interface: existence and properties of interface object

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode interface object length

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode interface object name

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode interface: existence and properties of interface prototype object

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode interface: existence and properties of interface prototype object's "constructor" property

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode interface: existence and properties of interface prototype object's @@unscopables property

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode interface: attribute offset

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode must be primary interface of new ConstantSourceNode(context)

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] Stringification of new ConstantSourceNode(context)

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] ConstantSourceNode interface: new ConstantSourceNode(context) must inherit property "offset" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioScheduledSourceNode interface: new ConstantSourceNode(context) must inherit property "onended" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioScheduledSourceNode interface: new ConstantSourceNode(context) must inherit property "start(double)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioScheduledSourceNode interface: calling start(double) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioScheduledSourceNode interface: new ConstantSourceNode(context) must inherit property "stop(double)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioScheduledSourceNode interface: calling stop(double) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "connect(AudioNode, unsigned long, unsigned long)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: calling connect(AudioNode, unsigned long, unsigned long) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "connect(AudioParam, unsigned long)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: calling connect(AudioParam, unsigned long) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "disconnect()" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "disconnect(unsigned long)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: calling disconnect(unsigned long) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "disconnect(AudioNode)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: calling disconnect(AudioNode) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "disconnect(AudioNode, unsigned long)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: calling disconnect(AudioNode, unsigned long) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "disconnect(AudioNode, unsigned long, unsigned long)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: calling disconnect(AudioNode, unsigned long, unsigned long) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "disconnect(AudioParam)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: calling disconnect(AudioParam) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "disconnect(AudioParam, unsigned long)" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: calling disconnect(AudioParam, unsigned long) on new ConstantSourceNode(context) with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "context" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https.window.html:
  └ PASS [expected FAIL] AudioNode interface: new ConstantSourceNode(context) must inherit property "numberOfInputs" with the proper type

  ▶ Unexpected subtest result in /webaudio/idlharness.https. [...]

2019-08-12 13:20 UTC, tdelacour commented
@jdm wanted to be able to quickly undo the test metadata changes in case I misunderstood the request, so I have not squashed into one commit yet. Mind quickly confirming that this is fine?

If so I'll also go ahead and file the follow-up issue outlining the relevant tests that now fail.

2019-08-12 13:32 UTC, ferjm commented
@bors-servo try=wpt

2019-08-12 13:32 UTC, bors-servo commented
:hourglass: Trying commit dc95d6c2984fede57255640115c7610eec7d529e with merge 7120e3ce484d1a3271da85c3148b3d011abc4195...

2019-08-12 14:01 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13078)

2019-08-13 06:37 UTC, ferjm commented
> @jdm wanted to be able to quickly undo the test metadata changes in case I misunderstood the request, so I have not squashed into one commit yet. Mind quickly confirming that this is fine?
> 
> If so I'll also go ahead and file the follow-up issue outlining the relevant tests that now fail.

The test expectations changes look good to me. You can go ahead and squash the commits and file the follow-up issue. Thanks!

2019-08-15 15:54 UTC, jdm commented
@bors-servo r+

2019-08-15 15:54 UTC, bors-servo commented
:pushpin: Commit 6027dd1 has been approved by `jdm`

<!-- @bors-servo r=jdm 6027dd148a148a05b2ddc7e117eb35f8a6ec4ecd -->

2019-08-15 19:05 UTC, bors-servo commented
:hourglass: Testing commit 6027dd148a148a05b2ddc7e117eb35f8a6ec4ecd with merge 36e68963c536b58de04147760dfa2800aa306ee2...

2019-08-15 21:35 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/bLHmbGncR_GM3BcbbpNl0A)

2019-08-15 21:42 UTC, jdm commented
@bors-servo retry

2019-08-15 22:05 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2019-08-15 22:05 UTC, bors-servo commented
:hourglass: Testing commit 6027dd148a148a05b2ddc7e117eb35f8a6ec4ecd with merge 60c190887466afd7dd2e6cb9c6d0bf2c78a3b35a...

2019-08-15 23:26 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13108), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13167), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/O-tH8CnIQ_qYaHoJiWzbsQ)
Approved by: jdm
Pushing 60c190887466afd7dd2e6cb9c6d0bf2c78a3b35a to master...

2019-08-15 23:27 UTC, merged