introduce a process namespace
servo/servo pull request #23934
Opened 2019-08-08 13:55 UTC by gterzian

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #23932 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-08-08 13:55 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/constellation.rs, components/script/script_thread.rs
 * @cbrewster: components/constellation/constellation.rs
 * @kichjang: components/script/script_thread.rs

2019-08-08 13:55 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-08-08 14:00 UTC, gterzian commented
I think this is better than the current manual counting of pipeline-namespace that goes on in servo/lib and constellation, it becomes downright useful in the light of for example https://github.com/servo/servo/pull/23637

Where in order to install a pipeline-namespace in a worker thread, you need to make a blocking ipc call to the constellation, see https://github.com/servo/servo/pull/23637/files#diff-55c92a6a5ba7654ce45fe6fc6c63740fR1471

It would also be useful to install a pipeline-namespace in threads that do not have a direct channel to the constellation, for example the style threadpool(the reason why it might need one is anything requiring creating unique Ids, for example using the shared-ipc router prototyped at https://github.com/servo/servo/pull/23909, which currently can't work with parallel layout, as the communication with the font-cache occurs from a rayon thread from which it isn't easy to ask the constellation for a pipeline-namespace id).

2019-08-08 15:27 UTC, gterzian commented
This isn't going to work in multiprocess, since there is nothing to prevent one process to race ahead of the other if the namespace is just a u32....

I think the only way is tot actually use the constellation as a global lock...

2019-08-08 16:57 UTC, gterzian commented
Actually, the last commit might be something the could work. It means we'd still use the constellation to provide the `PipelineNamspaceId` to install a pipeline-namespace, and it would then be shared with all threads in the process, so each could use it to create Ids without having to install it's own pipeline. 

The downside is that the namespace becomes a kind of contended resource for all threads in a process, yet this might not matter in practice. If it were to become a problem, it could be solved by adding some intermediary per-thread namespace, that would be installed using the per-process namespace...

This could definitely make it much easier to start using the name-space from a bunch of other threads, without having to orchestrate installing it via the constellation.

2019-08-09 09:16 UTC, gterzian commented
@bors-servo try=wpt

2019-08-09 09:16 UTC, bors-servo commented
:hourglass: Trying commit be5d0dee57e23cae31da1f350901d483631e818b with merge d8aef35c38dac28eca44550a3449e3186d70cbf4...

2019-08-09 10:07 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13053), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13112), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/aqpbT7ewSc6HSsgvbtUBKA)
State: approved= try=True

2019-08-13 12:41 UTC, gterzian commented
@jdm Ok here is the latest variation on that theme. I think this can be a way to address https://github.com/servo/servo/pull/23637/files#r312133197 generally across all threads. 

So, still using the constellation as a single source of unique per UA `PipelineNamespaceId`, and now adding a per-process `PipelineNameSpaceInstaller` that is shared with all threads in the process, and that can be used to setup thread-local pipeline-namespaces. 

It's better than the previous version since it keeps the actual namespace as a thread-local, and it improves on the current situation since it makes it easy for any thread to install a namespace. 

It improves on the code at https://github.com/servo/servo/pull/23637/files by removing the need for threads to have their own plumbing to ask the constellation for a namespace. For example, with this any thread in a rayon pool could get it's own namespace without needing to setup a channel with the constellation directly or otherwise being aware of how a namespace is installed. 

Still building to test if it actually works, I think it should be ok.

2019-08-13 13:43 UTC, gterzian commented
@bors-servo try=wpt (looks like it's working locally)

2019-08-13 13:43 UTC, bors-servo commented
:hourglass: Trying commit b103e9d2f8e81627666413e0623875623ec58f7f with merge 0ca1d0f2eeca84413b0b7dfb1cef904c39d21b8d...

2019-08-13 14:33 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13088), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13147), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/fDMbNJF8RwGheVYJuy2kgw)
State: approved= try=True

2019-08-14 13:04 UTC, gterzian commented
@bors-servo try=wpt

2019-08-14 13:04 UTC, bors-servo commented
:hourglass: Trying commit 0630426aeea83823585751c2f85e9a81528334ee with merge 991090795a32c9ff2e8dd1eab7f1dee3faa73da8...

2019-08-14 13:49 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13099), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13158), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/TjuyZoRRQyKqqD47ECk1hA)
State: approved= try=True

2019-08-15 07:17 UTC, gterzian commented
@jdm this is is ready for review, I haven't squashed those commits since I'm not sure the "batching of Ids" is a good idea, so that commit could still be removed. 

This is somewhat relevant for the messageport PR, since it could rebase off of this one and simplify the worker code that installs pipeline namespaces.

2019-08-21 00:37 UTC, jdm requested changes
These changes look fine, but I don't think we need the batch generation.

2019-08-21 00:37 UTC, jdm commented on components/constellation/constellation.rs
> +    /// do not require to ipc for them initially.
I imagine that any IPC for pipeline namespace generation will be completely dwarfed by the time it takes for the network request to complete. I don't think this is worth including without data backing it up.

2019-08-21 12:11 UTC, jdm approved these changes

2019-08-21 12:22 UTC, gterzian commented
Ok, rebased as well...

2019-08-21 12:45 UTC, jdm commented
@bors-servo r+

2019-08-21 12:45 UTC, bors-servo commented
:pushpin: Commit 34008a3 has been approved by `jdm`

<!-- @bors-servo r=jdm 34008a317bb6c7ea3a02ea8a761cda6795f409ae -->

2019-08-21 14:46 UTC, bors-servo commented
:hourglass: Testing commit 34008a317bb6c7ea3a02ea8a761cda6795f409ae with merge ba1fa0835f438df32cd40bc573cecac55e98e384...

2019-08-21 17:05 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13168), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13228), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/JudIqYloS0iq0vvWDLIBZA)
Approved by: jdm
Pushing ba1fa0835f438df32cd40bc573cecac55e98e384 to master...

2019-08-21 17:06 UTC, merged