Finish the JSON clone algorithm for WebDriver
servo/servo pull request #23947
Opened 2019-08-10 23:37 UTC by georgeroman

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

2019-08-10 23:37 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/webdriver_handlers.rs, components/webdriver_server/lib.rs
 * @jgraham: components/webdriver_server/lib.rs
 * @kichjang: components/script_traits/webdriver_msg.rs, components/script/webdriver_handlers.rs

2019-08-10 23:37 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-08-11 09:03 UTC, georgeroman commented
@bors-servo try=wpt

2019-08-11 09:03 UTC, bors-servo commented
:hourglass: Trying commit 61412eca367710687b3d1c2fdff6409323e5d12f with merge f1f977c74166ba6f57125f45df4228a823ae617f...

2019-08-11 09:53 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13129)

2019-08-11 15:19 UTC, georgeroman commented
@bors-servo try=wpt

2019-08-11 15:20 UTC, bors-servo commented
:hourglass: Trying commit 2dde01b2ef0f7af11165304fe91b9c8d3b5986f5 with merge 30a6883bb4a864686bdb6f338774ea878a246d68...

2019-08-11 16:08 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13131)

2019-08-11 22:09 UTC, georgeroman commented
@bors-servo try=wpt

2019-08-11 22:09 UTC, bors-servo commented
:hourglass: Trying commit af951020cfa585badc34f4cfce3221ba1d10c395 with merge 7d259b7dff2b6615a58aa83336d5670dd1c481b0...

2019-08-11 23:05 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13077), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13136), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/OR3gFTgXRL2Sg43HSANQbA)
State: approved= try=True

2019-08-15 19:56 UTC, jdm commented
r? @jdm

2019-08-15 21:41 UTC, asajeffrey commented
@jdm did you mean to r? yourself?

2019-08-15 21:48 UTC, jdm commented
I did.

2019-08-19 22:32 UTC, jdm requested changes

2019-08-19 22:32 UTC, jdm commented on components/script/webdriver_handlers.rs
> +                Err(WebDriverJSError::UnknownType)
We should throw a DOM error here if JS_CallFunctionName failed.

2019-08-19 22:32 UTC, jdm commented on components/script/webdriver_handlers.rs
> +            let mut value = UndefinedValue();
Use rooted! here.

2019-08-19 22:32 UTC, jdm commented on components/script/webdriver_handlers.rs
> +                jsapi::MutableHandle::from_marked_location(&mut value),
We can call value.handle_mut() instead.

2019-08-19 22:32 UTC, jdm commented on components/script/webdriver_handlers.rs
> +            jsapi::HandleObject::from_marked_location(&*object),
We can use object.handle() instead.

2019-08-19 22:32 UTC, jdm commented on components/script/webdriver_handlers.rs
> +                jsapi::Handle::from_marked_location(&*object),
object.handle().

2019-08-19 22:32 UTC, jdm commented on components/script/webdriver_handlers.rs
> +                if let Ok(_) = get_property_jsval(cx, object.handle(), property, item.handle_mut())
We should throw a DOM exception if this fails.

2019-08-20 22:33 UTC, jdm commented
@bors-servo r+

2019-08-20 22:33 UTC, bors-servo commented
:pushpin: Commit 48265f9 has been approved by `jdm`

<!-- @bors-servo r=jdm 48265f978c0a2043ae674191a024217b0bc712cc -->

2019-08-20 22:53 UTC, bors-servo commented
:hourglass: Testing commit 48265f978c0a2043ae674191a024217b0bc712cc with merge 4860565c959fbe64caaa2e2a9ee95900d34a6578...

2019-08-20 23:39 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13220)

2019-08-20 23:48 UTC, jdm commented
```
  ▶ Unexpected subtest result in /webdriver/tests/execute_script/cyclic.py:
  └ PASS [expected FAIL] test_object

  ▶ Unexpected subtest result in /webdriver/tests/execute_script/cyclic.py:
  └ PASS [expected FAIL] test_array_in_object
```

2019-08-20 23:48 UTC, jdm commented
@bors-servo delegate+

2019-08-20 23:48 UTC, bors-servo commented
:v: @georgeroman can now approve this pull request

2019-08-21 16:31 UTC, georgeroman commented
@bors-servo r=jdm

2019-08-21 16:31 UTC, bors-servo commented
:pushpin: Commit c665a65 has been approved by `jdm`

<!-- @bors-servo r=jdm c665a656900db286df275bd3a0f1a31b307844c1 -->

2019-08-22 00:56 UTC, bors-servo commented
:hourglass: Testing commit c665a656900db286df275bd3a0f1a31b307844c1 with merge 2a9b2fe027228b7a89c7c284e35795923d3e26b5...

2019-08-22 03:06 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13174), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13235), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/CuKX6p8dQHquoQ_D-L5_sA)
Approved by: jdm
Pushing 2a9b2fe027228b7a89c7c284e35795923d3e26b5 to master...

2019-08-22 03:07 UTC, merged