Add secure connection start
servo/servo pull request #23990
Opened 2019-08-16 23:31 UTC by tomasdivito

Implementing `secure_connection_start` as well as we can, this is related to #21268 

We are setting the value as well as we can since we don't have a way to know if we are currently using a secure transport or where the handshake before the connection is done as the spec says on the step 15 [https://w3c.github.io/resource-timing/#sec-process](https://w3c.github.io/resource-timing/#sec-process)

Regarding the Timing Allow Check, that's being done on another PR by another person which will take care of setting the rest of the values on `PerformaceResourceTiming` to Zero and prevent them to set them any other way.

Question: I'm currently setting the `secure_connection_time` using `precise_time_ms()` as the `connection_start` and `connection_end` are set that way... but other attributes inside `PerformanceResourceTiming` are set using `precise_time
---
- [x] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-08-16 23:31 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @nox (or someone else) soon.

2019-08-16 23:31 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net_traits/lib.rs, components/net/http_loader.rs

2019-08-16 23:31 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2019-08-20 23:50 UTC, jdm commented
I updated the issue to remove the reference to redirect_start.

2019-08-20 23:54 UTC, jdm requested changes
We will also need to update components/script/dom/webidls/PerformanceResourceTiming.webidl and components/script/dom/performanceresourcetiming.rs. Exposing the new DOM APIs should cause some test results in `./mach test-wpt tests/wpt/web-platform-tests/resource-timing/` to change (https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations explains how to update the expected results).

2019-08-20 23:54 UTC, jdm commented on components/net_traits/lib.rs
> +    SecureConnectionStart(u64),
No need to pass a value here - like many other values, we can default to precise_time_ns().

2019-08-20 23:54 UTC, jdm commented on components/net_traits/lib.rs
> +            ResourceAttribute::SecureConnectionStart(val) => self.secure_connection_start = val,
We should set this to precise_time_ns() instead.

2019-08-24 17:49 UTC, tomasdivito commented
I'll be working on making the required changes to the currently failing tests.

2019-09-10 19:14 UTC, jdm commented
Still working on this @tomasdivito?

2019-09-11 15:00 UTC, tomasdivito commented
@jdm Sorry, got really busy with university, I'll try to make the tests work tomorrow and probably ask some questions if that's ok, sorry for not updating!

2019-09-25 00:17 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #23873) made this pull request unmergeable. Please resolve the merge conflicts.

2019-09-30 15:28 UTC, jdm commented
This needs a `./mach fmt`, but also there is a build failure since #23873:
```
error[E0201]: duplicate definitions with name `SecureConnectionStart`:
   --> components\script\dom\performanceresourcetiming.rs:256:5
    |
196 | /     fn SecureConnectionStart(&self) -> DOMHighResTimeStamp {
197 | |         Finite::wrap(self.secure_connection_start)
198 | |     }
    | |_____- previous definition of `SecureConnectionStart` here
...
256 | /     fn SecureConnectionStart(&self) -> DOMHighResTimeStamp {
257 | |         Finite::wrap(self.secure_connection_start)
258 | |     }
    | |_____^ duplicate definition
error: aborting due to previous error
For more information about this error, try `rustc --explain E0201`.
```

2019-10-10 15:42 UTC, jdm commented
@bors-servo try=wpt

2019-10-10 15:42 UTC, bors-servo commented
:hourglass: Trying commit 0e4708b4e6da39f51df793fc24f8a3f781b2c35a with merge 358479ff933929f753fd582fd51cfdb64c18d64c...

2019-10-10 15:43 UTC, tomasdivito commented
@jdm when running the web platform tests like you suggested

`./mach test-wpt tests/wpt/web-platform-tests/resource-timing/` I'm getting different errors and timeouts that sometimes occur, and sometimes not, and I'm not sure if this can be related to my computer (I'm currently using a macbook air 2015 which is not that powerful, but I would had assumed that it would not matter much or any... but maybe I'm wrong?) 

An example of the output I'm getting for the last run:

```
Ran 71 tests finished in 307.0 seconds.
  • 42 ran as expected. 0 tests skipped.
  • 28 tests timed out unexpectedly
  • 1 tests had unexpected subtest results
```

while previously I got
```
Ran 71 tests finished in 314.0 seconds.
  • 33 ran as expected. 0 tests skipped.
  • 38 tests timed out unexpectedly
```

2019-10-10 16:23 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13685), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13749), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/BdDn9dK8TjSyFvtMF21ZvQ)
State: approved= try=True

2019-10-10 16:32 UTC, jdm commented
This looks good! Please squash the commits together into one and remove the "draft" marking for this PR, and then it will be ready to merge.

2019-10-10 22:17 UTC, jdm commented
@bors-servo r+
Thanks!

2019-10-10 22:17 UTC, bors-servo commented
:pushpin: Commit bd0c0b6 has been approved by `jdm`

<!-- @bors-servo r=jdm bd0c0b65baede6e19683912ca8905bd7a3aa5e31 -->

2019-10-10 23:28 UTC, bors-servo commented
:hourglass: Testing commit bd0c0b65baede6e19683912ca8905bd7a3aa5e31 with merge 4bced0782f7212ecc1c95b544a563f683eae2cb9...

2019-10-11 01:15 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/G7xoidY3QZq8B7ljeIMN9Q)

2019-10-11 02:16 UTC, jdm commented
@bors-servo retry

2019-10-11 02:16 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `Unknown error`

2019-10-11 02:16 UTC, bors-servo commented
:hourglass: Testing commit bd0c0b65baede6e19683912ca8905bd7a3aa5e31 with merge d28d9fe2739162adc449c71f1a296592125e8c99...

2019-10-11 02:55 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13692), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13756), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/Ngc84_PSTQ2scyrusPu-Eg)
Approved by: jdm
Pushing d28d9fe2739162adc449c71f1a296592125e8c99 to master...

2019-10-11 02:55 UTC, merged