build_commands: Make explicit Visual Studio version dependency conditional on UWP
servo/servo pull request #24051
Opened 2019-08-25 23:44 UTC by TheGoddessInari

Ever since 3dd1bfc3175, servo breaks building on non-UWP builds if you're not running Visual Studio 2017 in the default location on C:.

UWP is the only user, so keep it from assuming environment.
In general none of this should assume or hardcode environment, but this is a quick fix for people who aren't trying to build UWP.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because 3dd1bfc3175 didn't. This just bumps the conditionality.

2019-08-25 23:44 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/build_commands.py

2019-08-26 01:36 UTC, TheGoddessInari commented
Realized it didn't work, working on making this work.

Assumptions about environment are bad. 🦊

2019-08-26 02:55 UTC, jdm commented
@bors-servo try=windows

2019-08-26 02:55 UTC, bors-servo commented
:hourglass: Trying commit e66b9bea0b02605c5fd66713ee9c9b38d511fb6e with merge e6bed524825a099c96ec060c0dff4b7349e29819...

2019-08-26 04:05 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/A5AfQ0lmReSwvSF__xLfcw)

2019-08-26 07:34 UTC, jdm commented
@bors-servo try=windows

2019-08-26 07:34 UTC, bors-servo commented
:hourglass: Trying commit e15237c5f7e02353dc604fc94d78516ef32965d1 with merge fe230d3ad353cc10ebf6dcdd4a6c5b634471c528...

2019-08-26 08:37 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/I71cQ7P0QOeiTnvWJY0vGA)

2019-08-26 18:05 UTC, jdm requested changes

2019-08-27 08:27 UTC, merged