Implemented configurable logging through C API #23813.
servo/servo pull request #24184
Opened 2019-09-11 15:57 UTC by angelortiz1007

In CInitOptions added the variable  pub ptrfunc: Option<fn(*const c_char) -> bool> which is responsible for being assigned to an Option<> None, or to a function implemented in the C/C++ code.  The C/C++ implemented function is a platform specific logger.  

In addition, vslogger.rs::log() function was modified to call this C/C++ platform specific function - if implemented - and the Windows C/C++ OutputDebugString() function no longer called.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #__23813_ (GitHub issue number if applicable)

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-09-11 16:12 UTC, jdm requested changes

2019-09-11 16:12 UTC, jdm commented on support/hololens/ServoApp/ServoControl/Servo.cpp
> +  // o.ptrfunc = NULL; //&myptrfunc;
We want the logger initialized for our application, so no need for any examples - let's create our logging function and initialize it here.

2019-09-11 16:12 UTC, jdm commented on ports/libsimpleservo/capi/src/vslogger.rs
> +                LOG_PTR_FUNC.lock().unwrap().unwrap()(log.as_ptr() as *const i8);
Let's do this:
```rust
let log_fn = &*LOG_PTR_FUNC.lock().unwrap();
if let Some(log_fn) = *log_fn {
    log_fn(log.as_ptr() as *const c_char);
}
```

2019-09-11 16:12 UTC, jdm commented on ports/libsimpleservo/capi/src/lib.rs
> +    if opts.ptrfunc.is_some() {
No need to check if this is Some or not - we can just set our global regardless.

2019-09-11 16:12 UTC, jdm commented on ports/libsimpleservo/capi/src/lib.rs
> +    pub ptrfunc: Option<fn(*const c_char) -> bool>,
Let's call this `log_func` instead.

2019-09-11 17:29 UTC, jdm commented
@bors-servo r+
Thanks!

2019-09-11 17:29 UTC, bors-servo commented
:pushpin: Commit 98c98a7 has been approved by `jdm`

<!-- @bors-servo r=jdm 98c98a7634da1a1638a0d2d17d27b0d62343168f -->

2019-09-11 18:11 UTC, angelortiz1007 commented
You are welcome!

Let me know if you want to have 1 last zoom briefing exit.

2019-09-11 18:54 UTC, jdm commented
I won't be available for that, sadly.

2019-10-25 14:45 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #24534) made this pull request unmergeable. Please resolve the merge conflicts.

2020-04-20 22:33 UTC, jdm commented
Superseded by #26196.

2020-04-20 22:33 UTC, closed without merging