ISSUE-23995: lazily generate UniqueIds
servo/servo pull request #24217
Opened 2019-09-16 03:06 UTC by tdelacour

Updated `Node` so that its `unique_id` is only generated when `unique_id()` is called. This getter now also has assumed the responsibility for saving the `id` to the global hashset on `ScriptThread`. 

Felt like I was fighting the borrow-checker a little bit on this one. Definitely a good learning experience for me, but the result strikes me as a little messy? 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23995 (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-09-16 03:06 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/node.rs
 * @kichjang: components/script/dom/node.rs

2019-09-20 14:39 UTC, jdm requested changes
Looks good!

2019-09-20 14:39 UTC, jdm commented on components/script/dom/node.rs
> +            ScriptThread::save_node_id(uid.as_ref().unwrap().borrow().to_simple().to_string());
I recommend:
```rust
let id = UniqueId::new();
ScriptThread::save_node_id(id.to_simple().to_string());
*uid = Some(id);
```

2019-09-20 14:40 UTC, jdm commented
Please squash the commits together after making the remaining change.

2019-09-20 14:43 UTC, jdm commented
However, there's one other consideration:
```
thread 'size_of::size_div' panicked at 'Your changes have increased the stack size of commonly used DOM struct HTMLDivElement from 408 to 424. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', tests/unit/script/size_of.rs:36:1
```
Our unit tests that measure the memory usage of common DOM objects report that the size is increasing (presumably because of adding the DomRefCell wrapper to the unique id). One option is to update the tests for the new size; a more attractive option is to move the `unique_id` into the NodeRareData structure, and call `self.ensure_rare_data()` before trying to retrieve a unique id. This would ensure that in the common case the DOM objects do not consume any additional memory when they do not have a unique id.

2019-09-23 13:09 UTC, tdelacour commented
@jdm OK rfal!

2019-09-23 13:26 UTC, jdm commented
@bors-servo try=linux

2019-09-23 13:26 UTC, bors-servo commented
:hourglass: Trying commit eea2a7b448ee3e84c4a7319da7f6500049aff1ef with merge 11318451d3fad31adc22269b5384fe2c66e2c105...

2019-09-23 13:48 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/VnWnk1_vThWcZNPpSFY14w)

2019-09-23 13:51 UTC, jdm commented
```
thread 'size_of::size_span' panicked at 'Your changes have decreased the stack size of commonly used DOM struct HTMLSpanElement from 408 to 400. Good work! Please update the size in tests/unit/script/size_of.rs.', tests/unit/script/size_of.rs:37:1
thread 'size_of::size_htmlelement' panicked at 'Your changes have decreased the stack size of commonly used DOM struct HTMLElement from 408 to 400. Good work! Please update the size in tests/unit/script/size_of.rs.', tests/unit/script/size_of.rs:35:1
thread 'size_of::size_node' panicked at 'Your changes have decreased the stack size of commonly used DOM struct Node from 184 to 176. Good work! Please update the size in tests/unit/script/size_of.rs.', tests/unit/script/size_of.rs:33:1
thread 'size_of::size_text' panicked at 'Your changes have decreased the stack size of commonly used DOM struct Text from 216 to 208. Good work! Please update the size in tests/unit/script/size_of.rs.', tests/unit/script/size_of.rs:38:1
thread 'size_of::size_element' panicked at 'Your changes have decreased the stack size of commonly used DOM struct Element from 392 to 384. Good work! Please update the size in tests/unit/script/size_of.rs.', tests/unit/script/size_of.rs:34:1
thread 'size_of::size_div' panicked at 'Your changes have decreased the stack size of commonly used DOM struct HTMLDivElement from 408 to 400. Good work! Please update the size in tests/unit/script/size_of.rs.', tests/unit/script/size_of.rs:36:1
thread 'size_of::size_characterdata' panicked at 'Your changes have decreased the stack size of commonly used DOM struct CharacterData from 216 to 208. Good work! Please update the size in tests/unit/script/size_of.rs.', tests/unit/script/size_of.rs:39:1
```

2019-09-23 13:51 UTC, jdm commented
Otherwise this should be all good to go!

2019-09-24 02:03 UTC, jdm commented
@bors-servo r+
Thanks!

2019-09-24 02:03 UTC, bors-servo commented
:pushpin: Commit 35d30c0 has been approved by `jdm`

<!-- @bors-servo r=jdm 35d30c042f5769f0de35f110ae63ebd0e7dca237 -->

2019-09-24 02:39 UTC, bors-servo commented
:hourglass: Testing commit 35d30c042f5769f0de35f110ae63ebd0e7dca237 with merge bbad71f7a37c828c0759a654f2a1e383521f3272...

2019-09-24 03:20 UTC, bors-servo commented
:broken_heart: Test failed - [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13530)

2019-09-24 12:20 UTC, CYBAI commented
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "AssertionError: assert 'iVBORw0KGgoA...JRU5ErkJggg==' == 'iVBORw0KGgoAA...AAElFTkSuQmCC'", 
    "stack": "session = <Session 3cec4c58-be13-4c03-9a1a-f5bfb9c8bfc4>\nurl = <function url at 0x7f6476622c80>, domain = 'alt'\n\n    @pytest.mark.parametrize(\"domain\", [\"\", \"alt\"], ids=[\"same_origin\", \"cross_origin\"])\n    def test_source_origin(session, url, domain):\n        session.url = inline(\"\"\"{0}{1}\"\"\".format(DEFAULT_CSS_STYLE, DEFAULT_CONTENT))\n    \n        response = take_screenshot(session)\n        reference_screenshot = assert_success(response)\n        assert png_dimensions(reference_screenshot) == viewport_dimensions(session)\n    \n        iframe_content = \"<style>body {{ margin: 0; }}</style>{}\".format(DEFAULT_CONTENT)\n        session.url = inline(\"\"\"{0}{1}\"\"\".format(\n            DEFAULT_CSS_STYLE, iframe(iframe_content, domain=domain)))\n    \n        response = take_screenshot(session)\n        screenshot = assert_success(response)\n        assert png_dimensions(screenshot) == viewport_dimensions(session)\n    \n>       assert screenshot == reference_screenshot\nE       AssertionError: assert 'iVBORw0KGgoA...JRU5ErkJggg==' == 'iVBORw0KGgoAA...AAElFTkSuQmCC'\nE         - iVBORw0KGgoAAAANSUhEUgAABAAAAALkCAIAAAAeetB6AAAr50lEQVR4nO3dfbzX8/348U/ZsLGNLoRfjK8pXUxWbIj4uvyua7ou5SITc5FRKulKoisWUhoNqXRlpatZpcI3hg2NqMM2XxmTkiUX6eL83p9zOqfPOXXO0almnef9/odbn/f7836d99vzn/fj8/mczymXnZ2dAgAAYhAAAAAQiAAAAIBABAAAAAQiAAAAIBABAAAAgQgAAAAIRAAAAEAgRQZAuXLJfyjjihg+AABlVnEBUMQeyggjBgAISADEZcQAAAEJgLiMGAAgIAEQlxEDAAQkAOIyYgCAgARAXEYMABCQAIjLiAEAAhIAcRkxAEBAAiAuIwYACEgAxGXEAAABCYC4jBgAICABEJcRAwAEJADiMmIAgIAEQFxGDAAQkACIy4gBAAISAHEZMQBAQAIgLiMGAAhIAMRlxAAAAQmAuIwYACCgXQqAz96eM2rYfZPmvZT1wbrN36n0wxp165/VsHnrlucfX/nbye5S2zCt9UGtpqZaTf1kSsv9ksfbKfEJpZasfOiU1v8sYtlk7x76uYk9uviOfJ0RAwBQxpQ6ALZ88PtuFw1Z16xH15b1q1X57pZ172e9+Puxt/UdtWTdhVN2/RY2uRsu5kY8UeITSqfEZUt8wq7Yo4tvp6QRAwBQBpUyALb8bUzT9m/86skRZx9ULnmYb/3irnUbf3D7ml2+hS3xVrjEJ5ROicuW+IRdsUcX307xIwYAoEwqXQBseOb6E4fWnjfr8sMK3P4Xlv3pa+P79Ro++ZkVa1IVqzdo0+2OARf9+HvpQ5I73UIfdym0JXlY8FZ4/bIJ/XoMeezp9FLHnXXZbUNqPHrKE5lP2Co5MGedCUs7rejRZ+xTb64uV7nWeVcOHdnr7Crlk/0ln9WXyb9yla98+dz3Hjh/3+Sf+ZLnFDixoldL++KdeaMGDv7tk3/627++c9TPLrh+yOArTsxIpq97UXtGsSMGAKBsKlUAbHr5lhOv/f6UZ26qtk/yqCgbV9zXuPHEmgNG3NikziHZq5bOGt6135sd5sy+unrOLwgUvpMuuCXz38kPfGtMs0bjqvVPL1Wl3OrXn7zv5hEzViytNXT11icUkBxbqWfWaadcdlP/jqceud/a1yZ3a9t78+2vT2xZodzOn1UhBZ9Q8moVu+8zYtpd7Y8/+PPlM27p2HvDwJcfavKDZNfOXtQeUNyIAQAoo0oVABueuOiIh37+9owO308eFOVfMzrVHXPa03OuqJr7wnsqtWXlmIZnLrny5XHN03fAyc1xxp10WuaWzH+n1s26tN7oUxbN3rZU9keT2tTonLr/49wnFJQcW+H6H0xb/sDPD0weJTZnDT3tnL/d+vb95+6782dVSIEnlLRaQdmrf9vkxBevz7r/nPR7Cjt5UXtAcSMGAKCMKn0A/M/bMy4qJgA2Pn1dzYHVF827Ov/+Nn13PPLcs7L6vnHPGcnr4wXupHNkbsn898Znuta8tVrBpbI/Gtvw2D90/jDnCYWkj32k8d9ndTooeZDj80ktqk5v98HkluV3/qwKyXxCiddYSHLsYVNbJ6eRPnYnL2oPKG7EAACUUaUKgE1/7l3v2u9PebZH9aI/ArRhevuq45u+83jbA5IHeT6b1OKoWR3fm9A8ucFN7obz76RzZW4p8O8ZHao+2qTQUplPKGT7XflbUjt/VoVkPqGka9z8/lPDe/Yf+4dX31n92cYtOf8398//JYedvKg9oLgRAwBQRpUqAFJfLr627pDa8+d0+X/bXr4uJP3q+K3VFs6/5ohtTynw6viGaW0Om3The9PafDfZk2PtI02OnnNx7uvfmbfC6RfLBxxbcKnstY80zX9yIZnH5srfkn4HoISz2vrM/GMLyXxC8de4z1/vPeeMyfVG3NP1vNqHf3/f5CkFjt3Ji9oDih0xAABlU+kCILX57ZEN2yz71bxR/1Nx23faJHewq2d1Pn147ZkLbzh2n3VPdPrJ6PqL53bJv8PN+Xz8c1e98kiz9EeHvprf5Zh+P1r4bPdjt76NsP73lx/Xct2I3E/AZ94rp9bNuqTuqFMXZ3zUPvuTmZfUaPfFvblPLqTAsTm2bSnprNJZMqXl+1Na7Z882JFtSyUPil0t/UGpsedlzdz2SaRPJ15w5IwOecfu3EXtAcWPGACAMqmUAZAkwHszrmk9+NMLet7Q5sxa/+972etWvrZ46t3973237fQne9VLv6q/cfnIxo0n1hhwd/dmJxySWrV05vCufd9oN3v2Ncclr7Qnt7sfT21X65b9hkwe2qr2wV+tfG5c36Fjn3+22uDc78ApcJ+d2vTW/c0aja+e82U7Vcp//OaC39w84Dcvrjjlvh3+wYGCx6ZlbCnhrDYuvrb6DQeMX3jbyfuvWnhzoy6bRizPeWcgX8ZSieJW2/K3kefWf6TmnaN7Nj3hsP0+X/mnxwdddd34ag+t3Xrszl3UHlDSiAEAKINKHQCJ7HXLpt51x32TF7z8tzUb9698TN1z2lzX+8YLqud/qj3707882qfnsMnPZn2cqlDt9DbdBw/seHz+d+SntvxzwaCrbxozf9lH2RVrnN35tiE1xp3QYWqq1dQPW0+pkvN9/PmfmE/eH3h9Qt8egx97esXqLQf9qH7bm++oO/P0S6clT857wlbJDXrud/nnH1t4S/FntTFr3JUde0995YMN3z3ipxcNHXd3q6O3vkORKLxUsqm41Tb9Y97gG/o8OG/pPz7ft3L1Bh26nby8S5/ZGef8dS9qz/gaIwYAoKzZlQBg72bEAAABCYC4jBgAICABEJcRAwAEJADiMmIAgIAEQFxGDAAQkACIy4gBAAISAHEZMQBAQKUNgA0F/h5W+uFBrdJf4f9v+QL7b1hysZnXvlOSY/9j/keVMGIAAMqi3RQAie23lFW7eKW7ePjuU8KIAQAoiwTAztvFK93Fw3efEkYMAEBZVKoASG5hD2o19cvkX7nKV7587nsjP73o0CnNX+i0okefsU+9ubpc5VrnXTl0ZK+zq5RPnpFKZa9/fUK/nsMmPbNiTarCsfVbdxsysNPx3yuX7MmUu3Kq1biX2q3od/v4Rcv+8cmXm/ZrmfOBmeJWWL9sQr8eQx57esXqLQf9qH7bXrf/ZObpl05LtZr6YespVdIL5qyQPHHbj8jbUuSy2Wv+OLpP/zGzXsj68ItvVzrmpPPbdr7q8hZ1lnRMDi907Q+c91URiyTyz21NquJxZ11225Aaj57yhAAAAOAbUaoASCS30YVexk62VOqZddopl93Uv+OpR+639rUpN7W7eeOg1ye2rFAutSlrVOPzx/6w78jeLeodWn7NsifvubHfGx3mTO98VG4eZEjWqdj1tdOb9Rp4S4s6B38yv9s5bT4auHpK8/8rcoVNb41p1mhctf4jbmxSp0q5NW8sGNOr/4N/evvUUWtyTi9ZcPtTzdtS5IkdufI3jc+bftrIEVecdsxB2R8vnz+y6xWDnjtjcpINqW2H5ypykcLntvr1J++7ecSMFUtrDV297fBvSgkjBgCgLNqtAVDh+h9MW/7Azw9MHiU2vzXs9LP/OuDt+8/dd90TF9cZUXfBgq7H7JPsSMteNbFNwxevWTKiQf4CWyXrVOxZ9clld52WuaeYFU6Yd2m90acsmn1F1byYyF47o1PNDhvu/Tjn9JIFtz/VrVuKXnbI2s5Vx5z15pzLKuW+jp/a8vcRZ5zwXNdV2wdA0Yvs6Nw+mtSmRufU/bnn9o0qYcQAAJRFuzUADn2k8d9ndTooeZDj80ktqk5v98HkluWfvq7mrdUWzr/miLzb4ORGeNWDTRqtHPT8gDrfSh5lSK8zofnK6e23dkSOjUWv8MzZvz3+1mqL5l2df4+d7Fr7SJOj51zyYc7ppRfc/lRzthRzYksuXtLopEGbOva9+crW/33cwZknmX947oI7e24fjW147B86557bN6qEEQMAUBbt3gAoYktqRodKF05cX3i5cgdfPPODhxvnPz9X/lGZ2zcUvcI7zR875tEm7zze9oBkQ57MRTL/nSt/S7En1uizl8YOvO2BWUuWrf7Of53wszOb/+JXXc4/+jsZh+cuuCvn9o0qYcQAAJRF/5YAKP9M19p31XthxrY3B4qRf1T+OomNRa+Q7Ko54NhCL8Bnvsq+YVqbwyZd+N60Nt9N9uTIeX/g4mTv1zuxDatXvPDU7MdG3vVE5cEvTutYdWPBM0xOoKhFkl3bn9vaR5rm/vTcw785JYwYAICyqPQB0OawKS3fn9Jq/+RBju1v3Ldt+XR25zOfaLHogYbfTzbn+mJJt5OuPXDCi/139BGg3KOSB/mKWeGGdy+vO+rUxXMyPme/Zkrb4y7NHp37Ofuv5nc5pt+PFj7b/ditH9Ff//vLj2u5bkR6b9HLPlt70OH3nbHsqfxP72Sv/m3jWou6vPto01Shay96kR2d2yczL6nR7outv5/wjSphxAAAlEWlDYCNi6+tfsMB4xfedvL+qxbe3KjLphFLG9x3RMEb94xb+U1/Hdu63cwT+9x22Vk1Ku+zNmvxw72vHfmtW5+f1O7wvDvjPBlHZSpmhS1v3d+s0fjqA3K/aWfNsvmje985ddmrtYflftNO9sdT29W6Zb8hk4e2qn3wVyufG9d36Njnn602OGdvkcte+Fzbg9u9cN7gsUMvOe2Yg8t98taikVdf80Kbp2b/4oebC1/7nXPrjOy4o0UKnVv5j99c8JubB/zmxRWn3Jf7DUXfqBJGDABAWVTaAEhtzBp3ZcfeU1/5YMN3j/jpRYPafdj56mlfplL7532/fnIfn/t9+Xlbvsj63aDeg8cveO39z/c9pGaDtt2HDGhfM/Oz8Wn5RyXyDsxXzArrX5/Qt8fgx55esTq7QvUzL7lt+I8nnrrtu/a3/HPBoKtvGjN/2UfZFWuc3fm2ITXGndAh/08BFLHshvefm3jv3Q/NfuGNv76/ft9Dqp/c9Mr+A688uWK5wtc+dNzdrY7+aseLpG07t5y/UXDzHXW3/o2CnJ/+DSppxAAAlEGlDoD/bElI7OhtBDLt3SMGAKBUBEBce/eIAQAolbIYAMndf+7niLb7EBGZ9uIRAwBQWmUxAPh6jBgAICABEJcRAwAEJADiMmIAgIAEQFxGDAAQkACIy4gBAAISAHEZMQBAQKUKgNzv2Uy1fOjZpq/0vmPSkrc/KVep+hntegwZ0KHWgcn+VOqLd+aNGjj4t0/+6W//+s5RP7vg+iGDrzjxoHLJjlzrl03o12NI/h/H7XX7TzL+OG72+tcn9Os5bNIzK9akKhxbv3W3IQM7Hf+9bQcXqYgDt55tq3EvtVvR7/bxi5b945MvN+3XcuqHradU2dH2nHP49LXx/XoNn5xeqmL1Bm263THgoh/nnENRq6WPSnbvTYobMQAAZVSpAiCR3AdX/OVzP6p3Wd87rjqvZsUtq5bOGn79gLc7zZ3R5UffytnbfZ8R0+5qf/zBny+fcUvH3hsGvvxQkx8kB6ZSm94a06zRuGr9R9zYpE6VcmveWDCmV/8H//T2qaPWpO+hN2WNanz+2B/2Hdm7Rb1Dy69Z9uQ9N/Z7o8Oc6Z2PKp8cW4ziDkyfT9fXTm/Wa+AtLeoc/Mn8bue0+Wjg6iktUzve3uyd+xo3nlhzQPoMD8lOX1rXfm92mDP76urfTn5QkasJAAAA/uPtQgBUuGa/8W+Ou+Dg9OviaVtWjml01h9/+eeHmnw/eZQhe/Vvm5z44vVZ95+zb/Jo3axL640+ZdHsK6rm3dFnr53RqWaHDfd+nNxDr3vi4joj6i5Y0PWYfZI9admrJrZp+OI1S0Y02G/z63eefc6w1E0Lnrqhdt7uPMUemJxtxZ5Vn1x212kFb9J3vP1fMzrVHXPa03O2nWFyaQ3PXHLly+Oapxtmx0ftfUoYMQAAZdEuBECVhxv9fdbF+ff/6dvkkeee9Va/N+5ukPNC+TbJkw+b2vqDyenXyDc+07XmrdUWzbs6/+46uVVf+0iTo+dc8uGUluWfvi7Zu3D+NUdk7F31YJNGKwc9P6BO6rXhZ509NHXTU4u6/TjvNn+rjcUeuHla60MnNF85vX3uB5TyJSe2/fb0UgOrFzzDnEvL6vvGPWckl7bDo/ZCJYwYAICyaBcC4NAprf+ZvGafPMjz2aQWR83q+N6EJmueGt6z/9g/vPrO6s82bslZZf/cz/cnB87oUPXRJu883vaAZGue/NVSMzpUunDi+pxDMpQ7+OKZHzzcODm8KMmyxRyYylu/0Ar5Pzdz+4bp7auOb1roDPMurXnyzB0etRcqYcQAAJRFuxAAVcae/9bczpULvgNw9lv9Xrtu6c/PmFxvxD1dz6t9+Pf3TV5GT56cf8ecfgdgwLGFXqr/aGzDY//QOf0OwDNda99V74UZnQ5KNu+MZNliDsw8gUw73J5+B6DwmwnpSyvwDsB2R+2FShgxAABl0S4EQIWryj305qTWlfIKYEvO7wBc/fL9m686Yux5WTO33Yt/OvGCI2d02HrHvG7WJXVHnbo44xP22WumtD3u0uzR6d8B+HR25zOfaLHogYbbfo/giyXdTrr2wAkv9q/zreRRUYo9MP0RoB3dsidXsYPt657o9JPR9RfP7ZJfAMmlNTzzuateeaRZevUdH7X3KWHEAACURbsQAJVuer1OjZY33P7L82tVzP5 [...]

2019-09-24 13:27 UTC, tdelacour commented
Oh, huh. Reverted!

2019-09-24 13:32 UTC, jdm commented
@bors-servo r+

2019-09-24 13:32 UTC, bors-servo commented
:pushpin: Commit d0c64d3 has been approved by `jdm`

<!-- @bors-servo r=jdm d0c64d347d1b8c42af2a4d5e30a68867af871834 -->

2019-09-24 13:42 UTC, bors-servo commented
:hourglass: Testing commit d0c64d347d1b8c42af2a4d5e30a68867af871834 with merge 95a9fcca89bc52f4f6ce81fe5f878abbc308b66a...

2019-09-24 16:08 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/LViSZsvSTDmkhGYGxILdsw)

2019-09-24 17:40 UTC, bors-servo commented
:hourglass: Testing commit d0c64d347d1b8c42af2a4d5e30a68867af871834 with merge 5ab2d4ea835374c2ca88f5d9b50100669f142273...

2019-09-24 20:01 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13480), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13541), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/Wbv20cTTRDu60-y3vDtVAA)
Approved by: jdm
Pushing 5ab2d4ea835374c2ca88f5d9b50100669f142273 to master...

2019-09-24 20:02 UTC, merged