Integrates media track selection
servo/servo pull request #24265
Opened 2019-09-22 12:03 UTC by sreeise

Updates audio/video track selection to use the servo media player track selection methods.

This is technically only a partial fix because only one audio track can be set at a time and servo_media needs to be updated to handle multiple audio tracks. Once/if this goes through I can file follow up issue for that.

I believe this also inadvertently covers at least some of #22912

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22799 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because -  This probably should have a test case. But I am not aware of a way, at least not from servo, to test that the actual audio or video changed in the underlying player or on screen.

2019-09-22 12:03 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/videotrack.rs, components/script/dom/audiotracklist.rs, components/script/dom/videotracklist.rs, components/script/dom/htmlmediaelement.rs, components/script/dom/audiotrack.rs
 * @kichjang: components/script/dom/videotrack.rs, components/script/dom/audiotracklist.rs, components/script/dom/videotracklist.rs, components/script/dom/htmlmediaelement.rs, components/script/dom/audiotrack.rs

2019-09-22 12:03 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2019-09-22 12:13 UTC, nox requested changes

2019-09-22 12:13 UTC, nox commented on components/script/dom/audiotrack.rs
> +    #[allow(unrooted_must_root)]
Ditto, make the argument be `Option<&AudioTrackList>`.

2019-09-22 12:13 UTC, nox commented on components/script/dom/audiotrack.rs
> +    track_list: DomRefCell<Option<Dom<AudioTrackList>>>,
Make that `Option<Dom<AudioTrackList>>`, you never actually need to mutate it. If I'm wrong about it never changing, it should be `MutNullableDom<AudioTrackList>`.

2019-09-22 12:13 UTC, nox commented on components/script/dom/audiotracklist.rs
> +    media_element: DomRefCell<Option<Dom<HTMLMediaElement>>>,
`Option<Dom<HTMLMediaElement>>`

2019-09-22 12:13 UTC, nox commented on components/script/dom/audiotrack.rs
> +    #[allow(unrooted_must_root)]
Remove that, change the argument type to be `Option<&AudioTrackList>`.

2019-09-22 12:13 UTC, nox commented on components/script/dom/audiotracklist.rs
> +    #[allow(unrooted_must_root)]
Same remark as for the others `unrooted_must_root`.

2019-09-22 12:13 UTC, nox commented on components/script/dom/audiotracklist.rs
> +    #[allow(unrooted_must_root)]
Same remark as for the others `unrooted_must_root`.

2019-09-22 12:13 UTC, nox commented on components/script/dom/videotrack.rs
> +    #[allow(unrooted_must_root)]
Same remark as for the others `unrooted_must_root`.

2019-09-22 12:13 UTC, nox commented on components/script/dom/videotrack.rs
> +    #[allow(unrooted_must_root)]
Same remark as for the others `unrooted_must_root`.

2019-09-22 12:13 UTC, nox commented on components/script/dom/videotracklist.rs
> +    #[allow(unrooted_must_root)]
Same remark as for the others `unrooted_must_root`.

2019-09-22 12:13 UTC, nox commented on components/script/dom/videotrack.rs
> +    track_list: DomRefCell<Option<Dom<VideoTrackList>>>,
`Option<Dom<VideoTrackList>>`

2019-09-22 12:13 UTC, nox commented on components/script/dom/videotracklist.rs
> +    media_element: DomRefCell<Option<Dom<HTMLMediaElement>>>,
`Option<Dom<HTMLMediaElement>>`

2019-09-22 12:13 UTC, nox commented on components/script/dom/videotracklist.rs
> +    #[allow(unrooted_must_root)]
Same remark as for the others `unrooted_must_root`.

2019-09-22 15:00 UTC, sreeise commented
@nox Thanks for the review. I have a question if you don't mind answering. I was thinking that somehow DomRefCell was needed when a Dom object is not owned, as if somehow this made a difference to the garbage collector, but I realize that, as you mentioned, there is no need for a mutable borrow so I didn't need to use DomRefCell. I have read the documentation on the Dom module here https://doc.servo.org/script/dom/index.html and I am trying to get a better understanding of how the garbage collector keeps track. Am I correct in thinking that anything that is passed in the reflect_dom_object method is covered by the spider monkey garbage collector?

2019-09-22 15:23 UTC, nox commented
Anything that is properly accounted for by the `JSTraceable` implementation on a given type is covered by the SpiderMonkey GC.

2019-09-24 10:27 UTC, nox commented
LGTM but I'll let Josh give approval, given that's not an area I've touched in ages.

r? @jdm

2019-09-24 10:28 UTC, nox approved these changes

2019-10-02 14:36 UTC, jdm commented
@bors-servo r+
Looks good! Sorry for the long wait.

2019-10-02 14:36 UTC, bors-servo commented
:pushpin: Commit 5ea79c6 has been approved by `jdm`

<!-- @bors-servo r=jdm 5ea79c64f9a56b3e116d7d306c9d300a5d6717a5 -->

2019-10-02 14:53 UTC, bors-servo commented
:hourglass: Testing commit 5ea79c64f9a56b3e116d7d306c9d300a5d6717a5 with merge 218a2aefc5708a22a3594a2947317810bcf3c6f5...

2019-10-02 16:26 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13573), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13635), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/ehCjQpQhSk6YVFh5cs5wOw)
Approved by: jdm
Pushing 218a2aefc5708a22a3594a2947317810bcf3c6f5 to master...

2019-10-02 16:26 UTC, merged