Consolidate size helpers
servo/servo pull request #24524
Opened 2019-10-22 23:36 UTC by bblanke

Addresses issues raised in the review of PR #24518 and includes changes to 17 tests' metadata for those that now PASS.

Contains fixes in PR #24518:

Updated the offscreen canvas rendering context to use the offscreen canvas' size. This involved upgrading several methods to accept u64 sizes.

Additionally, the code in OffscreenCanvas::SetWidth() and OffscreenCanvas::SetHeight() was updated to send CanvasMsg::Recreate to the canvas paint thread.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #24465

- [X] There are tests for these changes – 17 were updated to PASS

2019-10-23 03:18 UTC, jdm commented
In future there is no need to close the existing PR to address review comments. You can make changes to the branch and push them (force pushing if you rewrite history at all) and they will be reflected in the open PR.

2019-10-23 16:24 UTC, bblanke commented
Okay; that makes sense!

2019-10-24 14:13 UTC, jdm requested changes
This looks really close! I've filed https://github.com/servo/servo/issues/24536 as some clean up that can be done as a result of this work. Your choice if you want to hop on it or not!

2019-10-24 14:13 UTC, jdm commented on tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html.ini
> +    expected: PASS
The new passing subtests can be removed from this file.

2019-10-24 14:13 UTC, jdm commented on components/script/dom/webglrenderingcontext.rs
> +pub trait Size2DExt {
No need for this now; we can import the trait from crate::euclidext::Size2DExt.

2019-10-24 14:13 UTC, jdm commented on components/script/dom/webglrenderingcontext.rs
> +        let src_rect = Rect::new(
Is this the same as `src_rect.to_u32()`?

2019-10-24 14:13 UTC, jdm commented on components/script/dom/imagedata.rs
> +pub trait Size2DExt {
This can be imported from crate::euclidext::Size2DExt instead.

2019-10-24 14:13 UTC, jdm commented on components/script/dom/canvasrenderingcontext2d.rs
> +        let rect = Rect::new(
Is this the same as `rect.to_u64()` if we import the helper trait?

2019-10-24 14:13 UTC, jdm commented on components/script/Cargo.toml
> +canvas = {path = "../canvas"}
Why is this change necessary?

2019-10-24 14:13 UTC, jdm commented on components/pixels/lib.rs
> +    let size = Size2D::new(size.width as u64, size.height as u64);
`size` is already a `Size2D<u64>`. Is this necessary?

2019-10-24 14:13 UTC, jdm commented
@bors-servo try=wpt

2019-10-24 14:52 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13871), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13935), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/elKoKCd2QhOl4j_A6Nj9wA)
State: approved= try=True

2019-10-28 16:59 UTC, jdm commented
Looks great! This needs to be rebased to deal with the merge conflicts from #24519 unfortunately, which will mean ensuring that any changes you made to CanvasState are moved into the new `components/script/canvas_state.rs` file. See step 7 in https://github.com/servo/servo/wiki/Github-workflow; if you have difficulties here, please let us know and we can help!

To make the process easier, I recommend [squashing](https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/) your commits into one single commit before starting the rebase against upstream.

2019-10-28 23:54 UTC, bblanke commented
@jdm I've made changes to my branch to address your feedback and #24536
Let me know what you think/if I need to do anything to move this toward a merge!

2019-10-29 00:01 UTC, jdm commented
@bblanke If you look at the bottom of the pull request, you should see:
```
Conflicting files
components/script/dom/canvasrenderingcontext2d.rs
components/script/dom/offscreencanvasrenderingcontext2d.rs
components/script/lib.rs
```
This means that your rebase did not include the changes from #24519, unfortunately. You need to ensure you have fetched a revision from servo/servo that includes 31ff2d43ccc835bffc99aac596dabae1d23cc5f7 and then rebase your branch on top of that revision.

2019-11-11 16:03 UTC, bblanke commented
@jdm Figured out how to properly rebase! The guide on your wiki is great. Let me know if this works.

2019-11-11 16:04 UTC, bblanke commented
@bors-servo try=wpt

2019-11-11 16:04 UTC, bors-servo commented
@bblanke: :key: Insufficient privileges: not in try users

2019-11-11 16:39 UTC, jdm commented
@bors-servo try=wpt

2019-11-11 16:39 UTC, bors-servo commented
:hourglass: Trying commit ec2961920b74fbe0345f72e6007c6d42ae852019 with merge a1194c4b8c3db89b797ba7984919b2668c39a6ca...

2019-11-11 17:21 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/14106), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/14169), [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/aRnmL_w8RnyADvKJsCuHeg)
State: approved= try=True

2019-11-11 17:35 UTC, jdm commented
@bors-servo r+
Thanks for doing this work!

2019-11-11 17:35 UTC, bors-servo commented
:pushpin: Commit ec29619 has been approved by `jdm`

<!-- @bors-servo r=jdm ec2961920b74fbe0345f72e6007c6d42ae852019 -->

2019-11-11 17:35 UTC, bors-servo commented
:hourglass: Testing commit ec2961920b74fbe0345f72e6007c6d42ae852019 with merge 3d2e980b3cba97e554074cda5ca73f35711225d0...

2019-11-11 19:26 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/R-hJOJxiQhmbiPr3AXUAcw)

2019-11-11 19:27 UTC, jdm commented
An interesting failure:
```
  ▶ CRASH [expected OK] /offscreen-canvas/the-offscreen-canvas/size.large.html
  │ 
  │ 
  │ 
  │ 
  │ Stack trace for thread "CanvasThread"
  │ stack backtrace:
  │    0: backtrace::backtrace::trace
  │    1: backtrace::capture::Backtrace::new
  │    2: servo::install_crash_handler::handler
  │    3: _sigtramp
  │    4: AzCreateDrawTarget
  │    5: azure::azure_hl::DrawTarget::new
  │    6: <canvas::azure_backend::AzureBackend as canvas::canvas_data::Backend>::create_drawtarget
  │    7: canvas::canvas_data::CanvasData::recreate
  │    8: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hb22351f2903007feE.llvm.14423657731009663445
  │    9: __rust_maybe_catch_panic
  │   10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │   12: std::sys::unix::thread::Thread::new::thread_start
  │   13: _pthread_body
  │   14: _pthread_start
  └ 
```
Does `./mach test-wpt tests/wpt/web-platform-tests/offscreen-canvas/the-offscreen-canvas/size.large.html` reproduce a crash for you?

2019-11-11 19:43 UTC, jdm commented
Ah, I see I can reproduce it locally, and apparently on mac the drawing surface doesn't get created successfully with such a large size:
```
(lldb) r
Process 47583 launched: '/Users/jdm/src/servo/target/debug/servo' (x86_64)
servo was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 47583 stopped
* thread #30, name = 'CanvasThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x0000000107473b00 servo`::AzCreateDrawTarget(AzBackendType, AzIntSize *, AzSurfaceFormat) [inlined] mozilla::detail::RefCounted<mozilla::gfx::DrawTarget, (mozilla::detail::RefCountAtomicity)1>::AddRef(this=<unavailable>) const at RefPtr.h:111:5 [opt]
   108 	    // Note: this method must be thread safe for AtomicRefCounted.
   109 	    MOZ_ASSERT(int32_t(mRefCnt) >= 0);
   110 	#ifndef MOZ_REFCOUNTED_LEAK_CHECKING
-> 111 	    ++mRefCnt;
   112 	#else
   113 	    const char* type = static_cast<const T*>(this)->typeName();
   114 	    uint32_t size = static_cast<const T*>(this)->typeSize();
Target 0: (servo) stopped.
(lldb) up
frame #1: 0x0000000107473b00 servo`::AzCreateDrawTarget(aBackend=<unavailable>, aSize=<unavailable>, aFormat=<unavailable>) at azure-c.cpp:181 [opt]
   178 	    RefPtr<gfx::DrawTarget> target = gfx::Factory::CreateDrawTarget(backendType,
   179 	                                                                    *size,
   180 	                                                                    surfaceFormat);
-> 181 	    target->AddRef();
   182 	    return target;
   183 	}
   184
```

2019-11-11 19:47 UTC, jdm commented
However, I can only reproduce it intermittently. Therefore, filed #24710.

@bors-servo retry

2019-11-11 19:47 UTC, bors-servo commented
:bomb: Failed to start rebuilding: `405 Not Allowed`

2019-11-11 19:47 UTC, bors-servo commented
:hourglass: Testing commit ec2961920b74fbe0345f72e6007c6d42ae852019 with merge 905f714bb4b2959f1735cc7469969696eac56d47...

2019-11-11 20:35 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/14108), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/14171), [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/BJekdFcdRRiWKV4A0ePO7w)
Approved by: jdm
Pushing 905f714bb4b2959f1735cc7469969696eac56d47 to master...

2019-11-11 20:35 UTC, merged

2019-11-12 00:56 UTC, bblanke commented
Weird; I'll investigate!