Implement MouseEvent's x/y and offsetX/offsetY attributes
servo/servo pull request #24521
Opened 2019-10-22 00:40 UTC by tigleym

Implement MouseEvent's x/y and offsetX/offsetY attributes

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #24248 (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2019-10-22 00:40 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @asajeffrey (or someone else) soon.

2019-10-22 00:40 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webidls/MouseEvent.webidl, components/script/dom/domrect.rs, components/script/dom/mouseevent.rs
 * @kichjang: components/script/dom/webidls/MouseEvent.webidl, components/script/dom/domrect.rs, components/script/dom/mouseevent.rs

2019-10-22 00:42 UTC, servo-wpt-sync commented
Opened new PR for upstreamable changes.

Completed upstream sync of web-platform-test changes at https://github.com/web-platform-tests/wpt/pull/19816.

2019-10-22 01:20 UTC, jdm commented
@bors-servo try=wpt

2019-10-22 01:20 UTC, bors-servo commented
:hourglass: Trying commit b3367350256b5547c2a705dde858bfc0d4fc8f03 with merge b3119be7ac5ec3e41f28cfb6cba79272b941ad45...

2019-10-22 02:02 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/13834), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/13898), [status-taskcluster](https://tools.taskcluster.net/task-group-inspector/#/D36WaFxLRBebAMCiSA-OSA)
State: approved= try=True

2019-10-23 04:11 UTC, atouchet commented on tests/wpt/metadata/css/cssom-view/mouseEvent.html.ini
> -
If there are no more failing tests you can delete the file.

2019-10-24 22:53 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#19816.

2019-10-25 22:26 UTC, jdm requested changes

2019-10-25 22:26 UTC, jdm commented on components/script/dom/mouseevent.rs
> +                    if let Some(element) = target.downcast::<Element>() {
If we downcast to Node instead then we can call `Node::client_rect`. This means we should get expected behaviour for mouse events on non-Elements like text nodes, for example.

2019-10-25 22:26 UTC, jdm commented on components/script/dom/mouseevent.rs
> +                    if let Some(element) = target.downcast::<Element>() {
Same as previous comment.

2019-10-25 22:26 UTC, jdm commented on components/script/dom/domrect.rs
> +    pub fn top(&self) -> f64 {
We should be able to remove these based on my other comments.

2019-10-29 02:37 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#19816.

2019-11-04 16:07 UTC, jdm commented
This looks good, it just needs a final `./mach update-manifest` to reflect the changes to the WPT test.

2019-11-04 16:46 UTC, tigleym commented
> This looks good, it just needs a final `./mach update-manifest` to reflect the changes to the WPT test.

Sounds good! I'll get this updated today.

2019-11-04 23:52 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#19816.

2019-11-05 00:00 UTC, jdm commented
@bors-servo r+

2019-11-05 00:00 UTC, bors-servo commented
:pushpin: Commit 38b91c3 has been approved by `jdm`

<!-- @bors-servo r=jdm 38b91c3501ce460dad52432a3cb2d4a859b04662 -->

2019-11-05 06:49 UTC, bors-servo commented
:hourglass: Testing commit 38b91c3501ce460dad52432a3cb2d4a859b04662 with merge f6a906d5e0fd83dbe75ab6f47512b4b5844c3e92...

2019-11-05 06:54 UTC, bors-servo commented
:snowman: The build was interrupted to prioritize another pull request.

2019-11-05 07:43 UTC, bors-servo commented
:hourglass: Testing commit 38b91c3501ce460dad52432a3cb2d4a859b04662 with merge 28dbbda5bb0736b4f8f6c5c08a8bc268496f5422...

2019-11-05 10:15 UTC, bors-servo commented
:sunny: Test successful - [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/14004), [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/14067), [status-taskcluster](https://tools.taskcluster.net/groups/fOUMKH-0TtWUTZKv7QJQBQ)
Approved by: jdm
Pushing 28dbbda5bb0736b4f8f6c5c08a8bc268496f5422 to master...

2019-11-05 10:15 UTC, merged