Add nightly task to build and run tests with latest webrender.
servo/servo pull request #24889
Opened 2019-11-27 17:26 UTC by jdm

Like the nightly Rust compiler upgrade task, this will help us learn sooner when Webrender introduces breaking API changes or causes regressions in our testsuite.

2019-11-27 17:30 UTC, Manishearth approved these changes
r+

2019-11-27 17:33 UTC, jdm commented
@bors-servo r=manishearth

2019-11-27 17:33 UTC, bors-servo commented
:pushpin: Commit 1c7f9d8 has been approved by `manishearth`

<!-- @bors-servo r=manishearth 1c7f9d8e0c97a84457877eb0d7ee50a434d46ddd -->

2019-11-27 17:33 UTC, bors-servo commented
:hourglass: Testing commit 1c7f9d8e0c97a84457877eb0d7ee50a434d46ddd with merge bdbddeadce56c65837afe3db778e693bc21e0a58...

2019-11-27 17:39 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/C0hnD2voSmm99tiR9LzgqA)

2019-11-27 18:06 UTC, SimonSapin commented on etc/taskcluster/decision_task.py
> +    return linux_wpt_common(total_chunks=4, layout_2020=False, webrender_nightly=True)
Nit: I’d prefer to keep the calls to `linux_wpt_common` closer to each other, so we see them all when changing for example the number of chunks.

2019-11-27 18:10 UTC, atouchet commented
Can this be used to submit a pull request like #23766 suggests?

2019-11-27 18:12 UTC, SimonSapin requested changes
I get the desire for something like this PR, but I’m not a fan of:

* Adding any more daily tasks that are expected to sometimes fail without a `servo/servo` PR breaking them
* Adding a known source of intermittent failures (WPT) to daily tasks

… as long as the only feedback we have from them is IRC notifications to a few people.

I tend to take care of compiler updates, but I’m not personally planning to do the same for WebRender. Yet with this PR I’ll get pinged *every day* when WebRender’s master doesn’t build in Servo or has any impact on WPT, until Servo is updated.

2019-11-27 18:18 UTC, SimonSapin commented
Possible mitigation: replace this:

https://github.com/servo/servo/blob/a020522f37241001b01ee77dab562d50b6e7a924/etc/taskcluster/decision_task.py#L128

With some per-task configuration where someone is pinged if they personally opt-in.

2019-11-27 18:23 UTC, jdm commented
I'll make the pinging configurable like you suggest.

2019-11-27 18:24 UTC, jdm commented
@atouchet That's more effort than I'm willing to spend on this task right now, given the complexities involved in https://github.com/servo/servo/blob/master/etc/ci/update-wpt-checkout.

2019-12-05 23:06 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #25117) made this pull request unmergeable. Please resolve the merge conflicts.

2020-11-11 20:47 UTC, bors-servo commented
:lock: Merge conflict

2023-07-07 08:53 UTC, mrobinson commented
Going to close this PR since it's against the old taskcluster config.

2023-07-07 08:53 UTC, closed without merging