stepUp, stepDown, and valueAsNumber work [draft]
servo/servo pull request #25405
Opened 2019-12-30 22:54 UTC by pshaughn

Steppy operation of input elements now functions. A few related tests still fail because of incorrect test expectations. A couple range reftests fail on what might be correct expectations; solving that involves layout, not DOM.
#25386 still needs valueAsDate and list; I'll probably update that within this PR since it's going to have changes in common with this.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25390 and fix #25388 and fix #19773 (except validation doesn't exist) and progress #25386

- [X] There are tests for these changes OR

2019-12-30 22:54 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webidls/HTMLInputElement.webidl, components/script/dom/element.rs, components/script/dom/servoparser/mod.rs, components/script/dom/htmlinputelement.rs, components/script/dom/bindings/str.rs
 * @kichjang: components/script/dom/webidls/HTMLInputElement.webidl, components/script/dom/element.rs, components/script/dom/servoparser/mod.rs, components/script/dom/htmlinputelement.rs, components/script/dom/bindings/str.rs

2019-12-30 22:54 UTC, pshaughn commented
@bors-servo try=wpt

2019-12-30 22:54 UTC, bors-servo commented
:hourglass: Trying commit b0be07b07a2dac70abbc02f12e28b022460e940a with merge f657e0ac6fb0d63a352fc840c8ef3027eb1fc5de...

2019-12-30 23:13 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/AuxFG5SVSl2cHBXhKVM0jg)

2019-12-31 00:06 UTC, pshaughn commented
@bors-servo retry=wpt

2019-12-31 00:09 UTC, pshaughn commented
is that the wrong syntax?
@bors-servo try=wpt

2019-12-31 00:09 UTC, bors-servo commented
:hourglass: Trying commit 673369955ecd7515851f65fa417a5a6745cd8587 with merge 7544c1b6486ed980422a20105befb21a85d36cf5...

2019-12-31 00:51 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/dfrE_Y9-TK2M9zPmOEhbpg)

2019-12-31 18:23 UTC, servo-wpt-sync commented
Opened new PR for upstreamable changes.

Completed upstream sync of web-platform-test changes at https://github.com/web-platform-tests/wpt/pull/20973.

2019-12-31 21:11 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2019-12-31 21:12 UTC, pshaughn commented
List is working now, and I added a test for it... existing valueAsNumber tests aren't covering the chrono types, I'm gonna go in and add those too, and this is still a draft
@bors-servo try=wpt

2019-12-31 21:12 UTC, bors-servo commented
:hourglass: Trying commit bb4c34af29a7439cb39b38936abf5c4aa1fae6aa with merge f138fc886ad1e81240c976cbbbc9b23999f745ae...

2019-12-31 21:55 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/Oo_UqMlSTvK5J6pQOizn0g)

2019-12-31 21:59 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2019-12-31 22:09 UTC, pshaughn commented
Don't bother trying that push, it needs a rebase (because a WPT test was fixed upstream) and a bunch of idlharness test metadata.

2019-12-31 22:39 UTC, pshaughn commented
I think this might be all synced up now.
@bors-servo try=wpt

2019-12-31 22:40 UTC, bors-servo commented
:hourglass: Trying commit 2998ac6cf71fb702136d2fb74768b26e1c301012 with merge c62b6e757c5c84124ace9a7b253de0549b84d79d...

2019-12-31 22:41 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2019-12-31 23:20 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/TA1aCQU6Qh-oZAp9ucQyTQ)

2019-12-31 23:39 UTC, pshaughn commented
@bors-servo try=wpt

2019-12-31 23:39 UTC, bors-servo commented
:hourglass: Trying commit c840a269495c5f80e3bd31be78af8c7095cc94da with merge 93b1a41e97e8e2a578ec0dbebeaee16e2609a071...

2019-12-31 23:40 UTC, servo-wpt-sync commented
PR title changed; changed existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2019-12-31 23:40 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2019-12-31 23:53 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2020-01-01 00:40 UTC, pshaughn commented
@bors-servo try=wpt

2020-01-01 00:40 UTC, bors-servo commented
:hourglass: Trying commit 4ee84c22dd6fc0a4fea3db8c573a28b1eb0eeaea with merge 46975169893aa09a20a34f20da60c0668f9e0624...

2020-01-01 01:23 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/IyBun-ogTLiuPw-Z4KYWlA)

2020-01-01 19:38 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2020-01-06 20:20 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2020-01-09 20:01 UTC, jdm requested changes
This is great! There's a surprising amount of subtlety in the implementation here, and your comments make me feel more comfortable with revisiting this code in the future if the spec changes or incompatibilities warrant it.

2020-01-09 20:01 UTC, jdm commented on tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/input-valueasnumber-stepping.html
> +          input=document.getElementById("input_"+inputType);
Same nit comments as previous test files.

2020-01-09 21:07 UTC, pshaughn commented on components/script/dom/htmlinputelement.rs
> +        let listString = self
I'm not sure how that even happened. Is there a way test-tidy could be set up to catch it?

2020-01-09 21:21 UTC, jdm commented on components/script/dom/htmlinputelement.rs
> +        let listString = self
I'm honestly surprised that the rust compiler warnings for this didn't fire.

2020-01-09 21:31 UTC, jdm commented on components/script/dom/htmlinputelement.rs
> +        let listString = self
Huh: https://github.com/servo/servo/blob/5c7a4db5f4e374dee287d403d90c7bc0e07ac9d0/components/script/lib.rs#L12

2020-01-09 21:38 UTC, pshaughn commented on components/script/dom/htmlinputelement.rs
> +            if let Some(ancestor) = ancestors.last() {
Yes, it is and I hadn't realized that method existed at the time. I think I was copying from what I saw in CompareDocumentPosition, but that method had a reason to also want the entire list.

2020-01-10 00:01 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2020-01-10 15:06 UTC, jdm approved these changes

2020-01-10 15:06 UTC, jdm commented
@bors-servo r+

2020-01-10 15:06 UTC, bors-servo commented
:pushpin: Commit 03f2f39 has been approved by `jdm`

<!-- @bors-servo r=jdm 03f2f39a28663d5718ed12b868651254b8775d8f -->

2020-01-10 15:53 UTC, bors-servo commented
:hourglass: Testing commit 03f2f39a28663d5718ed12b868651254b8775d8f with merge 634f12f9b6a20ee7e095d9fa1272fa58061e3806...

2020-01-10 16:33 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/PmKQJqvLTJSg8n-bkvDMoQ)

2020-01-10 17:43 UTC, jdm commented
```
  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type date (actual value: , expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type date (actual value: 0000-12-10, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type date (actual value: 2019-00-12, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type date (actual value: 2019-12-00, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type date (actual value: 2019-13-10, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type date (actual value: 2019-02-29, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type date (actual value: 2019-12-10, expected valueAsNumber: 1575936000000)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type date (actual value: 2016-02-29, expected valueAsNumber: 1456704000000)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber setter on type date (actual valueAsNumber: 0, expected value: 1970-01-01)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber setter on type date (actual valueAsNumber: 1575936000000, expected value: 2019-12-10)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type month (actual value: , expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type month (actual value: 0000-12, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type month (actual value: 2019-00, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type month (actual value: 2019-12, expected valueAsNumber: 599)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type week (actual value: , expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type week (actual value: 0000-W50, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type week (actual value: 2019-W00, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type week (actual value: 2019-W60, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type week (actual value: 2019-W50, expected valueAsNumber: 1575849600000)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber setter on type week (actual valueAsNumber: 0, expected value: 1970-W01)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type time (actual value: , expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type time (actual value: 24:00, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type time (actual value: 00:60, expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type time (actual value: 00:00, expected valueAsNumber: 0)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type time (actual value: 12:00, expected valueAsNumber: 43200000)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type time (actual value: 23:59, expected valueAsNumber: 86340000)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type datetime-local (actual value: , expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type datetime-local (actual value: 2019-12-10T00:00, expected valueAsNumber: 1575936000000)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber setter on type datetime-local (actual valueAsNumber: 1575936000000, expected value: 2019-12-10T00:00)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type number (actual value: , expected valueAsNumber: NaN)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type number (actual value: 123, expected valueAsNumber: 123)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type number (actual value: 123.456, expected valueAsNumber: 123.456)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber setter on type number (actual valueAsNumber: 123, expected value: 123)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type range (actual value: , expected valueAsNumber: 50)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type range (actual value: 0, expected valueAsNumber: 0)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumber getter on type range (actual value: 50, expected valueAsNumber: 50)

  â–¶ Unexpected subtest result in /html/semantics/forms/the-input-element/input-valueasnumber.html:
  â”” PASS [expected FAIL] valueAsNumb [...]

2020-01-10 19:00 UTC, pshaughn commented
Interesting! It looks like that fail at the end is expecting the seconds to be left off the string value when they're zero, which I'm 99% sure is not specified anywhere and which has branches for it in other tests.

2020-01-10 22:32 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #25413) made this pull request unmergeable. Please resolve the merge conflicts.

2020-01-11 00:13 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2020-01-11 00:35 UTC, jdm commented
@bors-servo try=wpt

2020-01-11 00:35 UTC, bors-servo commented
:hourglass: Trying commit cc330446fce39cddacc98c61f557cae5bc24eeb2 with merge 8d79ebd1e8f380d6470d7ce5b4ea2ac6c1305259...

2020-01-11 01:11 UTC, servo-wpt-sync commented
Transplanted upstreamable changes to existing PR.

Completed upstream sync of web-platform-test changes at w3c/web-platform-tests#20973.

2020-01-11 01:12 UTC, pshaughn commented
Sorry about that; the new tests from upstream led me to fix an actual bug despite the time-zone and optional-seconds test inconsistencies (one of my codepaths was multiplying seconds by 3600 instead of hours)
@bors-servo try=wpt

2020-01-11 01:12 UTC, bors-servo commented
:hourglass: Trying commit 87e86c81b98f7434711897b94606faba25b1dc5d with merge 94d7c9e2ef376619061790cd626f6ffe48ae9351...

2020-01-11 02:06 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/G_HBgCscQ_2K8-40ZVRHvQ)
State: approved= try=True

2020-01-11 02:42 UTC, jdm commented
@bors-servo r+

2020-01-11 02:42 UTC, bors-servo commented
:pushpin: Commit 87e86c8 has been approved by `jdm`

<!-- @bors-servo r=jdm 87e86c81b98f7434711897b94606faba25b1dc5d -->

2020-01-11 02:42 UTC, bors-servo commented
:hourglass: Testing commit 87e86c81b98f7434711897b94606faba25b1dc5d with merge efc38de92baf724bba36ac6ba9813a5d18220ea6...

2020-01-11 04:18 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/akgN0wEmQLOcv5lYV3sTFg)

2020-01-11 04:26 UTC, jdm commented
@bors-servo retry

2020-01-11 04:26 UTC, bors-servo commented
:hourglass: Testing commit 87e86c81b98f7434711897b94606faba25b1dc5d with merge 63cb13f5fa5f52d3574eb0da883f881b52e208ff...

2020-01-11 04:35 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/KkqEE5sTQFCPafYnorCIrQ)
Approved by: jdm
Pushing 63cb13f5fa5f52d3574eb0da883f881b52e208ff to master...

2020-01-11 04:36 UTC, merged