Put correct version number in rustup version-requirement string
servo/servo pull request #25434
Opened 2020-01-05 18:33 UTC by pshaughn

Just fixing a little typo that confused me when I saw it come up.

2020-01-05 18:33 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @wafflespeanut: python/servo/command_base.py

2020-01-05 18:58 UTC, jdm requested changes

2020-01-05 18:58 UTC, jdm commented on python/servo/command_base.py
> +            print("rustup is at version %s.%s.%s, Servo requires 1.21.0 or more recent." % version)
Let's make this a variable that's used in the check as well to avoid this happening again in the future.

2020-01-05 19:20 UTC, SimonSapin commented
Ouch, I specifically thought of not making this mistake and then went on to do it. Sorry!

Also, `return 1` in this position is not effective anymore. (With this section of code having moved into another method.) Should this check failing call `sys.exit` or raise an exception instead?

2020-01-06 16:17 UTC, jdm commented
```
./python/servo/command_base.py:1039: E703 statement ends with a semicolon
```

2020-01-06 16:24 UTC, pshaughn commented
Sorry about that!

2020-01-06 16:34 UTC, jdm commented
@bors-servo r+

2020-01-06 16:34 UTC, bors-servo commented
:pushpin: Commit f80958d has been approved by `jdm`

<!-- @bors-servo r=jdm f80958d2e87d298f267f0afc8c73d8090973e4c8 -->

2020-01-06 16:34 UTC, bors-servo commented
:hourglass: Testing commit f80958d2e87d298f267f0afc8c73d8090973e4c8 with merge 8b6c1e759438f21e2072ce36eb97130dd7d0e182...

2020-01-06 18:13 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/dD6iOcjTQ4OhCxk70mwujQ)
Approved by: jdm
Pushing 8b6c1e759438f21e2072ce36eb97130dd7d0e182 to master...

2020-01-06 18:13 UTC, merged