What if we unsilence all the "Why are errors silenced here?" errors?
servo/servo pull request #25685
Opened 2020-02-04 21:23 UTC by pshaughn

This might reveal interesting race conditions, or just let us clean out some unnecessary FIXMEs.

2020-02-04 21:23 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/dom/htmldetailselement.rs, components/script/serviceworkerjob.rs, components/script/dom/htmlmediaelement.rs and 5 more
 * @kichjang: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/script/dom/htmldetailselement.rs, components/script/serviceworkerjob.rs, components/script/dom/htmlmediaelement.rs and 5 more

2020-02-04 21:23 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2020-02-04 21:23 UTC, pshaughn commented
@bors-servo try=wpt

2020-02-04 21:23 UTC, bors-servo commented
:hourglass: Trying commit b042c7d6657163dfe74c58e79d29cdc7d1169712 with merge e23a3773d8b255db3a6b9a37a20fdc85b9599881...

2020-02-04 21:42 UTC, pshaughn commented
@bors-servo try=wpt

2020-02-04 21:43 UTC, bors-servo commented
:hourglass: Trying commit 51ccbf1cffa03d5d1850f5be77971cb660b0f184 with merge dadfc407fcdcba64edbcb81b604534a5a3e5d660...

2020-02-04 22:25 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/IcPS2_NXRPGFxWjDJzwS0A)

2020-02-04 22:28 UTC, pshaughn commented
Just a regular reftest intermittent.

2020-02-13 22:58 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #25488) made this pull request unmergeable. Please resolve the merge conflicts.

2020-02-24 23:32 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #25345) made this pull request unmergeable. Please resolve the merge conflicts.

2020-02-26 03:43 UTC, gterzian requested changes
I think this is a good idea, with the exception of task queuing done from the IPC router thread, because currently there is no guarantee that it shutdowns before the window event-loops, or other threads, that use it(while queuing a task from a task should indeed normally work). 

I will actually open a PR in https://github.com/servo/ipc-channel/ that wil add an explicit shutdown mechanism, and then open a PR here that uses it to shutdown this IPC router thread as part of the overall shutdown workflow, and then it would be a good idea to have to those assertions on the IPC thread as well. 

FYI the calls from the IPC router thread are made by thos `_Context` structs, since they are used as part of `ROUTER.add_route`, and in the spec they will usually be identified as task queued from "in parallel" steps(but not always).

2020-02-26 03:43 UTC, gterzian commented on components/script/dom/eventsource.rs
> +        global
This is called from the IPC router thread, and I wouldn't assert here unless we add some guarantees that it is shutdown when the other threads in the process shutdown.

2020-02-26 03:43 UTC, gterzian commented on components/script/dom/eventsource.rs
> +        global
ditto

2020-02-26 03:43 UTC, gterzian commented on components/script/dom/eventsource.rs
> +        global
ditto

2020-02-26 03:43 UTC, gterzian commented on components/script/dom/window.rs
> +                self.script_chan
This can actually be replaced by the syntax using `dom_manipulation_task_source`

2020-02-26 03:43 UTC, gterzian commented on components/script/dom/window.rs
> +        self.script_chan
This can also use the `dom_manipulation_task_source` syntax.

2020-02-26 03:57 UTC, jdm commented
I agree with gterzian!

2020-03-26 03:58 UTC, gterzian commented
After this https://github.com/servo/servo/pull/26036 we can actually move forward with this one!

2020-03-31 04:18 UTC, gterzian commented on components/script/dom/window.rs
> +                self.script_chan
This comment is still relevant

2020-03-31 04:18 UTC, gterzian commented on components/script/dom/window.rs
> +        self.script_chan
This comment is still relevant

2020-03-31 04:19 UTC, gterzian commented
Ok so now that we're shutting down the IPC router, this one is basically good to go I think. 

There are two comments that I noted are still relevant, not completely related but we might as well do it here...

2025-01-03 14:41 UTC, mrobinson commented on components/script/dom/eventsource.rs
> +        global
I think that after #34827 we will be able to handle this case by not queuing the task if the canceller has been canceled and just ensure that all cancellers are canceled before the `GlobalScope` is dropped.

2025-01-06 15:10 UTC, mrobinson commented
Closing this in favor of #34849.

2025-01-06 15:10 UTC, closed without merging

2025-01-07 12:56 UTC, pshaughn commented on components/script/dom/document.rs
> +        // FIXME: Why are we silencing errors here? Is it really okay to return
I'm not really involved with this project anymore, and please forgive me if I'm just making unproductive noise, but I notice this observation here wasn't brought up in #34849 and I never did find out whether or not it was meaningful.

2025-01-07 13:14 UTC, mrobinson commented on components/script/dom/document.rs
> +        // FIXME: Why are we silencing errors here? Is it really okay to return
Good point. There are more cases where we are silencing errors where it might not make sense. This might happen if, for instance, the resource thread ended unexpectedly. We need to think more deeply about what should happen in those kind of cases.