Remove dependency of constellation on canvas
servo/servo pull request #25694
Opened 2020-02-05 18:24 UTC by kunalmohan

move `ConstellationCanvasMsg` to canvas_traits and start canvas paint thread
to components/servo. This, however, does not remove dependency for conditional
compilation options.

---

- [X] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [X] These changes fix #24891  (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2020-02-05 18:24 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/constellation.rs
 * @cbrewster: components/constellation/constellation.rs

2020-02-05 19:41 UTC, Manishearth requested changes
We should actually remove the dependency and then do the feature threading in libservo instead.

2020-02-05 20:29 UTC, kunalmohan commented
I am a bit new to this, so would need a bit more information/guidance. Are you suggesting `libservo/canvas2d-azure` under features instead?

2020-02-05 21:28 UTC, kunalmohan commented
I just found that `libservo/canvas2d-azure` isn't possible since it would create a cyclic dependency.

2020-02-05 23:42 UTC, Manishearth commented
@kunalmohan no, in the libservo crate we add `canvas2d-azure = ["canvas/canvas2d-azure"]` as a feature

2020-02-06 02:34 UTC, kunalmohan commented
Oh, ok. That's already done in libservo. I guess that's what confused me a bit. I'll just remove the features section under `constellation/Cargo.toml` then.

2020-02-06 17:10 UTC, Manishearth commented
Yep

2020-02-06 17:11 UTC, Manishearth commented
@bors-servo r+

2020-02-06 17:11 UTC, bors-servo commented
:pushpin: Commit a4ba333 has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth a4ba33376a86775c4bef43fec8f8301a6a3fa113 -->

2020-02-06 17:11 UTC, bors-servo commented
:hourglass: Testing commit a4ba33376a86775c4bef43fec8f8301a6a3fa113 with merge 3a7fb48463cea83aa382375fb6ce91fc8d1391b5...

2020-02-06 17:34 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/TRHSiFm7SNmg6Ujq3YAOWw)

2020-02-06 18:27 UTC, Manishearth commented
@bors-servo retry

 - network issue

2020-02-06 18:27 UTC, bors-servo commented
:hourglass: Testing commit a4ba33376a86775c4bef43fec8f8301a6a3fa113 with merge c67b3d71e23f10ba2049bdd9aed822b19ed8527f...

2020-02-06 18:53 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/e51qo3IdSIqPtnLGv_HLwg)
Approved by: Manishearth
Pushing c67b3d71e23f10ba2049bdd9aed822b19ed8527f to master...

2020-02-06 18:53 UTC, merged