Add profiling to WebXR
servo/servo pull request #25810
Opened 2020-02-20 01:41 UTC by Manishearth

Part of https://github.com/servo/webxr/issues/128

Depends on https://github.com/servo/webxr/pull/131

r? @jdm

2020-02-20 01:41 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/document.rs, components/script/Cargo.toml, components/script/dom/xrsession.rs
 * @kichjang: components/script/dom/document.rs, components/script/Cargo.toml, components/script/dom/xrsession.rs

2020-02-20 01:41 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2020-02-20 17:02 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #25809) made this pull request unmergeable. Please resolve the merge conflicts.

2020-02-20 21:39 UTC, jdm requested changes

2020-02-20 21:39 UTC, jdm commented on components/canvas/webgl_thread.rs
> +        println!("WEBXR PROFILING [swap request]:\t{}ms", (start_swap - _sent_time) as f64 / 1_000_000.);
Let's define another `to_ms` function in canvas_traits to avoid repeating this calculation.

2020-02-20 21:39 UTC, jdm commented on components/script/dom/document.rs
> +            .send(WebGLMsg::SwapBuffers(dirty_context_ids, sender, 0))
Let's send a real time here; having 0 kept giving me weird output I had to ignore.

2020-02-22 16:13 UTC, Manishearth commented
@bors-servo r=jdm

2020-02-22 16:13 UTC, bors-servo commented
:pushpin: Commit b39bcab has been approved by `jdm`

<!-- @bors-servo r=jdm b39bcab92750b1088800ccd9337571a9805d4180 -->

2020-02-22 16:13 UTC, bors-servo commented
:hourglass: Testing commit b39bcab92750b1088800ccd9337571a9805d4180 with merge 5e542f58187249f0f3b601f3a7bea5825582d3f6...

2020-02-22 16:29 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/U1Ocg0ITSke3J_E7gqqdQw)

2020-02-22 16:50 UTC, jdm commented
./ports/libsimpleservo/capi/Cargo.toml:52: trailing whitespace

2020-02-22 23:01 UTC, Manishearth commented
@bors-servo r=jdm

2020-02-22 23:01 UTC, bors-servo commented
:pushpin: Commit e1b9b98 has been approved by `jdm`

<!-- @bors-servo r=jdm e1b9b98cd7fbfc900a474684d37abf6a0639e185 -->

2020-02-22 23:01 UTC, bors-servo commented
:hourglass: Testing commit e1b9b98cd7fbfc900a474684d37abf6a0639e185 with merge 329b1f9c8ece4127cc1e5e01c1385651221f510a...

2020-02-22 23:16 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/bYb_nnzFQmal1RbrsQBNxg)

2020-02-23 06:00 UTC, Manishearth commented
@bors-servo r=jdm

2020-02-23 06:00 UTC, bors-servo commented
:pushpin: Commit f3e1aba has been approved by `jdm`

<!-- @bors-servo r=jdm f3e1aba4e3bc1f715cebdca3d00734ab29b63d9b -->

2020-02-23 06:00 UTC, bors-servo commented
:hourglass: Testing commit f3e1aba4e3bc1f715cebdca3d00734ab29b63d9b with merge b6cd626ffec64e922a14e6464c8059a37e549018...

2020-02-23 06:51 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/ecvBfiiETgy1zxa6AB4iag)

2020-02-23 08:21 UTC, Manishearth commented
@bors-servo retry

 - https://github.com/servo/servo/issues/25513

2020-02-23 08:21 UTC, bors-servo commented
:hourglass: Testing commit f3e1aba4e3bc1f715cebdca3d00734ab29b63d9b with merge bc882fc73a3529255a9bab6177d76c0ab292601b...

2020-02-23 09:03 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/ZCY5J5zzR5e7KrsyQ9vM_Q)

2020-02-23 13:55 UTC, jdm commented
@bors-servo retry

2020-02-23 13:55 UTC, bors-servo commented
:hourglass: Testing commit f3e1aba4e3bc1f715cebdca3d00734ab29b63d9b with merge 6bc4a7df24df6c7ed41f2ee4c2d38a282760c2b6...

2020-02-23 14:15 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/a4TufbvbRP6DvMEAkoNd1A)
Approved by: jdm
Pushing 6bc4a7df24df6c7ed41f2ee4c2d38a282760c2b6 to master...

2020-02-23 14:15 UTC, merged

2020-02-23 14:27 UTC, nox commented
I suspect some sort of ABI issue on Windows with `GetPropertyKeys`.