Update ANGLE and UWP toolchain version
servo/servo pull request #25944
Opened 2020-03-10 23:23 UTC by Manishearth

I've been working with these patches applied for a while, they seem to work great.

r? @jdm

2020-03-10 23:31 UTC, jdm requested changes

2020-03-10 23:31 UTC, jdm commented on support/hololens/ServoApp/DefaultUrl.h
> +#define DEFAULT_URL L"https://manishearth.net/sand/vr.html"
Revert this?

2020-03-11 22:12 UTC, Manishearth commented on support/hololens/ServoApp/DefaultUrl.h
> +#define DEFAULT_URL L"https://manishearth.net/sand/vr.html"
oops, done

2020-03-11 22:47 UTC, jdm commented
@bors-servo r+

2020-03-11 22:47 UTC, bors-servo commented
:pushpin: Commit 991eaea has been approved by `jdm`

<!-- @bors-servo r=jdm 991eaea7114a58bed0ae6fd1a383968b80b29d97 -->

2020-03-11 22:47 UTC, bors-servo commented
:hourglass: Testing commit 991eaea7114a58bed0ae6fd1a383968b80b29d97 with merge cf6f2b3645d4c4145e94be45381e1616636e3d7b...

2020-03-12 08:43 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/SO6Ul__UQuar5sPNmLk2mg)

2020-03-12 14:02 UTC, CYBAI commented
```
Build started 3/12/2020 8:43:13 AM.
     1>Project "c:\users\task_1~1\appdata\local\temp\tmpewsqbc" on node 1 (default targets).
     1>Project "c:\users\task_1~1\appdata\local\temp\tmpewsqbc" (1) is building "C:\Users\task_1584001125\repo\support\hololens\ServoApp.sln" (2) on node 1 (Build target(s)).
     2>ValidateSolutionConfiguration:
         Building solution configuration "Debug|arm64".
     2>Project "C:\Users\task_1584001125\repo\support\hololens\ServoApp.sln" (2) is building "C:\Users\task_1584001125\repo\support\hololens\ServoApp\ServoApp.vcxproj" (3) on node 1 (default targets).
     3>C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\task_1584001125\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>Done Building Project "C:\Users\task_1584001125\repo\support\hololens\ServoApp\ServoApp.vcxproj" (default targets) -- FAILED.
     2>Done Building Project "C:\Users\task_1584001125\repo\support\hololens\ServoApp.sln" (Build target(s)) -- FAILED.
     1>Done Building Project "c:\users\task_1~1\appdata\local\temp\tmpewsqbc" (default targets) -- FAILED.
Build FAILED.
       "c:\users\task_1~1\appdata\local\temp\tmpewsqbc" (default target) (1) ->
       "C:\Users\task_1584001125\repo\support\hololens\ServoApp.sln" (Build target) (2) ->
       "C:\Users\task_1584001125\repo\support\hololens\ServoApp\ServoApp.vcxproj" (default target) (3) ->
       (_CheckWindowsSDKInstalled target) -> 
         C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\task_1584001125\repo\support\hololens\ServoApp\ServoApp.vcxproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:00.36
```

2020-03-13 00:10 UTC, Manishearth commented on support/hololens/ServoApp/ServoApp.vcxproj
> +    <WindowsTargetPlatformVersion Condition=" '$(WindowsTargetPlatformVersion)' == '' ">10.0</WindowsTargetPlatformVersion>
hmm, this was autogenerated by VS. But it should be 10.0.18something

2020-03-13 15:53 UTC, jdm commented
I'm building a new AMI that installs the newest SDK.

2020-03-13 16:29 UTC, jdm commented
@bors-servo try=windows

2020-03-13 16:32 UTC, jdm commented
@bors-servo r- retry

2020-03-13 16:32 UTC, bors-servo commented
:hourglass: Trying commit 991eaea7114a58bed0ae6fd1a383968b80b29d97 with merge 44c0de8fc414c4f49d6cb4fc13223efbbfe78c75...

2020-03-13 16:35 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/K1JKKEt4QgC1st3Id45pNA)

2020-03-13 16:46 UTC, jdm commented
@bors-servo retry

2020-03-13 16:46 UTC, bors-servo commented
:hourglass: Trying commit 991eaea7114a58bed0ae6fd1a383968b80b29d97 with merge 8114915957f7a12ef469470580310079a58ac1e7...

2020-03-13 16:50 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/IXMqaxXzQMaglKMHcuNQLg)

2020-03-13 17:50 UTC, jdm commented
@bors-servo retry

2020-03-13 17:50 UTC, bors-servo commented
:hourglass: Trying commit 991eaea7114a58bed0ae6fd1a383968b80b29d97 with merge eac18f2a99a393ff742f87c858942c2e5876eb0d...

2020-03-13 18:16 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/G-RvbP0zR3OuiIg19HpqIQ)

2020-03-13 18:19 UTC, jdm commented
Same issue with the 10.18whatever SDK explicitly installed in the windows AMI. I recommend modifying that 10.0 by hand to match the min version.

2020-03-16 04:58 UTC, Manishearth commented
@bors-servo try=windows retry

2020-03-16 04:58 UTC, bors-servo commented
:hourglass: Trying commit fe094e3a8cafac55cf353fa9c8e1cb32fc95fa8f with merge 813ebe078fbee6f622d2316cfbbddfa5241e1c2f...

2020-03-16 05:22 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/QeN-gqTlT0upLy0aFoYo1g)

2020-03-16 16:58 UTC, Manishearth commented
```
Build started 3/16/2020 5:23:50 AM.
     1>Project "c:\users\task_1~1\appdata\local\temp\tmpdysbwd" on node 1 (default targets).
     1>Project "c:\users\task_1~1\appdata\local\temp\tmpdysbwd" (1) is building "C:\Users\task_1584321971\repo\support\hololens\ServoApp.sln" (2) on node 1 (Build target(s)).
     2>ValidateSolutionConfiguration:
         Building solution configuration "Debug|x64".
     2>Project "C:\Users\task_1584321971\repo\support\hololens\ServoApp.sln" (2) is building "C:\Users\task_1584321971\repo\support\hololens\ServoApp\ServoApp.vcxproj" (3) on node 1 (default targets).
     3>C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\task_1584321971\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>Done Building Project "C:\Users\task_1584321971\repo\support\hololens\ServoApp\ServoApp.vcxproj" (default targets) -- FAILED.
     2>Done Building Project "C:\Users\task_1584321971\repo\support\hololens\ServoApp.sln" (Build target(s)) -- FAILED.
     1>Done Building Project "c:\users\task_1~1\appdata\local\temp\tmpdysbwd" (default targets) -- FAILED.
```

@jdm  we still need this installed it seems

2020-03-17 03:04 UTC, jdm commented
@bors-servo retry

2020-03-17 03:04 UTC, bors-servo commented
:hourglass: Trying commit fe094e3a8cafac55cf353fa9c8e1cb32fc95fa8f with merge 3c6c57cc0569111505def1fce002eaea291585e9...

2020-03-17 03:27 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/XLZIk8bNRV279BcHBjXEfQ)

2020-03-17 04:10 UTC, Manishearth commented
```
Build started 3/17/2020 3:27:09 AM.
     1>Project "c:\users\tab7f6~1\appdata\local\temp\tmpi0qn00" on node 1 (default targets).
     1>Project "c:\users\tab7f6~1\appdata\local\temp\tmpi0qn00" (1) is building "C:\Users\task_1584405424\repo\support\hololens\ServoApp.sln" (2) on node 1 (Build target(s)).
     2>ValidateSolutionConfiguration:
         Building solution configuration "Debug|arm64".
     2>Project "C:\Users\task_1584405424\repo\support\hololens\ServoApp.sln" (2) is building "C:\Users\task_1584405424\repo\support\hololens\ServoApp\ServoApp.vcxproj" (3) on node 1 (default targets).
     3>C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\task_1584405424\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>Done Building Project "C:\Users\task_1584405424\repo\support\hololens\ServoApp\ServoApp.vcxproj" (default targets) -- FAILED.
     2>Done Building Project "C:\Users\task_1584405424\repo\support\hololens\ServoApp.sln" (Build target(s)) -- FAILED.
     1>Done Building Project "c:\users\tab7f6~1\appdata\local\temp\tmpi0qn00" (default targets) -- FAILED.
```

same error

2020-03-17 13:14 UTC, jdm commented
@bors-servo retry

2020-03-17 13:14 UTC, bors-servo commented
:hourglass: Trying commit fe094e3a8cafac55cf353fa9c8e1cb32fc95fa8f with merge ed60de8475837c2cb06fd41143598a5da0e8c2bf...

2020-03-17 13:44 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/NDE3pvaQS_G9QB7ThTss5A)

2020-03-17 17:12 UTC, Manishearth commented
same error again

2020-04-19 01:32 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #25853) made this pull request unmergeable. Please resolve the merge conflicts.

2020-04-20 05:51 UTC, Manishearth commented
@bors-servo try

2020-04-20 05:51 UTC, bors-servo commented
:hourglass: Trying commit 3e8a01f5a297c5e4c240ee48ec8ef01a7f6a0d2b with merge 75a5ef6bb3acd0e49eb7585008f84f4806fb8f60...

2020-04-20 06:19 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/U5VGY1J9Rk6vLGfelYVfNg)

2020-04-20 14:59 UTC, jdm commented
I'm going to try upgrading CI to use VS 2019 and give this another shot.

2020-04-20 16:45 UTC, Manishearth commented
Oh! Yeah, I think this toolchain may not exist in VS 2017

2020-04-20 17:51 UTC, jdm commented
@bors-servo try=windows retry

2020-04-20 17:51 UTC, bors-servo commented
:hourglass: Trying commit 3e8a01f5a297c5e4c240ee48ec8ef01a7f6a0d2b with merge 3832fd31c6ed45792124bb302eae4cc3b7042b46...

2020-04-20 18:22 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/IibPZ3vfS5GXMGMhEWcSsw)

2020-04-20 18:26 UTC, Manishearth commented
```
     3>C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(777,5): error : The OutputPath property is not set for project 'ServoApp.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='ARM64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\task_1587405298\repo\support\hololens\ServoApp\ServoApp.vcxproj]
```

huh

2020-04-20 18:28 UTC, jdm commented
```
         Building solution configuration "Debug|arm64".
     2>Project "C:\Users\task_1587405298\repo\support\hololens\ServoApp.sln" (2) is building "C:\Users\task_1587405298\repo\support\hololens\ServoApp\ServoApp.vcxproj" (3) on node 1 (default targets).
     3>C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(777,5): error : The OutputPath property is not set for project 'ServoApp.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='ARM64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\task_1587405298\repo\support\hololens\ServoApp\ServoApp.vcxproj]
   
```
That's a new failure! Progress?

2020-04-20 19:01 UTC, jdm commented
It's a failure that's present on master with the new AMI, so I'm trying to fix it in https://github.com/servo/servo/pull/26234.

2020-04-20 22:34 UTC, jdm commented
@bors-servo retry

2020-04-20 22:34 UTC, bors-servo commented
:hourglass: Trying commit 3e8a01f5a297c5e4c240ee48ec8ef01a7f6a0d2b with merge 74ee83c0f50021fcb2006757d83f86f4658c9e64...

2020-04-20 23:22 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/OV4ZfDEBTnGTwDpf9T3__Q)
State: approved= try=True

2020-04-20 23:22 UTC, jdm commented
@bors-servo r+

2020-04-20 23:22 UTC, bors-servo commented
:pushpin: Commit 3e8a01f has been approved by `jdm`

<!-- @bors-servo r=jdm 3e8a01f5a297c5e4c240ee48ec8ef01a7f6a0d2b -->

2020-04-21 00:28 UTC, bors-servo commented
:hourglass: Testing commit 3e8a01f5a297c5e4c240ee48ec8ef01a7f6a0d2b with merge f99bbcfe408bc490609f98f0eb3db39343109c0b...

2020-04-21 01:17 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/L82cSkRmQ_uVkdkZ9EMA1g)

2020-04-21 01:30 UTC, Manishearth commented
@bors-servo retry

 - #25513

2020-04-21 01:32 UTC, bors-servo commented
:hourglass: Testing commit 3e8a01f5a297c5e4c240ee48ec8ef01a7f6a0d2b with merge 61275d8d948e6034386f4c555d1a7bf4ca80b40d...

2020-04-21 01:44 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/b0kvtbnjQ6KiWV48SWU3_Q)
Approved by: jdm
Pushing 61275d8d948e6034386f4c555d1a7bf4ca80b40d to master...

2020-04-21 01:44 UTC, merged