Removed createTouch and createTouchList
servo/servo pull request #26017
Opened 2020-03-23 17:54 UTC by humancalico

One thing I need to ask is that do these also needs to be removed from `/tests/wpt/web-platform-tests/touch-events/historical.html` & `tests/wpt/webgl/tests/deqp/temp_externs/iphone.js`?

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25978

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2020-03-23 17:55 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webidls/Document.webidl, components/script/dom/document.rs
 * @kichjang: components/script/dom/webidls/Document.webidl, components/script/dom/document.rs

2020-03-23 17:55 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify script code, but no tests are modified. Please consider adding a test!

2020-03-23 18:22 UTC, jdm commented
@bors-servo try=wpt

2020-03-23 18:22 UTC, bors-servo commented
:hourglass: Trying commit 1e6380ee5a8b86525e4968879e273c75519427f2 with merge 6e999ee27b7575b63f25b03c3dff00759e76f544...

2020-03-23 19:26 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/QImG-RheT5Se3bTamVOFiQ)

2020-03-23 19:38 UTC, jdm commented
We correctly pass the test that verifies that these APIs don't exist now:
```
  ▶ Unexpected subtest result in /touch-events/historical.html:
  └ PASS [expected FAIL] Document::createTouch
  ▶ Unexpected subtest result in /touch-events/historical.html:
  └ PASS [expected FAIL] Document::createTouchList
```
Please [update the test results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) for these tests in tests/wpt/metadata/touch-events/historical.html.ini!

2020-03-23 20:15 UTC, jdm requested changes

2020-03-23 20:15 UTC, jdm commented on tests/wpt/metadata/touch-events/historical.html.ini
> -    expected: FAIL
Both of these lines can be removed instead.

2020-03-23 20:15 UTC, jdm commented on tests/wpt/metadata/touch-events/historical.html.ini
> +    expected: PASS
Same here.

2020-03-23 21:18 UTC, humancalico commented
@jdm Can you have a look at it now?

2020-03-23 21:26 UTC, jdm commented
Looks good! Please squash them into a single commit and we'll merge them!

2020-03-23 22:26 UTC, jdm commented
@bors-servo r+
Thanks!

2020-03-23 22:26 UTC, bors-servo commented
:pushpin: Commit 2e1009d has been approved by `jdm`

<!-- @bors-servo r=jdm 2e1009da75fad35f19d747e37822f78b21dcd8e0 -->

2020-03-23 22:26 UTC, bors-servo commented
:hourglass: Testing commit 2e1009da75fad35f19d747e37822f78b21dcd8e0 with merge 21cccbccb6ef42d929d4e19c7c9eece762251210...

2020-03-23 23:20 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/QTM2DsdFQwmbTe_ZshHOkw)

2020-03-24 00:56 UTC, jdm commented
@bors-servo retry
#23290

2020-03-24 02:00 UTC, bors-servo commented
:hourglass: Testing commit 2e1009da75fad35f19d747e37822f78b21dcd8e0 with merge 28bcbd61a3959df80a85f5727f6d6dfd868d3878...

2020-03-24 02:47 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/bAZ7bWJRTZuf06Z5wvCONA)

2020-03-24 02:57 UTC, jdm commented
@bors-servo retry
#26020 #23290

2020-03-24 02:57 UTC, bors-servo commented
:hourglass: Testing commit 2e1009da75fad35f19d747e37822f78b21dcd8e0 with merge 945a8b7145a392d82958734c74be4f610563f885...

2020-03-24 03:12 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/IzRHM4ZHQpKbIUM3y6skKA)

2020-03-24 05:38 UTC, CYBAI commented
@bors-servo retry

- #25513

2020-03-24 05:38 UTC, bors-servo commented
:hourglass: Testing commit 2e1009da75fad35f19d747e37822f78b21dcd8e0 with merge 8b4d7c41aee9907318bee1be37b386b7414ea0a5...

2020-03-24 05:39 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/dP2VMsShQIezL298SZD_jQ)
Approved by: jdm
Pushing 8b4d7c41aee9907318bee1be37b386b7414ea0a5 to master...

2020-03-24 05:39 UTC, merged