[WIP] Implement WebGL depth texture
servo/servo pull request #26052
Opened 2020-03-28 01:02 UTC by ivanshen

As per https://github.com/servo/servo/issues/22796
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2020-03-28 01:02 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @asajeffrey (or someone else) soon.

2020-03-28 01:02 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/webgl_extensions/extensions.rs, components/script/dom/webgl_extensions/ext/mod.rs, components/script/dom/webglframebuffer.rs, components/script/dom/webglrenderingcontext.rs, components/script/dom/webgl_validations/tex_image_2d.rs and 2 more
 * @kichjang: components/script/dom/webgl_extensions/extensions.rs, components/script/dom/webgl_extensions/ext/mod.rs, components/script/dom/webglframebuffer.rs, components/script/dom/webglrenderingcontext.rs, components/script/dom/webgl_validations/tex_image_2d.rs and 2 more

2020-03-28 01:06 UTC, ivanshen commented
@jdm I'm unsure where the implementation for the [error conditions from depth texture](https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/) go. This is what I have so far. Would you be able to give me feedback on what I have?

2020-04-27 22:18 UTC, jdm requested changes
To answer your question about the error conditions, I would expect to see them in the TexImage2D and other methods. Almost all of them are checks against the parameters that are passed in.

2020-04-27 22:18 UTC, jdm commented on components/script/dom/webglframebuffer.rs
> +                gl::UNSIGNED_INT_24_8,
This change does not make sense to me. What is the intention here?

2020-04-27 22:18 UTC, jdm commented on components/script/dom/webglrenderingcontext.rs
> +        if target != gl::UNSIGNED_INT_24_8 {
This also doesn't make sense. The spec says ` The framebufferTexture2D entry point is extended to accept the target parameter DEPTH_ATTACHMENT and DEPTH_STENCIL_ATTACHMENT`, which is not what's being checked.

2020-04-27 22:18 UTC, jdm commented
Sorry for missing your request for feedback @ivanshen!

2020-07-21 20:32 UTC, jdm commented
Closing due to inactivity.

2020-07-21 20:32 UTC, closed without merging