Use hash_map::Entry to save a map lookup
servo/servo pull request #26183
Opened 2020-04-14 13:50 UTC by tamird

A bit of golf noticed via https://medium.com/programming-servo/programming-servo-workers-at-your-service-db71e5943511.

r? @gterzian

2020-04-14 13:50 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/constellation.rs
 * @cbrewster: components/constellation/constellation.rs

2020-04-14 15:04 UTC, gterzian requested changes
Nice catch! 

Could we perhaps still assign the result of the match and call `send` on it? I think it would be clearer than the currently proposed `let _ = match {}.send`.

To fix the formatting, you can also do `./mach fmt`.

2020-04-14 15:04 UTC, gterzian commented on components/constellation/constellation.rs
> +        let _ = match self.sw_managers.entry(scope.origin()) {
Ok, how about assigning to something like `sw_sender`, and then using that to send the message?

2020-04-14 20:49 UTC, tamird commented
Thanks, done!

2020-04-14 23:13 UTC, tamird commented
At last, this is green.

2020-04-15 05:00 UTC, gterzian commented
Thanks!

@bors-servo r+

2020-04-15 05:00 UTC, bors-servo commented
:pushpin: Commit fac1e65 has been approved by `gterzian`

<!-- @bors-servo r=gterzian fac1e654d217c1390c62a7631931d257634635c8 -->

2020-04-15 05:00 UTC, bors-servo commented
:hourglass: Testing commit fac1e654d217c1390c62a7631931d257634635c8 with merge ce9f22a5e4974f41cad50742a08aa7fcee9042c5...

2020-04-15 06:07 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/aDLpyo2CQJmsXC2Iy8-eFA)
Approved by: gterzian
Pushing ce9f22a5e4974f41cad50742a08aa7fcee9042c5 to master...

2020-04-15 06:07 UTC, merged