Generalize the 2020 regression report to show local unexpected failures
servo/servo pull request #26437
Opened 2020-05-05 22:08 UTC by SimonSapin

Example usage:

```
./mach test-wpt --release --layout-2020 --log-raw /tmp/servo.log
./tests/wpt/reftests-report/gen.py /tmp/servo.log
firefox ./tests/wpt/reftests-report/report.html
```

Produces a report similar https://community-tc.services.mozilla.com/api/index/v1/task/project.servo.layout-2020-regressions-report/artifacts/public/regressions.html, but showing unexpected reftest failures. The CI-generated one shows Layout 2020 failures (expected or not) that succeed in Layout 2013.

2020-05-05 22:08 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @jgraham: tests/wpt/reftests-report/gen.py, tests/wpt/reftests-report/prism.js, tests/wpt/reftests-report/prism.css

2020-05-05 22:09 UTC, SimonSapin commented
r? @jdm

2020-05-05 22:39 UTC, jdm commented
@bors-servo r+

2020-05-05 22:39 UTC, bors-servo commented
:pushpin: Commit 10923ca has been approved by `jdm`

<!-- @bors-servo r=jdm 10923ca47da6cfd8de4167d46f9aa3d2105cadba -->

2020-05-05 23:15 UTC, bors-servo commented
:hourglass: Testing commit 10923ca47da6cfd8de4167d46f9aa3d2105cadba with merge 74454aeffb21efa3ee03a53107eaaaec990883c0...

2020-05-06 00:15 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/dUyq0Bh8SmKYEaZaFXK61Q)

2020-05-06 00:24 UTC, jdm commented
```
# Push to master:
Found task <from index> indexed at project.servo.<MagicMock name='mock.check_output().decode().strip().__radd__()' id='140578698698592'>
Found task <from index> indexed at project.servo.docker-image.263b6783749c63391a9ca609cff096214027bfb21b16c61e851197f068cd8def
Scheduled b'<new id>': Linux x64: Upload docs to GitHub Pages
Traceback (most recent call last):
  File "./etc/taskcluster/mock.py", line 61, in <module>
    decision_task.main("github-push")
  File "/repo/etc/taskcluster/decision_task.py", line 15, in main
    tasks(task_for)
  File "/repo/etc/taskcluster/decision_task.py", line 71, in tasks
    function()
  File "/repo/etc/taskcluster/decision_task.py", line 268, in layout_2020_regressions_report
    .with_index_at("layout-2020-regressions-report")
AttributeError: 'NoneType' object has no attribute 'create'
Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
etc/taskcluster/decision_task.py     184     36    80%   73-98, 149, 287-293, 347, 394, 398, 414, 443, 462-463, 690-697, 801
etc/taskcluster/decisionlib.py       318      6    98%   77-78, 471-472, 485-486
etc/taskcluster/mock.py               38      7    82%   63-72
----------------------------------------------------------------
TOTAL                                540     49    91%
[taskcluster 2020-05-06 00:15:14.434Z] === Task Finished ===
```

2020-05-06 00:24 UTC, jdm requested changes

2020-05-06 00:24 UTC, jdm commented on etc/taskcluster/decisionlib.py
> +        self.routes.append("index.%s.%s" % (CONFIG.index_prefix, index_path))
This needs to return self.

2020-05-07 05:05 UTC, SimonSapin commented
Indeed, that fixes running `mock.py`. Thanks!

@bors-servo r=jdm

2020-05-07 05:05 UTC, bors-servo commented
:pushpin: Commit f524363 has been approved by `jdm`

<!-- @bors-servo r=jdm f524363667949e3ed300609eb711ee3ddd1a4f6e -->

2020-05-07 05:05 UTC, bors-servo commented
:hourglass: Testing commit f524363667949e3ed300609eb711ee3ddd1a4f6e with merge 856f03ae7595e90b86d6f1c7b64fae1f9f3aa95a...

2020-05-07 06:09 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/PkjF_PW7SCKRBjy4Zfv0lg)
Approved by: jdm
Pushing 856f03ae7595e90b86d6f1c7b64fae1f9f3aa95a to master...

2020-05-07 06:09 UTC, merged