Switch to single WebGPU thread
servo/servo pull request #26493
Opened 2020-05-12 13:02 UTC by kunalmohan

Replace the current-one thread per host in a browsing context group-implementation to a single thread across the browser. Remove some garbage code in request adapter on wgpu server-side.

r?@kvark @jdm 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2020-05-12 13:02 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/constellation/constellation.rs
 * @cbrewster: components/constellation/constellation.rs

2020-05-12 14:20 UTC, jdm requested changes
These changes generally look fine to me!

2020-05-12 14:20 UTC, jdm commented on components/constellation/constellation.rs
>          };
I don't understand the purpose of this change. If we only handle one message, we should make this method only accept the values we need from that message and make the caller deal with that. If we intend to accept more messages, we should accept an enum of only those valid messages.

2020-05-13 17:00 UTC, kunalmohan commented
Closing because this is no longer needed.

2020-05-13 17:00 UTC, closed without merging