[WIP] Introduce import.meta hook for module script
servo/servo pull request #26544
Opened 2020-05-16 05:32 UTC by CYBAI

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #26542
- [x] There are tests for these changes under `module/import-meta` folder.

2020-05-16 05:32 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/script_module.rs
 * @jgraham: tests/wpt/include.ini
 * @kichjang: components/script/script_module.rs

2020-05-16 05:32 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2020-05-16 05:32 UTC, CYBAI commented
r? @jdm

2020-05-16 05:34 UTC, CYBAI commented on components/script/script_module.rs
> +    )
@jdm I've followed Gecko to use those functions from mozjs but I still can't pass the import meta test which means the `import.meta` doesn't have the `url` attribute.

Do I miss something to set the property 🤔?

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/6782666/82111754-3ccf9080-9782-11ea-89f0-c3a75a5b348b.png">

2020-05-16 14:03 UTC, jdm requested changes
Ensuring the resulting strings don't contain random memory should help!

2020-05-16 14:03 UTC, jdm commented on components/script/script_module.rs
> +    rooted!(in(cx) let url_string = JS_NewStringCopyZ(cx, base_url.as_str().as_ptr() as *const i8));
JS_NewStringCopyZ requires the string to be null-terminated, so we should either use CString here or JS_NewStringCopyN so we can pass the length.

2020-05-17 01:40 UTC, CYBAI commented
@jdm fixing with what you pointed out, we can pass the test now!

> Ensuring the resulting strings don't contain random memory should help!

but, I still don't understand what you mean for `contain random memory` here 🤔 
does that mean, while using `JS_NewStringCopyZ`, it's possible to return an empty string which might cause different memory in each run?

btw, how can I know when I'll need a null-terminated string 🤔 ? thanks!

2020-05-17 02:26 UTC, jdm commented
If an API expects a null-terminated string and we pass a string constant without one, whatever values are present in memory following the string contents will be included until there's a null value encountered. That's why the test failed, because we ended setting a property named something like "urlZzta3#';(84, x?&".

In general, any C aoi that accepts a chat* argument that is intended to be a name or string value should be null terminated unless there's a length argument included. In the string copy API in particular, the Z suffix stands for "zero", which means null-terminated. The N suffix stands for "length" and accepts an argument that includes an end pointer.

2020-05-17 02:28 UTC, jdm commented
I suspect this needs a fmt, but otherwise it looks fine.

2020-05-17 02:31 UTC, CYBAI commented
> If an API expects a null-terminated string and we pass a string constant without one, whatever values are present in memory following the string contents will be included until there's a null value encountered. That's why the test failed, because we ended setting a property named something like "urlZzta3#';(84, x?&".
> 
> In general, any C aoi that accepts a chat* argument that is intended to be a name or string value should be null terminated unless there's a length argument included. In the string copy API in particular, the Z suffix stands for "zero", which means null-terminated. The N suffix stands for "length" and accepts an argument that includes an end pointer.

I see! That's very clear and I understand now! Thanks! :D

> I suspect this needs a fmt, but otherwise it looks fine.

Wait me a minute! Looks like I need to upgrade my local fmt 🤔

2020-05-17 02:31 UTC, CYBAI commented
oh, it's not a fmt error from rustfmt :P

2020-05-17 12:31 UTC, jdm commented
@bors-servo r+

2020-05-17 12:31 UTC, bors-servo commented
:pushpin: Commit 6bc6240 has been approved by `jdm`

<!-- @bors-servo r=jdm 6bc624001bf124921e337b8e67d5238cc147744d -->

2020-05-17 12:31 UTC, bors-servo commented
:hourglass: Testing commit 6bc624001bf124921e337b8e67d5238cc147744d with merge 5a99b5e22b1bd011afecd655546b8a9f2cfc7b31...

2020-05-17 13:08 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/FVEduwmXRH-6W3j28ly0wg)

2020-05-17 13:57 UTC, jdm commented
@bors-servo retry
#24622

2020-05-17 14:29 UTC, bors-servo commented
:hourglass: Testing commit 6bc624001bf124921e337b8e67d5238cc147744d with merge 619e0bceaf750ec862169a6a02cfbf82ba9be0a8...

2020-05-17 14:50 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/Yiot8vyDT7OommXy3yLgbw)
Approved by: jdm
Pushing 619e0bceaf750ec862169a6a02cfbf82ba9be0a8 to master...

2020-05-17 14:50 UTC, merged