Implement CanvasRenderingContext2d.fillText
servo/servo pull request #26697
Opened 2020-05-28 19:51 UTC by utsavoza

This is a draft PR attempting to resolve #11681. There are a couple of missing pieces currently, mainly the [communication between canvas paint thread and font cache thread](https://github.com/servo/servo/issues/11681#issuecomment-635306703) and the [approach to load the fonts](https://github.com/servo/servo/issues/11681#issuecomment-635382382) from its computed values in order to use it with the canvas backend.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #11681
- [ ] There are tests for these changes

2020-05-28 19:51 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @asajeffrey: components/script/dom/canvasrenderingcontext2d.rs, components/script/canvas_state.rs, components/script/dom/offscreencanvasrenderingcontext2d.rs, components/script/dom/window.rs, components/script/dom/webidls/CanvasRenderingContext2D.webidl
 * @kichjang: components/script/dom/canvasrenderingcontext2d.rs, components/script/canvas_state.rs, components/script/dom/offscreencanvasrenderingcontext2d.rs, components/script/dom/window.rs, components/script/dom/webidls/CanvasRenderingContext2D.webidl
 * @emilio: components/layout/query.rs

2020-05-28 19:51 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!
* These commits modify layout and script code, but no tests are modified. Please consider adding a test!

2020-06-06 17:05 UTC, utsavoza commented
@jdm, under what circumstances can [FontTemplateData::bytes](https://doc.servo.org/gfx/platform/freetype/font_template/struct.FontTemplateData.html#method.bytes) panic with message `No URL for Core Text font!`? I am unfamiliar with the underlying `core-text` implementation, but I am persistently seeing this issue when trying to obtain bytes from the font template for native fonts on macOS.

Although I am yet to complete the implementation, this is the relevant piece of code that triggers the panic from canvas paint thread:
```rust
let font = with_thread_local_font_context(canvas_data, |font_context| {
    let font_group = font_context.font_group(font_style);
    let font = font_group
        .borrow_mut()
        .first(font_context)
        .expect("couldn't find font");
    let mut font = font.borrow_mut();
    let bytes = font.handle.template().bytes(); // <- panics with 'No URL for Core Text font! (thread CanvasThread, at components/gfx/platform/macos/font_template.rs:143)'
    Font::from_bytes(Arc::new(bytes), 0).unwrap_or_else(load_default_system_fallback_font)
});
```

Also, I noticed we already have [an issue](https://github.com/servo/servo/issues/24622) filed with similar a panic backtrace. I am not sure if it is relevant, but my best guess would be the intermittent test failure can occur when the [font template is accessed](https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/gfx/font_cache_thread.rs#L177-L181) before/during the [web font is being fetched asynchronously](https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/gfx/font_cache_thread.rs#L200-L202) and eventually hitting:

https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/gfx/font_cache_thread.rs#L405

It would be interesting to see if setting the [`load_webfonts_synchronously`](https://github.com/servo/servo/blob/2f6efcbc3a535ed6718457b2f8ab5c78002ca09c/components/config/opts.rs#L70) config option to `true` affects the test failure in any manner.

2020-06-06 17:53 UTC, jdm commented
We already run all tests with the synchronous web fonts enabled, unfortunately.

2020-06-06 20:32 UTC, utsavoza commented
> We already run all tests with the synchronous web fonts enabled, unfortunately.

Oh, I didn't know that.

In any case, if we consider `FontTemplateData::bytes` a fallible operation, what should be the fallback behavior in case `FontTemplateData::bytes` fails to return the data in the font?

2020-06-09 12:02 UTC, jdm commented
r? @jdm

2020-06-09 21:44 UTC, jdm commented
These changes look great from a quick skim so far! Do you still need an answer to your last question? I see you're now using bytes_if_in_memory and falling back to loading a system font, which seems reasonable to me. Fantastic effort, in any case!

2020-06-09 21:44 UTC, jdm commented
@bors-servo try=wpt

2020-06-09 21:44 UTC, bors-servo commented
:hourglass: Trying commit dd9599279b4124c13ebaf4d48e548fe5316bb8a5 with merge 7051aaae9b54632b6cddd73419b073a08f7d366e...

2020-06-09 22:34 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/QkqT9gW5SkmHGORWfDb-9Q)

2020-06-10 06:59 UTC, utsavoza commented
> Do you still need an answer to your last question?

Thanks, I just needed to confirm the behavior; nevermind if the current approach seems ok.

I am pasting this here for my reference, will need to rebase the changes and update tests accordingly.

<details>
  <summary>Test results</summary>

```
▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
└ PASS [expected FAIL] CanvasRenderingContext2D interface: attribute font
▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
└ PASS [expected FAIL] CanvasRenderingContext2D interface: attribute textAlign
▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
└ PASS [expected FAIL] CanvasRenderingContext2D interface: attribute textBaseline
▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
└ PASS [expected FAIL] CanvasRenderingContext2D interface: attribute direction
▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
└ PASS [expected FAIL] CanvasRenderingContext2D interface: document.createElement("canvas").getContext("2d") must inherit property "font" with the proper type
▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
└ PASS [expected FAIL] CanvasRenderingContext2D interface: document.createElement("canvas").getContext("2d") must inherit property "textAlign" with the proper type
▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
└ PASS [expected FAIL] CanvasRenderingContext2D interface: document.createElement("canvas").getContext("2d") must inherit property "textBaseline" with the proper type
▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
└ PASS [expected FAIL] CanvasRenderingContext2D interface: document.createElement("canvas").getContext("2d") must inherit property "direction" with the proper type

▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.align.default.html:
└ PASS [expected FAIL] Canvas test: 2d.text.align.default
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.align.invalid.html:
└ PASS [expected FAIL] Canvas test: 2d.text.align.invalid
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.baseline.default.html:
└ PASS [expected FAIL] Canvas test: 2d.text.baseline.default
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.font.parse.size.percentage.html:
└ PASS [expected FAIL] Canvas test: 2d.text.font.parse.size.percentage
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.font.default.html:
└ PASS [expected FAIL] Canvas test: 2d.text.font.default
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.baseline.invalid.html:
└ PASS [expected FAIL] Canvas test: 2d.text.baseline.invalid
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.baseline.invalid.html:
└ PASS [expected FAIL] OffscreenCanvas test: 2d.text.baseline.invalid
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.font.parse.size.percentage.default.html:
└ PASS [expected FAIL] Canvas test: 2d.text.font.parse.size.percentage.default
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.align.invalid.worker.html:
└ PASS [expected FAIL] 2d
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.align.default.html:
└ PASS [expected FAIL] OffscreenCanvas test: 2d.text.align.default
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.baseline.default.html:
└ PASS [expected FAIL] OffscreenCanvas test: 2d.text.baseline.default
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.baseline.invalid.worker.html:
└ PASS [expected FAIL] 2d
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.baseline.default.worker.html:
└ PASS [expected FAIL] 2d
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.align.default.worker.html:
└ PASS [expected FAIL] 2d
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.font.relative_size.worker.html:
└ PASS [expected FAIL] 2d
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.font.parse.system.html:
└ PASS [expected FAIL] System fonts must be computed to explicit values
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.font.parse.system.html:
└ PASS [expected FAIL] System fonts must be computed to explicit values
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.font.parse.tiny.html:
│ FAIL [expected PASS] OffscreenCanvas test: 2d.text.font.parse.tiny
│   → assert_equals: ctx.font === '1px sans-serif' (got 10px sans-serif[string], expected 1px sans-serif[string]) expected "1px sans-serif" but got "10px sans-serif"
│
│ _assertSame@http://web-platform.test:8000/html/canvas/resources/canvas-tests.js:17:18
│ @http://web-platform.test:8000/html/canvas/offscreen/text/2d.text.font.parse.tiny.html:24:12
│ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
└ @http://web-platform.test:8000/html/canvas/offscreen/text/2d.text.font.parse.tiny.html:18:3
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.font.parse.tiny.worker.html:
│ FAIL [expected PASS] 2d
│   → assert_equals: ctx.font === '1px sans-serif' (got 10px sans-serif[string], expected 1px sans-serif[string]) expected "1px sans-serif" but got "10px sans-serif"
│
│ _assertSame@http://web-platform.test:8000/html/canvas/resources/canvas-tests.js:17:18
│ @http://web-platform.test:8000/html/canvas/offscreen/text/2d.text.font.parse.tiny.worker.js:20:12
│ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
└ @http://web-platform.test:8000/html/canvas/offscreen/text/2d.text.font.parse.tiny.worker.js:14:3
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.font.default.html:
└ PASS [expected FAIL] OffscreenCanvas test: 2d.text.font.default
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.font.relative_size.html:
└ PASS [expected FAIL] Canvas test: 2d.text.font.relative_size
▶ Unexpected subtest result in /html/canvas/element/text-styles/2d.text.font.parse.basic.html:
└ PASS [expected FAIL] Canvas test: 2d.text.font.parse.basic
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.align.invalid.html:
└ PASS [expected FAIL] OffscreenCanvas test: 2d.text.align.invalid
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.font.default.worker.html:
└ PASS [expected FAIL] 2d
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.font.parse.system.worker.html:
└ PASS [expected FAIL] System fonts must be computed to explicit values
▶ Unexpected subtest result in /html/canvas/offscreen/text/2d.text.font.relative_size.html:
└ PASS [expected FAIL] OffscreenCanvas test: 2d.text.font.relative_size
▶ Unexpected subtest result in /html/semantics/embedded-content/the-canvas-element/initial.reset.2dstate.html:
└ PASS [expected FAIL] Resetting the canvas state resets 2D state variables
▶ FAIL [expected PASS] /html/canvas/element/text-styles/canvas_text_font_001.htm
│   → /html/canvas/element/text-styles/canvas_text_font_001.htm 54ed3fe6baf2d8bc9bddcdb0e82725a5c568a6e6
└   → /html/canvas/element/text-styles/canvas_text_font_001-ref.htm 271b8adde3002c11379dbc7d18771d3f47b0ed33

▶ Unexpected subtest result in /html/canvas/element/the-canvas-state/2d.state.saverestore.font.html:
└ PASS [expected FAIL] save()/restore() works for font
▶ Unexpected subtest result in /html/canvas/element/the-canvas-state/2d.state.saverestore.textAlign.html:
└ PASS [expected FAIL] save()/restore() works for textAlign
▶ Unexpected subtest result in /html/canvas/element/the-canvas-state/2d.state.saverestore.textBaseline.html:
└ PASS [expected FAIL] save()/restore() works for textBaseline
```
<detai [...]

2020-06-11 16:21 UTC, jdm requested changes
Great job!

2020-06-11 16:21 UTC, jdm commented on components/style/properties/properties.mako.rs
> +        #[derive(Clone, Debug, MallocSizeOf, Serialize, Deserialize)]
Let's do this:
```rust
#[derive(Clone, Debug, MallocSizeOf)]
#[cfg_attr(feature = "servo", derive(Serialize, Deserialize))]

2020-06-11 16:21 UTC, jdm commented on components/style/values/computed/font.rs
> +    Deserialize,
Let's make this conditional on the "servo" feature.

2020-06-11 16:21 UTC, jdm commented on components/style/values/computed/font.rs
> +#[cfg_attr(feature = "servo", derive(Hash, MallocSizeOf, Serialize, Deserialize))]
Same here.

2020-06-11 16:21 UTC, jdm commented on components/style/values/computed/font.rs
> +    Deserialize,
Same here.

2020-06-11 16:21 UTC, jdm commented on components/style/values/specified/font.rs
> +    Deserialize,
Same here.

2020-06-11 16:21 UTC, jdm commented on components/style/values/specified/font.rs
> +    Deserialize,
Same here.

2020-06-12 13:02 UTC, utsavoza commented on components/canvas/canvas_data.rs
> +}
Actually, we require a mutable reference to CanvasFontContext and storing it CanvasPaintThread and passing a mutable reference in [fillText](https://github.com/servo/servo/pull/26697/files#diff-beef21ae0a52212d45bc2a499bc93eadR498-R505) method might make the borrow checker unhappy.

2020-06-12 13:18 UTC, jdm commented on components/canvas/canvas_data.rs
> +}
I'm not sure I understand why that would be a problem?

2020-06-12 13:32 UTC, utsavoza commented on components/canvas/canvas_data.rs
> +}
I think storing CanvasFontContext and getting a mutable reference will lead to multiple mutable borrows on self [here](https://github.com/servo/servo/pull/26697/files#diff-284fed15fb4a8b4f1991e2c5a9ea1139R148-R149):
```rust            
Canvas2dMsg::FillText(text, x, y, max_width, style, is_rtl) => {
    self.canvas(canvas_id).set_fill_style(style);
    self.canvas(canvas_id)
            .fill_text(text, x, y, max_width, is_rtl);
},

```
as we are calling fill_text on mutably borrowed CanvasData from CanvasPaintThread.

2020-06-12 13:51 UTC, jdm commented
@bors-servo r+

2020-06-12 13:51 UTC, bors-servo commented
:pushpin: Commit 8372cf1 has been approved by `jdm`

<!-- @bors-servo r=jdm 8372cf1bd8946ccb41d6d0aa851d977e8de33b1b -->

2020-06-12 14:35 UTC, bors-servo commented
:hourglass: Testing commit 8372cf1bd8946ccb41d6d0aa851d977e8de33b1b with merge 81ac9568dfcbed0e99f9bab453121df877b68ae0...

2020-06-12 15:19 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/fYtL17BcQLi_bmk4I8FRvg)

2020-06-12 15:51 UTC, jdm commented
@bors-servo r+

2020-06-12 15:51 UTC, bors-servo commented
:pushpin: Commit 2d646ec has been approved by `jdm`

<!-- @bors-servo r=jdm 2d646ecf2134edc01f21e34f86f837e15547b26c -->

2020-06-12 16:16 UTC, bors-servo commented
:hourglass: Testing commit 2d646ecf2134edc01f21e34f86f837e15547b26c with merge 433ee4605ba6601aa7fde53c49b8db714f8f591f...

2020-06-12 16:46 UTC, bors-servo commented
:broken_heart: Test failed - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/ZN9vYmFeRZWwwIvw46iiTQ)

2020-06-12 17:01 UTC, jdm commented
@bors-servo r+

2020-06-12 17:01 UTC, bors-servo commented
:pushpin: Commit 502f34a has been approved by `jdm`

<!-- @bors-servo r=jdm 502f34a9db36202cd89f7a1b48bd138d2ce6f46e -->

2020-06-12 17:43 UTC, bors-servo commented
:hourglass: Testing commit 502f34a9db36202cd89f7a1b48bd138d2ce6f46e with merge 721271dcd3c20db5ca8cf146e2b5907647afb4d6...

2020-06-12 18:43 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/ZY_iUQ7JQJ-X2Uxw09OmEA)
Approved by: jdm
Pushing 721271dcd3c20db5ca8cf146e2b5907647afb4d6 to master...

2020-06-12 18:43 UTC, merged