Unminify store get
servo/servo pull request #26711
Opened 2020-05-29 09:07 UTC by skrzyp1

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #26456(GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2020-05-29 09:07 UTC, highfive commented
Thanks for the pull request, and welcome! The Servo team is excited to review your changes, and you should hear from @simonsapin (or someone else) soon.

2020-05-29 09:07 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @kichjang: components/net/http_loader.rs

2020-05-29 09:07 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify net code, but no tests are modified. Please consider adding a test!

2020-06-01 13:34 UTC, jdm commented on components/script/dom/window.rs
>                      *self.unminified_js_dir.borrow_mut() =
I agree. Let's remove this code.

2020-06-01 13:35 UTC, jdm requested changes
This looks really good so far! Please squash all of the commits into one, then rebase that commit against master to remove any merge conflicts.

2020-06-02 01:50 UTC, CYBAI commented on components/script/dom/window.rs
> +            //let _ = fs::remove_dir_all(&path);
maybe should be removed if unused 👀?

2020-06-02 01:50 UTC, CYBAI commented on components/script/dom/window.rs
> +                Err(_) => warn!("Could not create unminified dir"), // for {:?}", host),
ditto.

```suggestion
                Err(_) => warn!("Could not create unminified dir"),
```

2020-06-02 15:39 UTC, servo-wpt-sync commented
Error syncing changes upstream. Logs saved in error-snapshot-1591112382232.

2020-06-02 19:32 UTC, jdm commented
@bors-servo r+

2020-06-02 19:32 UTC, bors-servo commented
:pushpin: Commit ee69064 has been approved by `jdm`

<!-- @bors-servo r=jdm ee6906443f9c60c60e38e6f6daaeb585fa886540 -->

2020-06-02 19:59 UTC, bors-servo commented
:hourglass: Testing commit ee6906443f9c60c60e38e6f6daaeb585fa886540 with merge 07369c4c681da3d72755fac14124c81136c2b636...

2020-06-02 20:58 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/UlCd6G5LRsGWTg6Mxl2NYg)
Approved by: jdm
Pushing 07369c4c681da3d72755fac14124c81136c2b636 to master...

2020-06-02 20:58 UTC, merged