UWP L10N
servo/servo pull request #26840
Opened 2020-06-10 07:53 UTC by paulrouget

Based on top of #26793.

Partially addresses #26665.

This does not cover Rust strings and resources files.

2020-06-10 07:53 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2020-06-10 15:11 UTC, jdm requested changes
Thanks for doing this!

2020-06-11 05:56 UTC, paulrouget commented
Addressed @jdm comments.

@bors-servo r=Manishearth

2020-06-11 05:56 UTC, bors-servo commented
:pushpin: Commit e5edd22 has been approved by `Manishearth`

<!-- @bors-servo r=Manishearth e5edd22208f5e59ef320482e991c96676c9b4967 -->

2020-06-11 06:12 UTC, bors-servo commented
:hourglass: Testing commit e5edd22208f5e59ef320482e991c96676c9b4967 with merge 10202c2ad28933f92d85501b5c2f5f7d5441c5cb...

2020-06-11 07:08 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/bpz4m06NR1KpE4-YH3rhrQ)
Approved by: Manishearth
Pushing 10202c2ad28933f92d85501b5c2f5f7d5441c5cb to master...

2020-06-11 07:08 UTC, merged