devtools: TabDescription actor
servo/servo pull request #27229
Opened 2020-07-10 10:52 UTC by paulrouget

We could do better by creating the browsing context actor lazily, but that's good enough to re-enable devtools with a recent version of Firefox. fix #27113.

2020-07-10 14:48 UTC, jdm requested changes
Thanks for investigating this!

2020-07-10 14:48 UTC, jdm commented on components/devtools/actors/tab.rs
> +    pub url: RefCell<String>,
Rather than duplicating this data in TabDescriptorActor and BrowsingContextActor, could we choose one of them?

2020-07-13 09:47 UTC, paulrouget commented
@jdm that's probably a better approach.

2020-07-13 13:15 UTC, jdm commented
@bors-servo r+

2020-07-13 13:15 UTC, bors-servo commented
:pushpin: Commit da80d4f has been approved by `jdm`

<!-- @bors-servo r=jdm da80d4ff01e2554a7a072e136531eb40c2e5eff6 -->

2020-07-13 13:15 UTC, bors-servo commented
:hourglass: Testing commit da80d4ff01e2554a7a072e136531eb40c2e5eff6 with merge 9fe92ecb4c35747fd58b13f6ae23eb0f31a14680...

2020-07-13 14:21 UTC, bors-servo commented
:sunny: Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/DrTTs1J2QIiJcg7OQX2pjQ)
Approved by: jdm
Pushing 9fe92ecb4c35747fd58b13f6ae23eb0f31a14680 to master...

2020-07-13 14:21 UTC, merged