Http auth implemented
servo/servo pull request #27644
Opened 2020-09-16 11:36 UTC by mustafapc19

---

- [ X] `./mach build -d` does not report any errors
- [ X] `./mach test-tidy` does not report any errors
- [ X] These changes fix #27439 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ X] These changes do not require tests because user input is required

2020-09-16 11:38 UTC, mustafapc19 commented
@jdm

2020-10-01 17:49 UTC, jdm requested changes
Looking good! We need to fix the authentication unit tests to not panic, too.

2020-10-01 17:49 UTC, jdm commented on components/net/http_loader.rs
> +        );
These changes aren't quite right - [this step](https://fetch.spec.whatwg.org/#ref-for-proxy-authentication-entry%E2%91%A0) of the specification says to store the credentials somewhere and use them in [this step](https://fetch.spec.whatwg.org/#ref-for-proxy-authentication-entry), which is different than setting the Authorization header on the request. We should keep this code unmodified and add a FIXME comment saying that we can use the new prompt_user_for_credentials code but we need to store the result somewhere.

2020-10-01 17:49 UTC, jdm commented on components/net/http_loader.rs
> +    ) -> std::option::Option<std::string::String> {
This can be `Option<String>` instead.

2020-10-01 17:49 UTC, jdm commented on components/net/http_loader.rs
> +        }
We can do `let embedder_proxy: EmbedderProxy = context.state.embedder_proxy.lock().unwrap().lock().clone();` instead here.

2020-10-01 17:49 UTC, jdm commented on components/net/http_loader.rs
> +        serde::export::Some(base64::encode(&format!("{}:{}", name_str, pass_str)))
This can be `Some(base64::encode(&format!("{}:{}", name_str, pass_str)))` instead.

2020-10-02 05:49 UTC, mustafapc19 commented
Sure. I am just a little busy. I'll sure do it tho. I came this far

2020-10-02 14:42 UTC, jdm commented
Yep! No rush, I just felt bad about leaving this PR without any feedback so far.

2020-11-13 21:29 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #27704) made this pull request unmergeable. Please resolve the merge conflicts.

2024-12-16 09:47 UTC, mrobinson commented
Closing in favor of #34620.

2024-12-16 09:47 UTC, closed without merging