Allow gradient interpolation hints to influence color-stop fixup
servo/servo pull request #28572
Opened 2021-08-15 04:00 UTC by Bryce-MW

I am working on the [easing gradients feature for CSS](https://github.com/w3c/csswg-drafts/issues/1332). I want to eventually implement that in Servo as a demonstration since Servo is a bit easier (in my opinion) to modify than Firefox or Chromium. However, at this point, Servo does not even support gradient interpolation hints so I am working towards that support. I think that it will require modifications to [webrender](https://github.com/servo/webrender) if we don't want to use [Firefox's approximation](https://searchfox.org/mozilla-central/rev/f98dad153b59a985efd4505912588d4651033395/layout/painting/nsCSSRenderingGradients.cpp#315-391). I am happy to implement that approximation though if we want something that works now.

This pull request just makes it so that the interpolation hints influence the position of unpositioned stops. Specifically, on [my test website](https://brycemw.ca/experiments/gradients), the first and third gradients look the same prior to this fix and they look correct after this fix. It is also important to note that the white colour-stop of the first gradient should be further to the right than the white colour-stop of the second gradient. There's a bit more [discussion about this effect here](https://github.com/w3c/csswg-drafts/issues/3931).

I've implemented this in both layout_2017 and layout_2020. I had to change a few things in 2017 that I don't fully understand so I would appreciate if someone could make sure that I didn't cause a subtle bug or performance issue. Especially around line 88 and 116 of `components/layout/display_list/gradient.rs`.

---

- [X] `./mach build -d` does not report any errors (and `./mach build -d --with-layout-2020`)
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable) (I didn't know there needed to be an issue)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because 

I haven't looked into tests yet since there are no existing tests for this that I can find. I can see if there is a way to do this if needed.

2021-08-15 04:00 UTC, highfive commented
Heads up! This PR modifies the following files:
 * @emilio: components/layout/display_list/gradient.rs, components/style/values/specified/image.rs, components/style/values/generics/image.rs

2021-08-15 04:00 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify style and layout code, but no tests are modified. Please consider adding a test!

2021-08-15 04:02 UTC, Bryce-MW commented
@bors-servo try=wpt-2020

Adding this since I modified layout_2020 (https://github.com/servo/servo/wiki/Layout-2020)

2021-08-15 04:02 UTC, bors-servo commented
@Bryce-MW: :key: Insufficient privileges: not in try users

2021-08-15 04:04 UTC, bors-servo commented
@Bryce-MW: :key: Insufficient privileges: not in try users

2023-08-08 18:19 UTC, mrobinson commented
@bors-servo try

2023-10-04 08:58 UTC, mrobinson commented
@emilio Would you mind taking a look at this one to see if the changes to style are something that you'd want in Gecko?

2023-10-04 09:17 UTC, emilio requested changes
So the style changes are only needed so that `components/layout/display_list/gradient.rs` doesn't discard the interpolation hints. That seems like a smell.

It seems like instead `convert_gradient_stops` could work with `GradientItem` directly, and then style doesn't need to change at all.

2024-03-15 14:56 UTC, mrobinson commented
I think this PR might be abandoned? I doesn't really change test results as far as I can see and it needs to be reworked. I'm going to close for now, but @Bryce-MW please feel free to reopen if you are still working on this. Servo is more active now so it's quite likely that this can land with a little bit of TLC.

2024-03-15 14:56 UTC, closed without merging

2024-03-15 14:59 UTC, Bryce-MW commented
I gave up on trying to get this merged a long time ago. I haven't been actively working on gradients for a while but if I did come back I'd likely start over rather than reworking this PR. Thanks!