Make names of Sender<> and Receiver<> variables more coherent
servo/servo pull request #29710
Opened 2023-05-04 16:38 UTC by atbrakhi

Sometimes these variables are called port, sometimes ipc, sometimes they have the name of the thread on the other end and sometimes not.  This PR tries to standardize on an obvious name for all of them:

Common pattern to note in this PR:
- If it is a `IpcSender`, then naming is followed by `ipc_sender`, such as:  `bluetooth_ipc_sender`,  `canvas_ipc_sender` etc..
- If variable is `crossbeam_channel` sender/receiver then naming is followed by `sender`/`receiver` such as:  `devtools_sender`, `canvas_sender` etc...

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix [#29679](https://github.com/servo/servo/issues/29679)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2023-05-04 18:25 UTC, mrobinson commented on components/constellation/constellation.rs
> +fn route_ipc_receiver_to_new_crossbeam_receiver_preserving_errors<T>(
In think you could also remove `mpsc_` from the name of the sender and receiver in this function as well.

2023-05-04 18:28 UTC, mrobinson commented on components/constellation/constellation.rs
> +            FromCompositorMsg::GetBrowsingContext(pipeline_id, browsing_context_ipc_sender) => {
`response_sender` is a actually a pretty good name here, because it describes what the channel does -- handle the response to this query.

2023-05-04 18:28 UTC, mrobinson commented on components/constellation/constellation.rs
> +            FromCompositorMsg::GetPipeline(browsing_context_id, pipeline_ipc_sender) => {
Same comment here.

2023-05-04 18:29 UTC, mrobinson commented on components/constellation/constellation.rs
> +                self.handle_script_new_auxiliary(load_info, layout_ipc_sender);
Ditto.

2023-05-04 18:32 UTC, mrobinson requested changes
This is a great start. I think in cases where a sender is merely used to send a response, we shouldn't use the name of the data type that is sent over it, but describe its purpose ie `response_sender`. I understand that this is an annoying change to make so I'm happy to do that if it's too tedious.

2023-05-05 08:25 UTC, atbrakhi commented
> This is a great start. I think in cases where a sender is merely used to send a response, we shouldn't use the name of the data type that is sent over it, but describe its purpose ie `response_sender`. I understand that this is an annoying change to make so I'm happy to do that if it's too tedious.

Thanks for the review. I have tried to accumulate these changes in recent commit.

2023-05-08 07:28 UTC, mrobinson commented
@bors-servo r+

Thank you. I've made a couple small change and squashed the commits.

2023-05-08 07:28 UTC, bors-servo commented
:pushpin: Commit 55de8e3 has been approved by `mrobinson`

<!-- @bors-servo r=mrobinson 55de8e3ddc58b239dd0d2de14d5cbfdb418d4873 -->

2023-05-08 08:58 UTC, atbrakhi commented
@bors-servo retry

2023-05-08 08:58 UTC, bors-servo commented
@atbrakhi: :key: Insufficient privileges: not in try users

2023-05-08 11:56 UTC, bors-servo commented
:sunny: Test successful - [checks-github](https://github.com/servo/servo/actions/runs/4913697960/jobs/8776539431)
Approved by: mrobinson
Pushing 61f872e7da238860c0e043b57b9bbf37cb7fa893 to master...

2023-05-08 11:56 UTC, merged