Always make dummy available, but use it only if no gstreamer
servo/servo pull request #30240
Opened 2023-08-29 15:10 UTC by sagudev

Per https://github.com/servo/servo/issues/30189#issuecomment-1697627591

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2023-08-29 16:17 UTC, mrobinson requested changes
I really like this change!

I think you'll also need to change how `configure_media_stack` works in `command_base.py`.

2023-08-30 04:30 UTC, sagudev commented on python/servo/command_base.py
> +        if "media-gstreamer" in self.features:
This worked before the change, but now it doesn't because when running test we simply do not provide any features.

2023-08-30 04:41 UTC, sagudev commented on python/servo/command_base.py
> +        if "media-gstreamer" in self.features:
I think unconditionally running `set_gstreamer_environment_variables_if_necessary` would be best.

2023-08-30 05:54 UTC, sagudev commented
try build: https://github.com/sagudev/servo/actions/runs/6020602591

2023-08-30 06:09 UTC, mrobinson approved these changes

2023-08-30 07:26 UTC, merged