Fix WPT import by overriding product name to servo
servo/servo pull request #30457
Opened 2023-10-02 06:19 UTC by mukilan

Upstream WPT update script has bug where 'product' defaults to 'firefox' and this causes import of uninstalled python modules specific to firefox runners.

Fixes #30452

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #30452 
- [x] These changes do not require tests because they fix failing CI job

2023-10-02 06:26 UTC, sagudev approved these changes
It works: https://github.com/servo/servo/actions/runs/6376202429

2023-10-02 06:34 UTC, sagudev commented
We also have
https://github.com/servo/servo/blob/d74d51190a523d20775bf448eee408935d346e8b/python/wpt/run.py#L57
but I think that one does not need changing because we still want to be able to run other products (and I think we already pass servo as default product).

2023-10-02 06:39 UTC, sagudev commented
> We also have
> 
> https://github.com/servo/servo/blob/d74d51190a523d20775bf448eee408935d346e8b/python/wpt/run.py#L57
> 
> but I think that one does not need changing because we still want to be able to run other products (and I think we already pass servo as default product).

Or maybe not https://github.com/servo/servo/actions/runs/6376640880/job/17303962638?pr=30456

2023-10-02 06:41 UTC, sagudev requested changes
https://github.com/servo/servo/actions/runs/6376640880/job/17303962638?pr=30456 fails, I think wee need to add product option to all wptrunner invocations

2023-10-02 06:46 UTC, sagudev commented
We should override wpt's create_parser so that default product is servo.
https://github.com/servo/servo/blob/d74d51190a523d20775bf448eee408935d346e8b/python/servo/testing_commands.py#L353

2023-10-02 07:46 UTC, mukilan commented
Hmm. This might be more involved than I initially thought. I'll look into the code base so I can understand the issue and the fix better.

2023-10-04 11:43 UTC, mukilan commented
The new fix seems to have solved the issues with test runner code. I just set product = servo in manifestupdate as well, since the adding a flag to parser creates a conflict with the flag already added by upsteam WPT framework. Also, the upstram change to default to firefox is only present affetcts the  update test/manifest parsers, not for the other parser., so test-wpt and others still function correctly.

With the fix, the new sync PR fails with the below error
```
{"path": "/home/runner/work/servo/servo/tests/wpt/tests/service-workers/service-worker/tentative/static-router/resources/simple.csv", "lineno": null, "rule": "IGNORED PATH", "message": "/home/runner/work/servo/servo/tests/wpt/tests/service-workers/service-worker/tentative/static-router/resources/simple.csv matches an ignore filter in .gitignore - please add a .gitignore exception"}

WPT Lint Tool:: lint error(s) in Web Platform Tests: exit status 1

Running the WPT lint on ./tests/wpt/mozilla/tests/...
{"path": "mozilla/collections.html", "lineno": 26, "rule": "HTML INVALID SYNTAX", "message": "Test-file line has a non-void HTML tag with /> syntax"}
{"path": "mozilla/htmlcollection.html", "lineno": 13, "rule": "HTML INVALID SYNTAX", "message": "Test-file line has a non-void HTML tag with /> syntax"}
{"path": "mozilla/htmlcollection.html", "lineno": 14, "rule": "HTML INVALID SYNTAX", "message": "Test-file line has a non-void HTML tag with /> syntax"}
{"path": "mozilla/htmlcollection.html", "lineno": 15, "rule": "HTML INVALID SYNTAX", "message": "Test-file line has a non-void HTML tag with /> syntax"}
```

which I think we can address in the sync PR itself and land this first.

2023-10-04 11:52 UTC, sagudev commented
I would prefer to fix sync error before landing this, so we can test whole sync/test workflow with this commit (currently it stops at tidy check), as there might be more changes needed on the code that is not run.

2023-10-04 15:05 UTC, sagudev approved these changes
It works on https://github.com/servo/servo/pull/30493

2023-10-04 16:31 UTC, mukilan commented
Thanks for the review!

2023-10-04 20:28 UTC, merged