servoshell: add fullscreen option
servo/servo pull request #30614
Opened 2023-10-25 05:36 UTC by MarybethGasman

These changes add a cli option to start servo in fullscreen mode. As requested in #30599.
It is currently in draft form as we need to have further discussions to determine whether we truly need it.
```sh
servo --fullscreen
```
No tests for now.

2023-11-13 05:45 UTC, delan requested changes
Thanks for the patch!

I think fullscreen generally means not having any window decorations, not just maximised. We should also return whether we started in fullscreen in the Window.fullscreen of our return value.

You can use WindowBuilder::with_fullscreen or winit Window::set_fullscreen for this, or even better, call .set_fullscreen(true) on our headed Window before returning it.

2023-11-15 23:56 UTC, MarybethGasman commented
Appreciate your advice.
I call set_fullscreen on our headed Window before returning it.

It works as expected when launching.
![image](https://github.com/servo/servo/assets/90539473/d6a08fdc-c3a6-48ba-9690-baf5970da2dd)

When I refresh page, the web content seems not displayed in fullscreen mode.
![image](https://github.com/servo/servo/assets/90539473/cc08cb76-feb4-4f53-97b9-d86eb3077e73)

And I can't exit fullscreen mode or servo by Esc.

The Esc problem is because fullscreen is a whatwg web api.
It will do nothing if there is no fullscreen element in the document.
So I change the code to always Send EmbedderMsg first.

The web content not in fullscreen problem is solved by call .with_maximized on the window builder.
I have no idea why.
Am I missing something?

2023-12-24 22:48 UTC, Taym95 commented on ports/servoshell/headed_window.rs
> +        let window = Window {
why this is needed?

2025-01-14 16:01 UTC, mrobinson commented
It seems like this PR is abandoned. For proper fullscreen support we need a bit more as well. For instance, there needs to be a way for content to request fullscreen and the UI to respond properly to this.

2025-01-14 16:01 UTC, closed without merging