WebIDL: Use Uint8ClampedArray instead of raw JSObject in bindings
servo/servo pull request #31226
Opened 2024-01-30 15:02 UTC by Taym95

part #31064

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [ ] These changes do not require tests because there is not behavior change

2024-01-31 17:12 UTC, Taym95 commented on components/script/dom/imagedata.rs
> +        unsafe { Self::new_without_data(global, proto, width, height) }
@gterzian can you review this when you got time, still in progress

2024-02-01 08:54 UTC, gterzian requested changes
Thanks! This one is another rather complicated one, so I suggest a few changes.

2024-02-01 08:54 UTC, gterzian commented on components/script/dom/imagedata.rs
> +        let typed_array =
I think this belongs in a new `new_initialized` method of the heaped array, and you should create it above before `imagedata`.

2024-02-01 08:54 UTC, gterzian commented on components/script/dom/imagedata.rs
> +        let typed_array =
And you can make `new_initialized` take an optional `JSObject`, so that it can be used with `new_with_js_object`(see below).

2024-02-01 08:54 UTC, gterzian commented on components/script/dom/imagedata.rs
> +        Self::new_without_data(global, proto, width, opt_height.unwrap())
Here you should keep `new_with_jsobject`, and create a new `new_initialized` method on `HeapTypedArray` that takes an optional jsobject, in this case some.

2024-02-11 18:03 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-02-11 18:25 UTC, closed without merging