Support the parsing of image/svg+xml elements
servo/servo pull request #31318
Opened 2024-02-11 21:25 UTC by KiChjang

A really simple PR to enable the parsing and recognition of `image/svg+xml` documents.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they're covered by WPT

2024-02-12 11:57 UTC, mukilan approved these changes
Thank you!

2024-02-13 05:43 UTC, mukilan requested changes
Looks like a lot more tests are passing now and need expectations to be updated for both 2020 and 2013 layout engines.

2024-02-14 07:05 UTC, mrobinson approved these changes

2024-02-14 08:16 UTC, mukilan approved these changes

2024-02-14 09:19 UTC, merged