WebIDL Fix ImageData constructor to take a Uint8ClampedArray instead of js_object
servo/servo pull request #31398
Opened 2024-02-21 12:44 UTC by Taym95

Fix ImageData constructor to take a Uint8ClampedArray instead of js_object

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #31320

- [x] These changes do not require tests because there is not behavior change.

2024-06-12 13:55 UTC, Taym95 commented
@gterzian Do you have any idea what to do with the PR? After this change, tests are failing for all browsers, including Servo?

2025-01-14 16:01 UTC, mrobinson commented
@Taym95 What's the status of this PR?

2025-01-15 08:38 UTC, gterzian commented
@Taym95 What is the failing test? If all browsers are failing, it may be because the test itself is not conformant.

2025-01-15 08:46 UTC, jdm commented
https://wpt.fyi/results/html/semantics/embedded-content/the-canvas-element/imagedata.html?label=master&label=experimental&aligned&q=imagedata.html

2025-01-16 12:30 UTC, gterzian reviewed
I think we should find a way to make the test pass.

2025-01-16 12:30 UTC, gterzian commented on components/script/dom/imagedata.rs
> +            match new_initialized_heap_typed_array::<ClampedU8>(HeapTypedArrayInit::Data {
I think this needs a rebase, because the api was updated.

2025-01-16 12:30 UTC, gterzian commented on components/script/dom/imagedata.rs
> +                Err(_) => return Err(Error::JSFailed),
Either we are failing here where previously we wouldn't. Maybe try returning a type error here?

Or we are not producing a type error below at https://github.com/servo/servo/pull/31398/files#diff-74ee6b1aa263f228fb8648bb921e80b79654506e8b39570b764649a02f881402R89, don't know why. Maybe `get_buffer` is too liberal in returning an object even when it's of the wrong type?

2025-04-19 17:21 UTC, jdm commented on components/script_bindings/webidls/CanvasRenderingContext2D.webidl
> +  [Throws] constructor(Uint8ClampedArray data, unsigned long sw, optional unsigned long sh
The specification is dense, but I think the test as written does not match the specification. From https://webidl.spec.whatwg.org/#js-overloads we can determine which overloaded constructor to call. The distinguishing arg is 0, so we start at step 12. 12.7 checks whether there is an overload with a typed array argument that matches the kind of the typed array that was passed in. There is not, so we continue to step 12.16, which checks if there is an overload with a number at the argument index (ignoring the actual value passed in at this point). There is, so that is the overload that is selected. We only passed this test previously because we reached step 12.11 and the argument was specified as an object, so we selected the overload with the typed array argument instead.

In short: the test is wrong, it is correct that we (and every other browser) fail it.

2025-04-20 11:22 UTC, mrobinson commented
I don't even see a backtrace on this crash, which suggests it's a segfault and not a Rust panic:

```
  ▶ CRASH [expected OK] /css/compositing/canvas-composite-modes.html
  │ 
  └ Caught signal 11 in thread "Script(1,1)"
```

2025-05-05 08:57 UTC, gterzian requested changes
looks good overall, but we should find out where that crash is coming from.

2025-05-05 08:57 UTC, gterzian commented on components/script/dom/bindings/buffer_source.rs
> +        return Err(Error::JSFailed);
Are you sure about the `Error::JSFailed`, previously it was just a `()`. Also the error is mapped to `JSFailed` a thttps://github.com/servo/servo/pull/31398/files#diff-74ee6b1aa263f228fb8648bb921e80b79654506e8b39570b764649a02f881402R61

2025-05-05 08:57 UTC, gterzian commented on components/script/dom/imagedata.rs
> +                    CustomAutoRooterGuard::new(*cx, &mut CustomAutoRooter::new(typed_array)),
I think you want to assign this to a variable and then call the function. May be the source of the crash actually.

2025-05-08 18:17 UTC, jdm commented on components/script/dom/imagedata.rs
> +                let data = CustomAutoRooterGuard::new(*cx, &mut rooted_typed_array);
Use the `auto_root!` macro for this instead:
```rust
auto_root!(in(*cx) let data = typed_array);
```

2025-05-09 10:14 UTC, gterzian approved these changes
LGTM. Did we ascertain what caused the crash?

Also, let's track this as part of https://github.com/servo/servo/issues/30862

2025-05-09 11:38 UTC, merged