Fix inheritance.sub.html WPT to work on Servo
servo/servo pull request #31534
Opened 2024-03-06 17:40 UTC by azharcodeit

Fix inheritance.sub.html WPT to work on Servo

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #31518 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2024-03-06 18:08 UTC, servo-wpt-sync commented
🤖 Opened new upstream WPT pull request (web-platform-tests/wpt#44954) with upstreamable changes.

2024-03-06 19:08 UTC, Loirooriol requested changes
Thanks, but while you are at it you should purge the old entries from the expectation files, like

```
rm tests/wpt/meta/css/css-backgrounds/inheritance.sub.html.ini
./mach test-wpt -r --log-raw /tmp/servo.log --headless tests/wpt/tests/css/css-backgrounds/inheritance.sub.html
./mach update-wpt /tmp/servo.log

rm tests/wpt/meta-legacy-layout/css/css-backgrounds/inheritance.sub.html.ini
./mach test-wpt --legacy-layout -r --log-raw /tmp/servo.log --headless tests/wpt/tests/css/css-backgrounds/inheritance.sub.html
./mach update-wpt --legacy-layout /tmp/servo.log
```

(Typically you don't need to remove to update the expectations, but in this case it's for purging the obsolete entries)

2024-03-06 20:56 UTC, Loirooriol commented
Oh, and when you post a pull request, you should mark the checkboxes in the template, like

```
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #31518 (GitHub issue number if applicable)
- [X] These changes do not require tests because this is just fixing a test
```

(arguably fixing a test could also count as "There are tests for these changes", pick whatever you think makes more sense)

2024-03-06 22:28 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#44954).

2024-03-06 23:59 UTC, Loirooriol commented
You added an empty patch, possibly by mistake and you wanted to push another one?

2024-03-07 00:14 UTC, azharcodeit commented
> You added an empty patch, possibly by mistake and you wanted to push another one?

Yes, working on it, pulled main branch so must have been automatically updated

2024-03-07 02:22 UTC, servo-wpt-sync commented
✍ Updated existing upstream WPT pull request (web-platform-tests/wpt#44954) title and body.

2024-03-07 02:27 UTC, servo-wpt-sync commented
✍ Updated existing upstream WPT pull request (web-platform-tests/wpt#44954) title and body.

2024-03-07 03:05 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-03-07 03:06 UTC, servo-wpt-sync commented
✍ Updated existing upstream WPT pull request (web-platform-tests/wpt#44954) title and body.

2024-03-07 03:20 UTC, azharcodeit commented on tests/wpt/tests/css/css-backgrounds/inheritance.sub.html
> +const mediumWidth = '3px';
@Loirooriol, addressed fixes in updated PR, please have a look, thank you!

2024-03-07 07:41 UTC, Loirooriol approved these changes
Thanks, looks good!

BTW, it's noteworthy that since this is a WPT change, it has been exported to that repo: https://github.com/web-platform-tests/wpt/pull/44954
There you can go to the "Checks" tab to ensure that this isn't breaking on other browsers. Effectively, chrome, firefox and safari were passing 64/64 before the change, and still 64/64 after the change, so everything is good.

2024-03-07 09:49 UTC, azharcodeit commented
> Thanks, looks good!
> 
> BTW, it's noteworthy that since this is a WPT change, it has been exported to that repo: [web-platform-tests/wpt#44954](https://github.com/web-platform-tests/wpt/pull/44954) There you can go to the "Checks" tab to ensure that this isn't breaking on other browsers. Effectively, chrome, firefox and safari were passing 64/64 before the change, and still 64/64 after the change, so everything is good.

Great! I will check it, thank you

2024-03-07 12:54 UTC, Loirooriol commented
Ah, #31453 landed first, so now there is a conflict in `tests/wpt/meta/css/css-backgrounds/inheritance.sub.html.ini`
Can you rebase the patch to the current tip?

2024-03-07 14:47 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-03-07 15:00 UTC, Loirooriol commented on tests/wpt/meta/css/css-backgrounds/inheritance.sub.html.ini
> +    expected: FAIL
You shouldn't be adding this. You can just remove this file now.

2024-03-07 15:27 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-03-07 18:58 UTC, sagudev commented
> 🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

https://github.com/web-platform-tests/wpt/pull/44954 does not include comment with spec link, so it's really out of sync.

2024-03-07 21:01 UTC, Loirooriol commented
It's strange, because initially the bot could export the changes without problems, and the test hasn't been changed upstream: https://github.com/web-platform-tests/wpt/commits/master/css/css-backgrounds/inheritance.sub.html

I will investigate tomorrow.

2024-03-08 08:39 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#44954).

2024-03-08 08:51 UTC, Loirooriol commented
I squashed the commits together and now it works.

I suspect the problem was that d5908c9ba80aff1f81c67519ed0f8b2c9d454064 has no WPT modification, and https://github.com/servo/servo/blob/ef3dad3a610d9d73754e976bece64a2184ed3821/python/wpt/exporter/step.py#L156 isn't using `--allow-empty`.

2024-03-08 10:31 UTC, mrobinson commented
Looks like the failure here was the typical "hdiutil: create failed - Resource busy" that we see.

2024-03-08 11:27 UTC, merged