clippy: Fix warnings in `components/net`
servo/servo pull request #31626
Opened 2024-03-12 15:46 UTC by eerii

Continuation to #31500, fixes all clippy warnings in `components/net` (excluding safety comments).

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are part of #31500
- [x] These changes do not require tests because they do not modify functionality, they only fix lint errors.

2024-03-12 16:01 UTC, mrobinson requested changes
Nice! Just a couple small comments:

2024-03-12 16:01 UTC, mrobinson commented on components/net/fetch/methods.rs
> +        ),
Could this just be something like this:

```
fn is_null_body_status(...) -> bool {
    matches!(
        status,
        Some(StatusCode::SWITCHING_PROTOCOLS) |
        Some(StatusCode::NO_CONTENT) |
        Some(StatusCode::RESET_CONTENT) |
        Some(StatusCode::NOT_MODIFIED)
    )
}

2024-03-12 16:01 UTC, mrobinson commented on components/net/filemanager_thread.rs
> +            );
Let's make this an early return.

2024-03-12 16:18 UTC, eerii commented on components/net/filemanager_thread.rs
> +            );
Done, thanks for the suggestion!

2024-03-12 17:15 UTC, mrobinson approved these changes

2024-03-13 09:39 UTC, mrobinson commented
Opened #31638 for this intermittent. Sending back to the MQ.

2024-03-13 11:09 UTC, merged