Fix Documentation Link to Private Item in layout_2020
servo/servo pull request #31644
Opened 2024-03-13 13:32 UTC by ektuu

…umentation

Removed markdown link syntax from references to the private item BaseFragmentInfo in components/layout_2020/table/mod.rs documentation comments to prevent Rustdoc warnings about linking to private items in public documentation. This adjustment ensures documentation clarity and adherence to Rust's documentation standards without generating broken links.

---

- [ X ] `./mach build -d` does not report any errors
- [ X  ] `./mach test-tidy` does not report any errors
- [  X ] These changes fix #_documentation generation warning regarding linking to a private item in public documentation  (#31575)

- [  X ] There are tests for these changes OR
- [  X ] These changes do not require tests because  they involve minor documentation adjustments that do not impact the functionality or output of the code.

2024-03-13 13:49 UTC, mrobinson requested changes
This PR removes a lot of code and documentation unnecessarily. Is this the results of pasting the code into an AI model and then just pasting the results into the file? Please don't do that. At the very least, make sure the code changes compile locally. This is what we ask in the commit template and it's good practice contributing to open source projects.

2024-03-13 13:49 UTC, mrobinson commented on components/layout_2020/table/mod.rs
> +    /// The range of tracks in this TableTrackGroup.
Please don't remove these links.

2024-03-13 16:49 UTC, ektuu commented
@mrobinson I really apologize for this carelessness. I'm a bit new to open source, and forgot to read `Contribution Guidelines`.
This was due to co-pilot in my VS Code.
I'll fix this by tomorrow, and make sure to not repeat such stupid mistakes again.

2024-03-14 10:44 UTC, mrobinson commented
> @mrobinson I really apologize for this carelessness. I'm a bit new to open source, and forgot to read `Contribution Guidelines`. This was due to co-pilot in my VS Code. I'll fix this by tomorrow, and make sure to not repeat such stupid mistakes again.

No worries. It's okay to use tools to help your work, but please make sure that things are working before opening a pull request. Welcome to the Servo project. If you haven't already, I recommend joining our Zulip chat and introducing yourself.

2024-03-19 07:55 UTC, mrobinson commented
I've just preserved the typo fixes here, because they are valid and I'd like to clear out some of the pending PRs.

2024-03-19 07:55 UTC, mrobinson approved these changes

2024-03-19 09:37 UTC, merged