Fix rust doc errors in components/layout_2020
servo/servo pull request #31708
Opened 2024-03-16 09:13 UTC by Aaryakhandelwal

Fixed the unresolved links present in components/layout_2020 
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #31575 (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [X] These changes do not require tests because they only change documentation and no functionality.

2024-03-16 22:04 UTC, Rhea-Eve commented
Sorry, I didn't see this before I added my own pr. I resolved some of the broken references differently.  See #31712.

2024-03-17 16:41 UTC, mrobinson requested changes

2024-03-17 16:41 UTC, mrobinson commented on components/layout_2020/flow/line.rs
> +    /// The block offset of the line start in the containing Inline Formatting Context.
I think you can just qualify the reference to InlineFormattingContext instead of removing the link.

2024-03-17 16:41 UTC, mrobinson commented on components/layout_2020/formatting_contexts.rs
> +/// The baselines of a layout or [`Fragment::Box`] Some layout uses the first and some layout uses
Again, I think this just needs to be qualified. `Fragment::Box` is an enum variant, but this is actually referring to the struct stored inside the enum variant `BoxFragment`.

2024-03-17 18:12 UTC, Rhea-Eve commented
@mrobinson I think that third edit that @Aaryakhandelwal suggested seems to be accurate. She changed [`Self::handle_cell`] to [`Self::add_cell`]. After looking at it, this was my hunch too, but I wasn't entirely sure. Currently, there does not seem to be a function called handle_cell. And it seems that the comment was added at the same time as add_cell.

2024-03-18 07:51 UTC, Aaryakhandelwal commented
@mrobinson , Am I still supposed to make changes, as the next PR created by @Rhea-Eve already handles these both errors correctly.

2024-03-18 08:30 UTC, mrobinson commented
> @mrobinson , Am I still supposed to make changes, as the next PR created by @Rhea-Eve already handles these both errors correctly.

Let's land both PRs. I suggest just updating this PR to remove the first two changes.

2024-03-18 14:40 UTC, Aaryakhandelwal commented
> > @mrobinson , Am I still supposed to make changes, as the next PR created by @Rhea-Eve already handles these both errors correctly.
> 
> Let's land both PRs. I suggest just updating this PR to remove the first two changes.

Yes, I will do that

2024-03-19 07:58 UTC, mrobinson approved these changes

2024-03-19 09:44 UTC, merged