Run platform bootstrap first in bootstrap
servo/servo pull request #31840
Opened 2024-03-23 11:05 UTC by sagudev

So the user do not need to install llvm via choco manually.

This should solve `error: linker lld-link.exe not found` error on windows.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2024-03-23 11:21 UTC, mrobinson requested changes
This will cause a problem on unsupported Linux distributions, as it prevents the installation of `crown` and `taplo`.

2024-03-23 11:33 UTC, sagudev commented
> This will cause a problem on unsupported Linux distributions, as it prevents the installation of `crown` and `taplo`.

We only need to do this on windows.

2024-03-24 17:28 UTC, mrobinson commented
Hrm. Thinking out loud here, maybe the order shouldn't be so important when running code in `./mach bootstrap`. What do you think about emitting a warning on Linux, but then a "Press enter to continue" prompt so that it isn't lost in the other output?

2024-03-24 17:43 UTC, sagudev commented
> Hrm. Thinking out loud here, maybe the order shouldn't be so important when running code in `./mach bootstrap`. What do you think about emitting a warning on Linux, but then a "Press enter to continue" prompt so that it isn't lost in the other output?

Warning for unsupported Linux distributions, right?

2024-03-25 11:08 UTC, mrobinson commented
> Warning for unsupported Linux distributions, right?

Yep, exactly. Perhaps this should just warn and allow continuing, rather than simply exiting and skipping the installation of taplo and crown.

2024-04-04 18:53 UTC, jschwe commented
> Yep, exactly. Perhaps this should just warn and allow continuing, rather than simply exiting and skipping the installation of taplo and crown.

It would be nice if that also happened on windows. For example, I was quite happy that the `choco` step currently happens late in the bootstrap.  I don't have choco installed, but also don't need choco to install anything, since I only care about cross-compiling.

2024-04-29 13:32 UTC, mrobinson approved these changes

2024-04-29 13:43 UTC, mrobinson commented
@jschwe I've opened #32176 for the usecase you mention.

2024-04-29 14:39 UTC, merged