clippy: fix warnings in ports/servoshell
servo/servo pull request #31939
Opened 2024-03-29 16:02 UTC by ektuu

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes are a part of https://github.com/servo/servo/issues/31500

- [ ] These changes do not require tests because only clippy warnings were fixed

2024-03-29 16:07 UTC, mrobinson approved these changes

2024-03-29 16:07 UTC, mrobinson requested changes
You need to run `./mach fmt` on this code.

2024-03-29 16:09 UTC, ektuu commented
> You need to run `./mach fmt` on this code.

It changes the complete format of changes in servoshell/app.rs.
I had run it but then I fixed some formatting manually which gave error, I've reformatted it .
Please review.

2024-03-31 10:52 UTC, ektuu commented
hey @mrobinson 
I have fixed the formatting here.
Waiting for your review:)

2024-03-31 20:02 UTC, mrobinson approved these changes

2024-03-31 21:18 UTC, merged