webgpu: Use safe callbacks
servo/servo pull request #32008
Opened 2024-04-06 04:39 UTC by sagudev

It also removes the need for HashMap in WGPU struct that keep data alive until it was used by C callback.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes OR

2024-04-06 05:54 UTC, sagudev commented
Buffermapasync is not working right: https://github.com/sagudev/servo/actions/runs/8578926656/job/23513773148 yet

2024-04-08 12:20 UTC, sagudev commented
It looks like some IPC messages are dropped/missing so some promises are never resolved.

2024-04-08 17:03 UTC, sagudev commented
NOTE-TO-SELF: Ipc-channel created from `response_async` should only send one massage back (wgpu runs callback also on failures at buffer map async).

2024-04-10 11:13 UTC, sagudev commented
I solved IPC problem (more on that is written in https://servo.zulipchat.com/#narrow/stream/263398-general/topic/ipc_channel) using `Arc<Mutex<VecDeque<_>>>` (queue of messages that were send from itself). Alternative option to self_msg is to put `webrender_api`, `webrender_document` and `global` in ArcMutex, while first two are not really problematic (only used in UpdateWebRenderData) `global` is used practically everywhere so we would need a lot of locks for every operation.

It makes https://sagudev.github.io/briefcase/fastgame.html actually work instead of freeze, but no WPT result is changed: https://github.com/sagudev/servo/actions/runs/8610552319/job/23597139814

2024-04-29 12:41 UTC, gterzian requested changes
So I've looked a bit into https://docs.rs/wgpu-core/0.20.0/src/wgpu_core/device/global.rs.html#2391, and I'm wondering if we really need the callbacks for the map asyncs. It seems to just makes things more complicated, see for example the lock around webrender. 

This is different from the closures of submitted work done, because those are actually called at a later stage. But the map asyncs callbacks are just called right then and there. 

I think https://docs.rs/wgpu/latest/wgpu/struct.BufferSlice.html#method.map_async only applies to when you are using the higher-level wgpu API. the wgpu-core `buffer_map_async`, simply call the callback synchronously however. 

If that is correct(I think it is, but let me know if you think otherwise), I would say we should remove the callbacks, and the locks.

2024-04-29 12:41 UTC, gterzian commented on components/webgpu/lib.rs
> +                        let callback = BufferMapCallback::from_rust(Box::from(move |result| {
Can we not just call `global.buffer_map_async` synchronously, and then handle the result and do the webrender stuff?

2024-04-29 12:41 UTC, gterzian commented on components/webgpu/lib.rs
> +                        let callback = BufferMapCallback::from_rust(Box::from(move |result| {
same here: do we need the callback?

2024-04-29 16:45 UTC, sagudev commented
Callback is called synchronously only when result if there is immediate failure (mostly validation): https://docs.rs/wgpu-core/0.20.0/src/wgpu_core/device/global.rs.html#2388 (we currently handle this twice, see https://github.com/servo/servo/issues/32172)

I think I can see why you get confused by callbacks (I got too for few moments), but `op` (`BufferMapOperation` that contains callback) is passed to https://docs.rs/wgpu-core/0.20.0/src/wgpu_core/device/global.rs.html#2498 as described in https://github.com/gfx-rs/wgpu/blob/08efa72a83d0acdf25177408150e4c87933c1cd7/wgpu-core/src/device/life.rs#L222 and triggered on maintain (it's called by device_poll) here: https://github.com/gfx-rs/wgpu/blob/08efa72a83d0acdf25177408150e4c87933c1cd7/wgpu-core/src/device/resource.rs#L455 (later this function returns both submission and mapping closures, that are actually fired in poll functions).

So yeah I think callbacks are really needed (if they were not, they would not be in wgpu). You can always ask in wgpu matrix channel if my explanation is to messy.

2024-04-30 11:43 UTC, gterzian approved these changes
> So yeah I think callbacks are really needed 

Ok, I now see the callback is stored over at https://github.com/gfx-rs/wgpu/blob/bdf30fa45aa86b827749f7ee45ed342ce27b0fbb/wgpu-core/src/device/global.rs#L2498

LGTM!

2024-04-30 12:47 UTC, merged