Fixed some clippy warnings in components
servo/servo pull request #32107
Opened 2024-04-18 12:00 UTC by jahielkomu

This PR includes fixes to some clippy warnings:

- Elides timelines
- Removes useless use of format!
- Removes unneeded return statement
- Eliminates use of an explicit closure for copying elements.
- Replaces the use of negated comparison with ```partial_cmp```
---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #31500 
- [X] These changes do not require tests because it touches not functionality

2024-04-18 12:01 UTC, jahielkomu commented
Hello @mrobinson , I hope you are well.
Please kindly review.

2024-04-18 13:41 UTC, mrobinson requested changes

2024-04-18 13:41 UTC, mrobinson commented on components/script/dom/webgl2renderingcontext.rs
> +            };
```suggestion
            self.base.webgl_error(InvalidValue);
            return Ok(());
```

2024-04-18 20:52 UTC, jahielkomu commented
@mrobinson , I have updated the PR.
Kindly review.

2024-04-19 08:19 UTC, mrobinson approved these changes

2024-04-19 08:20 UTC, mrobinson commented
Thanks!

2024-04-19 10:00 UTC, merged