webgpu: Implement device lost
servo/servo pull request #32354
Opened 2024-05-23 16:06 UTC by sagudev

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix https://github.com/servo/servo/issues/32347
- [x] There are tests for these changes in CTS

2024-05-23 16:06 UTC, sagudev commented
Current try run: https://github.com/sagudev/servo/actions/runs/9205601757/job/25323173909

2024-05-23 16:47 UTC, sagudev commented
I think I will not deal with `_webgpu/webgpu/cts.https.html?q=webgpu:api,operation,adapter,requestDevice:invalid:*` in this PR as wgpu-core allows creating multiple valid devices from same adapter, but spec doesn't.

2024-05-23 17:29 UTC, sagudev commented
new run: https://github.com/sagudev/servo/actions/runs/9211814858/job/25343380939
`_webgpu/webgpu/cts.https.html?q=webgpu:api,validation,state,device_lost,destroy` has (only in CI):
```
PASS [expected TIMEOUT] subtest: :stage="finish";awaitLost=true
PASS [expected NOTRUN] subtest: :stage="finish";awaitLost=false
PASS [expected NOTRUN] subtest: :stage="submit";awaitLost=true
FAIL [expected NOTRUN] subtest: :stage="submit";awaitLost=false

assert_unreached: 
  - EXCEPTION: endTestScope timed out
    PromiseTimeoutError@https://web-platform.test:8443/_webgpu/webgpu/common/util/util.js:114:8
    raceWithRejectOnTimeout/timeoutPromise&lt;/handle&lt;@https://web-platform.test:8443/_webgpu/webgpu/common/util/util.js:140:14
    step_timeout/&lt;@https://web-platform.test:8443/resources/testharness.js:1234:18
    
 Reached unreachable code
```

`_webgpu/webgpu/cts.https.html?q=webgpu:api,validation,state,device_lost,destroy:command,renderPass,renderBundle:*` is crashing now (instead of timeout), but it's out of scope of this PR.

2024-05-24 07:19 UTC, sagudev commented
`endTestScope timed out` are happening because WGPU thread is stuck in deadlock: https://github.com/gfx-rs/wgpu/issues/5737

2024-05-28 19:36 UTC, sagudev commented
https://github.com/sagudev/servo/actions/runs/9271180193/job/25507347414

`_webgpu/webgpu/cts.https.html?q=webgpu:api,validation,state,device_lost,destroy:createComputePipelineAsync:*` and `_webgpu/webgpu/cts.https.html?q=webgpu:api,validation,state,device_lost,destroy:createRenderPipelineAsync:*` is due to https://github.com/servo/servo/issues/31591

`_webgpu/webgpu/cts.https.html?q=webgpu:api,validation,state,device_lost,destroy:queue,writeTexture,2d,uncompressed_format:*` has flaky timeout that I have yet to investigate.

2024-06-12 17:28 UTC, sagudev commented
> 
> `_webgpu/webgpu/cts.https.html?q=webgpu:api,validation,state,device_lost,destroy:queue,writeTexture,2d,uncompressed_format:*` has flaky timeout that I have yet to investigate.

This is due to another deadlock issue in wgpu: https://github.com/gfx-rs/wgpu/issues/5737#issuecomment-2163556055

2024-06-13 17:25 UTC, gterzian commented
Will review tomorrow!

2024-06-14 09:47 UTC, gterzian requested changes
LGTM, but I don't think we need to propagate all the lost reasons.

2024-06-14 10:02 UTC, sagudev commented on components/webgpu/script_messages.rs
> +    Destroyed = 1,
I just copied this from wgpu as I planned to use wgpu's type, but we could definitely roll our own type (that would not have other irrelevant fields). That would mean that we will do 2 conversions: wgt::DeviceLostReason -> DeviceLostReason -> GPUDeviceLostReason

2024-06-14 10:11 UTC, sagudev commented on components/script/dom/gpudevice.rs
> +        let lost = GPUDeviceLostInfo::new(global, msg.into(), reason);
Given the experimental nature of servo (and even more experimental WebGPU support) I chose more (servo/wgpu) developer friendly approach by propagate wgpu error messages.

2024-06-14 14:03 UTC, sagudev commented on components/script/dom/gpudevice.rs
> +        lost_promise: Rc<Promise>,
I am not sure exactly what you meant here, but this promise is created in `new`, that calls `new_inherited`.

2024-06-14 14:28 UTC, sagudev commented
Lifetime of `GPUDevice` still bugs me, global scope has hashmap of `Dom<GPUDevice>` that keeps `GPUDevice` alive unless GPUDevice is manually destroyed, so we should probably use weakref in hashmap: https://doc.servo.org/script/dom/bindings/weakref/index.html, but this can be done as a follow up (this problem exist also in main).

2024-06-17 10:08 UTC, gterzian commented on components/script/dom/gpudevice.rs
> +        lost_promise: Rc<Promise>,
Ah yes, ok.

2024-06-17 10:10 UTC, gterzian approved these changes
LGTM. 

>we should probably use weakref in hashmap

Add a note before merging?

2024-06-17 10:50 UTC, sagudev commented
> > we should probably use weakref in hashmap
> 
> Add a note before merging?

I opened https://github.com/servo/servo/issues/32519 and assigned myself as I already have WIP.

2024-06-17 13:43 UTC, merged