Proper GPUDevice cleanup
servo/servo pull request #32520
Opened 2024-06-17 15:31 UTC by sagudev

GlobalScope now holds WeakRef to `GPUDevice`s so they should actually get GCed, then we run `GPUDevice` drop, that sends WebGPURequest::DropDevice which sends FreeDevice to script thread that frees id and removes GPUDevice from GlobalScope's hashmap (if it's still there, as we remove it eagerly after device is lost)

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #32519
- [x] There are tests for these changes in WebGPU CTS

2024-06-17 16:19 UTC, sagudev commented
Try run: https://github.com/sagudev/servo/actions/runs/9550525359/job/26324665866

there are some unexpected results that are unrelated to the changes (something about canvas), so I only need to do some more manual testing that it actually works.

2024-06-18 18:34 UTC, sagudev commented
I manually tested and it works. But if configure canvas is also run it does not get dropped because underlying GPUTexture is have owning ref to GPUDevice, even after page is changed (might be something wrong with canvas cleanup), but this is separate issue anyway.

2024-06-19 12:29 UTC, gterzian requested changes
Couple of things...

2024-06-19 13:00 UTC, sagudev commented on components/script/dom/globalscope.rs
> +            .root()
We remove it to be sure that we do not dispatch any errors anymore, but since this is also guaranteed by wgpu_thread we can remove logic here.

2024-06-19 14:47 UTC, jdm commented
> EDIT: I think we might be "leaking" some DOM objects, because when page is reloaded all should be dropped, right?

Only if a major GC happens after the reload, I believe?

2024-06-19 14:52 UTC, sagudev commented
> > EDIT: I think we might be "leaking" some DOM objects, because when page is reloaded all should be dropped, right?
> 
> Only if a major GC happens after the reload, I believe?

I used this patch:
```patch
From 54d7f933022c4a4abb47fe1c4245f52a1fcc0aee Mon Sep 17 00:00:00 2001
From: sagudev <16504129+sagudev@users.noreply.github.com>
Date: Tue, 18 Jun 2024 19:38:49 +0200
Subject: [PATCH] Add way to force a GC

---
 components/script/dom/testbinding.rs             | 13 +++++++++++++
 components/script/dom/webidls/TestBinding.webidl |  2 ++
 2 files changed, 15 insertions(+)

diff --git a/components/script/dom/testbinding.rs b/components/script/dom/testbinding.rs
index 388af65e23c2..0fef64f16fe2 100644
--- a/components/script/dom/testbinding.rs
+++ b/components/script/dom/testbinding.rs
@@ -1080,6 +1080,19 @@ impl TestBindingMethods for TestBinding {
             stringMember: Some(s2),
         }
     }
+
+    #[allow(unsafe_code)]
+    fn GC(&self) {
+        let cx = GlobalScope::get_cx();
+        unsafe {
+            js::jsapi::PrepareForFullGC(*cx);
+            js::jsapi::NonIncrementalGC(
+                *cx,
+                js::jsapi::JS::GCOptions::Shrink,
+                js::jsapi::JS::GCReason::COMPONENT_UTILS,
+            );
+        }
+    }
 }
 
 #[allow(non_snake_case)]
diff --git a/components/script/dom/webidls/TestBinding.webidl b/components/script/dom/webidls/TestBinding.webidl
index 4552a6e002ac..e8510126d90e 100644
--- a/components/script/dom/webidls/TestBinding.webidl
+++ b/components/script/dom/webidls/TestBinding.webidl
@@ -577,6 +577,8 @@ interface TestBinding {
   GlobalScope entryGlobal();
   GlobalScope incumbentGlobal();
 
+  undefined GC();
+
   [Exposed=(Window)]
   readonly attribute boolean semiExposedBoolFromInterface;
 ```
to force a GC on page load (so it should clean old page on reload):
```js
let testBinding = new window.TestBinding();
testBinding.GC();
```
but this didn't help either.

2024-06-20 03:55 UTC, gterzian approved these changes
LGTM

2024-06-20 06:47 UTC, merged