Implement window.HTMLDocument
servo/servo pull request #32553
Opened 2024-06-19 06:37 UTC by webbeef

This adds the webidl and implementation needed for `window.HTMLDocument` . Behavior is similar to Gecko's one.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #32536

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because there is no wpt tests covering that field.

2024-06-19 07:16 UTC, mrobinson requested changes

2024-06-19 07:16 UTC, mrobinson commented on components/script/dom/htmldocument.rs
> +    }
Could these not be implemented?

2024-06-19 08:03 UTC, mrobinson commented on components/script/dom/htmldocument.rs
> +    }
Is it not enough to simply ensure that window has an HTMLDocument getter that does the same thing as `fn Document(...)` in `window.rs`?

2024-06-19 15:26 UTC, Taym95 commented on components/script/dom/htmldocument.rs
> +// https://html.spec.whatwg.org/multipage/#htmldocument
can you follow other doc link and use this pattern: `/// <link>` for all doc link in this PR?

2024-06-19 17:39 UTC, mrobinson requested changes

2024-06-19 17:39 UTC, mrobinson commented on components/script/dom/htmldocument.rs
> +    }
Reading through https://github.com/whatwg/html/issues/4792 this seems to be the situation:

 - The specification says that `HTMLDocument` should be an alias for `Document` ie we should not need to implement a separate document interface. The `Document` interface implements the named getter (Servo gained support for this unfortunate part of the web platform last year).
 - No browsers do this though. Instead FireFox has `window.document` implement `HTMLDocument`, but not for XML documents. This means that `responseXML` and other XML pages do not have a named getter, which seems to big the biggest compatability risk.

This change is quite strange though. It implements `HTMLDocument`, but `window.document` is still not an HTMLDocument. If we want to follow Firefox, it seems like the named getter should move to `HTMLDocument` and `HTMLDocument` should be exposed at `window.document` when the document is HTML (but not XML).

2024-06-19 19:23 UTC, mrobinson commented
> @mrobinson I think you're not talking about the same spec (the whole naming is very confusing). What is implemented here is https://html.spec.whatwg.org/multipage/nav-history-apis.html#htmldocument :

I believe this is the same specification and the part that you quoted is the bit that says that `HTMLDocument` should be an alias of `Document`. In Firefox `window.document instanceof HTMLDocument == true`.

2024-06-19 23:35 UTC, jdm commented
> > I believe this is the same specification and the part that you quoted is the bit that says that `HTMLDocument` should be an alias of `Document`. In Firefox `window.document instanceof HTMLDocument == true`.
> 
> You're right. So in Servo we would need `Document` from `components/script/dom/document.rs` to implement `HTMLDocument`? A naive approach of just doing `impl HTMLDocumentMethods for Document { ... }` doesn't work. I'll try to figure out how the instanceof check is wired up.

A couple things:
1) the use of Document::new will need to be HTMLDocument::new in appropriate cases (and the code that creates a JS reflector for HTMLDocument will need to be written)
2) the first field of HTMLDocument will need to be Document, not Reflector.

2025-08-04 08:28 UTC, yezhizhen commented
Closing due to #38433.

2025-08-04 08:28 UTC, closed without merging