compositor: remove cursor_pos and update step on new frame
servo/servo pull request #32662
Opened 2024-07-02 04:07 UTC by wusyong

There's a bug when updating the cursor on a new frame because `cursor_pos` isn't updated at all. I would like to take this chance to remove it. It will be the embedder's responsibility to decide when it should update its cursor. In general cases, users will move their mouse, and the cursor should be updated.

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #32632

- [x] These changes do not require tests, but the servoshell should be built successfully.

2024-07-02 12:17 UTC, mrobinson requested changes
I don't think we should remove support for this. Perhaps it is the embedder's responsibility to manage cursor changes, but it is up to the engine to tell the embedder when a cursor change is requested. The embedder cannot manage this properly because it doesn't know anything about the WebRender display list.

Here's an example of where this is managed in WebKitGTK and I'm sure all other web engines are managed similarly: https://github.com/WebKit/WebKit/blob/d72f4bd734ae263071bcd38db5ded174974a5bd4/Source/WebKit/UIProcess/API/gtk/PageClientImpl.cpp#L174

What's the bug with `cursor_pos`? Can we fix that?

2024-07-02 12:57 UTC, wusyong commented
> What's the bug with cursor_pos? Can we fix that?

Compositor has two places to perform `update_cursor` and send `EmbedderMsg::SetCursor` to embedder. One is when it [receives mouse move event](https://github.com/servo/servo/blob/main/components/compositing/compositor.rs#L1558), the other is when there's [new webrender frame](https://github.com/servo/servo/blob/main/components/compositing/compositor.rs#L627). The problem with latter is it uses `cursor_pos` which never got updated, so it will always be `(0, 0)` and result in default cursor when calling `hit_test_at_point`.

While we can fix it by setting `cursor_pos` as well during the mouse move event, I feel like it's a good chance to remove it. So moving the mouse becomes the only way to update the cursor, which matches general cases. And if the embedder really wants to get more `EmbedderMsg::SetCursor` messages, it can just send more mouse move events manually. Besides, getting `EmbedderMsg::SetCursor` messages because of new webrender frame is confusing to embedder from my experience. If we want the cursor to get updated without moving, why not let the embedder manually request it when performing actions like `present`?

2024-07-07 02:33 UTC, wusyong commented on components/compositing/windowing.rs
>      MouseWindowMoveEventClass(DevicePoint),
I hope the updated doc comments can clarify the goal of this issue. I think it's reasonable that only the embedder can request the cursor message.

2024-07-07 04:30 UTC, wusyong commented on components/compositing/windowing.rs
>      MouseWindowMoveEventClass(DevicePoint),
I think you are right. I'll close this one and set the cursor_pos instead.

2024-07-07 04:30 UTC, closed without merging