Fix panic by using char_indices to iterate over str
servo/servo pull request #32978
Opened 2024-08-08 11:33 UTC by Taym95

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #32976

- [x] There are tests for these changes OR

2024-08-08 11:50 UTC, mrobinson requested changes
Nice fix! I have one small suggestion:

2024-08-08 11:50 UTC, mrobinson commented on components/script/dom/htmlimageelement.rs
> +    while let Some((i, ch)) = char_indices.next() {
```suggestion
    for (index, character) in s.char_indices() {
```

2024-08-08 12:24 UTC, NotnaKO commented
Why don't we use rfind here? Like:

2024-08-08 12:29 UTC, NotnaKO commented
Why don't we use find here?
```rs
let i = s.find(|c| !predicate(c)).unwrap_or(s.len())
(&s[0..i], &s[i..])
```

2024-08-09 07:43 UTC, Taym95 commented
> Why don't we use find here? Like:
> 
> ```rust
> let i = s.find(|c| !predicate(&c)).unwrap_or(s.len());
> (&s[0..i], &s[i..])
> ```
> 
> PR: #32980

Will give same result, I am trying to debug this one

2024-08-12 09:42 UTC, closed without merging