Extract binary select into common_command_arguments
servo/servo pull request #33205
Opened 2024-08-27 09:13 UTC by sagudev

Multiple commands support specifying binary, this will unify them all so we can use any binary on any such commands (I think nightly binaries needs to start using GitHub, but this is for followup).

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they are mach changes

2024-08-27 09:14 UTC, sagudev commented on python/servo/testing_commands.py
> +        return_value = wpt.run.run_tests(binary, **kwargs)
Not sure if this works for android.

2024-08-27 09:29 UTC, sagudev commented on python/servo/testing_commands.py
> +        return self._test_wpt(sys.executable, android=True, **kwargs)
Not sure about android.

2024-08-27 15:39 UTC, mrobinson requested changes
Looks good. Just a couple minor comments:

2024-08-27 15:39 UTC, mrobinson commented on python/servo/command_base.py
> +    def common_command_arguments(build_configuration=False, build_type=False, binary=False):
```suggestion
    def common_command_arguments(build_configuration=False, build_type=False, binary_selection=False):
```

2024-08-27 15:39 UTC, mrobinson commented on python/servo/testing_commands.py
> +    def smoketest(self, servo_binary, params):
```suggestion
    def smoketest(self, servo_binary: str, params):
```

2024-08-27 15:39 UTC, mrobinson commented on python/servo/testing_commands.py
> +    def dromaeo_test_runner(self, tests, binary):
Please add typing information here.

2024-08-27 15:39 UTC, mrobinson commented on python/servo/testing_commands.py
> +    def jquery_test_runner(self, cmd, binary):
Please add typing information here.

2024-08-27 15:39 UTC, mrobinson commented on python/servo/testing_commands.py
> +    def test_dromaeo(self, tests, servo_binary):
```suggestion
    def test_dromaeo(self, tests, servo_binary: str):
```

2024-08-27 15:39 UTC, mrobinson commented on python/servo/testing_commands.py
> +    def update_jquery(self, servo_binary):
```suggestion
    def update_jquery(self, servo_binary: str):
```

2024-08-27 15:39 UTC, mrobinson commented on python/servo/testing_commands.py
> +    def _test_wpt(self, servo_binary, **kwargs):
```suggestion
    def _test_wpt(self, servo_binary: str, **kwargs):
```

2024-08-27 15:39 UTC, mrobinson commented on python/servo/testing_commands.py
> +    def test_wpt(self, servo_binary, **kwargs):
```suggestion
    def test_wpt(self, servo_binary: str, **kwargs):
```

2024-08-27 15:39 UTC, mrobinson commented on python/servo/post_build_commands.py
> +    def rr_record(self, servo_binary, with_asan=False, params=[]):
```suggestion
    def rr_record(self, servo_binary: str, with_asan=False, params=[]):
```

2024-08-27 15:39 UTC, mrobinson commented on python/servo/post_build_commands.py
> +    def _run(self, servo_binary, params, debugger=False, debugger_cmd=None,
```suggestion
    def _run(self, servo_binary: str, params, debugger=False, debugger_cmd=None,
```

2024-08-28 11:40 UTC, mrobinson approved these changes
Thanks. This is a nice cleanup.

2024-08-28 11:40 UTC, mrobinson commented on python/servo/command_base.py
> +                CommandArgumentGroup('Binary select'),
```suggestion
                CommandArgumentGroup('Binary selection'),
```

2024-08-28 13:01 UTC, merged