clippy: Fix large size difference between variants in components/shared/webrender/lib.rs
servo/servo pull request #33690
Opened 2024-10-07 15:23 UTC by chickenleaf

**file**: components/shared/webrender/lib.rs

**PR Description**
**Issue**: Clippy warned about `ScriptToCompositorMsg` having a big size difference between variants.

**Change**:  
        1. Made `display_list_info` a `Box<CompositorDisplayListInfo>` in the `SendDisplayList` variant.
        2. Adjusted how `SendDisplayList` is constructed.

**Impact**: One extra heap allocation, but improves performance when using the enum. Functionality stays the same.

---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes are part of https://github.com/servo/servo/issues/31500

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they do not touch functionality.

2024-10-07 16:30 UTC, mrobinson requested changes

2024-10-07 16:30 UTC, mrobinson commented on components/shared/webrender/lib.rs
> -
Can you please preserve this empty line as it's unrelated to your change?

2024-10-07 16:31 UTC, mrobinson commented
Nice work! You will need to sign your commit (see https://github.com/servo/servo/pull/33690/checks?check_run_id=31183256151) and I have left one comment about an unnecessary blank line deletion. Thank you.

2024-10-07 17:25 UTC, chickenleaf commented
@mrobinson  yes thank you!! shall sign and add back the empty line right away

2024-10-08 09:21 UTC, mrobinson commented on components/shared/webrender/lib.rs
> -
You have added the empty line back, but with trailing white space.

2024-10-08 09:21 UTC, mrobinson commented on components/shared/webrender/lib.rs
> +
```suggestion

```

2024-10-08 09:22 UTC, mrobinson approved these changes

2024-10-08 12:32 UTC, merged