Add `medium` cargo profile for daily usage
servo/servo pull request #34035
Opened 2024-10-28 11:00 UTC by jschwe

- The standard `dev` mode is often too slow for daily work on servo
- Increasing the optimization level to 2 improves the performance noticably.
- Build time for opt-level = 1 is slightly higher than 2 on my machine
- Reducing debug info to `line-tables-only` improves link and build times,
  while still keeping relevant info for backtraces.

Also extend .servobuild to allow setting custom cargo profiles instead
of just release and dev.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

2024-10-28 11:39 UTC, nicoburns approved these changes
This seems useful. A couple of suggestions:

- Use `opt-level = 1` or `opt-level = 2` (default for release is 3). These (esp. 2) is generally fast enough for servo development (at least in my testing), but improve compile times.
- Use `debug = "line-tables-only"`. This will generate minimal debug info for file/line numbers when a panic occurs.

2024-10-28 11:41 UTC, mrobinson commented
I mean, if these options are useful for normal development, maybe they should be the default and then we can add a non-incremental build for when people need to prevent trouble. We already have a `production` profile and a `debug` profile.

@delan, thoughts here?

2024-10-28 11:42 UTC, mrobinson commented
I'm imagining four types of build:

1. Everyday development
2. Every development (non-incremental)
3. All debug options on
4. Production

2024-10-30 05:17 UTC, nicoburns commented
Merging this as it seems useful as-is (and doesn't affect anyone's existing workflows in it's current form). We can iterate and consider making this the default in future.

2024-10-30 05:48 UTC, delan requested changes
Thanks! Remember to update the book’s [section about build profiles](https://book.servo.org/hacking/building-servo.html#build-profiles) :)

One change, aside from that I think we’re good to go. The rest of my comments below don’t block this patch.

> Use `debug = "line-tables-only"`. This will generate minimal debug info for file/line numbers when a panic occurs.

What’s the motivation for this compared to `full`, which is what we use in `dev`? Does it make the build faster?

> Probably the biggest incompatibility is with `sccache`, since sccache doesn't work with incremental builds. Adding a new profile is the safest option, since changing release to incremental would likely "break" users that have sccache configured (in the sense that sccache won't cache any Rust crates anymore).

When we use sccache in CI, we set `CARGO_INCREMENTAL`, which may help with that without needing an extra profile.

2024-10-30 05:48 UTC, delan commented on Cargo.toml
> +[profile.devel]
this name is too similar to cargo’s `dev` (which is already a confusing can of worms due to the whole `[profile.dev]` vs `target/debug` thing). what about something like `dev-fast`?

2024-10-30 06:24 UTC, nicoburns commented
> > Use `debug = "line-tables-only"`. This will generate minimal debug info for file/line numbers when a panic occurs.
> 
> What’s the motivation for this compared to `full`, which is what we use in `dev`? Does it make the build faster?

I haven't measured, but yes it should do. "full" can produce several hundred megabytes of debuginfo for large projects, which dwarfs the size of the binary itself, and impacts both compile and link times. The cargo team is actually considering changing the default from 2 to 1 for the built-in dev/debug profile.


> what about something like dev-fast?

I'd prefer something short and without a hyphen if possible, as I figure I'm going to be typing this a lot. Maybe `fdev`?

2024-10-30 07:11 UTC, delan commented
> I'd prefer something short and without a hyphen if possible, as I figure I'm going to be typing this a lot. Maybe `fdev`?

`fastdev`? Otherwise `fdev` works for me.

2024-10-30 08:09 UTC, mrobinson commented
I agree with @delan's idea of making this a "more optimized" version of the `dev` profile, as that makes the name of the profile more understandable. Another option could be `dev-optimized` or `dev-opt` for an optimized `dev` build.

2024-10-30 08:36 UTC, jschwe commented
>>  Use debug = "line-tables-only". This will generate minimal debug info for file/line numbers when a panic occurs.
>
> What’s the motivation for this compared to full, which is what we use in dev? Does it make the build faster?

In addition to what nico said, my common workflow for openharmony also includes:
- Potentially copying the shared library from a remote build server to my machine
- packaging the app
- pushing the app to a device over usb
- installing the app

This means binary size is quite relevant for the build + test cycle, since the rust artifact is copied multiple times in the process. The `dev` profile gives an artifact that is over 2GB large!

I would say that the close names `dev` / `devel` are perhaps not that relevant, since the usage would be 
`--dev` vs `--profile=devel` which seems distinct enough. 

If we are discussing names though, then I guess it would also make sense to revisit Martins proposal of making this the default settings for `dev` and instead provide a custom profile for debugging with gdb/lldb. 
`debug` is probably not possible since it conflicts with the target directory name of the `dev` profile, but perhaps `debugger` / `debugging` or `gdb` would work?

2024-10-30 08:47 UTC, delan commented
I think any name that only differs from `dev` or `debug` by stemming or abbreviation would be too confusing for the new profile, regardless of whether the new profile is a faster `dev` or a more debuggable `release`.

Would `fastdev` be ok?

2024-10-30 08:52 UTC, mrobinson commented
> If we are discussing names though, then I guess it would also make sense to revisit Martins proposal of making this the default settings for `dev` and instead provide a custom profile for debugging with gdb/lldb.
> `debug` is probably not possible since it conflicts with the target directory name of the `dev` profile, but perhaps `debugger` / `debugging` or `gdb` would work?

Yeah, I am also okay with turning our current `dev` profile into `dev-full` or `dev-chonky` if this new profile is good enough for most debugging / development.

2024-10-30 15:58 UTC, jschwe commented
Updated the PR to modify the standard `dev` profile instead, and provide a `dev-full` custom profile which corresponds to the standard options from cargos `dev` profile, but is intended to be used when debugging only.

> Thanks! Remember to update the book’s [section about build profiles](https://book.servo.org/hacking/building-servo.html#build-profiles) :)

I'll open a PR to the book after this has been merged, since there still might be more discussions to be had.

2024-10-30 16:02 UTC, nicoburns commented
Do we have any data on compile times with this new configuration vs. the old one? That might good to get if we're going to make it the default. I would guess the increased opt level will make it slower, but the debug info change should speed it up. Not sure what (or how big) the overall effect will be.

2024-10-30 16:24 UTC, mrobinson approved these changes

2024-10-30 16:24 UTC, mrobinson commented on servobuild.example
> +# Check the `Cargo.toml` manifest for a complete list of custom profiles.
```suggestion
# Use `mode = <profile>` or `mach build --profile=<profile>`  to build the given
# profile. Check the `Cargo.toml` manifest for a complete list of custom profiles.
```

2024-10-30 17:41 UTC, jdm commented
> > Do we have any data on compile times with this new configuration vs. the old one? That might good to get if we're going to make it the default.
> 
> Is it a common use case to build and run servo in `dev` mode?

99% of my builds are dev builds. My priorities are debugging symbols and build speeds.

2024-11-19 10:36 UTC, jschwe commented
I got pre-empted with other things, but now I've got a bit of time to come back to this. 

> 99% of my builds are dev builds. My priorities are debugging symbols and build speeds.

Thanks for commenting! I dropped this idea and went back to a custom profile.

Regarding performance - I tried both opt-level  1 and 2 and at least on a 5995WX Linux system binary size and build time are almost identical:

### Opt-level 1

- Size: 479MB
- Clean build: 2:06 min
- Incremental after adding some whitespace to script: 0:31

### Opt-level 2
- Size: 487 MB
- Clean build: 1:56
- Incremental: 0:29 

It was a bit surprising to me that builds are slightly faster with O2 than with O1, but I guess that probably varies by machine.

2024-11-20 11:20 UTC, nicoburns commented
This is actually slower a release build for the initial build for me, but a rebuild is quite a bit quicker. The price of incremental compilation I guess.

I would also note that a lot the problem here seems to be the script crate. Changes to `layout_2020` are much faster. Splitting up script (which should allow the compilation) probably ought to be a priority if we want faster builds.

### Release build
Clean build: 4m 03s
Incremental (script): 1m 25s
Incremental (layout_2020): 16.5s

### Medium build
Clean build: 4m 23s 
Incremental (script): 52s
Incremental (layout_2020): 6.8s

Very jealous of your 5995WX with it's 2 minute clean build times!

P.S. Some weird crate rebuilds for the release profile incremental rebuild. Can't work out why `tungstenite` would rebuild for a whitespace change to script.

2024-11-21 10:34 UTC, delan approved these changes

2024-11-21 12:20 UTC, merged