layout: Use `Size::FitContent` when the alignment isn't `normal` or `stretch`
servo/servo pull request #34264
Opened 2024-11-16 17:22 UTC by taniishkaaa

Uses `Size::FitContent` when the `AlignFlags` isn't `normal` or `stretch` (Non-replaced case of #34248)

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes are part of #34248 
- [X] There are tests for these changes

2024-11-16 22:21 UTC, nicoburns commented
@taniishkaaa You will need to update the test expectations. The best way to do this (although it does take a bit of setup the first time) is to run the WPT test runner locally. There is documentation on that here https://book.servo.org/hacking/testing.html

You will probably want to run something like:

```bash
./mach build --release # Ensure you have an up-to-date build
ulimit -n 5000 # Optional: prevent "too many open files" errors when running the WPT runner
./mach test-wpt --release --include _mozilla/css --include css/CSS2 --include css/css-align --include css/css-position --include css/css-grid --include css/css-sizing --include css/css-values --include css/css-ui  --log-raw=raw.log
./mach update-wpt raw.log

You could also run the whole of "css" seeing as lots of subsection are affected here (but this will take longer).

There are also quite a few "unexpected FAIL"s, which should be looked into. These are not *necessarily* a problem as sometimes we were previously passing a test by coincidence when we don't really have the feature implemented. But I notice quite a few failures around abspos layout here that are probably worth looking into.

2024-11-17 07:28 UTC, taniishkaaa commented
These are the results before my latest commit. However, I did a try run and it gave the same results: https://github.com/taniishkaaa/servo/actions/runs/11876506211#summary-33095466502
Should I go ahead and update the test expectations or wait for a review?

2024-11-17 18:42 UTC, Loirooriol requested changes
Also, in the commit title or description or somewhere you should mention that the change is for absolutely positioned boxes.

2024-11-17 18:42 UTC, Loirooriol commented on components/layout_2020/positioned.rs
> +                }
Nit: no need to repeat `solve_size(.., stretch_size)`:
```suggestion
                let initial_behavior = match self.alignment.value() {
                    AlignFlags::STRETCH | AlignFlags::NORMAL => Size::Stretch,
                    _ => Size::FitContent,
                };
                let size = solve_size(initial_behavior, stretch_size);
```

2024-11-17 18:42 UTC, Loirooriol commented on components/layout_2020/positioned.rs
> +                .unwrap_or_default();
Instead of this, keep the `SizeConstraint` and return it as part of the `AxisResult`.

2024-11-17 18:42 UTC, Loirooriol commented on components/layout_2020/positioned.rs
>                  free_space -= used_size;
Use the `to_definite()` just for this. If it's not definite, I don't think the margins matter at all, but maybe setting `free_space` to zero makes the most sense?

```suggestion
                if let Some(used_size) = size.to_definite() {
                    free_space -= used_size;
                } else {
                    free_space = Au::zero(),
                }
```

2024-11-17 23:12 UTC, Loirooriol requested changes

2024-11-17 23:12 UTC, Loirooriol commented on components/layout_2020/positioned.rs
> +                    AlignFlags::STRETCH | AlignFlags::NORMAL => Size::Stretch,
This should include `AlignFlags::AUTO` (it behaves as normal in this case).

2024-11-18 11:45 UTC, Loirooriol approved these changes
LGTM if you update test expectations

2024-11-18 12:36 UTC, taniishkaaa commented
Done!

2024-11-18 16:10 UTC, merged