Support future uses of traits with associated types in rooting analysis
servo/servo pull request #34359
Opened 2024-11-23 21:26 UTC by jdm

These changes were required to allow #33416 to build successfully. They handle the case where a struct marked with `#[crown::unrooted_must_root_lint::allow_unrooted_interior]` is paramaterized over a trait, and also allow `#[crown::unrooted_must_root_lint::allow_unrooted_in_rc]` on associated types to propagate the current behaviours of those attributes on concrete types.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are part of #1799
- [x] There are tests for these changes

2024-11-24 05:57 UTC, sagudev requested changes
It needs some compile-fail tests.


Would want to force propagation of `allow_*` onto type types like we do for must_root: https://github.com/servo/servo/blob/main/support/crown/tests/compile-fail/trait_type_impl_must_root.rs, I think this is not needed for safety here, but it sure is nice to enforce same rooting rules or else they can became out of sync. We at least need it in other direction to ensure that trait types are not more relaxed than original.

2024-12-12 07:30 UTC, jdm commented
> Would want to force propagation of `allow_*` onto type types like we do for must_root: https://github.com/servo/servo/blob/main/support/crown/tests/compile-fail/trait_type_impl_must_root.rs, I think this is not needed for safety here, but it sure is nice to enforce same rooting rules or else they can became out of sync. We at least need it in other direction to ensure that trait types are not more relaxed than original.

I'm having a lot of trouble making this work. Here's my attempt:
```diff
diff --git a/support/crown/src/unrooted_must_root.rs b/support/crown/src/unrooted_must_root.rs
index 777ff3f089..3578957f39 100644
--- a/support/crown/src/unrooted_must_root.rs
+++ b/support/crown/src/unrooted_must_root.rs
@@ -6,7 +6,7 @@ use rustc_hir::{self as hir, intravisit as visit, ExprKind};
 use rustc_lint::{LateContext, LateLintPass, LintContext, LintPass, LintStore};
 use rustc_middle::ty;
 use rustc_session::declare_tool_lint;
-use rustc_span::def_id::LocalDefId;
+use rustc_span::def_id::{DefId, LocalDefId};
 use rustc_span::symbol::{sym, Symbol};

 use crate::common::{in_derive_expn, match_def_path};
@@ -51,6 +51,33 @@ impl UnrootedPass {
     }
 }

+fn associated_type_has_attr<'tcx>(
+    sym: &'_ Symbols,
+    cx: &LateContext<'tcx>,
+    ty: ty::Ty<'tcx>,
+    attr: Symbol,
+) -> bool {
+    let mut walker = ty.walk();
+    while let Some(generic_arg) = walker.next() {
+        let t = match generic_arg.unpack() {
+            rustc_middle::ty::GenericArgKind::Type(t) => t,
+            _ => {
+                walker.skip_current_subtree();
+                continue;
+            },
+        };
+        if let ty::Alias(
+            ty::AliasTyKind::Projection | ty::AliasTyKind::Inherent | ty::AliasTyKind::Weak,
+            ty,
+        ) = t.kind() {
+            return cx.tcx
+                .has_attrs_with_path(ty.def_id, &[sym.crown, sym.unrooted_must_root_lint, attr]);
+        }
+        return false
+    }
+    false
+}
+
 /// Checks if a type is unrooted or contains any owned unrooted types
 fn is_unrooted_ty<'tcx>(
     sym: &'_ Symbols,
@@ -253,12 +280,26 @@ impl<'tcx> LateLintPass<'tcx> for UnrootedPass {
         };

         let sym = &self.symbols;
-        if cx.tcx.has_attrs_with_path(
-            trait_item.hir_id().expect_owner(),
-            &[sym.crown, sym.unrooted_must_root_lint, sym.must_root],
-        ) {
-            return;
-        }
+        let has_attr = |did, name| {
+            cx.tcx
+                .has_attrs_with_path(did, &[sym.crown, sym.unrooted_must_root_lint, name])
+        };
+
+        let def_id: DefId = trait_item.hir_id().expect_owner().into();
+        let must_root_present = has_attr(
+            def_id,
+            sym.must_root,
+        );
+
+        let allow_unrooted_interior_present = has_attr(
+            def_id,
+            sym.allow_unrooted_interior,
+        );
+
+        let allow_unrooted_in_rc_present = has_attr(
+            def_id,
+            sym.allow_unrooted_in_rc,
+        );

         let trait_id = cx
             .tcx
@@ -273,17 +314,63 @@ impl<'tcx> LateLintPass<'tcx> for UnrootedPass {
                     .associated_items(impl_def_id)
                     .find_by_name_and_kind(cx.tcx, trait_item.ident, ty::AssocKind::Type, trait_id)
                     .unwrap();
+
                 let mir_ty = cx.tcx.type_of(type_impl.def_id).skip_binder();
-                if is_unrooted_ty(&self.symbols, cx, mir_ty, false) {
+
+                let impl_ty_must_root = associated_type_has_attr(sym, cx, mir_ty, sym.must_root);
+                let impl_ty_allow_unrooted = associated_type_has_attr(sym, cx, mir_ty, sym.allow_unrooted_interior);
+                let impl_ty_allow_rc = associated_type_has_attr(sym, cx, mir_ty,  sym.allow_unrooted_in_rc);
+                println!("{} vs {}", impl_ty_must_root, must_root_present);
+                if impl_ty_must_root != must_root_present {
+                    println!("hello");
+                    if !must_root_present && impl_ty_must_root {
+                        cx.lint(UNROOTED_MUST_ROOT, |lint| {
+                            lint.primary_message(
+                                "Type trait declaration must be marked with \
+                                 #[crown::unrooted_must_root_lint::must_root] \
+                                 to allow binding must_root types in associated types",
+                            );
+                            lint.span(trait_item.span);
+                        });
+                    } else {
+                        cx.lint(UNROOTED_MUST_ROOT, |lint| {
+                            lint.primary_message(
+                                "Mismatched use of \
+                                 #[crown::unrooted_must_root_lint::must_root] \
+                                 between associated type declaration and impl definition",
+                            );
+                            lint.span(trait_item.span);
+                        });
+                    }
+                }
+
+                if impl_ty_allow_unrooted != allow_unrooted_interior_present {
                     cx.lint(UNROOTED_MUST_ROOT, |lint| {
                         lint.primary_message(
-                            "Type trait declaration must be marked with \
-                        #[crown::unrooted_must_root_lint::must_root] \
-                        to allow binding must_root types in associated types",
+                            "Mismatched use of \
+                             #[crown::unrooted_must_root_lint::allow_unrooted_interior] \
+                             between associated type declaration and impl definition",
                         );
                         lint.span(trait_item.span);
-                    })
+                    });
+                }
+
+                if impl_ty_allow_rc != allow_unrooted_in_rc_present {
+                    cx.lint(UNROOTED_MUST_ROOT, |lint| {
+                        lint.primary_message(
+                            "Mismatched use of \
+                             #[crown::unrooted_must_root_lint::allow_unrooted_interior_in_rc] \
+                             between associated type declaration and impl definition",
+                        );
+                        lint.span(trait_item.span);
+                    });
                 }
+
+                //let mir_ty = cx.tcx.type_of(type_impl.def_id).skip_binder();
+                //let ty_is_unrooted = is_unrooted_ty(&self.symbols, cx, mir_ty, false);
+                /*if must_root_present  {
+                    })
+                }*/
             }
         }
     }
diff --git a/support/crown/tests/compile-fail/missing_allow_in_rc.rs b/support/crown/tests/compile-fail/missing_allow_in_rc.rs
index 3b1d0102ed..e2ae55fdf2 100644
--- a/support/crown/tests/compile-fail/missing_allow_in_rc.rs
+++ b/support/crown/tests/compile-fail/missing_allow_in_rc.rs
@@ -10,6 +10,7 @@ use std::rc::Rc;
 trait TypeHolderTrait {
     #[crown::unrooted_must_root_lint::must_root]
     type F;
+    //~^ ERROR: Mismatched use of #[crown::unrooted_must_root_lint::must_root] between associated type declaration and impl definition [crown::unrooted_must_root]
 }

 struct TypeHolder;
diff --git a/support/crown/tests/compile-fail/missing_unrooted_interior_on_trait.rs b/support/crown/tests/compile-fail/missing_unrooted_interior_on_trait.rs
index 41ae7544da..5a256e30b0 100644
--- a/support/crown/tests/compile-fail/missing_unrooted_interior_on_trait.rs
+++ b/support/crown/tests/compile-fail/missing_unrooted_interior_on_trait.rs
@@ -8,6 +8,7 @@
 trait TypeHolderTrait {
     #[crown::unrooted_must_root_lint::must_root]
     type F: Default;
+    //~^ ERROR: Mismatched use of #[crown::unrooted_must_root_lint::must_root] between associated type declaration and impl definition [crown::unrooted_must_root]
 }

 struct TypeHolder;
diff --git a/support/crown/tests/compile-fail/trait_type_impl_must_root.rs b/su [...]

2024-12-12 09:20 UTC, sagudev commented
I will take a look.

2024-12-12 14:59 UTC, sagudev commented
The problem is in `associated_type_has_attr`, we should probably need to handle more cases there, but it works for tests at least. I also needed to update some test expectations (msgs and one expectations was wrong). This patch applies on top of yours.

```patch
diff --git a/support/crown/src/unrooted_must_root.rs b/support/crown/src/unrooted_must_root.rs
index 9d9d2fc2d3..4ad970f988 100644
--- a/support/crown/src/unrooted_must_root.rs
+++ b/support/crown/src/unrooted_must_root.rs
@@ -66,18 +66,19 @@ fn associated_type_has_attr<'tcx>(
                 continue;
             },
         };
-        if let ty::Alias(
-            ty::AliasTyKind::Projection | ty::AliasTyKind::Inherent | ty::AliasTyKind::Weak,
-            ty,
-        ) = t.kind()
-        {
-            return cx
-                .tcx
-                .has_attrs_with_path(ty.def_id, &[sym.crown, sym.unrooted_must_root_lint, attr]);
+        match ty.kind() {
+            ty::Adt(did, substs) => {
+                return cx.tcx.has_attrs_with_path(
+                    did.did(),
+                    &[sym.crown, sym.unrooted_must_root_lint, attr],
+                );
+            },
+            tk => {
+                unreachable!("tk: {:?}", std::mem::discriminant(tk))
+            },
         }
-        return false;
     }
-    false
+    true
 }
 
 /// Checks if a type is unrooted or contains any owned unrooted types
@@ -298,7 +299,7 @@ impl<'tcx> LateLintPass<'tcx> for UnrootedPass {
             .tcx
             .trait_of_item(trait_item.hir_id().expect_owner().to_def_id())
             .unwrap();
-        // we need to make sure that all impl do not have any must_root type binded
+        // we need to make sure that each impl has same crown attrs
         let impls = cx.tcx.trait_impls_of(trait_id);
         for (_ty, impl_def_ids) in impls.non_blanket_impls() {
             for impl_def_id in impl_def_ids {
diff --git a/support/crown/tests/compile-fail/missing_allow_in_rc.rs b/support/crown/tests/compile-fail/missing_allow_in_rc.rs
index e2ae55fdf2..9e088d0c6a 100644
--- a/support/crown/tests/compile-fail/missing_allow_in_rc.rs
+++ b/support/crown/tests/compile-fail/missing_allow_in_rc.rs
@@ -10,7 +10,7 @@ use std::rc::Rc;
 trait TypeHolderTrait {
     #[crown::unrooted_must_root_lint::must_root]
     type F;
-    //~^ ERROR: Mismatched use of #[crown::unrooted_must_root_lint::must_root] between associated type declaration and impl definition [crown::unrooted_must_root]
+    //~^ ERROR: Mismatched use of #[crown::unrooted_must_root_lint::allow_unrooted_interior_in_rc] between associated type declaration and impl definition [crown::unrooted_must_root]
 }
 
 struct TypeHolder;
diff --git a/support/crown/tests/compile-fail/missing_unrooted_interior_on_trait.rs b/support/crown/tests/compile-fail/missing_unrooted_interior_on_trait.rs
index 5a256e30b0..7892f28cf3 100644
--- a/support/crown/tests/compile-fail/missing_unrooted_interior_on_trait.rs
+++ b/support/crown/tests/compile-fail/missing_unrooted_interior_on_trait.rs
@@ -8,7 +8,6 @@
 trait TypeHolderTrait {
     #[crown::unrooted_must_root_lint::must_root]
     type F: Default;
-    //~^ ERROR: Mismatched use of #[crown::unrooted_must_root_lint::must_root] between associated type declaration and impl definition [crown::unrooted_must_root]
 }
 
 struct TypeHolder;
@@ -16,7 +15,6 @@ impl TypeHolderTrait for TypeHolder {
     type F = Foo;
 }
 
-
 #[crown::unrooted_must_root_lint::must_root]
 #[derive(Default)]
 struct Foo;
```

2024-12-12 15:18 UTC, jdm commented
Aha, thanks!

2024-12-15 06:34 UTC, sagudev commented on support/crown/src/unrooted_must_root.rs
> +            },
We will need to handle more cases here:
```
thread 'rustc' panicked at src/unrooted_must_root.rs:77:17:
internal error: entered unreachable code: tk: Discriminant(22)
```

2024-12-15 06:36 UTC, sagudev commented
I guess crown runs on all crates:
```
  Downloaded image v0.24.9
   Compiling unicode-ident v1.0.14
   Compiling proc-macro2 v1.0.92
   Compiling libc v0.2.168
   Compiling serde v1.0.216
   Compiling cfg-if v1.0.0
   Compiling pkg-config v0.3.31
   Compiling log v0.4.22
   Compiling quote v1.0.37
thread 'rustc' panicked at src/unrooted_must_root.rs:77:17:
internal error: entered unreachable code: tk: Discriminant(22)
```

2025-01-04 08:54 UTC, sagudev commented on support/crown/src/unrooted_must_root.rs
> +            },
We are missing https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/sty/type.TyKind.html#variant.Alias

2025-01-15 19:56 UTC, jdm commented
The build now runs successfully for me, and picked up a couple (harmless) mismatches \o/

2025-01-16 06:56 UTC, sagudev commented on support/crown/src/unrooted_must_root.rs
> +                                 to allow binding must_root types in associated types",
Can we end all messages with a dot because rust inserts same text after it an makes it confusing.

2025-01-16 06:59 UTC, sagudev approved these changes
Otherwise this great.

2025-01-16 18:36 UTC, sagudev commented
tests expectations also needs to be updated: https://github.com/servo/servo/actions/runs/12815047923/job/35732894160?pr=34359#step:15:131

2025-01-16 20:52 UTC, merged