Fix mach bootstrap for Python 3.13
servo/servo pull request #34460
Opened 2024-12-02 20:58 UTC by MichaelMcDonnell

The 'cgi' module was removed in Python 3.13. This broke mach bootstrap for Python 13.3. The `legacy-cgi` is a drop-in replacement for projects not ready to upgrade to a better approach. I've added that to the requirements. The newer version of the `pillow` module was also required.

The mach test-wpt command still doesn't work after this change but bootstrap at least works.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #34095

- [X] These changes do not require tests because it can be tested by running `./mach bootstrap` with Python 3.13 installed. We could set up CI to do that if needed.

2024-12-02 21:01 UTC, servo-wpt-sync commented
🤖 Opened new upstream WPT pull request (web-platform-tests/wpt#49474) with upstreamable changes.

2024-12-02 21:14 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49474).

2024-12-03 10:38 UTC, dklassic commented
Tested on a Windows 11 + Python 3.13.0 setup I can confirm this fix is working!

2024-12-03 10:43 UTC, wusyong approved these changes

2024-12-03 10:46 UTC, mrobinson commented
I suspect a change like this should be submitted upstream in the WPT project instead of here so that it can be properly reviewed by the people who maintain the Python dependencies.

Please do not land this change from here.

2024-12-03 10:47 UTC, mrobinson requested changes
I have

2024-12-03 17:41 UTC, MichaelMcDonnell commented
@mrobinson Yes, it would be ideal to make the changes in WPT upstream. Yes, if this change were to be applied in upstream it would break upstream by requiring a Python 3.10 as a minimum instead of Python 3.8. I've run the WPT tests with Python 3.12 and that still worked.

Without this change `./mach build` doesn't work. It means I cannot build Servo on Fedora 41 without installing Python 3.12 and making it the default.

I made this PR as a stop-gap measure to unblock myself and others from building Servo until the issue is fixed upstream. The WPT tests fail inside the Python logging library with a lock being None, which points to an issue in Python itself. I hope that someone else will "pick up the ball" from here and figure out the last changes that are needed to fix the WPT tests. I expect it to be trivial to merge upstream back once it is fixed since they will most likely make the same changes plus some more work.

I guess it comes down to what is prioritized higher, unblocking versus taking on risk of breaking something?

2024-12-03 21:24 UTC, MichaelMcDonnell commented
I have created a WIP upstream pull request https://github.com/web-platform-tests/wpt/pull/49503. Help would greatly be appreciated.

2024-12-04 09:00 UTC, mrobinson commented
> @mrobinson Yes, it would be ideal to make the changes in WPT upstream. Yes, if this change were to be applied in upstream it would break upstream by requiring a Python 3.10 as a minimum instead of Python 3.8. I've run the WPT tests with Python 3.12 and that still worked.

We automatically sync changes from our repository upstream as upstream trusts us to do reviews here, so merging this here will also merge it upstream. That's the main issue here. Thanks for moving the discussion upstream!

2024-12-04 09:57 UTC, mrobinson commented
Closing this one in favor of https://github.com/web-platform-tests/wpt/pull/49503.

2024-12-04 09:57 UTC, closed without merging

2024-12-04 11:18 UTC, MichaelMcDonnell commented
> We automatically sync changes from our repository upstream as upstream trusts us to do reviews here, so merging this here will also merge it upstream. That's the main issue here. Thanks for moving the discussion upstream!

Ah ok, yeah that would not work then. Thank you for helping me!

2024-12-04 12:10 UTC, MichaelMcDonnell commented
I've closed web-platform-tests/wpt#49503 too. I don't see a way to support both that old versions of Python and current Python.

In the short term, I think the solution is not to rely on the system Python. In the long term, I think moving away from Python and to Rust instead is a better solution.