perf: use concat! and &'static str for servo version
servo/servo pull request #34566
Opened 2024-12-10 17:39 UTC by Integral-Tech

Replace `format!` and `String` with `concat!` and `&'static str` for servo version.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

2024-12-10 18:06 UTC, mrobinson requested changes
I think for something like this, where the code isn't run in a tight loop, the performance implications aren't very large. It feels a bit like premature optimization to make this change.

2024-12-10 18:33 UTC, Integral-Tech commented on components/compositing/compositor.rs
> -        version_string: String,
IMO, as the type has been changed to `&'static str`, changing argument / variable name from `version_string` to `version_str` is also preferred.

2024-12-12 08:56 UTC, mrobinson commented
Thank you for the contribution. I'd be happy to reconsider it if it's possible to see that it's having a real world effect on performance. For now, I'm not sure we are ready for these kind of micro-optimizations.

2024-12-12 08:56 UTC, closed without merging

2024-12-12 08:59 UTC, mrobinson commented
An example of why this might be tricky for embedders is that they do not have the potential to produce a static string at runtime for their version. For instance, if it was read from a configuration file...

2024-12-12 09:02 UTC, Integral-Tech commented
@mrobinson The original code uses `env!` macro which gets the environment variable during compilation.

2024-12-12 09:05 UTC, Integral-Tech commented
> An example of why this might be tricky for embedders is that they do not have the potential to produce a static string at runtime for their version.

@mrobinson `format!` produces the string at runtime, while `concat!` produces a static string during compilation,