XPath: implement lang() and id() core functions
servo/servo pull request #34594
Opened 2024-12-12 09:44 UTC by vlindhol

These two functions were still unimplemented. Also tweaked the AST a bit to make it clearer to express "no predicates".

As a bonus, fixed a parsing bug where "/" was attempted before "//", leaving the "//" branch as always unused.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34593 
- [x] There are tests for these changes

2024-12-12 09:53 UTC, vlindhol commented on components/script/dom/element.rs
> -
Moved this to `Node` since any node inherits the `lang` attribute, not only elements. Although it's on elements that the attribute gets set.

2024-12-12 18:25 UTC, mrobinson requested changes, later dismissed

2024-12-12 18:25 UTC, mrobinson commented on components/script/dom/node.rs
> +    // https://html.spec.whatwg.org/multipage/#language
```suggestion
    /// <https://html.spec.whatwg.org/multipage/#language>
```

2024-12-12 18:25 UTC, mrobinson commented on components/script/dom/node.rs
> +    pub fn get_lang(&self) -> Option<String> {
```suggestion
    pub(crate) fn get_lang(&self) -> Option<String> {
```

2024-12-12 20:11 UTC, simonwuelker commented
Are there no web platform tests for the `id` function?

2024-12-12 20:46 UTC, vlindhol commented
> Are there no web platform tests for the `id` function?

You are correct! I should probably add at least one smoke test. If I understood correctly, `tests/wpt/mozilla` is for our own tests, right? Ooooh or should I be making a PR to the actual WPT test suite?

2024-12-12 21:27 UTC, simonwuelker commented
> If I understood correctly, tests/wpt/mozilla is for our own tests, right?

Yes, but tests for `id` can easily be upstreamed, so we should add them to WPT. That way other browsers can benefit from them too.

> Ooooh or should I be making a PR to the actual WPT test suite?

You don't need to make a seperate PR for web platform tests (though you can, of course), an upstream PR will be opened automatically if you add the tests here.

The book has some info on adding new tests: https://book.servo.org/hacking/testing.html#writing-new-web-tests.

2025-03-05 19:33 UTC, simonwuelker commented
Are you still working on this?

2025-03-06 09:01 UTC, vlindhol commented
> Are you still working on this?

@simonwuelker yes, I've dropped off from OSS work for a few months due to personal reasons, but still very much am planning to continue this. Should be back in action in a week or two by the looks of it!

2025-06-01 11:04 UTC, servo-wpt-sync commented
🤖 Opened new upstream WPT pull request (web-platform-tests/wpt#52891) with upstreamable changes.

2025-06-01 11:13 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#52891).

2025-06-01 11:28 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#52891).

2025-06-01 11:29 UTC, servo-wpt-sync commented
✍ Updated existing upstream WPT pull request (web-platform-tests/wpt#52891) title and body.

2025-06-01 11:39 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#52891).

2025-06-01 12:11 UTC, vlindhol commented
@mrobinson @simonwuelker sorry for the longer-than-anticipated break, the PR is now up-to-date with tests for `id()` and AFAICT all other PR review things fixed!

2025-06-01 14:46 UTC, simonwuelker approved these changes
Thanks, LGTM with two nits (:

2025-06-01 14:46 UTC, simonwuelker commented on components/script/xpath/eval.rs
> +        }
This could be `self.is_some_and(T::is_primitive)`

2025-06-01 14:46 UTC, simonwuelker commented on tests/wpt/tests/domxpath/fn-id.html
> +</body>
Add a newline at the end of the file please

2025-06-02 07:09 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#52891).

2025-06-02 08:30 UTC, simonwuelker commented
Just one more `./mach update-manifest` and we can merge this ^^

2025-06-02 08:46 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#52891).

2025-06-02 15:04 UTC, simonwuelker commented
this needs a re-review from @mrobinson

2025-06-02 18:59 UTC, jdm commented
Given mrobinson's previous review comments, I'm going to mark it as addressed.

2025-06-02 20:08 UTC, merged