feat: Track the binary size for all the different platforms
servo/servo pull request #34744
Opened 2024-12-23 04:02 UTC by dklassic

Laid some groundworks and have it working in my fork to check for potential blockers. Opening this Draft PR for some feedback, for now what it does are:

- Add bencher step for each individual platforms, will run on full workflow
- Currently we only track build size in platforms other than Linux
- Build Size are tracked in:
    - macos: macos-${{ inputs.profile }}
    - Windows: windows-${{ inputs.profile }}
    - Linux: linux-${{ inputs.profile }}
    - Android: ${{ matrix.target }}-${{ inputs.profile }}
    - Open Harmony: ${{ matrix.target }}-${{ inputs.profile }}
  
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #34555 (intentional wording to prevent automatically closing the issue)

- [x] There are tests for these changes in try parser tests

2024-12-23 04:02 UTC, dklassic commented
Some unsure points:
- Not sure if the target-profile naming is good enough, especially for Android and Open Harmony the targets are all named with platform at the end (e.g. `x86_64-linux-android`) which is sorta hard to read.
- For now it only tracks `release`, supposedly we care more about `production` and `production-stripped` then I guess we'll have to basically build additional `production` binary at least for every platform for each main PR land, which may somewhat bloat the duration for our workflow.
- Another way is to track only nightly releases which can be done on [internal-wpt-dashboard](https://github.com/servo/internal-wpt-dashboard) runs as suggested by @sagudev or maybe pass an argument to allow size tracking workflow to run during [nightly builds](https://github.com/servo/servo/blob/main/.github/workflows/nightly.yml), which is maybe more of a no-brainer.

2024-12-23 05:26 UTC, sagudev commented
Wow, that's a lot of files. Can we remove repetition by making bencher workflow more generic (argument to accept os to get full binary name, all test to do in bencher bin, speedometer, dromeo) or at least use composable github action.

2024-12-23 05:41 UTC, dklassic commented
> Wow, that's a lot of files. Can we remove repetition by making bencher workflow more generic (argument to accept os to get full binary name, all test to do in bencher bin, speedometer, dromeo) or at least use composable github action.

Yeah that's probably the way to go, I'm just naively hacking it out to see if the workflow makes sense or not.

2024-12-24 04:01 UTC, dklassic commented on .github/workflows/bencher.yml
> +        run: echo "SERVO_BINARY_PATH=target/${{ inputs.profile }}/servo/servoshell-default-unsigned.hap" >> $GITHUB_ENV
Not quite happy about this part with tons of platform hardcoded setup, while we can definitely just pass binary path as input, still doesn't quite solve the complication of passing whether the Open Harmony artifact is signed or not.

2024-12-24 07:23 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-24 07:43 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-24 07:47 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-24 10:47 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-24 11:21 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-24 13:04 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-24 13:48 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-24 13:58 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-25 02:39 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-25 02:41 UTC, dklassic commented
So I've tested a full run with additional production profile and the duration is actually the same as a release profile only, because ultimately the bottleneck is WPT tests and production profile actually runs pretty fast.

I think we can just do everything all at once for each commit.

2024-12-25 03:06 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-25 03:17 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-25 03:19 UTC, servo-wpt-sync commented
🛠 These changes could not be applied onto the latest upstream WPT. Servo's copy of the Web Platform Tests may be out of sync.

2024-12-25 20:00 UTC, mrobinson commented
@dklassic Please squash and rebase before merging. Each commit is a line in the final commit message, so 60 commits will be quite long.

2025-01-03 05:04 UTC, dklassic commented
@jschwe just pinging to making sure this PR is not lost in all the moving parts. Feels like we should get it running soon and start tracking the numbers if there’s no other complications.

2025-01-06 16:23 UTC, wusyong approved these changes
LGTM and I think we should start tracking the size if possible.
If no one disagrees, I'll merge this later.

2025-01-06 16:30 UTC, sagudev commented on python/servo/try_parser.py
> +                words.extend(["lint"])
I think this will cause prod builds for every platform to be run on MQ (even though we skip bencher reports there). I think we should pack all perf into perf and/or prod-perf labels that would get expended to all these. Then on pushes to main add perf + prod-perf in addition to full.

2025-01-06 20:34 UTC, sagudev commented on python/servo/try_parser.py
> +                              },
All changed expectations can now be removed as they are not part of full.

2025-01-07 10:29 UTC, mrobinson requested changes

2025-01-07 10:29 UTC, mrobinson commented on python/servo/try_parser.py
> +        return JobConfig("Linux prod perf", Workflow.LINUX, bencher=True, profile="production")
"prod perf" is very cryptic. I think instead of adding more custom names, we should simply allow the caller to add more clarification. For instance: "linux +production +bencher" In addition, the job names should be printed with a similar kind of clarity. The text of the job in the GitHub interface should look like this "Linux (Bencher, Production)" so it's clear that these are modifiers to the "Linux" job.

2025-01-07 10:33 UTC, sagudev commented on python/servo/try_parser.py
> +        return JobConfig("Linux prod perf", Workflow.LINUX, bencher=True, profile="production")
Initial try_parser had support for configuring job options, but it was complicated (and not really useful). I suggest we use this syntax: `preset+modifier1+modifier2` to keep modifiers local on job (preset).

2025-01-08 04:53 UTC, dklassic commented
![image](https://github.com/user-attachments/assets/a69bc466-631e-48ab-96aa-11e53149ecca)

https://github.com/dklassic/servo/actions/runs/12664277375

Added workflow setup to be shown on the job name, should look way clearer what each workflow is doing now.

2025-01-08 10:33 UTC, sagudev commented on python/servo/try_parser.py
> +        return JobConfig("Linux (Production, Bencher)", Workflow.LINUX, bencher=True, profile="production")
Why do we need to write `(Production, Bencher)` now that we could just reuse modifier code?

2025-01-08 10:54 UTC, dklassic commented on python/servo/try_parser.py
> +        return JobConfig("Linux (Production, Bencher)", Workflow.LINUX, bencher=True, profile="production")
Actually it's just semi-handwritten atm because I can't figure out some complications earlier, but it suddenly struck me that I'm just overthinking some issue, I'll rework the modifier workflow.

2025-01-08 11:28 UTC, dklassic commented on python/servo/try_parser.py
> +        config.unit_tests = False
I'm not particularly happy with this way of setting up when to ignore unit tests,  not sure if there's a better way.

2025-01-08 15:54 UTC, sagudev commented on python/servo/try_parser.py
> +        config.unit_tests = False
Just thinking out loud, but unit-tests should probably be modifier too, because that's what it does.

2025-01-08 15:56 UTC, dklassic commented on python/servo/try_parser.py
> +        config.unit_tests = False
That does makes sense, I'll try setting it up and see how the ergonomic goes.

2025-01-08 16:17 UTC, dklassic commented on python/servo/try_parser.py
> +        config.unit_tests = False
I think making unit tests a modifier makes actual sense, just need some rewriting on several tests and workflows.

2025-01-08 18:33 UTC, dklassic commented
https://github.com/dklassic/servo/actions/runs/12675323101

Okay I think I got it all ready.

2025-01-10 05:34 UTC, dklassic commented
@sagudev do you mind see if there's any other improvements that can be made?

2025-01-10 05:58 UTC, jschwe commented on .github/workflows/bencher.yml
> +        if: ${{ inputs.stripped-file-size == true }}
Do we need this additional input option? Couldn't just check if `profile == production`?

2025-01-10 06:02 UTC, jschwe commented on .github/workflows/linux.yml
> +      dromaeo: ${{ inputs.profile == 'release' }}
Couldn't speedometer and dromaeo be `release` or production?

2025-01-10 06:03 UTC, jschwe approved these changes

2025-01-10 06:07 UTC, dklassic commented on .github/workflows/bencher.yml
> +        if: ${{ inputs.stripped-file-size == true }}
For ohos binaries, stripping them with llvm directly doesn’t seem to work atm.

2025-01-10 06:09 UTC, dklassic commented on .github/workflows/linux.yml
> +      dromaeo: ${{ inputs.profile == 'release' }}
That depends on whether we want to track the speedometer and dromaeo results for all platforms or not, which would also result in additional complications as bencher workflow currently all ran on Ubuntu.

2025-01-10 06:12 UTC, dklassic commented on .github/workflows/linux.yml
> +      dromaeo: ${{ inputs.profile == 'release' }}
I guess we can track the scores for production profile as well, not sure if warranted atm though.

2025-01-10 06:39 UTC, jschwe commented on .github/workflows/bencher.yml
> +        if: ${{ inputs.stripped-file-size == true }}
What kind of errors are you encountering? I've been using the standard llvm installed on my system to strip libservoshell.so without problems.

2025-01-10 06:43 UTC, dklassic commented on .github/workflows/bencher.yml
> +        if: ${{ inputs.stripped-file-size == true }}
I suppose I'm doing it wrongly then, here's the error:

https://github.com/dklassic/servo/actions/runs/12481534299/job/34834716773#step:13:21

2025-01-10 07:01 UTC, jschwe commented on .github/workflows/bencher.yml
> +        if: ${{ inputs.stripped-file-size == true }}
Ah, We shouldn't be measuring the .hap file, we should measure the `libservoshell.so` dynamic library, since that is what we develop here. The .hap is kind of like an apk file on android. For android I would recommend the same, measure `libservoshell.so`, since that is where our code is.

2025-01-12 19:49 UTC, dklassic commented on .github/workflows/bencher.yml
> +        if: ${{ inputs.stripped-file-size == true }}
Android and OpenHarmony now have their libservoshell.so file size properly tracked, meanwhile stripped file size will be automatically measured when profile is set to Production.

I think we should fix #34564 and add `android-production-bencher` to `try_parser.py` later as this PR has been dragging on a while now.

2025-01-17 04:43 UTC, wusyong commented
This seems to be the [passed run](https://github.com/dklassic/servo/actions/runs/12736632503). Again, I'll merge this weekend if there's no more comment.

2025-01-20 08:44 UTC, wusyong commented on python/servo/try_parser.py
> +        return JobConfig("Linux prod perf", Workflow.LINUX, bencher=True, profile="production")
@mrobinson looks like merge is blocked by this request. Could you review it?

2025-01-20 08:52 UTC, mrobinson approved these changes

2025-01-20 08:52 UTC, mrobinson commented on .github/workflows/bencher.yml
> +    # keep this in sync with testbed
```suggestion
    # This needs to be kept in sync with the `--testbed` argument sent to bencher.
```

2025-01-20 10:14 UTC, merged

2025-01-21 02:10 UTC, dklassic commented
https://github.com/servo/servo/actions/runs/12877943392/job/35903615621

At the moment `ohos.yml` doesn't seem to properly setup `signed` output resulting in bencher step not able to retrieve the proper file name.

In the meantime I came across this [discussion](https://github.com/orgs/community/discussions/26639) pointing out that matrix jobs will overwrite each other's output so this way of setting output is technically wrong. We'll need some improvements here.

2025-01-21 02:20 UTC, jschwe commented
> At the moment ohos.yml doesn't seem to properly setup signed output resulting in bencher step not able to retrieve the proper file name.

@dklassic Didn't we say that android / ohos should measure the size of the `.so` file? Not sure why the `signed` hap would be necessary here.

2025-01-21 04:58 UTC, dklassic commented
> @dklassic Didn't we say that android / ohos should measure the size of the `.so` file? Not sure why the `signed` hap would be necessary here.

We are measuring the `.so` file for android/ohos now.

During the build, the only uploaded artifact from build step is the .hap file, similarly in Android the .apk file. Since Linux/macOS also upload .tar.gz artifact it's pretty natural to just extract the files during bencher step.

> Do we not set unique artifact names for each job?

Yes, but we also decided if the file is signed or not during the build step which leads to different artifact names that have to be passed to the bencher step. I guess this isn't that big of an issue since with our current setup we either sign them all or not, it'll become an actual issue if we have signed/unsigned mix and match with the matrix.

We just need to fix the problem with improper output step leading to wrong artifact name being passed for now.

2025-01-22 12:04 UTC, mukilan commented
@dklassic , looks like this change has broken the nightly builds: https://github.com/servo/servo/actions/runs/12901786511

The error is 

```
The workflow is not valid. servo/servo/.github/workflows/android.yml@67aaa87885057f424655daf2c6728f9fb8440199 (Line: 151, Col: 3): Error calling workflow 'servo/servo/.github/workflows/bencher.yml@67aaa87885057f424655daf2c6728f9fb8440199'. The workflow is requesting 'checks: write, pull-requests: write', but is only allowed 'checks: none, pull-requests: none'.
```

Do you have any idea what the fix is? Should we just revert this change?

2025-01-22 12:45 UTC, dklassic commented
> @dklassic , looks like this change has broken the nightly builds: https://github.com/servo/servo/actions/runs/12901786511
> 
> The error is
> 
> ```
> The workflow is not valid. servo/servo/.github/workflows/android.yml@67aaa87885057f424655daf2c6728f9fb8440199 (Line: 151, Col: 3): Error calling workflow 'servo/servo/.github/workflows/bencher.yml@67aaa87885057f424655daf2c6728f9fb8440199'. The workflow is requesting 'checks: write, pull-requests: write', but is only allowed 'checks: none, pull-requests: none'.
> ```
> 
> Do you have any idea what the fix is? Should we just revert this change?

After some tests, seems like [matrix used in android/ohos workflow](https://github.com/servo/servo/blob/e74539404467cc31c03f52a419371258235a1d69/.github/workflows/ohos.yml#L138) will cause GitHub action to attempt to run that workflow somehow even if the condition isn't satisfied. I have yet found a simple solution to this so we could either:

- Revert the work
- Remove bencher step from ohos and android workflow
- Move each matrix in ohos and android workflow into a separate job

Maybe @sagudev had some experience dealing with this?

2025-01-22 12:55 UTC, sagudev commented
Hm, so what you are saying is that if and matrix are not working together as expected? I wonder if this is known github actions issue. Maybe we can bypass this by making matrix on condition, so if condition is false there would be empty matrix (and hopefully no job run) if not we can flatten the matrix.

2025-01-22 12:58 UTC, sagudev commented
I suspect that our if condition is not strong enough, but giving nightly workflow more permissions also sounds OK.

2025-01-22 13:03 UTC, dklassic commented
All windows/macos/linux/android/ohos bencher step use the same if condition and the issue only occurs when I left android or ohos bencher step uncommented. So yeah I think matrix and if doesn't work together as expected in this case.

I also concur that giving nightly workflow more permission seems like the best (cleanest) workaround.

2025-01-22 15:09 UTC, dklassic commented
@mukilan Upon further inspection, seems like the real reason is that in nightly.yml, both [android](https://github.com/servo/servo/blob/e74539404467cc31c03f52a419371258235a1d69/.github/workflows/nightly.yml#L126)/[ohos](https://github.com/servo/servo/blob/e74539404467cc31c03f52a419371258235a1d69/.github/workflows/nightly.yml#L142) ran with explicit permissions. Seems like when explicitly assigning the permissions, the it'll consequently check all related workflows to be limited within the scope, thus giving out this error message.

[Same error will happen on Linux](https://github.com/dklassic/servo/actions/runs/12911014440) if I explicitly limit the scope for upload-linux job.

2025-01-22 15:30 UTC, mukilan commented
Do we need the 'permissions:' block in bencher.yml at all? Since other workflows that call bencher.yml don't explicity elevate their permission, it seems they only work because they already run with default permissions that happened to be compatible with bencher.yml's required permissions.

I think the ideally our repository settings need to be changed so that the default permissions [are restrictive rather than permissive](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) and have each top-workflow declare the permissions it requires. Giving nightly permissions doesn't seem ideal to me (but is fine as a termporary workaround).

2025-01-22 15:42 UTC, dklassic commented
In that case what we should do is probably move the workflow call of `bencher.yml` to `dispatch-workflow.yml` instead, so that the bencher job won't be coupled with the build job resulting in the mismatch of permission scope during nightly release.

2025-01-22 16:03 UTC, dklassic commented
> I would suggest trying with 'permissions:' removed from bencher.yml before adding permissions to nightly.

I don't have the permission to test with servo's project setup, but back when I tested sagu's linux-perf PR in my fork those two permissions are required: https://github.com/servo/servo/pull/33261#issuecomment-2449003867

2025-01-22 16:06 UTC, sagudev commented
Actually default permissions are restrictive, so we relax them in bencher workflow using `permissions`.

2025-01-22 16:14 UTC, mukilan commented
@sagudev: are you referring to the default permissions of the servo repository? If so, the defaults are [permissive  according to the settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions):

![image](https://github.com/user-attachments/assets/cb380eb5-919e-4a76-a6fe-eaf6802899ee)

2025-01-22 16:31 UTC, mukilan commented
> Actually default permissions are restrictive, so we relax them in bencher workflow using permissions.

The issue here is the nestedness of the workflow call to `bencher`. The original error was because Github's static analysis found that nightly.yml was calling bencher.yml but the latter required permissions that are more relaxed than the former (for android & ohos). If it were possible for bencher.yml to relax the permissions of the parent workflow, then that would defeat the usefulness of the validation that Github is enforcing, so I suspect the only time bencher.yml can elevate permissions is when it runs as the top-level workflow.

I think in the long run we should move to default-restrictive permissions and then have the top-level workflows declare the required permissions. The permissions in bencher.yml only seem to serve as machine-checked documentation, but as it is causing issues with nested calls that are not possible at runtime, it seems like we have to either pass additional permissions in top-level workflows (that are not needed, so that is bad) or not declare them in nested workflows.

2025-01-22 20:10 UTC, Loirooriol commented
Should it just be reverted, while the permissions are figured out?

2025-01-23 03:43 UTC, dklassic commented
> Should it just be reverted, while the permissions are figured out?

Sure, will have to revert #35109 alongside.

Just note that someone with the project permission has to resolve this issue as I don’t have servo CI access to conduct related tests.