WIP implement localized quotes
servo/servo pull request #34770
Opened 2024-12-24 05:25 UTC by xiaochengh

Implement quotes. Generate correct quote characters that matches the locale. It's done by enabling the `quotes.css` UA style sheet.

Note: Quote depth calculation is not supported yet.

Problems: using a UA sheet for default quote characters doesn't seem like the right approach because:
- It doesn't support the `auto` value
- It matches every element and therefore doesn't allow author-defined values to properly inherit

The above issues might be mitigated if we let the UA sheet set an internal property instead of the `quote` property directly. Nevertheless, it still matches every element and therefore may cause a performance hit.

The proper approach seem to be adding quotes support to the icu crate. Should we do that instead?

---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2025-01-13 07:54 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-14 08:11 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-14 08:18 UTC, servo-wpt-sync commented
✍ Updated existing upstream WPT pull request (web-platform-tests/wpt#49835) title and body.

2025-01-14 08:20 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-14 09:52 UTC, servo-wpt-sync commented
✍ Updated existing upstream WPT pull request (web-platform-tests/wpt#49835) title and body.

2025-01-14 09:52 UTC, xiaochengh commented on components/layout_2020/quotes.rs
I feel like this file shouldn't be here. Any suggestions for a better location?

2025-01-14 09:55 UTC, xiaochengh commented on tests/wpt/tests/css/css-content/quotes-slot-scoping-ref.html
We used to have a false-pass here, since the ref file depends on `quotes`. So I'm making it simpler and depend on less stuff.

2025-01-14 10:00 UTC, servo-wpt-sync commented
✍ Updated existing upstream WPT pull request (web-platform-tests/wpt#49835) title and body.

2025-01-14 10:23 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-15 10:20 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-15 10:46 UTC, xiaochengh commented
@Loirooriol Could you take a look and help me trigger the WPT try run? Thanks!

2025-01-15 16:39 UTC, Loirooriol requested changes

2025-01-15 16:39 UTC, Loirooriol commented on components/layout_2020/dom_traversal.rs
> +                                let quotes = crate::quotes::quotes_for_lang(lang.0.as_ref(), depth);
I would add `use crate::quotes::quotes_for_lang;` at the top of the file and just `quotes_for_lang` here.

2025-01-15 16:39 UTC, Loirooriol commented on components/layout_2020/quotes.rs
I will defer to @mrobinson

2025-01-15 16:39 UTC, Loirooriol commented on components/script/dom/element.rs
> +    }
Can be left for a follow-up, but if JS changes the attribute, then this needs to be updated.

2025-01-16 04:59 UTC, xiaochengh commented on components/layout_2020/dom_traversal.rs
> +                                        quote_pair.closing.split_at(0).1,
I'm thinking about minimizing the dependency of `quotes.rs` so that it can be easily moved to elsewhere. Putting this file in `layout_2020` doesn't look right to me. In addition, Stylo's `QuotePair` contains two `OwnedStr` and requires heap memory allocation, which I'd like to avoid.

If both look OK to you, I'll change it to Stylo's `QuotePair`.

2025-01-16 06:37 UTC, xiaochengh reviewed
Updated, PTAL.

2025-01-16 06:37 UTC, xiaochengh commented on components/layout_2020/dom_traversal.rs
> +                                let quotes = crate::quotes::quotes_for_lang(lang.0.as_ref(), depth);
Done.

2025-01-16 06:39 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-16 18:59 UTC, Loirooriol commented on components/layout_2020/dom_traversal.rs
> +                                        quote_pair.closing.split_at(0).1,
Fair enough, it's good as is.

2025-01-16 18:59 UTC, Loirooriol approved these changes

2025-01-17 07:03 UTC, xiaochengh commented
@mrobinson Could you take a look? Thanks!

2025-01-17 08:39 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-17 08:52 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-17 14:59 UTC, mrobinson requested changes
Looks good! Thank you. I have a few suggestions. Let me know if you want me to do the conversion of the HashMap values.

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/quotes.rs
> +        ("af", QuotesData(0x201c, 0x201d, 0x2018, 0x2019)),
Please use a static `OnceLock` here to avoid building this map more than once. In addition, I think we should be using real Unicode characters here instead of constantly building the quotes from components parts. This can be done eventually with an import script or I'm happy to help out here converting the data.

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/quotes.rs
> +    let maybe_loc = lang.parse::<Locale>();
Avoid abbreviating variable names that are ambiguous (loc = locale or location?). `locale` is much easier to read here.

```suggestion
    let maybe_locale = lang.parse::<Locale>();
```

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/quotes.rs
> +    let loc = maybe_loc.unwrap();
Please try to avoid calling `.unwrap()` as it introduces the possibility of a panic.

```suggestion
    let locale = match lang.parse::<Locale>() {
        Err(_) => return DEFAULT_QUOTES,
        Ok(locale) => locale,
    };
```

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/quotes.rs
> +    }
I think this can be done with map:

```suggestion
    if let Some(data) = loc.id.region.and_then(|region| quotes_data.get(format!("{lang}-{region")) {
        return data;
    }
```

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/quotes.rs
> +    }
This can use a similar pattern which will also avoid cloning strings.

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/quotes.rs
> +}
This can be removed if the table store characters.

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/dom_traversal.rs
> +                        let depth: usize = 0;
Please remove this and simply use the constant.

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/dom_traversal.rs
> +                        let quote: Option<String> = match &pseudo_element_style.get_list().quotes {
Can the type be omitted here. If so, please do that.

2025-01-17 14:59 UTC, mrobinson commented on components/layout_2020/dom_traversal.rs
> +        _ => closing.to_string(),
```suggestion
        ContentItem::OpenQuote => opening.to_string(),
        ContentItem::CloseQuote => closing.to_string(),
        _ => unreachable!("Got an unexpected ContentItem when processing quotes."),
```

2025-01-17 15:01 UTC, servo-wpt-sync commented
✍ Updated existing upstream WPT pull request (web-platform-tests/wpt#49835) title and body.

2025-01-20 10:05 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-20 10:22 UTC, xiaochengh reviewed
Thanks for reviewing!

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/dom_traversal.rs
> +        _ => closing.to_string(),
Done.

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/dom_traversal.rs
> +                        let depth: usize = 0;
Done

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/dom_traversal.rs
> +                        let quote: Option<String> = match &pseudo_element_style.get_list().quotes {
Done

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/quotes.rs
> +        ("af", QuotesData(0x201c, 0x201d, 0x2018, 0x2019)),
Done. Thanks for fixing my Rust noobie issues.

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/quotes.rs
> +    let maybe_loc = lang.parse::<Locale>();
Done

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/quotes.rs
> +    let loc = maybe_loc.unwrap();
Done

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/quotes.rs
> +    }
Done

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/quotes.rs
> +    }
Done

2025-01-20 10:22 UTC, xiaochengh commented on components/layout_2020/quotes.rs
> +}
Done

2025-01-20 10:24 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-01-20 10:33 UTC, mrobinson requested changes
Thanks for the changes. It's looking good, but just one clarification on an earlier comment.

2025-01-20 10:33 UTC, mrobinson commented on components/layout_2020/quotes.rs
> +            QuotesData('\u{201c}', '\u{201d}', '\u{2018}', '\u{2019}'),
Hrm. What I was imagining here was that this HashMap would essentially be `HashMap<&'static str, QuotePair>;` and you would convert all of the QuotesData entries in the initialization to QuotePair. I think it makes more sense to do the conversion ahead of time rather than at runtime.

2025-01-20 10:33 UTC, mrobinson commented on components/layout_2020/quotes.rs
> +type QuotesMap = HashMap<&'static str, QuotesData>;
I would just go ahead and remove this typedef as the type itself is not very complicated.

2025-02-03 07:07 UTC, xiaochengh reviewed
Thanks for the review!

Updated & sorry for the delay, just back from the CNY break.

2025-02-03 07:07 UTC, xiaochengh commented on components/layout_2020/quotes.rs
> +type QuotesMap = HashMap<&'static str, QuotesData>;
Done

2025-02-03 07:07 UTC, xiaochengh commented on components/layout_2020/quotes.rs
> +            QuotesData('\u{201c}', '\u{201d}', '\u{2018}', '\u{2019}'),
Done

2025-02-03 07:09 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-06 05:33 UTC, xiaochengh commented
@mrobinson Friendly ping...

2025-02-07 12:35 UTC, mrobinson approved these changes

2025-02-07 13:00 UTC, xiaochengh commented on Cargo.toml
> +selectors = { git = "https://github.com/servo/stylo", rev = "refs/pull/110/head" }
What's the process here? Should I wait for the next Stylo branch?

2025-02-07 13:02 UTC, Loirooriol commented on Cargo.toml
> +selectors = { git = "https://github.com/servo/stylo", rev = "refs/pull/110/head" }
Just leave `Cargo.toml` unchanged (so `branch = "2025-02-03"`) but with `Cargo.lock` pointing to the tip (8af5d515a03bfca5d19fcaa541783327673a951e)

See https://github.com/servo/servo/pull/35352/files for reference

2025-02-07 13:33 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-07 13:36 UTC, xiaochengh commented on Cargo.toml
> +selectors = { git = "https://github.com/servo/stylo", rev = "refs/pull/110/head" }
Done, thanks!

2025-02-07 13:37 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-10 09:25 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-10 11:05 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-10 11:37 UTC, Loirooriol requested changes
Try not to regress tests on WebKit: https://wpt.fyi/results/css/css-content?diff&filter=ADC&run_id=5180619544068096&run_id=5103582259183616

2025-02-10 12:10 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-10 12:10 UTC, xiaochengh commented
> Try not to regress tests on WebKit: https://wpt.fyi/results/css/css-content?diff&filter=ADC&run_id=5180619544068096&run_id=5103582259183616

`quotes-016.html` is caused by a trivial mistake and has been fixed.

However, the other one seems to be due to continuous shaping between `::before`/`::after` and the DOM text.

In summary, we need:
1. Add CJK system fonts to the build bot. I don't think it's a good idea to make every CJK-related WPT switch to a web font...
2. Continuous shaping support. Currently Servo doesn't support shaping across element boundaries. But this can be left as another issue.

2025-02-10 14:00 UTC, Loirooriol commented
Still some regressions:
- Blink: https://wpt.fyi/results/css/css-content/quotes-034.html?diff&filter=ADC&run_id=5140438011084800&run_id=5184435219857408
- WebKit: https://wpt.fyi/results/css/css-content?diff&filter=ADC&run_id=5075969444675584&run_id=5146180214587392

> Add CJK system fonts to the build bot. I don't think it's a good idea to make every CJK-related WPT switch to a web font...

https://web-platform-tests.org/writing-tests/general-guidelines.html#be-cross-platform says "`@font-face` should be used", but yeah I'm fine with adding CJK system fonts if that's easier.

2025-02-12 21:57 UTC, Loirooriol commented
I would revert the test changes and just mark `quotes-034.html` as failing. It also fails on Gecko and WebKit anyways.

2025-02-20 08:46 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-21 13:14 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-21 14:50 UTC, xiaochengh commented
With noto-cjk installed, all other tests have passed except quotes-034.html, which is still rendering the quote as tofu.
And somehow in the ref file, the tofu is continuously shaped with the letter "j" following it; whereas in the test file they are disconnected... 🥲 

| Expected screenshot | Actual Screenshot |
| ----------- | ----------- |
| ![quotes-034-expected](https://github.com/user-attachments/assets/5e862822-fe15-4a23-a125-15a6e41c521c) | ![quotes-034-actual](https://github.com/user-attachments/assets/3b09e655-0a4c-4517-8040-e7795f87dfac) |

2025-02-22 07:43 UTC, xiaochengh commented
How about marking `quotes-034.html` as intermittent? And how to do that?

I don't want to mark it as failing, as it might pass in some other environments (like in my local env).

2025-02-22 09:48 UTC, mrobinson commented
> I don't want to mark it as failing, as it might pass in some other environments (like in my local env).

Unfortunately we have a bunch of tests like that. Marking it as intermittent will hide the failure if it ever starts failing on the CI. Would it be possible to start improving our testing environment/setup to ensure more consistent runs when tests are run locally? That is the strategy that WebKit takes, I think.

2025-02-22 15:07 UTC, xiaochengh commented
All right. Let me dig deeper to see why the JP quotes are still tofu after installing Noto CJK.

2025-02-22 16:48 UTC, mrobinson commented
> All right. Let me dig deeper to see why the JP quotes are still tofu after installing Noto CJK.

Oh! I would also say that if the test only fails locally and works as expected on the CI, it shouldn't block this change. I only meant my comment in the general sense. We have a larger issue with tests failing between different systems.

2025-02-23 05:17 UTC, xiaochengh commented
This is not a high priority change. Fixing CI might be more valuable, especially for our team.

2025-02-23 23:13 UTC, Loirooriol commented
CI getting different results than locally is not a problem specific to this. Also, wpt.fyi considers the test to fail on Firefox and Safari. In fact https://searchfox.org/mozilla-central/source/testing/web-platform/meta/css/css-content/quotes-034.html.ini only expects it to fail on linux, hinting that it's dependent on the environment.

So just mark the test as failing for now and leave investigations for later. Or otherwise https://github.com/servo/stylo/pull/110 should be reverted, since there is no point in accepting the property if it's not going to do anything.

2025-02-24 05:57 UTC, xiaochengh commented
IIUC, if we mark it fail, some developers will get stable unexpected passes locally, and they may update the expectation. Is that still OK?

2025-02-25 04:44 UTC, xiaochengh commented
OK then, I'll mark it failing. Also filed #35644 to track this.

2025-02-25 06:02 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-25 13:49 UTC, Loirooriol approved these changes

2025-02-25 13:49 UTC, Loirooriol commented on tests/wpt/meta/css/css-content/inheritance.html.ini
> +    expected: PASS
I don't think it's needed to annotate the passes, since passing is the default.

2025-02-25 13:49 UTC, Loirooriol commented on tests/wpt/meta/css/css-content/quotes-slot-scoping.html.ini
> +  expected: FAIL
Nit: add newline at the end of the file

2025-02-27 15:23 UTC, xiaochengh commented
@Loirooriol Done. I wish I can have more time coding...

2025-02-27 15:25 UTC, servo-wpt-sync commented
📝 Transplanted new upstreamable changes to existing upstream WPT pull request (web-platform-tests/wpt#49835).

2025-02-27 16:29 UTC, merged