Consider shadow dom when dispatching events
servo/servo pull request #34788
Opened 2024-12-29 00:35 UTC by simonwuelker

This essentially rewrites to event dispatching code to follow the spec more closely. The previous implementation completely ignored potential shadow roots in the DOM.

These changes  will allow us to implement the `composed` flag on events in the future.

There is a new TIMEOUT (previously FAIL) in `dom/events/event-global.html`. The test tries to bubble an event over a shadow boundary. This doesn't work anymore, as the `composed` flag is not supported yet.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes are part of https://github.com/servo/servo/issues/31149 (events do not yet pass shadow roots, but the infrastructure is in place)
- [X] There are tests for these changes (covered by WPT)

2025-01-06 16:43 UTC, mrobinson requested changes
Great change! The thorough specification text made this a lot easier to review. I just have one question and a few visibility nits.

2025-01-06 16:43 UTC, mrobinson commented on components/script/dom/event.rs
> +                .find(|segment| segment.shadow_adjusted_target.is_none())
The spec text above says to find the "the last struct in event’s path whose shadow-adjusted target is non-null" but the find call here seems to be reversed as it's finding the first segment that has `segment.shadow_adjusted_target.is_none()`.

2025-01-06 16:43 UTC, mrobinson commented on components/script/dom/eventtarget.rs
> +    pub fn get_the_parent(&self, event: &Event) -> Option<DomRoot<EventTarget>> {
```suggestion
    pub(crate) fn get_the_parent(&self, event: &Event) -> Option<DomRoot<EventTarget>> {
```

2025-01-06 16:43 UTC, mrobinson commented on components/script/dom/eventtarget.rs
> +    pub fn retarget(&self, b: &Self) -> DomRoot<EventTarget> {
```suggestion
    pub(crate) fn retarget(&self, b: &Self) -> DomRoot<EventTarget> {
```

2025-01-06 19:06 UTC, simonwuelker commented on components/script/dom/event.rs
> +                .find(|segment| segment.shadow_adjusted_target.is_none())
Good find!

2025-01-07 16:27 UTC, mrobinson approved these changes
Thanks! Looks like the is just a simple build failure now due to a method rename.

2025-01-07 20:33 UTC, simonwuelker commented
Looks like https://github.com/servo/servo/pull/34788#discussion_r1904378713 caused three more tests to pass

2025-01-07 21:54 UTC, merged