Document's current script should not be updated when executing script elements inside shadow trees
servo/servo pull request #34787
Opened 2024-12-28 23:07 UTC by willypuzzle

- [x] Added check if node is in shadow tree
- [x] Added flag removing when node is removed from subtree
- [x] Removed related `ini` file 

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34738 

- [x] These changes do not require tests because they just exist

2024-12-28 23:33 UTC, simonwuelker requested changes

2024-12-28 23:33 UTC, simonwuelker commented on components/script/dom/htmlscriptelement.rs
> +                if self.as_parent().as_parent().as_parent().is_in_shadow_tree() {
You can use `self.upcast::<Node>()` instead of repeatedly calling `as_parent`

2024-12-28 23:34 UTC, simonwuelker commented
>  These changes do not require tests because they just exist

(These changes *do* require tests, but this functionality is already tested as part of the WPT suite. )

2024-12-29 00:48 UTC, simonwuelker approved these changes
Thanks!

2024-12-29 01:23 UTC, simonwuelker commented
Removing this from the merge queue as I'm having second thoughts about the changes to `IS_IN_SHADOW_TREE` (sorry about that).

With these changes, when an element is removed from the tree all of its descendants will lose the `IS_IN_SHADOW_TREE` flag. But what if the shadow tree is part of the removed subtree?

2024-12-29 01:46 UTC, jdm commented
Hmm, yeah. So removing C should remove the flag, but removing B should not. Maybe we need a separate traversal in complete_remove_subtree that first checks whether the root is a shadow host and clears the flag on the root and its children if not?

2024-12-29 07:38 UTC, simonwuelker commented
> Hmm, yeah. So removing C should remove the flag, but removing B should not. Maybe we need a separate traversal in complete_remove_subtree that first checks whether the root is a shadow host and clears the flag on the root and its children if not?

Alternatively, we could remove `IS_IN_SHADOW_TREE` and keep track of the number of shadow roots that a specific node has. (a nonzero count would be equivalent to `IS_IN_SHADOW_TREE`).
Then, the disconnection code could look like this:

```rust
let mut n_disconnected_shadow_roots = former_parent.number_of_shadow_roots();
if former_parent.is_shadow_root() {
    n_disconnected_shadow_roots += 1;
}

for node in former_child.traverse_preorder() {
    // Unset CONNECTED, IS_IN_DOC flags etc...
    node.decrement_shadow_root_count(n_disconnected_shadow_roots);
}
```

That would allow us to do this in one single traversal, at the cost of some extra memory per node (though a `u16` is likely enough)

2024-12-29 12:49 UTC, willypuzzle commented
@jdm @simonwuelker what should I do at this point?

2024-12-29 16:46 UTC, simonwuelker commented
> @jdm @simonwuelker what should I do at this point?

This problem is also causing issues elsewhere (https://github.com/servo/servo/issues/34740) and is not directly related to this PR - 
I'll prepare a PR with the approach I outlined above, and then we can try and merge that first.

2025-01-04 00:45 UTC, simonwuelker commented
This can merge once the formatting is fixed

2025-01-04 14:21 UTC, merged