Add fetch blob range header
servo/servo pull request #34797
Opened 2024-12-30 13:10 UTC by rayguo17

Added Content Range Header for Partial blob request.
Address the blob range off by one issue

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34771 (GitHub issue number if applicable)

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

2024-12-30 13:24 UTC, simonwuelker commented
You need to sign your commits (add `-s` to `git commit`), see https://book.servo.org/contributing.html#pull-request-checklist for more informatoin

2024-12-30 13:34 UTC, rayguo17 commented
My bad, i just redo the commit, now it should have sign mark on it.

2025-01-05 08:04 UTC, sagudev commented
Hm, after reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests I think `range_request_blob_url.html` test is wrong, we can just remove it as https://github.com/servo/servo/blob/main/tests/wpt/tests/fetch/range/blob.any.js tests same functionality.

2025-01-07 06:34 UTC, jdm commented
Agreed!

2025-01-07 06:34 UTC, rayguo17 commented
Maybe i can just delete the `range_request_blob_url.html` and push again?

> Hm, after reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests I think `range_request_blob_url.html` test is wrong, we can just remove it as https://github.com/servo/servo/blob/main/tests/wpt/tests/fetch/range/blob.any.js tests same functionality.

2025-01-07 07:42 UTC, sagudev commented on build-profile.json5
I think this file should not be commited, maybe we should add it to gitignore. cc @jschwe.

2025-01-07 10:06 UTC, jschwe commented on build-profile.json5
Yes, please remove build-profile.json5 @rayguo17. 

Note: We do have a `build-profile.json5` file in the support/openharmony folder that needs to be committed, and having this file here has no effect at all so adding it to .gitignore also doesn't make sense to me. 

Please also remove `signing-configs.json` - this file probably should be added to `.gitignore`, since it is the recommended filename for the OpenHarmony signing configuration (from our book).

2025-01-07 10:26 UTC, rayguo17 commented on build-profile.json5
I mistakenly introduced this two files, and i have already deleted it in my latest commit.

2025-01-08 05:14 UTC, jdm commented
The expected results for `/xhr/blob-range.any.html` and `/xhr/blob-range.any.worker.html` also need updating!

2025-01-10 07:40 UTC, jdm requested changes
Looking good!

2025-01-10 07:40 UTC, jdm commented on components/net/filemanager_thread.rs
> +                    )
```suggestion
                    ContentRange::bytes(range.start as u64..range.end as u64, buf.size).ok()
```

2025-01-10 07:40 UTC, jdm commented on components/net/filemanager_thread.rs
> +                    None,
We should be able to construct a ContentRange argument from `range` and `metadata.size`, right? To answer your question from the issue, the MetaDataOnly variant is constructed when interacting with `<input type=file>`—they refer to files that exist in the embedder's environment that we do not need to store in memory.

2025-01-10 07:40 UTC, jdm commented on components/shared/net/filemanager_thread.rs
> +    pub fn to_abs_blob_range(&self, size: usize) -> Range<usize> {
```suggestion
    // Per <https://fetch.spec.whatwg.org/#concept-scheme-fetch> step 3.blob.14.8:
    // "A range header denotes an inclusive byte range, while the slice blob algorithm input range does not.
    // To use the slice blob algorithm, we have to increment rangeEnd."
    fn to_abs_blob_range(&self, size: usize) -> Range<usize> {
```

2025-01-13 09:11 UTC, rayguo17 commented on components/net/filemanager_thread.rs
> +                    None,
Yes, but when i try to test this path by interacting with `<input type=file>` i discovered a bug: https://github.com/servo/servo/issues/34814. Anyway I managed to add the contentRange support for file metadata as well in my latest commit, just need to wait for input file function to be recovered so that we can test it out.

2025-01-13 23:25 UTC, jdm approved these changes
Thank you!

2025-01-14 00:54 UTC, merged